### ISSUE TITLE
importing fusebox module should not have visible side effect

### ISSUE THREAD

**Issue by bigdrum** [fuse-box/fuse-box#1000]
This commit introduced an output to stdout when the module is being imported:

https://github.com/fuse-box/fuse-box/commit/5d4e57a79557561d975fd2f89c4bdf54f0c4a7ab

This is very surprising as we are using fusebox in a custom build script and the string is always printed even if Fusebox.init is not called (of course we can work around it by delayed importing the module, but probably it is not a good practice to output to stdout as the module is being imported).

I guess the better place to put this would be inside Fusebox.init.

**Comment by nchanged** [comment]
fair enough ;-)
