### ISSUE TITLE
PNPM Support

### ISSUE THREAD

**Issue by activestylus** [fuse-box/fuse-box#1006]
I see that you guys have integrated this with Yarn. Any chance that it could also work with this?

https://github.com/pnpm/pnpm

Not only is it fast as hell, but the aliasing strategy saves literally hundreds of MB on my dev machine.

**Comment by nchanged** [comment]
Hi! I think it should work, if it works with nodejs it will be bundled accordingly. Have you tried it yourself?

**Comment by nchanged** [comment]
closing this for now, please feel free to re-open.
