### ISSUE TITLE
Aliases ending in '/' not working when using quantum

### ISSUE THREAD

**Issue by xaviergonz** [fuse-box/fuse-box#1007]
I have an alias that points to my source folder like this
```
homeDir: : 'src',
alias: {
  'src': '~/',
}
```
and therefore I use imports such as
```import * as en from 'src/translations/en'```

All that works properly when not using quantum, but when using quantum (uglify: false, treeshake: false), I get the following generated code for the imports, which resolves to undefined:
```var en_2 = $fsx.r('~//translations/en');```

while the module definition generated code is like this:
```
// default/translations/en.js
$fsx.f[303] = function(module,exports){
```

Am I doing something wrong?

**Comment by xaviergonz** [comment]
I just changed 'src': '~/' to 'src': '~' and it started working, so maybe it is a matter of removing the trailing / somewhere

**Comment by xaviergonz** [comment]
Alternatively I guess a more resilient fix would be to normalize module names by deduping possible double slashes (just in case it not only happens in the beginning)

**Comment by nchanged** [comment]
Yep that will be in the alias logic, we will fix it )
