### ISSUE TITLE
CSS Modules issue with fuse-box 3

### ISSUE THREAD

**Issue by Fjandin** [fuse-box/fuse-box#1008]
I'm using fusebox with css modules + postcss (postcss-next)

I'm having an issue after updating to fuse-box 3.

Everything seems to be working fine until i edit any file that is not a css file.

Example:
I'm importing my styles as `import styles from './styles.css';`
As soon as i edit any non css file `styles` is undefined. If i afterwards edit any css file it works again.

my fuse.js
```
const alias = fs.readdirSync('./app').reduce((a, b) => ({...a, [b]: `~/${b}`}), {});
    alias.config = '~/config.js';
    fuse = FuseBox.init({
        alias,
        useTypescriptCompiler : true,
        target: 'browser',
        homeDir: 'app/',
        output: 'build/$name-$hash.js',
        hash: isProduction,
        tsConfig: './tsconfig.json',
        sourceMaps: !isProduction,
        plugins: [
            EnvPlugin({NODE_ENV: isProduction ? 'production' : 'development'}),
            ImageBase64Plugin({useDefault: true}),
            // CopyPlugin({useDefault: true, dest: 'assets', files: ['*.jpg']}),
            [
                CSSModules({root: './app'}),
                PostCSSPlugin([require('postcss-cssnext')], {sourceMaps: !isProduction}),
                CSSResourcePlugin({dist: './build/assets', resolve: (f) => `/assets/${f}`}),
                !isProduction ? CSSPlugin() : CSSPlugin({
                    group: 'app.css',
                    inject: (file) => `/${file}`,
                    outFile: `build/app.css`
                })
            ],
            WebIndexPlugin({
                template: 'app/index.html',
                target: 'index.html'
            }),
            isProduction && QuantumPlugin({
                treeshake: true,
                uglify: true
            })
        ]
    });
    app = fuse.bundle('app').instructions('> index.ts');
```

**Comment by nchanged** [comment]
Hi, I think that CSSModules plugin should come before the CSSPlugin because it tranformes the content into an object

**Comment by Fjandin** [comment]
I did put the CSSPlugin last. CSSModules, PostCSSPlugin and lastly CSSPlugin (i included my config in previous post).
It does work fine until i edit any non css file.

**Comment by nchanged** [comment]
No you got me wrong CSSModules should come before CSSPlugin not POSTCss
So postcss, css modules, css plugin

**Comment by Fjandin** [comment]
Tried that. Same issue. I have made a loom to show what happens:
https://www.useloom.com/share/433b94267cbc49c380118f2283368aa7

**Comment by nchanged** [comment]
Aha I see I think that an easy one, I will fix it tomorrow (hopefully) I forgot to update one important part in that module, could you share that repo?

**Comment by Fjandin** [comment]
https://github.com/Fjandin/fuse-box-app

**Comment by nchanged** [comment]
I will reference the fix of course )

**Comment by Fjandin** [comment]
Just tested with `3.1.0-next.2` and everything works fine now. Thanks man:)

**Comment by nchanged** [comment]
you're welcome =)
