### ISSUE TITLE
WebIndex does not update the bundle hashes on watch mode

### ISSUE THREAD

**Issue by xaviergonz** [fuse-box/fuse-box#1013]
When using hash: true and the webindex plugin, then the new bundles with a new hash get regenerated, but the webindex $bundles does not update, thus making a page reload load the old bundle rather than the updated one.

I'm using this as output: 
```output: `${outFolder}/$name-$hash.js`,```

and two bundles:
```
fuse.bundle("vendor").instructions("~ index.tsx").watch();
fuse.bundle("app").instructions("> [index.tsx]").watch();
```

**Comment by nchanged** [comment]
HM, that’s true webindex copies the html file only once ...

**Comment by nchanged** [comment]
`fuse-box@3.1.0-next.1`
