### ISSUE TITLE
sourcemaps not being inlined by default, inline: true does nothing

### ISSUE THREAD

**Issue by xaviergonz** [fuse-box/fuse-box#1015]
I'm using this in a dev build, not using quantum

```
    sourceMaps: {
      project: true,
      vendor: false,
      inline:true,
    },
```

but nevertheless the sourcemaps are generated as an app.map.js and the sourcemaps point to that url

**Comment by nchanged** [comment]
Inline means that the sources will be in the sourcemaps file, they can’t be in a JavaScript file 

You can alternatively serve them tho

**Comment by xaviergonz** [comment]
ahh ok, for some reason I thought it meant inlined inside the js files as a data url in base64
