### ISSUE TITLE
Start dev server on ssl

### ISSUE THREAD

**Issue by KnisterPeter** [fuse-box/fuse-box#1016]
I can find no option to start the dev server using ssl (with custom certificate).

Is it possible to configure the server and certificate? There is access to the express app after starting the server, but thats not enough.

**Comment by nchanged** [comment]
hi @KnisterPeter 
You can use this approach 

https://github.com/fuse-box/fuse-box-examples/tree/master/examples/custom-server

By creating a custom server and following this tutorial 
https://blog.cloudboost.io/everything-about-creating-an-https-server-using-node-js-2fc5c48a8d4e
