### ISSUE TITLE
Typos in the Getting Started guide.

### ISSUE THREAD

**Issue by matheus23** [fuse-box/fuse-box#1018]
I have found a couple of typos in the "Getting Started" guide of fusebox and wanted to submit corrections for them as pull request, but I can't find the repository.

If the website/getting started guide is not a public repository, I believe it would be beneficial for you to make it public (and especially open to pull requests)  :)

I think that the grammatical errors make it seem a little unprofessional. Here are the typos I found:

> You can not forced to used typescript.

> But keep in my synthetic default imports.

> constructud

there may be more, I have not read the guide fully yet.

**Comment by nchanged** [comment]
@matheus23 Hi! Thank you very much!
The docs are located here https://github.com/fuse-box/fuse-box/tree/master/docs

And that's the navigation https://github.com/fuse-box/fuse-box/blob/master/docs/_doc.json

You can easily submit a PR, once merged the docs will be updated automatically!

**Comment by nchanged** [comment]
@matheus23 I've fixed the typos you mentioned, please feel free to submit a PR, if you find more. I am sure you will, I didn't have much help with the documentation and was rushing a bit with the release of 3.0

And thanks again!
