### ISSUE TITLE
CSS inject:false seems to have no effect

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#1019]
Hi, since I updated to version 3 (3.0.2) it is now putting in my code following line (require("fuse-box-css")("bundle.css");) even though I have disabled injection as per config. Becuase of that it seems my whole app is crashing ;(

```js
const defaultFuse = FuseBox.init({
    homeDir: 'src',
    output: 'public/$name.js',
    plugins: [
      WebIndexPlugin({ template: 'src/client/index.html', target: 'index.html' }),
      JsxControlsPugin,
      JSONPlugin(),
      CSSPlugin({
        group: 'bundle.css',
        outFile: `public/styles/bundle.css`,
        inject: false
      })
    ],
  });
```

**Comment by tomitrescak** [comment]
Actually it gets even more conusing. The require("~/bundle.css") is generated instead of my following code:

```
import 'sweetalert2/dist/sweetalert2.css';
```

generates

```
FuseBox.pkg("sweetalert2", {}, function(___scope___){
___scope___.file("dist/sweetalert2.css", function(exports, require, module, __filename, __dirname){
require("~/bundle.css")
});
```

**Comment by nchanged** [comment]
But injection is related to the head not to the code, can you be more specific

**Comment by robertkruis** [comment]
@tomitrescak, @nchanged:  
I ran into the same issue as you did. When looking at the browser console, the module cannot be found therefore the rest of the bundle won't be loaded. This causes your application to stop functioning. When CSS is grouped, the CSSPlugin emits a `require("~/${bundleName}")`, which will look at the root of the project. The file however can't be found at the root, therefore the require statement crashes.

I did change the CSSPlugin.js after an `npm install` and replaced the above require statement with the following `require("${context.defaultPackageName}/${bundleName}")` on line 128. 
By using _**context.defaultPackageName**_ in the require statement, FuseBox will then look for the module in the package specified in your FuseBox configuration.

I've applied the above mentioned change in several of my prototype projects at work and grouping CSS files works as expected and I haven't run into any side-effects. Unfortunately I did not find time to create a pr, but below you can find a screenshot with the change. Maybe this can be incorporated into the FuseBox source?

![cssplugin](https://user-images.githubusercontent.com/6650061/34761995-5e324370-f5e6-11e7-9335-49a5f5377882.png)

**Comment by nchanged** [comment]
@robertkruis awesome! Thanks! that makes total sense!

**Comment by tomitrescak** [comment]
Hi, thanks for your help. Yet it did not solve my issue. Now I'm getting following error:

```
vendor.js:95921 GET http://localhost:3000/default/bundle.css 404 (Not Found)
```

The only way for me to remove this error is to have "bundle.css" generated in root folder. That is change

```
CSSPlugin({
        group: 'bundle.css',
        outFile: `public/styles/bundle.css`,
        inject: false
      })
```

to

```
CSSPlugin({
        group: 'bundle.css',
        outFile: `public/bundle.css`,
        inject: false
      })
```

**Comment by tomitrescak** [comment]
Has this patch made it to master? I still get the error with latest.

**Comment by nchanged** [comment]
@tomitrescak You should get rid of CSSPlugin() `options` and let FuseBox inline everything, (Inline source maps will work with the latest version). Then when making a production build enable {css : true} In the Quantum Plugin.
