### ISSUE TITLE
Test runner

### ISSUE THREAD

**Issue by leon-andria** [fuse-box/fuse-box#102]
Based on the change log, i notice 2 times about test runner and the intellisense of VS Code highlight about test method.
Sure there is no documentation about this but i give it a try and requested 2 dependencies:
1. fuse-test
2. fuse-test-reporter

So, i was able to install fuse-test but there is no way to find out about fuse-test-reporter.
Can you give more insights about this or what is the purpose ?

tks

**Comment by nchanged** [comment]
Well, the test runner in already working, but have not been officially released. If you want to participate in testing, you are so welcome! I can send you instruction later on.

**Comment by leon-andria** [comment]
Nice. Why not.
Im curious about it, i use already wallaby:-)

**Comment by nchanged** [comment]
It's gonna be bigger than wallaby =) Believe me =)

**Comment by nchanged** [comment]
Simple instructions are:
1) npm install fuse-test
2) Create a file ending with test.ts (for example Utils.test.ts)
3) Call fuse.test() (fuse is the instance of FuseBox.init like [this](https://github.com/fuse-box/fuse-test/blob/master/playground/test.js)
4) Check the examples [here](https://github.com/fuse-box/fuse-test/tree/master/playground/src/tests)

You can create them like so:

```
import { should } from "fuse-test";

export class MyAwesomeTest {
      "Should check something"() {
        should("123").length(3).beString()
    }
}
```

**Comment by leon-andria** [comment]
I buy it then send the doc

**Comment by nchanged** [comment]
that's just a beginning. The plans are just crazy, they will be executed automatically in the browser and on server. Custom reporters and stuff.. And of course, we can integrate it with editors.

`fuse-test` and should is limited. Feel free to improve the functionality.

**Comment by leon-andria** [comment]
I did already that and miss about fuse-test-reporter

**Comment by nchanged** [comment]
You don't need fuse-test-reporter it's coming automatically

**Comment by leon-andria** [comment]
Strange because since the beginning, i got this error message: Cannot find module 'fuse-test-reporter'

**Comment by nchanged** [comment]
do you have the latest fuse installed?

**Comment by nchanged** [comment]
cuz it's there https://github.com/fuse-box/fuse-box/tree/master/assets/libs/fuse-test-reporter

**Comment by leon-andria** [comment]
updating the version makes it works.
I will give my feedbacks mater, i'm testing.
I found some strange behavior.

**Comment by nchanged** [comment]
Thanks, for sure there are strange behaviors =)
