### ISSUE TITLE
Babel transpilation not working

### ISSUE THREAD

**Issue by oayres** [fuse-box/fuse-box#1022]
First off, my experience with fuse-box thus far has been great, so thanks for building an incredible bundler. However, unfortunately I cannot get it working the way I'd like just yet. For a host of reasons, we cannot and do not want to use TypeScript right now and would like our React project to be transpiled with Babel. But it appears to not work its magic on all of our code.

I figured it'd be easiest to just create a repo with a sample React project in using Fuse box. It includes a custom Node server, too.

https://github.com/oayres/fuse-issue

If you clone the repository and run `yarn install && node fuse.js` in the root, you'll encounter two issues:

1. I'm importing sass files from `./` inside the React component, but it doesn't get it. It's resolving `./` to the root of the project, but I want the current directory. `Error: unknown: ENOENT: no such file or directory, open '/my/path/fuse-issue/HomePage.scss'`

2. It's not transpiling the React components into ES5, in either client or server bundles, thus the build fails.

We're using the BabelPlugin provided (https://github.com/fuse-box/fuse-box/blob/master/docs/plugins/transpilers/BabelPlugin.md).

Any ideas why Babel is refusing to process the code?

Extra info - 
- Node v8.7.0
- Mac OS X, Sierra
- And yes, I have tried putting the `.babelrc` contents inline to the `BabelPlugin` config too, but same deal.

Cheers,
Owen

**Comment by nchanged** [comment]
Hi Owen!
Just installed your project.
`fuse-issue/HomePage.scss` Comes from that plugin -> `babel-plugin-react-css-modules` definitely not fuses' fault. You need to configure how to resolve these files. Unfortunately, I am not familiar with that plugin

Besides, `express-static-gzip` was missing

Secondly, your Babel must convert import statements into `require` that's how FuseBox works, so please adjust that. I noticed you have import with `@` - that's a scoped repository. If you want to have it working, add aliases

```
alias : {
        	"@components" : "~/components"
        },
```


Cheers

**Comment by oayres** [comment]
@nchanged Massively appreciate the quick response and help!

Hmm, that's strange. This babel plugin `babel-plugin-react-css-modules` works fine configured the same in Rollup and Webpack. I don't get why it would break in Fuse.

Forgive me on the static gzip thing. I was removing all the rubbish out of a bigger example and obviously left one in! Re-added.

Regarding the Babel part - I thought Babel did this by default? We're using the preset `env`, which should convert them into `require`, no? Either way, I just tried using the plugin `transform-es2015-modules-commonjs` just incase, but I still get the same unexpected token import. Do I need to register babel in any other way with Fuse?

Lastly, regarding the alias part, there is a reason I am using the babel plugin for this and it'd be interesting to hear your thoughts. Basically, we use Jest for unit testing, which uses `babel` under the hood. So when we write a Jest test on a React component that is importing other stuff with an alias, babel sorts that out for us. If we were to put the alias in at a build tool level, such as Webpack or Fuse, Jest will all of a sudden lose this context and fail the test. To work around that, we'd need to make Jest be preprocessed by our build tool, which we do not want (since it's unnecessary).

It appears to me like Babel is not actually processing the files, since in the bundle there is the module resolve unresolved, JSX not transformed and of course the imports, but I could be wrong :/

I've updated the repo with a few tiny tweaks. If you get the chance to take a second look, that'd be ace! Hugely appreciate the time.

Cheers,
Owen

**Comment by nchanged** [comment]
I see the problem. We use jest with my client too, and it's actually quite easy to setup with FuseBox, all you need to do is tweak a bit your `package.json`

```
"jest" : {
  "moduleNameMapper": {
      "^@components/(.*)": "<rootDir>/src/components/$1",
    },
}
```

And here is some config that copied over to your projects and adjusted


```js
const { FuseBox, Sparky, WebIndexPlugin, SassPlugin, CSSPlugin, BabelPlugin, QuantumPlugin } = require("fuse-box");
const { src, task, watch, context, fuse } = require("fuse-box/sparky");


context(class {
	sharedConfig(){
		return {  
			alias : {
				"@components" : "~/components"	
			},
			useTypescriptCompiler : true,
			polyfillNonStandardDefaultUsage : true,
        }
	}
    getConfig() {
        return FuseBox.init({
        	...this.sharedConfig(),
            homeDir: "src",
            output: "dist/$name.js",
            cache : false,
            target: "browser@es5",
            hash: this.isProduction,
            plugins: [
                WebIndexPlugin(),
                //BabelPlugin(),
                [ SassPlugin(), CSSPlugin() ],
                this.isProduction && QuantumPlugin({
                    bakeApiIntoBundle: "app",
                    uglify: true,
                    extendServerImport: true
                })
            ]
        })
    }
    createBundle(fuse) {
        const app = fuse.bundle("app");
        if (!this.isProduction) {
            app.watch()
            app.hmr()
        }
        app.instructions(">index.js");
        return app;
    }
});
task("clean", () => src("dist").clean("dist").exec() )

task("launch-server", async context => {
    const server = FuseBox.init({
    	...context.sharedConfig(), 
    	target: "server", 
    	homeDir: "src/", 
    	target : "server@es6",
		alias : {
        	"@components" : "~/components"
        },
        plugins : [
        	[ SassPlugin(), CSSPlugin() ]
        ],
    	output: "dist/server/$name.js" 
    })
    server.bundle("server")
        .completed(proc => proc.start())
        .instructions(">[server/index.js] + fuse-box-css").watch()
    await server.run();
});

task("default", ["clean", "launch-server"], async context => {
    const fuse = context.getConfig();
    fuse.dev({ httpServer: false });
    context.createBundle(fuse);
    await fuse.run();
});

task("dist", ["clean", "launch-server"], async context => {
    context.isProduction = true;
    const fuse = context.getConfig();
    fuse.dev(); // remove it later
    context.createBundle(fuse);
    await fuse.run();
});
```

It works.. almost, except for missing modules (i guess you haven't committed those) + `express` doesn't have `default` exports, that's why it might fail (and we usually avoid bundling deps)

Cheers

**Comment by oayres** [comment]
Thanks for your help with this @nchanged!

I tried your config. There are a few issues as you've mentioned, but the main problem we have here is that it's using TypeScript instead of Babel, but we need to use babel for certain plugins (react CSS modules is one of them).

If I disable the line `useTypescriptCompiler: true,` and recomment in the BabelPlugin, the issues come back.

Is it possible to fully avoid the typescript compiler for our source code (node modules would be fine with it, I'm guessing) and just use Babel?

**Comment by nchanged** [comment]
Yeah, that would be fine. You just need to make sure that Babel produces `require` statements instead of `import`

**Comment by nchanged** [comment]
I am wondering if we should have similar plugin that does this kind of magic ;-)

**Comment by oayres** [comment]
But, if you go here and try typing an import in on the left:
https://babeljs.io/repl/

It'll transpile it into a require. The issue isn't that babel is not turning it into a require, the problem is it isn't processing the file with Babel at all. Need to dig deeper to understand why that's happening, but it's as if Fuse is either not taking Babel's output, or it isn't passing it through babel at all

**Comment by nchanged** [comment]
Try with `--debug` and see all files are being captured by BabelPlugin

**Comment by oayres** [comment]
Here's some sample output:
```
14:35:16: BabelPlugin :
        Configuration: {"presets":[["env",{"modules":false}]],"plugins":["transform-es2015-modules-commonjs","transform-react-jsx","transform-decorators-legacy","transform-class-properties","transform-object-rest-spread",["react-css-modules",{"filetypes":{".scss":{"syntax":"postcss-scss"}},"removeImport":true,"generateScopedName":"vfuk-[name]__[local]"}]]}
14:35:16: BabelPluginClass : Captured server/app.js
14:35:16: BabelPluginClass : Captured server/middleware/staticResources.js
14:35:16: BabelPluginClass : Captured server/middleware/cohere.js
14:35:17: BabelPluginClass : Captured routes.js
14:35:17: BabelPluginClass : Captured pages/HomePage/index.js
14:35:17: BabelPluginClass : Captured pages/HomePage/HomePage.js
```

So it is being captured, but it isn't processing them, or it isn't _using_ the processed output at least. If you copy and paste it through babel or use any other bundler, it'll all be transpiled

**Comment by nchanged** [comment]
Oh yeah, I finally got it. That' the same file with CSS issues, there is an exception in Babel which results in a failed transpilation. So we need to fix the CSS issue first.

**Comment by oayres** [comment]
Cool, thanks @nchanged for your help. Do you have a link to the CSS issue to reference here please? I'd like to help move this forward if possible.

**Comment by nchanged** [comment]
Actually, we don't have anything similar. Maybe we could change the title accordingly?

**Comment by oayres** [comment]
Which CSS issues / file are you referring to here? You've lost me haha. I'm happy to help resolve and submit a PR, but where do I need to look?

What would you like to change the title to?

**Comment by nchanged** [comment]
Well, we could start with https://github.com/fuse-box/fuse-box/blob/master/src/plugins/js-transpilers/BublePlugin.ts this file ;-)

**Comment by oayres** [comment]
Cool, I'll get on this as soon as I can and report back findings on this issue.

_PS, you linked the Buble plugin, not the Babel one haha._

**Comment by nchanged** [comment]
Oh sorry man, but i guess you've found the right module by now ;-)

**Comment by nchanged** [comment]
@oayres do you think we can close the issue and maybe open a different one? Related to Babel CSS?

**Comment by oayres** [comment]
Yeah, could do. In terms of fuse-box, I guess the issue boils down to correctly handling a Babel error in the output. When Babel fails for any reason (which in my case, is the `babel-plugin-react-css-modules` getting unhappy), the build doesn't present the issue clearly and continues to bundle, which makes the app break.

Is there any reason we silently skip the file from being transpiled if it errors? Specifically referring to the fact `babel.transform` is in a try catch, where the catch just moves onto the next file. This could cause unexpected behaviour if you don't scroll up and spot anything in the terminal.

What are your thoughts on stopping the build entirely if it hits the `catch` @nchanged?

**Comment by nchanged** [comment]
@oayres thanks, that would be appropriate. I think in case of a fatal error all the dist contents need to be removed.

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
