### ISSUE TITLE
CSSDependencyExtractor - Maximum call stack when importing with LESS

### ISSUE THREAD

**Issue by zouloux** [fuse-box/fuse-box#1023]
Hi Fuse team,

I upgraded recently to 3.0.2 and a new problem occurs when using imports and LESS. Here is a proof of the issue :

```
git clone https://github.com/zouloux/fuse-box-cssdependencyextrator-issue-proof
cd fuse-box-cssdependencyextrator-issue-proof
npm i
node fuse
```

I suspect the recursive LESS import causing this :
Main.less is importing subfolder/Component.less
and Component.less is importing as reference ../Main.less

This is useful so I can use mixins from Main.less into Component.less.

I tried with and wither leading ./
Also with and without .less extension on imports.

This issue does not exists on version 3.0.0-next.20.

Thanks for your hard work !

**Comment by nchanged** [comment]
@zouloux Thank you for submitting the issue and being patient! Your issue is now fixed and will be available in the next `@next` version very soon.
