### ISSUE TITLE
Importing TypeScriptHelpers inside fuse.js returns undefined 

### ISSUE THREAD

**Issue by RPDeshaies** [fuse-box/fuse-box#1024]
```
const {TypeScriptHelpers} = require("fuse-box");
console.log(TypeScriptHelpers) // undefined
```

Using it like this `TypeScriptHelpers()` inside the `plugin` property of the `FuseBox.init` method
Gives me this error
```
TypeError: TypeScriptHelpers is not a function
```

Version: 3.0.2
Cleaned npm + .fusebox cache

**Comment by nchanged** [comment]
TypescriptHElpers was deprecated and removed. Please use tslib I will update the doc
