### ISSUE TITLE
crash when use uglify-js

### ISSUE THREAD

**Issue by foisonocean** [fuse-box/fuse-box#1025]
fuse-box version: 3.0.2

this is my fuse.js file:
```js
const { FuseBox, QuantumPlugin } = require('fuse-box')

FuseBox
  .init({
    homeDir : "src",
    target : 'browser@es5',
    output : "output/$name.js",
    plugins : [
      QuantumPlugin({
        uglify: true,
        treeshake : true,
      }),
    ]
  })
  .bundle("bundle.js")
  .instructions('>index.js')
  .fuse.run()
```

I got this error:
![image](https://user-images.githubusercontent.com/15059605/34785843-4c095170-f66d-11e7-9c43-363d63b1f607.png)

It's OK when I set `{uglify: false}`, so it seems that uglifyjs is asked to receive a file path, but actually received file content.

**Comment by nchanged** [comment]
Hi!
Please make sure that you are using the latest version of uglify-js.  That's because older version are incompatible with FuseBox API

**Comment by foisonocean** [comment]
@nchanged You mean I need to install uglify-js by myself? So why not write the version requirement of uglify-js in the `peer-dependencies` in package.json?

**Comment by nchanged** [comment]
https://fuse-box.org/page/quantum#installation

<img width="787" alt="screenshot 2018-01-10 19 14 09" src="https://user-images.githubusercontent.com/1629088/34788319-7acc4586-f63a-11e7-967f-57c0a167eeb3.png">
I might need to add some colors to the doc and place it into a red giant box ;-)
Sorry about that.
