### ISSUE TITLE
tslib in not included in the bundle

### ISSUE THREAD

**Issue by foisonocean** [fuse-box/fuse-box#1026]
This is my fuse.js file:
```js
const { FuseBox, QuantumPlugin } = require('fuse-box')

FuseBox
  .init({
    homeDir : "src",
    target : 'browser@es5',
    output : "output/$name.js",
    plugins : [
      QuantumPlugin({
        uglify: true,
        treeshake : true,
      }),
    ]
  })
  .bundle("bundle.js")
  .instructions('>index.js')
  .fuse.run()
```

fuse-box now is using typescript with `{"importHelpers": true}` to transpile my code, but in the final bundle file, the tslib dependency is not included.

**Comment by nchanged** [comment]
@foisonocean do you have tslib installed? 
Clear the cache and re-bundle please.

**Comment by nchanged** [comment]
@foisonocean you need to set `useTypescriptCompiler: true`. I noticed you are using `js`

**Comment by foisonocean** [comment]
@nchanged use Typescript compiler is the default behavior in fuse-box v3.0.2

**Comment by foisonocean** [comment]
In other words, my bundle file in not able to execute because tslib is missing.

**Comment by nchanged** [comment]
@foisonocean you would need tslib and `useTypescriptCompiler` flag, otherwise, it won't work

Cheers,

**Comment by nchanged** [comment]
@foisonocean based on this example
https://github.com/fuse-box/fuse-box-examples/tree/master/examples/use-typescript-compiler

I can close the issue, as it's verified and working as expected. Please contact us on GItter if you have further questions/problems.

**Comment by foisonocean** [comment]
@nchanged 
Set `useTypescriptCompiler: true` fix it, but I think there are still a problem about the default behavior of not set `useTypescriptCompiler`.
In my opinion, when not set `useTypescriptCompiler`, the correct behavior should be:
*Don't use TypeScript compiler*
Or
*Use TypeScript compiler, and bundle the `tslib` dependency*

**BUT** the current behavior is:
*Use TypeScript compiler, but **miss** the `tslib` dependency*

**Comment by nchanged** [comment]
@foisonocean useTypescriptCompiler replaces Babel, we cannot enable it by default, at least for now

**Comment by foisonocean** [comment]
@nchanged So the strange thing is, when I don't set `useTypescriptCompiler` flag, it still use typescript compiler

**Comment by nchanged** [comment]
@foisonocean it will use it if required (if targets don't match for example), but the flag forces it for everything

**Comment by foisonocean** [comment]
@nchanged So problem is here:
if I don't set the flag, and targets don't match, it will use the typescript compiler, but miss `tslib` in bundle

**Comment by nchanged** [comment]
@foisonocean ok I see now! Will check it out, thanks

**Comment by xdave** [comment]
@nchanged I'm having the same problem. Tried with @next I've disabled treeshaking an uglify to test. The page loads without any errors in the console, but it's blank. Manually calling `$fsx.r(1292);` in the browser console yields `undefined`.  I'm using the `esModuleInterop` option in tsconfig, so it's using the `__importDefault` helper almost everywhere.  However, this helper does not work because tslib isn't being loaded.  Works fine with with Quantum switched off.  Any ideas?

**Comment by nchanged** [comment]
@xdave please use https://fuse-box.org/page/configuration#allowsyntheticdefaultimports instead

**Comment by SephReed** [comment]
I'm running into this issue randomly too.  If I clear my cache, it'll work for a few loads.  Then suddenly I'll start getting the tslib error again.

**Comment by SephReed** [comment]
So, it starts happening after the first hmr().  If I clear .fusebox, then start node fuse, it'll run fine until the first hmr.  At which point, I'll get the `Uncaught Package not found tslib` error.

At the moment, this has randomly become a huge blocker for me.  How do I fix it?

**Comment by nchanged** [comment]
@SephReed could you give `v4` a try? 
https://github.com/fuse-box/react-example/tree/v4
