### ISSUE TITLE
HMR update breaks source maps in vscode

### ISSUE THREAD

**Issue by andrew-w-ross** [fuse-box/fuse-box#1029]
On update when the a `source-changed` event fires the sourceMapping url is incorrect as it points to `//# sourceMappingURL=${nameOfFileThatWasChange}.map` which doesn't exist and therefor breaks when vscode tries to map back to the original map file. 

You can recreate it using the [fuse-debug](/andrew-w-ross/fuse-debug#master) that uses v2 there is also a v3 branch that shows the same behaviour. 

I think a fix would be quite simple as the sourceMappingURL should just be the bundle name. I know there is a lot on your plate after the release of v3 so I'm more than happy to make a pr.

**Comment by nchanged** [comment]
Hi @andrew-w-ross thanks for bringing this issue. To be honest, I've never used vscode + sourcemaps, if you could help fix it and also updating the doc on how to use it - that would be terrific!

**Comment by andrew-w-ross** [comment]
vscode + sourcemaps is pretty awesome you should give it a try. I'll get onto a pr this weekend.

**Comment by nchanged** [comment]
@andrew-w-ross maybe you could write a guide on how to set it up?
For example here https://fuse-box.org/page/working-targets#uglifying

**Comment by andrew-w-ross** [comment]
@nchanged Sure I can do that.
