### ISSUE TITLE
Some modules cannot be imported because `this !== module.exports`

### ISSUE THREAD

**Issue by TimePath** [fuse-box/fuse-box#1030]
Some modules (such as pdfmake) expect `this === module.exports` when importing, as in node and webpack. 

Fuse-box seems to be setting `this = 0` instead: https://github.com/fuse-box/fuse-box/blob/e40ec64b4f6f03a21732e58e20e90ed07735382b/modules/fuse-box-loader-api/fusebox.js#L292

**Comment by nchanged** [comment]
Hi, @TimePath thanks for submitting the issue!
Would you suggest module.exports === this? Do you think you can make a PR to fix that? seems like a legit fix.
