### ISSUE TITLE
EnvPlugin doesn't work when target is "server" ??

### ISSUE THREAD

**Issue by mironal** [fuse-box/fuse-box#1033]
I tried use the EnvPlugin for inject process.env.NODE_ENV.

However, it did not work as I expected :cry:

Is there a problem with my usage?

> my test repo: https://github.com/mironal/fuse-box-env-plugin-test

## node --version

v9.4.0

## yarn --version

1.3.2

## fuse.js

```js
const { FuseBox, EnvPlugin } = require("fuse-box");

const fuse = FuseBox.init({
  homeDir: "./",
  target: "server",
  output: "dist/$name.js",
  plugins: [EnvPlugin({ NODE_ENV: "development", bar: "barbar" })]
});

fuse.bundle("app").instructions("> src/index.js");

fuse.run();
```

## src/app.js

```js
console.log(process.env.NODE_ENV, process.env.bar);
```

## Expected behavior

`development barbar`

### when use fuse-box 2.4.0

`undefined undefined`

### when use fuse-box 3.0.2

`undefined undefined`

**Comment by nchanged** [comment]
Thanks for submitting the issue! It has been fixed and it will be available in the next `@next` version.

**Comment by mironal** [comment]
thanks! 😄
