### ISSUE TITLE
universal target: node globals are shimmed even if dependencies explicitly suppress them

### ISSUE THREAD

**Issue by SheetJSDev** [fuse-box/fuse-box#1035]
**Context**: the [`xlsx` module](https://www.npmjs.com/package/xlsx) uses the [`browser` field of package.json](https://github.com/SheetJS/js-xlsx/blob/master/package.json#L25-L31) to suppress certain node shims for browser usage.  

**Example index.ts:**

```ts
import * as XLSX from 'xlsx';

console.log(XLSX.version)
```

**Example fuse.js:**

```js
const { FuseBox } = require("fuse-box");
const fuse = FuseBox.init({
    homeDir: "src",
    target: "universal",
    output: "dist/$name.js",
});
fuse.bundle("app").instructions(`>index.ts`);

fuse.run();
```

**Expectation**: since the dependency package.json explicitly suppresses `process`, a priori there are three reasonable outcomes for `process` in the browser:
1\. process is undeclared: no `/* fuse:injection: */ var process = require("process");` injection but call a function that sets global.process if `FuseBox.isServer()` is true
2\. process is assigned an `undefined` value: preserve the injection, but return `void 0` if `FuseBox.isServer()` is false.
3\. process is assigned [a stub object `{}`](https://github.com/defunctzombie/package-browser-field-spec#ignore-a-module) or throw an error.

**Actual Behavior**:
4\. fuse-box adds process sham that is not an empty object:

```js
if (FuseBox.isServer) {
// ...
} else {
// ...
    var process = module.exports = {};
// ...
    process.nextTick = function(fun) {
```

**Opinion**: The first approach is ideal, as it would be consistent with how a truly universal script would run in the browser.  Here's an example of behavior that only the first one preserves:

```js
(function() {
  var has_process = false;
  try { process; has_process = true; } catch(e){}
  return has_process;
})(); // false in browsers
```

Even though the [`package-browser-field-spec`](https://github.com/defunctzombie/package-browser-field-spec) doesn't directly address globals from the server environment, based on prior art the best approach is to honor suppressions of globals like `process` and `buffer`.

**Comment by nchanged** [comment]
hi, @SheetJSDev thanks for submitting the issue!

There is a bit of a problem with `universal` and browser fields. We cannot use them, as server builds will fail, most likely.  

Fuse injection makes sure that browser receives polyfills, server - native modules. 

>> since the dependency package.json explicitly suppresses process

It ignores them because of the `universal` target.  I am not sure what would be the correct fix to the problem. We either fix the `process` polyfill or use separate builds (which I would prefer doing - as FuseBox is great at optimising platform specific bundles)

Either way, I would like to hear your ideas and suggestions.

**Comment by SheetJSDev** [comment]
Upon re-reading the spec, it's clear that the case of node globals isn't properly addressed, and my original statement of opinion is not scalable.  This is as good a time as any to discuss what should happen.

<details>
  <summary><b>Discussion</b> (click to show)</summary>

Broadly speaking, for a given node core module there are two obvious injections:

A) if in server, use the node require; if in browser, use a shim
B) if in server, use the node require; if in browser, shim as `{}` (following the "spec").

For a given node global, there are 5 obvious injections.  In all cases, if in server, the node require will be used.

A) create a local variable, use a shim
B) create a local variable, shim as `{}`
C) pass through scope (global, window, self), use a shim
D) pass through scope, shim as `{}`
E) noop

The situation is made more complex in an environment where some modules suppress a shim and others don't (requiring A, which needs the shim, and B, which suppresses it).

</details>

To first order, the simplest solution would be a hybrid of A and B:

1) use a code injection conditioned on whether the browser shim should be used.  For `process`, if `"process":false` is set in the browser field of package.json, use the injection:

```js
/* fuse:injection: */ var process = require("process:false"); // process is suppressed
```

Normal injection if process is not explicitly suppressed:

```js
/* fuse:injection: */ var process = require("process"); // process is not suppressed
```

This can be determined at compile time since it is a property of the dependency's `package.json`.

2) if used, define the module `"process:false"` to pull the node global if applicable, returning undefined or null or `{}` otherwise:

```js
FuseBox.pkg("process:false", {}, function(___scope___){
___scope___.file("...", function(exports, require, module, __filename, __dirname){

if (FuseBox.isServer) {
    if (typeof __process_env__ !== "undefined") {
        Object.assign(global.process.env, __process_env__);
    }
    module.exports = global.process;
} else {
    module.exports = void 0;
}
});
return ___scope___.entry = "index.js";
});
```

3) if used, define the module `"process"` as per current behavior.

This ensures that `process` is visible from every module in node, but in the browser the modules that suppress `process` will see undefined and the modules that do not suppress `process` will see the sham.

**Comment by nchanged** [comment]
I see the solution and it seems legit. I do, however, have a question.
If the module `process` is suppressed, does it mean that we will have to replace all statements with an empty object, or inject an empty object? 

And what's the actual reasoning behind suppressing the `process`? Does it affect the runtime?

**Comment by SheetJSDev** [comment]
Suppression refers to the latter -- the actual lines of code accessing `process` are untouched, but at the top you would inject a declaration like `var process = require("process:false");`

Specifically for process, some libraries use tricks like `typeof process !== 'undefined' && process.env` to determine if running in node (usually just before testing for environment variables).  The ["correct" way to determine if the current process shim is injected](https://github.com/defunctzombie/node-process#browser-implementation) is `typeof process !== 'undefined' && !!process.browser`, which is not self-evident and requires knowledge of the actual shim code.

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
