### ISSUE TITLE
CSSPlugin + WebIndexPlugin not injecting css link tags into built index.html

### ISSUE THREAD

**Issue by chickendinosaur** [fuse-box/fuse-box#1039]
There is no injected link tag doing develpment or production build.

I am importing .scss files from a styles sub-folder in my src directory. Everything works perfect when running dev which means they're getting injected just fine by never extracted to disk.

**Fuse-box config:**
```
const {
    FuseBox,
    WebIndexPlugin,
    QuantumPlugin,
    SassPlugin,
    CSSPlugin
} = require('fuse-box');

const isProduction = process.env.NODE_ENV === 'production';

const fuse = FuseBox.init({
    homeDir: `${__dirname}/../src`,
    target: 'browser@es6',
    output: `${__dirname}/../dist/$name.js`,
    hash: isProduction,
    cache: !isProduction,
    plugins: [
        // JavaScript optimazations.
        isProduction && QuantumPlugin({
            ensureES5: false, // Ensures that all code that is in es5
            extendServerImport: false, // If you are using dynamic import statements to load remote javascript files. note: Install request library beforehand
            manifest: true, // Generates manifest.json
            processPolyfill: false, // Removes "use strict" from the code
            removeExportsInterop: true, // Removes Object.defineProperty(exports, '__esModule', { value: true });
            removeUseStrict: true,
            replaceProcessEnv: true, // Replaces process.env.NODE_ENV with a string identifier "production"
            replaceTypeOf: true, // Replaces typeof module, typeof exports, typeof window, typeof define, typeof require keywords to corresponding values at build time
            target: 'browser@es6', // Default value: browser Possible values server, browser, universal, electron, npm
            treeshake: true,
            warnings: true,
            uglify: {
                es6: true
            } // Quantum supports both uglify-js and uglify-es. Which one to use is determined by es6 option.
        }),

        // Style loading.
        [
            SassPlugin({
                outputStyle: isProduction ? 'compressed' : 'expanded',
                omitSourceMapUrl: true
            }),
            CSSPlugin({
                outFile: (file) => { return `${__dirname}/../dist/${file}`; },
                inject: (file) => { return `${file}`; }
            })
        ],

        // Generate index.html.
        WebIndexPlugin({
            template: `${__dirname}/../src/templates/index.html`,
            title: 'React + Typescript + Fusebox',
            appendBundles: true
        })
    ]
});

const app = fuse.bundle('app');

// Launch http server.
if (!isProduction) {
    app.watch();
    app.hmr();

    fuse.dev({
        port: 4444
    });
}

app.instructions('> client.tsx');

fuse.run();
```

**Generated index.html:**
```
<!DOCTYPE html>

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1">
</head>

<body>
  <div id='root'></div>
<script  type="text/javascript" src="/48d3c064-api.js"></script>
<script  type="text/javascript" src="/9cb13f30-app.js"></script></body>

</html>
```

**Comment by nchanged** [comment]
@chickendinosaur 
As I understood, you would like to have it written to `index.html`? 

At this very moment, WebIndexPlugin doesn't support that. But we will add the support later.

**Comment by chickendinosaur** [comment]
Correct. Like how the Webpack html plugin does it because you do not wan to have to update your .html template every time your used style files and and architecture changes. There should also be options for the attribute preload. 
I am guess that you were manually inserting a <link href="index.css" /> tag and calling it a day?

You should be and to flag options per a file to inject the <link /> tag or not due to utilizing service worker push or dynamic CSS code splitting.

For now I would just like it to at least insert the import CSS files since I import more then one .css file so they get cached separately. Example: import 'normalize.css';  import 'variable.scss';  import 'base.scss';  import 'index.scss';  

P.S.: FuseBox is the shit by the way! I forget how I stumbled across it the other night (probably scraping the internet for faster alternatives to Webpack) but I am 100% commited to FuseBox now and TypeScript coming from a Webpack + Flow enterprise application. Instant build relief so thanks!

**Comment by nchanged** [comment]
@chickendinosaur I am glad to hear that! Stay with us! This feature has been requested so many times, So I think it's coming with 3.1.0.

I rather have Quantum collect all CSS and generate files rather than having Options in `CSSPlugin`. Ideally - inline CSS during development, and extracted with Quantum.

**Comment by maximkott** [comment]
@nchanged  Do you know when 3.1.0 will hit the fan? I've seen that this has already been fixed in #1054.

I have to agree with @chickendinosaur, FuseBox has been a breath of fresh air! I found the api a bit confusing on the first try, (instructions, context, etc.), but after all I think it's awesome!

**Comment by nchanged** [comment]
@maximkott you can use `fuse-box@next` to get this feature. I don't know yet, there are a few critical issues that i need to resolve before the release

**Comment by maximkott** [comment]
@nchanged Thank you!

**Comment by Right2Drive** [comment]
Being that 3.1.0 was released already I'm assuming this was fixed? Does this require any changes on our part? It doesn't seem to be working out of the box for me

**Comment by nchanged** [comment]
Hi, @Right2Drive 
You can find some information here:
https://fuse-box.org/page/getting-started#start-with-css

and here:
https://fuse-box.org/page/quantum-configuration#css
