### ISSUE TITLE
alias option not finding modules

### ISSUE THREAD

**Issue by chickendinosaur** [fuse-box/fuse-box#1040]
I have spenta couple of hours trying to get alias working from both the tsconfig and now the 'alias' property via FuseBox.init({ alias:{} }); and am out of options at this point. I have tried probably every permutation of pathing so I hope this is something simple that I am missing because I need this feature.

My config is under a config folder at the project level with the package.json and reaches to the 'src' folder via __dirname/../src and is ran by 'npm run start'.

**FuseBox config:**
```
const {
    FuseBox,
    WebIndexPlugin,
    QuantumPlugin,
    SassPlugin,
    CSSPlugin
} = require('fuse-box');

const isProduction = process.env.NODE_ENV === 'production';

const fuse = FuseBox.init({
    target: 'browser@es6',
    cache: !isProduction,
    hash: isProduction,
    log: true, // !isProduction
    useTypescriptCompiler: true,
    homeDir: `${__dirname}/../src`,
    output: `${__dirname}/../dist/$name.js`,
    tsConfig: `${__dirname}/../tsconfig.json`,
    // modulesFolder: `${__dirname}/../node_modules_local`,
    alias: {
        'reducers': '~/reducers',
    },
    // sourceMaps: {
    //     project: true,
    //     vendor: true
    // },
    plugins: [
        // JavaScript optimazations.
        isProduction && QuantumPlugin({
            ensureES5: false, // Ensures that all code that is in es5
            extendServerImport: false, // If you are using dynamic import statements to load remote javascript files. note: Install request library beforehand
            manifest: true, // Generates manifest.json
            processPolyfill: false, // Removes "use strict" from the code
            removeExportsInterop: true, // Removes Object.defineProperty(exports, '__esModule', { value: true });
            removeUseStrict: true,
            replaceProcessEnv: true, // Replaces process.env.NODE_ENV with a string identifier "production"
            replaceTypeOf: true, // Replaces typeof module, typeof exports, typeof window, typeof define, typeof require keywords to corresponding values at build time
            target: 'browser@es6', // Default value: browser Possible values server, browser, universal, electron, npm
            treeshake: true,
            warnings: true,
            uglify: {
                es6: true
            } // Quantum supports both uglify-js and uglify-es. Which one to use is determined by es6 option.
        }),

        // Style loading.
        [
            SassPlugin({
                outputStyle: isProduction ? 'compressed' : 'expanded',
                omitSourceMapUrl: true
            }),
            CSSPlugin({
                outFile: (file) => { return `${__dirname}/../dist/${file}`; },
                inject: (file) => { return `${file}`; }
            })
        ],

        // Generate index.html.
        WebIndexPlugin({
            template: `${__dirname}/../src/templates/index.html`,
            title: 'React + Typescript + Fusebox',
            appendBundles: true
        })
    ]
});

const app = fuse.bundle('app');

// Launch http server.
if (!isProduction) {
    app.watch();
    app.hmr();

    fuse.dev({
        port: 4444
    });
}

app.instructions('> client.tsx');

fuse.run();
```

**Import from a nested file under src/components/root:**
```
import uiReducer from '#reducers/ui';
```

**Comment by nchanged** [comment]
Hi @chickendinosaur 

Thanks for submitting the issue! 

You have probably misunderstood how to use aliases, and you have a bit messy `homeDir` initialisation. I would not recommend using absolute paths. Instead, it's better to put `fuse.js in the root of your project, pointing homeDir to just `src`.

```js
import uiReducer from '#reducers/ui';
```

That is wrong, you shouldn't add `#`. If your alias looks like `'reducers': '~/reducers',` the actual import statements should be as follows:

```js
import uiReducer from 'reducers/ui';
```

Feel free to join Gitter and ask the community for help if that didn't help.
Cheers

**Comment by chickendinosaur** [comment]
Thanks for the quick reply!

My ticket was wrong. I was doing: ```import uiReducer from 'reducers/ui';``` without the "#" and it was not working.

My paths are technically all absolute paths since I am doing ```__dirname```. I have tried putting config in the root directory as well and get the same issue. I'll fiddle with it a little more but it's really driven me to the point of madness.

**Comment by nchanged** [comment]
@chickendinosaur what's exactly not working? Here is something

## Verifying the actual output.
Please open your transpiled code and find the line with require statement. If it has been changed to `~/reducers` that means that it's working properly

## Verify you `default` export

```
import uiReducer from 'reducers/ui';
```

Means that `reducers/ui` has `export default`

**Comment by chickendinosaur** [comment]
Seems to be working from the root folder. Will leave it there. Thanks!

**Comment by nchanged** [comment]
@chickendinosaur to make it work from you root folder you should put tilde:
```
alias: {
        'reducers': '~/reducers',
    },
```
What you did is a relative import
