### ISSUE TITLE
Question: How to create an alias for node_module to subfolder

### ISSUE THREAD

**Issue by jperezdavinchi** [fuse-box/fuse-box#1043]
Hi!,
I would like to ask for help with a configuration problem
I have an angular 5 project and I would like to switch from the default bundle (umd es5) to es2015.
Angular provides 3 distribution folders:
- bundles (umd). The default ones
- es5
- esm2015
![image](https://user-images.githubusercontent.com/28526655/35094262-09d4c0ea-fc45-11e7-9a39-4333bf85df0d.png)

The package.json of angular has the 'main' property targeting to the bundles folder, I would like to use esm2015 folder instead but using the same `import {} from "@angular/core"`;
I'm trying to use alias in this way:
```typescript
FuseBox.init({
    // some config
   alias:{
            "@angular/core":"@angular/core/esm2015/core",
            "@angular/compiler":"@angular/compiler/esm2015/compiler",
            "@angular/cdk":"@angular/cdk/esm2015/",
            "@angular/forms":"@angular/forms/esm2015/forms",
            "@angular/http":"@angular/http/esm2015/http",
   }
```
The console doesn't emit any error and the vendor.js bundle contains the code of @angular/core/esm2015/core.js
![image](https://user-images.githubusercontent.com/28526655/35094364-56292422-fc45-11e7-8d7d-384498f6f0fd.png)

But going to the browser the console shows:
![image](https://user-images.githubusercontent.com/28526655/35094540-d3df85dc-fc45-11e7-9413-0d98601cfe4e.png)

The error is thrown here
![image](https://user-images.githubusercontent.com/28526655/35094635-216d1206-fc46-11e7-8853-c4cff54665d7.png)

Complete fusebox configuration
```typescript
fuse = FuseBox.init({
        homeDir: `src/`,
        output: `dist/$name.js`,
        target: "browser",
        cache:false,
        hash:isProduction,
        sourceMaps:!isProduction,
        plugins: [
            JSONPlugin(),
            [
                SassPlugin(
                    {
                        outputStyle: 'expanded',
                        importer:true
                    }
                ),
                CSSPlugin()
            ],
            CSSPlugin(),
            WebIndexPlugin(
                {
                    title: '',
                    template: 'src/index.html',
                    path:"./"
                }
            ),
            ConsolidatePlugin({
                engine:"pug",
                extension:".pug"
            }),
            EnvPlugin({ NODE_ENV: isProduction ? "production" : "dev"}),
            ReplacePlugin({ "process.env.NODE_ENV": JSON.stringify(isProduction ? "production" : "dev") }),
            isProduction && UglifyESPlugin()
        ],
        alias:{
            "@angular/core":"@angular/core/esm2015/core",
            "@angular/compiler":"@angular/compiler/esm2015/compiler",
            "@angular/cdk":"@angular/cdk/esm2015/",
            "@angular/forms":"@angular/forms/esm2015/forms",
            "@angular/http":"@angular/http/esm2015/http",
            "@angular/material":"@angular/material/esm2015/core"
        }
    });
    //separate vendor
    vendor = fuse.bundle('vendor')
        .shim({
            jquery: {
                source: "node_modules/jquery/dist/jquery.js",
                exports: "$"
            }
        })
        .instructions(' ~ main.ts');
    app = fuse.bundle('main')
        .instructions(' !> [main.ts]');
```
Could it be a problem with the import of `@angular/core` in some dependency?
Thank you!

**Comment by nchanged** [comment]
Hi @jperezdavinchi 
I think you can just toggle this option https://fuse-box.org/page/configuration#usejsnext
👍

**Comment by jperezdavinchi** [comment]
Hi @nchanged,
thanks for the fast response.
With useJsNext:true, useJsNext:["@angular/core"] or useJsNext:["@angular"] vendor.js has the es5 code.
![image](https://user-images.githubusercontent.com/28526655/35096171-753a0f2e-fc4b-11e7-91cb-2fe07015d2cc.png)

**Comment by nchanged** [comment]
```
FuseBox.init({
  useJsNext : true,
   target : "browser@es6"
})
```
https://fuse-box.org/page/working-with-targets

**Comment by jperezdavinchi** [comment]
The same.
This is the package.json of angular core
![image](https://user-images.githubusercontent.com/28526655/35099139-30bc8104-fc57-11e7-94b5-16ce775a3edc.png)

**Comment by nchanged** [comment]
It should have been `jsnext:main` not `module` ;-(

**Comment by jperezdavinchi** [comment]
So, is not possible?
Maybe the alias approach?

**Comment by nchanged** [comment]
In this case alias. But you could point it directly to the typescript source. That will work even better

**Comment by nchanged** [comment]
@jperezdavinchi we can make it understand other formats too. `es2015` - first time I see something like that

**Comment by jperezdavinchi** [comment]
Thank you, I will try it. If I'm the first one trying to do this and es2015 is not of common use, will be a waste of time for you.

**Comment by jperezdavinchi** [comment]
@nchanged I looked for the sources in the angular package but there are only the definition files, so I must point to esm2015/core.js with the error described in the beginning of the issue.
In the browser in runtime appears that the angular module couldn't be found

**Comment by nchanged** [comment]
@jperezdavinchi I cannot really tell much unless I see the project. Do you mind sharing it?

**Comment by jperezdavinchi** [comment]
My apologies, I can't share it because is a project for a client of my company and I'm not the owner of the code.
But I will create a repo with the same dependencies.

**Comment by paxperscientiam** [comment]
For posterity, here's what I do re aliasing modules directory.

Define `__NODE_MODULES` as, for instance, `resources/modules.noSync/node_modules`.

Make sure to set `modulesFolder` to `__NODE_MODULES`

Custom require function:
````js
const req = (module) => {
  return require(path.resolve(__NODE_MODULES, module))
}
````

Not sure how npm does it, but with yarn i need to use a `.yarnrc` file in the project root with the following code:
`--modules-folder "./resources/modules.noSync/node_modules"`

A few steps to setup, but it works!
