### ISSUE TITLE
running gist online

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box#1045]
Hi

Would have been cool if there was a easy way to use fusebox in browser too.

Im using systemjs here (on hobby project/framework module made with fusebox)
**Plunker:**
http://plnkr.co/edit/gist:8a61d479da82e76c6a88eddb5cb710d8?p=preview

**gist.run**
https://gist.run/?id=8a61d479da82e76c6a88eddb5cb710d8&sha=e5c218edabd65624d9f24c73d81f0443b1a6541b

Is there any way you guys are able to make something better and faster ?

Would have been really cool.

**Comment by TimePath** [comment]
runkit? https://npm.runkit.com/fuse-box

**Comment by nchanged** [comment]
We can't really do that, unless somebody invests into servers; (

**Comment by vegarringdal** [comment]
Ok, was thinking u might get some providers like heroku to host it if its really good :-)

**Comment by vegarringdal** [comment]
This is really cool.
If something is made then i should be like this, just better. (more pure ts/js starter kids too, not just angular/react)
stackblitz.com


Sample on something not react or angular
https://stackblitz.com/edit/mframejs-simple-custom-element

**Comment by devmondo** [comment]
@vegarringdal we might have a bigger plan for this ;)

**Comment by vegarringdal** [comment]
Cool, like what ?

**Comment by devmondo** [comment]
not yet formulated :)
