### ISSUE TITLE
Quantum: Require not defined

### ISSUE THREAD

**Issue by jaysson** [fuse-box/fuse-box#1047]
Getting this issue if require is assigned to a variable, for example line number 355 in https://github.com/skaterdav85/validatorjs/blob/master/dist/validator.js

This happens only when quantum plugin is used.

**Comment by nchanged** [comment]
@jaysson does it happen when you import the library? Can you provide an example of how to reproduce it?

**Comment by jaysson** [comment]
Here is an example.

https://github.com/jaysson/quantum-require-issue

**Comment by davidctj** [comment]
I have similar error only when using Quantum.
Use a old dependency(dagre-d3) which check   `if(require)` for the node export when bundling...

**Comment by nchanged** [comment]
@davidctj could you give me a sample code?

**Comment by davidctj** [comment]
@nchanged 
1. fuse configuration 
`if (isProd ) {
  clientOptions.plugins.push(
    QuantumPlugin({
      replaceTypeOf: false,
      treeshake: true,
      uglify: {
          mangle:false
      },
      api: core => {
        core.solveComputed("moment/moment.js", {
          mapping: "moment/locale**",
          fn: statement => {
            statement.setExpression(`"moment/locale/" + name + ".js"`);
          }
        });
      }
    })
  );
}`

2. project - react component
`const dagreD3 = require('dagre-d3/index');`

fuse-box: 3.1.0-next.6
dagre-d3: 0.6.1

**Comment by nchanged** [comment]
thank you guys,  will tend to it before the 3.1 release
