### ISSUE TITLE
Code splitting requests the split bundle in production incorrectly

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#1050]
Hi, when running production build the code splitting does not seem to work when using SPA. I am using react router and loading component asynchronously. The split works like a charm, but the requests are incorrect, not considering the routes. 

Problem:
The split bundle is requested at end of path such as "/my/long/router/path/SPLIT_BUNDLE"

instead of 

"/SPLIT_BUNDLE"

**Comment by nchanged** [comment]
@tomitrescak you can configure like in this example
https://fuse-box.org/page/code-splitting#configuring

**Comment by tomitrescak** [comment]
Duh ... thanks.
