### ISSUE TITLE
SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by JohnLouderback** [fuse-box/fuse-box#1052]
I'm getting an exception `SyntaxError: Unexpected token .` when trying to import `import 'vuetify/dist/vuetify.min.css';`

![image](https://user-images.githubusercontent.com/4743179/35197797-48c220cc-fea2-11e7-817d-2864724d89cd.png)

It makes sense that the unexpected token error is occurring since the CSS appears to be injected directly into the body of a JavaScript function. I've tried to chain `[CSSResourcePlugin(), CSSPlugin()` in order to rectify the issue, but it seems to make no difference. I'm not clear on why this is happening this way.

Note: This only appears to affect my server bundle. If I bypass my SSR, the client renders fine and without errors.

**Comment by JohnLouderback** [comment]
@nchanged It seems that bundling all dependencies with the server bundle fixes the issue.

**Comment by nchanged** [comment]
Hi, it really looks like the  CSS plugin didn’t catch the file, are you sure that your chaining is correct? Can you share the config please?!

**Comment by nchanged** [comment]
You closed it before I hit submit :)

**Comment by jimmybaker** [comment]
I'm having the same problem with the react-dates package. 
<img width="1666" alt="image 2018-10-24 at 7 46 17 pm" src="https://user-images.githubusercontent.com/50668/47469244-897d0080-d7c5-11e8-9a3b-f874297b85da.png">

<img width="1198" alt="image 2018-10-24 at 7 44 47 pm" src="https://user-images.githubusercontent.com/50668/47469214-5470ae00-d7c5-11e8-8f8c-6c0888eab498.png">

Here's my config:
```
const {
  FuseBox,
  SassPlugin,
  CSSPlugin,
  WebIndexPlugin,
  Sparky,
  QuantumPlugin,
  EnvPlugin,
  JSONPlugin,
  SVGPlugin
} = require("fuse-box");
const GraphQLPlugin = require("fuse-box-graphql-plugin");

const express = require("express");
const path = require("path");
const { spawn } = require("child_process");

let production = false;

Sparky.task("build:renderer", () => {
  const fuse = FuseBox.init({
    homeDir: "src/renderer",
    output: "dist/renderer/$name.js",
    hash: production,
    target: "electron",
    cache: !production,
    sourceMaps: !production,
    plugins: [
      SVGPlugin(),
      JSONPlugin(),
      [".graphql|.gql", GraphQLPlugin()],
      EnvPlugin({ NODE_ENV: production ? "production" : "development" }),
      [SassPlugin(), CSSPlugin()],
      WebIndexPlugin({
        title: "FuseBox electron demo",
        template: "src/renderer/index.html",
        path: production ? "." : "/renderer/"
      }),
      production &&
        QuantumPlugin({
          bakeApiIntoBundle: "renderer",
          target: "electron",
          treeshake: true,
          removeExportsInterop: false,
          uglify: true
        })
    ]
  });
....
```

I tried using the CSSResourcePlugin but that didn't help. Any ideas on what I should try?

**Comment by nchanged** [comment]
@jimmybaker you should clear the cache
