### ISSUE TITLE
"Uncaught Package not found fusebox-hot-reload" + "cannot find module typescript"

### ISSUE THREAD

**Issue by urbanhop** [fuse-box/fuse-box#1053]
1. This is what my browser writes to the console when using

```
const { FuseBox, WebIndexPlugin } = require("fuse-box");
const fuse = FuseBox.init({
    homeDir : "src",
    target : 'browser@es6',
    output : "dist/$name.js",
    plugins : [
        WebIndexPlugin()
    ]
})
fuse.dev(); // launch http server
fuse.bundle("app").instructions(" > index.ts").hmr().watch()
fuse.run();
```

and an empty index.ts or an index.ts with a trivial line of code.

There is no package *fusebox-hot-reload*. What does this message mean?

2. In the console where "node fuse.js" runs, I read this error:

```
--- FuseBox 3.0.2 ---
{ Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    ...
```
I though fusebox has typescript integrated?

**Comment by devmondo** [comment]
Fuse has native support for typescript, but you need to install it obviously `npm install typescript` :)

**Comment by nchanged** [comment]
@urbanhop 
Greetings!
As per documentation it's required to install TypeScript
https://fuse-box.org/page/installation#add-to-project

Regarding that module, please clear the cache (remove `.fusebox` folder and try again

**Comment by urbanhop** [comment]
@devmondo : I have typescript installed :)
