### ISSUE TITLE
Browser build that uses `Buffer` isn't adding `base64-js`

### ISSUE THREAD

**Issue by SheetJSDev** [fuse-box/fuse-box#1055]
**Example index.ts:**

```typescript
import * as XLSX from 'xlsx';

console.log(XLSX.version);
```

**Example fuse.js:**

```js
const { FuseBox } = require("fuse-box");
const fuse = FuseBox.init({
  homeDir: ".",
  target:"browser",
  output: "$name.js"
});
fuse.bundle("client").instructions(">index.ts");
fuse.run();
```

**Example index.html:**

```html
<script src="client.js"></script>
```

**Expectation:** When serving the directory locally, the console should show a string

**Actual Behavior:** Error `Uncaught Package not found base64-js`

**Analysis:** The actual buffer shim requires base64-js:

```js
    var base64 = require("base64-js");
```

However, the `base64-js` module is not added to the bundle, as verified by manual inspection of the generated JS bundle.

**Comment by nchanged** [comment]
@SheetJSDev is it installed at all?

**Comment by nchanged** [comment]
As a temporary solution, you can use this https://fuse-box.org/page/configuration#auto-import

**Comment by SheetJSDev** [comment]
The workaround from https://fuse-box.org/page/configuration#natives works:

```js
const fuse = FuseBox.init({
  // ...
  target: "node",
  natives: {
    Buffer: false,
    stream: false,
    process: false
  }
});
```

**Comment by nchanged** [comment]
@SheetJSDev I believe you target is incorrect, `server` toggles them OFF automatically

**Comment by SheetJSDev** [comment]
To be absolutely sure, https://github.com/SheetJS/js-xlsx/blob/master/demos/fusebox/fuse.js works:

<details><summary>Code (click to show)</summary>

```js
const { FuseBox } = require("fuse-box");
const common_opts = {
  homeDir: ".",
  output: "$name.js"
};

const browser_opts = {
  target: "browser",
  natives: {
    Buffer: false,
    stream: false,
    process: false
  },
  ...common_opts
};

const node_opts = {
  target: "node",
  ...common_opts
};

const fuse1 = FuseBox.init(browser_opts);
fuse1.bundle("client").instructions(">sheetjs.ts"); fuse1.run();

const fuse2 = FuseBox.init(node_opts);
fuse2.bundle("server").instructions(">sheetjs.ts"); fuse2.run();
```

</details>

This issue is still relevant because the [`Buffer` shim depends on `base64-js` and `ieee754`](https://github.com/fuse-box/fuse-box/blob/master/modules/buffer/index.js) and neither are included in the bundle.  The [`ieee754`](https://unpkg.com/ieee754/index.js) and [`base64-js`](https://unpkg.com/base64-js/index.js) modules are simple enough to just add to the file in an IIFE:

```js
var base64 = (function() {
  var exports = {};
  // ... starting from line 2 of https://unpkg.com/base64-js/index.js
  return exports;
})();
var ieee754 = (function() {
  var exports = {};
  // ... code from https://unpkg.com/ieee754/index.js
  return exports;
})();
```

**Comment by nchanged** [comment]
@SheetJSDev that's quite interesting, I've just tried bundling 

```
import * as XLSX from 'xlsx';

console.log(XLSX.version);

```
with this config:

```
const fuse = FuseBox.init({
    homeDir : "src",
    output : "dist/$name.js",
    target : "browser",
    sourceMaps : true,
    cache : false,
    modulesFolder : "modules",
    plugins : [
        WebIndexPlugin(),
    ]
});

fuse.dev();

fuse.bundle("app")
    .watch()
    .hmr()
    .instructions(" > index.ts");
fuse.run();
```

And it works

**Comment by SheetJSDev** [comment]
@nchanged to be clear, in all cases FuseBox produces a bundle, but a simple page pulling in the bundle doesn't work.  Even the most recent example elicits the error (fuse-box 3.0.2 is the latest version on npm).  Squeezed the terminal output, browser error console and vim editor in one screenshot
![](https://user-images.githubusercontent.com/6070939/35288517-e833a5e0-0032-11e8-91db-41c7a7a9cc18.png)

The best fix IMHO, since none of the other shims lean on those modules, is to inject them by hand into [the buffer definition](https://github.com/fuse-box/fuse-box/blob/master/modules/buffer/index.js#L15-L16).

**Comment by nchanged** [comment]
Right, @SheetJSDev I cannot reproduce it

Please verify, I've just created a repository with the exact sample you provided
https://github.com/nchanged/fuse-box-tests/tree/master/xlsx

**Comment by nchanged** [comment]
<img width="546" alt="screenshot 2018-01-23 17 59 12" src="https://user-images.githubusercontent.com/1629088/35289279-2871c4b4-0067-11e8-83a1-c26cc58fa974.png">

**Comment by SheetJSDev** [comment]
The demo works when using a local fuse-box but not when the `require` pulls in the global version.  To reproduce, explicitly avoid installing fuse-box in the project directory:

```bash
sudo npm install -g fuse-box
git clone https://github.com/nchanged/fuse-box-tests/
cd fuse-box-tests/xlsx/
mkdir -p node_modules
npm install xlsx
node fuse.js
```

Tools like browserify and webpack work in both global and local deployments.  If fuse-box is not intended to be used, a warning should be added in the README somewhere.

**Comment by nchanged** [comment]
I see the problem, actually, it will work if you import a bundle

```js
require("fuse-box/es6")
``` 

But I will test it globally, it's fixable.
Do you think this issue can be closed? I think we need to create a different one.

**Comment by SheetJSDev** [comment]
Yes, make a new issue

**Comment by rvion** [comment]
@SheetJSDev 
@nchanged 

I an not finding the new related issue. 
I also have above problem when using a global/separated fuse-box install.


more generally, I think there is a small fix to do regarding module folders and how fuse-box detect them.

-------------------

I
```
FuseBox.init({
    modulesFolder: 'node_modules',
    ...
})
```

then

call `node ./fuse` giving it extra node_modules folder
`NODE_PATH=/c/Users/..../node_modules/ node ./fuse.js`

and base-64 ends up missing: 

```
Bundle "vendor"

└──  (0 files,  53 Bytes) default
└── buffer 45 kB (1 files)
└── flexlayout-react 172.7 kB (27 files)
└── fuse-box-css 1.3 kB (1 files)
└── json5 55.6 kB (1 files)
└── mobx-react 44.1 kB (1 files)
└── mobx 158.6 kB (1 files)
└── mousetrap 32.5 kB (1 files)
└── object-assign 2.2 kB (1 files)
└── parsimmon 14.6 kB (1 files)
└── prismjs 32.2 kB (5 files)
└── process 3.3 kB (1 files)
└── prop-types 4.1 kB (2 files)
└── react-dom 741.4 kB (3 files)
└── react 62 kB (3 files)
└── schedule 29.3 kB (6 files)
size: 1.4 MB in 1s 202ms
```
