### ISSUE TITLE
CSS Resource Plugin and HMR

### ISSUE THREAD

**Issue by zouloux** [fuse-box/fuse-box#1060]
Hi Fuse-Box team !

I think there is a little issue between HMR and CSS Resource.

We are creating an app with huge PNG files, and when HMR is triggered, png are cuts in half.
It took me a while to understand why but I think that HMR is triggered before CSS Resource has finished copying files. It works on small files because it's quick enough to be copied before the browser has the refresh trigger.

Another thing, is it possible to avoid CSS Resource copying resources each time we build ? Maybe it can check filesize or so to avoid useless copies.

Thanks for your help !

**Comment by nchanged** [comment]
@zouloux hi!
I've just checked the source code, it caches it. Could you provide an example where the described behaviour is reproduced?

**Comment by zouloux** [comment]
Sure, I'll try to make a simple example soon :)

**Comment by zouloux** [comment]
Hello ! I'm finally back with a solution with this issue.
I'm working on a fork of CSSResourcePlugin.

The `copyFile` function is asynchronous and, the Promise is not listened by the transform method, which allow Fuse to refresh the page without resources copied entirely when having huge resources.

This is how I patched it, sync file copying. Not great because it's blocking the main thread but it seems to be working :

```
const copyFile = (source, target) =>
{
	if (!fs.existsSync(source)) return;
	ensureDir(path.dirname(target));
	fs.copyFileSync(source, target);
};
```
