### ISSUE TITLE
Fusebox not including the javascript files with extension ".scss.js" into bundle

### ISSUE THREAD

**Issue by vjsrinath** [fuse-box/fuse-box#1062]
Hi, I am trying to use **office-ui-fabric-react** package in my application.

The **office-ui-fabric-react** includes many components where the styles are compiled into '.scss.js' file for scoping.

When bundling the dependencies of my application into vendor bundle it fails to load **require('./Image.scss')**;

I guess the fuse-box is not treating the above mentioned require call as js file. Because when I modified the require calls this way **require('./Image.scss.js')**, it worked.

**Update**
I made it to work by using extension overrides and changing the default package name like below,

```js
const fuse = FuseBox.int({...});
      const fabricContext = fuse.bundle('ui-fabric')
            .extensionOverrides('.js', '.scss.js')
            .instructions(`office-ui-fabric-react`).context;
fabricContext.defaultPackageName='office-ui-fabric-react';
```

Please confirm is this how it needs to be configured!!

**Comment by nchanged** [comment]
@vjsrinath Hi,
I see the problem, and your solution seems like it should work, although it's hacky. But in a way, it's a shame that people publish something like that.

I've noticed that the package is written in TypeScript, you could try pointing your import directly to a typescript file (FuseBox supports that) and see how that pans out, however, it might not work because of how the actual package is built and published to NPM

**Comment by vjsrinath** [comment]
@nchanged  Thanks for such a quick response.
I opted for a much simpler solution as overriding extensions messes things up with actual js modules.
I used ReplacePlugin to replace the .scss to .scss.js. This worked like a charm.
 ``` js
fuse.bundle('ui-fabric')
            .plugin(ReplacePlugin({ '.scss': '.scss.js' }))
            .instructions(`office-ui-fabric-react`);
```

**Comment by devmondo** [comment]
@viankakrisna great workaround

**Comment by leon-andria** [comment]
I would be interested to get details about you fuse config.
And to know who is requiring images.scss?

**Comment by vjsrinath** [comment]
@leon-andria Given below is the fuse config,

 ``` js
const fuse = FuseBox.init({
            alias: {
                utils: '~/utils',
                lib: '~/lib',
                modules: '~/modules',
                scss: '~/scss',
                store: '~/store',
                reducers: '~/reducers',
                types: '~/types'
            },
            homeDir: 'src',
            output: 'dist/$name.js',
            tsConfig: 'tsconfig.json',
            useJsNext: ['react', 'react-dom'],
            polyfillNonStandardDefaultUsage: ['react', 'react-dom'],
            sourceMaps: !this.isProduction,
            target: 'browser@es5',
            plugins: [
                EnvPlugin({
                    NODE_ENV: this.isProduction ? 'production' : 'development',
                    BASE_NAME: baseName,
                    BASE_PATH: basePath
                }),
                SVGPlugin(),
                [/\.css$/,
                    CSSResourcePlugin({
                        dist: 'dist/assets/resources',
                        resolve: path => `${basePath}assets/resources/${path}`
                    }),
                    CSSPlugin(this.isProduction ? {
                        group: 'vendor.css',
                        outFile: `dist/vendor.css`,
                        inject: false,
                        minify: this.isProduction
                    } : {})
                ],
                [
                    /src.*\.scss$/,
                    SassPlugin({ importer: true, macros: { "$scss": "src/scss" } }),
                    CSSResourcePlugin({
                        dist: 'dist/assets/resources',
                        resolve: path => `${basePath}assets/resources/${path}`
                    }),
                    CSSPlugin(this.isProduction ? {
                        group: 'app.css',
                        outFile: `dist/app.css`,
                        inject: false,
                        minify: this.isProduction
                    } : {})
                ],

                WebIndexPlugin({
                    template: 'src/index.html',
                    title: 'Portal Builder',
                    target: 'index.html'
                }),
                this.isProduction &&
                QuantumPlugin({
                    css: true,
                    bakeApiIntoBundle: 'vendor',
                    treeshake: false,
                    uglify: true,
                    replaceProcessEnv: true
                })
            ]
        });
 fuse.bundle('vendor').instructions(`~/index.tsx - office-ui-fabric-react`);
        fuse.bundle('ui-fabric')
            .plugin(ReplacePlugin({ '.scss': '.scss.js' }))
            .instructions(`office-ui-fabric-react`);
 fuse.bundle('app').instructions(' !> [index.tsx]');
```
Many of the components from office-ui-fabric-react package use this approach. Take a look the at link below,
[](https://unpkg.com/office-ui-fabric-react@5.43.1/lib/components/Image/Image.js)

**Comment by nchanged** [comment]
@vjsrinath 
Try `fuse-box@3.1.0-next.18` You can remove all options from `CSSPlugin` and add `QuantumPlugin({css : true})`

**Comment by leon-andria** [comment]
@vjsrinath I saw it, and now i can the workaround is not right. For me, i think in your config, its not needed to specify the path for testing, scss is already matched by the plugin.
Otherwise i consider that as fuse bug.

**Comment by leon-andria** [comment]
Can you guys re open this issue?

**Comment by vjsrinath** [comment]
@nchanged I tried version **fuse-box@3.1.0-next.18** but compilation failed with following error,

TypeError: Cannot read property 'startsWith' of undefined
    at walker (D:\_workarea\tfs\Users\Srinath\portal-builder\node_modules\fuse-box\plugins\stylesheet\CSSResourcePlugin.js:104:21)
    at contents.replace (D:\_workarea\tfs\Users\Srinath\portal-builder\node_modules\fuse-box\lib\CSSUrlParser.js:24:30)
    at String.replace (<anonymous>)
    at Function.walk (D:\_workarea\tfs\Users\Srinath\portal-builder\node_modules\fuse-box\lib\CSSUrlParser.js:22:25)
    at CSSResourcePluginClass.transform (D:\_workarea\tfs\Users\Srinath\portal-builder\node_modules\fuse-box\plugins\stylesheet\CSSResourcePlugin.js:160:53)    at tasks.push (D:\_workarea\tfs\Users\Srinath\portal-builder\node_modules\fuse-box\core\File.js:162:63)
    at realm_utils_1.each.promise (D:\_workarea\tfs\Users\Srinath\portal-builder\node_modules\fuse-box\core\File.js:173:66)
    at iterate (D:\_workarea\tfs\Users\Srinath\portal-builder\node_modules\realm-utils\dist\commonjs\each.js:79:34)
    at D:\_workarea\tfs\Users\Srinath\portal-builder\node_modules\realm-utils\dist\commonjs\each.js:92:16
    at new Promise (<anonymous>)

**Comment by vjsrinath** [comment]
@leon-andria Thanks, I have removed the testing conditions.

**Comment by leon-andria** [comment]
Does it work now by removing also the replaceplugin?

**Comment by nchanged** [comment]
@vjsrinath that's something new, because CSSREsourcePlugin has gone through some major modifications in 3.1.0

Can you reproduce it in a repository?

**Comment by vjsrinath** [comment]
@leon-andria Nope, it didn't work.

@nchanged Do you want me to create a separate repository and reproduce the scenario?

**Comment by nchanged** [comment]
That would be great!
