### ISSUE TITLE
[Docs] homeDir property is confusing

### ISSUE THREAD

**Issue by wujekbogdan** [fuse-box/fuse-box#1069]
One of the first things mentioned in the documentation is the `homeDir` property. It's not clearly said that this is a setting for the TS compiler only. So it would be good to mention that plugins' paths are still relative to the `fuse.js` config file, not to the `homeDir`.

**Comment by nchanged** [comment]
@wujekbogdan I think you got it wrong. `homeDir` is the root of your project (the actual js/ts project)

**Comment by wujekbogdan** [comment]
I got it wrong, that's why I've created this report :)
It would be good to make it clear in docs what the `homeDir` property is used for.

**Comment by nchanged** [comment]
@wujekbogdan you can help out by submitting a PR ;-)

**Comment by wujekbogdan** [comment]
@nchanged 
I think I could, but I'm still not sure if I understand it correctly. 

- Does fuse read the `tsconfig.json` from the project root dir even if the `homeDir` is set to something else (for example `src`)?
- How about plugins? Where do they look for their configurations? For example PostCSS plugin. By default it reads the config file (`.postcss.config.js`) from the project root. Where does it read the configuration from if the `homeDir` is set to, let's say, `src`?

**Comment by nchanged** [comment]
* Tsconfig: searches it it the `homeDir` upwards until appRoot is found (relative to node_modules)
`root/src/tsconfig.json`
`root/tsconfig.json`

^ both will be found

* PostCSS behaves like it used to behave (according to the PostCSS doc). 

Here is the logic here:

https://github.com/fuse-box/fuse-box/blob/452984511b5236e97184dd75135b2dc610fbb090/src/plugins/stylesheet/PostCSSPlugin.ts#L83-L97

**Comment by nchanged** [comment]
Will close this for now.
