### ISSUE TITLE
[Docs] Web Index Plugin - explain what $bundles and what macros are

### ISSUE THREAD

**Issue by wujekbogdan** [fuse-box/fuse-box#1072]
I've spotted 4 issues:
- It's not explained what bundles are. An assumption is made that a user knows what do you mean by *bundle*. IMO it would be good to say that a bundle is a compiled JS/TS file.
- You use the *macro* term not explaining what macros are.
- It's not very clear that `$bundles` is just a string that can be put anywhere in the custom HTML template.
- It's not very clear that `<script>` tags are added automatically by the plugin in place of `$bundles` strings

**Comment by nchanged** [comment]
Please make a PR, that would help a lot!

**Comment by wujekbogdan** [comment]
@nchanged 

I will :) Not only regarding this issue but also regarding some other docs-related reports that I created.

**Comment by nchanged** [comment]
Do you mind closing this issue?

**Comment by wujekbogdan** [comment]
@nchanged 
Np. I'll ping you when the PR is done.
