### ISSUE TITLE
I'm not able to setup Vue.js project with vue-class-component decorator

### ISSUE THREAD

**Issue by wujekbogdan** [fuse-box/fuse-box#1073]
I'm not able to setup Vue.js build with [vue-class-component](https://github.com/vuejs/vue-class-component) decorator.

The fuse config is written by me from scratch. I didn't copy/paste any config. The Vue class component is set up based on the example from the official [Vue.js TypeScript Support](https://vuejs.org/v2/guide/typescript.html) page.

Here's what I can see in the console:
```
tslib@1.9.0:67 Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at Object.__extends (tslib@1.9.0:67)
    at script.ts:7
    at Number.<anonymous> (script.ts:13)
    at c (fuse-box-css@0.0.1:47)
    at y.require (fuse-box-css@0.0.1:47)
    at Number.<anonymous> (index.ts:2)
    at c (fuse-box-css@0.0.1:47)
    at Function.r.import (fuse-box-css@0.0.1:47)
    at fuse-box-css@0.0.1:47
```

I gues that an issue is related somehow to imports because PHPStorm shows me the following error in the console: `Error:(2, 17) TS2307: Cannot find module './components/App.vue'.`

---

This is my setup:

**index.ts**
``` javascript
import Vue from 'vue';
import App from './components/App.vue';
import './scss/app.scss';

new Vue({
  el: '#js--app',
  components: {
    App,
  },
});
```

**App.vue**
``` html
<template>
    <button @click="onClick">Click!</button>
</template>

<script lang="ts">
  import Vue from 'vue';
  import Component from 'vue-class-component';

  @Component({
    template: '<button @click="onClick">Click!</button>'
  })
  export default class App extends Vue {
    message: string = 'Hello!';

    onClick(): void {
      window.alert(this.message)
    }
  }
</script>

```

**fuse.js**
``` javascript
const path = require('path');
const {
  FuseBox,
  WebIndexPlugin,
  SassPlugin,
  CSSResourcePlugin,
  CSSPlugin,
  PostCSSPlugin,
  QuantumPlugin,
  ImageBase64Plugin,
  VueComponentPlugin
} = require('fuse-box')
const {src, task, context} = require('fuse-box/sparky')

class Builder {
  constructor () {
    this.isProduction = false
  }

  setProduction () {
    this.isProduction = true
  }

  getFuse () {
    return FuseBox.init({
      homeDir: 'src',
      target: 'browser@es5',
      output: 'dist/$name.js',
      sourceMaps: !this.isProduction,
      useTypescriptCompiler : true,
      plugins: [
        VueComponentPlugin(),
        WebIndexPlugin({
          template: 'src/index.html'
        }),
        [
          'src/scss/app.scss',
          SassPlugin(),
          CSSResourcePlugin(),
          PostCSSPlugin(),
          CSSPlugin({
            inject: false,
            outFile: (file) => {
              return `./dist/css/${path.basename(file)}`;
            },
          })],
        ImageBase64Plugin(),
        this.isProduction && QuantumPlugin({
          bakeApiIntoBundle: 'app',
          uglify: true,
          css: true,
        })
      ]
    })
  }

  createBundle (fuse) {
    const app = fuse.bundle('app')

    if (!this.isProduction) {
      app.hmr()
      app.watch()
    }

    app.instructions('> index.ts')

    return app
  }
}

context(Builder)

task('clean', async () => {
  await src('./dist')
    .clean('dist/')
    .exec()
})

task('default', ['clean'], async context => {
  const fuse = context.getFuse()
  fuse.dev()
  context.createBundle(fuse)
  await fuse.run()
})

task('build', ['clean'], async context => {
  context.setProduction()
  const fuse = context.getFuse()
  context.createBundle(fuse)
  await fuse.run()
})

```

**tsconfig.json**
``` json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "ES5",
    "sourceMap": true,
    "inlineSources": true,
    "importHelpers": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true
  }
}
```

---

Here's the repository so that you could reproduce: https://github.com/wujekbogdan/fuse-vue-ts

**Comment by nchanged** [comment]
@wujekbogdan you can't expect it to work as it's described in the official documentation. The plugin is written in Webpack and has a direct dependency on it.

 We worked hard to deliver a similar plugin.

Here is the seed.
https://github.com/fuse-box/fuse-box-vue-seed

I will close this issue because you are using FuseBox plugin incorrectly. Please read up on the documentation, I will leave a short snippet here

https://github.com/fuse-box/fuse-box-vue-seed/blob/722b64e46f65955cb969c1e28897614378d0e05d/fuse.js#L32-L42

just poke me on Gitter ;-)

**Comment by nchanged** [comment]
UPD: the actual error might be related to the missing `allowSyntheticDefaultImports` flag with the latest beta
https://fuse-box.org/page/configuration#allowsyntheticdefaultimports

OR `polyfillNonStandardDefaultUsage` in 3.0.2

**Comment by wujekbogdan** [comment]
There were 2 issues:

1. missing `allowSyntheticDefaultImports: true`
2. The initialization code in the `index.ts` file wasn't using the render function. The Vue build imported by the import statement is a [runtime-only build](https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only).

---
I've committed a fix to the repo: https://github.com/wujekbogdan/fuse-vue-ts

**Comment by Lolhomme** [comment]
Hey! guys. I got some issues too with vue and fuse box.
It's just a HelloWorld but in the end I would like migrate an entire webpack app into fusebox app.

A link to my repo:  https://github.com/Lolhomme/fuse-box-testApp

On Firefox, on the dev tool console: "[Vue warn]: Cannot find element: #app"

**Comment by nchanged** [comment]
@Lolhomme hi
there a link above with the fix 
https://github.com/wujekbogdan/fuse-vue-ts/blob/master/src/index.ts#L6

I am no VUE expert, but I think that is it.

**Comment by Lolhomme** [comment]
@nchanged thanks but the fix didn't help me, but posting made me realise my mistake.

Thanks for your work and your time.
