### ISSUE TITLE
[Improvement] Quantum: bakeApiIntoBundle select more than one bundle

### ISSUE THREAD

**Issue by CzBuCHi** [fuse-box/fuse-box#1077]
As title says, but more preciselly i wanna to bake api into every created bundle.

Currently only way to achieve that is to call FuseBox.init for each bundle separately.

my proposal is to thread `bakeApiIntoBundle` as `string | string[] | true | undefined` and use something like this to determine, if api needs to be baked into bundle:

```js
function shouldBakeIntoBundle(
  bundleName: string,
  bakeApiIntoBundle: string | string[] | true | undefined,
): boolean {
  if (bakeApiIntoBundle === true) {
    return true;
  }

  if (typeof bakeApiIntoBundle === 'string') {
    return bakeApiIntoBundle === bundleName;
  }

  if (Array.isArray(bakeApiIntoBundle)) {
    return bakeApiIntoBundle.indexOf(bundleName) !== -1;
  }

  return false;
}
```

**Comment by nchanged** [comment]
@CzBuCHi Hi
Sure, I don't mind the improvement

Do you think you can make a PR?

**Comment by CzBuCHi** [comment]
ya ... i send something at evening ...

**Comment by CzBuCHi** [comment]
Just forked repo and tryied to run `npm test` (after `npm i`). Got bunch of test-related errors, which most of them can be fixed by this:
`npm i babel-core babel-preset-latest buble coffee-script marked node-sass pug stylus uglify-es vue vue-class-component vue-hot-reload-api vue-server-renderer vue-template-compiler vue-template-es2015-compiler`

After that only 2 errors remains:

**tests/PathMaster.test.js**
- "Should handle sub module with @ operator"
  -  `Expected undefined to equal bundles/core.umd.js`

**tests/dynamic_imports_test/CodeSplittingFileIntegrity.test.ts**
- "Should not split a library"
  - `Error: Expected string "// jwt-decode/lib/index.js" was not found` (test runner terminates here)


I dont wanna mess with any code before these gets fixed, but dont know how to fix first one and my 'fix' for seond one (commenting out lines 800-802) feels just wrong ....

Can u please kick me in right direction with these? :)

**Comment by nchanged** [comment]
@CzBuCHi `gulp installDevDeps` ;-)
