### ISSUE TITLE
Browser Field warnings for angular packages targeting electron

### ISSUE THREAD

**Issue by Kaffiend** [fuse-box/fuse-box#1080]
Warning for `zone.js`, and a few other packages, like peers of `socket.io` give warnings when target is set to `electron`, yes they are browser fields and browser packages but its irrelevant to electron's renderer process.

**Comment by CzBuCHi** [comment]
Same for "react-dom". Quick-fix would be modify function `isBrowserTarget` in `src\core\WorkflowContext.ts`:
```ts
public isBrowserTarget() {
    return this.target === "browser"; // || this.target === "electron";
}
```

but i have no idea what side effect that would have and sadly no time to investigate :( ...

**Comment by nchanged** [comment]
I think this has been resolved. ping?!
