### ISSUE TITLE
Disabling strict mode

### ISSUE THREAD

**Issue by marcinj1** [fuse-box/fuse-box#1087]
Hello,
is it possible to disable strict mode? I have a problems with:
Acorn error: Deleting local variable in strict mode

**Comment by devmondo** [comment]
if you are using typescript with fuse you can disable this option `noImplicitUseStrict`
https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by marcinj1** [comment]
Well, my code is written in JS. I tried with "noImplicitUseStrict": true and "noImplicitUseStrict": false in tsconfig.js but no luck. 

My confing:
`"module": "commonjs",
    "target": "ES5",
    "jsx": "react",
    "importHelpers": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noImplicitUseStrict": true`

**Comment by nchanged** [comment]
@marcinj1 actually it's all correct. NodeJS would give you a runtime error, that's why acorn cannot yield it. You either remove `use strict;` or fix that offending line.

**Comment by marcinj1** [comment]
Ok, thank you.

**Comment by nchanged** [comment]
If you don't mind, I will close the issue.
