### ISSUE TITLE
Error ^3.1.0-next.23 when using quantum solveComputed

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box#1089]
Main repo
https://github.com/vegarringdal/mframejs-fuseboxtest

**Watch(success)  `node fuse`**
https://github.com/vegarringdal/mframejs-fuseboxtest/blob/master/watch.js

**Build (failing) `node watch`**
https://github.com/vegarringdal/mframejs-fuseboxtest/blob/master/build.js

Trying to run this/solve this part:
https://github.com/vegarringdal/mframejs-fuseboxtest/blob/master/build.js#L66-L71

Where its failing in code... (dynamic loading)
https://github.com/vegarringdal/mframejs-fuseboxtest/blob/master/src/sample/sample.ts#L31-L48

This is getting html file title from attribute, and tried to use require
But getting error after running it through quantum
![image](https://user-images.githubusercontent.com/2901416/35754700-adb40100-0864-11e8-800d-fe590f3de0d4.png)

tried without uglify, its like the mapping is failing ?

![image](https://user-images.githubusercontent.com/2901416/35754921-895cd8bc-0865-11e8-98f8-f59f582800ea.png)

**Comment by vegarringdal** [comment]
nothing called @fsx.p ..

![image](https://user-images.githubusercontent.com/2901416/35755217-a20d3040-0866-11e8-8109-4a8e8c7a5728.png)

**Comment by vegarringdal** [comment]
@devmondo @nchanged 

is it something Im doing wrong ? (I hope so...)

**Comment by vegarringdal** [comment]
Did some more testing
Set console log to this:
`console.log(statement)`

![image](https://user-images.githubusercontent.com/2901416/35768306-eac04fe6-08f9-11e8-9417-9ca5b7b26a3d.png)

So by changing to this:

```
api: (core) => {
                    core.solveComputed("default/sample/sample.js", {
                        mapping: "*.html",
                        fn: (statement, core) =>{
                            console.log(statement)
                            let x  = statement.setExpression(`"default/sample/" + name + ".html"`)
                            
                        }
                    });
                }
```

it works.

so looks like mapping needs to be relative to file loading it...

**Comment by vegarringdal** [comment]
ok, I was wrong

I moved html files to a root folder called "cool"

to make it work I needed to do this:
```
api: (core) => {
                    core.solveComputed("default/sample/sample.js", {
                        mapping: "*.html",
                        fn: (statement, core) =>{
                            console.log(statement)
                            let x  = statement.setExpression(`"default/cool/" + name + ".html"`)
                            
                        }
                    });
                }
```

**Comment by vegarringdal** [comment]
update:

```js
            api: (core) => {
                    core.solveComputed("default/sample/sample.js", {
                        mapping: "cool/*.html",
                        fn: (statement, core) =>{
                            console.log(statement)
                            let x  = statement.setExpression(`"default/cool/" + name + ".html"`)
                            
                        }
                    });
                }

```
if I change mapping to this it wont work
so Im kinda wondering how the mapping really works ?

**Comment by nchanged** [comment]
@vegarringdal you build a map of files
`"default/cool/hello.html" : 1` by setting a mapping `cool/*.html`, after that you modify the expression to map the exact file id by a string.

**Comment by vegarringdal** [comment]
@nchanged if I have my html files in "sample" or "cool" folder I need to have mapping set to only `"*.html"` anything else breaks it..

**Comment by vegarringdal** [comment]
Folder structure:
![image](https://user-images.githubusercontent.com/2901416/35769992-e1093872-0913-11e8-87b7-3aa7cbdbbdfc.png)

code in sample.js under `sample` folder
![image](https://user-images.githubusercontent.com/2901416/35769998-f87a3c22-0913-11e8-81b1-483985e3fa77.png)


Build code: **(working)**
@nchanged  Why do I need to have it set to just `"*.html"` and not `"cool/*.html"`
![image](https://user-images.githubusercontent.com/2901416/35770004-154cda80-0914-11e8-89ab-23ea1abb480c.png)

**Comment by vegarringdal** [comment]
Just trying to understand this part better, since the docs threw me in the wrong direction.

Also tried similar with import(), I then had to copy the all the html files over, is this since its html and not js/ts ? since when I reference a module with import (not dynamic) it creates own bundle.

**Comment by nchanged** [comment]
@vegarringdal regarding the pathing, I don't really know, it might be a bug. Are you on windows xD ?

**Comment by vegarringdal** [comment]
yes, on windows :-)

Im mostly asking so docs dont trick others too, and in case its bug :-)
