### ISSUE TITLE
Express integration

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#109]
The project and the documentation looks amazing! I canhave wait to get my hands on this. What is not clear in the documentation is the integration of fuse box with express. Normally, it is express that loads the middleware (e.g. webpack) yet in your documentation you mention to load express middleware from fuse box. I am just not sure how can that be done. Would you be keen on creating a sample repo with express integration?

**Comment by nchanged** [comment]
@tomitrescak thank you!
Of course! we will create something like this. But in the meantime please take a look at this [section](http://fuse-box.org/#integrate-with-existing-app)

**Comment by devmondo** [comment]
@tomitrescak could you please check our new  [express seed](https://github.com/fuse-box/fuse-box-express-seed) :)

**Comment by tomitrescak** [comment]
@devmondo that great! Truly. It's amazing! ;) Thanks.

Over the weekend I'll put your solution to a good test with our large project (around 900+ typescript files + 12MB javascript codebase).
