### ISSUE TITLE
CSSResourcePlugin - resources are not being copied to ./dist

### ISSUE THREAD

**Issue by wujekbogdan** [fuse-box/fuse-box#1090]
In my SCSS file I import some SCSS files from `node_modules`

``` scss
@import "../../node_modules/photoswipe/src/css/main.scss";
@import "../../node_modules/photoswipe/src/css/default-skin/default-skin";
```

These files use some resources from the `"../../node_modules/photoswipe/src/css/default-skin/` directory.

If `CSSResourcePlugin()` plugin is not activated then in the output `app.css` file the path remains unchanged - as expected.
When the `CSSResourcePlugin()` is enabled then I can see the paths  in the output CSS `app.css` being changed, but no images are copied to `./dist/`

The plugin is initialized as follows:
``` javascript
CSSResourcePlugin({
  dist: './dist/resources/',
}),
```

The `./dist/resources/` is created, but it's empty.

It looks like a bug.

**Comment by wujekbogdan** [comment]
I have no idea what I did, but now it works fine and files are being copied to `./dist/resources/` properly.  Maybe I messed up the plugins order? Sorry for the confusion.

**Comment by nchanged** [comment]
@wujekbogdan warning yes, we should give the info on which file, which URL has failed to resolve.
