### ISSUE TITLE
__dirname points to "/" on target server

### ISSUE THREAD

**Issue by maximkott** [fuse-box/fuse-box#1093]
When I bundle a project using target "server" the "__dirname" variable always points to "/", is there a way to bypass this? I'll gladly provide an example project if necessary.

**Comment by nchanged** [comment]
hi @maximkott could you provide an example where this is used and cannot be replaced with `path.resolve()`

**Comment by maximkott** [comment]
Hi @nchanged , there you go https://github.com/maximkott/fusebox-1093

**Comment by maximkott** [comment]
I've stumbled upon this problem in this sample project, https://github.com/maximkott/fusox-examples/blob/master/electron/src/index.ts#L16, while building a cli wrapper for fuse-box https://github.com/maximkott/fusox

**Comment by bkniffler** [comment]
Any news? I'd expect __dirname to behave like normal in a node target build.

**Comment by nchanged** [comment]
I will make sure to give it a proper test in v4 which is coming soon )
