### ISSUE TITLE
ImageBase64Plugin doesn't catch images

### ISSUE THREAD

**Issue by steppefox** [fuse-box/fuse-box#1095]
After a new release 3.1.1, ImageBase64Plugin + TypeScript does not process images. At the beginning everything looks fine:

![image](https://user-images.githubusercontent.com/4667275/35904773-35d77a0e-0c06-11e8-842d-5c5d7f41ddfe.png)

But scroll down and see:

![image](https://user-images.githubusercontent.com/4667275/35904827-6c72005c-0c06-11e8-8885-3bae2438e655.png)

Looks like TS compiler trying to resolve png before ImageBase64Plugin.

Here is TS Config:

```
{
    "compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "jsx": "react",
        "module": "commonjs",
        "noImplicitAny": true,
        "outDir": "./dist/",
        "preserveConstEnums": true,
        "removeComments": true,
        "sourceMap": true,
        "target": "ES6"
    },
    "include": [
        "./src/**/*"
    ],
    "types": ["jest"]
}
```

And module declarations to avoid lint errors:

```
declare module '*.jpeg';
declare module '*.jpg';
declare module '*.gif';
declare module '*.png';
declare module '*.svg';
```

**Comment by nchanged** [comment]
@steppefox but does it break your build?

**Comment by steppefox** [comment]
@nchanged nope, but as result it doesn't include any PNG assets. In dist js file, modules for that files are empty, no base64 strings =(

**Comment by nchanged** [comment]
@steppefox oh, that's a regression. I will see it fixed and release a patch soon enough.

**Comment by nchanged** [comment]
@steppefox are you sure that it's not working?
I've just tested it

```
___scope___.file("client/assets/characters.png", function(exports, require, module, __filename, __dirname){
module.exports.default = "data:image/png;base64,iV" ......});
```

**Comment by nchanged** [comment]
@steppefox please verify the fix in `fuse-box@3.1.3-next.1`

**Comment by steppefox** [comment]
@nchanged 👍  it works!

**Comment by nchanged** [comment]
https://github.com/fuse-box/fuse-box/releases/tag/v3.1.3
