### ISSUE TITLE
Support for AngularJS?

### ISSUE THREAD

**Issue by TobiasTimm** [fuse-box/fuse-box#1099]
Does fuse-box support AngularJS?

**Comment by nchanged** [comment]
@TobiasTimm https://github.com/fuse-box/angular2-example

but it's an outdated version, feel free to update it, we need help!

**Comment by TobiasTimm** [comment]
@nchanged sry  I mean the old Angular so AngularJS or angular 1

**Comment by nchanged** [comment]
@TobiasTimm well that's javascript right? Hence it's supported ;-)

**Comment by TobiasTimm** [comment]
@nchanged Ah okay :smile: I'm asking because in webpack you need something like the https://www.npmjs.com/package/ng-annotate-webpack-plugin to support the //ngInject comments for the Dependency Injection and also a ng-cache-loader for the HTML-Templates. You don't need them, but it's a lot easier if the bundler handles it.

**Comment by nchanged** [comment]
@TobiasTimm unfortunately, we don't have that plugin ;-( If you are interested, you could help us create a plugin!

I will close this issue, for now, feel free to create a separate one.
