### ISSUE TITLE
HotReloadPlugin

### ISSUE THREAD

**Issue by leon-andria** [fuse-box/fuse-box#110]
In this line https://github.com/fuse-box/fuse-box/blob/master/src/plugins/HotReloadPlugin.ts#L13, it looks like having dependencies to "fusebox-hot-reload" but never see any package about this ?
Does this is a special convention ? Good to have an idea what does it mean.

**Comment by nchanged** [comment]
Yeah, it comes from custom fusebox modules

https://github.com/fuse-box/fuse-box/tree/master/assets/libs

**Comment by devmondo** [comment]
maybe some more documentation on that part ?

**Comment by nchanged** [comment]
definitely!

**Comment by leon-andria** [comment]
Guys,
Think it in this way when we come to contribute. How we can guess that the piece of code that i have just highligthed is coming from "/assets/libs" ?
Does a guidance or code rules are needed ?
When i read a code, it should not be magic or put a comment on the code that de dependencies come from "/assets/libs".

**Comment by devmondo** [comment]
@leon-andria fully agree, but FuseBox has this feature  that called custom modules folder, together with libs folder you can think of them as another npm_modules folder but with higher priority
