### ISSUE TITLE
Sparky exports all type definitions as 'any', 

### ISSUE THREAD

**Issue by danielbodart** [fuse-box/fuse-box#1101]
I'm use `ts-node` so I can have a type checked `fuse.ts` which is highly recommended. All of the standard FuseBox API has the correct types except that `sparky/index.d.ts` which is about as un-typed as possible:

```
export { npmPublish, tsc, bumpVersion } from './SparkyUtils'; // This is all typed
export declare const src: any;
export declare const watch: any;
export declare const task: any;
export declare const context: any;
export declare const exec: any;
export declare const init: any;
export declare const fuse: any;
```

I'm not sure if this a limitation of the Typescript compiler as the methods are all static methods on Sparky, but maybe it can be fixed or a bug logged with the Typescript compiler team.

Many thanks

**Comment by nchanged** [comment]
Thanks, I will check what's wrong with the typings

**Comment by danielbodart** [comment]
I've added a simple fix based on the recommendations given here: https://basarat.gitbooks.io/typescript/docs/tips/bind.html
