### ISSUE TITLE
AngularJS $templateCache

### ISSUE THREAD

**Issue by TobiasTimm** [fuse-box/fuse-box#1102]
I've started to implement one of the plugins mentioned in  #1099.

For that I've created a NgTemplatePlugin in my fork 
https://github.com/TobiasTimm/fuse-box

The tests worked pretty well, unfortunately in my test project 
https://github.com/TobiasTimm/angularjs-fuse-box 
the application or fuse (I don't know) is unable to find my generated `templates.js`.

I don't really know if my approach is the correct one :smile:
Maybe you guys can help me :smiley:

**Comment by nchanged** [comment]
Hi @TobiasTimm Great idea!

But I am not able to launch it because you are importing FuseBox from dist, which 
1) Isn't there
2) You should use dev environment for development as described [here](https://github.com/fuse-box/fuse-box/blob/master/.github/CONTRIBUTING.md#developing)

**Comment by TobiasTimm** [comment]
@nchanged I've pushed my playground within the fuse-box repo
https://github.com/TobiasTimm/fuse-box

**Comment by nchanged** [comment]
@TobiasTimm 
You got it 99% right ;-)

The problem is that you require the template like that `./template.js` which is a relative path, therefore, if you target file located somewhere else by root, you will get an error. To fix that, you should use tilde `~`

```
file.alternativeContent = `require("~/${
      this.bundleName
    }");\nmodule.exports.default = '${file.info.fuseBoxPath}';`;
``

I just tried it, and it works like a charm.

**Comment by TobiasTimm** [comment]
@nchanged thanks :smile: 
I will change it at home and think a bit about a way to implement the `ng-annotate` plugin. Because the project is deprecated and there is only a babel-plugin, but nothing for typescript unfortunately.

**Comment by TobiasTimm** [comment]
@nchanged I've created an external NgTemplatePlugin now.

Would be cool, if you can reference it.

https://github.com/TobiasTimm/fuse-box-ng-template-plugin

Also I've created an example project for angular.js, if you want to copy it for the examples section.

https://github.com/TobiasTimm/fuse-box-angularjs-example

Thanks for your help :smile:

**Comment by nchanged** [comment]
@TobiasTimm Great job!
I've added it to the plugin list
https://fuse-box.org/page/ngtemplateplugin
