### ISSUE TITLE
Service Worker: XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by samirbr** [fuse-box/fuse-box#1108]
I'm getting a `XMLHttpRequest is not defined` error when bundling a service worker. The error is due `XMLHttpRequest` not being defined in `ServiceWorkerGlobalScope`.

FuseBox checks whether the global scope is `Window` or `WorkerGlobalScope`. 

Evaluate the possibility to add `serviceworker` (and maybe `webworker`) target(s) to the bundling system.

**Update:** XMLHttpRequest API is currently deprecated. Evaluate refactoring [$async](https://github.com/fuse-box/fuse-box/blob/master/src/loader/LoaderAPI.ts#L343:L376) to use Fetch API.

**Comment by nchanged** [comment]
@samirbr thanks for submitting the issue. Fetch API is cool, but it's not supported by IE11, which is the latest (and the last) of IE.

Regarding your issue please provide some example with description (expectations). We open for PRs too ;-)

**Comment by samirbr** [comment]
Actually I a managed to make it work. I think one of my dependencies was causing the error. [Here](https://github.com/samirbr/fusebox-serviceworker-example) is a functional example.
My suggestion is use FetchAPI and import a polyfill for UE11. I might take a look into a PR for that ;-).

**Comment by nchanged** [comment]
@samirbr that would be awesome!!! I will close this issue for now.
