### ISSUE TITLE
Process is missing in VueComponentPlugin on browser

### ISSUE THREAD

**Issue by orblazer** [fuse-box/fuse-box#1110]
Hello, after fix this plugin on electron i have realised that on target browser the bug is persist.
This bug is generate because the `process` dependencies is not loaded. We need add depencies on the plugins.

**For HMR:**
Add this on [VuePlugin.ts#L26](https://github.com/fuse-box/fuse-box/blob/master/src/plugins/vue/VuePlugin.ts#L26)
```js
this.dependencies = ['process', 'vue-hot-reload-api', 'vue']
```
**For without HMR:**
Add this on [VuePlugin.ts#L26](https://github.com/fuse-box/fuse-box/blob/master/src/plugins/vue/VuePlugin.ts#L26)
```js
this.dependencies = ['vue']
```

For this, i want make another PR but i don't know how to detect the target and if HMR is enabled. This is my question.
Thanks.

**Comment by nchanged** [comment]
Following:
1) `context.target`
2) `producer.hmrInjected`

**Comment by orblazer** [comment]
I progess on the bug but i have error and i don't know the reason.
The plugin `vue-hot-reload-api` don't add in bundled file because `shouldIgnoreDeps` in [ModuleCollection#L373](https://github.com/fuse-box/fuse-box/blob/master/src/core/ModuleCollection.ts#L373) is true for unknown reason..

**Comment by orblazer** [comment]
Ok ok, for my bug i know why, this is because i add `vue-hot-reload-api` when `producerEnd` is called because i don't know how to detect if HMR   is enabled on function `init`. Thanks you if you can light me :)

**Comment by nchanged** [comment]
I hope you don't mind if close this issue.
