### ISSUE TITLE
[BROKEN] https://fuse-box.org/page/uglifyes-plugin

### ISSUE THREAD

**Issue by TheGrimSilence** [fuse-box/fuse-box#1112]
The page for UglifyESPlugin is broken, only going as far as Install
![fusebox - blazing fast js bundler_loader with super powers - google chrome 2_16_2018 9_02_26 pm](https://user-images.githubusercontent.com/11479772/36338168-edaada10-135c-11e8-955b-440390e4bdcc.png)

**Comment by orblazer** [comment]
This is same for [VueComponentPlugin](https://fuse-box.org/page/vue-component-plugin) page.

**Comment by nchanged** [comment]
thanks, it was fixed
