### ISSUE TITLE
ReplacePlugin wrong key parsing ?

### ISSUE THREAD

**Issue by orblazer** [fuse-box/fuse-box#1113]
Hello, when use the ReplacePlugin the key is an regex or juste a string ?

If is a string ok i go fix that because the key characters are not escaped.
Exemple if you use key `$ASSETS` the regex at the end is `/$ASSETS/g` and this is wrong because we want `/\$ASSETS/g` regex for escape `$` character.

Thanks.

**Comment by nchanged** [comment]
ReplacePlugin does a simple replace. Feel free to open a PR and improve it, any help is greatly appreciated ;-)
