### ISSUE TITLE
Not found on request 

### ISSUE THREAD

**Issue by maximkott** [fuse-box/fuse-box#1119]
I'm facing a strange issue, when I set a package name and try export my package to the global namespace, like: 

```
FuseBox.init({package: "yolo", globals: {yolo: "yolo"}, ...})
```

I get this error in browser `yolo not found on request`, it tries to load id from the dev server. I doesn't seem to break anything, my code works as expected. Package is accessible trough `window.yolo`. Any ideas what could be the reason for such behaviour? 

**Edit**

The error disappears in production mode / with quantum enabled. The only difference between my builds in production and development mode is that in dev mode I do split vendors from project files like this:

```
fuse.bundle('vendors').instructions('~ %s')
fuse.bundle('yolo').instructions('!> [%s]')
```

Whereas in production I just do this:

```
fuse.bundle('yolo').instructions('> %s')
```

So I disabled bundle splitting and it works in dev mode too. So quantum is not the reason. There is some kind of a problem in combination with `glboals` and bundle splitting.

**Edit**

When disabling bundle splitting and using a configuration similar to this:

```
FuseBox.init({
  ...,
  package: 'yolo',
  globals: {default: 'yolo'},
})
```

With HMR enabled, I get this error as soon as the HMR kicks in (I edit and save a file), the initial page load causes no errors, however: 

```
events@0.0.0:308 Uncaught TypeError: Cannot read property 'f' of undefined
    at Function.r.flush (events@0.0.0:308)
    at EventEmitter.<anonymous> (fusebox-hot-reload@0.0.0:112)
    at EventEmitter.emit (events@0.0.0:82)
    at WebSocket.client.onmessage (fusebox-websocket@0.0.0:71)
```

When I change configuration to this:

```
FuseBox.init({
  ...,
//  package: 'yolo',
  globals: {default: 'yolo'},
})
```

HMR works fine again, and my library is properly exported to the window (however, it still doesn't work with bundle splitting).

**Comment by nchanged** [comment]
@maximkott I don't think you should be naming your package. That was before we had Quantum. Just export the default package as is. And Quantum will do the rest

**Comment by maximkott** [comment]
@nchanged Any advise on how to get rid of the error message while splittings vendors from sources? Thanks!

**Comment by nchanged** [comment]
`.instructions('!> [%s]')` isn't a valid file.
`.instructions('!> [index.ts]')`

**Comment by maximkott** [comment]
@nchanged Yeah, sorry, I forgot to change that in the example (I'm using util.format), however, I do use proper file paths, so that can't be the problem.

**Comment by nchanged** [comment]
that's right, @maximkott it should be relative to your homeDir

**Comment by maximkott** [comment]
@nchanged All instruction paths are relative to the homeDir

**Comment by nchanged** [comment]
I don’t really understand what’s the problem now. Can you be more specific?

**Comment by nchanged** [comment]
You would need vendors there. If you are packaging with Quantum, you need either target npm, or package vendors

https://fuse-box.org/page/publishing-to-npm#what-is-the-actual-benefit-of-having-typescript-source-exposed

**Comment by maximkott** [comment]
I had a type there, its `main not found on request` and not `yolo not found on request`.
This happens without QuantumPlugin, when I enable QuantumPlugin, this problem no longer exists. So only plain FuseBox builds are affected.

**Comment by nchanged** [comment]
How about ` globals: { default: "main" }` without any package option

**Comment by maximkott** [comment]
I tried that, after you mentioned it here

> @maximkott I don't think you should be naming your package. That was before we had Quantum. Just export the default package as is. And Quantum will do the rest

Same result

**Comment by nchanged** [comment]
Then please reproduce it in a repository, you must be doing something wrong.

**Comment by maximkott** [comment]
Will do

**Comment by nchanged** [comment]
Closing it due to inactivity
