### ISSUE TITLE
Could Fusebox support --stdin option? 

### ISSUE THREAD

**Issue by mindreframer** [fuse-box/fuse-box#1121]
To quote the docs from webpack: `Specifying this option instructs the server to close when stdin ends.`

An example can be found here: 
- https://github.com/webpack/webpack-dev-server/tree/master/examples/cli/stdin

Why would users need it? 

I know about a particular community that would love: Elixir developers! The most popular framework used there is Phoenix and it integrates into brunch.io and webpack by running them in watch-mode with an --stdin option. That helps to control the JS compiler directly from Elixir. 

The community is really performance-sensitive and anythings that improves the JS part (dev UX / speed / correctness) will be gladly accepted and embraced. 

Here is an article explaining the setup for webpack with Phoenix: 
- http://matthewlehner.net/using-webpack-with-phoenix-and-elixir/

This could be a chance to get more developer exposure within a small and focused developer community. 

Thanks for fusebox, love it!

**Comment by nchanged** [comment]
@mindreframer Hi, Yes, we can have something like that. 
Just to be clear,
We want to enable `CTRL+D` combination to shut down (gracefully) dev server. Is that right?

I've found a is a [snippet](https://gist.github.com/unitycoder/8eade8271b44e1bf9ac149e5d7ad566b)

Basically, that one just calls `process.exit`. 

Other than then, if you have better ideas, please share.

**Comment by mindreframer** [comment]
@nchanged I think this might be even simpler! 

From Brunch.io: 

https://github.com/brunch/brunch/blob/36ba9bb4804e306b0a225d6ec75eddb231188d10/lib/watch.js#L182

```
if (cfg.stdin) {
      process.stdin.on('end', () => process.exit(0));
      process.stdin.resume();
}
```


For Webpack: 
https://github.com/webpack/webpack-dev-server/blob/3e220fe1c9dcdc7b688090f0f4661e06a1e87c91/bin/webpack-dev-server.js#L265
```
if (argv.stdin) {
    process.stdin.on('end', () => {
      process.exit(0); // eslint-disable-line no-process-exit
    });
    process.stdin.resume();
  }
```

That might be it. ¯\_(ツ)_/¯

**Comment by nchanged** [comment]
Do you think that the configuration above could be enabled on `fuse.dev` (without any specific option) ?

**Comment by mindreframer** [comment]
@nchanged I am not sure. The behaviour of the application changes somewhat, it might trip up some scripts. Imho it should be a rather explicit opt-in option, similarly to webpack / bruch.io.

**Comment by nchanged** [comment]
@mindreframer I will be more than happy to help the community move to FuseBox. Let me know how I can help, and if you have further questions please contact me on Gitter.
You can enable stdin in the `@next` version
