### ISSUE TITLE
Support for Aurelia

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box#113]
Support for Aurelia would have been nice
http://aurelia.io/

Atm it looks like we need a custom Aurleia-loader.

Update from gitter channel:
> @devmondo :
@vegarringdal we are working now on the loader, stay tuned

**Comment by leon-andria** [comment]
Guys,

I would like to tell you that i just finish few minutes ago the loader !!! It works at this stage but can be optimized.
I will push tomorrow on my repo.

**Comment by leon-andria** [comment]
Here we are here https://github.com/leon-andria/fuse-aurelia-loader
But, this is really JUST an overview for LOADER, the problem is really to understand all execution flow.
Abstract implementation with Aurelia is like vodoo where you need to be really HIGH skilled.

**Comment by niieani** [comment]
With the upcoming changes to Aurelia's PAL, it should be very simple to add proper Aurelia support for fuse-box, as it can follow the same rules for recognizing dependencies as the new AureliaPlugin for Webpack. We could probably even reuse some of the code from the those plugins.

**Comment by leon-andria** [comment]
Awesome if there is a simple way to achieve that in near futur.
I'm really concern about the abstract implementation whatever it's the default loader / bootstrapper or with Webpack.
Fusebox cannot be resume in just Fusebox.import(...), there are more than this. Aurelia uses massively metadata and THIS is the SECRET sauce that Fusebox handle in its core engine.
hth,

**Comment by niieani** [comment]
That's true. Aurelia already makes use of "reflection" (e.g. for finding relative paths), so having it built-in in fuse-box will simplify the proper implementation.

**Comment by vegarringdal** [comment]
> With the upcoming changes to Aurelia (using PAL.moduleName), it should be very simple to add proper Aurelia support for fuse-box...

@niieani Is there a ETA for the upcoming changes ? Any chance you help the fusebox team implement this when its ready, since you know a lot how the inner magic of Aurelia works 😄

**Comment by niieani** [comment]
@vegarringdal probably next week, since parts of the solution were already published.

Here's the discussion about statically analyzing dependencies and the added `PLATFORM.moduleName`: https://github.com/aurelia/pal/issues/17

Discussion about "reflection" or Origin detection: https://github.com/aurelia/metadata/issues/51

PR and discussion with general new Webpack support and boilerplate: https://github.com/aurelia/skeleton-navigation/pull/714

Awesome job on fuse-box guys. It's looking really good so far, waiting for moar! 👍

**Comment by leon-andria** [comment]
guys,

just small update on the repo here: https://github.com/leon-andria/fuse-aurelia-loader and any dependencies works.
We can make <require from.... so fucking fast :-)

**Comment by Thanood** [comment]
CSS is next, I guess. 😏 
I've tried `<require from="hello-world.css">` in `<hello-world>` and add a css file which makes `<hello-world>` display as a block element.
It resolves to `module = FuseBox.import(id)` and throws:
```
Uncaught (in promise) Package was not found "css-resource-plugin!hello-world.css"
```

**Comment by vegarringdal** [comment]
@Thanood great work

Updated this:
https://github.com/vegarringdal/aurelia-fusebox-test

Its a bare minimum what you need to get it up and running

**Comment by devmondo** [comment]
@vegarringdal you say that your version works ?

**Comment by niieani** [comment]
Just to note, you'd probably be better off by forking the `aurelia-loader-webpack` rather than the original RequireJS/SystemJS-based `aurelia-loader-default`, since the concepts will be more similar in the Webpack loader. Also, the Webpack loader also supports HMR as does FuseBox.

**Comment by leon-andria** [comment]
@Thanood The css plugin is more simpler :-) I'm going to shape all of these in a plugin now, this was just a simple test. 
I'm going to say that the moment you tasted with Fuse, you are not going to ue Webpack or the default Aurelia cli... it was a nightmare for any changes or day after day to run au run --watch --env dev ==> you know what i mean.

**Comment by leon-andria** [comment]
@niieani Yes, i based my sample on webpack. And it was my mistake to not return the Promise like Webpack.
Maybe i'm wrong but this sample loader can solve 80% of cases.

**Comment by nchanged** [comment]
@leon-andria could submit a PR, so we could test? If it's possible, could you create a project in the `_playground` folder with aurelia bootstrap and `hello world` app, thanks =)

**Comment by vegarringdal** [comment]
@leon-andria Thanks for making the loader
When you make a very simple sample, could you use https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-typescript/src as a resource, I might have done something wrong but looks like router had issues with current loader

**Comment by leon-andria** [comment]
@vegarringdal I just pushed the css example. Take a look on app.js and include the css plugin, that's it.

**Comment by vegarringdal** [comment]
I played around with it a little
In the loadModule I removed the first if statement and in the end I did this:
```
if(!FuseBox.packages[id]){
        module = FuseBox.import('~/' + id)
      } else {
        module = FuseBox.import(id)
      }
```
The router stared to work, but atm it looks like Im not getting my tsconfig working because it looks liek decorators are failing

**Comment by nchanged** [comment]
@vegarringdal would [FuseBox.exists](https://github.com/fuse-box/fuse-box/blob/master/src-frontend/FuseBox.ts#L441) do better?

**Comment by devmondo** [comment]
@vegarringdal  i agree with @nchanged  the Api is there for such a case
regarding TS issues we need to make it more clear !

**Comment by vegarringdal** [comment]
Yes, but I didnt know that :-)
Just wanted the router to work, the entire loader will need some work here and there.
Im atm just trying and failing to get something simple like basic skeleton sample code working 😄

**Comment by vegarringdal** [comment]
Created simple demp here:
https://github.com/vegarringdal/aurelia-fusebox-test

* Tried to keep it very simple, just started with blank folder, and installed the repos needed, then copied the src folder of the aurelia-typescript-skeleton.
* Did some modifications to the loader to make i work with the router
* **One know bug atm is the @autoinject,** not working (maybe Ive done something wrong with fuse setup)
* will try and add more stuff to try and see if other things break

![fusetest](https://cloud.githubusercontent.com/assets/2901416/22865338/1f8bbc0c-f162-11e6-8e5c-144ceae2ca08.gif)

**Comment by nchanged** [comment]
@vegarringdal you need help with the @autoinject decorator?

**Comment by leon-andria** [comment]
@vegarringdal I have downloaded your repo now and i was able to run with autoinject.
You need to put "emitDecoratorMetadata": true in the tsconfig and make sure to call @autoinject without the parenthesis. That's it and work pretty nice!

**Comment by Thanood** [comment]
As far as I know (and I may very well be wrong here) getting the routes to bundle and to load correctly was one of the more challenging parts of getting Aurelia to run with webpack.. 😃 

So: nice work! 👍

**Comment by vegarringdal** [comment]
> @vegarringdal I have downloaded your repo now and i was able to run with autoinject.
You need to put "emitDecoratorMetadata": true in the tsconfig and make sure to call @autoinject without the parenthesis. That's it and work pretty nice!

@leon-andria (@nchanged  info)
Great, I prb messed up when trying to get decorators to work before adding the typescript helpers
How the plugin/clean up going btw ? Could you use my modification to the loader ? Didnt try and do much more yesterday, it was late, and figured you know a lot more what was going on/ fuse api :-)

@Thanood 
Yes 👍 thx to @leon-andria  for making the loader


@nchanged 
I would liek to test this plugin in same repo as the sample I started on
This one (se link below), whats the best way of defining a package, and all bundle paths like I do here:
https://vegarringdal.gitbooks.io/dev-rebuild/content/chap15/aurelia-cli_not_aspcore.html

**Comment by devmondo** [comment]
@Thanood FuseBox, has multi-entries bundles and you can load your bundles dynamically at runtime, os you could easily create bundle for each route and when you hit that route you can load its respective bundle at run time and boom!, of course shared code needs to be bundled and loaded first as usual :)

**Comment by vegarringdal** [comment]
@leon-andria @nchanged 

Trying to get plugin to work, but getting some issues

When I try and FuseBox.import("aurelia-v-grid") this I get nothing, even though its under Fusebox.packages
Its missing entry point
![image](https://cloud.githubusercontent.com/assets/2901416/22908005/69520054-f24c-11e6-9473-4009275d1891.png)



Here is the package I create:
https://github.com/vegarringdal/aurelia-fusebox-test/blob/master/fuse.js#L23-L32

code:
```
let gridFuse = fuse.init({
        package: "aurelia-v-grid",
        homeDir: "./node_modules/aurelia-v-grid/dist/commonjs",
        outFile: "./aurelia-v-grid.js",
        globals: { default: "aurelia-v-grid" },
        plugins: [
        fb.CSSPlugin(),
        fb.HTMLPlugin({ useDefault: true }),
    ]
})
gridFuse.bundle('> index.js + **/*.html + **/*.js + **/*.css');
```

This gets loaded after main bundle here:
https://github.com/vegarringdal/aurelia-fusebox-test/blob/master/index.html#L20

If anyone want to give it a try, then its just to git clone it thennpm install & node fuse

Main issue like I see it is that I cant set entypoint when I create the package
Would also have been nice if it was possible to do this without creating 2 packages/bundle files also (maybe it is) or add my package as a option to main build

**Comment by nchanged** [comment]
@vegarringdal 
```
fuse.init({
        package: "aurelia-v-grid",
        homeDir: "./node_modules/aurelia-v-grid/dist/commonjs",
        outFile: "./aurelia-v-grid.js",
        globals: { "aurelia-v-grid": "aurelia-v-grid" },
        plugins: [
        fb.CSSPlugin(),
        fb.HTMLPlugin({ useDefault: true }),
    ]
})
```
You problem was `globals`. You had "default", but that's wrong, because you modified your package name to `aurelia-v-grid`. This will work 100%, as it was tested before, and actually there is a [package](https://www.npmjs.com/package/clan-fp) on npm that uses exactly the same approach

**Comment by vegarringdal** [comment]
@nchanged, Ill give it a try tomorrow after work :smile:
might need to add more to docs about this, I tried ```globals:{default:"aurelia-v-grid"}``` earlier

**Comment by nchanged** [comment]
@vegarringdal @leon-andria Would it make sense, guys, if I gave you direct access to https://github.com/fuse-box/fuse-box-aurelia-loader to speed up the process?
?

**Comment by vegarringdal** [comment]
@nchanged you could atleast give @leon-andria access, think he started to work on the plugin.

Atm Im just trying to get that plugin working so we can show how to deal with a plugin with other then commonjs as default.

Also tried that change you suggested, but missed entry still, but give it a new try later :-)

**Comment by nchanged** [comment]
@leon-andria @vegarringdal you are the best! :1st_place_medal:

**Comment by vegarringdal** [comment]
@leon-andria 
Ive started recoding the loader a lot, so it checks more if moduls exist before tying to load any, so no hardcoded test for some of the aurelia you had a easy fix to prove it was possible :-)

Atm it looks to be able to load my grid plugin, I prb doing all sorts of bad when making my bundle to get all the resources inn, hopefully this could solve this/make it simpler: https://github.com/fuse-box/fuse-box/issues/170

But atm it works, little video:

![fusetest](https://cloud.githubusercontent.com/assets/2901416/22948704/c856a88a-f2ff-11e6-98ac-faecb30cc1a0.gif)


Ill try and clean up my code ofter Ive tested with some more stuff like value convertes etc

**Comment by vegarringdal** [comment]
@leon-andria @nchanged @Thanood 
Updated this one: https://github.com/vegarringdal/aurelia-fusebox-test/blob/master/src/fuse-aurelia-loader.ts
There is a lot I have no clue about, so Im sure you guys can make it a lot better

**Comment by nchanged** [comment]
There is some awesomeness being cooked at the very moment https://github.com/fuse-box/fuse-box/pull/158 

We will have a custom HMR for aurelia!

**Comment by vegarringdal** [comment]
very nice :smile:

**Comment by vegarringdal** [comment]
Info for anyone looking at this:

https://github.com/fuse-box/fuse-box-aurelia-loader

**Comment by vegarringdal** [comment]
We can really close this for now, basic support is in, further issues etc can continue here: https://github.com/fuse-box/fuse-box-aurelia-loader

**Comment by devmondo** [comment]
@vegarringdal @leon-andria  thank you guys soo much for this you rock 💯
