### ISSUE TITLE
FuseBox.import and Quantum

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#1131]
Guys, I am trying to use Quantum, but I have quite a few FuseBox.imports in my code, which are importing huge JS modules dynamically. Any advice on how can I import large JS modules into my project?

Thanks!

**Comment by nchanged** [comment]
@tomitrescak using [Code Splitting](https://fuse-box.org/page/code-splitting)

You should try it ;-)

**Comment by tomitrescak** [comment]
@nchanged I am trying, but it is not working for me. You are not using .js suffixes for split bundles and on our server configuration it wreaks havoc. 

do you have an example of an "express" server where it works? Thanks!

**Comment by tomitrescak** [comment]
Ok, got it like this:

```
app.use('/bundles', (req: any, res: any) => {
    res.sendFile(`${statics}/${req.originalUrl}`)
});
```

The problem of this is that FB is now bundling in my huge js file which I really wanted to keep out. Any advice here? I want to keep that JS file completely out of everything and I do not want to minify it or pass with quantum as it is already minified.

**Comment by tomitrescak** [comment]
So, my question I guess is ... how to import a minified bundle, keep it completely separate without any processing?

Currently, FuseBox "unwraps" the bundle and then it tries to minify it back. This takes a LOOONG TIME.

**Comment by nchanged** [comment]
Can you just import a package dynamically? That would be the most optimal solution. As in

`await import("moment")`

**Comment by nchanged** [comment]
Closing this issue for now, please re-open elsewise
