### ISSUE TITLE
Quantum doesn't cope with require.extensions

### ISSUE THREAD

**Issue by ccapndave** [fuse-box/fuse-box#1133]
Specifically the code at https://github.com/wycats/handlebars.js/blob/7535e48a7969229f44489124a8ef07bd17363f06/lib/index.js#L22-L25

gets compiled into:

```js
if (typeof $fsx !== 'undefined' && require.extensions) {
    require.extensions['.handlebars'] = extension;
    require.extensions['.hbs'] = extension;
}
```

causing a fatal runtime error.

**Comment by nchanged** [comment]
@ccapndave which version are you using.
Mine transpiled into:
```
if ('function' !== 'undefined' && require.extensions) {
}
```

**Comment by ccapndave** [comment]
3.2.0-next.8 with:

```
QuantumPlugin({
          globalRequire: true,
          replaceTypeOf: false,
          treeshake: true,
          bakeApiIntoBundle : "app"
        })
```

**Comment by ccapndave** [comment]
BTW - I don't really understand what `replaceTypeOf: false` is for, but we had to add it in so that https://github.com/localForage/localForage would work with Quantum.

**Comment by nchanged** [comment]
@ccapndave yeah, not I get the same error

**Comment by ccapndave** [comment]
What if you put in `replaceTypeOf: false`?

**Comment by nchanged** [comment]
It will still yield the same error, but I will fix it shortly

**Comment by ccapndave** [comment]
Thanks for fixing this!
