### ISSUE TITLE
Is it possible to run a fusebox bundle on any server?

### ISSUE THREAD

**Issue by valepu** [fuse-box/fuse-box#1137]
Greetings,
I have just discovered fuse box and i was testing it out a bit, i have downloaded and run https://github.com/fuse-box/angular2-example 
But I have a question that might sound stupid but couldn't find a simple answer: Is there a way build a project so you can just put the files from the dist directory on, for example, apache and have them work?
I have tried with the angular2-example project as it is but it just gives me this error on the chrome console

```
Uncaught TypeError: Cannot read property 'module' of undefined
    at Object.e.f.(anonymous function) 
```

Thanks for your answers

**Comment by devmondo** [comment]
@valepu fuse-box produces javascript code like any other normal javascript code that runs either in the browser or in Node.js, but make sure to you [quantum](https://fuse-box.org/page/quantum) for your final so it would be more compatible. 

for the error above, it mostly means you have an error in your code. did you try to enable `debug` and `log` options in the fuse ? it would give you more details.

**Comment by valepu** [comment]
I fear I wasn't clear in my question, let me write down the steps:

1) I have cloned the repository angular2-example on my machine
2) I ran "npm run dist" and it built the files app and vendor in the dist directory then opened a server on localhost:4444
3) opened a browser window to localhost:4444 and everything worked fine (I could run the todo app without any issues)
4) copied the files from dist to the directory from which my local apache serves files to the web
5) went to the url where the files supposed to be
6) received the error I mentioned above

The same thing happened with another example project (the angularjs example from the creator of the template cache plugin).
This made me think fuse-box generated JavaScript can run only through its own server.

**Comment by nchanged** [comment]
Did you copy all the files including index.html? I am sure something was missing

**Comment by valepu** [comment]
I copied the dist folder as a whole, and when i went to the apache url i saw the project title, also no 404 errors in the browser console.

**Comment by valepu** [comment]
I don't remember which version of npm and chrome i was using but i'm confident my node version was 9.7.1 since i had it updated just before using the projects (i had previously installed node 7 and i had some issues running fusebox). Will check again when i'm back home

**Comment by valepu** [comment]
I have just tried at work with node v8.6.0 and npm 5.6.0 (Linux Mint) and it worked fine both on Mozilla (52 LTS) and Chrome (Version 63.0.3239.132 (Official Build) (64-bit)) 
I'm sorry i jumped to such a weird conclusion that fuse box required to be run on its own server.

**Comment by valepu** [comment]
I have tried again deleting node_modules directory and running npm install again, this time it worked. Probably because i had run npm install before updating node the first time.

Thanks for your support
