### ISSUE TITLE
How do I import a file outside of my home directory?

### ISSUE THREAD

**Issue by phamtm** [fuse-box/fuse-box#1138]
First of all, I'm a great fan of fusebox. Second of all, I am trying to replace the my company frontend project current `webpack` configuration with `fusebox`. I have a folder structure like this:

```
|__ shared/src
|
|__ webapp/src
|
|__ mobile
```

`webapp` and `mobile` is 2 applications, while `shared` is the shared logic between those 2. That means I will need to import something from `shared` logic into `webapp`

However by using fusebox I cannot seem to do that. I faced some warnings like `WARNING File "..." cannot be bundled because it's out of your project directory (homeDir)`. By using `webpack` I can still import it using relative path.

So is there any way to solve this problem currently with fusebox? Really appreciate your help.

**Comment by nchanged** [comment]
HI! I am glad to hear that you aren’t enjoying FuseBox! 

You can solve your issue by moving up your homeDir, and changing the instructions to src/index

**Comment by nchanged** [comment]
Closing this issue for now.
