### ISSUE TITLE
Update docs to tell dependencies that needs to be installed to use plugins

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box#114]
Update docs to tell dependencies that needs to be installed to use the plugins
Maybe a complete list/table of the plugins and dependencies would be nice, so its easy to find.
Could be the first thing you see here:
http://fuse-box.org/#built-in-plugins

This can confuse people during first install:
```
npm WARN fuse-box@1.3.109 requires a peer of less@* but none was installed.
npm WARN fuse-box@1.3.109 requires a peer of babel-core@* but none was installed.
npm WARN fuse-box@1.3.109 requires a peer of stylus@* but none was installed.
npm WARN fuse-box@1.3.109 requires a peer of node-sass@* but none was installed.
npm WARN fuse-box@1.3.109 requires a peer of uglify-js@* but none was installed.
```

**Comment by koko236** [comment]
+1  I 'd get peer dependencies warnings if I saw any but nothing like that showed up on install. 

I'm just getting started after reading introduction from the docs and watching 4 minutes introductory video on YT thinking, ok it looks much easier than Webpack. Then scss doesn't work after adding the plugins in fuse.js, (says node-sass missing). Trying to run the dev server and I get:

```
fusebox-hot-reload%400.0.0 was not found
fusebox-websocket%400.0.0 was not found
events%400.0.0 was not found
```

In 20 minutes I've managed to find 4 or 5 pieces of documentation about how effortless is the fb setup but didn't find a decent step by step introduction saying what is actually necessary to make fusebox run.

**Comment by koko236** [comment]
Sorry for the bad vibe, I cleared cache, installed additional dependencies and basic example does work now. It is indeed easier to start than Webpack but still being clear about what doesn't happen automagically would smooth out the first experience. All in all it seems to be very cool tool.

**Comment by nchanged** [comment]
Thanks! Please upgrade the version, peer deps were removed! And you are welcome to improve the documention! We want to make it as easy as possible for the newcomers.

**Comment by devmondo** [comment]
@koko236 fully agree, we also had peer deps, but some people complained about them.

we are more than happy to accept any suggestion to make it better :)

**Comment by devmondo** [comment]
done here https://github.com/fuse-box/fuse-box/commit/50c60f988397620774a58ddc28a64278fab124d2
