### ISSUE TITLE
watch fails when file is deleted/renamed

### ISSUE THREAD

**Issue by valepu** [fuse-box/fuse-box#1141]
Greetings,
I'm playing with fusebox and i'm really loving it! So i'm trying to learn a bit more about it by creating a fuse.js file from scratch
I'm trying to make a simple task to watch for files in the assets folder and copy them

```
task("assets", async context => {
	watch('./assets/**/**.**', { base: './src' })
	.dest('./dist')
	.exec();
});
```

This works and i'm able to use these files in my code, but whenever i delete or rename a file i receive this error `Error: ENOENT: no such file or directory, stat [...]` and the file is not deleted (i can still access it from its url). Is there another, more correct, way to watch for changes in static files?

**Comment by nchanged** [comment]
Hi!
You forgot to add return.

**Comment by valepu** [comment]
Hi,
I changed the task like this:

```
task("assets", async context => {
	return watch('./assets/**/**.**', { base: './src' })
	.dest('./dist')
	.exec();
});
```

But i still get the same error. Mind that when adding files it works

**Comment by nchanged** [comment]
It’s probably a mistake or there is no {} which implies on a return statement. Could you paste your full config ?

**Comment by valepu** [comment]
Your last comment made me realize i've put {} on the clean task and so it didn't imply on a return statement anymore. Now it works, thanks
