### ISSUE TITLE
Quantum not working well with variables named "require" inside AngularJS code

### ISSUE THREAD

**Issue by valepu** [fuse-box/fuse-box#1142]
Greetings,
I'm having an issue very similar to this one: https://github.com/fuse-box/fuse-box/issues/1133
In AngularJS (1.6.9) there is this piece of code:

```
[...]
    function getControllers(directiveName, require, $element, elementControllers) {
      var value;

      if (isString(require)) {
        var match = require.match(REQUIRE_PREFIX_REGEXP);
        var name = require.substring(match[0].length);
[...]
```

Which doesn't get parse correctly when using quantum. 

Error: `ReferenceError: require is not defined`

Converted code (without uglify):  

```
function getControllers(directiveName, $fsx, $element, elementControllers) {
                    var value;
                    if (isString($fsx)) {
                        var match = require.match(REQUIRE_PREFIX_REGEXP);
                        var name = require.substring(match[0].length);

```

Reading the issue linked above i updated fusebox to 3.2.0-next10 but then something similar happened to another piece of code in AngularJS:

AngularJS code:

```
  function getDirectiveRequire(directive) {
    var require = directive.require || (directive.controller && directive.name);

    if (!isArray(require) && isObject(require)) {
      forEach(require, function(value, key) {
        var match = value.match(REQUIRE_PREFIX_REGEXP);
        var name = value.substring(match[0].length);
        if (!name) require[key] = match[0] + key;
      });
    }
```
Error: `TypeError: e.match is not a function`

Converted code (without uglify):  

```
function getDirectiveRequire(directive) {
            var require = directive.require || directive.controller && directive.name;
            if (!isArray($fsx) && isObject($fsx)) {
                forEach($fsx, function (value, key) {
                    var match = value.match(REQUIRE_PREFIX_REGEXP);
                    var name = value.substring(match[0].length);
                    if (!name)
                        require[key] = match[0] + key;
                });
            }
            return $fsx;
        }
```

This is my quantum configuration (i have tried with any combination of replaceTypeOf and mangle, also completely disabling uglify, still not working)
```

				this.isProduction && QuantumPlugin({
					//bakeApiIntoBundle: "app",
					replaceTypeOf: false,
					treeshake: true,
					uglify: {
						mangle: true
					},
					css: {
						clean: true
					},
					api: core => {
						core.solveComputed("moment/moment.js", {
							mapping: "moment/locale**",
							fn: statement => {
                                                             statement.setExpression(`"moment/locale/" + name + ".js"`);
							}
						});
					}
					// containedAPI : true
				})
```

**Comment by nchanged** [comment]
I don’t think we have a polyfill for require.match 
Unless it’s defined, the thing is it’s  being replaced by Quantum (from what’s I see)

Can you make a repository where this can be reproduced. I am on vacation ATM but I will try to help your as soon as I can

**Comment by valepu** [comment]
The first part, the one with "require.match" is fixed when updating to 3.2.0-next10, but then a similar issue happens somewhere else (i think in the first part require is just a string passed as a parameter to the function).

I have created the repository at https://github.com/valepu/angularjs-fusebox-require 
Running npm run dist and then going to the page will show the error in the console (at the moment i have installed 3.2.0-next10, using 3.1.3 will show a different error).
It is an uncommon use case, this is probably why it hasn't happened to anyone else yet  (also because not many people use AngularJS anymore for new projects), it happens only if you have an AngularJS directive with a "require" attribute

I have created the repo starting from https://github.com/TobiasTimm/fuse-box-angularjs-example which made me realize shimming angular will also fix the problem since Quantum won't replace the variables named require (yesterday i temporarily fixed by renaming all the variables called "require" inside AngularJS code...)

Anyways, thanks for your time and i'm sorry to disturb you during your vacation. I have spent the weekend converting a project i maintain from JSPM to Fusebox and it feels refreshing!
Have a nice vacation

**Comment by nchanged** [comment]
Thanks, I will fix this issue, it’s not a big deal actually. We just need to check if a variable require has been defined, then, obviously skip all manipulations with it

**Comment by jpike88** [comment]
I just ran into this one, preventing me from using Quantum, I just went through hell to NOT shim angular... problem is with angular@1.6.10

**Comment by jpike88** [comment]
```
function getDirectiveRequire(directive) {
            var require = directive.require || directive.controller && directive.name;
            if (!isArray($fsx) && isObject($fsx)) {
                forEach($fsx, function (value, key) {
                    var match = value.match(REQUIRE_PREFIX_REGEXP);
                    var name = value.substring(match[0].length);
                    if (!name)
                        require[key] = match[0] + key;
                });
            }
            return $fsx;
        }
```

**Comment by jpike88** [comment]
It's not just happening with one part of the angular.js file, it's happening in multiple spots, it's basically mangled the file completely. $fsx is being inserted all over the place.

I think the issue lies in StatementModification.ts, but I'll be damned if I know what to do. I'm assuming it's a quick fix right?

**Comment by jpike88** [comment]
No the issue is in AstUtils.ts, in the matchesSigleVariable (theres a typo) function...

**Comment by jpike88** [comment]
The following commit acts as a workaround:

https://github.com/streaka/angular.js/commit/35c0fb4096c54a41d6b96406d9d7428fe1797aef

Two scenarios where fuse-box shouldn't just be replacing every node called 'require':

- when require has been previously defined as a variable within that scope
- when require has been defined as a parameter of the function within that scope
