### ISSUE TITLE
Source map url slashes are not converted properly on windows

### ISSUE THREAD

**Issue by ab18556** [fuse-box/fuse-box#1143]
On Windows, with this configuration:

`const fuse = FuseBox.init({
  homeDir: 'src',
  output: 'dist/$name.js',
  target: 'browser@es5',
  sourceMaps: true,
  plugins: [
    [
      SassPlugin({ importer: true }),
      CSSResourcePlugin(),
      CSSPlugin(),
    ],
  ],
});`

The path of the css source map is like this:

`# sourceMappingURL=\\css-sourcemaps\\20b2d2d8.map`

But it should be like this

`# sourceMappingURL=/css-sourcemaps/20b2d2d8.map`

**Comment by ab18556** [comment]
I investigated a little bit and I think using path.posix instead of using only path would fix this issue. I am wondering if there might be more instances of this issue on windows since path is used all over the place.

**Comment by nchanged** [comment]
We have a special function there, ensureFuseBoxPath or joinFuseBoxPath so that should be used on render
