### ISSUE TITLE
[Feature] Sparky src / watch negative filter

### ISSUE THREAD

**Issue by CzBuCHi** [fuse-box/fuse-box#1148]
Currently i need to write this code:
```ts
  await Sparky.src("**/__mocks__/*", { base })
    .file("*", async file => {
      if (file.homePath.indexOf("node_modules") !== -1) {
        return;
      }

    })
    .exec();
```
to get all mocks that arent in node_modules folder, but that will print `→Captured file ...` for all files and i cannot figure out, how to write filter string correctly so i dont need to check homePath inside callback fn.

Poking arount in code it seems, that negative glob patterns arent supported at all.

According to #962 it looks like sparky will be updated, so my question is this: 

**Will Sparky support negative glob patterns in the future?** 

eg:

```ts
await Sparky.src(["**/__mocks__/*", "!**/node_modules], { base });
```

**Comment by nchanged** [comment]
Hi,  all options are passed to chokidar, and I think that chokidar supports the syntax above

**Comment by CzBuCHi** [comment]
I did look at the code in SparkFlow.getFiles - these globs are simply `concat`ed tohether - so even if "!**/node_modules" works these results wouldnt be removed from results of "**/__mocks__/*" ...

after modifying method `getFiles` to this: 

```ts
protected async getFiles(globs: string[], opts?: SparkyFilePatternOptions): Promise<SparkyFile[]> {
    const files = await globby(globs, { cwd: opts.base, absolute: true  });
    const root = opts && opts.base ? path.join(Config.PROJECT_ROOT, opts.base) : Config.PROJECT_ROOT;        
    this.files = files.map(file => new SparkyFile(file, root));
    return this.files;
}
```
i managed to get i to work, but im using package [globby](https://www.npmjs.com/package/globby) instead of `glob` and i dont wanna do these changes, because i dont know what else is dependent on glob ... (and having reference to both is just stupid)

---
original code for reference: (im not using getFile method at all)
```ts
protected getFiles(globs: string[], opts?: SparkyFilePatternOptions): Promise<SparkyFile[]> {
    this.files = [];
    const getFilePromises = [];
    globs.forEach(g => {
        getFilePromises.push(this.getFile(g, opts));
    })
    return Promise.all(getFilePromises)
        .then(results => {
            this.files = [].concat.apply([], results);
            return this.files;
        })
}

protected getFile(globString, opts?: SparkyFilePatternOptions) {
    let info = parse(globString, opts)

    return new Promise((resolve, reject) => {
        if (!info.isGlob) {
            return resolve([new SparkyFile(info.filepath, info.root)])
        }
        glob(info.glob, (err, files: string[]) => {
            if (err) {
                return reject(err);
            }
            return resolve(files.map(file => new SparkyFile(file, info.root)))
        });
    });
}
```

**Comment by nchanged** [comment]
I am closing this issue for now, please re-open if you till have problems with it
