### ISSUE TITLE
fuse-box-contrib group

### ISSUE THREAD

**Issue by TobiasTimm** [fuse-box/fuse-box#1149]
Hey @nchanged,

maybe it would help the people, if we publish/develop the 3rd-party-plugins in a fuse-box-contrib group. Similar to the https://github.com/webpack-contrib

**Comment by nchanged** [comment]
@TobiasTimm so people would ask permission to create repositories?

**Comment by TobiasTimm** [comment]
I don't know how github orgs are working, but If I compare it to the webpack group. People open issues to request a transfer proposal https://github.com/webpack-contrib/organization/issues/16 and a group of staff members validate the repos. Idk how they are handling bugfixes etc.

**Comment by TobiasTimm** [comment]
also see https://github.com/webpack-contrib/organization/issues/15

**Comment by TobiasTimm** [comment]
@nchanged opinons? 😄

**Comment by nchanged** [comment]
@TobiasTimm I've created an organisation, maybe you could help out me here?

**Comment by TobiasTimm** [comment]
Sure I will help you where I can. Just write me a message on gitter where you need help with
________________________________
