### ISSUE TITLE
development server not refreshing properly

### ISSUE THREAD

**Issue by lionar** [fuse-box/fuse-box#115]
# Development server refresh

When i run the fusebox development server and change my content the following happens:

- On Firefox the development server refreshes the page once properly, after that it does not refresh anymore. 

- On chrome the development server refreshes once properly, after that it keeps appending my content when i use for example document.write, meaning the old content that was previously written stays on the page in chrome.

i used the following configuration:

```js
const fb = require ( "fuse-box" );
const FuseBox = fb.FuseBox;

const fuse = FuseBox.init ( 
{
	homeDir: "./application",
	outFile: "./build/application.js"
} ); 

fuse.devServer ( "> index.ts", 
{
    port: 4444, 
    httpServer: true
} );
```

**Comment by nchanged** [comment]
Welcome @lionar and thanks for submitting the issue.

FuseBox reloads your entry point, therefore everything is repeated. `document.write` will be executed as many times as it was called.

**Comment by devmondo** [comment]
the `HMR` is more powerful now and gives you ability to customize the behavior per requirement, please check this article for more info 
[Rethinking Hot Module Reloading](https://medium.com/@basarat/rethinking-hot-module-reloading-58ce15b5f496#.uw41smbh4)
