### ISSUE TITLE
Getting started with CSS docs are wrong

### ISSUE THREAD

**Issue by IanT8** [fuse-box/fuse-box#1150]
Here: https://fuse-box.org/page/getting-started#start-with-css

Line one of the example is

`const { FuseBox, SassPlugin, CSSPlugin } = require("fuse-box");
`

it should be

`const { FuseBox, SassPlugin, CSSResourcePlugin, CSSPlugin, WebIndexPlugin } = require('fuse-box');
`

the correct full code example is

```
const { FuseBox, SassPlugin, CSSResourcePlugin, CSSPlugin, WebIndexPlugin } = require('fuse-box');
const fuse = FuseBox.init({
  homeDir: 'src',
  target: 'browser@es5',
  output: 'dist/$name.js',
  plugins: [
    WebIndexPlugin({template: 'index.html'}),
    ['styles.scss', SassPlugin(), CSSResourcePlugin({dist: 'dist/css-resources'}), CSSPlugin()]
  ]
});
fuse.dev();
fuse.bundle('app').instructions(' > index.ts').hmr().watch();
fuse.run();
```

**Comment by nchanged** [comment]
Thanks, can you make a PR to fix that ?

**Comment by IanT8** [comment]
Sure do I have to fork the repo for that?

**Comment by nchanged** [comment]
Well, of course. I have limited access to the Internet ATM, and I would really appreciate your help

**Comment by IanT8** [comment]
Great, I'll do it this evening. This will be my first contribution to an
open-source project.

**Comment by nchanged** [comment]
Closing this issue for now. Please re-open elsewise
