### ISSUE TITLE
Browser Field warnings with Server Client and @ compile target

### ISSUE THREAD

**Issue by Kaffiend** [fuse-box/fuse-box#1151]
when using targets like 'browser@es5' warnings are thrown to set .target("browser")

**Comment by Kaffiend** [comment]
so i found that if i explicitly specify the tsconfig for client and server and use the compile target, i can still get es5 for the client and esnext for the server without the warnings.

**Comment by nchanged** [comment]
Closing this issue, re-open if still valid
