### ISSUE TITLE
Question: Sparky Context Typescript

### ISSUE THREAD

**Issue by Kaffiend** [fuse-box/fuse-box#1152]
I'm trying to figure out a way to get context to use a named class, with Typescript.
I have tried static properties in the class, and passing an instance to context as well. None of the properties are found. I'm probably overlooking something simple here.

```
import {context} from 'fuse-box/sparky'
import {BuildContext} from './fuse-context'

//Tried 
context(BuildContext)
// and 
context(new BuildContext);
 and i also tried making everything static in the class too.

What all can a `context` take?

**Comment by Kaffiend** [comment]
Answered in gitter

**Comment by Kompwu** [comment]
Anwser from gitter: `task(“name”, (context : IMyContext) => { })`
