### ISSUE TITLE
Hammer is not defined

### ISSUE THREAD

**Issue by camreyaro** [fuse-box/fuse-box#1155]
Hi! I'm getting started at FuseBox and I'm getting 'Hammer is not defined' error at output file (app.js).
Hammerjs is being imported as follows in index.ts:

`import 'hammerjs';`

I also tried:

`import * as Hammer from 'hammerjs';`

Thanks.

**Comment by nchanged** [comment]
I will check it out in 1 week ( on vacation ATM) in the meantime try clearing the cache

**Comment by devmondo** [comment]
@camreyaro 
`npm install hammerjs -S`

```js
import * as Hammer from 'hammerjs';
 
console.log(Hammer);
```
works for me using fuse-box 3 :)
