### ISSUE TITLE
difference between `fusebox` and `fuse-box` modules on npm

### ISSUE THREAD

**Issue by SheetJSDev** [fuse-box/fuse-box#1156]
There are 2 npm modules related to fusebox:

https://www.npmjs.com/package/fusebox (version 1.3.123, last release a year ago.)

https://www.npmjs.com/package/fuse-box (version 3.1.3, last release a month ago.)

Both seem to be pertaining to the same project.

Given that the logo and much of the body text refers to "FuseBox" with no hyphen, it's easy to confuse the two names.  Is there a reason to maintain both?  Should `fusebox` be deprecated (`npm deprecate`)?

**Comment by nchanged** [comment]
Fair enough, thanks for the tip. Will do that next week after my vacation
