### ISSUE TITLE
Typescript > React, error running server (Cannot GET /)

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#116]
Hi, having issues to make this work with typescript + react. When running fuse, all compiles correctly, but am getting `cannot get /` when visiting http://localhost:4444
I took your react example and converted javascript file to typescript.
Then, I changed the fuse config to following:

```js
const fsbx = require("fuse-box");

// Create FuseBox Instance
let fuseBox = new fsbx.FuseBox({
    homeDir: "src/",
    sourceMap: {
        bundleReference: "sourcemaps.js.map",
        outFile: "./build/sourcemaps.js.map",
    },
    outFile: "./build/app.js",
    plugins: [
        fsbx.SVGPlugin(),
        fsbx.CSSPlugin(),
        fsbx.TypeScriptHelpers()
    ]
});

fuseBox.devServer("> index.tsx");
```

I have added following tsconfig.json to the "src" folder

```json
{
    "compileOnSave": false,
    "compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "lib": [
            "dom",
            "es2015",
            "es2016"
        ],
        "noEmitHelpers": false,
        "emitDecoratorMetadata": true,
        "jsx": "react",
        "target": "es2016",
        "module": "commonjs",
        "moduleResolution": "node",
        "removeComments": true,
        "preserveConstEnums": true,
        "sourceMap": true,
        "strictNullChecks": false,
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "noUnusedLocals": false,
        "noUnusedParameters": true,
        "skipLibCheck": true,
        "skipDefaultLibCheck": true,
        "experimentalDecorators": true,
        "outDir": ".",
        "pretty": true
    },
    "exclude": [
        "node_modules"
    ]
}
```

And I have added a new "index.html" file to the root of the project

```html
<!DOCTYPE html>
<html>

<head>
    <title>App</title>

</head>

<body>
    <app>Loading...</app>
    <script src="app.js"></script>
</body>

</html>
```

**Comment by tomitrescak** [comment]
Looks like the problem is when I try to build into "build" directory. When I build into root all is good.

**Comment by nchanged** [comment]
`devServer` requires `index.html` next to the bundle in order for it to work. But yes, you can change `root` to any other existing folder

**Comment by basarat** [comment]
> Looks like the problem is when I try to build into "build" directory. When I build into root all is good.

By default it serves the folder where the outFile is. You can change it by passing some other folder for root. Docs updated here : https://github.com/fuse-box/fuse-box/pull/119/files#diff-01c8e55da4da91dc1911cf06ed57f356R14 / https://github.com/basarat/fuse-box/blob/2cc7ec8e0b880e209f903cbc58bbd513a5237e08/docs/devserver.md#changing-the-the-served-folder

@nchanged the PR was merged https://github.com/fuse-box/fuse-box/pull/119 but docs at http://fuse-box.org/#dev-server-and-hmr are still out of date. Is publishing not automatic or did I do something wrong? Thanks again :rose:

**Comment by nchanged** [comment]
@basarat thanks! it is usually automatic. I had some problems with the hook. fixed it now.

**Comment by basarat** [comment]
@nchanged quick question: How is `homeDir` used: http://fuse-box.org/#home-directory

The only impact I can see of it is how `tsconfig.json` is picked up (its picked from the home-directory by default). Is there anything else that is impacted by it? Thanks :rose:

All paths seems to relative to `process.cwd()` and changing `homeDir` has no effect with my limited testing :rose:

**Comment by nchanged** [comment]
`homeDir` is where you project lives. It affects bundling as well.
Imaging
```
src/
    a.ts
    b.ts
```

setting `homeDir` to `src` would lock it to that folder, producing bundle with the scope `a.js` `b.js`
Setting it to the root, would change it to `src/a.js` `src/b.js`

**Comment by nchanged** [comment]
@basarat homeDir is very important. As it affects the scope. It has to be clarified in docs...

**Comment by nchanged** [comment]
@tomitrescak can we close this one now?

**Comment by tomitrescak** [comment]
Yes, all clear now.

**Comment by tomitrescak** [comment]
Yes, all clear now.
