### ISSUE TITLE
auth0-lock issues

### ISSUE THREAD

**Issue by camreyaro** [fuse-box/fuse-box#1161]
Hi, I'm trying to bundle auth0-lock (10.2.2 version), but I can't make it work.

In my entry file:
`require('auth0-lock')`

In my fuse.js file:
` target : 'browser',`

I'm getting "Failed to instantiate module" error, and "Base64 not found on request", too.

Thanks.

**Comment by devmondo** [comment]
@camreyaro 
do it like this and it shall work
`import * as auth from "auth0-lock";`

check image
![image](https://user-images.githubusercontent.com/1266367/37455590-db3fb35a-2856-11e8-9043-07866f37b2b8.png)

**Comment by nchanged** [comment]
closing this for now.
