### ISSUE TITLE
Patching `global` variable is not complete

### ISSUE THREAD

**Issue by pavel** [fuse-box/fuse-box#1163]
`LoaderAPI.ts` on master (4f5d2530232ed235a27bbabf9cf64afb32aca526) file [contains](https://github.com/fuse-box/fuse-box/blob/4f5d2530232ed235a27bbabf9cf64afb32aca526/src/loader/LoaderAPI.ts#L54-L57):

```ts
// Patching global variable
if ($isBrowser) {
    g["global"] = $isWebWorker ? {} : window;
}
```

This does not accommodate for a ServiceWorker case.

**Comment by nchanged** [comment]
Hi @pavel 
thanks for submitting the issue.
Do you think you can make a PR and add the ServiceWorker case?
