### ISSUE TITLE
antd design base project with locale

### ISSUE THREAD

**Issue by jezikk** [fuse-box/fuse-box#1170]
Hi,

I'm trying to create a simple antd project using fuse-box. Basically it is only an entry point described in https://ant.design/docs/react/getting-started.

My fuse-box settings:
```
const { context, src, task } = require('fuse-box/sparky');
const {
    FuseBox,
    WebIndexPlugin,
    QuantumPlugin,
    LESSPlugin,
    SVGPlugin,
    CSSPlugin,
    EnvPlugin,
    JSONPlugin
} = require('fuse-box');

task('default', async context => {
    await context.cleanDist();
    const fuse = context.getConfig();
    context.enableServer(fuse);
    context.createBundle(fuse);
    await fuse.run();
});

task('build', async context => {
    await context.cleanDist();
    context.isProduction = true;
    const fuse = context.getConfig();
    context.createBundle(fuse);
    await fuse.run();
});

context(
    class {
        getConfig() {
            return FuseBox.init({
                homeDir: 'src',
                target: 'browser@es5',
                output: 'dist/$name.js',
                sourceMaps: !this.isProduction,
                cache: !this.isProduction,
                allowSyntheticDefaultImports: true,
                alias: {
                    '~/component-indexof.js': 'component-indexof'
                },
                plugins: [
                    WebIndexPlugin({
                        target: `index.html`,
                        template: `./index.html`,
                        path: '/'
                    }),
                    EnvPlugin({
                        NODE_ENV: this.isProduction
                            ? 'production'
                            : 'development'
                    }),
                    SVGPlugin(),
                    JSONPlugin(),
                    [LESSPlugin({ javascriptEnabled: true }), CSSPlugin()],
                    this.isProduction &&
                        QuantumPlugin({
                            treeshake: true,
                            uglify: true,
                            bakeApiIntoBundle: 'app'
                        })
                ]
            });
        }

        enableServer(fuse) {
            fuse.dev({
                port: 3000,
                hmr: true
            });
        }

        createBundle(fuse) {
            const bundle = fuse.bundle('app').instructions('> index.tsx');
            if (!this.isProduction) {
                bundle.watch().hmr();
            }
            return bundle;
        }

        async cleanDist() {
            await src('dist/')
                .clean('dist/')
                .exec();
        }
    }
);
```
My tsconfig settings:
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "ES5",
        "sourceMap": true,
        "inlineSources": true,
        "jsx": "react",
        "importHelpers": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "allowSyntheticDefaultImports": true
    }
}
```
My entry point:
```
import * as React from 'react';
import * as ReactDOM from 'react-dom';

import { LocaleProvider } from 'antd';
import fr from 'antd/lib/locale-provider/fr_FR';

import { App } from './App';

const Main = () => (
    <LocaleProvider locale={fr}>
        <App />
    </LocaleProvider>
);

ReactDOM.render(<Main />, document.getElementById('root'));
```
I'm getting the following error:
```
Uncaught TypeError: Cannot read property 'default' of undefined
GET http://localhost:3000/antd/lib/locale-provider/fr_FR 404 (Not Found)
antd/lib/locale-provider/fr_FR not found on request
```
My example is available here: https://github.com/jezikk/fusebox-antd-starter

I searched the internet, but I did not find anything. Can you please help me? There are two similar projects fuse-box-antd-example and fuse-box-antd available, but both are obsolete.

**Comment by jezikk** [comment]
I made some updates in `tsconfig.json`:
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "ES5",
        "sourceMap": true,
        "jsx": "react",
        "moduleResolution": "node",
        "esModuleInterop": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "allowSyntheticDefaultImports": true
    }
}
```

Now there is only one issue that import `import locale from 'antd/lib/locale-provider/en_GB';` is not resolved:
 
```
GET http://localhost:3000/antd/lib/locale-provider/en_GB 404 (Not Found)
antd/lib/locale-provider/en_GB not found on request
```

**Comment by devmondo** [comment]
@jezikk  it is because there is no named exports, you can change your import to 
`import * as fr from 'antd/lib/locale-provider/fr_FR';`
or enable fuse synthatic imports https://fuse-box.org/page/configuration#allowsyntheticdefaultimports

**Comment by jezikk** [comment]
@devmondo  Thanks for your response, but I'm currently using `allowSyntheticDefaultImports: true` in both `tsconfig.json` and fusebox settings.

I have two projects. First project is bundled with webpack and works without any problem:
```
https://github.com/jezikk/webpack-antd-starter
```

I'm trying to achieve the same result with fusebox here:
```
https://github.com/jezikk/fusebox-antd-starter
```

`tsconfig.json` is the same as well as the code, but fusebox configuration is more complex than the webpack. I do not know where the error is. Current fusebox settings available on Github returns the following errors:

```
WARNING File "C:\Users\Michal\Documents\Projects\fusebox-antd-starter\node_modules\antd\es\modal\locale.js" cannot be bundled because it's out of your project directory (homeDir)
  → WARNING File "C:\Users\Michal\Documents\Projects\fusebox-antd-starter\node_modules\antd\es\date-picker\locale\en_US.js" cannot be
bundled because it's out of your project directory (homeDir)
  → WARNING File "C:\Users\Michal\Documents\Projects\fusebox-antd-starter\node_modules\antd\es\time-picker\locale\en_US.js" cannot be
bundled because it's out of your project directory (homeDir)
  → WARNING File "C:\Users\Michal\Documents\Projects\fusebox-antd-starter\node_modules\antd\es\time-picker\locale\en_US.js" cannot be
bundled because it's out of your project directory (homeDir)
  → WARNING File "C:\Users\Michal\Documents\Projects\fusebox-antd-starter\node_modules\antd\es\calendar\locale\en_US.js" cannot be bundled because it's out of your project directory (homeDir)
  → WARNING File "C:\Users\Michal\Documents\Projects\fusebox-antd-starter\node_modules\antd\es\date-picker\locale\en_US.js" cannot be
bundled because it's out of your project directory (homeDir)
```

**Comment by devmondo** [comment]
@jezikk i dont know if it is a bug, but i tried adding `js` extension to in my local test and it worked.
try to do it here 
https://github.com/jezikk/fusebox-antd-starter/blob/master/src/index.tsx#L4

**Comment by jezikk** [comment]
@devmondo  I've made change in code, but now getting the following error:
```
Uncaught Package not found antd\es\locale-provider
```

Next, there is a strange behavior in this use case:

1. I removed the folder `.fusebox` from the project.
1. I run `npm start`.
1. Fusebox returns the following warnings:
![warning](https://user-images.githubusercontent.com/7671531/38102307-1fad2dec-3383-11e8-9df8-038f18efcf22.png)
1. I stopped dev server by CTRL + C
1. I run dev server again using `npm start`
![success](https://user-images.githubusercontent.com/7671531/38102398-63d3fbfe-3383-11e8-9254-a74cc23ac2c7.png)
1. Warnings are no longer displayed.

**Comment by devmondo** [comment]
always clean the cache like u did  when you face strange issue :) 
again maybe it is a cache bug, but at least i see it working now

**Comment by jezikk** [comment]
@devmondo But it doesn't work. These error is shown:

Uncaught Package not found antd\es\locale-provider

And components are not rendered.

**Comment by devmondo** [comment]
@jezikk i tried to run your repo locally, but i got many errors about no access allowed, etc...

i see that you still have those 2 lines
```js
import { LocaleProvider } from 'antd';
import locale from 'antd/lib/locale-provider/cs_CZ';
```

both of them are files with `js` extension 
![image](https://user-images.githubusercontent.com/1266367/38118944-72632c2a-33cf-11e8-9ce3-123da2b98489.png)

But, you still did not add the extension in the import. 
`allowSyntheticDefaultImports` is not related to that, it is related to allow babel default style imports.
the problem is that Typescript does not recognize `.js` file extension, so just add extensions as below and see if it works.

```js
import { LocaleProvider } from 'antd.js';
import locale from 'antd/lib/locale-provider/cs_CZ.js';
```

**Comment by jezikk** [comment]
After suggested update the followinf error is shown:
```
Uncaught Package not found antd.js
```

It's still weird because ts-loader works successfully without these extensions.

**Comment by devmondo** [comment]
@jezikk you cant do it like this
`import { LocaleProvider } from 'antd.js';`

there is no`antd.js` the package itself is `antd`, so i checked they have dist folder and you can try 
``import { LocaleProvider } from 'antd/dist/index.js';`

**Comment by jezikk** [comment]
@devmondo  Ok, I've made a new project which is almost working:

https://github.com/jezikk/fusebox-antd-test

I think there is one last problem in the `DatePicker` component. This component uses `moment` localizations and looking for the wrong path:

![err](https://user-images.githubusercontent.com/7671531/38178309-4d9de900-3610-11e8-9830-a840dd76d411.PNG)

I believe that this `new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, /ru/)` could solve my problem based on the following:

https://stackoverflow.com/questions/44522693/antd-locale-is-undefined

@devmondo  Can you please help me to achive this in fusebox? Is there any similar plugin as ContextReplacementPlugin in webpack?

Thank you!

**Comment by jezikk** [comment]
The code below solved my problem as described in Antd docs:
```
import * as React from 'react';
import * as moment from 'moment';
import { render } from 'react-dom';

// Antd settings
import LocaleProvider from 'antd/lib/locale-provider';
import locales from 'antd/lib/locale-provider/cs_CZ';
import 'moment/locale/cs';
moment.locale('cs')
```
