### ISSUE TITLE
NWJS Target

### ISSUE THREAD

**Issue by Kaffiend** [fuse-box/fuse-box#1172]
Any plans or requirement to implement nwjs target similar to webpack?

**Comment by nchanged** [comment]
@Kaffiend Isn't it like electron? 

Do you think you can test it out?

**Comment by Kaffiend** [comment]
@nchanged you can access node api in the DOM, I’m not sure what that would entail on the bundler side. I’m trying it out right now as I would rather not use webpack 😊

Ian Mackie
Lead Developer

**Comment by Kaffiend** [comment]
I think it might require a new target, that allows both server and browser fields in the DOM. `electron` target still warns about `zone.js` (angular) and node api does not appear to be available.

**Comment by Kaffiend** [comment]
belay my last, updated to newest version of fusebox and it works!, maybe an alias for `nwjs` or `node-webkit` for a clear target?

**Comment by nchanged** [comment]
@Kaffiend an alias to electron target?

**Comment by nchanged** [comment]
@Kaffiend I will be happy to accept a PR, 
I will close this issue for now.
