### ISSUE TITLE
Allow splitting packages into a group 

### ISSUE THREAD

**Issue by leon-andria** [fuse-box/fuse-box#1174]
Splitting packages work nicely however there is no way to organize or grouping some packages with other.
Let's assume that we have the following packages name:

- pkg1
- pkg2
- pkg3

What I would like to achieve is to reorganize **pkg1** & **pkg3** in a bundle, and **pkg2** in another bundle.
With FuseBox, we can enforce strong guidelines with a Team who develop a large application by recommending to use massively the syntax:
```javascript
let r = await import("xxx");
```
By using the code splitting config, I would expect below grouping syntax:
```javascript
{
   "bundle1": [ "pkg1", "pkg3" ],
   "bundle2": [ "pkg2" ]
}
```
bundle1 a bundle2 are named bundles but can be like bundle-[hash] during the finalization of the process.
What is the real benefits behind this ?
No matter how big or small you application, you can develop without thinking anymore about code splitting, the rule of thumb is just do import. Of course, FuseBox by default do the splitting as it is today, auto split per package.
If you are not happy with the default behavior, you can start to reorganize by optimizing the code splitting configuration.

**Comment by nchanged** [comment]
Right, so you are suggesting grouping modules into a one bundle using config. What would come once you import it? 

It doesn't sound very good, because typescript won't allow it, and it's off the standard, unless you specify typings for it.

```js
const {moment, foobar } = await import("foo")
```

**Comment by leon-andria** [comment]
It's not what i meant. The developper doesnt do the syntax you are writing, otherwise it's a mess.
You don't change the way you are coding. The grouping or reorganization is a step for optimizing bundles by knowing well you application behavior.
Having a sort of mapping configuration would be nice.

**Comment by nchanged** [comment]
@leon-andria what prevents you from create a module that exports these 2 bundles?
`woo.ts`
```js
export foo from "foo";
export boo from "boo"
```

```ts
const {foo, boo} = await import("./woo")
```

**Comment by leon-andria** [comment]
Not a bad idea in a development phase but it's not what i want.
In a simple term, think it in a step of workflow.
1 guy who develops and 1 guy who manage the optimization. So, your developper should code as normal without knowing in advance how this will be bundled in the final process.

**Comment by leon-andria** [comment]
Does it help to have an idea if i'm telling you bundler visualizer?
