### ISSUE TITLE
Support for http & https in browser

### ISSUE THREAD

**Issue by dynasource** [fuse-box/fuse-box#1178]
Hi, thanx for all the efforts done to make this software.

I'm trying to understand how to use Node's `http` and `https` native modules in the browser. Is there support for this yet (like in Webpack?)?

**Comment by nchanged** [comment]
Hi @dynasource 
All it takes is adding a polyfill here.
https://github.com/fuse-box/fuse-box/blob/master/modules/http/index.js

We are happy to accept a PR ;)

**Comment by nchanged** [comment]
Will close this issue for now, please re-open once you have something
