### ISSUE TITLE
[issue] Strange behaviour with hot reload

### ISSUE THREAD

**Issue by vitorcamachoo** [fuse-box/fuse-box#118]
Hei, I have several issues when using devServer.

First, when I run ``devServer`` with ``cache:false`` the browser do not reload.
The next issue is, if I have cache active, the hot reload works but with strange behaviors, for example if I had the following import:
```js
import angular from 'angular'
```
and add other imports for example:
```js
import angular from 'angular'
import material from 'angular-material'
```

Sometimes it compiles right, but sometimes it don't and it throw an error trying to request
``angular-material was not found upon request``
![image](https://cloud.githubusercontent.com/assets/20595956/22850594/1176b086-f004-11e6-8252-524743130817.png)

And the other issue, is, if I try: (using cache:true)
```js
import lodash from 'lodash';
console.log(lodash.map)
```
result: 
![image](https://cloud.githubusercontent.com/assets/20595956/22850615/7637ec88-f004-11e6-8926-879abf883919.png)

and if I change the import to 
```js
import map from 'lodash/map';
console.log(map)
```
![image](https://cloud.githubusercontent.com/assets/20595956/22850620/9b40fb8c-f004-11e6-8eb8-ef5978e6932d.png)

Thanks.

**Comment by nchanged** [comment]
Welcome @vitorcamachoo !
That's a known issue, each time you add new dependency you need to refresh the page. I have a plan how to quickly solve for now - just refresh the page, in case of `require` failure.

Let me know if you have better ideas

**Comment by vitorcamachoo** [comment]
Hi, thanks.

The thing is, even refreshing the broken, it always throw that error. I need to restart all the process, ie, kill the task and start again.

**Comment by nchanged** [comment]
@vitorcamachoo sorry to hear that If you could create a repo where we can reproduce your error, that would help a lot!

**Comment by devmondo** [comment]
closed for inactivity, please reopen if otherwise :)
