### ISSUE TITLE
Angular 1 example

### ISSUE THREAD

**Issue by jpike88** [fuse-box/fuse-box#1182]
Would be great if someone could create an angular 1 example, including implementation of how HMR would work.

**Comment by nchanged** [comment]
@jpike88 Hi
https://fuse-box.org/page/ngtemplateplugin

There is everything, including HMR

**Comment by jpike88** [comment]
Damn sorry, missed it... that wasn't easy to find! Maybe its worth putting some clearer links on the docs site?

**Comment by nchanged** [comment]
@jpike88 it's on the plugin list ;-)

**Comment by nchanged** [comment]
@jpike88 Yes, if you can help with that - it would be great!

**Comment by jpike88** [comment]
How do you locally host those docs to work on them? I just see markdown and a json file?

**Comment by nchanged** [comment]
you can't host them, but they look pretty much the same on the web page
