### ISSUE TITLE
lot of typescript files in this repository don't compile

### ISSUE THREAD

**Issue by vemoo** [fuse-box/fuse-box#1183]
If I run `sh -c 'find src -iname tsconfig.json | while read f; do echo "PROJ: $f"; tsc -p "$f" --noEmit; echo; done'` from the root of this repository, there are lots of errors. What does that mean? It seems to me that a lot of the tests are abandoned.

Even when running `gulp dist` I get `src/loader/LoaderAPI.ts(9,33): error TS2304: Cannot find name 'ServiceWorkerGlobalScope'.`

**Comment by nchanged** [comment]
what do you mean by a lot of tests are abandoned? that typing issue is a known one

**Comment by nchanged** [comment]
Ah right we've introduced tslint not long time ago, so clearly there are bunch of errors, doing it one step at a time )

**Comment by vemoo** [comment]
those are not tslint errors, those are typescript errors, thats invalid typescript code

**Comment by nchanged** [comment]
as for me, the only error I get is about that `ServiceWorkerGlobalScope `

**Comment by vemoo** [comment]
what command have you run?
have you tried openning the file in vscode?

**Comment by vemoo** [comment]
I think I figured it out. Those are errors, but typescript fixes them when transpiling. So that's why the tests work.

They don't show when running fuse-box because it uses `ts.transpileModule` which only reports syntactic errors (no typechecking) and it's ignoring its diagnostics.

So I see 2 issues:

- Here https://github.com/fuse-box/fuse-box/blob/89c008db416c773cfebee9ef611297dc4564e403/src/core/File.ts#L663 `result.diagnostics` should be checked and logged
- How can I get typescript typechecking errors with fuse-box?

**Comment by nchanged** [comment]
Let's close this for now
