### ISSUE TITLE
Quantum bug

### ISSUE THREAD

**Issue by leon-andria** [fuse-box/fuse-box#1184]
Hi, I have a very annoying issue with quantum, 
This is the index.ts code I have 
```js
(async () => {
    const moment = await import("moment")
    console.log(moment);
 })();
```
Now with this simple standard config 
```js
const sharedFuseConfig = {
    homeDir: `src`,
    cache: true,
    modulesFolder: `${__dirname}/node_modules/`,
    plugins: [
      QuantumPlugin({
            target : 'browser',
            bakeApiIntoBundle : 'app',
            manifest : true,
            containedAPI : false,
            removeExportsInterop : false,
            replaceTypeOf:false,
            removeUseStrict : false,
            ensureES5 : false
        })
    ],
    output: `./dist/$name.js`
};
```
Now when I do node fuse, everything is fine and fuse creates a split bundle for `momentjs` but now if I modify my `index.ts` and save it fuse watcher kicks again but now I get an empty `momentjs` splitted file like this:
```js
(function($fsx){
})($fsx);
```
 The only way around this is to stop the fuse process everytime I change my local code and restart so quantum will create a none empty split `momentjs` file.

So to explain better, what is happening is that with quantum enabled, it works and kicks  but it creates empty split files and you have to restart fuse process in order to avoid this issue. Which is something I don’t want at all, because for me I want to see my production result immediately and I don’t want to go through the dev vs production process. That is why I enabled quantum by default.

**Comment by nchanged** [comment]
I get it, will check it out next week, thanks!

**Comment by leon-andria** [comment]
Keep me update on your findings. This bug is really a blocking point.

**Comment by nchanged** [comment]
I will get to it when I will have time.

**Comment by leon-andria** [comment]
Thanks for your support!
By the way, I debug it and I found out where is the bug. It takes 20 min to figure it out but the bug is special on this line: https://github.com/fuse-box/fuse-box/blob/master/src/quantum/plugin/QuantumCore.ts#L167
Specially this line is so confusing but I guess, you know what you wrote. To solve the bug, I have to add the following line after it:
```js
this.producerAbstraction.bundleAbstractions.get(key).packageAbstractions = bundleAbstraction.packageAbstractions;
```
The problem is that after the first bundle, packageAbstractions from bits are empty. So, if you want the render to write content, https://github.com/fuse-box/fuse-box/blob/master/src/quantum/plugin/QuantumCore.ts#L267. You have to fullfil packageAbstractions.

Again, after debugging all of this, even i say I solve it, I feel that there is something wrong somewhere.
Up to u to understand it if this allows you to figure out it !

**Comment by nchanged** [comment]
@leon-andria been looking at it for a while, can't find a solution just yet. If you have ideas please share ;-) It might be related to the old variables being populated

**Comment by leon-andria** [comment]
@nchanged I will look at this tonight, with the last debugging experience I got to track this issue, I have a better idea.

**Comment by DitlevHB** [comment]
Hi
I am facing the same issue, with a simple setup dynamically loading a module

``` 
import("lodash").then((module)=> console.log(module)); 
```

with the fusebox config

```
FuseBox.init({
        homeDir: "./src",
        output: "dist/$name.js",
        cache: false,
        sourceMaps: !isProduction,
        useTypescriptCompiler: true,
        plugins: [
            QuantumPlugin({
                treeshake: true,
                target: "universal",
                bakeApiIntoBundle:"app"
            })
        ]
    });
```

Initial build works flawless, but after saving the file with the dynamic import of lodash (while fuse is running) , it just fails, producing

```
(function($fsx){
})($fsx);
```

in the new file generated by QuantumBit: Moving module lodash from app to 6cb2ad0d

Help appreciated! :)

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
