### ISSUE TITLE
Recommended method of including external JS files

### ISSUE THREAD

**Issue by jpike88** [fuse-box/fuse-box#1187]
I am moving from a legacy codebase and have heaps of JS files with all overload global.

Using the shim function is not practical because we have too many globals to worry about.

This is just for our 'lib' folder, our actual core app is all TypeScript and follows the rules for proper ES6 module packaging.

Is there a way to expose a bunch of .js files to the global scope, basically concatenating them and running without any bundling, in a way that works here?

What is the recommend path here?

**Comment by nchanged** [comment]
@jpike88 yep you can 
1) Copy them to the dist folder and importing them using `import()` that would be many requests tho
2) you can create a custom task with sparky that simply concatenates them, outside of fusebox bundling process
3) Create a plugin that  does `step 2` 😃

**Comment by jpike88** [comment]
I'd love to do 3, I really like this project and plan to start making contributions shortly
