### ISSUE TITLE
Uglifying error with uglify-js

### ISSUE THREAD

**Issue by pmonty** [fuse-box/fuse-box#1190]
I have been working through getting FuseBox working it has been stressful but I am nearly there. Below is a screenshot of the error(s) i am getting. 

I am getting a weird ```→ WARNING Ignoring local @import of "/css-resources/281877879.css" as resource is missing.``` and the more obvious ```→ Error during uglifying app```

![image](https://user-images.githubusercontent.com/7111292/38592279-8b2a9c80-3d7e-11e8-8e5e-afbfb3f111dd.png)

Here is my [code/gist](https://gist.github.com/pmonty/6cfb141ab6e3da093a423187c83a35bf)

Things I have tried:
- I have tried using uglify-es.
- I updated the version of uglify-js and -es to match in my package.json and the package.json in `fuse-box/node_modules`. 
- Deleting .fusebox folder (which I do in my clean task anyway)

Things I am thinking it might be related too:
- ~~my use of `$(__dirname)` messing around with paths?~~
-  uglify-js (or -es) specific error? Though I did uglify-js manually in my terminal with the following command `uglifyjs app.js -c -m -o app.min.js` on my unoptimised/non-production output and it worked.
- fuse-box bug

Not sure what the issue might be and not sure on how to do the following:
- get uglify-js error or log information
- tell what options fuse-box uses to uglify
- determine why the ignoring local @import css bug is occuring but my styles still builds

any help would be amazing! This has been much more stressful than it should have been unfortunately and don't really want to turn around and go back to webpack just because these two (what I hope are the last ones) errors are causing me grief :(

I will update the lists and scratch off ones i try

**Edit**
Just to test I added what is definitely newer than es5 code to my playground app below.

```
const ComponentTest = (props) => {
    return (<div>{props.test.toString()}{props.tests}</div>)
}

class App extends React.Component<{}, {}>
{
    public render()
    {
        const spreadstuff = {
            test: 5,
            tests: "test"
        };
        return <div><p>Hello World<ComponentTest {...spreadstuff}/></p><Login /></div>;
    }
}
```

and it compiled and uglyfied perfectly fine whether I set it to sue uglify-js or uglify-es, with pretty much the exact same (very very close) fuse.ts file to my main project.

**Comment by pmonty** [comment]
So I removed that Env variable as a test and got the exact same error (including the line, col, pos). 

Is there a way to have that IMAGE_PATH use absolute path as it is needed? Maybe `definedExpressions`?

Also any idea about the css issue aswell?

**Comment by nchanged** [comment]
CSSResourcePlugin can't resolve your path that's the problem

**Comment by pmonty** [comment]
Oh so after some thorough research last night it seems to be erroring on this code in my Constants file

**Bundle code parsed to uglify**
```
var Constants = function () {
    function Constants() {
        this.wholesalerSettings = [object Object];
        this.API = this.setHostUrl();
    }
```
**Actual Code before build**
```
    constructor() {
        this.wholesalerSettings = process.env.WHOLESALERSETTINGS;
        this.API = this.setHostUrl();
    }
```

**Where I set WHOLESALERSETTINGS in Fuse.ts**
```
EnvPlugin({ 
    WHOLESALERSETTINGS: this.wholesalerSettings,
    IMAGE_PATH: `./src/~/wholesalers/${this.wholesaler}/images/`
}),
```

So what is the correct way to have those global variables used?
