### ISSUE TITLE
Dynamic Images 

### ISSUE THREAD

**Issue by pmonty** [fuse-box/fuse-box#1192]
So in a WebPack version I had a function that would require

```
const getImageByName = (filename: string): any => {
    const result = require(process.env.IMAGE_PATH + '/' + filename);
    return result;
};

export { getImageByName };
```

and would use it by just doing the following in my img tags in jsx

```
<img src={getImageByName('filenamehere.png')} />
```

Though this does not seem to be working anymore in FuseBox. I thought it might be because of TypeScript but it worked in my TypeScript webpack version and from what I can find require should work in TypeScript. 

Not sure what the issue could be or if there is a plugin I am missing. 

Here is my [code/gist](https://gist.github.com/pmonty/6cfb141ab6e3da093a423187c83a35bf)

**Comment by nchanged** [comment]
@pmonty Hi
We have [CopyPlugin](https://fuse-box.org/page/copy-plugin#usage)
It copies the file and gives you a URL

I will close this issue for now. This plugin does exactly what you want

**Comment by pmonty** [comment]
Have added the following line.

```
CopyPlugin({ files: ['*.png'] }),
```

But code above still doesn't work, there isn't any errors or issues building or running. 

I noticed it didn't copy the files over into dist and then when I inspect it inside of dev tools it says `./login-icon.png not found on request`

**Comment by nchanged** [comment]
You need to resolve it properly. It's up to your dev server

**Comment by pmonty** [comment]
Dev server? Shouldn't the images be in my dist folder if I am using the CopyPlugin()? 

So I am am building even without serving the project and they are not appearing in the assets folder. Does the CopyPlugin maybe need to go first before all other plugins?

**Comment by nchanged** [comment]
Make sure nothing else intercepts your png files, They will appear in the dist folder, yes.
Configure it 
https://fuse-box.org/page/copy-plugin#dest

**Comment by pmonty** [comment]
Set dest to static as a test but still no images. I also thought it might be the * symbol I had infront of .png so tried with and without.

```
plugins:
                [
                    CopyPlugin({ files: ['.png'], dest: "static"}),     
                    [
                        SassPlugin({ importer: true }),
                        CSSResourcePlugin({ dist: "dist/assets/css-resources" }),
                        CSSModules({ scopedName: '[local]'}),
                        CSSPlugin(this.cssOptions)
                    ],               
                    EnvPlugin({ NODE_ENV: this.environment }),
                    WebIndexPlugin({ template: `${__dirname}/src/index.html` }),
                    this.isOptimised && QuantumPlugin({ bakeApiIntoBundle: 'vendor', treeshake: true, uglify: true, css: true})
                ]
```

As you can see I put the **CopyPlugin** ahead of the rest and still did not work. 

Not sure what you mean when ensure nothing else is intercepting the png files but they are certainly only referenced by that function and in the img tag.

**Comment by nchanged** [comment]
Working for me
https://github.com/fuse-box/fuse-box-examples/

**Comment by pmonty** [comment]
Will take a closer look tonight soon but not sure why mine is not working copied the CopyPlugin line exactly the same. I do get the following when I run quantum

``` 
Warnings:
Your quantum bundle might not work
   - Computed statement warning in default/services/Assets.js
``` 

On my function:
```
const getImageByName = (filename: string): any => {
    const result = require(process.env.IMAGE_PATH + '/' + filename);
    return result;
};

export { getImageByName };
```
 Not sure why no errors just that warning but still bundles.

**Comment by nchanged** [comment]
You can't use dynamic statements. Use the copy plugin

**Comment by pmonty** [comment]
Oh so unlike webpack they can't be dynamic? 

So I added an import statement 

```
import Logo from './login-icon.png';

<img src={Logo} />

```

that worked... but doesn't help the fact that the image will be different for each build based on a ENV variable. 

Could dynamic imports fix this?

**Comment by pmonty** [comment]
Been looking at this issue all day so far and can't come up with a solution. I don't really want to write a task that would edit the appropriate files and add static imports where needed as this would mean that if we add an image then we need to update the Sparky task. This really should be a plugin or feature that allows this sort of stuff cause it is definitely something that is needed when people are in my situation where they need to load different images based on an environment variable and want the build process to be quick so they can switch between either and not need to worry about changing any code in my example it would be as easy as...

`WHOLESALER=UD yarn run build --optimise`
and then once that is done and I build for the next WHOLESALER all I do is quickly change the WHOLESALER node variable
`WHOLESALER=AC yarn run build --optimise`

This would be a really nifty feature, definitely see that it might increase the build time so a plugin would be better as it then would not be something that has to be done or would only take effect if absolutely necessary

**Comment by nchanged** [comment]
@pmonty computed require statements is in our plans, but I am sure there is a way to make you thing work with FuseBox

**Comment by pmonty** [comment]
Oh that is great news then! 

Yeh going to try a few things over the weekend. I think CSS classes might be the way at the moment. It is definitely working for our smaller image files (.svg)

**Comment by pmonty** [comment]
Tried the CSS classes and not quite working. It is importing my .SVG and .CSS files as `_XXXXXXX.filetype` XXXXXXXX is any combination of just numbers. Though when I did import it and do it like...

```
import IMG as '../images/logo.svg';

//...

<img src={IMG} />
```

The file gets copied as [hash]_[filename].[filetype] which is nice and obviously works. Shouldn't it be working like the same for CSS url()?

Also is there a timeline on computed require statements?

**Comment by nchanged** [comment]
You  need CSSResourcePlugin that does what you want, I don't know yet when I will have time for dynamic statement resolution - it's a very very challenging task

**Comment by pmonty** [comment]
Fair enough.

My CSSResourcePlugin is setup like:
```
                        CSSResourcePlugin({ 
                            dist: './dist/assets/css-resources',
                            resolve: (f) => `/assets/css-resources/${f}`
                        }),
```

It is copying the files as `_870402667.png` and then when I visit `http://localhost:8080/css-resources/_870402667.png` it shows. But when I run the app it doesn't. Which is strange cause the output css is correct.

```
<i class="icon"></i>
// ..
.icon {
    background: url(/assets/css-resources/_870402667.png);
}
```

**Comment by nchanged** [comment]
read up on how to configure the resolution, it's a pretty obvious error and it's all described in the doc

**Comment by pmonty** [comment]
Ah kk got it working with `macros`.

Is there anything I could do to help with computed/dynamic require statements? Even document some stuff or requirements?

**Comment by nchanged** [comment]
Yes, we need the specs. 
Here is some reference too https://github.com/fuse-box/fuse-box/issues/1166

**Comment by nchanged** [comment]
It could do the trick,yep!
