### ISSUE TITLE
Typescript re-compiles all files on file changes

### ISSUE THREAD

**Issue by jpike88** [fuse-box/fuse-box#1196]
Is that supposed to happen? I would have thought it would tree-shake on recompilation

**Comment by nchanged** [comment]
tree shaking happens on with Quantum, it's used to make production builds. Don't do it for development. FuseBox re-compiles only one file, that one that changed. If you have it all re-compiled, check for `cache` option, it should be either removed, or set to `true`

**Comment by jpike88** [comment]
size: 2.1 MB in 11s 15ms

**Comment by jpike88** [comment]
Heaps of "Source changed for blah" messages are firing on all the .ts files instead of just the one I changed

**Comment by jpike88** [comment]
Ok its behaving now...
