### ISSUE TITLE
Split CSS Files

### ISSUE THREAD

**Issue by smitt04** [fuse-box/fuse-box#1199]
It would be nice to be able to split css files for a couple of reasons.

1. Split out css per bundle. i.e. (vendor.css, app.css)
2. Specify css bundles. i.e. (light.css, dark.css)

For QuantumPlugin we can specify css files with
```
cssFiles : { "dark**" : "dark.css", "light**" : "light.css" }
```

For dev, we may need a manifest file to do dynamic loads.

**Comment by nchanged** [comment]
For vendors:
```
cssFiles : { 
   "node_modules/**" : "vendor.css"
   "dark**" : "dark.css", 
   "light**" : "light.css" 
}
```

**Comment by smitt04** [comment]
@nchanged 
I see that the original style.css gets created from here
https://github.com/fuse-box/fuse-box/blob/master/src/quantum/plugin/modifications/CSSModifications.ts#L22-L23

The quantum plugin is only keeping track of a single `cssCollection`, should we add a new `cssCollections: CSSCollection[]` that handles all other css files?

**Comment by nchanged** [comment]
Yep, but in our case, we need to introduce groups in the `CSSCollection` then once populated,
this part

https://github.com/fuse-box/fuse-box/blob/ef7e577b778fb07667870a89492f7d0fdd14e152/src/quantum/plugin/BundleWriter.ts#L134-L159

needs to be modified in order to respect the config

**Comment by nchanged** [comment]
```
   const cssFile = new CSSFile(cssPath, cssRaw);
  const group =  defineGroupByCriteria(cssFile)
  const collection =   core.cssCollection.get(group)
  collection.add(cssFile);
```

Something like that

**Comment by smitt04** [comment]
so `core.cssCollection.get(group)` returns a `CSSCollection`instead of say having `core.cssCollections` and a `core.getCSSCollection(group)`?

So should we change `core.cssCollection` from `CSSCollection` to `core.cssCollection: Map<string, CSSCollection>` and at minimum have a `css` group? 

I am guessing the group name will be what gets saved in the manifest, and to not break it we would need a `css` group.

**Comment by smitt04** [comment]
I have an initial version working here. https://github.com/smitt04/fuse-box/commit/00fd5dc73ffa57481ea301f6e0772e03a41ddc3d

I just need to do some more testing and possibly figure out what to do with key names in the manifest file.  It looks something like: 
```
{
  "light**": {
    "filename": "light.css",
    "type": "css",
    "absPath": "/Users/**/projects/smitt04/fuse-box/_playground/generic/dist/light.css",
    "webIndexed": true
  },
  "dark**": {
    "filename": "dark.css",
    "type": "css",
    "absPath": "/Users/**/projects/smitt04/fuse-box/_playground/generic/dist/dark.css",
    "webIndexed": true
  },
  "app": {
    "fileName": "app.js",
    "type": "js",
    "absPath": "/Users/**/projects/smitt04/fuse-box/_playground/generic/dist/app.js",
    "webIndexed": true,
    "relativePath": "app.js"
  },
  "api.js": {
    "fileName": "api.js",
    "type": "js",
    "absPath": "/Users/**/projects/smitt04/fuse-box/_playground/generic/dist/api.js",
    "webIndexed": true,
    "relativePath": "api.js"
  }
}
```
The key names are currently taken from the regex used in `cssFiles` an example `fuse.js`

```
const {FuseBox, WebIndexPlugin, QuantumPlugin, CSSPlugin} = require("../../.dev");
const fuse = FuseBox.init({
  homeDir: "src",
  output: "dist/$name.js",
  target: "browser",
  sourceMaps: true,
  plugins: [
    CSSPlugin(),
    WebIndexPlugin(),
    QuantumPlugin({
      manifest: true,
      css: true,
      cssFiles: {
        'dark**': 'dark.css',
        'light**': 'light.css'
      }
    })
  ]
});

fuse.bundle("app")
  .instructions(" > index.ts");
fuse.run();
```

**Comment by nchanged** [comment]
Looking good!
We need to figure out a key for `unmatched` and `vendor` (which package name isn't `default`)

**Comment by smitt04** [comment]
I have updated the names of the manifest file to use the file name attribute of `cssFiles`.  And the default styles uses the property of `cssPath`.  

I am now trying to determine if a file is a dependency or not.  I can't use the regex `node_modules/**` as the file names don't include that.

If I `import 'bootstrap';` then the name is either `'bootstrap'` or `dist/css/bootstrap.css` depending where I look.  @nchanged how can I determine if a require is a dependency or not? Also should we auto split vendors? or should the user be required to add something like `'node_modules/**': 'vendor.css'`?

**Comment by nchanged** [comment]
Yeah you can't really match them by node modules you have to use file property, which has packageAbstraction.name that's how you can determine if a package is external, for example , all local files are under default package name

**Comment by smitt04** [comment]
Ok, I have a `isVendor` check now which is `statement.file.packageAbstraction.name !== core.context.defaultPackageName`.

We need to figure out how to determine when we should split vendors or what the file name is.  It doesn't seem correct to have a vendor option in `cssFiles` as those are regex matches and vendors is a special case.  Should we have another quantum option like `vendorCSSPath: string = vendor.css' and if `vendorCSSPath === cssPath` then they would be merged otherwise split? Any other suggestions would be good too.

**Comment by nchanged** [comment]
Ok, We can have a naming convention of course. For example `vendor` would correspond to the actual vendors and won't be recognised as a regular match pattern, being present, however in the `cssFiles` config.

We could take it further, and introduce special characters, for example, `@vendor`
```
cssFiles {
   "@vendor" : "vendor.css",
   'dark**': 'dark.css',
    'light**': 'light.css'
}
```
But that's implicit, I have a twofold feeling about it. 

Another option is to pass an object, which is more explicit than the example above.
```
cssFiles : {
   {type : "vendor', file : "vendor.css"},
   'dark**': 'dark.css',
    'light**': 'light.css'
}
```

Another example where we want to extract jquery CSS

```
cssFiles : {
   'jquery/**.css': 'jquery.css',
    'default/**light**': 'light.css', // more explicit reference including package name
    'default/**dark**': 'dark.css'
}
```

I am more inclined towards the following approach

```
cssFiles : {
    'default/**light**': 'light.css', // more explicit reference including package name
    'default/**dark**': 'dark.css',
    '*': 'everything_else_could_be_vendor.css'
}
```
^ Whereas it's not really critical for the user to get the actual vendors, CSS splitting will be mainly used for theming. Everything else could be considered as a vendor. What do you think?

**Comment by smitt04** [comment]
I like the idea about prefixing the selector with the package name.  That makes it explicit, and you can easily split out to as many files as you want.  We would still need to have a way to group all app specific styles.  Maybe just `'default/*': 'styles.css'`.

The pattern would be `'{package}/{regex/glob pattern}': '{fileName}'`

So all examples could be:
```
cssFiles : {
    'default/**light**': 'light.css',
    'default/**dark**': 'dark.css',
    'default/*': 'styles.css', // all other app css files.
    'jquery/**.css': 'jquery.css', // catch all jquery css files.
    '*/**.css': 'some_vendors.css', // catch all packages and regex
    '*': 'vendor.css' // A special catch all packages / css files, including default if not specified above.
}
```

**Comment by nchanged** [comment]
Perfect, there is one case 
When there is no `cssFiles` case we need to avoid breaking changes, catch everything and pipe it into `styles.css` like it was. Having `cssFiles` in this case would completely override the default behaviour as in it will be totally up to the user. An alternative would be:
```js
cssFiles : {
    '*': 'styles.css' // equals `css : true`
}
```

Long story short, `css : true` would create `cssFiles` with the config above by default

**Comment by smitt04** [comment]
Ok, I have updated the fork to use the new way.  Everything seems to be working. I am assuming you would like docs and unit tests first before a PR?

**Comment by nchanged** [comment]
Docs would be nice to have in Quantum section, yes. We could write a guide too on how to handle CSS ;-) but that's optional.

Here is a test example 

How to test if a file was created, in our case 

https://github.com/fuse-box/fuse-box/blob/e9f84099b93030ffcea9291e9f86f2388e2b99ca/src/tests/dynamic_imports_test/CodeSplittingFileIntegrity.test.ts#L93-L106

You can take [this](https://github.com/fuse-box/fuse-box/blob/master/src/tests/dynamic_imports_test/CodeSplittingFileIntegrity.test.ts#L66) test case is a  base.

Thank you so much for contributing! ❤️

**Comment by smitt04** [comment]
I will add some tests to `quantum/tests`. So this feature will fix the quantum issue with css code splitting.  What would you like to do about the dev side?  Should we create another issue?  It seems kind of weird to me that we would do something different for dev vs prod though.

**Comment by nchanged** [comment]
Let us have another issue, yup.

**Comment by smitt04** [comment]
I was trying to write tests and it doesn't seem like I can do the same thing as the CodeSplittingFileIntegrity test as the producer only saves js files, I couldn't see a way to get css files created.  So I can try to update the `FuseTestEnv` or I can do the test more like

https://github.com/fuse-box/fuse-box/blob/4587955e4e7815e68dd808478dada04e58792641/src/tests/plugins/CSSPlugin.test.ts#L63-L84

I think the FuseTestEnv should be updated to have css files but I don't even know where to begin on that one.

**Comment by smitt04** [comment]
Yea, I saw that but for code-splitting i thought it would be better to test that the files were created.  I could use web index plugin and test the file names in the `link` tag i guess.

**Comment by nchanged** [comment]
@smitt04 how is going? Do you need any help?

**Comment by smitt04** [comment]
Unfortunately I have been pretty busy at work and haven't had time to work on the tests yet.  If you wanted to write some that would be greatly appreciated.

**Comment by nchanged** [comment]
@smitt04 can you submit a PR to a different branch?

**Comment by smitt04** [comment]
sure can you create the other branch? i cant submit one to a branch that doesnt exist yet.

**Comment by Kompwu** [comment]
Hi, i think we can close it now?, right ?
