### ISSUE TITLE
More complex example

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#120]
Guys, what a fantastic piece of software. Been playing with it for quite some time and the speed and performance is mesmerising. I have been following your docs and been successful to about 50% of stuff I wanted to accomplish. Thanks to your express-seed example I got it all working in express but there is still some thing that could use better explanation. What would be great (possibly extending the express-seed) example is to explain:

- code splitting
- lazy loading

I could not make it work at all. I have been somehow successful with generating vendor bundle, but I did not understand how to use those generated bundles. Running the express server without fuse bit leads to errors in console trying to connect to fuse `WebSocket connection to 'ws://localhost:4446/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`. Thus, I am not sure how to create a production build, disconnected from fuse.

Yet another issue is that even when I generate two bundles, one for app and another for vendor, including both of them in html does not allow to import modules from the other one using just standard import. Please see the example at the bottom of the post.

So, my question would be ... four questions (possible enhancement of docs or the express-seed app)

1. How to split code in several bundles (e.g. vendor, part1, part2) 
2. How to define spilt points for single page application, and lazy loads parts during execution? In webpack it's via require.ensure, or System.import which automatically generates a given bundle
3. How to make this work in the dev environment
4. How to make this work in production? Separate html file maybe?

The Ideal example for React + Typescript + Production Ready
--------------------------

1. React app with one component and one helper class (e.g. Foo.ts) that has it's own dependency (e.g. 'path' such as in another example of yours?)
2. Component with one button that would lazy load the Foo.ts class and its dependencies
3. There would be three generated bundles
     - app bundle
     - vendor bundle (everything from node_modules)
     - foo bundle and foo specific dependencies
4. There would be two configs, 
     - development: running the dev server with 3 non-minified bundles
     - production: running the express server, serving 3 minified bundles

I have already started work on plugin that would automatically add file-hashes to file in index.html file so that changes are always propagated to clients.

With example like this you'd cover about 80% of react production cases.
I hope I do not sound demanding, I will gladly do all this myself and do a PR I just need a push towards the goal.

Thanks for the amazing effort!

Example
----------------

This is as far as I got:

1. fuse config that creates two bundles (yet I cannot use them, since anything that is in app.js cannot require stuff from vendor.js using standard require or import. It seems that react and react-dom are loading, but it blows up on fbjs (`GET http://localhost:3446/fbjs/lib/invariant 404 (Not Found)
v @ app.jsx:31
d @ app.jsx:31
w.require @ app.jsx:31
....
app.jsx:31 fbjs/lib/invariant was not found upon request`)

```js
const fsbx = require('fuse-box');

const fuseBox = fsbx.FuseBox.init({
    homeDir: 'src/',
    sourceMap: {
        bundleReference: 'app.js.map',
        outFile: './dist/app.js.map'
    },
    outFile: './dist/app.js',
    plugins: [
        fsbx.SVGPlugin(),
        fsbx.CSSPlugin(),
        fsbx.TypeScriptHelpers(),
        fsbx.JSONPlugin(),
        fsbx.HTMLPlugin({useDefault: false})
    ]
});

fuseBox.bundle({
    "dist/vendor.js": "+react +react-dom",
});

fuseBox.devServer('>[index.tsx]', {
    port: 4446,
    httpServer: false
});
```

This is index.html page

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>FuseBox with Node Express Example</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
<dic id="root">
</dic>
<script src="vendor.js"></script>
<script src="app.js"></script>
</body>
</html>
```

**Comment by tomitrescak** [comment]
To share my progress I have created a repository: https://github.com/tomitrescak/fuse-box-express-complex.git

What is done and what is needed:

- [x] Use Express
- [x] Use React + Typescript
- [x] Lazy load a module (need confirmation if it's done ok)
- [ ] Split vendor code to separate bundle
- [ ] Separate production build disconnected from fuse

**Comment by nchanged** [comment]
@tomitrescak thanks for such kind words!

1) `devServer` generates a development bundle. Therefore you can't use the same code in production.
You need to generate a different bundle using [this](http://fuse-box.org/#arithmetic-instructions) method. You can add [UglifyJSPlugin](http://fuse-box.org/#uglifyjsplugin) to minify everything.

2) Bundles can be split and re-used. I don't understand why your app.js can't get stuff from `vendor.js`, You import it wrongly, probably.
As for automatic split, we don't have it yet, but let's solve problems gradually.

I will prepare typescript+react+reflux+css seed and split the code. (I have a working example already)

**Comment by tomitrescak** [comment]
Thanks, I will wait for your example! I have a problem that when I create vendor bundle many fbjs errors appear.

**Comment by tomitrescak** [comment]
One more question. The typescript compilation seems to work differently from tsc. 
Tsc compiles my project just fine but fuse-box blows up.

For example, compiling following code:

```
declare global {
  namespace App {
    interface IError {
      error: string | number;
      reason?: string;
      details?: string;
    }
}
```

I get  following error:

```
```

**Comment by nchanged** [comment]
I will add some sample like that, that's very strange ...

**Comment by nchanged** [comment]
I see, i hope you are not mixing .ts and .js!
Make sure you have `index.ts` as an entry point.

**Comment by tomitrescak** [comment]
No, I have ts entry point:

fuseBox.devServer('>client/index.ts', {
    port: 4446,
    httpServer: false
});

**Comment by tomitrescak** [comment]
Ignore that last problem, I have set outDir to "." when testing lazy imports. So, the compilation is ok.

**Comment by tomitrescak** [comment]
I take that back, it blows up on following code:

```
const StarRating = ({codeStars, stepsStars}: IStarRatingProps) => (
  <span>
    { codeStars >= 1 ? <span className={ratingOk}>★</span> : <span className={ratingNone}>☆</span> }
    { codeStars >= 2 ? <span className={ratingOk}>★</span> : <span className={ratingNone}>☆</span> }
    { codeStars >= 3 ? <span className={ratingOk}>★</span> : <span className={ratingNone}>☆</span> }
    { stepsStars >= 1 ? <span className={ratingOkLoc}>★</span> : <span className={ratingNone}>☆</span> }
    { stepsStars >= 2 ? <span className={ratingOkLoc}>★</span> : <span className={ratingNone}>☆</span> }
  </span>
);
```

```
Acorn error: Unexpected token (8:26)
File: /Users/tomi/Downloads/fuse-box-express-seed-master/src/client/modules/core/components/star_rating_view.tsx

6  var StarRating = function (_a) {
7      var codeStars = _a.codeStars, stepsStars = _a.stepsStars;
8      return ({ codeStars:  >= 1 ? className :  = { ratingOk: exports.ratingOk } >  } < /span> : <span className={ratingNone}>☆</span > );
9  };
10  {
11      codeStars >= 2 ? className :  = { ratingOk: exports.ratingOk } > ;
12      /span> : <span className={ratingNone}>☆</span > ;
```

**Comment by nchanged** [comment]
That's related to your `tsconfig.json` it has to be in your homeDir with react enabled.
```
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "moduleResolution": "node",
        "isolatedModules": false,
        "jsx": "react",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "declaration": true,
        "noImplicitAny": false,
        "noImplicitUseStrict": false,
        "removeComments": true,
        "noLib": false,
        "outDir": "build/",
        "noEmitHelpers": true,
        "preserveConstEnums": true,
        "suppressImplicitAnyIndexErrors": true
    },
    "exclude": [],
    "compileOnSave": false,
    "buildOnSave": false,
    "atom": {
        "rewriteTsconfig": false
    }
}
```

**Comment by nchanged** [comment]
Ready!
https://github.com/fuse-box/fuse-box-ts-react-reflux-seed

I think this repo can answer to at least 70% of your questions.

```
npm install
gulp start
```

It creates 2 bundles which interact with each other.  

An express server which serves a test folder running on port `3000`. And HMR socket running on port `5678`

`gulp dist` -> for production


That's a very crude example I will improve it and make it more complex with lazy load later on. Feel free to ask questions, suggest improvements.

**Comment by basarat** [comment]
> That's related to your tsconfig.json it has to be in your homeDir with react enabled.

Alternatively I just point to the tsconfig using the tsconfig option : http://fuse-box.org/#tsconfig

**Comment by tomitrescak** [comment]
I did that, and I have a tsconfig in src folder specified below.
But I can see acorn doing some crazy stuff. This is one of the errors: 

Original code:

```
for (let i = 0; i < board.players.length; i++) {

      let player = board.players[i];
      let cls = this.initPlayer(context, this.debug.runner, player.tile.className, board, player, inputs, i > 0 ? `_${i + 1}` : '');
      context.players.push({ tile: player, instance: cls });
    }
```

Error

```
Acorn error: The keyword 'let' is reserved (137:53)
File: /Users/tomi/Downloads/fuse-box-express-seed-master/src/client/modules/debugger/models/board_validator_model.ts

135      context.loadBoard = (stringBoard: string[][]) => this.loadBoard(stringBoard);
136
137      for (let i = 0; i <board.players.length /> i++) {let} = board.players[i];
138        let cls = this.initPlayer(context, this.debug.runner, player.tile.className, board, player, inputs, i > 0 ? `_${i + 1}` : '');
139        context.players.push({tile} player, instance: cls });
140      }
```

Here is tsconfig

```
{
    "compileOnSave": false,
    "compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "noEmitHelpers": false,
        "emitDecoratorMetadata": true,
        "jsx": "preserve",
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "removeComments": true,
        "preserveConstEnums": true,
        "sourceMap": true,
        "strictNullChecks": false,
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "noUnusedLocals": false,
        "noUnusedParameters": true,
        "skipLibCheck": true,
        "skipDefaultLibCheck": true,
        "experimentalDecorators": true,
        "outDir": "./build",
        "types": [
            "chai",
            "react",
            "jest"
        ],
        "typeRoots": [
            "src/typings/overrides",
            "node_modules/@types"
        ],
        "pretty": true
    },
    "exclude": [
        "node_modules"
    ]
}
```

**Comment by nchanged** [comment]
@tomitrescak you got some problems with typescript there. It's not recognized as a typescript file. Please check the seed

**Comment by nchanged** [comment]
@tomitrescak on top of that, make sure you have NodeJs 6+ installed.

**Comment by tomitrescak** [comment]
I got 7.4.0, tsc behaves as expected, it compiles fine in vs code as well. I will port the code to the seed you created and let you know.

**Comment by nchanged** [comment]
Let me know if you manage to run the seed without errrors.

**Comment by tomitrescak** [comment]
@nchanged thanks for your help! I managed to finally compile my app, the problem was with legacy casting (parts of my code have +4 years).

whenever you use casting such as following, the compiler blows up.

```
const a = <MyType>null;
```

Luckily I ran into it while trying to use ts-loader-light and it was raising the same problem. Maybe it could make its way into troubleshooting part of your docs.

Preliminary it looks AMESOME! My vendor bundle took 1.7 seconds i.s.o. 30+ on webpack ;)

The issue now is with versioning.
E.g. fusebox packages version object-assign@2.0.0, but one of the packages is requiring object-assign@4.1.1

**Comment by nchanged** [comment]
1.7 seconds comparing to 30s is big of a difference!
Try launching it once again, it will take 50ms!:)

Let's investigate what's wrong with it, fuse can resolve conflicting libraries btw, and bundle 2 versions

**Comment by devmondo** [comment]
@tomitrescak  awesome stuff man!

the compiler error is TS one right and not FuseBox one?  
regarding speed, we did not lie when we said 10x faster :)

**Comment by tomitrescak** [comment]
How can I proceed with investigation? Is it possible that the problem is that I separated vendor code from the main app?

**Comment by nchanged** [comment]
Yes, it's possible. Try merging everything into one bundle, and check your dependency tree.

**Comment by tomitrescak** [comment]
I just wanna report back on progress:

1. Yes, the code splitting is not working properly (I kind of get why) as only one version of "object-assign" is packed int vendor bundle
2. When packed into a single file it went mostly ok, apart from following:
   - the __decorate helper does not work properly and needed to be included manually in my root file
   - I had to shim the `tty` package that is used by debug.js that was making problems (not sure how it is handled by webpack)
      ```
      shim : {
            "tty" : { exports : "{ isatty() { return false; } }" }
        },
      ```
   - The CSS files are place correctly into a subfolder but they are not served by the dev server
   - The sourcemaps do not map into node_module files, they show empty file
   
But, the biggest problem I have is that I need to somehow chain the typescript compilation as I need to transform file before compilation (I use jsx-controls <If>, <Choose> ... ) and I have other transforms in place. Do you think this would be a good place for plugin? How could I chain it before typescript compilation?

**Comment by nchanged** [comment]
@tomitrescak we don't have pre-typescript plugins as it is handled internally (No plugin is required to work with typescript). But! I could expose it in the plugin API if needed.

**Comment by nchanged** [comment]
> The CSS files from external parties are directly included in the bundle, and it brings compilation problems ...

Try the  CSSPlugin on them!

**Comment by nchanged** [comment]
> I had to shim the tty package that is used by debug.js that was making problems (not sure how it is handled by webpack)
Could you make a PR, and put your implementation [over here](https://github.com/fuse-box/fuse-box/blob/master/assets/libs/tty/index.js#L4) instead? 

That would be very kind of you.

**Comment by nchanged** [comment]
@tomitrescak would [that](https://github.com/fuse-box/fuse-box/blob/master/src/File.ts#L325) help  you?

**Comment by tomitrescak** [comment]
@nchanged will do that PR tomorrow, now i understand why tty was crashing.
Your solution will definitely work like magic, the only thing is that I don't know how to access context to implement my transformation function. Thanks for all our kind help.

I will also do a PR to your example app to add support for source maps and adding hashes to JavaScript sources.

**Comment by nchanged** [comment]
Thanks! I will introduce "onBeforeTs" method in the plugin API today

**Comment by tomitrescak** [comment]
@nchanged just another report:

With the new version of fusion I was able to cleanly separate vendor code from application code and it works! The last bit is the `onBeforeTs`. Would you be please so kind and post here in case you will have time to implement it? Thanks!

**Comment by nchanged** [comment]
@tomitrescak I will add it to the PluginAPI soon! will keep you posted.

**Comment by nchanged** [comment]
I am closing this now. Let's make a separate issue.

**Comment by nchanged** [comment]
#164
