### ISSUE TITLE
Consider adding TSLint

### ISSUE THREAD

**Issue by smitt04** [fuse-box/fuse-box#1201]
It would help with coding style across contributors. As an example I have noticed an inconsistency with semi-colons, are they required or not.

**Comment by nchanged** [comment]
thanks, that would be great. We have `tslint`already.  (It's been introduced recently) It's just not many things are refactored at the moment.

**Comment by jpike88** [comment]
@smitt04 is this related to your issue?

https://github.com/fuse-box/fuse-box/issues/1211

**Comment by smitt04** [comment]
@jpike88 Not quite, I just wanted a tslint config so that my ide could tell me the proper coding style for this project.  I didn't realize there was a `tslint.json`already when I created this issue.  I thought I checked for one.  I have been pretty sleep deprived as of late, so I probably missed it.
