### ISSUE TITLE
Custom fusebox plugins

### ISSUE THREAD

**Issue by kokujin** [fuse-box/fuse-box#1202]
Can someone point me to a tutorial that shows how to code custom Fusebox plugins? Thanks

**Comment by nchanged** [comment]
There is somewhere, I could try to find later. 
But if you take a look at the simplest plugin [here](https://github.com/fuse-box/fuse-box/blob/master/src/plugins/HTMLplugin.ts) You will understand everything. 

Basically `file.loadContent()`
And then do you stuff in `file.content` ;-)

**Comment by kokujin** [comment]
Thanks @nchanged, but I would need  a bit more. I am looking for something official, a plugin skeleton with an explanation of al parameters and best practices. A test example would be great too.
