### ISSUE TITLE
Fusebox alternative to gulp-inject?

### ISSUE THREAD

**Issue by kokujin** [fuse-box/fuse-box#1203]
Is there a Fusebox alternative to [gulp-inject](https://github.com/klei/gulp-inject)? Thanks

**Comment by jpike88** [comment]
What are you trying to inject? Anything you're trying to stick into an html context is likely something you can bundle using an import statement

**Comment by kokujin** [comment]
Thanks @jpike88

gulp-inject reads the files emitted from your build pipeline and inserts them into a file/template/view of your choice. Actually, a flexible version of the fusebox plugin: WebIndexPlugin

**Comment by jpike88** [comment]
What are you trying to import specifically? You might find it can be handled via an import statement

**Comment by kokujin** [comment]
I am trying to inject CSS and JS assets. For example:
```````
<link rel="stylesheet" href="css/app.css">
```````
```````
 <script src="js/app.js"> </script>
```````
