### ISSUE TITLE
Incorrect error message

### ISSUE THREAD

**Issue by jpike88** [fuse-box/fuse-box#1204]
This error assumes that TypeScript is not installed, and hides whatever error may be firing instead.

https://github.com/fuse-box/fuse-box/blob/e9f84099b93030ffcea9291e9f86f2388e2b99ca/src/core/File.ts#L622

![screen shot 2018-04-16 at 9 16 49 pm](https://user-images.githubusercontent.com/9585787/38814351-8388b3b8-41bb-11e8-9bca-183b7af5cb49.png)

**Comment by jpike88** [comment]
Turns out the error was a malformed tsconfig.json

**Comment by nchanged** [comment]
Hi, we are open for PR, any help is greatly appreciated
