### ISSUE TITLE
Run code from multiple files with Quantum Plugin

### ISSUE THREAD

**Issue by Sala** [fuse-box/fuse-box#1206]
I might be doing something wrong, maybe I'm not doing the config correct, or maybe it's just a bug, but I guess you're the best people to tell me.

Simplified scenario: I have two files: editor.js with just alert('editor'); and main.js with alert('main'); and I want to include both of those files into a page. My fuse config looks like this:
`const fuse = FuseBox.init( {
		homeDir: "inc/assets",
		output: "inc/assets/dist/$name.js",
		plugins: [
			QuantumPlugin({
				bakeApiIntoBundle:true
			})
		]
	} );`

	fuse.bundle( 'main' ).instructions( '> js/main.js' );
	fuse.bundle( 'editor' ).instructions( '> js/editor.js' );`

When I open the page there is only one alert because only in one generated file I have the function to run at the end of the code. 
`(function($fsx){
// default/js/editor.js
$fsx.f[1] = function(){
alert('editor');
}
$fsx.r(1)
})($fsx);`
and 
`(function($fsx){
// default/js/main.js
$fsx.f[0] = function(){
alert('main');
}
})($fsx);`

My question is if it's possible to have the content of both files to run on my page? Should I add something special in the config or it is not currently supported?

P.S. If I remove the Quantum plugin, the files are generated and they execute the code as expected.

Thanks in advance,
Andrei

**Comment by nchanged** [comment]
are u including your scripts to index? do you have WebIndexPlugin? looks like the other scripts isn't loaded

**Comment by Sala** [comment]
I'm manually  loading both of scripts to the page, but as you can see, the content is not executed. No, I'm not using a WebIndexPlugin.

When I looked in the code (QuantumCore.js:151) I got to this:
`entryId = ${this.producer.entryPackageName}/${this.producer.entryPackageFile};`
and after that there is a check (line 166)
`if (fileId === entryId) {  fileAbstraction.setEnryPoint(globalsName);  }`

Even though the entryPackageFile is set for each bundle, when it gets to the Quantum code, it just uses the same last value.

**Comment by nchanged** [comment]
yeah, there could be only one entry point per producer.

**Comment by Sala** [comment]
I agree that there is only one en**t**ry point per producer but there are two instances of producers. the issue that I see is that when trying to create the en**t**ry point, only the last producer is used, so the entryId is always the same.

My question is, am I using a wrong configuration or there's a bug in the package?

**Comment by nchanged** [comment]
```
fuse.bundle( 'main' ).instructions( '> js/main.js' );
fuse.bundle( 'editor' ).instructions( 'js/editor.js' );`
```

It should be like that I think.
I would advise you sticking to one bundle and use dynamic imports instead

```js
await import("./js/editor")
```

When run through Quantum it will create a split file with all dependencies

**Comment by Sala** [comment]
In my scenario I have to use two bundles that work independently, so I can't really use import :(. Is there a way to have multiple bundles configured to work as described?

**Comment by nchanged** [comment]
If you want to have a completely separately bundles, you need to have 2 producers and is in `FuseBox.init`

**Comment by tungd** [comment]
Hi, I'm also hitting this issue today. My opinion is that it should behave as @Sala described, after all like he said that's consistent with Quantum disabled. I also think being consistent in behavior with the FuseBox API is an important point, we really don't want our build to work on development but break on production. 

And the fix is actually quite simple, in https://github.com/fuse-box/fuse-box/blob/master/src/quantum/plugin/QuantumCore.ts#L212, just compute `entryId` per bundle instead of per package:

```typescript
public prepareFiles(bundleAbstraction: BundleAbstraction) {
    // set ids first
    let entryId;

    // if (this.producer.entryPackageFile && this.producer.entryPackageName) {
    //  entryId = `${this.producer.entryPackageName}/${this.producer.entryPackageFile}`;
    // }

    bundleAbstraction.packageAbstractions.forEach(packageAbstraction => {

        entryId = `${this.producer.entryPackageName}/${packageAbstraction.entryFile}` // <---

        packageAbstraction.fileAbstractions.forEach((fileAbstraction, key: string) => {
            ...
        })
    })
}
```

**Comment by nchanged** [comment]
Can u submit a PR?

**Comment by tungd** [comment]
@nchanged sure, here you go #1387
