### ISSUE TITLE
Quantum API - Computed Statement Resolution

### ISSUE THREAD

**Issue by pmonty** [fuse-box/fuse-box#1208]
Have followed this [Quantum - Computed Statement Resolution](https://fuse-box.org/page/quantum-configuration#computed-statement-resolution) and got it copying the image to the .dist folder and the Quantum bundle warning does not appear.

Not to sure what the issue is but as @nchanged mentioned in gitter it appears FuseBox is complaining that the API is not loading.

![image](https://user-images.githubusercontent.com/7111292/38937088-b46663da-4365-11e8-90f3-084e8b47972f.png)

My code (Assets.ts)
```
export function getImageByName(filename: string) {
    return require("../images/" + filename + ".png");
};
```

App.tsx
```
const test = getImageByName("icon-tick.png");
//... then down in render i am just trying to console.log(test);
```

And then here is my [Fuse.ts](https://gist.github.com/pmonty/e6cf5540ad8aa2ae1a34a7eed36c5e57)

I did get a similar setup working with the `quantum_computed_resolve` fuse-box example. Not to sure what the difference is. Both that and my playground that I am testing on are quite simple apps.

Differences obviously can be drawn from looking at my Fuse.ts gist and the fuse.js file in the FuseBox example project.

**Comment by pmonty** [comment]
The issue was icon-tick.png**.png** doe's not exist... silly mistake. Not sure how to delete issues but am closing it now.

**Comment by pmonty** [comment]
Hmm opening as it seems its not fully fixed. Will update shortly.

**Comment by nchanged** [comment]
@pmonty you need to read this section
https://fuse-box.org/page/quantum-configuration#computed-statement-resolution

You are using computed statements, you need mapping ;-)
```
QuantumPlugin({
    api: (core) => {
        core.solveComputed("default/yourfile.js", {
            mapping: "images/*.png",
            fn: (statement, core) =>
                statement.setExpression(`"default/fromRoot/images/" + name + ".html"`)
        });
    }
})
```

**Comment by pmonty** [comment]
Yeh read through it and followed the examples. The issue isn;'t the warning just that the api is not loading saying `it is not a function`.

Really strange, you can see how I have the mapping set up correctly in my gist in the first post. Not sure what the issue might be. It copies the file into the dist folder an everything.

**Comment by pmonty** [comment]
Tested it as is and it worked (dev and production build).

Moment I make changes
- change all extensions/references to .png
- add an image to views folder
- change line to `const first = getHTMLContents("test-img");`
 
Then after those it does work on dev build but the production/dist build that uses quantum breaks with the $fsx.p is not a function error.

**Comment by nchanged** [comment]
Hm, could you reproduce this issue in a repository?

**Comment by pmonty** [comment]
Will check it out tomorrow and let you know how it goes.

**Comment by pmonty** [comment]
Hmm so looks like tree-shaking was the issue and it was removing the following
```
// default/images/EA/images/icontick.png
$fsx.f[29] = function(module,exports){
module.exports = '/assets/7c8a54f-icontick.png';
}
```

So added this and it worked. I guess it will still treeshake atleast but avoid assets.ts related stuff.
```
treeshake: {
    shouldRemove: file => {
        if (file.fuseBoxPath === "Assets.js") {
           return false;
        }
   }
},
```

So hopefully this will be entirely avoidable when dynamic computed import statements are available. Guess treeshaking was just doing it job and causing the issue.
