### ISSUE TITLE
import unsafe option

### ISSUE THREAD

**Issue by jpike88** [fuse-box/fuse-box#1209]
Is there a way to import a JS file, exposing its contents to the globe scope WITHOUT manually specifying it?

e.g. import UNSAFE '../blah.js'

This adds blah.js to a special globally scoped bundle, and executes it as if it was added as a <script> tag directly to the html?

**Comment by nchanged** [comment]
yes, you can import javascript files dynamically as described here
https://fuse-box.org/page/dynamic-import#loading-remote-javascript-file-from-cdn

**Comment by jpike88** [comment]
ah awesome thanks. keep this issue open i'll amend the docs so is a bit clearer

**Comment by jpike88** [comment]
could you assign it to me or do i need to be a collaborator

**Comment by jpike88** [comment]
Ok turns out I'm still a bit of a noob.

I want to use Sparky to concatenate a bunch of .js files, and pipe them through the BabelPlugin at the same time. No documentation or examples of something like this. What would that look like?

**Comment by jpike88** [comment]
This really links back to this issue:

https://github.com/fuse-box/fuse-box/issues/1187

Now I guess I just need to know how to do it in a Sparky/Fusebox like way without resorting too much to a more vanilla method.

**Comment by nchanged** [comment]
Just make a bundle and pipe it to dist. then import with the parent bundle

**Comment by jpike88** [comment]
screw it i'm going all in, i'll use imports properly
