### ISSUE TITLE
Problem building CSS with Sparky task

### ISSUE THREAD

**Issue by kokujin** [fuse-box/fuse-box#1210]
My JS Sparky task works when I use it alone, I have problems when I add a CSS task. 
Can some take a look at my fuse config?

``````
const { FuseBox, QuantumPlugin, UglifyJSPlugin, SassPlugin, CSSPlugin, CSSResourcePlugin, WebIndexPlugin } = require("fuse-box");
const { src, task, exec, context } = require("fuse-box/sparky");
const isProduction = false;

// JS
// ----------------------------------------------------------------------------
task('build-js', () => {
    fuse = FuseBox.init({
        target: 'browser',
        homeDir: "assets/js",
        output: "public/js/$name.js",
        useTypescriptCompiler: true,
        cache: false,
        log: {
            showBundledFiles: true,
            clearTerminalOnBundle: true
        },
        debug: true,
        plugins: [           
            isProduction && QuantumPlugin({
                uglify: true,
                treeshake: true
            })
        ]
    });
    fuse.bundle("app").instructions(">main.js");    
});

// CSS
// ----------------------------------------------------------------------------
task('build-css', () => {
    fuse = FuseBox.init({
        target: 'browser',
        homeDir: "assets/css",
        output: "public/css/$name.js",        
        debug: true,
        plugins: [
            [SassPlugin(), CSSPlugin(), CSSResourcePlugin({
                dist: "dist/css-resources"
            })]
        ]        
    });
    fuse.bundle("app").instructions(">main.js");        
});

// Run on default build
task('default', ['build-js', 'build-css'], () => fuse.run());

``````

**Comment by nchanged** [comment]
I don't understand the point of bundling CSS separately. 
https://fuse-box.org/page/getting-started#start-with-css

Read up there ^. When building production use QuantumPlugin which will generate a CSS file for you. 
https://fuse-box.org/page/quantum-configuration#css


Regarding your config, it won't work, as you need to run `fuse.run()` after each producer. But I would advise you on using Quantum for generating CSS it is also optimized using `clean-css` in the background.

**Comment by kokujin** [comment]
Thanks @nchanged for your post, I could only get both tasks to output Javascript. Can someone send me a link to a fusebox/ Fusebox Sparky config that bundles JS and CSS? I have not been able to find anything on the net. Thanks

**Comment by jpike88** [comment]
Hi @kokujin, it's really simple.

Just import 'blah.css'; in your project, and include the CSSPlugin in the build.

'build-js' then just becomes 'build', its all included in one bundle.

**Comment by kokujin** [comment]
Thanks @jpike88, actually, I would like to create a separate file, "app.css", which contains all the converted SASS and normal CSS files.

**Comment by nchanged** [comment]
@jpike88 actually it's all here:
https://github.com/fuse-box/fuse-box-examples/tree/master/examples/css-resource-plugin-example

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
