### ISSUE TITLE
Test Runner - before/after methods are counted as assertions

### ISSUE THREAD

**Issue by mycompassspins** [fuse-box/fuse-box#1215]
If I've got a test with 1 assertion, a `beforeEach` method, an `afterEach` method and an `after` method, the test runner will show 4 passed when the test is complete. Is this intentional? It threw me before I realized what was happening, when I was seeing all assertions passed but the test fail. Is this intentional, or am I missing something?

This test:

```
export class TestTest
{
	async beforeEach()
	{
		console.log('beforeEach');
	}

	async afterEach()
	{
		console.log('afterEach');
	}

	async after()
	{
		console.log('after');
	}

	'works kinda'()
	{
		should(true).equal(true);
	}
}
```

Produces the following console output:

```
Test test →
beforeEach
      ✓ works kinda
afterEach
after

   ☞ 
    4 passed  (96ms)
```

**Comment by nchanged** [comment]
yes, you can return either a Promise (make it async) or pass `done` function

You async function is resolved in your example

**Comment by mycompassspins** [comment]
@nchanged, thanks for the speedy response! But maybe I was unclear. In my example, there is only *1 assertion*, but the test runner is counting 4. It is including the before/after hooks, even though no assertions are made in those methods. That's how it's supposed to work?

**Comment by nchanged** [comment]
@mycompassspins Oh yeah, that counter is buggy, I see it now. Thanks!

**Comment by nchanged** [comment]
We are using jest now.
