### ISSUE TITLE
Quantum doesn't work: Globals only loading last variable in globals config

### ISSUE THREAD

**Issue by jpike88** [fuse-box/fuse-box#1217]
Using @next, found a weird bug in quantum that prevents my builds from working properly.

My globals config looks like this:

![screen shot 2018-04-24 at 12 04 04 pm](https://user-images.githubusercontent.com/9585787/39167123-9f3b30f2-47b7-11e8-926f-e68371903482.png)

I'm using bakeApiIntoBundle too just FYI.

The end of my app.js looks like this:

![screen shot 2018-04-24 at 12 04 46 pm](https://user-images.githubusercontent.com/9585787/39167135-b245eaca-47b7-11e8-8653-c994657be5fd.png)

If I change the order of the globals config, then the last one will be the only one that is exposed.

Will investigate further, but this is definitely a quantum related bug.

**Comment by jpike88** [comment]
https://github.com/fuse-box/fuse-box/blob/66f06bb358bc3673412fd4b37c19c29dbad83505/src/quantum/plugin/QuantumCore.ts#L225

**Comment by nchanged** [comment]
@jpike88 globals expose whatever yours entry point exposes. So make sure your `index.ts` has
```
export angular ...
export lodash
export blabla
```

**Comment by jpike88** [comment]
No luck. I have this in my app.ts now:

```
export {angular, lodash, PouchDB, tinymce};
```

That doesn't stop the end of app.js looking like this:

```
window['tinymce']=$fsx.r(0)
```

**Comment by jpike88** [comment]
My index.ts imports lodash, then the next import statement is angular-google-maps, which expects a '_' variable on window.

This '_' just never gets a chance to happen, nor is it being passed to window as you can see.

**Comment by nchanged** [comment]
Yes, if you want to expose every single variable in your entry point, you need to add `*`

**Comment by jpike88** [comment]
My problem is that my entry point imports like so:

import _ from 'lodash';
import someThingThatNeedsLodash from 'anotherLibrary'

Even if lodash is to be exported on the global scope, the entry point fails to initialise because global variables aren't being hoisted quickly enough, and I get a '_ is not defined' error.

And should my globals object now look like this?

```
        {
            angular: 'angular',
            'lodash': '_',
            'pouchdb-browser': 'PouchDB',
            tinymce: 'tinymce',
            'noIdeaWhatGoesHere': '*'
        }
```

Quantum only selects the last value in that object, and even ignores the key. This still seems to be a bug or design flaw.

**Comment by jpike88** [comment]
Found a workaround...

**Comment by jpike88** [comment]
Actually this isn't good enough, I'd like to see if we can actually resolve this.

That workaround was downgrading the problematic module so it figured out how to co-exist... or something.

If Quantum only cares about the last _value_ in a key/value map, that doesn't make a lot of sense. Why is globals an object, and why does it work one way with Quantum enabled and another without?

This works on development:

```
{
            angular: 'angular',
            'lodash': '_',
            'pouchdb-browser': 'PouchDB',
            tinymce: 'tinymce'       
}
```

But I have to use this on production for it to work.

```
{
            thisMakesNoSense: '*'
}
```

I don't get it.

**Comment by nchanged** [comment]
`globals : {default : "*"}`

```
export * as _ from 'lodash';
import * as ngmaps from 'angular-google-maps';
import * as foo from 'pouchdb-browser';
import * as bar from 'pouchdb-upsert';
```
