### ISSUE TITLE
Run ReplacePlugin before everything.

### ISSUE THREAD

**Issue by DrecDroid** [fuse-box/fuse-box#1219]
Hi, is there a way to run ReplacePlugin before Typescript? I have this use case that is not for production:

I want to test some VueComponents alone so I have created a `demo` task and a `demo.ts` file. This demo.ts looks like this:

```
import Vue from "vue";

import DemoComponent from "replacethis";

new Vue({
  render: DemoComponent
}).$mount("#app");
```

and the `demo task` something like this: 

```
task('demo', () => {
  let componentPath = process.argv[3]

  let fuse = FuseBox.init({    
    target: 'browser@es6',
    homeDir: 'src/',
    output: 'build/$name.js',
    plugins: [
      ReplacePlugin({
        "replacethis": componentPath,
      }),
      VueComponentPlugin(),
      WebIndexPlugin({
        template: 'src/demo.html'
      })
    ]
  })
    
  fuse.dev()

  const app = fuse.bundle('app')
  app.watch();
  app.hmr();
  app.instructions(`>demo.ts`);  
  fuse.run()
})
```

The problem is that the plugin replaces the resulting js file after typescript compilation, so it doesn't work.
I've seen that in the many places in the github bugtracker, that you are discouraging the use of ReplacePlugin in favor of EnvPlugin with QuantumPlugin. But I don't want this for production and using EnvPlugin means I have to do dynamic importing, thing I don't have some much clue in the documentation.

Thanks in advance.

**Comment by nchanged** [comment]
@DrecDroid 
You can achieve that by creating a custom plugin. Here is a micro example

```
const myTypescriptPlugin = {
	test : "*.ts",
	onTypescriptTransform: (file) => {
   	 file.contents = file.contents.replace("a", "b")
    }

}
plugins : [
   myTypescriptPlugin
]
```

**Comment by DrecDroid** [comment]
Thanks, I'll try that.

**Comment by nchanged** [comment]
This has been all fixed in `v4`. Please upgrade to the [major version](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)
