### ISSUE TITLE
Quantum removes "process".

### ISSUE THREAD

**Issue by ypopovych** [fuse-box/fuse-box#1220]
My app works fine in the dev mode but stops working after Quantum.

Browser console shows this error `Uncaught ReferenceError: process is not defined`

It can't find `process` into one of the vendor libraries. Seems as Quantum removes it from the bundle (or changes loading order, so its `process` module isn't loaded yet)

My Quantum config is:
```js
QuantumPlugin({
  bakeApiIntoBundle: 'vendor',
  uglify: {
    es6: true
  },
  treeshake: true,
  css: true,
  api: (core) => {
    core.solveComputed("bn.js/lib/bn.js");
    core.solveComputed("eth-lib/lib/bytes.js");
  }
})
```

How this can be fixed?

Thanks,
Yehor

**Comment by nchanged** [comment]
@ypopovych it's hard to tell without an example.

Could you make one? Or copy paste the offending line from the fusebox' output.

**Comment by ypopovych** [comment]
Disabled uglifying.

Exception inside if line.
```js
// process-nextick-args/index.js
$fsx.f[474] = function(module,exports){
if (!process.version || process.version.indexOf('v0.') === 0 || process.version.indexOf('v1.') === 0 && process.version.indexOf('v1.8.') !== 0) {
    module.exports = { nextTick: nextTick };
} else {
    module.exports = process;
}
function nextTick(fn, arg1, arg2, arg3) {
    if (typeof fn !== 'function') {
        throw new TypeError('"callback" argument must be a function');
    }
    var len = arguments.length;
    var args, i;
    switch (len) {
    case 0:
    case 1:
        return process.nextTick(fn);
    case 2:
        return process.nextTick(function afterTickOne() {
            fn.call(null, arg1);
        });
    case 3:
        return process.nextTick(function afterTickTwo() {
            fn.call(null, arg1, arg2);
        });
    case 4:
        return process.nextTick(function afterTickThree() {
            fn.call(null, arg1, arg2, arg3);
        });
    default:
        args = new Array(len - 1);
        i = 0;
        while (i < args.length) {
            args[i++] = arguments[i];
        }
        return process.nextTick(function afterTick() {
            fn.apply(null, args);
        });
    }
}
```

**Comment by ypopovych** [comment]
This module imported by readable-stream module, which replaces FuseBox built-in stream module. Maybe problem somewhere there

**Comment by ypopovych** [comment]
Added workaround into `stream` module.
Right now it has this content:
```js
if (FuseBox.isServer) {
  module.exports = global.require('stream');
} else {
  window.process = require('./browser');
  module.exports = require('readable-stream');
}
```
Where browser.js is a file, copied from process library. It works this way. How can I fix it in the right way? Can I force inject FuseBox "process" module (if I try to require process there, it will crash Quantum)

**Comment by nchanged** [comment]
How about that
```
QuantumPlugin({
    replaceProcessEnv : true
})
```

**Comment by ypopovych** [comment]
It doesn't help :(

**Comment by nchanged** [comment]
@ypopovych we might need to replace that on Quantum level.
Will it work If you replace `process.version` with `""` (empty string) ? 

As in

```
if (!"" || "".indexOf('v0.') === 0 || "".indexOf('v1.') === 0 && process.version.indexOf('v1.8.') !== 0) {
    module.exports = { nextTick: nextTick };
} else {
    module.exports = process;
}
```

**Comment by ypopovych** [comment]
This works for now (maybe will lead to other bugs, can't find any now).
```js
if (FuseBox.isServer) {
  module.exports = global.require('stream');
} else {
  window.process = { version: "" };
  module.exports = require('readable-stream');
}
```

**Comment by nchanged** [comment]
Define it in window for now, I will have a solution to this soon enough

**Comment by misantronic** [comment]
I found the problem with my build.
I destructured `process.env` like

`const { MY_VAR } = process.env`

This causes `process.env` to be removed.

**Comment by MaxSvargal** [comment]
The same problem at now. Any news?

**Comment by nchanged** [comment]
Which variable is missing now ?

**Comment by DaveO-Home** [comment]
I have this problem with, new release of CanJS 5,  ```process.call```
config;
```
QuantumPlugin({
            api: (core) => {
                core.solveComputed("moment/moment.js");
            },
            manifest: false,
            replaceProcessEnv: false,
            processPolyfill: true,
            target: "browser",
            uglify: false,
            treeshake: false
```l

**Comment by nchanged** [comment]
@DaveO-Home will defining `window.process = { call : function(){}}` help? 
I definitely need to replace more of these variables.

**Comment by DaveO-Home** [comment]
@nchanged  the function is a bit complicated so redefining would be difficult.  Does Quantum ignore if window is coded?  The function is actually used with at least stache templates.

**Comment by nchanged** [comment]
@DaveO-Home I believe you need to add it to your `index.html`
And implement as you want

**Comment by DaveO-Home** [comment]
@nchanged 
It looks like Quantum is changing any "process" parameter in a function signature to "undefined".  This works fine in most cases, however canjs has a method the includes a closure and the "process" name is not modified for the closure.
```
...
section.startSection(renderer);
...
startSection: function (undefined) {
        var newSection = new HTMLSection(undefined);
        this.last().add(newSection.targetCallback);
        this.stack.push(newSection);
    },
...

var HTMLSection = function (undefined) {    // <==== this originally was process
    this.data = 'targetData';
    this.targetData = [];
    this.targetStack = [];
    var self = this;
    this.targetCallback = function (scope, sectionNode) {
        process.call(this, scope, sectionNode, self.compiled.hydrate.bind(self.compiled), self.inverseCompiled && self.inverseCompiled.hydrate.bind(self.inverseCompiled));
    };
```
App fails with process undefined.....

**Comment by nchanged** [comment]
@DaveO-Home and what does it exactly `process.call` do?

**Comment by DaveO-Home** [comment]
@nchanged HTMLSection is part of the helpers module that renders templates.  The maintainer just used "process" as an arbitrary name in the function signature. It is actually an object named "renderer" instantiated in the can-stache module. I did suggested that maybe they could rename it to say; "rendererProcess". But as shown above, Quantum does corrupt the code.

**Comment by nchanged** [comment]
Oh I see now, I though it was fixed, apparently not in all cases

**Comment by DaveO-Home** [comment]
@nchanged - still having this issue with 3.7.0....

**Comment by nchanged** [comment]
@DaveO-Home Hey, I will make a fix in v4 which won't remove the process from the build. Too many complications and issue with it.

**Comment by denniskoenig** [comment]
Got some help in the Slack channel, as a workaround you can use the ReplacePlugin().
I had a problem that `if (process.platform === 'win32')` caused `ReferenceError: process is not defined`.

As example if someone else has the problem:
```
ReplacePlugin({
  "process.platform": JSON.stringify(process.platform)
}),
```

**Comment by myxit** [comment]
Sorry for having noise in the ticket, found this thread when tried to fix using react-markdown component in our fuse-box setup project.
Workaround:
```
FuseBox.init({
    shim: {
          jquery: {
          source: "process-shim.js",
          exports: "process",
          },
      },
...

/// in the process-shim.js
window.process = {
  cwd: function() { return '' }
}
```
