### ISSUE TITLE
mobx@4.2 triggers "Cannot redefine property: default" error

### ISSUE THREAD

**Issue by troynt** [fuse-box/fuse-box#1224]
Hello,

I'm not sure if this is issue with mobx library or Fusebox.

I found that mobx-react@5 triggers "Cannot redefine property: default" error in browser console.
Previous versions of mobx-react work fine.

Example Repo: https://github.com/troynt/fuse-box-antd
Start using ```npm run watch```

Observe errors in console.

Errors disappear when mobx-react ```@observer``` decorator is removed. 
https://github.com/troynt/fuse-box-antd/blob/master/src/client/containers/App.tsx#L8

Mobx addition can be found in commit
https://github.com/troynt/fuse-box-antd/commit/2f2bfe6cebb70123d67997a97b7ecddd4443796e

Mobx code triggering error
https://github.com/mobxjs/mobx/blob/d17e73cba664842048008cefbbd2243a6db1af30/src/mobx.ts#L143-L161

Thanks,

Troy

**Comment by nchanged** [comment]
thanks Troy, 
I will take a look in the evening, in the meantime, it would help if you took a look at this code:

https://github.com/fuse-box/fuse-box/blob/4afb220c641326fd99a7145e4c8cf5fbffc782b2/modules/fuse-box-responsive-api/index.js#L11-L14

I assume you are using `allowSyntheticDefaultImports` there might be a bug there.

**Comment by troynt** [comment]
Ok, so tracked it down to Mobx.
https://github.com/mobxjs/mobx/blob/d17e73cba664842048008cefbbd2243a6db1af30/src/mobx.ts#L143-L161

Still not sure where the fix should be though.
