### ISSUE TITLE
Globals/Shim for accessing exports of a global variable

### ISSUE THREAD

**Issue by jglover** [fuse-box/fuse-box#1227]
Hi, just looking for some advice re: globals.  
I have a private module which has a few exports, which is on window under a variable name (I can't change this). Essentially `window.externalModules.*` need to map to `window.*`  
In webpack the following would work:  
```
externals: {
    exportOne: 'externalModules.exportOne',
    exportTwo: 'externalModules.exportTwo',
    blah: 'externalModules.blah'
},
```
The docs seem to suggest this can be done, but despite my efforts with dot syntax, array syntax, and setting handlers or wildcard as per the following I don't seem to be able to get it to work. Another point of note is the module I'm referring too doesn't exist in the node_modules directory in the same directory as `homeDir` or `fuse.js` but a node_modules directory one directory down. The docs I'm referring to are:
>  You can also expose your package's exports to window or exports.
> ```// assuming mySuperLib exports a "handler" and "logger" property
> 
> FuseBox.init({
>     // exposes window.superHandler
>     globals: { "mySuperLib": { "handler": "superHandler"} },
> 
>     // OR
>     // exposes window.handler and window.logger
>     globals: { "mySuperLib": "*" },
> })```
  
what I have currently is:
```
globals: {
    "@moduleName/subName": "*",
```
Which contains an index.js with the exports.

Much appreciate any advice on this one.

**Comment by jpike88** [comment]
Can you post your actual fuse.js?

**Comment by nchanged** [comment]
@jglover Hi
The easiest way to make it work is to expose you entry point instead.

index.js
```
export * as foobar from "@moduleName/subName"
```


```
globals: { "default": "*" }
```

Then `window.fooobar` should contain it all.

**Comment by jglover** [comment]
Thanks all
@jpike88 there's nothing special about it, literally just started and I'm trying to get an initial bundle and globals working correctly.

@nchanged  that would be ideal but I can't change index.js, it's transpiled from another language to js. They're already exported to a variable on window. However `@moduleName/subName/index.js` does have the four exports I need within it. In theory I could go:
```
globals: {
  "@moduleName/subName": { "handler": "exportOne"}
}
```
But I get an error that `module @moduleName/undefined` could not be found at runtime

**Comment by nchanged** [comment]
Can you reproduce it?

**Comment by jglover** [comment]
Apologies for the slow reply, now I'm getting  
`Uncaught Package not found @moduleName/subName    zen-observable@0.6.1:513`
in the Chrome console.  
I have verified that the module does exist in the `node_modules` adjacent to the fuse.js and there's a valid index.js under `./node_modules/@moduleName/subName/index.js`

**Comment by Kompwu** [comment]
@jglover Hi, It' d be easier to help you if we had a chunk of code at least. :wink:

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
