### ISSUE TITLE
Optimizing Quantum+uglify memory usage

### ISSUE THREAD

**Issue by jpike88** [fuse-box/fuse-box#1230]
Quantum eats up a buttload of memory > 1gb just to calculate abstractions etc etc... final package is about 10mb

Then if I want to uglify, memory just keeps climbing from there. On a 4GB laptop (or build server) this can create some issues

I have to run the node process with --max-old-space-size=8192 just so it doesn't take forever, trying to be nice with memory.

Is it possible or a good idea, you think to seperate Quantum into a seperate process, and then kill that process when it's done? Or is it better to ensure Quantum is given proper memory isolation internally so garbage collector can wipe hanging memory?

**Comment by nchanged** [comment]
I believe we can do that.
Once fuse has finished bunding, Quantum kicks in, And it requires the same scope. For example `sourceMaps` are taken from the original flow. Therefore I don't think it will be that easy to create a separate process unless we really look into storing some information available at `dev` time and sharing to another process once the first one has finished.

**Comment by Kompwu** [comment]
Hi, maybe by zero-ing `Quantum` instance once jobs are done.
It seems easy to do and would be a super simple solution to the problem.
What do you think?

**Comment by Kompwu** [comment]
@jpike88 Knock knock ... ?

**Comment by nchanged** [comment]
@Kompwu it's far away from a simple solution, and it's not more complicated than `zero-ing` it down, because javascript doesn't work that way.

**Comment by jpike88** [comment]
Yeah zeroing quantum isn’t much use because firstly you can’t guarantee that the JS runtime will clean it up, secondly, there are too many references made to easily detach it in a way that is memory safe. That’s why a seperate process at probably the best bet, as Quantum is doing a whole lot of stuff...

**Comment by Kompwu** [comment]
Oh, okay.
