### ISSUE TITLE
Quantum doesn't generate sourcemaps

### ISSUE THREAD

**Issue by jpike88** [fuse-box/fuse-box#1237]
This is my fuse.js below...

I can't see any sourcemaps generated in the target directory. What am I doing wrong?

```
const fuse = FuseBox.init({
        homeDir: srcDir + '/components',
        target: (isProduction ? 'browser@es5' : 'browser@ESNext'),
        output: stagingDir + (isProduction ? "/$name.min.js" : "/$name.js"),
        allowSyntheticDefaultImports: true,
        sourceMaps: { inline: false },
        hash: isProduction,
        tsConfig: (isProduction ? 'src/tsconfig-production.json' : 'src/tsconfig.json'),
        useTypescriptCompiler: true,
        package: {
            name: "default"
        },
        globals: {
            angular: 'angular',
            'lodash': '_',
            'pouchdb-browser': 'PouchDB',
            tinymce: 'tinymce'
        },
        plugins: [
            isProduction && BabelPlugin({
                extensions: [".ts"],
                config: {
                    sourceMaps: true,
                    "plugins": [["angularjs-annotate", {}]]
                },
            }),
            [CSSResourcePlugin({ inline: true }), CSSPlugin()],
            WebIndexPlugin({
                template: srcDir + "/index.html",
                path: '.'
            }),
            NgTemplatePlugin(),
            isProduction && QuantumPlugin({
                bakeApiIntoBundle: 'app',
                processPolyfill: true,
                uglify: true
            })
        ]
    })
```

**Comment by nchanged** [comment]
@jpike88 It was never supposed to generate SourceMaps, Quantum doesn't support them yet

**Comment by nchanged** [comment]
@jpike88 no source maps, no workaround, Quantum does crazy amount of modifications, it would have been OK, if escodegen didn't reformat the code when transpiling back. There is a solution, (I was looking at it back in the days the one that was merging the original source maps with the new ones)

**Comment by jpike88** [comment]
This isn't possible to leverage?

https://github.com/estools/escodegen/wiki/Source-Map-Usage

**Comment by jpike88** [comment]
And how are you currently handling error reporting in production environments?

**Comment by nchanged** [comment]
@jpike88 That's a good question, most people don't need sourcemaps for production, I am not saying that this issue hasn't been raised already.

I can create a test branch, where we could test it.

**Comment by nchanged** [comment]
@jpike88 let's do it this week, let's hack, I think it's possible ;-)

**Comment by nchanged** [comment]
#1275

**Comment by misantronic** [comment]
just want to let you know that I also need this for error-reporting.
looking forward to a solution.

**Comment by nchanged** [comment]
#1375
