### ISSUE TITLE
TypeError: selectorParser(...).processSync is not a function

### ISSUE THREAD

**Issue by ujjwalguptaofficial** [fuse-box/fuse-box#1238]
I am getting this issue, when building the code.

![image](https://user-images.githubusercontent.com/10938615/39407424-91e6894e-4be3-11e8-93df-9a937e738c67.png)

Here is repo link - https://github.com/ujjwalguptaofficial/idbstudio

**Comment by nchanged** [comment]
Could it be related to PostCSS version?

**Comment by ujjwalguptaofficial** [comment]
not sure, but as far as I see it seems.

**Comment by Kompwu** [comment]
@ujjwalguptaofficial Hi, can you try to upgrade dependencies ?

**Comment by ujjwalguptaofficial** [comment]
updating 'vue-loader' worked.

Thanks.
