### ISSUE TITLE
Fusebox Cache Missing React Component

### ISSUE THREAD

**Issue by troynt** [fuse-box/fuse-box#1240]
# Observations

##  Observation 1
With cache enabled, first time bundling gets console warning
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

If I then comment out any line in file, to blow away cache for the file, the second time bundling no error.
I can then uncomment the line and I still observe no bundling error.

##  Observation 2
With cache disabled, bundling does not produce error.

# TODO

- [ ] create test repo

**Comment by troynt** [comment]
I'm closing this issue as I have been unable to reproduce the issue in a sample project.
Will reopen if I can consistently reproduce it.

**Comment by nchanged** [comment]
@troynt does it happen in a cloud environment (docker containers)? 

Can you try this:

```
fuse.run({chokidar : {awaitWriteFinish : true}});
```

**Comment by troynt** [comment]
I'm experiencing this issue just running on the host machine ( not developing on docker ).

When I use docker for my production build I do not take advantage of Fusebox cache, so I haven't seen this issue there either.
