### ISSUE TITLE
Compile Typescript with babel

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#1243]
Typescript support came to Babel 7. Do you consider a possibility to choose typescript compiler? Using Babel only solves quite a lot of issues.

**Comment by Kompwu** [comment]
I think it'll be useless.
Babel isn't very fast compared to the TypeScript transpiler.

**Comment by tomitrescak** [comment]
What if I do not care about the speed of the compilation, rather the robustness of the babel infrastructure?

**Comment by Kompwu** [comment]
@tomitrescak FuseBox care.
But, you can make a plugin :wink:

**Comment by Kompwu** [comment]
@tomitrescak `transform()` is only executed once.
You should try overloading the compiler.

**Comment by nchanged** [comment]
@tomitrescak You need to take a look at `File.ts` all transpilation happens there!

**Comment by tomitrescak** [comment]
I can see that u also bundle js with typescript. Rewriting this to Babel would be a gargantuan effort with meek benefits. I’ll check how much performance suffers using the Babel plugin, but knowing your caching system it will be marginal.
