### ISSUE TITLE
Asynchronous loading of external resources with import(...)

### ISSUE THREAD

**Issue by Kompwu** [fuse-box/fuse-box#1245]
I've tried that way:
```js
import("https://fonts.googleapis.com/css?family=Roboto:100,300,400")
```
But it just doesn't work. :sos:

**Comment by nchanged** [comment]
I think it's unsupported, and I don't think it will be. Since the `import` doesn't really know what to do with that path (and not extensions are specified)

We can't add any additional options as it doesn't align with the standard. You gotta use some other script to do that.
