### ISSUE TITLE
404 error on refresh

### ISSUE THREAD

**Issue by pmonty** [fuse-box/fuse-box#1248]
So my app is using react-router and could possibly be how we are doing things or could be fusebox settings. Webpack version refreshes fine on any screen if you refresh. But final major issue I noticed now is when I refresh the page in the fusebox build I get a blank screen with message `Cannot GET /portal`

![image](https://user-images.githubusercontent.com/7111292/39557146-d4244b7e-4ec8-11e8-9004-8e9243368795.png)

Not sure why... the console is blank and nothing in the network tab either. To get back I need to remove `/portal` and hit up `localhost:3000` and it will take me back to the start.

My [fuse.ts is here](https://gist.github.com/pmonty/2c043825759de87f58e37d7be366a4a6) 

I noticed some stuff in regards to express, but am a little confused as I have two bundles. Hopefully my project isn't to complex for this as I have `/portal/innercontainer` not just `/portal`

**Comment by nchanged** [comment]
That's a normal behavior, please read up on development section how to configure the dev server.you can also search in the issues,  there are many similar.

I will close this one for now, as it's been answered at least 5 times

**Comment by pmonty** [comment]
Have updated [my fuse.ts](https://gist.github.com/pmonty/2c043825759de87f58e37d7be366a4a6) I followed along to the example and it is working though my images aren't loading again. Getting the placeholder icon instead and the alt-text instead. 

Also getting the following and my vendor.js.map no longer builds
![image](https://user-images.githubusercontent.com/7111292/39563150-5a0da7b6-4ef2-11e8-8669-9ec73438cc03.png)

**Comment by nchanged** [comment]
https://github.com/fuse-box/fuse-box-examples/blob/bcc31dada29863fbef091f4ac57cd83fa2ab393b/examples/react-code-splitting/fuse.js#L43-L45

https://fuse-box.org/page/css-resource-plugin#options

![screenshot 2018-05-03 09 00 07](https://user-images.githubusercontent.com/1629088/39563419-6583c59a-4eb0-11e8-8510-0d110a39a084.png)

**Comment by pmonty** [comment]
@nchanged i am using inline and the images are definitely in the assets folder and the src attribute on the img tag is correct.

**Comment by nchanged** [comment]
https://fuse-box.org/page/web-index-plugin#options

@pmonty everything is the doc 😢 😢 😢 
use `path` option

**Comment by nchanged** [comment]
That means that the browser can't fetch your files

**Comment by nchanged** [comment]
https://gist.github.com/pmonty/2c043825759de87f58e37d7be366a4a6#file-fuse-ts-L108

remove `bundles` from there. Because you are having `/bundles/bundles`.

**Comment by pmonty** [comment]
```createBundle(fuse) {
        const app = fuse.bundle("static/app");
        app.splitConfig({ dest: "static" })
        if (!this.isProduction) {
            app.watch()
            app.hmr()
        }
        app.instructions(">app.tsx");
        return app;
    }```
that is the example code it has it aswell. And the code I had with the bundle there is correct it puts it in bundles/app.js

**Comment by nchanged** [comment]
@pmonty react routing solve here
https://github.com/fuse-box/fuse-box-examples/tree/master/examples/react-code-splitting

**Comment by pmonty** [comment]
Nah followed word for word, even used static as a test and nothing. Without the `path` in webindexplugin it loads up atleast. Just the images are missing though. Not sure how to make them appear since they are in the assets folders in my dist folder. Express settings maybe?

**Comment by nchanged** [comment]
either that, or tweak your paths

**Comment by pmonty** [comment]
```
    context.fuse.dev({ open: true, port: 3000 }, server => {
        const dist = path.join(__dirname, "dist");
        const app = server.httpServer.app;
        app.use("/bundles/", express.static(path.join(dist, 'bundles')));
        app.get("*", function(req, res) {
            res.sendFile(path.join(dist, "index.html"));
        });
        app.use("/assets/", express.static(path.join(dist, 'assets')));        
        app.get("*", function(req, res) {
            res.sendFile(path.join(dist, `assets/${req.params.id}`));
        });
    });
```

Tried that but nothing. And still getting the Devtools failed to parse sourcemap warnings. Those could possibly be the issue for the images missing?

**Comment by nchanged** [comment]
you don't need that:
```
app.get("assets/", function(req, res) {
            res.sendFile(path.join(dist, `assets/${req.params.id}`));
        });
```

**Comment by pmonty** [comment]
Will close for now as it seems to have worked and still works when I remove what you said I don't need :)
