### ISSUE TITLE
Support for Vue components?

### ISSUE THREAD

**Issue by bovisp** [fuse-box/fuse-box#125]
I just started using Fuse Box this morning and I absolutely love it!

I use Vuejs in my projects a lot and can get a basic example working easily enough. Is it possible to use separate .vue files for each of my components and then import them through index.js like so?

```
Vue.component('example', require('./components/Example.vue'));

```

**Comment by bovisp** [comment]
Just a slight clarification. What I am looking for is a way to load single-file Vue components that look like this:

```
<template>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Example Component</div>

                    <div class="panel-body">
                        I'm an example component!
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        mounted() {
            console.log('Component mounted.')
        }
    }
</script>

<style type="sass">
$color = blue

body
    background-color: $color
</style>
```

The renderer should also pickup the `type` attribute from the style tag and apply the appropriate css processor (in this case `node-sass`).

**Comment by leon-andria** [comment]
Does this help you ? https://github.com/fuse-box/fuse-box-vue-seed.
Precisely with import in https://github.com/fuse-box/fuse-box-vue-seed/blob/master/src/main.ts#L2

**Comment by nchanged** [comment]
@bovisp Welcome to FuseBox!

You can use [wildcard imports](http://fuse-box.org/#wildcard-import) and register them from a folder. 
This is what you will get:
```
{ "batch/a.js" : {}, "batch/b.js" : {} }
```

It might help you making it more magical.
On top of that, we will make an official Vue compiler plugin soon.

**Comment by bovisp** [comment]
@nchanged. Thanks for the response. Yeah. Will use wildcard imports for now and will wait on the vue compiler.

Love the fuse-box speed. Webpack  runs a little slow on my 10 year old MacBook Pro, but fusebox just hums along. Keep up the great work.

Paul

**Comment by smitt04** [comment]
@nchanged is there an issue or project to watch for vue.js compiler? I am waiting for that before i can try out fuse-box.

**Comment by nchanged** [comment]
We have a primitive version of it, let us test a bit. You can watch this issue.

**Comment by rottmann** [comment]
Is there a short example on how to use VuePlugin?

i tried:

bundle
```
let app = fuse.bundle('app')
  .instructions(`> index.ts`)
  .plugin(VuePlugin())
  .plugin(TypeScriptHelpers())
```

index.ts
```
import Vue from 'vue'
import App from './views/AppView.vue'

new Vue({
  el: '#app',
  render: h => h(App),
})
```

output
```
{ message: 'File contents for /home/rottmann/git/ivs/app/src/views/AppView.vue were not loaded. Missing a plugin?' }
```

when i remove `.vue` form the filename i got this error in browser console:
```
./views/AppView not found on request
```

**Comment by marshallswain** [comment]
For what it's worth, I created a `.vue` plugin for StealJS.  I haven't tried creating a plugin with FuseBox, yet.  But if it helps anybody to look at the code, it's here: https://github.com/icanjs/steal-vue/blob/master/steal-vue.js

**Comment by nchanged** [comment]
Great! thanks!

**Comment by rottmann** [comment]
Found the problems, why my compile script not work:
1. Missing "vue-teamplate-compiler" plugin (not see it, cause of missing details in error message)
2. Scope problem with let/var view https://github.com/fuse-box/fuse-box/pull/462

**Comment by Sirikon** [comment]
Was trying to get FuseBox working with .vue files... couldn't at start, but could make it work making a modification to the resulting .js file.

```ts
// index.ts
'use strict'

import * as Vue from 'vue/dist/vue.js'
import * as App from './components/App.vue'

new Vue({
    el: '#app',
    render: h => h(App)
})

```

```html
<!-- components/App.vue -->
<template>
    <div>
        {{ msg }}
    </div>
</template>

<script>

    export default {
        name: 'app',
        data () {
            return {
                msg: 'Welcome to Your Vue.js App'
            }
        }
    }

</script>

```

```js
// fuse.js
'use strict'

const { FuseBox, VuePlugin } = require('fuse-box')

const fsbx = FuseBox.init({
    homeDir: './src',
    outFile: 'dist/app.js',
    plugins: [
        VuePlugin()
    ]
})

fsbx.bundle('>index.ts')

```

The result  component's code fragment looks like this:

```js
var View = require('vue/dist/vue.js');
var _p = {};
var _v = function(exports){"use strict";
exports.__esModule = true;
exports["default"] = {
    name: 'app',
    data: function () {
        return {
            msg: 'Welcome to Your Vue.js App'
        };
    }
};
};
_p.template = "\n<div>\n    {{ msg }}\n</div>\n";
let _e = {}; _v(_e); _p = Object.assign(_e.default, _p)
module.exports ={render : function(el){_p.el = el; return new View(_p)}}
```

It didn't worked, __but__, If I change the last line manually like this:

```js
// ...
_p.template = "\n<div>\n    {{ msg }}\n</div>\n";
let _e = {}; _v(_e); _p = Object.assign(_e.default, _p)
//module.exports ={render : function(el){_p.el = el; return new View(_p)}}
module.exports =_p
```

It works.

This change should be done here, right?: [VuePlugin.t#55](https://github.com/fuse-box/fuse-box/blob/master/src/plugins/VuePlugin.ts#L55)

**Comment by nchanged** [comment]
@Sirikon that's right, if you propose as change, please do it on 2.0 branch.

That's the latest documentation fuse-box.org:3333

**Comment by Sirikon** [comment]
@nchanged Was trying to get working the vue template compilation, but found out that Vue used "with" statement, wich isn't allowed in strict mode, and that's something that acorn checks. (Maybe that's why the 'parsed' variable is commented).

Is there any conversation about this? I'm investigating work-arounds, but can't find any previous conversation about this here.

**Comment by nchanged** [comment]
@Sirikon I am not sure about that

**Comment by eddow** [comment]
What I could notice was that the normalization of the file is a bit complex.
Getting inspiration from vue-loader (and its normalization function) we can see that
- we need to apply the built renderer to the object or its options if it is a function
- the scopeID must be managed in case of scoped styles
- There is style injection
- special care has to be taken or ssr

Basically, it might become interesting to write a helper function in/beside VuePluginClass and call it from the generated code.

Inspiration: https://github.com/vuejs/vue-loader/blob/master/lib/component-normalizer.js

**Comment by eddow** [comment]
this is already helping (I declare my components with classes and typescript decorators) but still doesn't allow styles
```
var _p = {};
var _v = function(exports){
	${jsTranspiled.outputText}
};
_p.render = ` + toFunction(compiled.render) + `
_p.staticRenderFns = [ ` + compiled.staticRenderFns.map(toFunction).join(',') + ` ];
var _e = {}; _v(_e); _e = _e.default; 
Object.assign('function'=== typeof _e ? _e.options : _e, _p);
module.exports =_e
```

**Comment by TombolaShepless** [comment]
@bovisp @eddow #832

**Comment by devmondo** [comment]
The new release https://github.com/fuse-box/fuse-box/releases/tag/v2.3.1 is out with awesome Vue support it should fix this.

will close this, for now, let us know otherwise :)
