### ISSUE TITLE
Quantum splitConfig resolution when app is hosted in a sub-folder.

### ISSUE THREAD

**Issue by formula349** [fuse-box/fuse-box#1250]
I'm having trouble with the split config bundle resolving when the app is hosted in a sub folder. The problem is that one environment is hosted under a /uat path on the server, while production is hosted under the root /.

If I use splitConfig({ browser: '/scripts/dist' }) then it works great in production. If I switch to a relative path it works until the page is loaded with a path like /sis/user or /user, the split bundle tries to resolve with /user/scripts/dist or /sis/user/scripts/dist.

I've looked a great deal through the code and the docs for a way to handle this. If I missed something, please let me know. Otherwise I think the easiest way to handle this would be to allow the splitConfig browser parameter take a function that is executed at runtime to determine the path based on the environment.

Any ideas? Thanks!

**Comment by nchanged** [comment]
Why not making a special build for production with split config? As in a condition

**Comment by formula349** [comment]
Introducing this variable into the build pipeline might be the best approach. Thanks!
