### ISSUE TITLE
Vendor bundle not bundling jquery

### ISSUE THREAD

**Issue by pmonty** [fuse-box/fuse-box#1251]
So have adjusted [my fuse.ts](https://gist.github.com/pmonty/2c043825759de87f58e37d7be366a4a6) to deal with my previous issue and it seems to be working with the dev server. The only issue now is the quantum build. I get `$ is not defined` which is correct it isn't being bundled despite me adding the shim to the vendor bundle.

Relevant code:
```
    public get vendorBundle()
    {
        const vendor = this.fuse.bundle('bundles/vendor');
        vendor.shim({
            jquery: {
                source: "node_modules/jquery/dist/jquery.min.js",
                exports: "$",
            }
        });
        vendor.splitConfig({ dest: "bundles" });
        if (!this.isProduction) {
            vendor.watch();
            vendor.hmr();
        }
        vendor.sourceMaps(true);
        vendor.instructions(`~ app.tsx`);
        return vendor;
        // return this.fuse.bundle('bundles/vendor').instructions(`~ app.tsx`);
    }
```

It is fine though without quantum. Feel free to check my quantum setup in the link at top but I haven't touched that in ages. I thought it might be treeshaking so disabled as a test and that wasn't the issue. 

If i shim it globally and not on the specific bundle then it bundles a [hash]-shims.js and adds it to index.html but then I get the following error in console.

![image](https://user-images.githubusercontent.com/7111292/39612952-373b1826-4fa7-11e8-97a8-41cf56195d17.png)

**Update:**
Looks like if I shim jquery.js instead of jquery.min.js then dev won't even work.

**Comment by nchanged** [comment]
Make sure WebIndexPlugin has `$bundles` and the actual shims are loaded before you main app, which isn't based on what I see. Define vendor first, then your master app

**Comment by pmonty** [comment]
Not to sure what you mean by $bundles in the plugin. If you mean in the template file then it is definitely there because the output is the following.
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>EnergyAustralia Broadband - Self Service Portal</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600" rel="stylesheet">
    <script src="https://unpkg.com/core-js@2.5.1/client/core.min.js"></script>
    <link rel="stylesheet" href="/e887cff9-styles.css"/>
</head>
<body>
    <div id="root">
    </div>
    <script  type="text/javascript" src="/bundles/34058a2a-vendor.js"></script>
    <script  type="text/javascript" src="/bundles/320ef160-app.js"></script>
</body>
</html>
```

looks like the vendor gets bundled before the app or atleast defined before. And as for in my fuse file I always do it in that order
```
    context.vendorBundle;
    context.appBundle;
```

**Comment by pmonty** [comment]
Not to sure what you mean by $bundles in the plugin. If you mean in the template file then it is definitely there because the output is the following.
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>EnergyAustralia Broadband - Self Service Portal</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600" rel="stylesheet">
    <script src="https://unpkg.com/core-js@2.5.1/client/core.min.js"></script>
    <link rel="stylesheet" href="/e887cff9-styles.css"/>
</head>
<body>
    <div id="root">
    </div>
    <script  type="text/javascript" src="/bundles/34058a2a-vendor.js"></script>
    <script  type="text/javascript" src="/bundles/320ef160-app.js"></script>
</body>
</html>
```

looks like the vendor gets bundled before the app or atleast defined before. And as for in my fuse file I always do it in that order
```
    context.vendorBundle;
    context.appBundle;
```

**Comment by nchanged** [comment]
that means that `7669ec3a-shims.js` cannot be reached. It's an HTTP error.
Should be 
```
 <script  type="text/javascript" src="/bundles/7669ec3a-shims.js"></script>
```
(I think)

**Comment by pmonty** [comment]
Definitely right as this is the whole dist folder after build.

![image](https://user-images.githubusercontent.com/7111292/39670179-52a25542-5142-11e8-9fa9-d8a1543a5e47.png)

Also looks like it says syntax error so its like it is finding the file fine.

**Comment by nchanged** [comment]
Ok then what is this syntax error then

**Comment by pmonty** [comment]
Looks like `Unexpected token <` but its in the shim file which is jquery.min.js and not my own code.

**Comment by nchanged** [comment]
@pmonty that means that the file isn't fetched, or fetched with an error. Inspect the network tab, and check what it responds with. I bet it's an HTML file, but not javascript

**Comment by pmonty** [comment]
I have noticed also that when I don't use quantum it finds the files. But in quantum I opened the index.html file directly and removed the `/` at the start of each `src` attribute and then it kind of done some stuff. Jquery is still missing though.

```
<script  type="text/javascript" src="7669ec3a-shims.js"></script>
<script  type="text/javascript" src="bundles/34058a2a-vendor.js"></script>
<script  type="text/javascript" src="bundles/320ef160-app.js"></script>
```

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
