### ISSUE TITLE
fuse-box eslint-loader

### ISSUE THREAD

**Issue by PodaruDragos** [fuse-box/fuse-box#126]
I started with fuse-box today and i got to say this is one of the best bundle-loaders i have ever worked with. It will be really nice to have a eslint-loader for sloppy developers like me.

**Comment by nchanged** [comment]
Thanks for you kind words! We will keep you posted!

**Comment by nchanged** [comment]
Please, check this doc!
https://github.com/fuse-box/fuse-box/blob/master/docs/third-party-plugins.md

It has been implemented.
