### ISSUE TITLE
eliminate dead code + tree-shaking

### ISSUE THREAD

**Issue by misantronic** [fuse-box/fuse-box#1262]
I have the following code:

```js
if (process.env.NODE_ENV !== 'production') {
        renderMigration();
}
```

in production this part is successfully removed from the code which is great. 
What's not working is that `renderMigration()` and all its dependencies are not removed by tree shaking but also bundled to the production-app.

```js
i.renderMigration=async function(){await n.connect(),d.render ....
```

What can I do to make this work?

**Comment by nchanged** [comment]
@misantronic 
I think you need to move the implementation into a separate module then it will be removed 
```
if (process.env.NODE_ENV !== 'production') {
  require("./renderMigration")
}
```

**Comment by misantronic** [comment]
Great, thank you!
