### ISSUE TITLE
Inline js into HTML

### ISSUE THREAD

**Issue by phamtm** [fuse-box/fuse-box#1263]
Is there a way to directly inline JavaScript into the HTML template? One use case I have is to bundle the Fusebox loader api directly into HTML to save one round trip. Thank you!

**Comment by nchanged** [comment]
@phamtm not atm, but you can open a PR, we can assist it. Take a look at WebIndexPlugin implementation, this feature can be added there

**Comment by nchanged** [comment]
Implemented in  `v4`. Please upgrade to the [major version](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)
