### ISSUE TITLE
Shims are not bundled

### ISSUE THREAD

**Issue by Gregor-Agnes** [fuse-box/fuse-box#1266]
Having following fuse.js:

```const { src, task, exec, context } = require("fuse-box/sparky");
const {FuseBox, CSSPlugin, SassPlugin, QuantumPlugin, UglifyJSPlugin, WebIndexPlugin, Sparky} = require("fuse-box");
let app, vendor, isProduction = false;

let themeName = 'exampletheme';
let proxy = 'http://some.proxy.url';

context(class {
  getConfig() {
    return FuseBox.init({
      target: 'browser@es5',
      homeDir: "web/typo3conf/ext/" + themeName + "/Resources/Private",
      output: "web/typo3conf/ext/" + themeName + "/Resources/Public/$name.js",
      sourceMaps: !isProduction,
      plugins: [
        [SassPlugin(), CSSPlugin()],
        CSSPlugin(),
        WebIndexPlugin({path: "."}),
        this.isProduction && QuantumPlugin({
          treeshake: true,
          uglify: true,
          bakeApiIntoBundle: 'vendor',
          css: {
            clean: true
          }
        })
      ]
    });
  }
})
// development task "node fuse""
task("default", async context => {
  const fuse = context.getConfig();
  if (!isProduction) {
    fuse.dev({
      proxy: {
        '/': {
          target: proxy,
          changeOrigin: true,
          pathRewrite: {
            '^/': '/',
          },
        }
      }
    });
  }
  fuse.bundle("vendor")
    .shim({
      jquery: {
        source: "node_modules/jquery/dist/jquery.js",
        exports: "$",
      }
    }).hmr().watch()
    .instructions("~ JavaScript/index.ts");

  fuse.bundle("app")
    .instructions("!> JavaScript/index.ts")

  await fuse.run();
});

// Dist task "node fuse dist"
task("dist", async context => {
  context.isProduction = true;
  const fuse = context.getConfig();
  await src("web/typo3conf/ext/" + themeName + "/Resources/Public/")
    .clean("web/typo3conf/ext/" + themeName + "/Resources/Public/")
    .exec();
  fuse.bundle("vendor")
    .shim({
      jquery: {
        source: "node_modules/jquery/dist/jquery.js",
        exports: "$",
      }
    })
    .instructions("~ JavaScript/index.ts");
  fuse.bundle("app")
    .instructions("!> JavaScript/index.ts")

  await fuse.run()
});
```
Dev-Mode: everything fine
Production: jquery shim is not included in vendor.
So I tried:
```
treeshake: {
  shouldRemove: file => {
    if (file.fuseBoxPath === "jquery/index.js") {
      return false;
    }
  }
},
```
because I noticed

> → tree shaking: Mark for removal jquery/index.js

in the console.

but still: jquery gets not included in vendor. But treeshaking stops working. app.js ist nearly 1MB instead of 1KB. 

If I shim in the config part, everything ist fine, but I don't want the extra shim.js file.

I looked at https://github.com/fuse-box/jquery-shimming-example/blob/master/fuse.js 
but there is not Quantum-Example.

**Comment by nchanged** [comment]
@Gregor-Agnes 
please move `.shim({
      jquery: {
        source: "node_modules/jquery/dist/jquery.js",
        exports: "$",
      }
    })`  `to FuseBox.init` as described in the doc. We need to remove it from the chain, it buggy.

**Comment by Gregor-Agnes** [comment]
Ok. Is there any other way to bundle shims in vendor.js?

**Comment by nchanged** [comment]
@Gregor-Agnes shims will be in a separate bundle called `shims.js`

**Comment by Gregor-Agnes** [comment]
Yes I know that. I want to reduce the http-requests and therefore I wrote:

> If I shim in the config part, everything ist fine, but I don't want the extra shim.js file.

So just for the record: Is there any other way to bundle shims?

**Comment by nchanged** [comment]
Not ATM, but we are open for PRs. That shouldn't be big of a deal.

https://github.com/fuse-box/fuse-box/blob/5652c0b0f59e9887907db4d5f0984c7accee6fda/src/quantum/plugin/BundleWriter.ts#L38-L58

We could introduce `bakeShimsIntoBundle` options in Quantum

**Comment by nchanged** [comment]
#1274
