### ISSUE TITLE
Usage of .babelrc 

### ISSUE THREAD

**Issue by JiDai** [fuse-box/fuse-box#127]
Hi,

Can I use the recommended `.babelrc` rather than inline fuse configuration : 

```
fsbx.BabelPlugin({
    config: {
        sourceMaps: true,
        presets: ["react"],
        plugins: [
            "react-hot-loader/babel",
            "transform-class-properties"
        ]
    }
})
```

Thanks

**Comment by nchanged** [comment]
Not at the moment, but it's a great feature to have! We keep you posted.

**Comment by devmondo** [comment]
@JiDai  we implemented this in  babelrc branch, we will merge it soon, but if you want to take a spin you can try that branch :)

**Comment by nchanged** [comment]
https://github.com/fuse-box/fuse-box/commit/3dc757d6d16679be2b1175b00dabba47552aab25#diff-cce8c4ee9af60947caba11bb839e6f30R34

**Comment by JiDai** [comment]
I tried to install commit in npm
```"fuse-box": "git://github.com/fuse-box/fuse-box.git#3dc757d",``` 
but I got the error
```Error: Cannot find module 'fuse-box'```
I don't have this error on master

**Comment by nchanged** [comment]
it's in master now, you can pull, and run `gulp dist`

**Comment by JiDai** [comment]
Ah ok, did not see that. I tried to clone/git pull but `gulp dist` throw this error : 
```
Error: ENOENT: no such file or directory, open '.../fuse-box/src/tsconfig.json'
```

**Comment by nchanged** [comment]
do you you have `tsconfig.json` in `src/` ?

**Comment by devmondo** [comment]
@nchanged  with update we made we should not care about this, i think this is source code error it self

**Comment by nchanged** [comment]
It's all good now.
https://github.com/fuse-box/react-example/blob/master/.babelrc
