### ISSUE TITLE
Acorn error preventing bundle

### ISSUE THREAD

**Issue by Robula** [fuse-box/fuse-box#1271]
OS: macOS 10.13.4
Node: 8.10.0
fuse-box: 3.2.2

Hi all, I have just installed fuse-box for the first time to try it out however I am unable to bundle my code due to an Acorn error.

My `fuse.js`:
```
const { FuseBox } = require('fuse-box');

const fuse = FuseBox.init({
  homeDir: 'src',
  target: 'server@esnext',
  output: 'dist/$name.js'
});

fuse
  .bundle('app')
  .instructions('> index.ts');
fuse.run();
```

After running `node fuse.js` I get this in the output.
```
Acorn error: Invalid number (19:15)
File: /Users/rob/DEV/FuseProj/node_modules/extract-zip/node_modules/mkdirp/index.js

17
18      if (mode === undefined) {
19          mode = 0777 & (~process.umask());
20      }
21      if (!made) made = null;
22
23      var cb = f || function () {};
```
Am I missing something?
Thanks

**Comment by nchanged** [comment]
@Robula how about `.instructions('> [index.ts]');` that's how it should be with server

**Comment by Robula** [comment]
@nchanged Right you are! Thanks 😄
