### ISSUE TITLE
SPAM: Storybook for FuseBox

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#1272]
Guys, sorry for the spam.
I love your work, but you know that already.

It took me some time, but I finally brought my package to where I wanted to have it.
It is a storybook (React component catalogue) and a test viewer.

It comes in two flavours:

1. The environment itself:

https://github.com/tomitrescak/luis

2. The vscode plugin that allows you to live preview your snapshots and also components:

https://marketplace.visualstudio.com/items?itemName=Tomas.luis-snapshot-preview 

If you like the effort, maybe you can drop a note somewhere.
I am going to auto close this issue.

**Comment by nchanged** [comment]
That's terrific! Could you submit a PR to our docs? 
I will re-open it, so I won't forget.

**Comment by tomitrescak** [comment]
@nchanged will be my pleasure .. I tried to find where but not sure. Can you point me to the file? Thanks!

**Comment by nchanged** [comment]
Maybe guides? 
https://github.com/fuse-box/fuse-box/tree/master/docs/guides

**Comment by Kompwu** [comment]
@tomitrescak How's going ?

**Comment by tomitrescak** [comment]
Am swamped right now. Will do it when I have a bit of time ;/

**Comment by Kompwu** [comment]
@tomitrescak ping.

**Comment by tomitrescak** [comment]
Guys, my life is a misery right now. How about just using the intro from the documentation with the animated gif and linking it to the package? It is quite stable now.

**Comment by Kompwu** [comment]
@tomitrescak ping.

**Comment by nchanged** [comment]
Let's do it =)

**Comment by tomitrescak** [comment]
I added the file there with a short description. Please let me know what you think!
