### ISSUE TITLE
Uncaught Package not found util with feross/simple-peer

### ISSUE THREAD

**Issue by popsUlfr** [fuse-box/fuse-box#1273]
Hello everyone.

I just hit an issue trying to bundle [feross/simple-peer](https://github.com/feross/simple-peer) in my project.

It throws
```
Uncaught Package not found util
```

With Quantum I get the process not found error #1220 

I already cleaned `.fusebox`

I also tried installing `fuse-box@next`, but still the same.

Here is a minimal example I extracted from my main project to reproduce : 

`src/index.ts` : 
```typescript
import * as Peer from 'simple-peer';

const peer = new Peer({initiator: true});
peer.on('signal', data => console.log(data));
```

`fuse.js` : 
```javascript
const { src, task, exec, context } = require("fuse-box/sparky");
const { FuseBox, WebIndexPlugin, QuantumPlugin } = require('fuse-box');
context(class {
	getClientConfig() {
		return FuseBox.init({
			target : 'browser@es2017',
			homeDir: 'src',
			output: 'dist/$name.js',
			package: 'client',
			plugins: [
				!this.isProduction && WebIndexPlugin(),
				this.isProduction && QuantumPlugin({
					target: 'browser',
					treeshake : true,
					bakeApiIntoBundle: true
				})
			]
		});
	}
});

task('default', async context => {
	const fuse = context.getClientConfig();
	fuse.dev();
	fuse.bundle('client')
		.hmr()
		.watch()
		.instructions('>index.ts');
	await fuse.run();
});

task('dist', async context => {
	context.isProduction = true;
	const fuse = context.getClientConfig();
	fuse.bundle('client')
		.instructions('>index.ts');
	await fuse.run()
});
```

`package.json` : 
```json
{
  "name": "fuse-box-package-not-found-error",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "fuse-box": "^3.2.2",
    "simple-peer": "^9.1.1",
    "typescript": "^2.8.3"
  }
}
```

Here it is prepackaged : 
[fuse-box-package-not-found-error.tar.gz](https://github.com/fuse-box/fuse-box/files/2022899/fuse-box-package-not-found-error.tar.gz)

EDIT: Using the shim feature it works by adding this configuration

```javascript
shim: {
	'simple-peer': {
		source: 'node_modules/simple-peer/simplepeer.min.js',
		exports: 'SimplePeer'
	}
}
```

Would be nice to know though why fuse-box is having a hard time with the source files.

**Comment by nchanged** [comment]
Hello @popsUlfr 
I've been investigating this issue, and here is what have:

This package depends on `readable-stream` which has a `browser` field, with the following config:

https://github.com/nodejs/readable-stream/blob/master/package.json#L40

According to the browser spec `util: false` means that this library WILL NOT be bundled.

FuseBox does everything correctly, but, obviously, that leads to an error, because it uses util. 

I noticed some odd comments in the code


```
/*<replacement>*/
var debugUtil = require('util');
var debug = void 0;
if (debugUtil && debugUtil.debuglog) {
  debug = debugUtil.debuglog('stream');
} else {
  debug = function () {};
}
/*</replacement>*/
```
Which tells me that the author created that package with one bundler in mind. Nonetheless, FuseBox follows the standard. 
No can do here.

**Comment by popsUlfr** [comment]
@nchanged Thanks for the information.

`readable-stream` doesn't necessarily seem to expect browserify or does it ? browserifying `simple-peer` bundles it all up without issue so I was wondering if something could be done in fuse-box to also support such edge cases in the future especially if browserify can handle it.

I'm a bit confused about : 

> According to the browser spec util: false means that this library WILL NOT be bundled.

> FuseBox does everything correctly, but, obviously, that leads to an error, because it uses util.

So why is fusebox generating code that is still looking for it ?

Does Quantum perform as well on already minified code ? I'm gonna do some tests on my end as well.

**Comment by nchanged** [comment]
It doesn't alter the code, It won't know what to do with it (using util)
Yes, Quantum handles it nicely.
You can also add it `util` manually

instructions(">index.ts +util")

**Comment by popsUlfr** [comment]
@nchanged Ah I get it now, thank you.

> instructions(">index.ts +util")

Ah riiiiiiight, that's very cool :D I'll have to remember that trick.

Fusebox is really awesome thanks for all the work that went into it.

**Comment by misantronic** [comment]
I also ran into this issue when updating to fuse-box@3.7.0
`instructions(">index.ts +util")` fixed it for me.
