### ISSUE TITLE
source-maps for production-build

### ISSUE THREAD

**Issue by misantronic** [fuse-box/fuse-box#1275]
for using with bugsnag, I want to create source-maps for my production build.
As far as I can see it, when setting `sourceMaps: true`, they are only generated when not using the QuantumPlugin (minifiying, tree-shaking etc).

**Comment by nchanged** [comment]
Yep, that's a known issue. Quantum doesn't support source maps yet

**Comment by nchanged** [comment]
#1375

**Comment by nchanged** [comment]
This has been all fixed in `v4`. Please upgrade to the [major version](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)
