### ISSUE TITLE
sparky waterfall-parallel docs

### ISSUE THREAD

**Issue by SassNinja** [fuse-box/fuse-box#1279]
There's a typo in the sparky docs at waterfall-parallel section
https://fuse-box.org/page/sparky#waterfall-vs-parallel

It says
> To run tasks in `waterfall` mode, just prefix the task name with an `&`

This doesn't match the example below.
It should rather be `in parallel mode`, shouldn't it?

**Comment by nchanged** [comment]
@SassNinja That's right. Can you submit a PR please?

**Comment by SassNinja** [comment]
@nchanged done!
