### ISSUE TITLE
Resolve modules from source folder

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#1284]
Hi, I browsed through the issues and I can't find a solution to my problem. Something similar is in #991 but no luck with that.

I have a root folder set to `src`.
I am trying to import a module from `import DataSet from client/modules/form/models/dataset_model`.

I have set following in my fuse.js:

```
fuse
  .bundle('app')
  .alias('client', '~/client')
```

Yet, I keep getting `WARNING Statement "modules/form/models/dataset_model.js" has failed to resolve in module "client"`

Truth is that I have a .ts file there not .js. 
Any luck to solve this? Thanks!

**Comment by tomitrescak** [comment]
Weird, doing following works:

```
FuseBox.init({
  ...
  alias: {
    client: '~/client/',
    server: '~/server/',
    shared: '~/shared/'
  },
```

Looks like the `.alias` is not working properly.

**Comment by bendersej** [comment]
@tomitrescak, `alias` takes in an object literal: https://fuse-box.org/page/configuration#alias, hence your first code snippet is incorrect (and your second works as expected).

**Comment by nchanged** [comment]
This has been all fixed in `v4`. Please upgrade to the [major version](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)
