### ISSUE TITLE
[Feature] Bare build

### ISSUE THREAD

**Issue by wyqydsyq** [fuse-box/fuse-box#1285]
I'd like to be able to use fuse-box for both JS modules and my actual webapps for convenience and consistency in configuration between the two types of projects, currently it is only possible to use for webapps because the fuse-box runtime gets automatically injected into the bundle which prevents you from importing it as a JS module.

If there were a flag to disable injection of the fuse-box runtime (so the resulting bundle is just plain JS module exports, not wrapped in fuse-box) this would enable people using it for both cases.

Obviously most of the functionality fuse-box offers wouldn't be useful in the context of a plain module, but it doesn't have to be, it would just be nice to be able to build all my JS projects using the same tool and configuration format regardless of whether they're a standalone webapp or a JS module to be imported by other code.

**Comment by nchanged** [comment]
Hi, if you use Quantum plugin for production it will add only 200bytes of API and it will be the size of a bundle produced using Rollup

Give it a try
