### ISSUE TITLE
Package names that begin with capital letters can be defined, but not properly imported

### ISSUE THREAD

**Issue by dlannoye** [fuse-box/fuse-box#1286]
I have a repository that shows this issues here:
https://github.com/dlannoye/fuse-box-default-package

In fuse.js I am defining a package with a name that begins with an uppercase letter. This builds and bundles fine, but at load time I get an `Uncaught Package not found default` from the fuse-box generated import call. This is because the code in the loader doesn't treat the string beginning with a capital letters as a package name.

If I call `FuseBox.import("", { pkg: "SomeProject" });` the package loads just fine. 

I can understand this restriction since the [package.json](https://docs.npmjs.com/files/package.json) specs say not to use capital letters in a package name, but it would be nice if fuse-box handled this in a better way. Maybe through a build time error or a better exception message. 

Also the fuse-box [documentation for package name](https://fuse-box.org/page/configuration#package-name) uses invalid names for npm packages and doesn't mention these restrictions.

**Comment by nchanged** [comment]
@dlannoye I see, the thing is that Quantum renders useless this package name option. So I would recommend removing that, and use Quantum plugin instead with `isolatedAPI`  or 'noConflictAPI'. If you want to expose it to `window` is `globals` option on FuseBox.init.

It will produce highly optimised no-conflict bundles .

**Comment by dlannoye** [comment]
I had also noticed that Quantum avoids this issue and will probably be moving my development builds to use it as well. That said I have also opened a PR to update the documentation around package names: #1287
