### ISSUE TITLE
Uncaught Package not found p5.dom 

### ISSUE THREAD

**Issue by mictadlo** [fuse-box/fuse-box#1290]
Hi,
I got `Uncaught Package not found p5.dom` while using the following code:

`src/sketch.ts` 
```
import 'p5';
/// <reference path="../node_modules/p5/lib/addons" />
import 'p5.dom'
```
The `package.json` looks like this:
```
    {
    	"dependencies": {
    		"p5": "^0.6.1"
    	},
    	"devDependencies": {
    		"@types/node": "^10.3.1",
    		"fuse-box": "^3.2.2",
    		"tslib": "^1.9.2",
    		"typescript": "^2.9.1",
    	}
    }
```
fuse.js:
```
const {FuseBox, WebIndexPlugin} = require('fuse-box');

const fuse = FuseBox.init({
  homeDir: 'src',
  output: 'dist/$name.js',
  sourceMaps: true,
  globals: { "p5": "p5" },
  plugins: [
      WebIndexPlugin(),
  ]
});

fuse.dev({open : true});

fuse.bundle('app')
  .instructions('> sketch.ts +p5')
  .hmr({reload: true})
  .watch()

fuse.run();
```
What did I miss?

Thank you in advance.

Michal

**Comment by nchanged** [comment]
@mictadlo it looks like FuseBox thinks it's a file
`p5.dom` as `dots` in module names are not allowed.

**Comment by mictadlo** [comment]
Is there any workaround? Here is the p5 [project](https://github.com/processing/p5.js/tree/master/lib/addons).

**Comment by nchanged** [comment]
This has been all fixed in `v4`. Please upgrade to the [major version](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)
