### ISSUE TITLE
Wrong build output

### ISSUE THREAD

**Issue by marcobusemann** [fuse-box/fuse-box#1291]
Hey folks, 

first of all, thanks for the great work!
On my way switching from webpack to fuse-box for one of my projects, i got a problem i cannot explain to myself. 

Given then following typescript code:
```
import { Game } from './Game';
import { Player } from './Player';

export interface NewGamePlayer {
    id: string;
    name: string;
}

export class NewGame extends Game {
    constructor(players : NewGamePlayer[]) {
        super(players[0].id, players.map(p => new Player(p.id, p.name)));
    }
}
```

I bundle the server using this config:

```
const fuseServer = FuseBox.init({
    homeDir : "src/server",
    target : "server@esnext",
    output : "dist/$name.js",
    tsConfig : "./tsconfig.json",
});

fuseServer.bundle("server")
    .watch()
    .instructions(" > [server.ts]");
fuseServer.run();
```

The part of the bundle for the code above looks like this. Obviously the variable ```Player_1``` is missing which results in an error. In my opinion ```Player_1``` should be required exactly like ```Game_1```.

```
___scope___.file("game/NewGame.js", function(exports, require, module, __filename, __dirname){

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Game_1 = require("./Game");
class NewGame extends Game_1.Game {
    constructor(players) {
        super(players[0].id, players.map(p => new Player_1.Player(p.id, p.name)));
    }
}
exports.NewGame = NewGame;

});
```

Am i missing something?

**Comment by nchanged** [comment]
Hi, thanks!
that's actually very odd since FuseBox doesn't do anything to imports there, if there one to blame it's typescript. Can you modify the code
```
import { Game } from './Game';
import { Player } from './Player';
console.log(Player);
```

And see the output? Also for cleaner experiment clear the cache, (`.fusebox` folder)
