### ISSUE TITLE
SASS and overriding styles

### ISSUE THREAD

**Issue by pmonty** [fuse-box/fuse-box#1292]
So I seem to have sorted out my resources issue by importing the node_module bootstrap-sass directly in .tsx. and then immediately after it importing my main stylesheet as it overrides some of the bootstrap-sass stuff to personalise it a bit.

But now some of the overriding is not working borders on certain buttons are missing and some text colors are a bit off.

**Current setup:**
_App.tsx_
```
import 'bootstrap-sass/assets/javascripts/bootstrap.min.js';
import 'bootstrap-sass/assets/stylesheets/_bootstrap.scss';
import '~/wholesalers/EA/styles/site.scss';

//..... rest of code
```

_wholesalers/EA/styles/site.scss_
```
// styling
// base folder has generic stuff between all wholesalers

@import '../../base/styles/mixins.scss';
@import "../../base/styles/_variables.scss";
@import "../../base/styles/site.scss";

//more styling and overriding specific to that wholesaler
```

_base/styles/site.scss_
```
@import 'vendor';
```

__vendor.scss_
in this file the commented line is where it use to be it is now in the tsx instead
```
/* #### VENDOR LIBRARIES #### */

$icon-font-path: '~bootstrap-sass/assets/fonts/bootstrap/';
//@import '~bootstrap-sass/assets/stylesheets/_bootstrap.scss';
@import '~react-select/dist/react-select.css';
@import '~react-table/react-table.css';
@import '~animate.sass/scss/animate.scss';
```

Setup is pretty complex, not sure if FuseBox can handle such a complex styling solution but it seems to be doing most things right. Except as mentioned it is breaking some styling from overridden bootstrap-sass. It is also not handling the following:

```
  &:after {
    content: url(../../images/formsubmitarrow.png);
```

That file does not get added to assets or even inlined if i try inlining.

**Comment by nchanged** [comment]
regarding your path resolution you could it solve my adding macros

```
CSSResourcePlugin({
                        dist: `css-resources`,
                        macros : {
                            images : path.resolve(__dirname, "src/foo/bar/images")
                        }
                    }),
```

```
 &:after {
    content: url($images/formsubmitarrow.png);
```

**Comment by pmonty** [comment]
hmm for that particular issue I am getting 
```
Errors for bundles/app bundle
  → ERROR Invalid CSS after "...formsubmitarrow": expected expression (e.g. 1px, bold), was ".png);"
      at /Users/pmonty/Projects/anex/ANEX.Website.OssPortal/src/~/wholesalers/base/styles/elements/_buttons.scss:28:41
```

strange

**Comment by nchanged** [comment]
Yeah, the quotation is important!

**Comment by pmonty** [comment]
Any idea on the overriding issue? What is the purpose of importing via typescript for fusebox us it quicker?

Cause I've noticed my CSS bundle is almost double the size of my webpack one. 

Surely if my main (first CSS entry point) I'd included in the app.tsx then I don't need to include my nodemodules CSS stuff in tax aswell as it would get caught right?

**Comment by pmonty** [comment]
More of an issue is popping up now. It seems that my CSS bundle is including multiple definitions....

done a quick search for the following
```
mary-usage:active,.btn-primary-usage:focus:active,.btn-primary-usage:hover:active{background:#6600ab;border-color:#5a0096}
```

and that is in my css bundle 5 times. On webpack it was only once. Not sure why it would be 5 times bundled.

**Comment by nchanged** [comment]
Hi, sorry for experiencing that. Yes asset resolution works only relative to the path of a parent file. But I am planning to work on an universal CSSPlugin that should solve the issus

**Comment by pmonty** [comment]
@nchanged  so here is my solution using macros

```
          [
            SassPlugin({ importer: true }),
            CSSResourcePlugin({ 
              inline: true,
              macros: { 
                base: path.resolve(__dirname, './src/~/wholesalers/base/images'),
                node: path.resolve(__dirname, './node_modules/')
              }
            }),            
            CSSPlugin({ minify: true })
          ],
```
```
$icon-font-path: '$node/bootstrap-sass/assets/fonts/bootstrap/'; 
@import '~bootstrap-sass/assets/stylesheets/_bootstrap.scss';
@import '~animate.sass/scss/animate.scss';
```
using the $node macro there helped hmmm. 

Cannot wait to see this universal plugin though!!!!

Only issue I have now though is that some stuff is being added multiple times to the css bundle and I think it is because there are multiple same files.

```
.btn-primary-usage {
  @extend .btn-primary-theme!optional; // Toggle
}
```

That code is in 5 of the same named _button-variables.scss file under each wholesaler folder. Should really only be importing one of them but it is probably more of an issue with my complex project and necessity for a lot fo things at build time to be dynamic. Will try sort something out for this but not a big deal as with this minor issue the bundle is only slightly bigger than the previous webpack build but my app and vendor bundles are much smaller 😄 

This issue can remained close 💯 😃

**Comment by nchanged** [comment]
@pmonty try QuantumCSS, `clean-css` should remove the dups. Besides it will strip it out of your js and pipe to the file system.
