### ISSUE TITLE
Different port for HMR

### ISSUE THREAD

**Issue by peterhudec** [fuse-box/fuse-box#1295]
It seems that it is currently not possible to configure `hmr()` to use a different port than `dev()` server uses, even though there is the `hmr({port})` option which seems to have no effect whatsoever. Setting the `hmr({socketURI})` works only if the port is the same as `dev({port})`.

Is this a bug or intended behaviour?

The reason I need the HMR to use a different port than the dev server is that I want my own websocket to be accessible on the app's root path, which however is used by HMR.

**Comment by nchanged** [comment]
@peterhudec   I think if you do both it will work. At least the last time I checked.
You can set `httpServer : false` and make your own dev server

Here is how to check it out in 20 second ;-)
```bash
npm install -g fuse-box
fuse install react-express-server
cd react-express-server
npm install
node fuse
```

**Comment by peterhudec** [comment]
Ok, so `hmr({socketURI})` works only for the HMR socket client, but the HMR server always uses the `dev({port})`. There was no process using the port specified by `dev({port})` or `hmr({socketURI})` on my system. Nevertheless, setting `dev({httpServer: false})` worked for me.

Anyway, `hmr({port})` doesn't seem to have any effect and the only purpose of `hmr({socketURI})` seems to be handling `wss`. So this is more about documentation.

**Comment by nchanged** [comment]
You know what might be the problem. the order of your hmr and .dev calls. Try swapping them. The problem emerges when hmr is trying to store a value on a non existing Dev server

**Comment by peterhudec** [comment]
So I have swapped them calls so that `dev()` comes after `hmr()` and the only difference is that the _socket client_ is now trying to connect to `ws://localhost:4444`, no matter what `hmr({port})` is set to. But still there is no process using port `4444`.

```js
fuse.bundle("app")
  .instructions(`>index.tsx`)
  .hmr({port: 8222})
  .watch('**')

fuse.dev({port: 8111})

fuse.run()

// Connecting to fusebox HMR at ws://localhost:4444 (ERR_CONNECTION_REFUSED)
```

```js
fuse.dev({port: 8111})

fuse.bundle("app")
  .instructions(`>index.tsx`)
  .hmr({port: 8222})
  .watch('**')

fuse.run()

// Connecting to fusebox HMR at ws://localhost:8111 (Connected)
```

**Comment by nchanged** [comment]
So your order was correct. Ive just realised that the socket server is launched on the same port as http hence cannot be configured individually

**Comment by nchanged** [comment]
This has been all fixed in `v4`. Please upgrade to the [major version](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)
