### ISSUE TITLE
RawPlugin: synthetic default imports

### ISSUE THREAD

**Issue by merlinnot** [fuse-box/fuse-box#1296]
Hi, I'd like to make a PR to make `RawPlugin` work with synthetic default imports. I see three reasonable ways of implementing it:
- add an option to `RawPlugin`, e.g. `RawPlugin({useSyntheticDefaultImports: true})`
- detecting the configuration (`allowSyntheticDefaultImports` in `tsconfig.json` or an option passed to FuseBox.init)

May I ask someone more experienced with the codebase for an opinion?

**Comment by nchanged** [comment]
@merlinnot we can detect `allowSyntheticDefaultImports` that too.

[https://github.com/fuse-box/fuse-box/blob/master/src/core/TypescriptConfig.ts](This) object is available in context (which has all the config loaded)

Also it would be nice to introduce an option.

Basically we check for it here:

https://github.com/fuse-box/fuse-box/blob/f680f49b7e7ceefd1387c9a6426155e393fac0fd/src/plugins/RawPlugin.ts#L73-L77


And do similarly to HTMLPlugin

https://github.com/fuse-box/fuse-box/blob/f680f49b7e7ceefd1387c9a6426155e393fac0fd/src/plugins/HTMLplugin.ts#L61-L65

**Comment by merlinnot** [comment]
Isn't it inconsistent with CopyPlugin? https://fuse-box.org/page/copy-plugin#usage

**Comment by nchanged** [comment]
This has been all fixed in `v4`. Please upgrade to the [major version](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)
