### ISSUE TITLE
Tiny chunk: 5 bytes

### ISSUE THREAD

**Issue by merlinnot** [fuse-box/fuse-box#1297]
In my production build, a chunk of size 5 bytes is created.

Here is a content of the file:
```js
$fsx;
```

All of the logs for this chunk:
```
  → Create split bundle 3b2ebcd7 with entry point @firebase/firestore/dist/index.cjs.js

  → Render bundle 3b2ebcd7

  → Uglifying bundles/3b2ebcd7...
  → Using uglify-es because the target is greater than ES5 or es6 option is set
  → Done uglifying bundles/3b2ebcd7
  size:  5 Bytes, 25 Bytes (gzipped)
```

**Comment by nchanged** [comment]
That's probably a bug with code splitting and external packages. Is this package using dynamic `import` syntax?

**Comment by merlinnot** [comment]
Yes, I'm using dynamic imports.

The package which lands in this chunk is not imported dynamically, but all of the files using this module are. I know that due to the size of this dependency (360kB) many splitters (like AggressiveSplittingPlugin for webpack) often extract it as a separate chunk.

**Comment by nchanged** [comment]
Does FuseBox extract it too? It's a known issue with this tiny chunk due to some conflicting dependencies

**Comment by merlinnot** [comment]
I thought only Quantum extracts chunks and FuseBox leaves everything in one file. How can I check that?

**Comment by nchanged** [comment]
that's right, Quantum extracts modules from the master bundle. There is a known issue, (I am aware of that) That tiny bit happens because
* A module is used asynchronously 
* A module is used synchronously someplace else

**Comment by merlinnot** [comment]
That might be the case, indeed.
