### ISSUE TITLE
Quantum: race condition: importing chunks

### ISSUE THREAD

**Issue by merlinnot** [fuse-box/fuse-box#1299]
I'm not certain which information might be valuable for debugging, but here are the basics:

My application is randomly throwing an error on load:
`Cannot read property 'store' of undefined`

Here's a source code of the relevant fragment:
```ts
import { userReducer } from '../reducers/user';
import { userSaga } from '../sagas/user';
import { saga, store } from '../store';

store.addReducers({ user: userReducer });
saga.run(userSaga);
```

It is being compiled to:
```js
(e.f[13] = function(t, a) {
  Object.defineProperty(a, '__esModule', { value: !0 });
  const r = e.r(14),
    n = e.r(15),
    s = e.r(18);
  s.store.addReducers({ user: r.userReducer }), s.saga.run(n.userSaga);
})
```

I've found the following object in the main chunk:
```js
{
  '5b128a11': ['bundles/5b128a11.js', 160],
  '899053d9': ['bundles/899053d9.js', 6],
  dbaa81ff: ['bundles/dbaa81ff.js', 7],
  '18abec98': ['bundles/18abec98.js', 18],
  '52ceddfb': ['bundles/52ceddfb.js', 13],
  b3f7477: ['bundles/b3f7477.js', 124],
  '3b2ebcd7': ['bundles/3b2ebcd7.js', 162],
  eb553a2c: ['bundles/eb553a2c.js', 133],
  '3f760a37': ['bundles/3f760a37.js', 10],
  '6cf28694': ['bundles/6cf28694.js', 24],
  '4dea487': ['bundles/4dea487.js', 80],
  aec457f1: ['bundles/aec457f1.js', 98],
  '88dec448': ['bundles/88dec448.js', 102],
  d6911687: ['bundles/d6911687.js', 115],
}
```

I assume that number `18` in this object corresponds to `e.r(18)` call from the compiled fragment. I took a look at the network panel at the time when the exception was thrown to see if `18abec98` chunk was loaded. Here's what I've found:
<img width="501" alt="screen shot 2018-06-22 at 19 22 21" src="https://user-images.githubusercontent.com/10390061/41790056-a1cb0ce8-7651-11e8-9cbc-cdbf140a35a1.png">

Since there is no `await`/`then`/callback I assume that a Quantum runtime takes care of calling all of the fragments in a correct order, when all of the dependencies are already resolved. It looks like some bug might be hiding there.

**Comment by nchanged** [comment]
Hm it looks like are you are not using dynamic imports on it, but a sync method instead. that might be it.

**Comment by merlinnot** [comment]
It should work fine, right? I want this piece to be loaded synchronously.

I no longer experience the issue after enabling `useJsNext`. Still reproducable when I switch it off.

**Comment by nchanged** [comment]
There might be an issue somewhere. It would be great if you could reproduce it. Otherwise it's impossible for me to fix it ;-)

**Comment by merlinnot** [comment]
Here are the relevant parts of the log for your convenience. I can share the entire thing if you want.

```
  → Generating abstraction, this may take a while
  → Abstraction generated
  → Process bundle cua
  → Process package default
  →   Files: 160
  → Create split bundle 18abec98 with entry point default/store/index.js
  → QuantumBit: Adding default/store/index.js to 18abec98
  → QuantumBit: Moving module redux from cua to 18abec98
  → QuantumBit: Moving module symbol-observable from cua to 18abec98
  → Render bundle 18abec98
  → Uglifying bundles/18abec98...
  → Using uglify-es because the target is greater than ES5 or es6 option is set
  → Done uglifying bundles/18abec98
  size:  6.1 kB, 2.3 kB (gzipped)
```

This file is imported synchronously in multiple files loaded asynchronously (fragments of the application) and it is being loaded using dynamic imports in the entrypoint, like this:
```ts
const [
  { appReducer },
  { appSaga, fragmentLoadingSaga },
  { saga, store },
] = await Promise.all([
  import('../reducers/app'),
  import('../sagas/app'),
  import('../store'),
  import('../fragments/user'),
]);
```

**Comment by nchanged** [comment]
@merlinnot right, can you import is synchronously in your entry point?

**Comment by merlinnot** [comment]
I could, but it would delay first contentful (and in some cases meaningful) paint. For the time being it works fine for me (after switching on `useJsNext`), but still, that's a bug :)

**Comment by merlinnot** [comment]
It doesn't work in the end... I guess I was lucky a few times when I've enabled `useJsNext`.

**Comment by nchanged** [comment]
@merlinnot could you reproduce the issue in a repository?

**Comment by merlinnot** [comment]
Sure, will do.

**Comment by merlinnot** [comment]
Here you go: https://github.com/merlinnot/fuse-box-issue-1299

**Comment by nchanged** [comment]
Well actually only `b` bundle

**Comment by merlinnot** [comment]
It’s just for a sake of repro so you can have fun debugging ;)

In my app I’m just importing Redux store in the shell. All fragments are then loaded asynchronously, but these fragments also import Redux store synchronously.

That’s basically what you have in a repro: index.ts is a shell, a.ts is a store and b.ts is a fragment.

**Comment by nchanged** [comment]
long story short - your Redux store shouldn't be separated from the master bundle, right?

**Comment by merlinnot** [comment]
Store can be in the master bundle, but I’m worried about other stuff:
- Ramada/Lodash - I might import some small pieces in the main bundle, other methods in fragments and I’d like to see only the required pieces in the master
- some huge libraries like Firestore - I import it asynchronously in the master bundle, but fragments load it synchronously. Ideally I’d like it to be in a separate bundle.

I think that the best option for me would be to create separate chunk out of everything and prefetch it. In the past I was pretty pleased with the results of aggressive splitting plugin.

**Comment by merlinnot** [comment]
```ts
await import("hugelib");
```
in the shell (master).

Then
```ts
import { stuff } from "hugelib"
```
in `fragment.ts`,

which is then imported with
```ts
await import("./fragment")
```
in the shell (master).

To make it more complicated, the fragment loading logic in my case is actually implemented separately and also loaded asynchronously...

The flow when you open the app looks like:
- index.html loads shell
- shell has a synchronously loaded loading screen
- authentication module is loaded asynchronously to figure out if a user is authenticated or not
- if he's not authenticated, authentication UI is loaded asynchronously
- afterwards Redux store is loaded (synchronoulsy), main application saga and so on
- then fragment loading logic is dowloaded asynchronously
- then fragment loading logic imports needed fragment based on path, these fragment might have some synchronous imports from stuff that was already used in the shell

But it's only one of the apps I have...

Ideal (general) behaviour I could think of is to separate everything that is anywhere loaded asynchronously and then try to combine these chunks if they are imported in the exact same bundles.

It's definitely needed for dependencies with side effects, like Custom Elements.

It would result in a large number of chunks for sure, but we have HTTP/2 and Service Workers, so we'll be good :)

**Comment by nchanged** [comment]
@merlinnot Why don't you have a config file that lists all the async imports.
```
export conf = {
  foo : () => await import("/foo"),
  boo : () => await import("/boo")
}
```

Then it will be all nice and neat ;-)

**Comment by nchanged** [comment]
@merlinnot btw, give `@next` a try. Quantum now does automatic CSS splitting ;-)

**Comment by merlinnot** [comment]
In some files I import async stuff synchronously. If I'd only import it asynchronously, it would make most of my code more complex that it needs to be, instead of writing

```ts
import { stuff } from './my/module'

do(stuff);
```

I'd have to write
```ts
import { myModule } from './conf';

(async () => {
  const { stuff } = await myModule();

  do(stuff);
})();
```

And I'm not so sure how it would work with tree shaking ;)

**Comment by merlinnot** [comment]
I've seen the issue with css, but I'm mostly working with Web Components and using link tags in Shadow DOM (thanks to [inertness of HTML elements in shadow trees](https://w3c.github.io/webcomponents/spec/shadow/#inertness-of-html-elements-in-a-shadow-tree)) causes FOUC on a component level (basically every component is flashing on it's own, looks funny).

So I'm using RawPlugin with a custom decorator and FuseBox HMR handler to inline my styles and hot-reload them:

Decorator:
```ts
import { html, LitElement } from '@polymer/lit-element';
import { register, unregister } from '../fusebox/registry';

export const styled = (name: string, styles: any) => <
  T extends { new (...args: any[]): LitElement }
>(
  constructor: T,
) =>
  class StyledElement extends constructor {
    static get properties() {
      return {
        styles: String,
      };
    }

    public styles: string;

    constructor(...args) {
      super(...args);
      this.styles = styles;
    }

    public _render(properties: any) {
      return html`
        <style>${properties.styles}</style>
        ${super._render(properties)}
      `;
    }

    public connectedCallback() {
      register(name, this);
      super.connectedCallback();
    }

    public disconnectedCallback() {
      unregister(name, this);
      super.disconnectedCallback();
    }
  };
```

Plugin:
```ts
import 'fuse-box/modules/fuse-loader';
import { getAll } from './registry';

const componentNameRegexp = /^styles\/([a-z\-]*)\.scss$/;
const pathToComponentName = path => {
  const maybeMatch = componentNameRegexp.exec(path);
  return maybeMatch !== null ? maybeMatch[1] : undefined;
};

const customizedHMRPlugin = {
  hmrUpdate: ({ content, path, type }): boolean => {
    if (type !== 'js') {
      return false;
    }

    const name = pathToComponentName(path);
    if (name !== undefined) {
      FuseBox.dynamic(path, content);
      const elements = getAll(name);
      if (elements !== undefined) {
        // tslint:disable-next-line no-eval
        const styles = eval(content);

        elements.forEach(element => {
          (element as any).styles = styles;
        });
      }
    } else {
      window.location.reload();
    }

    return true;
  },
};

if (!window.hmrRegistered) {
  window.hmrRegistered = true;
  FuseBox.addPlugin(customizedHMRPlugin);
}
```

Registry:
```ts
import { LitElement } from '@polymer/lit-element';

const instances: Map<string, Set<LitElement>> = new Map();

export const register = (name: string, element: LitElement) => {
  if (instances.has(name) === false) {
    instances.set(name, new Set());
  }

  const set = instances.get(name);
  if (set !== undefined) {
    set.add(element);
  }
};

export const unregister = (name: string, element: LitElement) => {
  const set = instances.get(name);
  if (set !== undefined) {
    set.delete(element);
  }
};

export const getAll = (name: string): Set<LitElement> | undefined =>
  instances.get(name);
```

I was actually about to create an issue for inlining Sass source maps, I know there is an issue with HMR + source maps, but I'm wondering if these would be inlined... Maybe it would work with my solution?

**Comment by nchanged** [comment]
@merlinnot that issue with HMR and sourcemaps was closed yesterday =)
https://github.com/fuse-box/fuse-box/commit/86d9811bda47303e6a3df338199a15f7fdc85f56

**Comment by merlinnot** [comment]
Oh nice. But there is no option to inline source maps with RawPlugin, is there?

**Comment by merlinnot** [comment]
My config for styles is quite simple (for dev):
```js
  [
    SassPlugin({
      importer: true,
      macros: { '@material': 'node_modules/@material' },
    }),
    PostCSSPlugin([require('autoprefixer')()]),
    RawPlugin(),
  ],
```

**Comment by nchanged** [comment]
no sure why do you mean by inlining sourcemaps with RawPlugin

**Comment by merlinnot** [comment]
I'm using RawPlugin to import my styles and inline them, like this:
```ts
import * as styles from "../styles/component.sass";

html`<style>${styles}</styles>`
```

Right now I get quite a lot of warning messages in the console because `styles` is a string (CSS) with a source mapping URL comment at the end.

That made me think that the browser can actually pick up these source maps even tho I inject it using template string literals. So I was wondering if inlining these would actually make my sass files to be mapped correctly.

**Comment by nchanged** [comment]
Thing is, you might want to go for a custom RawPlugin.. or CSSRawPlugin that would generate sourcemaps and link them too. `RawPlugin` simply reads the input and wraps it in a string.
