### ISSUE TITLE
Reflexion: target "npm" as server by default

### ISSUE THREAD

**Issue by eddow** [fuse-box/fuse-box#1301]
In `QuantumOptions.ts`, the function `isTargetServer` reads like this:
```ts
    public isTargetServer() {
        return this.optsTarget === "server" || this.optsTarget === "electron" || this.optsTarget === "npm";
    }
```

This means that, if the quantum target is set to `npm`, the code will be considered server-side; while an npm package can definitely be made for the browser-side.

As `universal` (of which `npm` is quite similar) is nor letting true `isTargetServer` nor `isTargetBrowser`, the `npm` target should perhaps do the same.

**Comment by nchanged** [comment]
@eddow I think you misunderstood target `npm`. Any package on npm is kind of server side. FuseBox transforms into a corresponding target upon bundling.

Target `npm` just preserves `require` statements which is essential when bundled with FuseBox or any other bundler. That's why we need to let it be

**Comment by eddow** [comment]
Okay, the problem then is when I try to make an npm package that is intended to be used browser-side.
When using the target "browser", requiring an external libraries does not generate a `require('external')` but just check out a cache ... that is empty.

**Comment by eddow** [comment]
Up - Do you plan to make it possible to bundle a client-side library or should I make a fork to publish on npm?
For now, you have 'end-product:server/client/universal' and 'library:server'
As I am developing some 'library:universal', if you refuse to bundle such, I will have to find another way to have my things bundled.

Could we have the team have a look onto that problem? I feel we are stuck here just the two of us.

**Comment by nchanged** [comment]
@eddow please read this one https://fuse-box.org/page/publishing-to-npm#publish-raw-typescript-package-recommended

You can also set target `npm` when publishing. It will be converted either to server/browser/universal upon bundling. To be clear if it's target npm on the actual npm, it doesn't mean that the result will be `target server`

Alternatively, publish typescrpit source or `ts:main` property in package.json like it's described in the guide. All your problems will be solved

**Comment by eddow** [comment]
Well, `ts:main` is a work around to avoid going through the bundling of the library - it is a way to **bypass** fuse-box.
I wish to use fuse-box to bundle the library - this is what I speak about, not bypassing it.
(beside,  `containedAPI` and `bakeApiIntoBundle` links are obsolete, as these options seem to no more exist on the Quantum page)

I didn't understand what you mean by " if it's target npm on the actual npm"

The function `isTargetServer` will return `true` if `this.optsTarget === "npm"` - this means what it means!
This will lead to the fact that, in the bundle, `isServer` and `isBrowser` will be replaced respectively by `true` and `false` instead of checking whether the `window` object exists or not => technically, `npm` => `server` and all the client-side functionalities (like using the CSS) are disabled.
As I make a library that uses CSS, using `target: 'npm'` removes the cSS and for now, I have to hack by having my users adding the CSS on my library in their programs.

**Comment by nchanged** [comment]
@eddow Ok, how about adding target `npm-server` `npm-browser` targets and avoid breaking changes. I will be happy to accept the PR if it doesn't break anything.

**Comment by eddow** [comment]
That would definitively be great, I'll do that
