### ISSUE TITLE
HMR does not run application entry point when using setStatefulModules()

### ISSUE THREAD

**Issue by koffmoff** [fuse-box/fuse-box#1302]
I'm customizing HMR like this:

```ts
import {setStatefulModules} from "fuse-box/modules/fuse-hmr"

setStatefulModules(moduleName => {
    // I'd like to specify it like this, but it does not seem to work. The module is reloaded,
    // but the main path is not executed.
    // return !/view/.test(moduleName)

    // Instead we have to list all stateful components explicitly (only stores for now)
    return /store/.test(moduleName)
})
```

I'd like to treat all modules except my views as stateful. So I'd like to use the commented away, negative condition. But when I use that, the module is replaced just fine upon HMR, but the main path is never executed. Hence nothing is updated.

**Comment by nchanged** [comment]
@koffmoff 
Please check this module [here](https://github.com/fuse-box/fuse-box/blob/master/src/modules/fuse-hmr/index.ts)
It might be easier to implement your own HMR logic which is described here [this](https://fuse-box.org/page/hmr#custom-hmr)

**Comment by koffmoff** [comment]
Thanks for the hint. Looking at the code was helpful. The default implementation flushes all *non* stateful modules and since my main module (index.tsx) was considered stateful, it wasn't flushed, and thus not executed again when reloaded.

This did it:

```ts
setStatefulModules(moduleName => {
    return !/view|index/.test(moduleName)
})
```
