### ISSUE TITLE
Ignore library/file in Quantum

### ISSUE THREAD

**Issue by ypopovych** [fuse-box/fuse-box#1311]
Hi,

I have a wasm library in my project. It's size almost 8mb. And Quantum crashes on the build with NodeJS memory exceptions. 

Can I somehow ignore this library in the Quantum (it optimized already)?

Thanks.

**Comment by nchanged** [comment]
I don't think you can ignore it, what you can is creating a separate bundle without running it through Quantum, and then lazy load it

Another option, of course is to increase nodejs memory limit (you can find it on Google)

**Comment by ypopovych** [comment]
Can I use the same fuse instance, or I should pack it into other, and then use packed JS?

**Comment by nalbion** [comment]
@ypopovych what if you ignored the module completely? #1314

**Comment by nchanged** [comment]
@ypopovych you can use the same instance, just create a different bundle

**Comment by ypopovych** [comment]
Can someone provide an example? Can't understand how to disable Quantum for the bundle. I can disable it only to all bundles in Fuse instance (by removing it from plugins).

**Comment by ypopovych** [comment]
Tried to import it as shim, but Quantum runs uglify on it :( And it crashes

**Comment by nchanged** [comment]
@ypopovych you can't disable Quantum on one package. It breaks consistency. Allocate more memory
```
node --max-old-space-size=8192 server.js  
```

**Comment by ypopovych** [comment]
Fixed for now by simply copying of this file with Sparky task, and importing it dynamically.
