### ISSUE TITLE
exclude package

### ISSUE THREAD

**Issue by nalbion** [fuse-box/fuse-box#1314]
I want to be build a package to deploy on Google Cloud Functions. My code imports `@google-cloud/datastore` which has _many_ transitive dependencies (as is typical for Node libraries), some of which have binary files, computed imports etc.

Because I'm compiling Typescript and using other libraries in my build/test/package/deploy process,  `node_modules` contains 100s-1000s of libraries, most of which aren't needed in production.

Ideally, I'd like to be able to build something that looked like:

- package.json - `{"main": "index.js", dependencies: { "@google-cloud/datastore": "1.4.1" }}`
- index.js - compiled from multiple TypeScript files in my project and most of the code I'm importing from  libraries and transitive dependencies
- node_modules - all of, but only the code that is not included in index.js but is required to run the app.

I've created a simple demo app to show what I'm trying to do:

https://github.com/nalbion/packaged-google-function/blob/master/lib/demo.js

To exclude `@google-cloud/datastore` and it's transitive dependencies from my compiled `demo.js` I've added a filterFile:

```javascript
filterFile: file => {
        return !['@google-cloud/datastore'].includes(file.collection.name);
    },
```

I'm confused by the lines in the output:

```javascript
FuseBox.pkg("@google-cloud/datastore", {}, function(___scope___){
return ___scope___.entry = "src/index.js";
});
```

Google Cloud Functions is also confused:

```
TypeError: Cannot read property 'default' of null
    at helloWorld (/user_code/demo.js:10:42)
```

For reference, the demo was working until I tried to add the datastore code:

https://github.com/nalbion/packaged-google-function/blob/no-dependencies/lib/demo.js

I suspect that `filterFile` is not intended for this purpose, or maybe I'm using it wrong. 
Is there an equivalent to filter packages?

**Comment by nchanged** [comment]
hi @nalbion 
Based on the output you are requiring something that doesn't exist. FuseBox wasn't able to resolve the package. 
Could you require a specific file from the package? It would help if you pasted some links

Besides, there is `ignoreModules` of FuseBox.init

**Comment by nalbion** [comment]
@nchanged I didn't see `ignoreModules` in the documentation, but it sounds like what I'm looking for.

I call `import Datastore from '@google-cloud/datastore';` and then `new Datastore({projectId: 'demo'});` in [src/gcf/demo.ts](https://github.com/nalbion/packaged-google-function/blob/master/src/gcf/demo.ts)

**Comment by nchanged** [comment]
@nalbion yep, it's not documented `ignoreModules`, the other option is to add it to instructions

```
instructions("- google-cloud")
```

**Comment by nchanged** [comment]
closing this for now
