### ISSUE TITLE
Merge fuse-box-contrib/fuse-box-ng-template-plugin into main repo

### ISSUE THREAD

**Issue by jpike88** [fuse-box/fuse-box#1316]
Due to this issue:

https://github.com/fuse-box-contrib/fuse-box-ng-template-plugin/issues/5

I think we should just pull this plugin into the repo so it doesn't pollute npm dependency versions.

**Comment by nchanged** [comment]
Let's wait for the author to respond, if not we can move it

**Comment by jpike88** [comment]
Never mind, he's updated it and made fuse box a peer dependency. thank god for that

![screen shot 2018-07-17 at 9 56 39 am](https://user-images.githubusercontent.com/9585787/42794182-b8ebaf9a-89a7-11e8-8c02-d0346e4c2910.png)
