### ISSUE TITLE
Tree shaking with ramda or lodash-es

### ISSUE THREAD

**Issue by LucasIcarus** [fuse-box/fuse-box#1319]
with `fuse.js`

```js
plugins: [
  UglifyJSPlugin({
    mangle: { toplevel: true },
    compress: { side_effects: false, pure_getters: true }
  }),
  QuantumPlugin({
    treeshake: true,
    uglify: true
   })
]

// other config is copied from examples/quantum-tree-shaking.
```

Compare the two samples below.

```ts
import { pathOr } from 'ramda'
console.log(pathOr);
```

`app.js` around 90+kb

```ts
import pathOr from 'ramda/es/pathOr'
console.log(pathOr);
```

`app.js` around 7.x kb

Comparing two output files without uglify

```js
  // ramda/es/index.js
  $fsx.f[2] = function(module,exports){
  Object.defineProperty(exports, '__esModule', { value: true });
  var F_1 = $fsx.r(3);
  exports.F = F_1.default;
  var T_1 = $fsx.r(7);
  exports.T = T_1.default;
  var __1 = $fsx.r(8);
  exports.__ = __1.default;
  var add_1 = $fsx.r(9);
  exports.add = add_1.default;
  // ... many other exports
```

```js
  // ramda/es/index.js
  $fsx.f[2] = function(module,exports){
  Object.defineProperty(exports, '__esModule', { value: true });
  var pathOr_1 = $fsx.r(249);
  exports.pathOr = pathOr_1.default;
  }
  // other files
```

It seems that shaking happens and uglify-js didn't remove the code which should be.

I pass some testing option to uglify-js through UglifyJSPlugin of fuse-box, but nothing changes.. 

lodash-es has almost same output. Any config I have missed?

**Comment by nchanged** [comment]
@LucasIcarus thanks for bringing this up. It's all my list to fix it. Treeshaking doesn't work with default exports ATM. I made this limitation due to the abuse of `default` usage back in the days. 

Please be patient ;-)

**Comment by LucasIcarus** [comment]
@nchanged  Thanks for the quick reply. 

Looking forward to the release of the new version.
