### ISSUE TITLE
CLI : executing fuse.js and fuse.ts

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#1321]
```bash
fuse dist
```

This command should try `fuse.js` and `fuse.ts` files - it  should execute them using `node` or `ts-node` commands (if available).

Obviously `fuse install` will do other things (as described on the command list), however, if a matching command wasn't found it should assume the described above.

**Comment by jorgebucaran** [comment]
@nchanged Where would one find the command list?
