### ISSUE TITLE
Source maps not found

### ISSUE THREAD

**Issue by mweiczorek** [fuse-box/fuse-box#1324]
Hi,

I have source maps enabled for a development build of Typescript/React. Whenever I change a file and the HMR reloads, I get the following errors:

[Chrome](https://pasteboard.co/HuUK6ST.png) - [Firefox Dev](https://pasteboard.co/HuUKXHc.png)

It appears as if it's attemping to load it from web root. My Code is as follows:

    const fuse = FuseBox.init({
        homeDir: './src',
        output: `${outputDir}/assets/dev/$name`,
        target: 'browser',
        log: false,
        cache: true,
        sourceMaps: {
        inline: false
        }
    });

----

    const devOptions = {
        root: false,
        port: devPort,
        httpServer: true
    };
    fuse.dev(devOptions, server => {
        const devRoot = path.resolve(outputDir);
        const devServer: Express.Application = server.httpServer.app;
        devServer.use("/assets/", Express.static(path.join(devRoot, "assets")));
        devServer.get("*", (req, res) => {
        res.sendFile(path.join(devRoot, "index.html"));
        });
    });

Using latest version (3.4.0)
Deleted node_modules and .fusebox directories

I honestly have no clue how to go about fixing this, the application runs fine otherwise, except that console.log calls are no longer mapped to the line of code where they were invoked.

**Comment by nchanged** [comment]
Thanks 
That's a known issue, HMR break sourcrmaps for a corresponding file. No fix available yet
