### ISSUE TITLE
Asset reference error

### ISSUE THREAD

**Issue by mybigman** [fuse-box/fuse-box#1325]
Hi Guys,

Using the Vue seed example, there appears to be a bug?

Using default or dist builds the following error is shown.

```
Errors for vendor bundle
  → ERROR Asset reference "components.css" has failed to resolve in module "default"
```

What looks to be happening is its baking the [S]CSS code into both the vendor bundle and app bundle whereas it should only go into the app bundle.

<pre>
Bundle "vendor"

    <b>components.css</b>
└──  (1 files,  644 Bytes) default
└── fuse-box-css@0.0.1 1.5 kB (0 files)
└── process@0.0.0 4 kB (0 files)
└── vue-hot-reload-api@2.3.0 6.3 kB (0 files)
└── vue-router@3.0.1 64.4 kB (0 files)
└── vue@2.5.16 207.3 kB (0 files)

Bundle "app"

    components/App.vue
    components/Config.vue
    components/Home.vue
    index.js
    components.css
└──  (5 files,  10.8 kB) default
└── events@0.0.0 9.8 kB (0 files)
└── fusebox-hot-reload@0.0.0 7.6 kB (0 files)
└── fusebox-websocket@0.0.0 2.9 kB (0 files)
</pre>

So the more [S]CSS code throughout the app the bigger and bigger both bundles become :/

Thanks.

PS. Great bundler though :)

**Comment by nchanged** [comment]
@mybigman thanks ;-)

You can use Quantum css option, it will extract all css into the filesystem.

That error is probably related to a scss file that couldn't be resolved.

**Comment by mybigman** [comment]
@nchanged  thanks for the reply.

Though I am not looking to extract the the scss out into a file.

All I have is this as a test.

```
<style lang="scss" scoped>
.container  {
  color: red;
}
</style>
```
The css is being inlined into the page without issues.

```
<style id="component.css" type="text/css">
.container[data-v-4d761a29] {
  color: red;
}</style>
```
The issue is caused by -
```
CSSPlugin({
  group: 'components.css',
  inject: 'components.css'
})
```
Obviously removing this solves the error but also removes the injection of the css. 

Bug or?

**Comment by nchanged** [comment]
@mybigman Remove all options from the CSSPlugin that's the legacy part, It will be removed after the next major release.

As I mentioned, let Quantum extract your CSS.

**Comment by mybigman** [comment]
@nchanged thank you sir it appears to all good now :)
