### ISSUE TITLE
Deployment to google app engine can't import fuse-box

### ISSUE THREAD

**Issue by janat08** [fuse-box/fuse-box#1326]
deploying express seed will result it fuse-box not found errors.

**Comment by nchanged** [comment]
You probably need to install fuse-box 😃

If it's not there you need to install it manually. I will close this issue because there is no issue 😃 you can reopen it but please provide a more specific description

**Comment by janat08** [comment]
express seed has fuse-box installed.

**Comment by nchanged** [comment]
Then something is wrong with your node env

**Comment by janat08** [comment]
it used node 8.

**Comment by janat08** [comment]
the standard offering only offers node 8.

**Comment by janat08** [comment]
Something is nutty about

**Comment by janat08** [comment]
App engine. These errors persised when i replaced fusebox entirely.

**Comment by janat08** [comment]
App engine. These errors persised when i replaced fusebox entirely.
