### ISSUE TITLE
CSSPlugin: cannot import same SCSS file from multiple other SCSS files??

### ISSUE THREAD

**Issue by iLLucionist** [fuse-box/fuse-box#1329]
So I'm building a ReactJS app completely modular.

in my `src/`, I have common `scss` files, particularly `vars.scss`.

In `src/ui/` I have a `jsx`-file and a `scss`-file for every component, e.g.:

```
Button.jsx
button.scss
Tabs.jsx
tabs.scss
Tab.jsx
tab.scss
TabButton.jsx
tabbutton.scss
```

All these component scss files need to reference variables and other common scss that is defined in common files. So all these `scss`-files have this line in them:

button.scss:
`@import '../styles/vars.scss';`

tabs.scss:
`@import '../styles/vars.scss';`

tabbutton.scss:
`@import '../styles/vars.scss';`

Etc.

All my `JSX`-files import the component-scss, e.g.:

Button.jsx:
`import './button.scss';`

Tabs.jsx:
`import './tabs.scss';`

TabButton.jsx:
`import './tabbuton.scss';`

Etc.

Now, for some reason, fuse-box seems to crash more often - literally 4 out of 5 times - than not when I am saving the `vars.scss` file, but not other files. I guess this has to do with how dependencies are resolved? I get the following error in the terminal from `node fuse`:

```
--------------------------
Bundle "app"

    App.jsx
    Inspector.jsx
    Mainbar.jsx
    Palette.jsx
    Sheets.jsx
    index.jsx
    styles/base.scss
    ui/Button.jsx
    ui/ButtonGroup.jsx
    ui/Tab.jsx
    ui/TabButton.jsx
    ui/Tabs.jsx
    ui/button.scss
    ui/buttongroup.scss
    ui/tab.scss
    ui/tabbutton.scss
    ui/tabs.scss
└──  (17 files,  11.9 kB) default
└── events@0.0.0 9.8 kB (0 files)
└── fbjs@0.8.17 14.6 kB (0 files)
└── fuse-box-css@0.0.1 1.5 kB (0 files)
└── fusebox-hot-reload@0.0.0 7.6 kB (0 files)
└── fusebox-websocket@0.0.0 2.9 kB (0 files)
└── object-assign@4.1.1 2.2 kB (0 files)
└── process@0.0.0 4 kB (0 files)
└── prop-types@15.6.2 4.1 kB (0 files)
└── react-dom@16.4.1 705.4 kB (0 files)
└── react@16.4.1 54.6 kB (0 files)
└── tslib@1.9.3 11.5 kB (0 files)
size: 830.1 kB in 24ms
19:24:59: Connection closed
19:24:59: Client connected
  → CSS Dependency: styles/vars.scss depends on ui/button.scss
19:25:01: Source changed for ui/button.scss
  → CSS Dependency: styles/vars.scss depends on ui/tabbutton.scss
19:25:01: Source changed for ui/tabbutton.scss
  → CSS Dependency: styles/vars.scss depends on ui/tabs.scss
19:25:01: Source changed for ui/tabs.scss
  → CSS Dependency: styles/vars.scss depends on styles/base.scss
19:25:01: Source changed for styles/base.scss
Error: not opened
    at WebSocket.send (/home/maximl/Projects/reacttest2/node_modules/ws/lib/WebSocket.js:219:16)
    at clients.forEach.client (/home/maximl/Projects/reacttest2/node_modules/fuse-box/devServer/SocketServer.js:47:20)
    at Set.forEach (<anonymous>)
    at SocketServer.send (/home/maximl/Projects/reacttest2/node_modules/fuse-box/devServer/SocketServer.js:46:22)
    at fuse.context.sourceChangedEmitter.on (/home/maximl/Projects/reacttest2/node_modules/fuse-box/core/Bundle.js:59:28)
    at listeners.forEach (/home/maximl/Projects/reacttest2/node_modules/fuse-box/EventEmitter.js:22:50)
    at Array.forEach (<anonymous>)
    at EventEmitter.emit (/home/maximl/Projects/reacttest2/node_modules/fuse-box/EventEmitter.js:22:28)
    at CSSPluginClass.emitHMR (/home/maximl/Projects/reacttest2/node_modules/fuse-box/plugins/stylesheet/CSSplugin.js:99:51)
    at CSSPluginClass.transform (/home/maximl/Projects/reacttest2/node_modules/fuse-box/plugins/stylesheet/CSSplugin.js:166:18
```

Console in the browser says:
`uncaught exception: Package not found fusebox-hot-reload`.

My `fuse.conf` is this:

```
const { src, task, exec, context } = require("fuse-box/sparky");

const {
    FuseBox,
    SassPlugin,
    CSSPlugin,
    CSSResourcePlugin,
    WebIndexPlugin,
} = require("fuse-box");

context(class {
    getConfig() {
        return FuseBox.init({
            homeDir : "src",
            target : 'browser',
            output : "dist/$name.js",
            cache: true,
            useTypescriptCompiler : true,
            allowSyntheticDefaultImports : false,
            plugins : [
                ["node_modules/**css",
                    CSSResourcePlugin({
                        dist: "dist/css-resources",
                    }),
                    CSSPlugin()
                ],
                [SassPlugin({ sourceMap: false }),
                    CSSResourcePlugin({ dist: "dist/css-resources" }),
                    CSSPlugin()],
                WebIndexPlugin({
                    template: "src/index.html"
                }),
            ],
            alias: {
            }
        })
    }
})

task("default", async context => {
    const fuse = context.getConfig();
    fuse.dev()
    fuse.bundle("app")
        .instructions("> index.jsx")
        .completed(proc => proc.start)
        .hmr({reload: true}).watch()
    await fuse.run();
});
```

**Comment by iLLucionist** [comment]
Great tip. Unfortunately, for me, it does not work.

**(1) I entered this into my `fuse.js` config:**

```
{
(...)

plugins { [
    (...)

    [SassPlugin({
        sourceMap: false,
        header: `@import "src/styles/vars";`
    }),
        CSSResourcePlugin({ dist: "dist/css-resources" }),
        CSSPlugin)],
    (...)
] ),

(...)
}
```

**(2) I ensured that I did not manually import:**

```
$ ~/{project_root}/grep -Rnw --exclude-dir={\.*, node_modules\*} -e '@import`

Binary file .fuse.js.swp matches
fuse.js:29:                    header: `@import "src/styles/vars";`
src/styles/base.scss:1:// @import './vars';
src/ui/button.scss:1:// @import '../styles/vars.scss';
src/ui/tabbutton.scss:1:// @import '../styles/vars.scss';
src/ui/tabs.scss:1:// @import '../styles/vars.scss';
```

I then manually commented out every import of `vars.scss` in these files.

**(3) The same issue I described in my previous report happened again:**

- I can save any `scss`-file _except_ `vars.scss`.
- When I save `vars.scss`, I get the `CSS Dependency (...) depends on` message recursively for every file that references `vars.scss` and the browser no longer refreshes. The console also reads `Connection closed`.
- When I then save a `scss`-file that references `vars.scss`, the error occurs that ends at `CSSPluginClass.transform` as I've described in my previous report.

Arguably, `header` accomplishes the exact same thing I was doing manually. Instead of adding the `@import 'vars.scss'` in all source files separately, the `SassPlugin` does it for me, leading the the same behavior.

**(4) A bug or a sass 'mis'-feature?**

It's weird, because I always thought that you should DRY as much as possible and program as modular as possible. Anyways, it seems that SASS generally can't handle **duplicate imports**:

https://github.com/webpack-contrib/sass-loader/issues/145

Apparently, there is a `node-sass` plugin/extension aimed to deal with this:

https://github.com/at-import/node-sass-import-once

Perhaps in future versions of fuse-box this could be integrated?

**(5) Perhaps CSS partials? --> Doesn't work as of now**

Finally, the SASS-docs themselves read:

> You can create partial Sass files that contain little snippets of CSS that you can include in other Sass files. This is a great way to modularize your CSS and help keep things easier to maintain. A partial is simply a Sass file named with a leading underscore. You might name it something like _partial.scss. The underscore lets Sass know that the file is only a partial file and that it should not be generated into a CSS file. Sass partials are used with the @import directive.

https://sass-lang.com/guide

I have tried this by moving `vars.scss` to `_vars.scss` and updating my `fuse.js`-config accordingly (e.g., `header: "@import "src/styles/_vars";`), but this results in the same errors and behavior as describe above.

I thought.. well, maybe it's how `SASSPlugin` processes files, which may be different from `node-sass` in some regards. So I removed `header` from `SASSPlugin`-config, manually set all imports to `_vars`. But then fuse-box crashes immediately with the same errors and behaviors as described above.

**(6) Solution**

I am not sure how to proceed. I want my css/sass to be modular, but I can't have it that way now apparently. Perhaps I should look into PostCSS. For know, I'll just have one separate collection of sass-files and not rely on fuse-box do handle the processing of sass using `import`-statements in my `JSX`-files.

I now have the old-school `base.scss` which just imports everything, e.g.:

```
@import './vars';
@import './button';
@import './buttongroup';
@import './tabs';
@import './tab';
@import './tabbutton';
```

And then I only import `base.scss` in my main JSX-file `App.jsx`:

`import './styles/base.scss';`

Now, performance-wise, I don't think this will be a great deal because my React-app is UI-heavy and probably all ui-components that I am building will be used in basically every view/route in React. But I hope to re-use my ui component library in the future and I do not want to have to manually check which ui-components I did use and which I didn't (e.g., a normal website will probably not need tabs, only web apps).

I suspect somehow the way fuse-box handles `import`-statements conflicts with how `node-sass` treats `@import`-statements. Because it seems that both try to do dependency resolution separately and that might interfere.

I am under the impression that somehow the `CSSPlugin` crashes __after__ fuse-box did the dependency resolution, because I STILL get the `CSS depends on...` message now that I have one `base.scss` message:

```
  → CSS Dependency: styles/vars.scss depends on styles/base.scss
  13:13:50: Source changed for styles/base.scss
```

Previously, `CSSPlugin` seems to crash whole fuse-box __after__ this output.

Sorry for my verbosity / long post. I always like to be thorough with documentation and debugging.

**Comment by iLLucionist** [comment]
@nchanged I have tried what you have suggested and it results to the same behavior and errors.

I changed `header` for `SASSPlugin` to:

```
(...)

header: '@import "/home/illucionist/Projects/reactui/src/styles/vars";',

(...)
```

In my JSX-files, I import as follows, for example `Tab.jsx`:

`import `./tab.scss';`

In each SCSS-file, I do NOT import `vars.scss`.

I still think there may be two potential sources of error:

1. SASS cannot handle multiple imports of the same file (which is still happening, but with an absolute path instead of a relative path), but then why does fuse-box crash?

2. Fuse-box's dependency resolution in `JS|TS|JSX`-files of the `import`-statement conflicts with how the SASS/CSS-plugin handles multiple references to the same file.

**Comment by nchanged** [comment]
@iLLucionist yep, I've been thinking about having a plugin that combines the functionality of all CSS plugins + could have one Sass entry point regardless of how many times you import a CSS files from in the code.  Can you apply a workaround in the meantime?

**Comment by iLLucionist** [comment]
@nchanged That's a great idea. I don't have spare resources to modify the plugins myself, but I think that what I do manually (reference the `vars.scss` file one time in `base.scss`):

1. Build `JS|JSX|TS`-dependency map:
2. Reduce `JS|JSX|TS`-dependency map, have a `duplicate`-flag (these files imported first, as other files rely on them).
3. Extract `@imports` from the reduced `JS|JSX|TS`-dependency map.
4. Reduce `SCSS`-dependency map, keep duplicate flag (again, these files imported first, as other files rely on them).
5. Construct complete dependency map.
6. Put duplicate imports first, then unique imports. Give `SCSS` duplicate imports precedence over `JS|JSX|TS` duplicate imports.
7. Create a `imports.scss` import map and feed that to `node-sass`.


```
.JSX-files

-> Main.JSX:

import Tabs from './Tabs.JSX';
import Modal from './Modal.JSX';

-> Tabs.JSX:

import './panel.scss';
import './tabs.scss';

-> Modal.JSX:

import './panel.scss';
import './modal.scss';

.SCSS-files:

-> panel.scss:

import './base';
import './vars';

-> tabs.scss:

import './base';
import './vars';

-> modal.scss:

import './base';
import './vars';
```

**Step 1: Initial `JS|JSX|TS`-dependency map:**

```
SCSS-files from JS|JSX|TS:

Main.JSX -> Tabs.JSX -> panel.scss
Main.JSX -> Tabs.JSX -> tabs.scss
Main.JSX -> Modal.JSX -> panel.scss
Main.JSX -> Modal.JSX -> modal.scss
```

**Step 2: Initial Reduce of `JS|JSX|TS`-dependency map:**

```
SCSS-files from JS|JSX|TS:

Main.JSX -> Tabs.JSX -> panel.scss; duplicate: true
Main.JSX -> Tabs.JSX -> tabs.scss; duplicate: false
Main.JSX -> Modal.JSX -> modal.scss; duplicate: false

```

**Step 3: Extract `@imports` using regex in `SCSS`-files:**

```
-> Main.JSX -> Tabs.JSX -> panel.scss

import './base';
import './vars';

-> Main.JSX -> Tabs.JSX -> tabs.scss

import './base';
import './vars';

-> Main.JSX -> Modal.JSX -> modal.scss

import './base';
import './vars';

```

**Step 4: Initial Reduce of `SCSS`-dependency map:**

```
import './base'; duplicate: true
import './vars'; duplicate: true
```

**Step 5: Complete reduced `SCSS-dependency` map:**

```

From JS|JSX|TS:

panel.scss; duplicate: true
tabs.scss; duplicate: false
modal.scss; duplicate: false

From SCSS:

base.scss; duplicate: true
vars.scss; duplicate: true

```

**Step 6: Put duplicate imports first, then unique imports:**

Give precedence to duplicate imports from `SCSS` over `JS|JSX|TX`-imports.


```
-> Duplicate from SCSS
base.scss
vars.scss

-> Duplicate from JS|JSX|TS
panel.scss

-> UNIQUE
tabs.scss
modal.scss
```

**Step 7: Create one `base.scss` files with dependency import map and feed that to `node-sass`:**

```
@import('base');
@import('vars');
@import('panel');
@import('tabs');
@import('moda');
```

I think this would really be a nice feature to have in fuse-box as it REALLY lifts concerns off of the developer, as fuse-box aims to do versus webpack. I found fuse-box WAY MORE intuitive to set up than webpack. This would be a great feature where developers "do not have to think" about these kind of issues.. "it just works".

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
