### ISSUE TITLE
Detection of dependencies like Parcel

### ISSUE THREAD

**Issue by Kompwu** [fuse-box/fuse-box#1332]
it gets heavy with all these dependencies, sometimes never used. I think we should do like Parcel, it seems handy and it keeps everything light.

**Comment by nchanged** [comment]
There is a minimum set of dependencies. For example, if you need Sass, you install it separately.

**Comment by Kompwu** [comment]
@nchanged Parcel does things in a more automated way ;)

**Comment by nchanged** [comment]
Well. then leave your suggestions. For all I know parcel doesn't provide as flexible configuration as parcel. I mean no configuration at all xD

**Comment by nchanged** [comment]
closing this for now, as it's not on the priority list
