### ISSUE TITLE
Webpack plugin "VersionFilePlugin" alternative on FuseBox

### ISSUE THREAD

**Issue by Kompwu** [fuse-box/fuse-box#1334]
How can I mimic this on FuseBox?

**Comment by nchanged** [comment]
so what does it do?

**Comment by Kompwu** [comment]
@nchanged something like that:
```js
function createManifest(log) {
  let manifest = JSON.parse(fs.readFileSync(dir.manifest, 'utf8'));
  let pkg = JSON.parse(fs.readFileSync(dir.package, 'utf8'));
  manifest['name'] = pkg['displayName'];
  manifest['version'] = pkg['version'];
  manifest['description'] = pkg['description'];
  if (fs.existsSync(dir.distManifest)) fs.unlinkSync(dir.distManifest);
  fs.writeFileSync(dir.distManifest, JSON.stringify(manifest));
  if (log) console.info('manifest: created');
}
```
BTW, i have cache issues on `manifest` & `pkg` i tryed to force reload them with `fs.readFileSync` but it fails.

**Comment by nchanged** [comment]
We can add it Quantum Manifest that's easier and more consistent

**Comment by Kompwu** [comment]
@nchanged How ? 🤔

**Comment by nchanged** [comment]
we would need to introduce `version` in FuseBox.init that would write the number into manifest.json with Quantum

**Comment by Kompwu** [comment]
@nchanged what about crx ?

**Comment by Kompwu** [comment]
@nchanged What about `crx` ?

**Comment by nchanged** [comment]
sorry?

**Comment by nchanged** [comment]
Closing this one for now since your can do that using `process.env` and Quantum at build time.
