### ISSUE TITLE
Package not found process / watcher doesn't recover

### ISSUE THREAD

**Issue by sod** [fuse-box/fuse-box#1335]
Followup to https://github.com/fuse-box/fuse-box/issues/585 but with a reproduction:

Repro repo: https://github.com/sod/fuse-box-watcher-issue
Fuse-box version: 3.4.0

Issue: If I have a syntax error in any `.vue` file, the watcher breaks. If I fix the syntax error, the watcher doesn't recover. I have to restart it.

### Reproduction

```bash
git clone https://github.com/sod/fuse-box-watcher-issue
cd fuse-box-watcher-issue
npm install
npm start # starts watcher and opens browser on localhost:4444
```

### 1. Change line 8 in `src/component/my-component.vue` from

```typescript
export default {
```

to

```typescript
/export default {
```

you see this syntax error in the terminal:

```log
Acorn error: Unexpected token (7:1)
File: /Users/avweiss/dev/playground/fuse-box-watcher-issue/src/component/my-component.vue

5          staticRenderFns: []
6        })
7  /export default {;
8  ;
9
10  Object.assign(exports.default.options||exports.default, _options)
11  var process = FuseBox.import('process');
```

### 2. Change the line back

 watcher doesn't recover. Error in browser console on http://localhost:4444 reads:

```log
Package not found process
```

If you stop the watcher and restart via `npm start` it works again.

**Comment by nchanged** [comment]
Thanks, Will look into it

**Comment by sod** [comment]
I could pin down the issue.

When the build fails, there is a rejecting promise inside `pendingPromises` in `WorkflowContext`. So every time [`WorkflowContext.resolve`](https://github.com/fuse-box/fuse-box/blob/master/src/core/WorkflowContext.ts#L217-L221) runs:

```typescript
    public resolve() {
        return Promise.all(this.pendingPromises).then(() => {
            this.pendingPromises = [];
        });
    }
```

The `this.pendingPromises = [];` is never executed, as the rejection also causes the Promise.all to reject.

I could fix this issue by adding a catch to resolve method:

```typescript
        return Promise.all(this.pendingPromises).catch(() => undefined).then(() => {
            this.pendingPromises = [];
        });
```

I could also fix it another way, by wiping pendingPromises in [`nukeCache`](https://github.com/fuse-box/fuse-box/blob/master/src/core/WorkflowContext.ts#L325-L331):

```typescript
    public nukeCache() {
        this.resetNodeModules();
        this.pendingPromises = []; // <-- added this
        if (this.cache) {
            removeFolder(this.cache.cacheFolder);
            this.cache.initialize();
        }
    }
```

Not really sure what the right approach or sideeffects are.
