### ISSUE TITLE
Code formatter

### ISSUE THREAD

**Issue by merlinnot** [fuse-box/fuse-box#1342]
Hi, what do you think about using [Prettier](https://prettier.io) as a code formatter?

I'd be happy to make a PR.

**Comment by nchanged** [comment]
Hey 😃 if you take a look at the commits I just did it today 😃 applied it to all the modules and created editorconfig file too

**Comment by merlinnot** [comment]
Wow that timing. Can't see it in devDependencies tho, is it in master?

Then I could:
- add a precommit hook to make sure formatting is on par (Husky + lint-staged)
- add scripts for validating and fixing to `package.json`
- add validation to the CI pipeline
- enable it for Markdown files too

**Comment by nchanged** [comment]
I think a precommit hook would work! Just let's make sure it's locked to `src/**/**.ts`
Let's not touch the markdown files just yet. I made a big mistake going for my own solution with md parsing.  Maybe you have something in mind that could generate beautiful static docs? Last time I checked - didn't like anything ;-(

**Comment by merlinnot** [comment]
Quite some projects (including Prettier) are using [Docosaurus[(https://docusaurus.io).
