### ISSUE TITLE
More modern CI/CD

### ISSUE THREAD

**Issue by merlinnot** [fuse-box/fuse-box#1343]
Hi, what do you think about refining the CI/CD configuration a bit to speed up the builds, add automatic deployments of tagged releases and adding all of the required steps (linter, formatter, ...)?

I have quite a lot of experience with a variety (>10) of CI/CD systems and Travis falls behind. I could especially recommend:
- [Buddy](https://buddy.works)
- [CircleCI](https://circleci.com)

Let me know what you think, I'd be happy to make a PR.

**Comment by nchanged** [comment]
I would love to have automatic releases!!! Please suggest something!

**Comment by merlinnot** [comment]
Nice, would you rather go with a more well-established (CircleCI) or cutting-edge (Buddy)?

**Comment by jpike88** [comment]
I'd vote for CircleCI

**Comment by nchanged** [comment]
all there =)
