### ISSUE TITLE
typescript helpers __decorate vs __decorator

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#135]
Hi, in your helper you make available __decorator .. while typescript emits __deocrate. Is that on purpose? thanks!

**Comment by nchanged** [comment]
Hi! FuseBox overrides default [__decorate](https://github.com/fuse-box/fuse-box/blob/master/assets/libs/fuse-typescript-helpers/__decorate.js) 

[Here](https://github.com/fuse-box/fuse-box/blob/master/src/plugins/TypeScriptHelpers.ts#L78) it is patching it, and replaces with FuseBox's

**Comment by tomitrescak** [comment]
Hmm, then something is fishy, as my fusebox bundled app is complaining that __decorate does not exist:

```
Uncaught ReferenceError: __decorate is not defined
```

**Comment by nchanged** [comment]
did you add typescriptHelpers?

**Comment by tomitrescak** [comment]
Yes I did, all other helpers work excepr for __decorate :/

**Comment by nchanged** [comment]
Hm... I have actually seen this bug once, but was not able to find the nature of it. If you could suggest a fix?! Or at least find a reason?

**Comment by devmondo** [comment]
@nchanged it is related to caching or `IDE` race condition we tested together, i see it a lot with `WebStorm`

**Comment by unlight** [comment]
Actually, typescriptHelpers is obsolete since TypeScript 2.1
https://github.com/Microsoft/tslib

**Comment by devmondo** [comment]
@unlight  good point!

**Comment by nchanged** [comment]
Guys, what's the status of this issue?

**Comment by devmondo** [comment]
@nchanged  perosnallly i include `TSHelpers` plugin, but TS 2.1 should work on its own!

**Comment by tomitrescak** [comment]
To me, the tshelper plugin does not work due to race condition issues, I switched to native 2.1 solution with tslib. I can close this.

**Comment by nchanged** [comment]
Thanks, but we need to create another issue, related to that
