### ISSUE TITLE
Hosting for the website

### ISSUE THREAD

**Issue by merlinnot** [fuse-box/fuse-box#1352]
We should consider other options rather than an nginx server for website hosting. I was researching this topic quite recently and the best solution I can think of would be to use Firebase Hosting for production and Netlify for staging.

Firebase has the [best performance](https://portal.cedexis.com/ui/reports/share/s5lq5rhclb4?primaryDimension=platform&time=last_30_days&source=community&ipSource=client&statistic=percentile_50&probeType=0&group0Sort=percentile_50&group0Order=asc&vis.group0Sort=percentile_50&vis.group0Order=asc&table.group0Limit=10&table.group0Sort=percentile_50&table.group0Order=asc&vis.group1Limit=5&vis.group1Sort=percentile_50&vis.group1Order=asc&table.group1Limit=10&table.group1Sort=percentile_50&table.group1Order=asc&vis.platform%5B%5D=33381&vis.platform%5B%5D=32431&vis.platform%5B%5D=20367&vis.platform%5B%5D=29&vis.platform%5B%5D=17653&timeScale=&bqBackend=&dumbo=&platform%5B%5D=33381&platform%5B%5D=32431&platform%5B%5D=20367&platform%5B%5D=29&platform%5B%5D=17653) out of all CDNs.

Netlify makes a deployment and adds a link for every PR, so it's very easy to click through all of the changes.

**Comment by nchanged** [comment]
Well, if had millions of hits per day then probably yes ;-) My own server would work as fine ;-) (the current one)

**Comment by merlinnot** [comment]
It's important for positioning in Google and visitors from other continents. It's free and comes with a managed SSL certificate (Let's Encrypt).

**Comment by nchanged** [comment]
Ahhh! ok, got it ;-)

**Comment by merlinnot** [comment]
Landed!
