### ISSUE TITLE
Development mode sticking _1 after imports

### ISSUE THREAD

**Issue by jpike88** [fuse-box/fuse-box#1354]
Is it possible to eliminate the _1, and have class names on import etc start as foo, then any dupes be called foo_1, foo_2 etc? I'll make a PR if I'm on the mark with it. It's driving me nuts trying to paste variable names into console and add _1 each time

**Comment by nchanged** [comment]
@jpike88 that's typescript ;-)

**Comment by jpike88** [comment]
Can we override it in any way?

**Comment by nchanged** [comment]
@jpike88 nope we can't... Sorry, not without breaking the sourcemaps
