### ISSUE TITLE
Cypress support

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#1359]
Dear, as you know I love your work. Recently we also fell in love with [Cypress](https://www.cypress.io/how-it-works/) an E2E testing environment. It would be really awesome if we could support FuseBox there. There is a webpack and parcel preprocessor that are supported by cypress. https://github.com/cypress-io/cypress-parcel-preprocessor 

I tried to take it myseld but I do not see into fuse-box API that much. Can you maybe point me to where to start? There is a "per-file" bundling that I do not know how to take.

**Comment by nchanged** [comment]
@tomitrescak that's looking nice. I will gladly help you. Can you provide the requirements?!

What's a pre-fie bundling?

**Comment by vegarringdal** [comment]
Cypress looks very nice

**Comment by jpike88** [comment]
I've been using Cypress for a month or so now on fuse-box development builds, it is awesome. But I'm having trouble seeing what advantages tying Cypress to fuse-box would entail. You mean you just want to chain a fuse.dev() command before you start your cypress tests?

**Comment by nchanged** [comment]
@jpike88 do you mind sharing the setup?

**Comment by tomitrescak** [comment]
Guys, truth be told, we do not need FuseBox. I thought that cypress is capable of preparing a bundle that it will test, which it is not. For typescript compilation, Webpack and Parcel worked just fine. There is no need for separate bundler as of this point. If you agree I can close this issue.
