### ISSUE TITLE
Missings and bugs features in version 3.4.0

### ISSUE THREAD

**Issue by TrungRueta** [fuse-box/fuse-box#1361]
Hi FuseBox team and everyone!

I tried to use fuse-box in my new project (vue) and veryhappy about speed and easy to setup. But i found that we still have some problem with plugins:

- Missing plugin allow create json file contains file url after compiled. In webpack they has https://www.npmjs.com/package/assets-webpack-plugin allow render. So many project who want to manual grab files asset by server can read this file. For now i use WebIndexPlugin fusebox to create html file then include into template framework by fs.readFileSync.

- Vue component plugin: Plugin work verynice. i even not use babel anymore, only typescript to transpile, but it has problem. Vue 2.5.0 with Vue-Loader support functional component, in our plugin it not work. If i add `functional` word to `<template` it no affect, component still be normal. If i add `functional: true` into script object component, it will failed in render . this error is 100%

- Babel plugin: babel plugin still reference to babel 6 whichs old, Now we had babel 7 with better speed and coding. Please update it soon.

Please take a look and give me a suggest to work around problems. Because i found more than 1 issue so i want group them here we can talk better

**Comment by nchanged** [comment]
@TrungRueta Hi
Glad to hear that ;-)
1) https://fuse-box.org/page/copy-plugin that's your plugin here ;-)
2) Could you take a look at the code and maybe submit a PR? A guy who initially developed it is gone now, I am trying my best to fix stuff there, but I don't have enough experience with Vue
3) Something easily doable? Can you help?

**Comment by TrungRueta** [comment]
hi @nchanged. So happy when you handle plugin while author gone. Will be sad if we lost support one of most powerful framework like Vue in Wonderful flow develop tool like Fusebox. I really love Fusebox because very easy to setup and speed god-like :)

Thank you to suggest issue 1 i will try and response if  have any idea. About idea 3 i have not any exp to play on babel, only use it before in webpack to do projects so i can help much. We maybe need author's plugin :( 

About issue 2: 
I afraid to have to say that i have very lack expr about github because almost time i must work in company ( i just normal dev ) so never try support opensource projects via Github before... but i still try my best to support you about this. I spend hours after read your reply and research code from `VueComponentPlugin` and `vue-loader` and read documents i found. Now this is what we need to modify to open `functional` features in one-file component like `vue-loader`:

***document*** 
- Office Vue document about functional component: https://vuejs.org/v2/guide/render-function.html#Functional-Components
@yyx990803 explaines every detail about `functional` features. Please attention section about replace `this` codes to `context` code.
- functional vue component on-fly (idea) : 
https://medium.com/@denny.headrick/templates-for-vue-functional-components-on-the-fly-fa1cd8707f26
author **Denny Headrick** in topic told about functional word in `<template function...` one-file template will not work without `vue-loader` and he suggest way to build vue component register function which render functional component. Please see first function he show, he replace some parts inside render function. His idea is replace `this` parts to `ctx` or context because `functional` component without this.
- *vue-loader* main code: https://github.com/vuejs/vue-loader/blob/master/lib/index.js
attention line 93: detect component is functional or not
```
const hasFunctional = descriptor.template && descriptor.template.attrs.functional
```
then `hasFunctional (Boolean)` passed to function line 148:
```
var component = normalizer(
  script,
  render,
  staticRenderFns,
  ${hasFunctional ? `true` : `false`},
  ${/injectStyles/.test(stylesCode) ? `injectStyles` : `null`},
  ${hasScoped ? JSON.stringify(id) : `null`},
  ${isServer ? JSON.stringify(hash(request)) : `null`}
  ${isShadow ? `,true` : ``}
)
```
line 169: pass detect functional to function render hot reload code:
```
if (needsHotReload) {
  code += `\n` + genHotReloadCode(id, hasFunctional, templateRequest)
}
```
- *vue-loader* normalizer function: https://github.com/vuejs/vue-loader/blob/master/lib/runtime/componentNormalizer.js
line 30: author add `functional: true` to `options (component object)` (see office document)
```
// functional template
if (functionalTemplate) {
  options.functional = true
}
```
- *vue-loader* hot-reload function: https://github.com/vuejs/vue-loader/blob/master/lib/codegen/hotReload.js
line 25: choose between `rerender` for functional components and `reload` for rest. Please see office doc about hot reload plugin with example here: https://github.com/vuejs/vue-hot-reload-api
```
api.${functional ? 'rerender' : 'reload'}('${id}', component.options)
```

Above is documents i research it is important to edit fuse-box plugins. Now is how i modify plugin
- *Vue Template class*: Follow idea of *Denny* we need modify `render function`, please see line 4 `toFunction` function:
```
private toFunction(code) {
  const vueTranspiler = require("vue-template-es2015-compiler");
  return vueTranspiler(`function render () {${code}}`);
}
```
we need modify string function after transpiled:
```
toFunction(code) {
  const vueTranspiler = require("vue-template-es2015-compiler");
  const codeTranspiled = vueTranspiler(`function render () {${code}}`);
  
  // fix: modify context render function so it can render functional.
  if (this.block.attrs.functional) {
      const functionalCode = codeTranspiled
      // create render 
      .replace('function render ()', 'function render (createElement, context)')
      // replace this with context
      .replace(
          'var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h', 
          'var _vm = context;var _h = createElement;var _c = createElement'
      )
      // replace slot
      .replace(
          '_vm._t("default")',
          '_vm.children'
      )
      ;
      return functionalCode
  }
  return codeTranspiled;
}
```
First replace is use createElement and context from render function follow office Vue doc:
`function render ()` to `function render (createElement, context)`
second replace After transpiled plugin add variables helper:
```
var _vm=this;
var _h=_vm.$createElement;
var _c=_vm._self._c||_h
```
we need replace to :
```
var _vm = context;
var _h = createElement;
var _c = createElement
```
Third replace is modify $slot functions to children (please see office Vue document section functional - slot vs children).

line 31: 
```
return `Object.assign(_options, {
  _scopeId: ${this.scopeId ? JSON.stringify(this.scopeId) : null},
  render: ${this.toFunction(compiled.render)},
  staticRenderFns: [${compiled.staticRenderFns.map(t => this.toFunction(t)).join(",")}]
})`;
```
render options (component object) here we need add prop `functional: true` to help mark this component is functional:
```
return `Object.assign(_options, {
  _scopeId: ${this.scopeId ? JSON.stringify(this.scopeId) : null},
  render: ${this.toFunction(compiled.render,)},
  staticRenderFns: [${compiled.staticRenderFns.map((t) => this.toFunction(t)).join(',')}],
  ${this.block.attrs.functional ? 'functional: true' : ''}
```

Here we had functional open. To use just need add `functional` word into `<template>` like `<template functional>. to make hot-reload i tried to modify more but still not luck for now

- *vue plugin main file*: https://github.com/fuse-box/fuse-box/blob/master/src/plugins/vue/VuePlugin.ts
hot reload require modify follow code *vue-loader* https://github.com/vuejs/vue-loader/blob/master/lib/codegen/hotReload.js line 25:
```
api.${functional ? 'rerender' : 'reload'}('${id}', component.options)
```
here in *VuePlugin.js* file we replace code of `bundleEnd(context)`:
```
if (!isComponentStyling) {
  var component = FuseBox.import(fusePath).default;
  var uniqueId = component._vueModuleId||component.options._vueModuleId;

  // hack: detect if vue is functional component
  var apiFunc = component.functional === true
      ? api.reload(uniqueId, component)
      : api.reload(uniqueId, component);
}
```

***Todo things***
Although code work, but still have some issues not work yet i list here maybe you and @yyx990803 take alook and help complete it :(

- Replace render function path still follow office vue document, we still need replace codes such as : attr, listener and events. Because i not use it in functional component so i lack of case to test.
- hot-reload section not work. If edit comonents wrapper of functional component it update values, but if edit template of functional component it not work but no throw any eror. I lack exp to hot-reload so i can not go depper.

Again, Thank you Fuse-box and @yyx990803 created amazone tools for world! Thank @nchanged spend time to support fusebox. I hope i can give some small help to you guys.

**Comment by nchanged** [comment]
@TrungRueta It's quite easy to try it with a dev build. [Try it](https://github.com/fuse-box/fuse-box/blob/master/CONTRIBUTING.md#-local-development)

From the looks of it, you understand what you are doing =) Please try! The whole community is based on people who help!

**Comment by nchanged** [comment]
Please upgrade to the [major version](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)
