### ISSUE TITLE
run dist then exit

### ISSUE THREAD

**Issue by valepu** [fuse-box/fuse-box#1362]
Greetings,
I want to create a task that builds my application and then stops. In my fuse.js file  i have this task

```
task("dist", ["clean"], async context => {
  context.isProduction = true;
  const fuse = context.getConfig();
  fuse.dev(); // remove it later
  context.createBundle(fuse);
  await fuse.run();
});
```

Which builds the project but then opens a server (so the process does not stop)

**Comment by nchanged** [comment]
@valepu Greeting, do you see the line in your code

```
 fuse.dev(); // remove it later
```
So, remove it later, or now ;-)

**Comment by valepu** [comment]
If i remove 
`fuse.dev(); `

I don't get the server (if i got to localhost:3000 i get no answer) but the task doesn't end, it just hangs. On the console i see "[20:57:33] Resolved 'dist' after 23s 400ms" and the files are built correctly in the dist folder but i don't get back to my console prompt

**Comment by nchanged** [comment]
@valepu please read carefully the documentation. You probably have a watcher enabled.
