### ISSUE TITLE
fuse-box can't find css chunks generated by QuantumPlugin "css: true"

### ISSUE THREAD

**Issue by sod** [fuse-box/fuse-box#1363]
Version: Fuse-Box 3.5.0-next.11

The issue seems not to relate to the vue plugin. But I left it in the reproduction for good measure and added a javascript chunk reproduction.

Reproduction:

```bash
git clone git@github.com:sod/fuse-box-vue-css-issue.git
npm install
node fuse.js production
```

Simplified, the import chain looks something like:
```javascript
// app.js
import('LazyJavascript.js') // lazy import test with javascript
import('LazyVue.vue') // lazy import test with vue plugin

// LazyJavascript.js
import 'LazyCss.css';

// LazyVue.vue
<style>.LazyVue {}</style>
```

These are the files that fuse-box creates:
```bash
➜  fuse-box-vue-css-issue git:(master) ll dist
total 56
-rw-r--r--  1 avweiss  staff   192B 27 Aug 14:10 1dae24fd-402ac6e6.js
-rw-r--r--  1 avweiss  staff    41B 27 Aug 14:10 2b281f12-c5ce912c.css   # css from lazy chunk 1 
-rw-r--r--  1 avweiss  staff    33B 27 Aug 14:10 79c13975-styles.css     # global css 
-rw-r--r--  1 avweiss  staff   2,7K 27 Aug 14:10 80cdde38-app.js
-rw-r--r--  1 avweiss  staff    31B 27 Aug 14:10 84dd5197-402ac6e6.css   # css from lazy chunk 2
-rw-r--r--  1 avweiss  staff   116B 27 Aug 14:10 c5c74b24-c5ce912c.js
-rw-r--r--  1 avweiss  staff   492B 27 Aug 14:10 index.html
```

But this is what fuse-box runtime tries to load:
![image](https://user-images.githubusercontent.com/905328/44659205-ada9a480-aa03-11e8-8d60-2e5b2668fa1b.png)

Thats only the second part of the file name in:
```bash
2b281f12-c5ce912c.css <- real filename
         ^^^^^^^^^^^^ <- requested part of the filename

Terminal fuse-box output for that chunk:
  → CSS: Grouping inlined css default/LazyDependencies/LazyJavaScriptCssDependency.css into c5ce912c.css
  → CSS: Using "clean-css" module to optimise CSS
  → CSS: Successfully optimised
  → Uglifying app...
  → Using uglify-es because the target is greater than ES5 or es6 option is set
  → Done uglifying app
  size:  2.7 kB, 1.2 kB (gzipped)
```

**Comment by nchanged** [comment]
I think it has been fixed already. fuse-box@3.5.0-next.11

I just forgot to release ;-)

**Comment by sod** [comment]
fuse-box@3.5.0-next.10 included everything that was in master. The only extra commit added unit tests, but no extra functionality.

And updating the reproduction repo to 3.5.0-next.11 didn't change the behavior.

**Comment by sod** [comment]
Seems like the writeBundle method just uses the quantum bit name (the name of the lazy javascript chunk?) and appends css

![image](https://user-images.githubusercontent.com/905328/44714408-81e6f700-aab5-11e8-91f8-cbdd806f47ff.png)

But the css writer wrote the data to the disc and prefixed it with the content hash.

And indeed, if I disable the hashing in the build (`hash: false` inside `FuseBox.init({...})`), the prod build works.

So the bundler currently doesn't take content hashing filename of the css chunks into account?

**Comment by nchanged** [comment]
@sod gothcha

**Comment by nchanged** [comment]
[code-splitting.zip](https://github.com/fuse-box/fuse-box/files/2329058/code-splitting.zip)
I am not sure I can reproduce it, please check out the archive

**Comment by nchanged** [comment]
Oh yeah, I got it know =)

**Comment by nchanged** [comment]
`fuse-box@3.5.0-next.12` please verify it here

**Comment by sod** [comment]
<img width="189" alt="image" src="https://user-images.githubusercontent.com/905328/44738785-44568e00-aaf6-11e8-9650-36ac903e96a0.png">

**Comment by sod** [comment]
yes, `fuse-box@3.5.0-next.12` fixed it :)
