### ISSUE TITLE
BabelPlugin with Babel7 support

### ISSUE THREAD

**Issue by eddyw** [fuse-box/fuse-box#1364]
Now that Babel 7 is out, I was attempting to run a test project with fuse-box and Babel 7. However, [here](https://github.com/fuse-box/fuse-box/blob/master/src/plugins/js-transpilers/BabelPlugin.ts#L101) BabelPlugin explicitly requires `babel-core`. I want to discuss the possibility of allowing the user to define which or from where to include babel core. Kind of like:
```javascript
BabelPlugin({
  babelCore: '@babel/core', // < fallback to `babel-core` if not specified?
  config: {...}
})
```
Since `babel-core` and `@babel/core` have the same API (I think, I took a quick look :P), It would work.
Or, as an alternative, if It can be versioned. Maybe something like:
```javascript
Babel7Plugin({...})
```
Keeping the previous one untouched.

**Comment by nchanged** [comment]
@eddyw sounds legit to me? can you submit a PR? also please update the docs ;-)

**Comment by eddyw** [comment]
@nchanged I have a dirty implementation working on local. It'd take me some time to implement it properly :P

While we're at it, `@babel/preset-env` has a `useBuiltIns` options which can be set to `usage` to include polyfills for things that need to be polyfilled. For instance, with the following:

**Source:**
```javascript
[1, 2, 3].includes(3);
```

**Config:**
```javascript
const client = FuseBox.init({
  cache: false,
  target: "universal@esnext",
  homeDir: "src",
  output: "dist/$name.js",
  useTypescriptCompiler: false,
  tsConfig: "./tsconfig.json",
  sourceMaps: {
    project: true,
    vendor: true,
    inline: true
  },
  ensureTsConfig: true,
  log: false,
  plugins: [
    EnvPlugin({
      NODE_ENV: "development"
    }),
    SourceMapPlainJsPlugin(),
    Babel7Plugin({ // << Just replaces babel-core with @babel/core and `transform` to `transformAsync`
      limit2Project: true,
      config: {
        sourceMaps: true,
        sourceType: "module", // << by default babel will guess
        ast: true, // << this defaults to `false`, I'm not sure if it was like that before Babel 7
        presets: [
          [
            "@babel/preset-env",
            {
              useBuiltIns: "usage",
              targets: "> 0.25%, not dead",
              debug: true,
              modules: "commonjs"
            }
          ]
        ]
      },
      extensions: [".tsx", ".ts", ".js", ".jsx"]
    }),
  ]
})
```
with the preset config, it generates the following:
```javascript
(function(FuseBox){FuseBox.$fuse$=FuseBox;
FuseBox.target = "universal";
var __process_env__ = {"NODE_ENV":"development"};
FuseBox.pkg("default", {}, function(___scope___){
___scope___.file("client/app.jsx", function(exports, require, module, __filename, __dirname){

"use strict"; 

require("core-js/modules/es7.array.includes"); // <<< Injected by babel

require("core-js/modules/es6.string.includes"); // <<< Injected by babel

[1, 2, 3].includes(3);
});
return ___scope___.entry = "client/app.jsx";
});

FuseBox.import("default/client/app.jsx");
FuseBox.main("default/client/app.jsx");
})
(function(e){function r(e){var r=e.charCodeAt(0),n=e.charCodeAt(1);if((m||58!==n) ...blablabla... }();return m||(h.FuseBox=_),e.FuseBox=_}(this))
//# sourceMappingURL=app.js.map?tm=1535441846599
```
Since those `require` are included by babel, this code may work on `NodeJS` but it won't work on browser since those `require` are not resolved/included by FuseBox.

I'm not very familiar with the FuseBox API. Any suggestion where to look at? `useBuiltIns: "usage"` is a pretty cool feature and I want to implement this.

**Comment by eddyw** [comment]
Well, I found `file.analysis.addDependency` which should add those extra requires, I guess?
For instance:
```javascript
file.analysis.addDependency('core-js/modules/es7.array.includes')
file.analysis.addDependency('core-js/modules/es6.string.includes')
```

**Comment by nchanged** [comment]
That will work, also you could kick analysis on the generate babel source and see what's there

**Comment by eddyw** [comment]
Actually, I thought maybe to "inject" a plugin to babel config, so we can get from AST all references to `core-js`, kind of like this:
```javascript
this.config.plugins = [ // << Just testing but shouldn't over-write
  function addStringDependenciesForCoreJS() {
    return {
      visitor: {
        CallExpression(path) {
          const node = path.node
          if ( // << probably all this can be better :/
            node.callee.type === 'Identifier' &&
            node.callee.name === 'require' &&
            node.arguments[0].type === 'StringLiteral' &&
            node.arguments[0].value.indexOf('core-js/modules') === 0
          ) {
            file.addStringDependency(node.arguments[0].value)
          }
        }
      }
    };
  }
];
```
I was checking `analysis` but in `dependencies` those imports do not appear, only the ones that are originally in the source. Unless I'm missing something.

Anyway, I'll get some time this week (maybe) to have a babel 7 plugin and leave the polyfills thing for later (or kind of under an optional flag/property)

**Comment by eddyw** [comment]
@nchanged question, the BabelPlugin does `file.analysis.analyze();` if `result.ast` is returned. However, `file.analysis.wasAnalysed` always returns `false`, so `file.analysis.analyze();` actually does nothing there, so it's not able to recognize and resolve the imports. If setting `file.analysis.wasAnalysed = false`, it analyses the file correctly and recognized the `imports/require` added by `@babel/polyfill`. So my question is, why or when does `file.analysis.wasAnalysed` becomes `false` here? :/

Since it's a private var, I'm not sure that it's a pretty solution to set it to `true`, also I still don't fully understand it yet. `file.analysis.requiresTranspilation` returns `false` though, so I guess it's not transpiling with TypeScript over again.

**Comment by nchanged** [comment]
@eddyw I think you need to investigate it. The last time I touched Babel - was a very long time ago =(

**Comment by nchanged** [comment]
Still relevant?

**Comment by eddyw** [comment]
@nchanged I'm not working with FuseBox right now, so I didn't have time to make much progress and learn how Fusebox works. I'd like to keep the issue open though :P

Main reason why I wanted to work on the plugin was because of the automatically inserted polyfills but I haven't figured out yet how Fusebox works and how to make it follow and transpile the auto-inserted `import`s or `require`s. They are just ignored.

**Comment by natew** [comment]
This still seems relevant, when using @babel/core 7 I get an error where it's looking for babel-core via FuseBox.

**Comment by eddyw** [comment]
Merry Christmast PR 🙌
I've taken time-off until end of year and decided to work on this today. I haven't done anything about the polyfills (it'll just complicate it) but I've ported all the logic from babel plugin to make it work with babel7.

I'm starting a new project next year which will likely use FuseBox and I'd love to have babel7 plugin, so I'll be more focused on making it work and solve any issues :)
