### ISSUE TITLE
Lerna + TS project references example

### ISSUE THREAD

**Issue by Ciantic** [fuse-box/fuse-box#1365]
I'm creating this issue as advised by @nchanged

I'm trying to setup a project structure with Lerna:

* packages/components
* packages/adminapp (contains fuse.js, depends on components)
* packages/componentbrowser (contains fuse.js, depends on components)

Idea is that if I start adminapp or componentbrowser they should depend on the components package. I have to watch the changes with the fuse and recompile the dependency package also, in this case `components`.

I ran in a multiple troubles with this, I did get the VSCode declaration maps working with the new [TS 3.0 project references](https://www.typescriptlang.org/docs/handbook/project-references.html), but I couldn't get the Fuse-box to recompile the dependency project when e.g. `adminapp` is started.

My attempted example is here: https://github.com/Ciantic/lerna-fusebox-typescript it contains only the rather bare bones setup, with adminapp and components.

I think what I'm trying to do would require the Fuse box to understand ts project references, otherwise I also have to run `tsc -w -b packages` in the background to update declaration maps etc. if I can get this so far.

**Comment by nchanged** [comment]
@Ciantic just a suggestion. Why not moving fuse.js next to `packages` folder. point `homeDir` to packages and makes an alias to `@yourcompany/` : `~/packages/`

It should work

**Comment by nchanged** [comment]
I will be looking at it soon after the 3.6 with sourcemaps 😃

**Comment by dotnetprofessional** [comment]
Do we have an update on this?

**Comment by Ciantic** [comment]
My 2019 look on this is that it's not Fuse box fault. Monorepo seems to be difficult to get working with other systems too. I currently use just barebones create-react-app with TypeScript support,

**Comment by Ciantic** [comment]
(I closed this accidentally, I had to comment)

**Comment by nchanged** [comment]
@Ciantic a fully working and super fast complex repository is here https://github.com/squidfunk/fusebox-lerna-multi-monorepo

**Comment by Martaver** [comment]
Btw this example link is broken

**Comment by nchanged** [comment]
@Martaver https://github.com/fuse-box/sandbox/tree/master/lerna-megarepo
