### ISSUE TITLE
typescript-plugin-styled-components

### ISSUE THREAD

**Issue by PPehrs** [fuse-box/fuse-box#1366]
I want to use _typescript-plugin-styled-components_ for styled-components _displayName_ reason

https://www.styled-components.com/docs/tooling#better-debugging is an alternative, but wont work

can someone help me to integrate _typescript-plugin-styled-components_ as plugin or maybe there is another way to _displayName_ for styled-components

**Comment by nchanged** [comment]
https://github.com/Microsoft/typescript-styled-plugin
You mean this one? 

According to docs, this should be good enough
```
{
  "compilerOptions": {
    "plugins": [
      {
        "name": "typescript-styled-plugin"
      }
    ]
  }
}
```

**Comment by PPehrs** [comment]
thanks for this quick answer

it's not the plugin i mean

with the typescript-plugin-styled-components styled-component classNames will be modified from:

<div class="**sc-EHOje** cQxCCl">

to:

<div class="**MyStyledComponent**-EHOje cQxCCl">

we use it already with webpack but fail to use it with fuse-box

https://github.com/Igorbek/typescript-plugin-styled-components

**Comment by nchanged** [comment]
@PPehrs awesome, I think we can port it, since it's only a typescript transformer which FuseBox supports on plugin level.

**Comment by nchanged** [comment]
Is this one still relevant?

**Comment by PPehrs** [comment]
yes, would be great if you can port it, is it possible?

**Comment by RXminuS** [comment]
I put up a bounty if anyone is eager https://www.bountysource.com/issues/62705770-typescript-plugin-styled-components

**Comment by eds-snippets** [comment]
Please close this issue, because it is already solved. Documentation about the plugin you can find [here](https://github.com/fuse-box/fuse-box/blob/master/website/versioned_docs/version-3.6.0/plugins/styled-components-plugin.md). If you have any additional questions about the plugin, just don't hesitate to ask. Thank you.

**Comment by RXminuS** [comment]
Awesome job! You just saved me hours of headaches! @nchanged do I need to do anything for the bounty to pay out?

**Comment by nchanged** [comment]
@RXminuS thank @eds-snippets ;-) You should contact him ;-)

**Comment by nchanged** [comment]
@eds-snippets I guess you should click "claim bounty" on that page
