### ISSUE TITLE
Reference error: require not defined

### ISSUE THREAD

**Issue by mweiczorek** [fuse-box/fuse-box#1368]
When bundling, I get the error "require not defined" when using quantum.
The error stack in the browser is non-sensical, so I didn't post it

Using latest version 3.4.0

Here is my bundling code:

```
  const quantumOptions: IQuantumExtensionParams = {
    bakeApiIntoBundle: true,
    target: 'browser',
    removeUseStrict: true,
    uglify: true,
    ensureES5: true,
  }

  const fuse = FuseBox.init({
    homeDir: './src',
    output: `${outputDir}/$name`,
    target: 'browser',
    log: true,
    cache: false,
    sourceMaps: false,
    alias: {
      "@io": "~/io",
      "@store": "~/store",
      "@client": "~/client",
      "@components": "~/client/components",
      "@decorators": "~/decorators",
      "@util": "~/util",
    },
    plugins: [
      QuantumPlugin(quantumOptions),
      JSONPlugin(),
      EnvPlugin(env),
      //UglifyESPlugin()
    ]
  })

  fuse.bundle(bundleName)
    .instructions('> client/index.ts -server')
  // .plugin(JSONPlugin())
  // .plugin(EnvPlugin(env))
  // .plugin(UglifyESPlugin())

  fuse.run()
````

**Comment by nchanged** [comment]
Please clear the dist folder so the ouput (without sourcemaps ) would make sense and copy paste the log

Some library has a very "smart" way of checking environment or makes a reference on require function

**Comment by nchanged** [comment]
Yes, I guess you had sourcemaps on, are they are still read. Since you don't have sourcemaps for vendor please disable them and clear the entire dist folder.

**Comment by mweiczorek** [comment]
No, source maps are off (see my code snippet)

This is a React-TypeScript project I'm trying to bundle to ES5. Without the Quantum plugin, everything works fine, but I need Quantum for dead code elimination. I'm not sure what you mean by "dist folder"

The bundle is built to my output directory, which only ever has one file (the bundle). Is this library re-mapping the require function to something else?

**Comment by mweiczorek** [comment]
![untitled](https://user-images.githubusercontent.com/224439/44743152-e47ada00-ab2b-11e8-91a4-f63aad29cf40.png)

This is the stack trace... not too easy to follow. This is after disabling uglification.

THis is the line of the bundle code at the top stack entry:

````
// app-root-path/browser-shim.js
$fsx.f[130] = function(module,exports){
exports.path = $fsx.r(502).dirname(require.main.filename); // <-- this is where the error is thrown
exports.resolve = function (pathToModule) {
    return exports.path + pathToModule;
};
exports.require = function (pathToModule) {
    return $fsx.r(exports.resolve(pathToModule));
};
exports.toString = function () {
    return exports.path;
};
exports.setPath = function (explicitlySetPath) {
    exports.path = explicitlySetPath;
};
}
````

**Comment by nchanged** [comment]
@mweiczorek Right, I don't think you can even bundle this lib ;-( I see, Quantum didn't replace `require.main.filename`

I wonder if you replace it with just an empty string, will it work? It's just for the browser right?

**Comment by mweiczorek** [comment]
I looked deeper, and this was a server-side library that was leaked to client code because it was imported (not required inside the calling method) - this worked with normal bundling (without Quantum), because my code checked for client/server environment at runtime (via decorator) - but somehow, Quantum did something to make this introspected at compile time. Very strange. I guess JS isn't so isomorphic as people say.

Seems to be working now!

**Comment by nchanged** [comment]
@mweiczorek Its Quantum's job to make it all smooth. I need to figure out what to do with `require.main.filename` on browser.

**Comment by mweiczorek** [comment]
I'd issue a warning or error if encountered in a browser-targeted bundle with server-only code was included - with the module name and the file its imported in If possible.

Thanks for your quick responses.

**Comment by nchanged** [comment]
This has been all fixed in `v4`. Please upgrade to the [major version](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)
