### ISSUE TITLE
Weird regression in 3.5.0, only .js file being generated in output directory

### ISSUE THREAD

**Issue by jpike88** [fuse-box/fuse-box#1372]
I just upgraded from 3.4.0 to 3.5.0, and my build server is breaking because it seems to be only detecting and uploading a single file instead of like 30 in the output directory.

That file is the bundled javascript file. But it seems all assets, even the index.html are missing.

I dont have time to currently investigate further, but do you know of anything that was done since 3.4.0 that could affect this?

**Comment by jpike88** [comment]
Confirming that reverting to 3.4.0 fixed the issue. Quantum is being used, and Im doing this before I run it:

```
    // add assets
    src('**/**.**', { base: srcDir + '/assets' })
        .dest(stagingDir)
        .exec()
```

So this means that the build is clearing the directory as it bundles, and not just that, but failing to create an index.html file...?

**Comment by jpike88** [comment]
When I get a moment I'll step forward through each of the 3.5.0 next bundles till I hit the issue

**Comment by nchanged** [comment]
@jpike88 I don't think anything could possibly affect it, but obviously, something had happened. Please investigate =)

**Comment by nchanged** [comment]
@jpike88 maybe you could reproduce it too?

**Comment by jpike88** [comment]
It would be easier to stick my head up my own ass than reproduce this one. I can’t get it to happen on local machine, just codebuild server and I don’t want to mess with docker

I’ll just isolate the commit, there’s few enough to have a solid guess

**Comment by nchanged** [comment]
@jpike88 yes, please check it, I can roll a patch real quick.

**Comment by jpike88** [comment]
@nchanged can't repro, looks ok
