### ISSUE TITLE
Debugging server in VSCODE

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#1374]
Hi, I followed your guide here: https://fuse-box.org/docs/guides/debugging-with-vscode#server-debugging

Yet, I cannot debug my typescript files. The server will break in the generated javascript but not in the typescript. There must be something with source maps.

Her is my config:

```
const { FuseBox } = require('fuse-box');

const fuse = FuseBox.init({
  homeDir: 'src',
  output: 'dist/$name.js',
  alias: {
    data: '~/data/',
    tests: '~/tests/',
    server: '~/server/',
    shared: '~/shared/'
  }
  sourceMaps: {
     project: true,
     vendor: true
  }
});

fuse
  .bundle('server')
  .instructions('> [server/index.ts]')
  .target('server@es2017')
  .watch('src/server/**')
  .completed(proc => {
    proc.require({
      close: ({ FuseBox }) => FuseBox.import(FuseBox.mainFile).shutdown()
    });
  });

fuse.run();
```

Here is repo:

https://github.com/tomitrescak/corporator

**Comment by nchanged** [comment]
Hi, there is no support for server sourcemaps yet

**Comment by nchanged** [comment]
https://github.com/evanw/node-source-map-support/blob/master/README.md

This should help

**Comment by tomitrescak** [comment]
Hi, I made it work with following config from the example files:

```
{
      "type": "node",
      "request": "attach",
      "name": "Attach Server",
      "port": 9031,
      "restart": true,
      "sourceMapPathOverrides": {
        "/*": "${workspaceRoot}/*"
      }
    },
```

Thanks guys for the amazing work you do!
