### ISSUE TITLE
Invalid import paths for modules using custom extensions

### ISSUE THREAD

**Issue by merlinnot** [fuse-box/fuse-box#1383]
If some npm module specifies a `module` field in it's `package.json` with an extension which is not included in the whitelist of recognised extensions (such as a popular `.mjs`), FuseBox adds `.js` to the end of the path which results in a broken import.

**Comment by merlinnot** [comment]
An example of a broken package: https://visionmedia.github.io/page.js/

**Comment by nchanged** [comment]
That has been fixed `fuse-box@next`

Give it a try. It's a brand new version with major updated
