### ISSUE TITLE
pass paramerters to fuse

### ISSUE THREAD

**Issue by misantronic** [fuse-box/fuse-box#1386]
is it possible to pass parameters via cli to the fuse-script?

`node fuse dev --no-cache` is not working since he thinks `--no-cache` is a task.

**Comment by Kaffiend** [comment]
You can pass task names for sparky and create a sparky task to clear the cache. You can also use an environment variable. 
```
 const fuse = FuseBox.init({
    homeDir: "src",
    output: `${OUTPUT_DIR}/$name.js`,
    log: isProduction,
    cache: !isProduction, // you can evaluate here 
    sourceMaps: true,
    tsConfig: "tsconfig.json",
  })
```
then use a lib like `cross-env` in your npm script to set the environment variable or even spark and the environment plugin.
