### ISSUE TITLE
import bootstrap css

### ISSUE THREAD

**Issue by Kaffiend** [fuse-box/fuse-box#1388]
@nchanged I'm not sure what i'm missing i've done this time and time before but i'm at wits end.

In electron i'm just trying to use the css from bootstrap.

I've tried both the distributed scss (with proper plugin of course) and css and still keep getting the same result.
![image](https://user-images.githubusercontent.com/7826229/45912331-946efa80-bded-11e8-98e1-62eb5e81fb88.png)
its coming from this...
![image](https://user-images.githubusercontent.com/7826229/45912344-bec0b800-bded-11e8-984e-f18bce31db9d.png)

and my two bundle configurations
```
  // bundle the electron main code
  const mainBundle = fuse
    .bundle("main")
    .target("server")
    .instructions("> [main/main.ts]")
  // inject in some configuration
  // and watch unless we're bundling for production
  if (!isProduction) {
    mainBundle.watch()
  }

  // bundle the electron renderer code
  const rendererBundle = fuse
    .bundle("renderer")
    .target('electron')
    .instructions("> [renderer/main.tsx] + fuse-box-css")
    .plugin(
      CSSPlugin(),
      CopyPlugin({ useDefault: false, files: ASSETS, dest: "assets", resolve: "assets/" }))
```
Edit: One thing i forgot to mention is if i change the arithmetic to include all, the bootstrap works but then electron doesnt load proper. If you try to use ipc or any other electron api it crashes out and says that `electron failed to install correctly`

**Comment by nchanged** [comment]
Try adding plugins to FuseBox.init
And secondly you can't combine the CSSplugin and the CopyPlugin use either or.

**Comment by Kaffiend** [comment]
no change...

**Comment by Kaffiend** [comment]
Here is the repo. It uses mongodb by the way.
https://github.com/Kaffiend/fusebox-electron-react-typescript-mongo

**Comment by Kaffiend** [comment]
That's what i originally had, still same result.

**Comment by nchanged** [comment]
@Kaffiend remove all the opts from the CSSPlugin, it will be removed soon.

**Comment by Kaffiend** [comment]
Tried that as well. Same result. I am clearing the .fusebox directory every
test too.

**Comment by nchanged** [comment]
@Kaffiend I launched it, it can't find index.html
Some instructions on how to repro the issue?

**Comment by Kaffiend** [comment]
@nchanged Is the index.html in the `out` dir? i just cloned a fresh one and it started fine with a repro

**Comment by Irrgeist** [comment]
I have the same issue. I tried a minimal project, the index.ts is also empty. Installed bootstrap via NPM:
```
const { FuseBox, CSSPlugin, CSSResourcePlugin } = require("fuse-box");
const fuse = FuseBox.init({
  homeDir: "src",
  target: "browser@es6",
  output: "dist/$name.js",
  plugins: [
      [
          CSSResourcePlugin({
              dist: 'dist/resources',
              resolve: f => `dist/resources/${f}`
          }),
          CSSPlugin()
      ]
  ]
});

fuse
  .bundle("app")
  .instructions(" > index.ts")
fuse.run();
```

this is the output:
```
--- FuseBox 3.5.0 ---
  → Typescript config file:  \src\tsconfig.json
  → Typescript script target: ES6

--------------------------
Bundle "app"

    index.js
└──  (1 files,  287 Bytes) default
size: 287 Bytes in 120ms
```

**Comment by nchanged** [comment]
@Kaffiend due to the limit amount of time at hand, I would like just to clone and see the problem. Please, prepare the repository so I won't need to fiddle around about the launch

**Comment by nchanged** [comment]
closing it due to inactivity
