### ISSUE TITLE
Plug for Angular2

### ISSUE THREAD

**Issue by fmoessle** [fuse-box/fuse-box#139]
Are there any plans for plugins for angular2 like:

[https://github.com/TheLarkInn/angular2-template-loader](url)
or
[https://www.npmjs.com/package/@ngtools/webpack](url)

It would be great to be able to use 'templateURL' and 'styleURLs' without the usage of require(), angular2-template-loader solves this issue.

@ngtools/webpack helps you to aot-compile your application in notime, without much configuration.

**Comment by devmondo** [comment]
@fmoessle  of course, we are moving towards providing all of that :)

**Comment by mitsoe** [comment]
Would also make it a lot easier to switch to FuseBox from a normal angular2 env

**Comment by nchanged** [comment]
I agree, we should get to ng2 after aurelia and HMR plugins.

**Comment by alex-klock** [comment]
I just published a plugin that works similarly to angular2-template-loader but for fuse-box, it'll take care of the templateUrl and styleUrls.

https://github.com/alex-klock/ng2-fused

**Comment by nchanged** [comment]
Oh! nice! looking cool!

**Comment by nchanged** [comment]
added it here: https://github.com/fuse-box/fuse-box/blob/master/docs/third-party-plugins.md

**Comment by fmoessle** [comment]
Thanks :),

if there will be an aot-plugin and a router-plugin for lazy loading I would love to use fuse-box for my angular applications

**Comment by alex-klock** [comment]
Thanks @nchanged!

@fmoessle, I'm working on a Ng2LazyPlugin (actually converting some hard coded FuseBox code in my routes to a more generic plugin form) and should have that available in ng2-fused hopefully within a few days.  As for the aot, been meaning to switch over an application I'm working on to use aot, so hopefully that'll give me a chance to attempt to tackle an aot fuse-box plugin for it as well. :)

**Comment by nchanged** [comment]
@alex-klock please take a look at the upcoming version over here https://github.com/fuse-box/preview-1.4.1/blob/master/examples/react-code-splitting/fuse.js

**Comment by alex-klock** [comment]
Thanks for the link @nchanged! :) Been watching those examples, I "think" my router plugin should be okay for both current version and upcoming 1.4.1, it's more about transforming the Angular2 loadChildren string which looks like `loadChildren: './+lazyModule/lazy.module.ts#LazyModule'` to the alternative function syntax which returns a Promise utilizing the Loader API (very similar to the fuse-tools lazyload method and how its used in the LazyComponent from the example you post, I may just see about utilizing that library directly).  Right now on the application I'm working on, I've got lazy loading of modules working with FuseBox (no plugin though, the loadChildren functions all have the FuseBox.import directly in the code), with a check to see if it was a devServer bundle (single file, already loaded) or split bundles (using the current .bundle() method to create multiple bundles). 

I'll make sure it works against the 1.4.1 version before releasing it.

**Comment by nchanged** [comment]
I think we are talking about this one:
https://github.com/alex-klock/ng2-fused

Closing this for now. Please feel free to check the latest bleeding edge version `fuse-box@2.0.0-beta.8`
and documentation for it http://fuse-box.org:3333 You are welcome to re-open it elsewise ;-)
