### ISSUE TITLE
Erroneous case-sensitivity re package/globals

### ISSUE THREAD

**Issue by paxperscientiam** [fuse-box/fuse-box#1392]
Haven't totally nailed it down, but, after some testing, it appears that `fusebox` gets confused when `InitObject.package.name` begins with a capital letter.

Settings except:

This works ...
````js
  package: {
          main: "index.js",
          name: "pax",
        },
        globals: {
          pax: "pax",
        },
````
... but this does NOT:
````js
  package: {
          main: "index.js",
          name: "Pax",
        },
        globals: {
          Pax: "Pax",
        },
````

I tried with several other identifiers: in each case, there is an error is the package name begins with a capital letter.

Leads to this error -> "uncaught exception: Package not found default"

**Comment by nchanged** [comment]
@paxperscientiam please avoid setting `package` option. It will be get flattened with Quantum. i've updated the docs
