### ISSUE TITLE
Allow to specify which bundles to inject into template (FR)

### ISSUE THREAD

**Issue by paxperscientiam** [fuse-box/fuse-box#1397]
This is a feature request that I intend to do myself:

Currently, the WebIndexPlugin only accepts `true` or `false` on the `appendBundles` property. A nice expansion would be to allow the user to specify where a given bundle is injected.

Something like this:
````html
<!DOCTYPE html>
<html>
  <head>
${bundles[key1]}
  </head>
  <body>
    ${bundles[vendor]}
    <h1>Style from index.scss with shared</h1>
    <h2>Style from foo.scss with shared</h2>
$bundles <!-- everything else -->
  </body>
</html>
````

Something to that effect

**Comment by nchanged** [comment]
But you can use consolidate and any template engine 😃 also with injecting variables

**Comment by paxperscientiam** [comment]
In my use-case, I am only using script injection for testing and proxy for development. That is, implementing a javascript templating engine for testing purposes would be overkill; I use PHP for development/templating.
