### ISSUE TITLE
CSS modules docs suggest using CSSModulesPlugin that does not exist

### ISSUE THREAD

**Issue by adam-risberg** [fuse-box/fuse-box#1398]
Documentation at [https://github.com/fuse-box/fuse-box/blob/master/docs/plugins/css-modules.md](url) instructs one to use CSSModulesPlugin. I'm fuse-box 3.5.0 and CSSModulesPlugin is gone. I got it working by following the docs but replacing CSSModulesPlugins with CSSModules.

I'm assuming the docs is out-of-date.

**Comment by nchanged** [comment]
there is it 
https://github.com/fuse-box/fuse-box/blob/master/src/plugins/stylesheet/CSSModules.ts

Could you help out updating the docs?
