### ISSUE TITLE
ES6 dependency with "class" not transpiled to ES5

### ISSUE THREAD

**Issue by koffmoff** [fuse-box/fuse-box#1399]
See #916 .

I have the same problem with an ES6 dependency containing a `class` definition. It wasn't transpiled to ES5. Adding a dummy `const` assignment in the same file as the class solved the problem.

`LanguageLevel.ts` probably needs to be able to detect `class` keywords as well.

**Comment by nchanged** [comment]
Do you think you can make a PR? should be easy to add a condition [here](https://github.com/fuse-box/fuse-box/blob/master/src/analysis/plugins/LanguageLevel.ts)

**Comment by koffmoff** [comment]
Tried but I don't understand how to develop/debug. I initialized a new npm project under _playground/generic, added my ES6 dependency and tried to bundle it. No matter what I do, fuse-box does not bundle my dependency here in the playground. Works in a "normal" project outside the fuse-box repo.

**Comment by nchanged** [comment]
@koffmoff just add that dependency to `fuse-box` don't init any repositories.

**Comment by koffmoff** [comment]
Sure enough. Got the env going. Thought it'd be an easy fix but I stumbled upon another problem. See PR #1400 for more info.

**Comment by nchanged** [comment]
@koffmoff thanks for the PR. Let's close this one now!
