### ISSUE TITLE
Better angular application required (demo). HELP

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#14]
Hey guys, 
It would be nice to have a proper ng2 TODO app (anything but HelloWorld) based on Fuse? Existing examples are outdated (angular changed their APIs) and I cannot find a single sane ng2 demo app.

I am sure many of angular developers have something to share ;-)

Cheers

**Comment by joselee** [comment]
Here we go mate!
https://github.com/fuse-box/angular2-example/pull/3

**Comment by nchanged** [comment]
Bloody marvellous mate! Thanks!
