### ISSUE TITLE
CSP-Header 'unsafe-eval' and Code splitting

### ISSUE THREAD

**Issue by misantronic** [fuse-box/fuse-box#1403]
When activating code-splitting in fuse-box, the chunks being loaded are evaluated using `eval` --> `new Function(...)`.
With CSP I want to block these kind of scripts to prevent XSS-attacks etc.

Therefore fuse-box with code-splitting is not compatible with CSP 'unsafe-eval'.
Is there a way around it? I would like to keep 'unsafe-eval' disabled.

**Comment by nchanged** [comment]
@misantronic we could evaluate it on script level. I guess. 
It's here
https://github.com/fuse-box/fuse-box/blob/fe08a38927fe81d9ac44afe372752bd101d0bfe4/modules/fuse-box-responsive-api/index.js#L356

Do you think you can experiment and share you ideas?

**Comment by nchanged** [comment]
TO be precise, it's location here
https://github.com/fuse-box/fuse-box/blob/fe08a38927fe81d9ac44afe372752bd101d0bfe4/modules/fuse-box-responsive-api/index.js#L285-L305

**Comment by misantronic** [comment]
Don't your think this might work for loading the script?
No Ajax-Request needed.

```ts
async function loadScript(src: string): Promise<void> {
    return new Promise<void>(resolve => {
        const script = document.createElement('script');

        script.type = 'text/javascript';
        script.async = true;
        script.onload = () => setTimeout(resolve, 16);
        script.src = src;
        
        document.body.appendChild(script);
    });
}
```

**Comment by nchanged** [comment]
@misantronic we still need to understand when the script has finished loading so we could trigger an entry point. 

* Trigger script once loaded ( need to make a XHR request anyway I think)
* Cache it (to avoid duplicate scripts in head
* Make it optional, since we don't want to have breaking changes.

**Comment by misantronic** [comment]
Ok, so the problem is that the code is not yet initialized when `onload` is invoked?
Maybe we can put a flag at the end of each script on which is checked?
something like

```js
await loadScript('chunk.js');

const int = setInterval(() => {
  if($FUSEBOX_FLAG_LOADED) {
    clearInterval(int);
    console.log('CODE READY');
  }
}, 16);
```

**Comment by nchanged** [comment]
@misantronic To check if a module is loaded? Yes can do that. But again, it all should optional (with a variable). Do you think you can cook a PR?

**Comment by misantronic** [comment]
yes, I will have a look into it over the next few days.On Oct 10, 2018 18:05, nchanged <notifications@github.com> wrote:@misantronic To check if a module is loaded? Yes can do that. But again, it all should optional (with a variable). Do you think you can cook a PR?

**Comment by nchanged** [comment]
@misantronic got any updates on that?

**Comment by misantronic** [comment]
nope. unfortunately, I haven't had the time to look into it, yet.

**Comment by nchanged** [comment]
Closing this for now. Feel free to re-open once relevant.
