### ISSUE TITLE
manifest.json includes absolute paths

### ISSUE THREAD

**Issue by paxperscientiam** [fuse-box/fuse-box#1406]
Maybe I'm missing the point, but why does the manifest.json file include the explicit local path?

```json
{
  "shims.js": {
    "fileName": "shims.js",
    "type": "js",
    "absPath": "/local/path/to/development/root/dist/js/shims.js",
    "webIndexed": true,
    "relativePath": "shims.js"
  },
  "vendor": {
    "fileName": "vendor.js",
    "type": "js",
    "absPath": "/local/path/to/development/root/dist/js/vendor.js",
    "webIndexed": true,
    "relativePath": "vendor.js"
  }
}
```

In the [docs](https://fuse-box.org/docs/production-builds/quantum-configuration#manifest) example, it's indicated that a placeholder variable `$userpath` should be written instead of the explicit local path.

**Comment by nchanged** [comment]
That "variable" is merely to conceal the actual path. Manifest should always be ignored and live it the dist folder

**Comment by paxperscientiam** [comment]
But, is it supposed to include absolute paths from development machine?

**Comment by nchanged** [comment]
@paxperscientiam of course not. A manifest should be generate on the machine that you want to deploy to. Or on a docker container, of course
