### ISSUE TITLE
Circular Includes cause import to be undefined

### ISSUE THREAD

**Issue by SephReed** [fuse-box/fuse-box#1415]
I have a project which I want to have a circular include in.  When I write the code, it results in one of the includes being undefined.

Here's an example of what I'm doing (minus a bunch of functionality).
```
// Child.ts
import Parent from "./Parent";

export default class Child {
  constructor(private parent: Parent){}
}
```

```
// Parent.ts
import Child from "./Child";

export default class Parent {
  private child: Child;
  constructor() {
    this.child = new Child(this);
  }
}
```

In my case it's `Game imports CharacterDeck extends Deck` and `Deck imports Game`.

I can tell it has to do with circular imports because commenting out the `Deck imports Game` code fixes the issue of `Game imports CharacterDeck === undefined`.

**Comment by nchanged** [comment]
And what do you expect? 

Circular dependency will give you undefined anyway in any language. It will give undefined in NodeJS too. If you really want to make it work use it at runtime with `require`.  But I wouldn't recommend it since circular dependency is a sign of poor design and should be alarming.
```
export default class Stuff {
   getInstance(){
       new Stuff(require("./Parent"))
   }
}
```

**Comment by SephReed** [comment]
> circular dependency is a sign of poor design and should be alarming

Very true, but that doesn't mean there aren't good cases for it.   In any case, what I would expect from any graph traversal algorithm (in this case dependency mapping), is to do what a human would do.

In this case:
1. Parent starts off as type any and incomplete
2. Parent imports Child which is at first also of type any and incomplete
3. Child tries to import Parent, it gets back the type any and also that it is incomplete (and so registers the type any as something that will be updated later),
4. Child is compiled into a type like (missing something I'm sure) { new(parent: Parent): void }
5. Child updates it's state from "complete" to "incomplete".  Anything which had been using the `any` form of Child can now update it's assumed typings.
6. Child is imported to parent
7. Parent continues compiling itself
8. Parent updates it's state from "complete" to "incomplete".  Anything which had been using the `any` form of Child can now update it's assumed typings.

I really appreciate the work you guys are doing on this project, it's a huge step up from other tools I've used.  So thank you, and I hope there is a way to make circular dependencies not such a hassle.  I hadn't realized that NodeJS was getting caught up on this, but I know for sure that my TS language server is having no issues at all.  

Also, even in compiled languages, unless the circular dependency is the kind that *really* has an infinite logic loop (like finding the size in bytes of two things that include each other), it is possible.  That's why IFNDEF is found at the top of many files in C++.  When it comes to nodes and trees, circular dependencies are practically an inevitability.

**Comment by nchanged** [comment]
@SephReed Thanks for such kind words ;-)

I can tolerate circular dependency as typing In TypeScript - the way you described `(parent : Parent)`. But an explicit circular dependency is usually a bad practice, and there are better ways.

In regards to in-browser circular dependency the only solution I've come up with is to return an `undefined` Object. Otherwise it's  a `maximum call stack size exceeded` error. [The actual implementation](https://github.com/fuse-box/fuse-box/blob/344e320abeed0448929773e6c4259ad2877b3c9f/modules/fuse-box-responsive-api/index.js#L425-L443) is quite simple. You can take a look if you want.

**Comment by SephReed** [comment]
> But an explicit circular dependency is usually a bad practice, and there are better ways.

It's funny, but at least once per major project, I'll come across a situation where I have to choose between callback hell, globals, or circular dependencies.  I was definitely taught in school to choose callback hell, but it was too late: I'd already found easier solutions that involved circular dependencies.  I still do it the standard way at work, but I do so knowing just how much extra effort it takes.  It's okay for employees to know their managers, and I think that relationship translates just fine to code.

Anyways, code theory digression aside, thanks for the link.  I'll see if I can't find a way to make it avoid going in circles.

**Comment by SephReed** [comment]
So, I'm not sure what the file function does, but it looks like it should not give undefined in circular cases.  

It appears parent gets required, creates a cache item, passes it on to `file.call(cached.exports, cached.m, cached.exports);` which presumably fills it up with details on it's existence and purpose, then returns that item.  So, by that logic, parent should be an empty cache object by the time child requests it... I think.

But having an empty object is still not much better than simply "undefined".  But I can imagine a strange transpilation which would solve this issue.  It definitely would belong behind an optional flag, but if the import section of the code was separated from running part asynchronously, it could work.

For example:

```
import Parent
import Foo

class Child {
  foo: Foo;
}
```

would become something along the lines of

```
return Promise.all([
  asyncRequire(Parent),
  asyncRequire(Foo),
]).then(([Parent, Foo]) => {
  export = class Child {
    foo: undefined;
  }
});
```

All the above is very bad pseudo code, I don't spent much time in transpiled code or non-typescript node.

**Comment by SephReed** [comment]
Hmmm... thought more about the suggestion, it would just lock up with circular promises.  I think the real trick is for one of them to go ahead without completion and see if everything works out, and if it doesn't, try the other one.  Only when neither of them can complete their exports without the others import is it a truly blocked circular reference.

I think I can write the code fairly quickly.  I'll see.

**Comment by SephReed** [comment]
Hey, sorry for all the chattiness.  I'll try to just keep it to questions.

When `Parent` is imported to `Child` it should reference a cache object.  Is this cache object `module`?  

If so, it would make sense that it would assign `module.exports.default` to Parent, making it undefined.  If that's the case, where can I find the lines of code which are doing this module extraction?  If those are made into something that listens for changes to a cache object, it should be able to avoid almost all circular dependency issues.

**Comment by nchanged** [comment]
It's impossible due to the runtime limitation. You can't access an object
which hasn't been yet created

**Comment by SephReed** [comment]
It's definitely not impossible, but after thinking about this more, I think using an inline require is a workable solution.  

But to show you how this could work, all you have to do is transpile imports so they return a module with observable exports.  Like so:

```
import "Parent";
import { Foo, Bar } from "./Foo";

export default class Child {
  foo: Foo;
}
```

transpiles to =>

```
const ParentModule = requireModule("./Parent");
const FooModule = requireModule("./Foo");

let Foo, Bar, Parent;
ParentModule.observeExports((exports) => Parent = exports.default);
FooModule.observeExports((exports) => {
  Bar = exports.Bar;
  Foo = exports.Foo;
});

module.exports.default = class Child {
  foo;
}

module.triggerExportsObservers();
```
