### ISSUE TITLE
Question: workers bundle without quantum

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box#1416]
I finally got this working... fork it if you want
https://github.com/vegarringdal/fuse-box-monaco-editor

but only way I could get a worker bundle working was to use quantum
how can I do this without quantum/ to get sourcemaps etc

**Comment by nchanged** [comment]
@vegarringdal this will have too wait until I get the first Source maps version to work. Which will happen in the next `@next`  (after the release on 3.6 which is this week)

**Comment by nchanged** [comment]
https://github.com/fuse-box/fuse-box/issues/1375

**Comment by vegarringdal** [comment]
ok, we should do PR to monaco editor sample repo when its done.
This way maybe more people will be aware fusebox exists :-)

**Comment by nchanged** [comment]
will close it for now

**Comment by vegarringdal** [comment]
k, version how is version 3.7 going ?

**Comment by nchanged** [comment]
@vegarringdal I think I will release it soon ;-)
