### ISSUE TITLE
Importing css from node_modules (react-dates)

### ISSUE THREAD

**Issue by jimmybaker** [fuse-box/fuse-box#1417]
I'm trying to use the react-dates package and as per their instructions I added the following lines at the top of my app:

```
import "react-dates/initialize";
import "react-dates/lib/css/_datepicker.css";
```

Starting the app with these lines in place gives me the following error:

<img width="1666" alt="image 2018-10-24 at 7 46 17 pm" src="https://user-images.githubusercontent.com/50668/47469541-0492e680-d7c7-11e8-9089-181cad2ab140.png">
<img width="1198" alt="image 2018-10-24 at 7 44 47 pm" src="https://user-images.githubusercontent.com/50668/47469545-078dd700-d7c7-11e8-8bff-09f694bddb03.png">

Here's my configuration:

```javascript
const {
  FuseBox,
  SassPlugin,
  CSSPlugin,
  WebIndexPlugin,
  Sparky,
  QuantumPlugin,
  EnvPlugin,
  JSONPlugin,
  SVGPlugin
} = require("fuse-box");
const GraphQLPlugin = require("fuse-box-graphql-plugin");

const express = require("express");
const path = require("path");
const { spawn } = require("child_process");

let production = false;

Sparky.task("build:renderer", () => {
  const fuse = FuseBox.init({
    homeDir: "src/renderer",
    output: "dist/renderer/$name.js",
    hash: production,
    target: "electron",
    cache: !production,
    sourceMaps: !production,
    plugins: [
      SVGPlugin(),
      JSONPlugin(),
      [".graphql|.gql", GraphQLPlugin()],
      EnvPlugin({ NODE_ENV: production ? "production" : "development" }),
      [SassPlugin(), CSSPlugin()],
      WebIndexPlugin({
        title: "FuseBox electron demo",
        template: "src/renderer/index.html",
        path: production ? "." : "/renderer/"
      }),
      production &&
        QuantumPlugin({
          bakeApiIntoBundle: "renderer",
          target: "electron",
          treeshake: true,
          removeExportsInterop: false,
          uglify: true
        })
    ]
  });
...
```

I've tried using the CSSResourcePlugin but that didn't help. Any ideas on what I could be missing?

**Comment by nchanged** [comment]
* Clear the cache
* Add Just the CSSPlugin, you handle scss but not pure css
```js
[
[SassPlugin(), CSSPlugin()],
CSSPlugin()
]
```

**Comment by jimmybaker** [comment]
@nchanged - Thanks for your suggestion, but that didn't seem to help. By clearing the cache I think you mean `rm -rf .fusebox` so I did that, then I updated the config to what you suggested and re-launched and it seemed to make it worse. Other css files weren't being brought in at that point.

For now, I've copied the css from the file and put it inline on the index.html page which makes it work.

**Comment by nchanged** [comment]
Maybe they are using imports ? Try PostCss with import plugin

**Comment by nchanged** [comment]
@jimmybaker I can confirm that having CSS plugin resolves the problem. You probably initialised it wrong,. 

https://fuse-box.org/docs/getting-started/add-css#adding-css-support

```ts
FuseBox.init({
  plugins: [
     CSSPlugin(),
     [SassPlugin(), CSSPlugin()]
  ] ,
});
```
