### ISSUE TITLE
Build a bundle at a time for CI/CD purposes

### ISSUE THREAD

**Issue by brad-jones** [fuse-box/fuse-box#1419]
**Background:** We have a fusebox based SPA, it has 2 bundles (app & vendor). So far pretty simple.

The difference is that the app is built for many different customers with different themes applied. We achieve this by injecting some environment variables at build time, eg: `CUSTOMER=foo node fuse.js`

We also have some other config, mainly feature flags and other things injected like so:

```js
EnvPlugin({ SETTINGS: JSON.stringify(require(`./src/customers/${process.env.CUSTOMER}/config.json`)) })
```

We actually build about 6 (and counting) apps.

**Problem:** Locally a dev will usually just work on one customer at a time so building everything at once is desired but in our CI/CD pipeline we end up running 6 different builds which does all the treeshaking, minification & other optimisations 6 times for the same vendor bundle. This is using up lots of compute and memory resources and is not scalable.

Semi related: https://github.com/fuse-box/fuse-box/issues/1230

What I want to do is build a single vendor bundle once in the CI/CD pipeline and then build the 6 different app bundles.

I have experimented with building a single bundle at a time but with Quantum this is not feasible due to it's virtual file system using random numbers and not actual paths.

Is there a way to perform a Quantum like build that does all the treeshaking, etc... but uses a string based virtual file system thus allowing bundles to be built by separate invocations of fuse-box?

**Comment by nchanged** [comment]
Hi @brad-jones 
I understand the problem. Unfortunately there is no clear path or solution for that exact issue you're having. However, I can suggest some tricks on how to make your build better. 

Having these hardcoded numbers doesn't mean that Quantum can't be dynamic.

## Dynamic configuration at runtime

Use dynamic [json loading](https://fuse-box.org/docs/development/dynamic-imports#loading-json)

```ts
import(`./{process.env.config}.json`).then(target => {
  console.log(target);
});
```
Copy all the env file into a dist folder (or whenever Quantum can reach it) and you got it.

## Custom mapping

You can also use  [custom mapping](https://fuse-box.org/docs/production-builds/quantum-configuration#computed-statement-resolution) It isn't the most elegant solution, and frankly I am not proud of it. But it might work for your case. 

## Isolate Quantum build
You can also make a [contained](https://fuse-box.org/docs/production-builds/quantum-configuration#containedapi) + [noConflictApi](https://fuse-box.org/docs/production-builds/quantum-configuration#noconflictapi) Quantum build, whereas all the packages are exported to the window object. Including this script in every app, will give you an access to packages via window, which can be shimmed or/and other.

**Comment by brad-jones** [comment]
Thanks for the suggestions, I'll have to have more of a play around with things.

When you mentioned [custom mapping](https://fuse-box.org/docs/production-builds/quantum-configuration#computed-statement-resolution) did you actually mean to link to [runtime bundle mapping](https://fuse-box.org/docs/production-builds/quantum-configuration#runtimebundlemapping)?

Again I need to play with it but I think that might work for what I want to do.

Having multiple projects might also work but we would need to do a lot more work to split out the base logic & presentation into extendible classes and generic components. It may be the way we go if I can convince the boss that a rewrite is worth it.

**Comment by nchanged** [comment]
Nope, runtime bundle mapping is when you manually map strings to Quantum numbers.

**Comment by nchanged** [comment]
Closing this for now.
