### ISSUE TITLE
Cannot use React.lazy

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#1420]
Hi, I tried to use Ract.lazy functionality for code splitting but it does not seem to work. For some reason, the "object" is returned.

Following works in Create React app, does not work in FuseBox ;(

```
import React, {lazy, Suspense} from 'react';
const OtherComponent = lazy(() => import('./OtherComponent'));

function MyComponent() {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <OtherComponent />
    </Suspense>
  );
}
```

**Comment by nchanged** [comment]
@tomitrescak it returns whatever the module is returning. Try exporting your component using  `default`

**Comment by tomitrescak** [comment]
@nchanged thanks for your support. I know that this is not your job to support other libraries. Of course that was the issue.

Yet, there is one more problem. If I am at url /foo/bar, the code splitted urls are loaded from `/foo/bar/hashed.js` which leads to 404, instead of `/hashed.js`. I could not find a documentation that would force loading the file from the root

**Comment by nchanged** [comment]
Its in the code splitting section 

splitConfig
