### ISSUE TITLE
Hot module reload does not work for separate css-files in a Vue-project. 

### ISSUE THREAD

**Issue by cptnhaddock** [fuse-box/fuse-box#1422]
Hot module reload does not work for separate css-files in a Vue-project. 
Steps to reproduce:
Clone https://github.com/fuse-box/fuse-box-vue-seed
Add a new css file and a class which alters the background, i.e. 
`.my-class {
background-color: red;
}`
Add the class somewhere where it makes a difference in Home.vue, i.e.  `<div class="logos-container my-class">`
Do `npm start`
Change the background color in the css file to blue

Desired behavior:
The background color should be changed to blue in the browser

Actual:
The background color does not change

Possible solution:
plugins/vue/VuePlugin.ts on line 128, add an else and return false to let the other plugins handle the reload.

**Comment by nchanged** [comment]
@cptnhaddock thanks
Can you submit a PR please?

**Comment by cptnhaddock** [comment]
Yes, will do!
