### ISSUE TITLE
Cannot read axios package.json

### ISSUE THREAD

**Issue by maxali** [fuse-box/fuse-box#143]
Added [axios](https://www.npmjs.com/package/axios) (`npm i axios`) to my project and react-example.

When I run `node fuse.js`, it gives:
```
15:45:08 : Launching dev server on port 4444
{ message: 'File contents for C:\\react-example-master\\node_modules\\axios\\package.json were not loaded. Missing a plugin?' }
15:45:11 : Client connected
```

Browser error:
![image](https://cloud.githubusercontent.com/assets/1834466/22863120/efe8702a-f13a-11e6-88d8-7da4aa1d4584.png)

**Comment by nchanged** [comment]
Add Json plugin please, and remove your cache folder

**Comment by devmondo** [comment]
@maxali whenever there is requirement for loading `json` file, either by you locally or NPM package, `json` plugin needs to be there.

@nchanged  maybe we should include it by default ?

**Comment by maxali** [comment]
@nchanged @devmondo it works. Thanks.
