### ISSUE TITLE
Incorrect module resolution when running custom TS transformers

### ISSUE THREAD

**Issue by Gustorn** [fuse-box/fuse-box#1430]
I ran into a problem when using custom TS transformers that add new import declarations to a source file programatically. The problem is that the newly added symbols won't be handled correctly by fuse-box:

Let's take the following code snippet:

```ts
import { flow } from "mobx";
flow();
```

If it was manually written, the transpiled code looks something like this:

```js
var mobx_1 = require("mobx");
mobx_1.flow();
```

But if I generated the code with a transformer, here's what it ends up looking like:

```js
var mobx_1 = require("mobx");
flow();
```

The latter fails at runtime with a `flow is not defined` error. For a minimal repro, please see: https://github.com/Gustorn/fuse-box-transformers-issue

**Comment by nchanged** [comment]
@Gustorn FuseBox doesn't do anything special with it. It's all a default behavior. You should take a look at your transformer. 

I am not really sure what you are trying to do there, but maybe [auto import](https://fuse-box.org/docs/3.5.0/development/configuration#auto-import) will help?

**Comment by Gustorn** [comment]
Indeed, the transformer was actually wrong, it just happened to work with bundlers that use `ES2015` modules as their native format (webpack, rollup). Sorry for the false alarm!
