### ISSUE TITLE
$css make wrong path with quantum

### ISSUE THREAD

**Issue by laekem34** [fuse-box/fuse-box#1432]
Hello,

I recently started on fusebox, and I find it very convenient to manage a simple project.

I encounter a little difficulty when I want to build my application in production, I do not know if it comes from the Quantum or WebIndex plugin.
The css file comes out in the / dist / styles folder (which is wanted) but in the index.html file, the template's $ css variable returns the file at the root and not with the correct path.

I show you everything about this problem that I can not solve.

I would like the path to the css file to be generated as it should

thank you in advance

fuse.js :
```
const { FuseBox, WebIndexPlugin, SVGPlugin, CSSPlugin, SassPlugin, CSSResourcePlugin, QuantumPlugin } = require("fuse-box");
const { src, task, context } = require("fuse-box/sparky");

context({
  isProduction: false,
  getConfig() {
    return FuseBox.init({
      homeDir : "./src",
      output : "./dist/$name.js",
      useTypescriptCompiler : true,
      cache: !this.isProduction,
      hash: this.isProduction,
      plugins: [
        [
          SassPlugin({ outputStyle: 'compressed' }),
          CSSResourcePlugin({ dist: "dist/css-resources" }),
          CSSPlugin()
        ],
        SVGPlugin(),
        WebIndexPlugin({
            template : "src/index.html",,
            path: '.'
        }),
        this.isProduction && QuantumPlugin({
          bakeApiIntoBundle: "script/script",
          css : {
            clean: true,
            path: "styles/style-min"
          },
          treeshake: true,
          uglify: true
        })
      ]
    });
  },
  createAppBundle(fuse) {
    const app = fuse
      .bundle("script/script")
      .instructions("> main.js");
      if (!this.isProduction) {
        app.watch()
           .hmr();  
      }
    return app;    
  }
})

task("clean", () => src("dist").clean("dist").exec() );
task("cc", () => src(".fusebox").clean(".fusebox").exec() );

task("default", ["clean"], async (context) => {
  const fuse = context.getConfig();

  fuse.dev({open: true});
  context.createAppBundle(fuse);
  await fuse.run();  
});

task("dist", ["clean"], async (context) => {
  context.isProduction = true;
  const fuse = context.getConfig();

  context.createAppBundle(fuse);
  await fuse.run();  
});
```

Generated head index.html : 

```
  < head >
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="c6a6f72a-style-min.css"/>   // here was $css
    <title>Title</title>
  </head >


    <script   type="text/javascript" src="script/cf499958-script.js"></script>
```

My dist structure: 
  css-ressources/
  script/  cf499958-script.js
  styles/  c6a6f72a-style-min.css
  index.html

**Comment by nchanged** [comment]
Hi, that's your solution. Adjust WebIndexPlugin path variable. It's not up to Quantum to fix your public paths.
```
WebIndexPlugin({
        path: "/styles"
}),
```

I will close this issue now as i've just verified it and it works as expected. Feel free to join Gitter. You are always welcome there!

**Comment by nchanged** [comment]
@laekem34 sorry for that. I've figured out that the best way of doing it is adding additional option to WebIndexPlugin. It's available in `fuse-box@3.7.0-next.7`

Here is the [documentation](https://github.com/fuse-box/fuse-box/blob/c8239d957586518cdb81874d166b31534e5f4b1e/docs/plugins/web-index.md#resolving-paths)

I hope this option will help you!

**Comment by laekem34** [comment]
Hello !

yes of course, thanks you very much :)

an official release date for this version ?

**Comment by nchanged** [comment]
@laekem34 it's published already `fuse-box@next`

**Comment by laekem34** [comment]
Ok thank you !
