### ISSUE TITLE
Is it recommended to write fuse configuration in TypeScript?

### ISSUE THREAD

**Issue by athrunsun** [fuse-box/fuse-box#1433]
Is it recommended to write fuse configuration in TS, i.e. fuse.ts?

I can't find anything about that in official documentation. Do we have a update to date example repo for that purpose?

I love TS as fusebox did, so really want to know how is it officially supported as for configuration file.

Thanks!

**Comment by nchanged** [comment]
hi @athrunsun 
Of course you can use `fuse.ts` in fact many people do so with `ts-node`
I had ideas on making cli understand either or `fuse.ts` or `fuse.js`. But this is just in plans. If you have further questions please use our Gitter channel ;-)
