### ISSUE TITLE
problem when uglifying multi-line strings starting with escape character

### ISSUE THREAD

**Issue by wmathes** [fuse-box/fuse-box#1434]
Hello guys, first off... amazing job you're doing here! Love fuse-box and spreading the word whenever i can :p 

While trying to bundle `postgraphile` i came across a problem which only appears in combination with `fuse-box` and `uglify-es`. I wasn't able to recreate it using just `uglify-es` itself. 

If a function returns an inline multiline string, which starts with ``\` follwed by a linebreak, then the whole `return`-statement is discarded and the function returns `undefined` instead. 

I've prepared a small repo https://github.com/screencloud/fuse-box-uglify-error-sample which after `npm i` and `npm start` shows the problem easily.

This
```js
function shouldReturnSomeString(serverVersionNum) {
    return `\
x`;
}

module.exports = {
    shouldReturnSomeString
};
```

gets minified as
```js
n.exports = {
                shouldReturnSomeString: function shouldReturnSomeString(e) {
                }
            }
```

if the leading `\` is removed, any character added behind it or the string assigned to variable first, then the result is correct.

note that other functions in the same file following the broken function are eaten up completely as well.

I'm happy to dig a bit deeper, but at least for today i'm out of time and monkeypatching postgraphile solved the more immediate issue for me. If i can help to fix it though i'm happy to :)

**Comment by nchanged** [comment]
@wmathes uglify-es is no longer supported and will be removed from FuseBox soon. Please use `terser` plugin in `fuse-box@next`

**Comment by nchanged** [comment]
Any update ?

**Comment by wmathes** [comment]
Just tried it out and it seems to work. Apparently `terser` though just removes the `\` altogether, which is working, but still slightly changes the string. I won't worry about this though. 

Thanks for the heads up :)
