### ISSUE TITLE
DevTools failed to parse SourceMap

### ISSUE THREAD

**Issue by jimmybaker** [fuse-box/fuse-box#1435]
<img width="1024" alt="image 2018-11-08 at 4 24 13 pm" src="https://user-images.githubusercontent.com/50668/48231186-ee625a00-e372-11e8-8d86-b773427f7074.png">

Does anyone know how to get rid of these messages?

**Comment by nchanged** [comment]
@jimmybaker you can't really get rid of them, since it's baked into the source code, but you could try exposing `node_modules` for development purposes.

Should be clear enough ;-)
