### ISSUE TITLE
Syntax error in domain polyfill

### ISSUE THREAD

**Issue by repl-sean-heintz** [fuse-box/fuse-box#1437]
https://github.com/fuse-box/fuse-box/blob/162afc3c5da8213dc2a32be8ab142bb6f8518d32/modules/domain/index.js#L67

This line contains a syntax error as `return` is being used outside of a function. This appears to have been an artifact that was left in when adapting the polyfill for use with fusebox.

I will open a PR with my proposed fix. I've made the change in the browser editor so can someone with better eyes take a look and see if it makes sense?

**Comment by nchanged** [comment]
@repl-sean-heintz nice one thanks! That totally makes sense and has been merged! Thanks a lot!
