### ISSUE TITLE
No typescript compilation error in case of wrong syntax etc.

### ISSUE THREAD

**Issue by vldk** [fuse-box/fuse-box#144]
If in ts source files we have syntax error, there is any error messages in output. It would be nice to show TS-diagnostics messages.

**Comment by devmondo** [comment]
@vldk currently we assume that your `IDE` shows those errors, but we might introduce some `dmeon` for that!

**Comment by nchanged** [comment]
#140

**Comment by nchanged** [comment]
Moving the discussion here: #146
