### ISSUE TITLE
Processing CSS *without* adding it to virtual filesystem?

### ISSUE THREAD

**Issue by paxperscientiam** [fuse-box/fuse-box#1443]
Hey, I've scoured the docs and issues, but I cannot find an answer to this question. I thought that setting Quantum's `css` option to `false` would do it, but that hasn't been the case.

In my `index.ts`, I have the command `import "./css/app.scss"`, which is processed beautifully by the CSS processors.

Use-case: loading CSS when JavaScript is disabled. So, when JS is disabled, one cannot load CSS via FuseBox (obviously). So, I manually add the tag to my HTML so that I can support environments without JS.

The problem then is that, when JavaScript is enabled, my `app.css` is loaded twice -- once by link tag and a second time by FuseBox.

`<noscript>` works, but ... not ideal.

Thanks for your help!

**Comment by nchanged** [comment]
@paxperscientiam did you add `$css` macro to your template? It will be replaced with the generated CSS file

**Comment by paxperscientiam** [comment]
Hi @nchanged . Sorry, I should have noted that I do not use WebIndexPlugin.

**Comment by nchanged** [comment]
@paxperscientiam then you should utilise `manifest.json` in Quantum and place it there yourself.

**Comment by paxperscientiam** [comment]
I'm confused. I thought `manifest.json` was for pointing to icons for apps?

**Comment by nchanged** [comment]
Quantum [manifest](https://fuse-box.org/docs/production-builds/quantum-configuration#manifest)

You can process it with the language of your server choice and add css files to your template
