### ISSUE TITLE
Position of dynamically loaded CSS in DOM needs to be configurable

### ISSUE THREAD

**Issue by wrench7** [fuse-box/fuse-box#1444]
After upgrading from v3.3.0-next.4 to v3.6.0 I noticed that the dynamic loading of CSS scripts provided by Quantum breaks the order in which the CSS is written to the DOM.

I tracked the issue down to this line of code:
https://github.com/fuse-box/fuse-box/blob/c8239d957586518cdb81874d166b31534e5f4b1e/modules/fuse-box-responsive-api/index.js#L171

Simply changing this line to `head.appendChild(target)` fixes the issue for me. 

Perhaps we could have another macro available similar to the WebIndexPlugin $css one to target where dynamically loaded CSS (and even scripts) should be inserted into the DOM?

**Comment by nchanged** [comment]
Yes we can make it configurable. Feel free to open a PR with your suggestions. Have you tried Quantum CSS option with lazy loading yet?

**Comment by wrench7** [comment]
Yes I believe it's the lazy loading that is causing me the issues. Here's my QuantumPlugin setup:

```
QuantumPlugin({
  bakeApiIntoBundle: 'vendor',
  treeshake: true,
  uglify: true,
  replaceTypeOf: false,
  css: {clean: true},
})
```

If I was to do a PR, it would simply be to make the change I've already suggested above. Are you happy with that?

**Comment by nchanged** [comment]
@wrench7 so your fix is pretty much in `appending` not inserting before the scripts? Then yes, it should be fine. Make sure that nothing is broken ;-)

**Comment by nchanged** [comment]
@wrench7 any update on that?

**Comment by wrench7** [comment]
Hey, I hacked it locally, as I wasn't really sure that changing the code, and then having everyone's CSS appear in a different place (without the ability to toggle it) was as a great idea. I can open a PR if you're ok with me making the one change I suggested above?

**Comment by nchanged** [comment]
Good job! We will let it marinade a bit longer in the next 😉
