### ISSUE TITLE
custom cache folder

### ISSUE THREAD

**Issue by pungggi** [fuse-box/fuse-box#1445]
hello , would be nice define a custom location for the `.fusebox` folder.
https://fuse-box.org/docs/development/configuration#cache

Good job, by the way, I just started with fuse box, i love it!

**Comment by nchanged** [comment]
Hi there is in fact,please check Configuration.ts

**Comment by pungggi** [comment]
Not sure what you mean by Configuration.ts

**Comment by nchanged** [comment]
@pungggi 
https://github.com/fuse-box/fuse-box/blob/7b7a76b14f47bee0da56d804327e2697ad2e2c4c/src/Config.ts#L14

FUSEBOX_TEMP_FOLDER=.some node fuse.js
