### ISSUE TITLE
Case Sensitive Imports Plugin

### ISSUE THREAD

**Issue by RXminuS** [fuse-box/fuse-box#1448]
Hey I would like to make a plugin to check that all imports are case sensitive (we had a few bugs on certain platforms because of this) but I have no idea where to start.

Had a look at some existing plugins and the documentation but I don't really feel like I'm grasping the core concepts yet to visualize how it would fit together. And there's no clear interface or something I can implement.

Could we maybe discuss a simple / pseudo implementation here and I'll try and write the plugin and a blogpost to hopefully help others writing their first simple Fuse-Box plugin?

**Comment by nchanged** [comment]
hi @RXminuS 
[Here is](https://github.com/fuse-box/fuse-box/blob/master/docs/plugin-api.md#dependencies) some information. For some reason it's not included in the doc. But, if you want to start with something simple I'd recommend taking a look at the [HTMPlugin](https://github.com/fuse-box/fuse-box/blob/master/src/plugins/HTMLplugin.ts)

**Comment by eddyw** [comment]
There is an option in tsconfig `forceConsistentCasingInFileNames` which when true should report those errors. From my point of view, I'd be better if FuseBox read this option and decided how to treat files if case sensitive or not. I believe on Windows there is no difference when importing files with casing madness, we've had those bugs before on a typo on import that somebody on Windows have forgotten to check :P

**Comment by nchanged** [comment]
Will close this for now, feel free to propose a PR if still relevant
