### ISSUE TITLE
Typescript Helpers

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#145]
Typescript helpers 

It is required to include [Typescript helpers](http://fuse-box.org/#typescript-helpers) to user's plugin list. 

What about having a built-in support? + Fixing `tsconfig.json` setting `emitHelpers` to `false` automatically. Making it smooth!

**Comment by xdave** [comment]
So, my current solution is to use the `tslib` package and enable `importHelpers`, but this includes unnecessary helpers.  I had to do this because vscode complains that it can't find the `tslib` module when I use language constructs that need the helpers.

**Comment by guillaume86** [comment]
@xdave I'm interested in this as __rest is not in the TypescriptHelpers plugin.
How did you get the importHelpers flag to work in fusebox?
I tried adding tslib to the project and setting the flag in my tsconfig but it doesn't seem to work.

**Comment by xdave** [comment]
Use this

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "strict": true,
    "importHelpers": true,
    "lib": ["dom", "es2017"]
  },
  "compileOnSave": false
}
```

**Comment by xdave** [comment]
I am not using the TypescriptHelpers pllugin

**Comment by guillaume86** [comment]
Thanks it was probably a cache problem it works now.
