### ISSUE TITLE
ConsolidatePlugin: How to specify handlebars helpers

### ISSUE THREAD

**Issue by rope-hmg** [fuse-box/fuse-box#1450]
Hi, I am unable to find any documentation for registering handlebars helpers via the consolidate plugin.

I have the following for my plugin:

    ConsolidatePlugin({
        engine    : 'handlebars',
        extension : '.tpl',
        includeDir: 'src/templates',
    }),

The helpers live under `src/templates/helpers/`.

Also. I noticed a typo on the `ConsolidatePlugin` page.
The `includeDir` section has `engine` as the object key n the example.

Thanks

**Comment by rope-hmg** [comment]
I have worked around it manually for now. I have created a `Sparky` `task` that requires all the files and uses `Handlebars` directly to register the helpers.

**Comment by nchanged** [comment]
@rope-hmg we are passing options as is. If you want you can propose a PR on how to handle it. Will close this for now
