### ISSUE TITLE
Feature Request: Also publish Sparky as a standalone module

### ISSUE THREAD

**Issue by booninite** [fuse-box/fuse-box#1455]
I have a project that is using Sparky as a task runner, because it is simply awesome.  However, we cannot leverage fuse-box as a bundler at the moment, so we are bringing in those dependencies needlessly in our project.  It would be a huge help if Sparky could additionally be published as a standalone `npm` module.

Cheers 👍

**Comment by nchanged** [comment]
@booninite hi
Do you think you could help making a gulp task? Similar to this one?
https://github.com/fuse-box/fuse-box/blob/c8958a7b23178e71b1057cca0555cb70cbe0b67c/gulpfile.js#L216-L227

I would accept a PR for that. It's just currently the process is manual, however, linking it to the release of `@next` would automate things. I don't mind that.

**Comment by nchanged** [comment]
will close this for now.
