### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by swASO** [fuse-box/fuse-box#1456]
Before summiting an issue, please make sure that:

* You have removed the `.fusebox` folder in your project root
-> yes
* Removed node_modules, (re-installed everything)
-> yes
* Started the bundling process again.
-> yes
* Read the documentation on your subject here -> fuse-box.org
-> yes

Hi!, 

i tried to create a little test project for me but i can not get it to work, with webpack i dont have any problems, - what i am doing wrong ? 

![image](https://user-images.githubusercontent.com/4096843/50678143-99069a00-0ffd-11e9-9232-4e076aad1733.png)

if i add a `console.log({process})` into the index.jsx it also didnt work, but when i remove the `<JssProvider>` ( and also the import, everythings seems to work, also the console.log ) 

```
import { MuiThemeProvider } from '@material-ui/core';
import { Provider } from 'mobx-react';
import * as React from 'react';
import ReactDOM from 'react-dom';
import { JssProvider } from 'react-jss';
import { BrowserRouter } from 'react-router-dom';
import theme from './theme/theme';

const stores = {

};
console.log({ process })



const App = () => (
    <div>
        test!
    </div>
);

ReactDOM.render(
    <MuiThemeProvider theme={theme}>
        <JssProvider>
            <Provider {...stores}>
                <BrowserRouter>
                    <App />
                </BrowserRouter>
            </Provider>
        </JssProvider>
    </MuiThemeProvider>,
    document.getElementById('root')
);
```

[fuse-box.zip](https://github.com/fuse-box/fuse-box/files/2726280/fuse-box.zip)

**Comment by swASO** [comment]
mhm, downgrade to "react-jss": "8.6.1" works
i close this issues, seems not really a problem with fuse-box, but why works webpack then ? ¯\_(ツ)_/¯

**Comment by nchanged** [comment]
@swASO process is quite a tricky one. I think FuseBox fails to autoImport process due to the syntax. Also check your build target. If you change it to es5 it should work.

**Comment by swASO** [comment]
@nchanged Hi, thats why i attached "fuse-box.zip" 
i already set `target : "browser@es5"`

**Comment by adam-risberg** [comment]
Material-ui version 4+ uses jss version 10+, downgrading is jss is thus not an option. Is there a workaround for this issue?

**Comment by nchanged** [comment]
@adam-risberg please follow [v4}(https://github.com/fuse-box/fuse-box/issues/1527) version. It has been solved there

**Comment by denniskoenig** [comment]
Got some help in the Slack channel, as a workaround you can use the ReplacePlugin().
I had a problem that `if (process.platform === 'win32')` caused `ReferenceError: process is not defined`.

As example if someone else has the problem:
```
ReplacePlugin({
  "process.platform": JSON.stringify(process.platform)
}),
```
