### ISSUE TITLE
FuseBox doesn't report diagnostic error on tsconfig.json file

### ISSUE THREAD

**Issue by eddyw** [fuse-box/fuse-box#1457]
When certain mis-configured options are set on `tsconfig.json` file, those are not actually reported by FuseBox. For instance `{ jsx: "asd" }`

Could we use `ts.convertCompilerOptionsFromJson(...)` instead on `TypescriptConfig.ts`?
This would require to check for `typescript` to be included first.

The reason is because, `File.transpileUsingTypescript` uses `ts.transpileModule` which will transpile code despite errors or mis-configuration in tsconfig file. It does however include a `diagnostics` property (along with `outputText` and `sourceMapText`)

So, we could either check on `TypescriptConfig.ts` or in `File.transpileUsingTypescript` for diagnostic errors on tsconfig file.

Opinions/ideas?
From tsconfig containing `{ ..., jsx: "asd" }`, this is the diagnostic error that should be displayed:
```javascript
Argument for '--jsx' option must be: 'preserve', 'react-native', 'react'.
```

**Comment by nchanged** [comment]
Fair enough , do you know how to fix that? Can you propose a PR?

**Comment by eddyw** [comment]
@nchanged yes, I'm working on it. I'll have a PR in a couple of days or so

A couple of questions:
- we're currently not catching syntax errors. `transpileModule` will try to "repair" broken code and will always transpile but enabling diagnostics we can catch syntax errors. Catching syntax errors is not the same as type errors, so it shouldn't affect transpilation time. It's basically:
```javascript
	private getTranspilationConfig() {
		return Object.assign({}, this.context.tsConfig.getConfig(), {
			fileName: this.info.absPath,
			transformers: this.context.fuse.opts.transformers || {},
			reportDiagnostics: true, // <<< reports syntax and global errors
		});
	}
```
Note:
- global errors are errors without filename such as the ones in the tsconfig file
- syntax errors is just bad JS/TS code that shouldn't be "repaired"
- doesn't do type-checking

Should we do this with a flag? I don't know, such as `reportSyntaxErrors: true` to enable it? or enable always by default?

- Another thing is that, we only check if `typescript` is installed within the `File.ts` on `transpileUsingTypescript` function. However, in `FuseBox.ts` we include `TypescriptConfig.ts` which assumes `typescript` is installed without checking (there is an ts import and the `read` function). How to better handle this? I currently added a `ensureTypescriptInstalled` function to `Utils.ts` which does:
```typescript
export function ensureTypescriptInstalled() {
	try {
		require.resolve('typescript');
	} catch (error) {
		if (error && error.code === 'MODULE_NOT_FOUND') {
			throw new Error(`Option "useTypescriptCompiler" requires "typescript" module to be installed`);
		}
		throw error
	}
}
```
Which checks if `typescript` is resolvable when `useTypescriptCompiler` is truthy. However, as mentioned before we include later on in `FuseBox.ts` the `TypescriptConfig.ts` file, so it's a bit confusing where this check should be :P

**Comment by nchanged** [comment]
* How will `reportDiagnostics` affect the overall performance? We could include it by default if doesn't affect it.
* The check should anywhere where we use typescript ;-)

**Comment by eddyw** [comment]
- I still don't know. I'd set a flag, later on we can test if has a negative effect or performance or not. If negative, defaults to false, if not then true but we can leave the option for the user to enable/disable for whatever reason
- I feel this may break some things. For instance, in `FuseBox.ts`, there is:
```typescript
		const tsConfig = new TypescriptConfig(this.context);
		tsConfig.setConfigFile(opts.tsConfig);
		this.context.tsConfig = tsConfig;
```
which doesn't check if `typescript` is installed but `TypescriptConfig.ts` imports it and other files such as `Bundle` and `VuePlugin` use it regardless of `typescript` being installed or not. Any idea how it'd be best?

**Comment by nchanged** [comment]
I think we should require typescript to be installed. Maybe in FuseBox.ts right on start?

**Comment by eddyw** [comment]
What about people who use it without TS? with `useTypescriptCompiler` set to `false`?
Or .. add it as `peerDependency` maybe?, so the user can know that once installing FuseBox, NPM will scream `I need typescript` :P if so, then we'd need to specify minimal version of TS package as well. Then check on `FuseBox.ts` at start.

**Comment by nchanged** [comment]
@eddyw TS is required by default, since it might transpile node_module in the background ;-)

**Comment by eddyw** [comment]
@nchanged I worked a bit on this today and.. thanks to diagnostics I found out that `ESNext` points to wrong target on latest TS version (not sure if enums changed).

In FuseBox:
```typescript
export enum ScriptTarget {
	ES5 = 1,
	ES2015 = 2,
	ES6 = 2,
	ES2016 = 3,
	ES7 = 3,
	ES2017 = 4,
	ESNext = 5,
}
```
In TS:
```typescript
   enum ScriptTarget {
        ES3 = 0,
        ES5 = 1,
        ES2015 = 2,
        ES2016 = 3,
        ES2017 = 4,
        ES2018 = 5,
        ESNext = 6, // <<<< 6
        JSON = 100,
        Latest = 6
    }
```
Could we use instead `ts.ScriptTarget`? so it'd be more dependent on the TS version installed rather than having it hard-coded which could be inconsistent as those enums differ from different TS versions.

Only "breaking-change" would be that there is no actual ES7. When `{ target: 'es7' }` displays:
```javascript
error TS6046: Argument for '--target' option must be: 'es3', 'es5', 'es6', 'es2015', 'es2016', 'es2017', 'es2018', 'esnext'.
```
Or in older version of TS:
```javascript
error TS6046: Argument for '--target' option must be: 'es3', 'es5', 'es6', 'es2015', 'es2016', 'es2017', 'esnext'.
```
This would help the user to know what the target can be according to the TS version installed. It should probably require some changes in `LanguageLevel.ts` and some other places. To facilitate this, FuseBox could require a minimal version of TS to be installed which has `ES2017` at least (used in `LanguageLevel.ts` when `const` found). Or another option, just use `ts.ScriptTarget.Latest`

Thoughts?

**Comment by nchanged** [comment]
@eddow that I noticed too (VSCode reports that) Could you fix it? Also in tsconfig generator.

**Comment by eddow** [comment]
That was confusing :D (I guess a misstype)
