### ISSUE TITLE
Can we have type-checking plugin officially?

### ISSUE THREAD

**Issue by eddyw** [fuse-box/fuse-box#1458]
TS supports incremental compilation as well as type-checking only files that have changed. I've been doing some testing and we can even cache the diagnostic errors of the files that we type-checked and trigger new type-checking only on the files that have changed and its dependents without having to trigger whole project type-check.

Is it possible to have a good TS checker integrated within FuseBox's plugins officially?

I'm aware of the `fuse-box-typechecker` project but it runs kind of separately from FuseBox. The advantage of using the plugin is that we can take advantage of the existing cache to save diagnostic errors of files that we analysed before and use the same config that FuseBox has as well as stopping compilation earlier. Initially first compilation would of course be a bit slower but once cached, it'd be pretty quick. Since it's a plugin, it wouldn't affect existing users unless used.

I'm currently working on this since it's something I'd love to have for upcoming projects where we're considering using FuseBox + TS and most of all having fast type-checking integrated.

Opinions/Ideas? :)

Having it officially in FuseBox plugins would facilitate other to contribute directly as well :P

**Comment by nchanged** [comment]
@eddyw That's a good idea, I've been thinking myself of integrating the existing type checker, I think it pretty stable. But, if you are saying there is a solution that does it faster/or better, please suggest.

Regarding caching - I don't think we can take advantage of it, since the diagnostic are should be ran against the entire project, otherwise it won't make sense. Imagine changing an interface in one place, which affects 50 other files scattered all around the project.

**Comment by eddyw** [comment]
It's not completely true. If using language services (as if FuseBox was a code editor), it can trigger type-check in dependent files only for the types that have changed. For instance, vscode does this pretty fast and doesn't do whole project type-check. Actually, it triggers only type-check on the current file being edited for the type that has changed. The un-changed type declarations are kind of cached in a document registry which keeps the files versioned.

So, it'd be like:
- If cached, add `version` and `diagnostics` to the file (contents are already cached)
- Type-check file if it wasn't before
- If file changed, change `version`
--- Get diagnostics for the current file. If has errors, display
--- Get diagnostics for its dependents only for the types that have changed in current file. As the TS document registry can get `version` of all files, it'd know which ones have changed

It's a work in progress and theoretically would be faster that doing whole project type-check. There are other factors though.

The idea is to treat FuseBox as if it was a code editor doing type-check. It'd take some time and [issues/1457](https://github.com/fuse-box/fuse-box/issues/1457) is a first step which does the global type-check on the tsconfig only
