### ISSUE TITLE
Window unavailable in worker

### ISSUE THREAD

**Issue by bkniffler** [fuse-box/fuse-box#1460]
Hey,
this is basically the same issue like webpack had: https://github.com/webpack/webpack/issues/6642
This makes it difficult to use worker with dependencies that rely on window.xxx.

Their solution is an option like this: 
```
output: {
  globalObject: `(typeof self !== 'undefined' ? self : this)`,
},
```

**Comment by nchanged** [comment]
I think use can use Banner plugin for that, but yes we would need a separate plugin for that. It can be based on Banner Plugin

**Comment by bkniffler** [comment]
Good to know. I will let you decide if you want to add that as a quality of life functionality, but I guess the banner plugin will be sufficient, though not super obvious for newcomers. Maybe its enough to have this in the issues, so people who search for that will get on the right track.

**Comment by nchanged** [comment]
@bkniffler well that plugin would make life much easier, since one would need to give it an object. If you want to help and introduce this plugin please go ahead ;-) That would be a real help. You can take a look at BannerPlugin and how it injects custom strings.

**Comment by bkniffler** [comment]
I've created a PR!

**Comment by bkniffler** [comment]
I think the PR is not really required. If you want to make window available in your worker (maybe due to some dependencies you are using check for `typeof window !== "undefined"` to figure out if you are in a browser environment, you could:

```
BannerPlugin(
"var window = typeof self !== 'undefined' ? self : this;"
)
```
