### ISSUE TITLE
Doubts about the css group API

### ISSUE THREAD

**Issue by LucasIcarus** [fuse-box/fuse-box#1469]
https://github.com/fuse-box/fuse-box/blob/ef6074289b206128f9ad32d3c133f9c1b55ec8b2/src/quantum/plugin/modifications/CSSModifications.ts#L81-L94

Recently, I create a project with fuse-box. It's a internal platform with multi-SPAs which shared the same static first level navigations within a base template rendered by Node.js.

For create multiple SPA level stylesheet and js for docking old publish system which had abuse of file structure, some hard code was written with Context API of Sparky.

Here I produce a demo project to simulate the situation.

https://github.com/LucasIcarus/fuse_css_group_demo

Here are some discoveries through the project set up.

- the cssFile.packageName was locked to `default`

- the filename of cssFiles default fallback was locked to `style.css`

- since `key.split("/", 2)` and `string2RegExp(pattern)`, the key of cssFiles Object is hard to organize.

- filenames of css would inherit $hash but would not respect the order set within `output`

- there was no bundled event which the API of fuse-box could reach.

These doubts above most probably caused by my personal carelessness of reading docs or for some special design purposes. 

Thanks for your time.

**Comment by LucasIcarus** [comment]
reopen after editing.

**Comment by nchanged** [comment]
I am not entirely understanding the purpose of splitting to many CSS files. Isn't better to have it all in one file? Just use Gzip. Besides with code splitting it will be automatically lazy loaded.

**Comment by LucasIcarus** [comment]
Split css files is kind of traditional strategy, avoid potential className conflicts...

**Comment by LucasIcarus** [comment]
tried lazy load, perfectly match!

thanks a lot. @nchanged
