### ISSUE TITLE
emitHMRDependencies is undocumented 

### ISSUE THREAD

**Issue by TylorS** [fuse-box/fuse-box#1476]
I've been working on a project using fusebox and have come to realize this configuration option is currently undocumented. It seems like the intended use case is for custom hot module replacement plugins. Is that correct? 

I'm currently making use of the values directly through `Bundle.context.dependents` while listening to file changes using the `BundleProducer.sharedEvents.on('file-changed', ...)` API. I'm also wondering if this is an okay/stable API for me to rely on?

**Comment by nchanged** [comment]
Yes, it's stable.I am not sure why this feature is undocumented , could you
help out on this one?
