### ISSUE TITLE
Question: is there a way to get `fuseBoxPath` from dependencies?

### ISSUE THREAD

**Issue by eddyw** [fuse-box/fuse-box#1479]
Hey,

I'm working on a plugin which requires knowledge of dependencies of a file. What I currently do is in `transform` get `file.analysis.dependencies` if:
```typescript
import foobar from './foobar'
...
```
I get `['./foobar']`. However, I couldn't figure out if there is a way of getting the `fuseBoxPath` from it. Doing `this.context.convertToFuseBoxPath('./foobar.ts')` I get `./foobar.ts` expecting `foobar.ts` instead which is what `file` (pointing to `foobar.ts`) shows in `file.info.fuseBoxPath`. Ideas?

**Comment by nchanged** [comment]
@eddow basically I am working on a branch (WIP) 
https://github.com/fuse-box/fuse-box/commit/a318900677456a09eb95eb85810ce4f377952b18
Lookup for ModuleCollection.ts and `resolvedDependencies` this should give you an idea

**Comment by eddow** [comment]
@eddyw  :">

**Comment by eddyw** [comment]
@eddow he did it again 🙈:')
@nchanged I had a quick look but I noticed that it still doesn't show `file.resolvedDependencies` in `transform` or `onTypescriptTransform`. I figured that it's because it happens async while `transform/onTypescriptTransform` is executing. I added an ugly `setTimeout` in `transform`:
```typescript
setTimeout(() => {
	console.dir({ resolved: file.resolvedDependencies }, { depth: 1 }) // [File, File]
}, 2000)
console.dir({ resolved: file.resolvedDependencies }, { depth: 1 }) // []
```
Is there a way to wait for it in `transform` or `onTypescriptTransform`?

**Comment by nchanged** [comment]
my lord, you aren't the same, I've just figured it out xDD sorry
@eddyw the easiest way for you in this situation is to resolve it manually

```
const resolvedInfo = this.pm.resolve(name, file.info.absDir, fileLimitPath, file);
```

**Comment by eddyw** [comment]
@nchanged hmm, I'll wait until your branch is merged. I've been working on type-checking plugin and besides the path info I'll need the `file` itself (as in `file.resolvedDependencies` in your branch) to notify the language service to do type-check on resolved dependencies. Otherwise, well, it won't :P 

I'll probably submit a PR tomorrow if I can as WIP. It's working well (despite the limitation of not being able to notify dependencies .. yet), I achieved caching diagnostics, so it doesn't type-check at all when re-running `fuse.js` with cache initially, just loads the previous diagnostics from cache :D, then does partial/incremental type-check only on files that have changed.

**Comment by nchanged** [comment]
@eddyw I was thinking... if you have a good working (and fast) type checking plugin, it would make sense to integrate it directly to FuseBox behind an option
