### ISSUE TITLE
Discussion: FuseBox TypeScript type-checking

### ISSUE THREAD

**Issue by eddyw** [fuse-box/fuse-box#1480]
Hey,

I've been working on integrating TS type-check on FuseBox since it's something all known bundlers seem to be missing out of the box. Since FuseBox has first class support for TS, it just seemed right. So these are the ideas I had, broken in several steps:
- Global type-check of `tsconfig` file (merged [issues/1457](https://github.com/fuse-box/fuse-box/issues/1457))
- Improve the check of `tsconfig` file (merged [pull/1484](https://github.com/fuse-box/fuse-box/pull/1484)):
  - use `ts.readConfigFile` to read the `tsconfig.json` file which reports errors in JSON file using diagnostics which will help us map and display nicely which line is wrong (like missing `,`). Since previous was merged, this is next :)
  - I realized that some diagnostics should be ignored, such as errors in `rootDir` and `files` which FuseBox doesn't use or need, so reporting those errors is irrelevant
  - `transpileModule` is now reliable since now we're checking `compilerOptions`. However, it doesn't report syntax errors, `Acorn` parser does.. at some extent but doesn't catch always. I don't know if it'd affect performance implementing it, so I left the task to `Acorn` but probably it should be enabled if full-type check
- TS type-checking - I'm working on a plugin but as @nchanged mentioned in [here](https://github.com/fuse-box/fuse-box/issues/1479#issuecomment-458831563) if it works well and it's fast it could be integrated behind a flag. This is currently a blocker until merged -> [hmt-request-missing-deps](https://github.com/fuse-box/fuse-box/commit/a318900677456a09eb95eb85810ce4f377952b18) since resolved dependencies is needed
- resolve tsconfig `paths` (WIP [pull/1495](https://github.com/fuse-box/fuse-box/pull/1495))

I've been doing some research on how to fasten type-checking using TS language services. This is what I took:
- There is a document registry which keeps source files versioned and re-uses the files that have not changed. Ideally, we should cache all files `{ source: [TS original code], version: [number], diagnostics: [previous errors/warnings] }` and re-hydrate the registry from cache, so it'd spend less time looking for files and analysing
- at creation of language service, an array of filenames should be provided. These are the files that are actually "watched" for changes. Currently I populate the array on every call to `transform` (in plugin), so we can know which files were added/removed. If file is not reference anywhere anymore, it is removed from document registry (clear from memory, otherwise high memory usage over time if using `watch` in FuseBox). However, one of the slowest things when it is when it has to look for a file that we didn't provide in the array. For example, `import * as fs from 'fs'` triggered a lookup in `node_modules` in current directory, then on dirs and files named `fs` and `@types/fs`, etc. Maybe a way to fasten this, it'd be to check if `@types/*` exists and add all filenames to this array of filenames. However, user may provide their own in `include` in `tsconfig.json`, so I don't know yet how to deal with such situations.

**Comment by nchanged** [comment]
@eddyw hey,
Great job on the tsconfig btw ;-)

There are few things that come to mind, my mind flow:

* When a file is changed, we should take into consideration not only its dependencies but the **dependants** too, basically it should go both ways. That may result in grabbing pretty much the entire project (reading it into an object) which will degrade the performance - it will make a drastic impact on the memory consumption. 

FuseBox consume quit a lot of RAM, since it retains everything in memory already.

* If we are going for providing a list of files for diagnostic (as opposed to feeding it a directory), that should be in a separate nodejs process  which might complicate things a bit, since we might need to send some of the configuration to the slave. (But somewhat I think it's not required, since a TypeScript checker is already strict by nature). 

* On the other hand, let's take VSCode and its type checking capabilities. It's pretty good but there is no actual visual feedback of the affected / errored files unless you open them.

Have you seen [this](https://github.com/fuse-box/fuse-box-typechecker) @vegarringdal put a lot of efforts in making it work. And it's not the simplest implementation.

**Comment by eddyw** [comment]
Yes, I've seen the fusebox type-checker. However, I want to take advantage of TS incremental compilation [(language service)](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#incremental-build-support-using-the-language-services) which can be faster.

VSCode consumes a lot of memory and makes use of the language service. Using language service, all files are kept in a document registry, when a file is required twice, if it exists in the registry already and has not changed, then diagnostics are pretty fast to get because the registry keeps the files versioned (similarly as `git` in memory). There is a comment here
https://github.com/Microsoft/TypeScript/blob/5d3685d04167aa6fad77d961236fcaff759ffbe3/src/services/documentRegistry.ts#L11-L12
which is what I'm trying to achieve. If a file has not been seen before, the language service will lookup for it in all relative directories and this is the most time consuming task. I've done a benchmark on a single file that takes around ~1s to type-check but re-hydrating the registry is goes down to ~200ms. Then, as previously analysed files exist cached in the registry, type-checking another file which uses the same types but different content, it takes ~30ms.

It's a [space-time tradeoff](https://en.wikipedia.org/wiki/Space%E2%80%93time_tradeoff). If using one process, it can cache and access the cache of the registry and incremental compilation gets faster, for instance when `watch`ing in FuseBox.

I'm taking as an example `ts-node` which does exactly this under the hood:
https://github.com/TypeStrong/ts-node/blob/master/src/index.ts#L307-L322
and it handles pretty well I'd say big projects. So I'm thinking to stick to the plugin first and see if it's a viable solution to be integrated within FuseBox itself behind an option.

**Comment by vegarringdal** [comment]
Nice.

How does that work if the edit you do, breaks another file?
Because its referencing the file you edited ?


If you manage to build some awesome fast plugin then that would be great fusebox.
So keep up the good work :-)

**Comment by eddyw** [comment]
@vegarringdal  If file `a` changes and it's referenced in `b` and `c` but not in `x`, only `a` source and version is updated in document registry, for `b` and `c` only get new diagnostics (file content has not changed in neither of both).

I realized that walking through dependencies may not have so much performance gain as to asking new diagnostics for all files (after cache them all in registry). Well, depending if the file is referenced or not. Anyways, there is performance gain on caching itself, so it's still a win.

@nchanged I'm working on improving the checking in tsconfig file which shows which line|column in `tsconfig` is wrong:
![image](https://user-images.githubusercontent.com/1407526/52142172-eaed1f00-2692-11e9-956d-944a6c2fdf31.png)
![image](https://user-images.githubusercontent.com/1407526/52142174-ede80f80-2692-11e9-9c45-96411dde5647.png)
Currently, for displaying errors on FuseBox format, it was adding an arrow on front and capitalizing the `error|warning` word. However, probably we'd need a custom formatter of diagnostics to display it as FuseBox errors/warnings format. TSLint has its own, so maybe we can get inspired by it and make one for FuseBox? For now, I'll use the ts formatter which is pretty enough for first implementation.

On a different topic, I figured out how TS solves `paths` aliases from `tsconfig` using `ts.resolveModuleName`. Would it be a good idea for automatic aliasing to use instead `paths` of `tsconfig` to resolve those aliases? or .. somehow?
This is the output for resolving `"paths": { "@app": ["./foobar"] }, baseUrl: "./src"`:
```js
{ resolvedModule:
   { resolvedFileName: 'src/foobar.ts',
     originalPath: undefined,
     extension: '.ts',
     isExternalLibraryImport: false,
     packageId: undefined }
```
Ideas? I haven't seen known bundlers *not* to ignore `paths` and always do it behind some plugin or external library. It'd be nice if the config could be honored and `paths` taken into account and resolved :)

**Comment by nchanged** [comment]
That would be terrific! Fusebox supports aliasing I only on the root directory, if we could automate it that would be a great improvement! btw I did a nice progress on HMR. It can hydrate the modules with missing dependencies and (hopefully) update in-memory source maps )

**Comment by eddyw** [comment]
@nchanged cool, I'll add it to my to-do list then :D
I'll check those new changes on HMR :)
Btw, I made some progress myself on improving tsconfig check:
![image](https://user-images.githubusercontent.com/1407526/52154609-9e690a00-26b9-11e9-968c-8f7878407658.png)
- refactored a bit `read` on `TypescriptConfig`
- displays line|column and source text of where is wrong

![image](https://user-images.githubusercontent.com/1407526/52154680-f30c8500-26b9-11e9-96b6-8315f4b99f62.png)
- the config file is `tsconfig.json` but reports errors on `tsconfig2.json` (because using `"extends": "./tsconfig2.json"`)

![image](https://user-images.githubusercontent.com/1407526/52154748-251de700-26ba-11e9-9b12-0018ed128eea.png)
- report errors on `customTsConfig` when array. On test `tsConfig: [{ target: 'ES2019' }, { jsx: 'asd' }],`. I'm not sure how to best display the errors. It makes sense to me but I'd like a second opinion :P . I can't read the `fuse.js` file itself and locale the faulty lines. That'd amazing .. but pretty expensive to do xD

Currently the formatting of the errors is done with some trickery using `replace`, `split` and `map` to make it pretty but ideally we'd need own formatter for FuseBox which should be faster. Also in to-do but for now it's just okay. It doesn't need to be super performant because anyways the process will exit after.

**Comment by vegarringdal** [comment]
> I realized that walking through dependencies may not have so much performance gain as to asking new diagnostics for all files (after cache them all in registry). Well, depending if the file is referenced or not. Anyways, there is performance gain on caching itself, so it's still a win.

I pass inn pass in old program on files changed, thats why recheck time go down.
Giving a update on all errors to end user on edits with nice setup tured out pretty nice. Of course when there is a 100++ errors it might be a bit messy.
But anyways, will be cool to see how your solution works out in the end. Giving fusebox users more options will be good, especially if its built in and works without any config :-)

**Comment by vegarringdal** [comment]
Just started started on version 3 of the type checker.

Tested it on the fusebox repo

```
var checkerWatch = require("fuse-box-typechecker").TypeChecker({
  tsConfig: "./src/tsconfig.json",
  basePath: "./",
  // tsLint: './tslint.json',
  name: "checkerWatch",
  tsConfigOverride:{
      compilerOptions: {
        "skipLibCheck": true
      }
  }
});

checkerWatch.runWatch("./src");
```

First run tok about 5-6sec on both.
Tok a random file and just did a save to trigger watch.
Version 2.12.0 after first run stayed around 3,5 sec.
Version 3.0.0-next.2 after first run stayed around 1,8-2 sec.
This was inside a virtual pc- 9 year old, might go faster on something better 😂 


![image](https://user-images.githubusercontent.com/2901416/61598458-962c6900-ac1e-11e9-90a5-4085e0ac2bb8.png)
