### ISSUE TITLE
Discussion: FuseBox 4.0 Changes and suggestions

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#1483]
Hey dear fusers, It's time to make some breaking changes and major improvements to FuseBox.

## HMR
We all know it's not perfect. So here is what's coming in FuseBox 4.0 (that's actually the reason why I decided to go for a major release).

### Automatic dependency hydration. 
We all know this annoying moment when you create a  **new file** and you need to refresh the page in order to make it work? Well. guess what. I've fixed it already and it's coming in the next `@next` version.

When receiving an HMR update we send parsed dependencies along. Once received, we verify whether the received files are registered in the scope, if some missing - we send a request (via socket) to the running instance to get those files.  

### Working source maps after an HMR update

Source maps is a very delicate thing to handle, And I though that i had fixed it a few months ago, but it is in fact still broken. But the changes I made recently fixed the hydration of the new content with properly mapped source maps.  Breaking changes are here.

```
const customizedHMRPlugin = {
    hmrUpdate: ({ type, path, content, dependencies, dependants }, socket) => {
        if (type === "js") {
            FuseBox.flush();
            FuseBox.consume(content); // FuseBox.dynamic will no longer work with the sent content
            if (FuseBox.mainFile) {
                FuseBox.import(FuseBox.mainFile);
            }
            return true;
        }
    },
};
```

FuseBox no longer sends the raw content, but a properly mapped one with `FuseBox.package` and `FuseBox.__scope__`. The trick here is to add fuse' headers (wrap the content), shift the source maps by 2 lines (since `new Function()` adds an extra 2 lines of code) and voilà! We have a perfectly mapped anonymous function with embedded source maps! 

---

More updates are coming, please post your ideas/suggestions. And any help is greatly appreciated. Let's make this happen!

**Comment by nchanged** [comment]
@eddyw you mean that autoImports that import a module by a variable? How come we need to involve tsconfig.json?

**Comment by eddyw** [comment]
@nchanged sorry, I meant automatic aliasing 🙈

**Comment by nchanged** [comment]
@eddyw brilliant, I will release 3.7 today, after that we can start making some order ;-)

**Comment by NN---** [comment]
My biggest concern about FuseBox that WebPack is so popular that there are not enough devs who will use it.
If there was a conversion tool from WebPack to FuseBox that could really help.
It is not needed to be generic conversion, just support Angular CLI and Create React App based projects for instance.

**Comment by nchanged** [comment]
@NN--- I know, but I can't deliver it all. I am not working with angular for example.

**Comment by NN---** [comment]
I mean that if you can have conversion tool to what "ng new" creates, it will be sufficient.

**Comment by DaveO-Home** [comment]
@NN--- @nchanged I have a howto demo on using webpack and fuse-box  with Angular and React
at 
```
   github.com/DaveO-Home/embedded-acceptance-tests-ng
   github.com/DaveO-Home/embedded-acceptance-tests-react
```
the conversion is trivial....

**Comment by jpike88** [comment]
FuseBox.consume breaks, i get this error

```Uncaught ReferenceError: client is not defined```

my path looks like this:

```client/src/components/ng2/app/login/login.component.js```

maybe aliasing is interfering?

**Comment by nchanged** [comment]
#1527
