### ISSUE TITLE
target electron requires  ignoreModules: ["electron"] for renderer

### ISSUE THREAD

**Issue by Zaitsev** [fuse-box/fuse-box#1490]
It would  be nice to inject `electron` by default to ignores if target electron

**Comment by jeremy-coleman** [comment]
really you should only need to transpile your src directory if targeting electron, all the vendor stuff can just stay in node_modules

**Comment by nchanged** [comment]
@jeremy-coleman the more you bundle with electron the better. It's known to affect the CPU badly, and `require` is very slow there

**Comment by jeremy-coleman** [comment]
I have noticed electron runs really slow with fusebox (at least in dev) for some reason, i've compared the same app between browserify ,webpack and fusebox, and the one running under fusebox is always significantly slower and i cant seem to pin down why

**Comment by nchanged** [comment]
@jeremy-coleman it should be faster when using Quantum and bundle most of the dependencies

**Comment by Zaitsev** [comment]
> I have noticed electron runs really slow with fusebox (at least in dev) for some reason, i've compared the same app between browserify ,webpack and fusebox, and the one running under fusebox is always significantly slower and i cant seem to pin down why

Could you provide some test-cases?

I tested it many times and I don't see any significant performance difference between webpack and fuse in my electron app. But only in production (Quantum-ed) mode
