### ISSUE TITLE
Applying automatic alias based on baseUrl in tsconfig.json stopped to work in version 3.7.0

### ISSUE THREAD

**Issue by mvladic** [fuse-box/fuse-box#1491]
Let me show how I use fuse-box as short as possible.

In `fuse.js`:

```
...
const fuse = FuseBox.init({
    homeDir: "src",
...
const bundle = fuse.bundle("app").instructions(" > index.tsx");
...
```

In `src/tsconig.json`:

```
{
    "compilerOptions": {
        ...
        "baseUrl": "."
    }
}
```

In `src/index.tsx` I'm importing `src/app/app.tsx` like this:

```
...
import App from "app/app";
...
```

In version 3.6.0 this worked and during the build following was printed:

```
...
  → Applying automatic alias based on baseUrl in tsconfig.json
  → 
        app => "~/app"
...
```

In version 3.7.0 there is no such note, but following is printed:

```
...
→ WARNING Statement "App.js" has failed to resolve in module "app"
...
```

P.S. In version 3.7.0 there is a bug fix:

- tsconfig baseURL and automatic alias [3d7e228](https://github.com/fuse-box/fuse-box/commit/3d7e228)

I don't know what was the purpose of that fix but maybe it could be the reason why above scenario stopped to work in version 3.7.0.

**Comment by nchanged** [comment]
Hi, I personally made sure that automatic aliases are working before the release. Do you think you can reproduce it?

**Comment by nchanged** [comment]
@mvladic `fuse-box@3.7.0-patch.1` it should be patched here. Could you verify it? As soon as it's verified I will release `3.7.1`

Sorry for breaking you build.

**Comment by mvladic** [comment]
@nchanged Yes, I'm running on Windows.

I tried 3.7.0-patch.1. It now includes all the code, but now I have some other problem. I'm using styled-components which imports `stream`. I noticed, on version 3.6.0, `stream` looks like this:

```
FuseBox.pkg("stream", {}, function(___scope___){
___scope___.file("index.js", function(exports, require, module, __filename, __dirname){
if (FuseBox.isServer) {
	module.exports = global.require("stream");
} else {
	module.exports = function() {};
}
});
```
and on version 3.7.0[-patch.1] it look like this:

```
    FuseBox.pkg("stream", {}, function(___scope___) {
        ___scope___.file("index.js", function(exports, require, module, __filename, __dirname) {
            if (FuseBox.isServer) {
                module.exports = global.require("stream");
            } else {
                module.exports = {
                    Stream: require("stream-browserify")
                };
            }
        });
        return ___scope___.entry = "index.js";
    });
```
So, `stream-browserify` is now used in the browser. But, importing "stream-browserify" fails with package `util` not found:

```
require("stream-browserify") -> 
require('readable-stream/readable.js') ->
require('./lib/_stream_readable.js') ->
require('util') -> not found!
```

I also tried on the Mac, both 3.7.0 and 3.7.0-patch.1, and both versions work exactly like 3.7.0-patch.1 on Windows.

**Comment by nchanged** [comment]
Ok so the automatic alias is solved, the problem is with stream now. Can it be reproduced by just using the Stream?

**Comment by mvladic** [comment]
Yes, if I just import `stream` in `index.ts` I will also get `Uncaught Package not found util` error in browser.

index.tsx:

```
import { Readable } from "stream";
console.log(new Readable());
```

**Comment by eddyw** [comment]
@mvladic could you possibly share your `tsconfig.json` file? and FuseBox options passed to `init`? (more interested in `tsconfig` option, if array and has over-writes, then which options)

**Comment by mvladic** [comment]
Here is the complete repository:

https://github.com/mvladic/test-fuse-box-1

**Comment by nchanged** [comment]
@mvladic https://github.com/fuse-box/fuse-box/releases/tag/v3.7.1
