### ISSUE TITLE
Quantum replaceProcessEnv: false breaks React ap 

### ISSUE THREAD

**Issue by Zaitsev** [fuse-box/fuse-box#1492]
for FuseBox 3.7 and 4.0next.5
```javascript
 EnvPlugin({ NODE_ENV: isProduction ? "production" : "development" }),
QuantumPlugin({
                bakeApiIntoBundle: 'app',
                target: 'browser',
                treeshake: true,
                sourceMaps: { vendor: false },
                replaceProcessEnv: false,
                removeExportsInterop: false,
                replaceTypeOf: false,
                uglify: false,
                terser: false
            })
...
   app.instructions(">index.jsx + fuse-box-process");
```
`replaceProcessEnv: false`  produces error `ReferenceError: process is not defined` which is expected since browsers don't have process, but from [EnvPlugin](https://fuse-box.org/docs/plugins/replace-plugin) docs

>Creates environment variables that can be accessed at build or run time

so I believe `process.env` should be added by fuse (and its added in dev-mode) but it missing in production bundle.

I've add  '+ fuse-box-process' but treeShake removes it

`  → tree shaking: Mark for removal process/index.js`
and without treeShake both reacts included 
```json
{
 "modules/react/cjs/react.production.min.js": 7618,
  "modules/react/cjs/react.development.js": 37026,
}
```
I've tried by [docs](https://fuse-box.org/docs/plugins/replace-plugin#notes)
` ReplacePlugin({ "process.env.NODE_ENV": JSON.stringify("production") }),`
but got 
```
Launching quantum core
  → Generating abstraction, this may take a while
{ SyntaxError: Unexpected token (40:0)
```

I've create repo with bug https://github.com/Zaitsev/react-example

**Comment by nchanged** [comment]
I will check , but maybe that's why it's on by default?

**Comment by Zaitsev** [comment]
> I will check , but maybe that's why it's on by default?

Yes. you are right. But I believe that settings above should at least add process.env  and not remove `process` injection if docs are consistent

**Comment by kwhitley** [comment]
@Zaitsev @nchanged - what was the solution to this?  I'm running into the same issue (with the react cjs loader dep when quantum building)

**Comment by kwhitley** [comment]
@nchanged Specifically I've been able to isolate the break to importing and using the following package in my deps:
https://www.npmjs.com/package/auth0-js

Implementation can be as simple as:
```js
import auth0 from 'auth0-js'
const test = auth0
```

Fails with:
![image](https://user-images.githubusercontent.com/865416/55033248-b20d5e80-4fe0-11e9-922a-f79584eff12b.png)

Hope that helps!

**Comment by kwhitley** [comment]
More specifically here (within the module):
![image](https://user-images.githubusercontent.com/865416/55033836-02d18700-4fe2-11e9-8226-1bedcc622fe0.png)

**Comment by kwhitley** [comment]
...which is a reference to an internally defined function named simply "process"

![image](https://user-images.githubusercontent.com/865416/55033932-44fac880-4fe2-11e9-84bd-aad018694c99.png)

**Comment by kwhitley** [comment]
Renaming the function to `process2` and the assignment to: 
`process: process2`

Solved the process failure issue... of course, this would require a fork/replacement of the pretty mainstream `auth0-js` lib to resolve.  Is there a way in the Quantum config/options to avoid this collision?

**Comment by nchanged** [comment]
@kwhitley I will make sure it won't happen in `v4` which is being cooked ATM. There will be a lot of improvements to speed and quality ;-)

**Comment by kwhitley** [comment]
@nchanged - let me know if you could use any help testing v4!  Love this builder, and now advocate it throughout my company, use it on all my personal projects, etc.  Such a breath of fresh air over the cumbersome webpack builds, and honestly, lightning fast in comparison as well...

**Comment by nchanged** [comment]
@kwhitley `v4` will be 7x-10x faster than `v3` with much less configuration ;-) Follow the updates on twitter, I will post and updated, when there will be something to test ;-)
https://twitter.com/FuseBoxJS
