### ISSUE TITLE
Using dependencies with non-transpiled src code

### ISSUE THREAD

**Issue by bkniffler** [fuse-box/fuse-box#1498]
Here is an example repo: 
https://github.com/bkniffler/fuse-box-rn

## Background
By building a react-native-web (https://github.com/necolas/react-native-web) based web application, I'm running into problems, since react-native-web allows to use react-native UI projects like react-native-elements (https://github.com/react-native-training/react-native-elements) by mapping react-native base elements (`View`, `Text`, ...) to react-dom components. This works by aliasing `react-native` to `react-native-web`.

## Problem
Lots of react-native ui libraries and tools will not publish transpiled code, but raw src code with jsx, es-modules etc, since metro bundler will automatically run them through babel. I'm not able to run those dependencies through babel though, even with `useJsNext: true` and `Babel7Plugin=>limit2project`

How can I make fuse-box load them without throwing syntax errors?

**Comment by charsleysa** [comment]
Closed due to inactivity.
