### ISSUE TITLE
Performance degradation by updating 3.7.0-next.17 to 3.7.0 and above

### ISSUE THREAD

**Issue by bkniffler** [fuse-box/fuse-box#1499]
Initial build times increased from 5s to 25s on cold booting my app the first time and reloading after changing a file was at 2s, while with later version it is around >12s. 

Has there been any significant changes to fuse-box that could justify the performance degradation? I could provide a demo app, but maybe you have an idea?

Caching is enabled. Source maps are enabled. I'm only using typescript, so no other plugins involved. It is a browser@es target.

**Comment by nchanged** [comment]
Right, there was a bug in previous versions ignoring  the targets when dealing with node modules .set the target to esnext or es2017 and you will get back to your 5 secs

**Comment by nchanged** [comment]
@bkniffler all good? Sorry for closing it before confirming. It's just I had the same "issue" with my huge project, the compile time spiked to 25 seconds too. Then I realised that I had target `es5` and it's natural for FuseBox to transpile all node modules if the target is not met.

**Comment by bkniffler** [comment]
Heya, sorry for the delay. Turns out your first guess was 100% right! I'm on latest v4 and its even faster than 3.7.0-next.17, beautiful! Also, it makes sense that having @es5 (which I had before, small typo) will make stuff considerably slower to build. 

Thanks for all your hard work, I really appreciate the power and simplicity of fusebox (especially after being on webpack and parcel).

**Comment by nchanged** [comment]
I am happy its all resolved )
