### ISSUE TITLE
"Blind" copy of files

### ISSUE THREAD

**Issue by LukeHackett** [fuse-box/fuse-box#1500]
I have some json files that are not referenced directly in code, but I would like them to be copied over into the final `dist` folder, at a given location (they are fetched via XHR at application runtime). 

I thought that it might be possible with the CopyPlugin, (e.g.):

```
CopyPlugin({
    files: ['config/locales/**/*.json'],
    dest: 'assets/locales'
})
```

However that only seems to work when the static files are referenced from within the source code.

Is it possible to perform a "blind" copy of some static files that are not referenced within source code?

**Comment by nchanged** [comment]
@LukeHackett yes, that's how I use it one of my projects

```ts
task("copy-assets", async () => {
	exec("copy-favicon", "copy-static");
});

task("copy-static", async () => {
	await src("static/**.**", { base: "src/frontend/assets" })
		.dest("dist/assets")
		.exec();
});
task("copy-favicon", async () => {
	await src("favicon/**.**", { base: "src/frontend/assets" })
		.dest("dist/assets")
		.exec();
});
```

**Comment by LukeHackett** [comment]
Ah! that makes complete sense... I was still in "webpack" mode and thought that the CopyPlugin was the solution, however using Sparky makes complete sense. 

Here's my Sparky task, should anyone else need a pointer:

```javascript
const {watch} = require("fuse-box/sparky");

Sparky.task("copy:locale", async () => {
    await watch('./locale/*.json', { base: './src/config' })
        .dest('./dist/assets')
        .exec();
});
```
