### ISSUE TITLE
automaticAlias doesn't work well with instructions

### ISSUE THREAD

**Issue by tungd** [fuse-box/fuse-box#1502]
Hi, I encountered some issues with `automaticAlias`. Following is my config:

```js
const fuse = FuseBox.init({
  homeDir: "./src",
  output: "./build/$name.js",
  useTypescriptCompiler: true,
  allowSyntheticDefaultImports : true,
  compilerOptions: {
    baseUrl: "./src"
  },
});

const vendor = fuse.bundle("vendor").instructions("~ index.js");
const app = fuse.bundle("app").instructions("> [index.js]");
```

This results in the code imported from alias (components, utils, etc.) isn't included in either of the bundles. I believe in both cases FuseBox confused the components with packages in `node_modules`. Note that I do have correct alias mapping logged to console:

```
  → Applying automatic alias based on baseUrl in tsconfig.json
  →
 	components => "~/components"
	libs => "~/libs"
	scss => "~/scss"
	utils => "~/utils"
```

If I create multiple bundles but don't use instructions, it works. 
Interestingly, replacing `compilerOptions` with `alias` will make it work with instructions.

**Comment by tungd** [comment]
After some debugging turns out `WorkflowContext.addAlias` only get called once if using `compilerOptions`, so the contexts of the bundles have empty `aliasCollection`. When using `alias` it gets called three times, once for `FuseBox.init` and two more times for each of the call to `FuseBox.bundle`.

**Comment by nchanged** [comment]
Thanks for the issue! We will look into it

**Comment by eddyw** [comment]
FuseBox didn't have `compilerOptions` option on init last time I checked :P
Try setting on `FuseBox.init`:
```javascript
tsConfig: [{ baseUrl: './src' }]
```
which over-writes `tsconfig.json` file compiler options (merges).

**Comment by nchanged** [comment]
that's correct. Closing this for now

**Comment by tungd** [comment]
Oh I see, thanks 👍
