### ISSUE TITLE
Usage with external project

### ISSUE THREAD

**Issue by azdanov** [fuse-box/fuse-box#1507]
I was wondering if it is possible to hook up fuse-box with Laravel similar to [laravel-mix](https://github.com/JeffreyWay/laravel-mix) that uses webpack.

**Comment by nchanged** [comment]
Hi, you should wait for v4. The API is greatly simplified, no need in some shady tools :)

**Comment by azdanov** [comment]
@nchanged Thanks for good news. Looking forward to it.
