### ISSUE TITLE
fuse-box@4.0.0-beta.7 is not including JSON files correctly

### ISSUE THREAD

**Issue by jpike88** [fuse-box/fuse-box#1508]
I updated from 3.6.0 to latest beta. JSON file that was referenced is still being referenced in output like so:

```const translations_json_1 = require("~/server/src/components/translations/translations");```

However, that require points to nothing, that path is the only path that comes close to what I'm looking for. I've changing nothing in my fuse.js code when updating (other than moving sourceMaps from chaining on instructions to the init config, which I'm guessing is irrelevant).

**Comment by jpike88** [comment]
I updated from 3.6.0 to latest beta. JSON file that was referenced is still being included in output like so:

```const translations_json_1 = require("~/server/src/components/translations/translations");```

However, that file isn't being referenced elsewhere in the file. I've changing nothing in my fuse.js code when updating (other than moving sourceMaps from chaining on instructions to the init config, which I'm guessing is irrelevant).

**Comment by nchanged** [comment]
Let's wait for `v4` with a complete re-write. It's all gonna be handled gracefully there.

**Comment by jpike88** [comment]
Downgrading to 4.0.0-next.6 fixed this

**Comment by jpike88** [comment]
And broke something else, getting ```uncaught package not found util``` in a browser build. The issue doesn't occur on quantum builds though. just fyi

**Comment by nchanged** [comment]
#1527 should be fixed there
