### ISSUE TITLE
Fatal error in , line 0 # unreachable code

### ISSUE THREAD

**Issue by jpike88** [fuse-box/fuse-box#1510]
```
etc etc etc
[14:17:55] Resolved 'prepareAppFiles' after 32s 692ms
[14:17:55] Resolved 'serverlessProduction' after 32s 708ms

#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x70000e690a80Illegal instruction: 4
```

I get this rarely, any idea what it is? It doesn't happen straight away... might be when a change is 
being reloaded?

**Comment by jpike88** [comment]
Then got this:
```Segmentation fault: 11```

Seems to coincide with a changed file.

**Comment by nchanged** [comment]
That's some nodejs error

**Comment by nchanged** [comment]
That's probably related to memory error. Not enough RAM? Stay tuned to v4, it's gonna be a blast ;-)

**Comment by jpike88** [comment]
looking forward to it dude!
