### ISSUE TITLE
sourcemaps not generated with TerserPlugin

### ISSUE THREAD

**Issue by samueljc** [fuse-box/fuse-box#1512]
Disclaimer: I'm fairly new to fuse-box and typescript in general.

I'm using fuse-box 3.7.1

I'm pretty sure sourcemaps are broken with the TerserPlugin, though I'm not sure how they should be working.

Looking at the source, `includeSourceMaps` isn't getting carried over between the old source and the new one in the TerserPlugin so the source maps are never getting written. The `newConcat.add` at the end doesn't update the `includeSourceMaps` property either. It seems like this was the case in the older, deprecated UglifyESPlugin as well, so I don't understand how sourcemaps were working for that tool, assuming they were.

I think there are some more issues with the TerserPlugin as `inSourceMap` and `outSourceMap` aren't valid options to Terser.minify based on [the terser repo](https://github.com/terser-js/terser/blob/master/lib/minify.js#L68). I don't see any documentation for sourceMapConfig, so I'm not really sure how this should be getting used but it doesn't seem well-suited to work with Terser.minify.

---

Ultimately I'm trying to get production sourcemaps for an electron app in a separate .map file so I can have them for debugging tracked exceptions but not deploy them. If I should be going about this differently I will, but I'm starting to doubt that I can get there with the current Terser or UglifyES plugins.

**Comment by nchanged** [comment]
@samueljc could you share you fuse.js?

**Comment by samueljc** [comment]
I created a smaller example that's similar and still demonstrates the issue. Hope this helps.

https://github.com/samueljc/fusebox-sourcemap-example

**Comment by nchanged** [comment]
@samueljc I see the problem
here are the steps to improve and fix your build:

1) Remove Terser Plugin from the plugin list
2) For development use target `browser@esnext` for production `browser@2017`
3) Add [quantum plugin](https://fuse-box.org/docs/3.5.0/production-builds/quantum#docsNav) that's the one that should be used for generating production builds
4) Set [uglify](https://fuse-box.org/docs/3.5.0/production-builds/quantum-configuration#uglify) options. TerserPlugin will be picked automatically since you target it greater than es5

And as always, I am posting for everyone. There is an ongoing work on [v4](https://github.com/fuse-box/fuse-box/pull/1488). The configuration will be much much simpler and more understandable.

**Comment by samueljc** [comment]
Thanks @nchanged 

A few questions:

1. Is TerserPlugin not supported for direct use?
2. This is an electron project. Are [these docs ](https://github.com/fuse-box/fuse-box/blob/master/docs/development/configuration.md) wrong and we shouldn't be using the `electron` target anymore? Should we be using `browser` for both the main and renderer processes of our app?

---

After making the changes you mentioned this works fine in my minimal example, but I'm having an issue in my actual project which is far larger and can't be shared. I cleared out the node_modules and redownloaded, but that didn't make any difference.

```
  → Render bundle mainWindow
  → Uglifying mainWindow...
  → Using terser because the target is greater than ES5 or es6 option is set
  → Error during uglifying mainWindow
Z.get #83:23 at Z.get (~/client/node_modules/terser/lib/utils.js:83:23
Log.error #314:14 at Log.error (~/client/node_modules/fuse-box/Log.js:314:14

extraErrorProperties: 
  message:     Unexpected token name «code», expected punc «,»
  filename:    0
  line:        49695
  col:         122
  pos:         2055589
  constructor: function() {}
  name:        SyntaxError
{ SyntaxError: Unexpected token name «code», expected punc «,»
    at Z.get (~/client/node_modules/terser/lib/utils.js:83:23)
    at formatError (internal/util/inspect.js:817:16)
    at formatRaw (internal/util/inspect.js:616:14)
    at formatValue (internal/util/inspect.js:511:10)
    at inspect (internal/util/inspect.js:191:10)
    at Object.formatWithOptions (util.js:84:12)
    at Console.(anonymous function) (console.js:196:15)
    at Console.warn (console.js:213:31)
    at process.nextTick (~/client/node_modules/fuse-box/sparky/Sparky.js:37:29)
  message: 'Unexpected token name «code», expected punc «,»',
  filename: '0',
  line: 49695,
  col: 122,
  pos: 2055589 }
```

Let me know if I can help; not sure what would be useful.

**Comment by nchanged** [comment]
@samueljc my bad `electron@esnext` and `electron@2017`
This error is probably because of Terser, not fusebox

**Comment by samueljc** [comment]
@nchanged Thanks for the quick response time. Turns out that was related to our use of EnvPlugin, so I was able to get past that by setting `replaceProcessEnv: false` in the quantum config. Our app is now able to build with quantum, but running gives the following error:

```
Uncaught Exception:
ReferenceError: $fsx is not defined
    at Object.<anonymous> (~/dist/main.js:1:156)
    at Object.<anonymous> (~/dist/main.js:3:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at loadApplicationPackage (~/node_modules/electron/dist/resources/default_app.asar/main.js:119:12)
    at Object.<anonymous> (~/node_modules/electron/dist/resources/default_app.asar/main.js:164:5)
    at Object.<anonymous> (~/node_modules/electron/dist/resources/default_app.asar/main.js:204:3)
```

If you're not sure of the immediate cause of this new error I can close this ticket as it seems to be resolved, do some digging, and maybe file another one if I find an issue. Note, unlike [this ticket](https://github.com/fuse-box/fuse-box/issues/1264) I do not have target set to anything for the quantum config.

**Comment by nchanged** [comment]
@samueljc you should take a look [manifest](https://fuse-box.org/docs/production-builds/quantum-configuration#manifest) since Quantum produces more bundles (forgot to include them?) and [this](https://fuse-box.org/docs/production-builds/quantum-configuration#bakeapiintobundle)

**Comment by samueljc** [comment]
Still running into separate issues that are probably related to `process.env`, but my original issue has been resolved. Thanks again.
