### ISSUE TITLE
Alias doesn't work for esmodules written libraries that requires aliased library

### ISSUE THREAD

**Issue by dzek69** [fuse-box/fuse-box#1513]
Simple repository with demo: https://github.com/dzek69/fb-bug-demo

I'm using esmodules code style, and I'm using Babel for transpiling.
I'm aliasing `react` to `nervjs`.
If I import "react" directly in my code - it's all fine.
If I import a library that imports "react" - aliasing doesn't work and browser script crashes with `Uncaught Package not found react`
If I import already-transpiled library that imports "react" - aliasing works as expected.

**Comment by nchanged** [comment]
Aliasing has been tested in `fuse-box@next` Please give it a try
