### ISSUE TITLE
less modifyVars

### ISSUE THREAD

**Issue by machiaveli88** [fuse-box/fuse-box#1514]
Is it possible to use less modifyVars with fuse-box?

**Comment by nchanged** [comment]
Hi, Could you throw some links here please?

**Comment by machiaveli88** [comment]
Oh sorry, I forgot: http://lesscss.org/usage/#using-less-in-the-browser-modify-variables

Example: https://codepen.io/seven-phases-max/pen/dPYxzR

**Comment by nchanged** [comment]
Gotcha, so the situation is .. that I am now in a complete re-write. I will keep that thing in mind, when moving the less plugin.

**Comment by machiaveli88** [comment]
Okay, cool, thanks for your answer! What exactly are you re-writting? Do you already know about how long this will take?

**Comment by nchanged** [comment]
@machiaveli88 
https://github.com/fuse-box/fuse-box/tree/v4/src

fuse-box ;-) 

ETA:
2-4 weeks: First version (without production builds)
2 weeks - production ready

**Comment by machiaveli88** [comment]
Ah, cool, I'm very excited. :)

**Comment by machiaveli88** [comment]
Okay, I think It's working already with less options:
`LESSPlugin({
        modifyVars: {
          'color1': 'green'
        }
      })`
