### ISSUE TITLE
Module concat only with transpile optional

### ISSUE THREAD

**Issue by jeremy-coleman** [fuse-box/fuse-box#1518]
I would love a feature that would allow me to just concat files together that dedupes imports/exports without transpiling. 

Basically rollup that doesnt attempt to resolve external dependencies and optionally doesnt transpile, mostly for code organization and source code management. 

Ie:
Sparky.concat(srcGlob, destFile)

**Comment by nchanged** [comment]
Hi we need more specs on that one. I am currently working on a brand new version of FuseBox, I will keep this issue open.

**Comment by nchanged** [comment]
#1527

**Comment by charsleysa** [comment]
Closed due to inactivity.
