### ISSUE TITLE
QuantumPlugin: CSS Clean removing css because of a rouge comment?

### ISSUE THREAD

**Issue by LukeHackett** [fuse-box/fuse-box#1519]
I'm seeing some strange CSS outputs when using QuantumPlugin.

I'm importing a compiled [CSS file](https://github.com/jpuri/react-draft-wysiwyg/blob/master/dist/react-draft-wysiwyg.css) from another [node module](https://github.com/jpuri/react-draft-wysiwyg), and I have noticed that part of my resulting CSS bundle is commented out, and thus is removed via the cleancss (or uglify) functionality of fusebox.

I have managed to find the problem to be the last line of the node module's CSS file which contains the sourceMappingURL as:

```
/*# sourceMappingURL=react-draft-wysiwyg.css.map*/
```

But in my compiled (production) CSS it looks like this

```
body {
  background: red;
}

/*
.foo {
  color: blue;
}
```
Notice the loan comment - `/*` The only way I have managed to fix this,

Comparing this compiled (dev) CSS, it looks like this:

```
body {
  background: red;
}

/*# sourceMappingURL=/css-sourcemaps/01441df7f.map */
.foo {
  color: blue;
}
```
My `QuantumPlugin` configuration is a follows 
```
QuantumPlugin({
    bakeApiIntoBundle: 'vendor',
    treeshake: true,
    uglify: true,
    css: {clean: true}
})
```

I'm also using the `SassPlugin` although I don't think its a problem with the Sass Plugin. 

I was wondering if the `QuantumPlugin` is getting confused with the source map inline comment, and consequently is not correctly removing the entire of the sourceMapUrl?

My current work around is to ensure the import of the module's CSS file is always done last, and thus won't cause any problems, however I don't like this as it will require use of overriding css with `!important`.

**Checklist**
- [x] You have removed the `.fusebox` folder in your project root
- [x] Removed node_modules, (re-installed everything)
- [x] Started the bundling process again.
- [x] Read the documentation on your subject here -> fuse-box.org

**Comment by nchanged** [comment]
@LukeHackett hang in there, there is a [massive update](https://github.com/fuse-box/fuse-box/tree/v4/src) coming. Follow twitter to be the first one to try ;-) I will bear in mind the issue.

**Comment by charsleysa** [comment]
Closed as related to v3.x which is no longer supported.
