### ISSUE TITLE
Update ws version form 1.1.1 to 1.1.5 due to make fuse box for reliable

### ISSUE THREAD

**Issue by AndreyTretyak** [fuse-box/fuse-box#1520]
Version of [ws 1.1.5 has some important security fixes](https://github.com/websockets/ws/releases/tag/1.1.5), and should not contain any breaking changes. 
Could we switch to using it in fuse-box or there are some objections?

**Comment by nchanged** [comment]
@AndreyTretyak I will make sure to include to `v4` version. I will update every single issue and invite for the beta testing. Thanks

**Comment by AndreyTretyak** [comment]
Thank you it will help a lot

**Comment by AndreyTretyak** [comment]
@nchanged  sorry for so many requests, but maybe you can also consider updating to some newer versions of ws if it does not take too much effort (at least 3.3.1 or maybe even never)  it looks like 1.1.5 does not contain all fixes.

**Comment by charsleysa** [comment]
Closing as issue is related to v3.x and versions prior to v4 are no longer supported.
