### ISSUE TITLE
SassPlugin resources path slashes being stripped

### ISSUE THREAD

**Issue by dazzoh** [fuse-box/fuse-box#1526]
When trying to use a common resources file it looks like the generated imports are missing slashes:

ERROR File to import not found or unreadable: ..resources.scss.
 at [project]/src/styles.scss:1:1
ERROR File to import not found or unreadable: ........resources.scss.
   at [project]/src/lib/stdlib/web-app/WebApp.scss:1:1

fuse.js configuration for this was copied from the fuse docs:
```javascript
 plugins: [
        WebIndexPlugin(),
        prod && QuantumPlugin({
            removeExportsInterop: false,
            uglify: true,

        }),
        [
            SassPlugin({
                resources: [{test: /.*/, file: "resources.scss"}],
            }),
            CSSModulesPlugin({scopedName: prod ? "[hash:base64:4]" : "[name]__[local]___[hash:base64:3]"}),
            CSSResourcePlugin({dist: "dist/css-resources"}),
            CSSPlugin(),
        ]
    ],
```

I have tried removing .fusebox and node_modules.

Any help appreciated.

**Comment by nchanged** [comment]
@dazzoh we are nearly there with `version 4`. I will update the ticket and invite you to help testing it (if you are interested)

**Comment by dazzoh** [comment]
Hi @nchanged , sure thing -  happy to help on that.  Any idea of an ETA?

**Comment by nchanged** [comment]
It was supposed to come out today, but I have discovered a critical bug. So the alpha should be here this week and early next one. V4 is at least 7 times faster, and your issue there is resolved )

**Comment by nchanged** [comment]
#1527

**Comment by dazzoh** [comment]
@nchanged Just got round to trying this out. Same result, unfortunately (did a clean install too).

**Comment by nchanged** [comment]
Oh, I haven't added the resources yet. Will do today or tomorrow

**Comment by nchanged** [comment]
That has been fixed in v4. And it's called autoImport .
Available in `fuse-box@next`
