### ISSUE TITLE
Typescript doesn't work with parent folder as homeDir

### ISSUE THREAD

**Issue by SephReed** [fuse-box/fuse-box#1532]
I have a project like so

```
+ Project Root
  - Plugin Framework
  - Plugins
  + PluginSandBox
     - fuse.js
```

All of it is written in typescript.

I set my fuse file up like so:

```
const { FuseBox, WebIndexPlugin } = require("fuse-box");
const fuse = FuseBox.init({
  homeDir: "../",
  target: "browser@es6",
  output: "dist/$name.js",
  plugins: [WebIndexPlugin()],
});
fuse.dev(); // launch http server
fuse
  .bundle("app")
  .instructions(" > PluginSandBox/Demos.ts")
  .hmr()
  .watch();
fuse.run();
```

Demos.ts references multiple typescript files for plugins, found in the Plugins folder.  I keep getting errors that the modules don't have a js file.  It would appear fuse-box is expecting all of these "parent folder modules" to not be in typescript.

ASFAICT, this means I can't use typescript and not have fuse-box be at the root of my project.

**Comment by SephReed** [comment]
I've found a more direct way to ask this question.  Closing, will open a new one later.

**Comment by nchanged** [comment]
@SassNinja please try [version 4](https://github.com/fuse-box/fuse-box/issues/1527) this issue has been resolved there.
