### ISSUE TITLE
High CPU load in Chrome with dev tools open

### ISSUE THREAD

**Issue by jschill** [fuse-box/fuse-box#1534]
When file watching with fuse-box (3.7) it takes really long time for chrome to refresh the page if the dev tools are open. Looking at the activity monitor the cpu for chrome is maxed out. Am I alone with this or is it a common issue?

**Comment by nchanged** [comment]
@jschill I don't think it's related to fusebox at all. Try incognito mode. It's probably one of your extensions

**Comment by jschill** [comment]
@nchanged Maybe not. I've tried incognito and it's the same problem. Works fine as long as dev tools is closed, but as soon as it's open and i save a file, the rebuild only takes a couple of seconds but chrome takes more like 30-40 seconds before it's refreshing. I was first thinking hmr+sourcemaps, but my hmr is disabled. Or can it be activated by enabling another option?

**Comment by nchanged** [comment]
Nope, HMR is quite simple, and doesn't not require any CPU computation. I've never experienced anything related. Maybe restarting helps? If you have too many chrome instance open - that might have an effect.

**Comment by jschill** [comment]
OK, been debugging this now for quite some time. I got the cpu spike (see graph) even when i disabled the watching, changing a source file and running fusebox. In incognito and not. 
<img width="180" alt="Skärmklipp 2019-06-10 22 15 49" src="https://user-images.githubusercontent.com/224493/59224977-e8b24880-8bcf-11e9-8652-e2503d6ae6d4.png">

However, when removing my files from my "filesystem workspace" (sources > filesystem in dev tools), chrome is lightning fast. So I guess the problem is on Chrome's side when files in your workspace are updated outside of Chrome.
