### ISSUE TITLE
How to implement subresource integrity

### ISSUE THREAD

**Issue by valepu** [fuse-box/fuse-box#1536]
I've recently read about Subresource integrity ( https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity ) and I was wondering if it was possible to use it with fusebox.
Particularly what I want to achieve is that when I build my application for production the script and link tags have the integrity and crossorigin attributes created by fusebox (the integrity attribute should be an hash of the file, while the crossorigin could be configured).
Is this currently possible?

**Comment by nchanged** [comment]
Sounds interesting. Yes it can be done. Follow [v4](https://github.com/fuse-box/fuse-box/issues/1527) issue and also gitter. Soon we will be testing production builds, and there we could implement it right away! Join Gitter!

**Comment by nchanged** [comment]
I Believe that is now supported, since v4 no longer uses XHR requests, but relies on script tags. We could introduce the support in `webIndex`

Please give a try for `@next` and open another issue if needed.
