### ISSUE TITLE
File watcher creates endless loop [windows - V4]

### ISSUE THREAD

**Issue by jeremy-coleman** [fuse-box/fuse-box#1537]
when running in dev mode, changing any file will cause an endless loop on windows

(this was previously brought up in another thread but I think should have its own issue)

Current Behavior:
change source file ->
bundle ->
watcher sees output change ->
rebundles ->
sees output change again ->
rebundles ->
repeat

*update*
quick fix is just ignoring the dist folder in the config file:

watch: {
    ignored: ["dist"]
  }

**Comment by nchanged** [comment]
thank you @jeremy-coleman !

**Comment by nchanged** [comment]
That has been fixed.
