### ISSUE TITLE
React-SSR + code splitting not working in production

### ISSUE THREAD

**Issue by vutran1710** [fuse-box/fuse-box#1538]
I'm building a small application using ExpressJS, React-SSR, code-splitting with fuse-box.
Things work fine in dev mode but when it comes to production, well...
```
Launching quantum core
  → Generating abstraction, this may take a while
  → Abstraction generated
  → Process bundle server/bundle
  → Process package default
  →   Files: 12
  → Create split bundle 813cc1cc with entry point default/client/component/container/Calculator.jsx
  → QuantumBit: Adding default/client/component/container/Calculator.jsx to 813cc1cc
  → Render bundle server/bundle
  → Render bundle 813cc1cc
[22:12:58] Resolved 'be_serve' after 305ms
[22:12:58] Resolved 'default' after 4s 297ms
|> App started at http://localhost:8000
|> DB: mongodb://root:1234@localhost:27017/dev
```

The bundles  are splitted but when I move to the inner route (`/calc`), it throws an error saying I got an incorrect minified of react.
```
Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
```
Can anyone point out to me how to do this correctly?
Sorry heres my repo https://github.com/vutran1710/SweetDeals

**Comment by nchanged** [comment]
@vutran1710 Hi
The main focus is on `v4` now.  What I can suggest doing - is check how it resolves it. 

https://fuse-box.org/docs/development/code-splitting#docsNav

```
.splitConfig({
    browser: "/static/bundles/",
    server: "dist/static/bundles/",
    dest: "bundles/",
  })
```

I believe it can't resolve it is all. Just check the paths.

**Comment by nchanged** [comment]
All Resolved and tested in `@next`
