### ISSUE TITLE
FuseBox 4.0.0 Status

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#1539]
EDIT: `fuse-box@4.0.0` has been released!

Starting from `fuse-box@4.0.0-alpha.39`  we are entering a new stage where we start testing production builds. Please give you feedback!
EDIT: `fuse-box@4.0.0-next.446` is the latest version and any issues not tested against version or newer will be closed.

Example [here](https://github.com/fuse-box/react-example/tree/v4)

Things to do:

### Logging
It's a mess, we need to check the indents and make it all consistent
- [ ] Fix logging

### Docs
- [ ] Getting started 
- [ ] Installation
- [ ] Migrating from v3
- [ ] Migrating from webpack
- [ ] Essential config (webindex, cache, homeDir, entry, watcher)
- [x] Stylesheet
- [x] How plugins work
- [x] Plugin development
- [x] [Web worker docs](https://github.com/fuse-box/fuse-box/blob/v4/docs/webworkers.md)
- [x] [Electron docs](https://github.com/fuse-box/fuse-box/blob/v4/docs/electron.md)
- [ ] Production builds
- [ ] Turbo mode

### Electron 
- [x] [Electron support](https://github.com/fuse-box/fuse-box-electron-seed)

### Turbo mode
- [ ] Typescript turbo mode (workers) - development
- [ ] Typescript turbo mode (workers) - production
- [ ] JS turbo mode (workers) (do we need it?)

### CSS

- [x] Less Plugin
- [x] Stylus plugin
- [x] PostCSS Plugin
- [x] SassPlugin
- [ ] Possibility to use postCSS in `less` `sass` and `stylus` (after processing)
- [ ] Css code splitting (comes with JS splitting)
- [ ] Shared resources (import config file automatically)

### Ui frameworks

- [ ] Vue
- [ ] Elm

### WebIndex
- [ ] Adding consolidate?

### Webworkers
 - [x] [Web worker support](https://github.com/fuse-box/fuse-box-v4-bootstrap/tree/master/workers)
 - [x] web worker [docs](https://github.com/fuse-box/fuse-box/blob/v4/docs/webworkers.md)
### Production builds

- [ ] Tree-shaking (the hardest part is completed)
- [x] Code splitting
- [x] Manifest
- [ ] Configuring uglify
- [ ] Bundle configuration (currently it's automatic app + vendor)

## To discuss

1) **Bundle configuration** We need to come with a good approach to configuring the output.
Currently, v4 create `app.j`s and `vendor.js`. We should make it configurable

```ts
runProd({
  bundles: [
    { type : "vendor", include: ['react', 'react-dom'], exposes: ['??'], name: 'react' },
    { type : "vendor", name: 'vendor' },
    { type : "app", name: 'application', excludes : ["./something"], exposes : ["??"] },
  ],
});
```

More to come.

**Comment by SephReed** [comment]
A way to specify the which plugin (or plugin chain??) you want to use from the import line would be very nice.

Something like `import * as raw from "!!raw-loader!/myFile.ts"` could be the syntax.  All it would require in terms of coding is adding an `interface Plugin { importId?: string, ... }`, and then checking for that importId while doing the file imports.

**Comment by nchanged** [comment]
@SephReed changing the URL's won't happen. 

* That's not a valid path
* That's a webpack way
* We know better ;-)

```
pluginRaw("folder/*")
```

**Comment by SephReed** [comment]
Feel free not to do it the webpack way, but your solution is invalid for my use-case.

For my docs, I need to be able to simultaneously import the source code of a demo and display it.

**Comment by SephReed** [comment]
Unless the idea is that I could do this:

```
// some demo displayer
const raw = pluginRaw("path/to/item");
```
(Which I'm pretty sure does not work)

**Comment by SephReed** [comment]
So.. whats the resolution here?  Are we going to come up with a way to specify importers or am I going to have to make a work around?

**Comment by nchanged** [comment]
@SephReed there will be a plugin soon, be patient =)

**Comment by SephReed** [comment]
I ended up making a really neat work-around, so don't worry about that plugin for my sake.  Looking forward to the rest of everything else.  Thanks for the awesome codebase!

**Comment by paxperscientiam** [comment]
@nchanged what do you think about leveraging typedoc? I'm integrating it into a library I'm working on. Gotta say, very impressive!

**Comment by SephReed** [comment]
Couldn't typedoc stuff be done with sparky?  Or do you mean using specific comment types within fuse box?

**Comment by jeremy-coleman** [comment]
typedoc has a lot of AST related stuff that could be super userful. my brains full though , rip

**Comment by paxperscientiam** [comment]
@SephReed @jeremy-coleman , i'm exploring typedoc stuff now.

**Comment by paxperscientiam** [comment]
@nchanged , I am running into some trouble with typedoc, though it may not be the per se problem.

When I execute `\npm run document`, I get the following error:
```shell
> fuse-box@4.0.0-alpha.55 document /Users/ramos/repos/fuse-box
> ts-node -T fuse document


Using TypeScript 3.2.4 from /Users/ramos/repos/fuse-box/node_modules/typedoc/node_modules/typescript/lib
Error: Cannot write file '/Users/ramos/repos/fuse-box/src/main/__tests__/cases/projects/src1/index.js' because it would be overwritten by multiple input files.
 → Running document
true
```
Here is my fork: https://github.com/paxperscientiam/fuse-box/tree/v4

**Comment by SephReed** [comment]
Seriously, how does anybody both display and run example files using fuse-box?  I really need to be able to import a file as both raw and source.

So far, my solution is to just make `MyFile.ts.raw`, and then run a script which copies every `.raw` file and removes the extension making `MyFile.ts`.  Then I import `.raw` with raw plugin, and the ts file is imported normally.  But having to maintain two copies of the exact same file is kind of a hassle.

**Comment by nchanged** [comment]
what's your goal? to import a `typescript/javascript` file as string? If so, please create an issue, I will tag and make sure it's implemented before the release

**Comment by SephReed** [comment]
This is exactly the goal.  I have a feat request opened here: https://github.com/fuse-box/fuse-box/issues/1544.  The last response is a link to this current thread.

**Comment by SephReed** [comment]
Thank you very much for looking into it.  I know all the pieces are there, but I'm not familiar enough with the fusebox repo to put the pieces together.

**Comment by SephReed** [comment]
There's a feature I need right now an insane amount and I don't think it would take long:  RawEditPlugin.

It allows you to edit the raw text of a file before it is saved to `./dist` or pushed to hmr().  It's sort of a deadmans switch for when things go wrong and you really, really just need to duct tape some shit together.  Please, kindly consider adding something for doing this.  Fusebox will never be perfect, and without something like this, users can do nothing when things go wrong.

- [ ] Deadmans switch RawEditPlugin

**Comment by SephReed** [comment]
It's called ReplacePlugin.  God dammit.  Thanks you though.  I'm now sold on fuse-box.  Maybe I can help out with the docs though.

**Comment by nchanged** [comment]
@SephReed https://github.com/fuse-box/fuse-box/blob/v4/docs/plugins/pluginReplace.md

**Comment by nchanged** [comment]
Hi! Please read the docs more carefully:) There is no Quantum plugin anymore, more over you don't need any plugins (for the most time) Check the react example mentioned in the docs 

Css splitting will be there

**Comment by tomitrescak** [comment]
Guys, AMAZING work, feels much more stable now. What is the status on ESM module support for free shaking? You say that the hardest part is implemented, is it possible to test/contribute? Thanks

**Comment by nchanged** [comment]
@tomitrescak there is actually a major change coming, that's is currently in alpha - Fuse Compiler, which is supposed to replace typescript completely. It's 20x times faster (not joking) and consumes very little memory, so your laptop will stay on your desk ;-) Give it a try `4.0.0-alpha.256`

There are no source maps yet (coming next week), and the reload is broken, however, we are working on a stable build.  Production mode is disabled until we make sure that the dev is stable enough. runProd() should be as fast as runDev() with fuse compiler ;-)

**Comment by tomitrescak** [comment]
@nchanged gave it a go, but crashed on build for me ;(

**Comment by nchanged** [comment]
@tomitrescak that's what we're are all fixing here ;-) Could you give a sample of the code that crashes?

**Comment by tomitrescak** [comment]
Hello, it crashes on compilation. This is the error:

```
   FATAL  Error while parsing the code

  - at /Users/tomi/Github/apps/corpix/app/client/src/index.tsx
  - SyntaxError: Line 1, column 7: Unexpected
    at report (/Users/tomi/Github/apps/corpix/node_modules/buntis/dist/buntis.umd.js:4472:21)
    at parseGlobalModuleDeclarationOrIdentifier (/Users/tomi/Github/apps/corpix/node_modules/buntis/dist/buntis.umd.js:11398:15)
    at parseDeclarationList (/Users/tomi/Github/apps/corpix/node_modules/buntis/dist/buntis.umd.js:6143:22)
    at parseDeclarations (/Users/tomi/Github/apps/corpix/node_modules/buntis/dist/buntis.umd.js:6109:27)
    at parseSource (/Users/tomi/Github/apps/corpix/node_modules/buntis/dist/buntis.umd.js:6087:17)
    at Object.parseTSModule (/Users/tomi/Github/apps/corpix/node_modules/buntis/dist/buntis.umd.js:11751:14)
    at Module.parse (/Users/tomi/Github/apps/corpix/node_modules/fuse-box/core/Module.js:37:35)
    at processModule (/Users/tomi/Github/apps/corpix/node_modules/fuse-box/main/assemble.js:158:21)
    at parseDefaultPackage (/Users/tomi/Github/apps/corpix/node_modules/fuse-box/main/assemble.js:241:5)
    at Object.assemble (/Users/tomi/Github/apps/corpix/node_modules/fuse-box/main/assemble.js:276:5)
```

This is the file:

```
global.process = {
  env: {
    NODE_ENV: 'me'
  }
}; // BTW -> I could not find a way to set environemnt variables with FB4

import 'tslib';
import { renderApp } from './router';

renderApp();
```

This is the fuse config

```
const { fusebox } = require('fuse-box');

const fuse = fusebox({
  target: 'browser@es5',
  entry: 'app/client/src/index.tsx',
  homeDir: '../../',
  devServer: true,
  webIndex: {
    template: 'src/index.html'
  }
});

fuse.runDev();
```

**Comment by eddyw** [comment]
@tomitrescak in TS, you use `globalThis` :P 
```javascript
globalThis.process = {
  env: {
    NODE_ENV: 'me'
  }
};
```

**Comment by nchanged** [comment]
@tomitrescak target `browser` !!! I can't reproduce it here
https://buntis.github.io/buntis/

**Comment by tomitrescak** [comment]
Hey, without this it compiled fine, but then in browser I got "cannot find buffer"

```
global.process = {
  env: {
    NODE_ENV: 'me'
  }
};
```

**Comment by nchanged** [comment]
@tomitrescak which file complains about it? could you throw a source code at me?

**Comment by MrFoxPro** [comment]
Can't compile with this error =C
```
assemble package react-addons-css-transition-group:15.6.2{ SyntaxError: [15:11]: Expected '('
    at report (E:\Dima\F\FoxRP\ui\node_modules\meriyah\dist\meriyah.umd.js:188:13)
    at consume (E:\Dima\F\FoxRP\ui\node_modules\meriyah\dist\meriyah.umd.js:2097:11)
    at parseMethodFormals (E:\Dima\F\FoxRP\ui\node_modules\meriyah\dist\meriyah.umd.js:5223:7)
    at parseMethodDefinition (E:\Dima\F\FoxRP\ui\node_modules\meriyah\dist\meriyah.umd.js:4684:22)
    at parseClassElementList (E:\Dima\F\FoxRP\ui\node_modules\meriyah\dist\meriyah.umd.js:6077:21)
    at parseClassBody (E:\Dima\F\FoxRP\ui\node_modules\meriyah\dist\meriyah.umd.js:5954:21)
    at parseClassDeclaration (E:\Dima\F\FoxRP\ui\node_modules\meriyah\dist\meriyah.umd.js:5862:20)
    at parseStatementListItem (E:\Dima\F\FoxRP\ui\node_modules\meriyah\dist\meriyah.umd.js:2563:22)
    at parseModuleItem (E:\Dima\F\FoxRP\ui\node_modules\meriyah\dist\meriyah.umd.js:2554:22)
    at parseModuleItemList (E:\Dima\F\FoxRP\ui\node_modules\meriyah\dist\meriyah.umd.js:2541:27)
  index: 310,
  line: 15,
  column: 11,
  description: "[15:11]: Expected '('",
  loc: { line: 15, column: 11 } }```
my config is pretty default:
```
```
import { fusebox, pluginCSS, pluginJSON } from 'fuse-box';

const fuse = fusebox({
  target: 'browser',
  homeDir: "./src",
  entry: 'index.tsx',
  modules: ["./node_modules"],
  devServer: true,
  tsConfig: "./tsconfig.json",
  sourceMap: {
    // project: true
  },
  allowSyntheticDefaultImports: true,

  webIndex: {
    template: 'src/index.html'
  },
  dependencies: {
    // include: ['tslib'],
    // ignoreAllExternal: true,
  },
  plugins: [pluginCSS(), pluginJSON()],
  cache: true,
});

fuse.runDev();
```

**Comment by nchanged** [comment]
@MrFoxPro and the offending file?

**Comment by MrFoxPro** [comment]
@nchanged 
I don't know how to check that. Package react-addons-css-transition-group contains only index.js with import of other dependencies, and this is lines in meriyah.umd.js
```
  function report(parser, type, ...params) {
      throw new ParseError(parser.index, parser.line, parser.column, type, ...params);
  }
```
whole file meryah.umd.js: https://hastebin.com/uvahodegow.js
am i missed something?

**Comment by nchanged** [comment]
@MrFoxPro set `cache : {FTL : false}`

**Comment by paxperscientiam** [comment]
@nchanged with regard to build process, I think the default should be to use a `fuse.ts` as opposed to `fuse.js`. The idea being to leveraging TypeScript hinting to make it easier for user to know at development time if they're using the right properties when writing their configurations.

Also, IMHO, `/dev/stderr` should indicate by default faulty configurations.

**Comment by SephReed** [comment]
I see above that many Doc items are checked off.    Where in the repo are their plain-texts found?

**Comment by nchanged** [comment]
In the docs folder )

**Comment by SephReed** [comment]
Really?  https://github.com/fuse-box/fuse-box/tree/master/docs

None of them have been touched in 2 months, which seemed strange.

**Comment by Marcisbee** [comment]
I believe it's on v4 branch https://github.com/fuse-box/fuse-box/tree/v4/docs

**Comment by nchanged** [comment]
@SephReed be the one who touched them now  :)

**Comment by SephReed** [comment]
@nchanged That's my hope.  I was going to read through them and edit as I run into issues.  (@Marcisbee The v4 branch seems even older btw)

**Comment by nchanged** [comment]
@SephReed all the work is in `fuse-compiler` branch. I will merge it as soon as it's ready

**Comment by johnpittman** [comment]
Service worker option going to be the same?

**Comment by nchanged** [comment]
@johnpittman you mean web worker?

**Comment by johnpittman** [comment]
Service worker. Wasn't there a field to set to export sw.js that acts like
the PWA plugin for webpack. I remember seeing someone mention it and seeing
a response with configuration for it in v3. We currently use webpack for
service worker projects.

John R. Pittman |
<https://plus.google.com/u/0/100394734061909211307/about/p/pub>

johnrichardpittman@gmail.com

mobile: 561-460-2051

**Comment by patrickmichalina** [comment]
@johnpittman I have been manually creating ServiceWorker bundles with fusebox. No plugin yet as far as I know.

**Comment by charsleysa** [comment]
Closing as `fuse-box@4.0.0` has been released.
