### ISSUE TITLE
Feat request: RawPlugin, being able to import files that are also dependencies

### ISSUE THREAD

**Issue by SephReed** [fuse-box/fuse-box#1544]
https://fuse-box.org/docs/plugins/raw-plugin#docsNav

https://github.com/fuse-box/fuse-box/blob/master/src/plugins/RawPlugin.ts

I've tried reading the docs and looking at the source code (above), but I can't seem to figure out if what I'm trying to do is possible.

I'm creating a demo, and I'd like to be able to simultaneously import my code as a source dependency, and import it raw to show people what the code that's being run is.

If it doesn't exist, webpack raw-loader has a thing it does where `import css from '!!raw-loader!./file.css'; ` will force that plugin to be used.

I did check the docs for about plugins (https://fuse-box.org/docs/getting-started/about-plugins), but couldn't find that there either.

**Comment by nchanged** [comment]
@SephReed hi, please pay attention to this ticket. V3 is no longer maintained. https://github.com/fuse-box/fuse-box/issues/1539
