### ISSUE TITLE
Update Chokidar

### ISSUE THREAD

**Issue by FlorianRappl** [fuse-box/fuse-box#1546]
I think this is a fairly cool project and you guys put some good thoughts and efforts into the whole bundle - much appreciated!

Since the current chain of dependencies also involves Braces in a fairly outdated version (https://npmjs.com/advisories/786) where the root of this chain can be found in a quite old version of chokidar I was curious to hear if there is an option to upgrade to the latest version of chokidar. There will only be more vulnerabilities in the future, thus staying up to date may be beneficial in the long run.

I assume the reason for sticking with v1 of chokidar is the removal of the backslash from chokidar 2+. Nevertheless, people should anyway exclusively use standard slashes as separators - they work on both -nix and Windows and are the only allowed separator in glob patterns. Thus I would not even argue that this would be a breaking change to users (otherwise it could still be resolved via automatic replacements of "\" to "/" if the system is found to be Windows).

Thanks!

**Comment by nchanged** [comment]
@FlorianRappl thanks ;-)
[FuseBox v4](https://github.com/fuse-box/fuse-box/issues/1539) is already using chokidar 2, I will update it to chokidar 3 soon.
If you have time to help, please do so. `v4` features a drastic performance increase with a much more simplified configuration.

**Comment by jeremy-coleman** [comment]
https://github.com/codeandconspire/postcss-watcher/blob/master/index.js

And

https://github.com/egoist/rollup-plugin-postcss/tree/master/src

Combining these would be a nice dx and make re implementing the style plugins much easier. The rollup postcss plugin just lets you import whatever extension as long as the compiler installed, no config needed

**Comment by nchanged** [comment]
that's a nice idea, however, FuseBox v4 doesn't require any plugins for css by default. Everything works out of the box. For now we have raw css and `sass` implemented. Soon, I am going to plug in more, if you feel like helping, please pitch in for the greatness ;-)

**Comment by nchanged** [comment]
v4 now uses the latest chokidar

Docs for the watcher [here](https://github.com/fuse-box/fuse-box/blob/v4/docs/watcher.md)
