### ISSUE TITLE
Minimum transpile config doesn't work if you don't add sourcemaps

### ISSUE THREAD

**Issue by ArekusuNaito** [fuse-box/fuse-box#155]
Since sourcemaps are not required in a production environment I wanted to create a minimum configuration to transpile code.
The attached project does't transpile and the console logs the next error.
The project transpiles correctly if you add sourcemaps.
`Uncaught SyntaxError: Unexpected token import`

Files:
- fuse.js
- index.js - Just imports Foo
- foo.js a simple class

[minimum-no-sourcemap-transpiling.zip](https://github.com/fuse-box/fuse-box/files/772787/minimum-no-sourcemap-transpiling.zip)

I want to help other users to create a really simple setup :)

**Comment by nchanged** [comment]
@ArekusuNaito thanks a lot! We will look into it.

**Comment by nchanged** [comment]
#180
