### ISSUE TITLE
[feature request] Use alternate port when default port is busy

### ISSUE THREAD

**Issue by paxperscientiam** [fuse-box/fuse-box#1553]
This is a feature request. Current behavior is that given the scenario whereby the default port (4444) is in use, fuse-box will fail to start. Suggested behavior is that fuse-box use another port rather than fail. And, perhaps, indicate what process is using the default port.

**Comment by nchanged** [comment]
Alternatively we could use ctx.fatal to exit gracefully

**Comment by kyr0** [comment]
I'll PR that, we can use an alternate port impl. later. But the immediate bug is that you expect that your code is running on port X ... but another fuse is running there and you run into heavy *con*-_fuse_-*ion*

**Comment by kyr0** [comment]
@nchanged Please review :)
