### ISSUE TITLE
CSS concatenation comment out CSS portions

### ISSUE THREAD

**Issue by guillaume86** [fuse-box/fuse-box#1555]
I found a issue with CSS concatenation. The issue is here:

https://github.com/fuse-box/fuse-box/blob/eafee772e5e0a3cc96580098a72e5bc9c489a9db/src/quantum/core/CSSCollection.ts#L29

I have a file which ended with 

    /*# sourceMappingURL=data:application/json;base64,BLABLA= */

when running the replace, the result is `/*` which will comment all following files until a closing comment is found.

In addition to fixing this, I wonder if we should protect against files really ending with /* or missing a comment ending tag.

**Comment by charsleysa** [comment]
@guillaume86 can you please confirm if the issue still occurs with `fuse-box@4.0.0-next.400`?
Also see [here for info on major changes](https://github.com/fuse-box/fuse-box/blob/master/docs/changelog-fuse-compiler.md)

**Comment by guillaume86** [comment]
Hi, sorry I'm not using fusebox anymore on that project but it should be easy enough to try out, just end a css file with a sourcemap and import it in another css file, then add a rule under the import. Then check the rule is not commented when bundling.
