### ISSUE TITLE
EnvPlugin won't inject process.env into vendor bundle

### ISSUE THREAD

**Issue by Martaver** [fuse-box/fuse-box#1557]
I'm playing around with an alpha build of `react-beautiful-dnd` which, for some reason, is using `process.env` in its published npm package. I'm pretty sure it's just there for debugging during alpha, but I wanted to get it working and test a feature I've been waiting for.

Seems like `EnvPlugin` isn't injecting `process.env` into the vendor bundle, though...?

Is this expected, and is there a way to make `process.env` universal?

**Comment by nchanged** [comment]
@Martaver are you sure you were using `v4`
Check [this](https://github.com/fuse-box/react-example/blob/v4/fuse.ts#L17) out. There is no EnvPlugin anymore. It's a part of the core.

**Comment by Martaver** [comment]
Nah I’m on 3.7.1 - its react-beautiful-dnd that’s on alpha I’m playing
with. Just trying to explain why I need process.env in the vendor bundle.

**Comment by nchanged** [comment]
`process.env` should be available across all the bundles. Unless there is a bug with Quantum. Do you think you could give me more details?

**Comment by Martaver** [comment]
Actually this is in my dev build, so I'm not even using Quantum. FB options:
```
FuseBox.init({
            ...this.options,
            plugins: [
                // We need to hard core the api url & port passed from build's env vars into static assets
                EnvPlugin({
                    API_HOST: process.env.API_HOST,
                    API_PORT: process.env.API_PORT
                }),
                WebIndexPlugin({
                    template: `${SRC}/index.html`
                }),
                SVGPlugin(),
                CSSPlugin(),
                this.__PROD__ &&
                QuantumPlugin({
                    uglify: true,
                    css: true
                })
            ]
        })
```

Vendor splitting:
```
const vendor = fuse.bundle("vendor");

        vendor.instructions("~ typescript/sim/src/index.tsx");

        const sim = fuse.bundle("index");

        sim.instructions("!> [typescript/sim/src/index.tsx]");
        !this.__PROD__ && sim.watch(path => {
            const only = /typescript/;
            const exclude = /(node_modules)/;
            return only.test(path) && !exclude.test(path);
        });
        !this.__PROD__ && sim.hmr();
        return sim;
```

Nothing really out of the ordinary...?

**Comment by jeremy-coleman** [comment]
Im using react beautiful dnd without issue in fusebox3 , no vendor split tho. Ive found it breaks things often

**Comment by nchanged** [comment]
@jeremy-coleman things are much more stable with `v4` give it a try

**Comment by nchanged** [comment]
This is fixed in `v4` please re-open if needed.
