### ISSUE TITLE
V4 Alpha - bug or user fault ?

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box#1558]
Tried using lit-element in v4 alpha.

Getting error messages:
![image](https://user-images.githubusercontent.com/2901416/60727954-71a67080-9f3f-11e9-9d9f-74bcd1be3afb.png)

Created a simple test repo here:
https://github.com/vegarringdal/bug

Maybe Im doing something wrong, but it works in v3 when I tried.
Hopefully its just me using it wrong and a easy fix
Added a branch for v3 just incase it helps

**Comment by vegarringdal** [comment]
@nchanged Was it a bug or just me doing something wrong with v4.0.0 ?
:-)

**Comment by nchanged** [comment]
Will check it today/tomorrow )

**Comment by vegarringdal** [comment]
@nchanged 
I tok a new look 
From what I can see it skips renaming the templateFactory into `__req3__`
Looks like ES6 shorthand code tricks it
Dunno if this helps you figure out the bad parts 😄 



![image](https://user-images.githubusercontent.com/2901416/61155093-51068980-a4f0-11e9-9928-e5bc3069a3a5.png)


from the source
![image](https://user-images.githubusercontent.com/2901416/61155168-7f846480-a4f0-11e9-8284-c27e31ffe6dd.png)

**Comment by nchanged** [comment]
@vegarringdal confirmed
```
import { foo } from './foo';
console.log({ foo });
```

shorthand is the problem

**Comment by nchanged** [comment]
`fuse-box@4.0.0-alpha.57` fixed

**Comment by vegarringdal** [comment]
@nchanged nice, that was quickly fixed after it got confirmed 😁
Do all plugins like postcss etc work with v4?

**Comment by nchanged** [comment]
@vegarringdal unfortunately there is only `sass` and `css` for now. But it should be coming soon, after i am done with production ;-) Sass should work out of the box without any plugins.
