### ISSUE TITLE
Update `ws` to prevent security issues

### ISSUE THREAD

**Issue by dzek69** [fuse-box/fuse-box#1559]
`ws` dependency of fuse-box has **high severity** vulenerability.

This may not be an issue if `ws` is only locally used for development, but still looks bad when audit tools and even github itself is triggering alerts about that.

> Known high severity security vulnerability detected in ws >= 0.2.6, < 3.3.1 

Please consider updating `ws`.

**Comment by nchanged** [comment]
Thanks,
I've updated it in `v4`

https://github.com/fuse-box/fuse-box/blob/89fd5d3caaf55151aff8426974b6f210aecbdd8d/package.json#L65-L67

**Comment by dzek69** [comment]
any plans for release date for v4?

**Comment by nchanged** [comment]
@dzek69 `4.0.0-alpha.56`

**Comment by dzek69** [comment]
I mean stable version :)

**Comment by nchanged** [comment]
I wish it moved faster, I need help with the docs ( and there are a few
things to do still
