### ISSUE TITLE
electron-fusebox - Node API

### ISSUE THREAD

**Issue by ArekusuNaito** [fuse-box/fuse-box#156]
When using Electron you have access to Node API on your front-end.
The problem here is that Fuse-box thinks Electron is on a front-end and it doesn't allow you to load
Node API.

The Hacky way I found in order to work is to set `FuseBox.isServer=true`but this MUST BE DONE on every source file. Which I don't think is a good way to do it.
`FuseBox.isServer=true` would have to be on the first lines of the bundle.js file. That way every source file would know that is on a server environment.

---
![image](https://cloud.githubusercontent.com/assets/10826197/22912636/0f1a7f28-f22c-11e6-8fbe-810757d19122.png)

---
A suggestion I have (which I don't know if is a good one) is to have an option on the bundle settings to force the `FuseBox.isServer` flag on the bundle.js file

Perhaps something like this? (Notice the isServer  key)

```
let fuseBox = new fsbx.FuseBox({
    homeDir: "src/",
    sourceMap:
    {
      bundleReference: "sourcemaps.js.map",
      outFile: "./build/sourcemaps.js.map",
    },
    outFile: "./build/bundle.js",
    plugins: [
        fsbx.JSONPlugin(),
        fsbx.BabelPlugin({
            config: {
                sourceMaps: true,
                presets: ["es2015"]
            }
        })
    ],
    isServer: true
});
```

Uploaded my project:
[electron-node-api.zip](https://github.com/fuse-box/fuse-box/files/773007/electron-node-api.zip)

Thanks guys! :)

**Comment by nchanged** [comment]
That would be cool, yeah, great idea!

**Comment by nchanged** [comment]
I think `serverBundle` is more explicit?!

**Comment by ArekusuNaito** [comment]
Updated to `    "fuse-box": "^1.3.115",`
And `serverBundle` is not working.

My .init code

```
let fuseBox = fsbx.FuseBox.init({
    homeDir: "src/",
    sourceMap:
    {
      bundleReference: "sourcemaps.js.map",
      outFile: "./build/sourcemaps.js.map",
    },
    outFile: "./build/bundle.js",
    plugins: [
        fsbx.JSONPlugin(),
        fsbx.BabelPlugin({
            config: {
                sourceMaps: true,
                presets: ["es2015"]
            }
        })
    ],
    serverBundle : true
})
```

I'm importing `fs` like this
`const fs = require('fs');`

**Comment by nchanged** [comment]
http://fuse-box.org/#server-bundle sets `FuseBox.isServer` to true. Can you confirm that?

**Comment by ArekusuNaito** [comment]
It's working now. I don't know if was cache?
Nuked .fuseBox a while ago.
Didn't change anything to my code.

This confirms it on my bundle file.

![image](https://cloud.githubusercontent.com/assets/10826197/23020090/028fc822-f40b-11e6-81f3-41e4874a1ce2.png)

Thank you for your quick assistance!

**Comment by nchanged** [comment]
You are more than welcome!
