### ISSUE TITLE
HTMLPlugin/CopyPlugin useDefault should also turn on __esModule

### ISSUE THREAD

**Issue by 3cp** [fuse-box/fuse-box#1562]
When useDefault is turned on, HTMLPlugin simplify generates:
```js
module.exports.default =  "...";
```

But this is not compatible with BabelPlugin and Babel7Plugin, where babel checks `__esModule` for esm format or commonjs format.

In babel project, `import foo from './foo.html';` results `foo` to be an object instead of a string.
TypeScript project is not affected.

To fix the compatibility with babel, suggest to add `module.exports.__esModule = true; ` before the default export, for both HTMLPlugin and CopyPlugin. I can make a PR if this makes sense.

**Comment by nchanged** [comment]
@3cp v3 will be soon out of the equation. `v4` will be merged soon that offers a completely different API

Please take a look a [json](https://github.com/fuse-box/fuse-box/blob/v4/src/plugins/core/plugin_json.ts) plugin, If you could please add plugin_html 

Some information with examples is [here](https://github.com/fuse-box/fuse-box/issues/1539) and [here](https://github.com/fuse-box/fuse-box/issues/1527)

**Comment by 3cp** [comment]
ok, I will have a look again when v4 is released.

**Comment by nchanged** [comment]
`__esModule ` is being set during the runtime with FuseBox `v4`
I will close this for now.
