### ISSUE TITLE
Native Extensions

### ISSUE THREAD

**Issue by kaaninel** [fuse-box/fuse-box#1563]
It's really hard to use .node files with fusebox currently and there is no tutorial as far as i can see. whatever i try it treats file as text. And since require is hooked i cant get it working properly. I somehow managed to make it work using quantum (since no require hook?) but its not stable. So is there a way that i can use or can you help me write a plugin for it ? .node could stay out of bundle separately tho.

**Comment by nchanged** [comment]
@kaaninel I will make sure it works with `v4`! There is a total re-write. Give it a try!

**Comment by kaaninel** [comment]
Thank you! If you need any help let me know. I was messing with typescript compiler etc for long time. Not since I'm using fusebox tho its pretty much enough for what I need.

**Comment by nchanged** [comment]
@kaaninel there is plenty of work ;-) join Gitter for a chat! ;-)

**Comment by charsleysa** [comment]
I wrote a quick plugin for handling `.node` files that works with `fuse-box@next` based off of `pluginLink`, just add it to the list of plugins in your config.

```ts
                (ctx) => {
                    ctx.ict.on('bundle_resolve_module', (props) => {
                        if (!props.module.captured && props.module.props.extension === '.node') {
                            const target = props.module.props.absPath;
                            const name = fastHash(target) + path.extname(target);
                            const location = path.join('./node-native', name);
                            const destination = path.join(props.module.props.ctx.writer.outputDirectory, location);

                            props.module.captured = true;
                            props.module.props.ctx.log.info('node-native', 'Captured $file with pluginNodeNative', {
                                file: props.module.props.absPath
                            });

                            if (!fileExists(destination)) {
                                props.module.props.ctx.taskManager.copyFile(props.module.props.absPath, destination);
                            }

                            props.module.contents = `module.exports = require("${location}");`;
                        }
                        return props;
                    });
                },
```

**Comment by nchanged** [comment]
@charsleysa hey this looks awesome! Do you think you can create a PR and add it to the plugin list?
Also add it to [pluginAssumption](https://github.com/fuse-box/fuse-box/blob/master/src/plugins/core/plugin_assumption.ts) so it will be configured automatically.

**Comment by charsleysa** [comment]
@nchanged recommend close issue as fixed.
