### ISSUE TITLE
Fusebox not showing tsc errors

### ISSUE THREAD

**Issue by SephReed** [fuse-box/fuse-box#1564]
I really like the error output of `tsc --watch`, but whenever I start a fuse.js, the only errors I get are really unhelpful ones about my bundle code in the browser.

How can I get fuse-box to show normal tsc errors?

**Comment by nchanged** [comment]
There aren't "normal" errors ) FuseBox doesn't do type checking, you should setup your IDE to do so or use a type checker (you can find it on the list of repos)

 I will close this one since this question has been asked already.

**Comment by SephReed** [comment]
So, fusebox is using tsc to compile typescript.  tsc outputs errors.  These are the "normal" errors I'm talking about.  Maybe they're not normal, but given they're the output of running tsc, I think I should be able to see them somehow.

How can I see them?

**Comment by nchanged** [comment]
FuseBox doesn't use tsc at all. It uses the compiler API directly. 

https://github.com/fuse-box/fuse-box-typechecker

**Comment by SephReed** [comment]
Ah.  In that case, you're probably much more familiar with the compiler API then I.

Why not use 
```
let allDiagnostics = ts
    .getPreEmitDiagnostics(program)
    .concat(emitResult.diagnostics);

https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler

**Comment by vegarringdal** [comment]
@SephReed 

https://github.com/fuse-box/fuse-box-typechecker

This gives you the error and option for tslint also.
Is it not working ?
