### ISSUE TITLE
fusebox does not like method named "process" 

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box#1566]
Sample
https://github.com/vegarringdal/bug2

You can see under dev what dev build generatesand dist what production build generates.
In dev mode it tried tries to import 
- https://github.com/vegarringdal/bug2/blob/master/dev/app.js#L5

I could prob get around this in dev mode by using env plugin.

While in dist mode it renames the method name to undefined
https://github.com/vegarringdal/bug2/blob/master/dist/app.js#L15

This is not good... my code will now fail.
Is there a way I can get around this without changing name of method ? my issue is that other libs I use have this method and fails during dist build.

**Comment by nchanged** [comment]
Please check if it works with v4, and reproduce it, I am not going to apply any patches to v3 anymore

**Comment by vegarringdal** [comment]
it works in v4
