### ISSUE TITLE
v4: plugin feature request: minify template literals

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box#1568]
Started using lit-html lately.
Would be great if fusebox could minify template literals

Found this, maybe it can help you make a plugin after v4 is released
https://github.com/asyncLiz/minify-html-literals#readme

**Comment by kyr0** [comment]
You can solve this using `customTransformers` now (recently added :) Just scan the AST for template literals and return the minified text. The modified AST will be given to the typescript compiler. You can also write a plugin that registers this transformer in the context config, so when your plugin is used, the customTransformer is used.

**Comment by vegarringdal** [comment]
@kyr0 
Nice, will try and look at this in the weekend.
Might ask you for help, since I have really no clue about this :-)

**Comment by vegarringdal** [comment]
> You can also write a plugin that registers this transformer in the context config, so when your plugin is used, the customTransformer is used.

@kyr0 
Wont anything I add be destroyed by the plugin,or where you thinking about something else ?

https://github.com/fuse-box/fuse-box/blob/master/src/plugins/core/plugin_customtransform.ts
Maybe this should check if there is allready added customTransformers ?

**Comment by vegarringdal** [comment]
fixed
