### ISSUE TITLE
Feature Request:  Deadman switch plugin: (modify raw bundle output)

### ISSUE THREAD

**Issue by SephReed** [fuse-box/fuse-box#1575]
I really, really, really, REAAALLLYY, REEAALLY need a feature right now.

Find and replace.  Before a file is saved and sent to hmr(), you can modify the text.  That's all.  This one feature alone would save my ass so much trouble.  I just need to modify the text, right before the file is saved/sent to hmr().

This has got to be the easiest feature you could ever make, and it could be used to solve pretty much any problem that arises from app.js being rendered incorrectly.

**Comment by SephReed** [comment]
This would pretty much be the equivalent of `{ dangerouslySetInnerHtml: string }` in React.  Nobody should ever need a deadman switch, but sometimes you really, really do.  Like right now.  I really need a deadman switch.  I need a way to force this thing into working, because it's a very big problem for me.

I'm currently building a framework which I have been intending to release with fuse-box as it's goto bundler, and if it had this feature I'd be sold for life.  But without it, I'm sitting here completely blocked by a single tiny bug that I have absolutely no way of figuring out where it came from, and all I would need to do is add one, teeny, tiny little command:

```
 bundle = fuse
  .bundle("app")
  .rawEdit((fileName, content) => 
    fileName === "app.js" ? content.replace(/tslib@[.\d]+/g, "tslib") : content
  )
```

I need this so badly.  With something like this, I could fix every single problem from now until the end of time, even if the fix was sloppy duct tape.  But without this feature, I'm stuck sitting here, looking at 6 characters I have no I idea where they came from, having a totally broken project.


THIS IS A BIG DEAL.

I know I'm going on and on here, but seriously, this is really, really, really important.  There needs to be a safety release.  There needs to be a back up.  Fuse-box will never be perfect, and when it hits a point of total breakage, users need a way to patch it.  I can do nothing.  I tried using sparky to patch app.js, but it doesn't work.  Hmr() gets none of it, and there's race conditions.  It's totally not a solution.

But if I could modify the raw output of a bundle, just the straight up text, I could fix anything.  Anything ever, granted I was willing to put in the effort.  In this case the effort would be very minimal, but instead, the closest I can get to fixing this issue is posting an excessively long issue comment.

So please, please, hear me out.  Drop what you're doing, and spend the 20 minutes it'll take to create this plugin.

Here's the basic usage again:
```
function modifyRaw(parser: (outputName: string, content:string) => string): Plugin {
  // just before saving a file or pushing it to hmr, run the parser on the content
}
```


It would save every user from now until the end of time from being stuck in a position of being able to do nothing.  It's the kind of feature that's irresponsible not to have.  It's like having a kindling house with no fire escapes.   It's like driving without a seat belt.  It's like giving up your rights to amazon.  If everything works as it's supposed to, you're fine.  But when things go wrong, you're up shits creek with a turd for a paddle.

And that's where I am.  Up shits creek.  But with this function, I'd have salvation.  Ultimate peace for the rest of life.  Everything good happens when this feature happens, and everything bad happens when it doesn't.

Further, it would take absolutely no time for someone like you.

PLEASE.  I'm not afraid to beg.  I'll do it.  PLEASE HELP.  HALLLp.  I'm so fucked right now.  HELELEAPPPPPP.

**Comment by nchanged** [comment]
@SephReed there won't be any fixes to `v3` anymore. Please move to `v4`.
The issue you are facing is fixed there.
Join Gitter if you need any help.

**Comment by nchanged** [comment]
@SephReed any update on that?

**Comment by SephReed** [comment]
The replace plugin appears to be working, though I'd already reorganized my project around not using tslib by the time I found it.  I think I'm finally hitting a patch where I'll have the appropriate time to move over to v4.  I'm absolutely interested in joining gitter.  What's your channel name?

**Comment by nchanged** [comment]
https://gitter.im/fusebox-bundler/Lobby

I am closing this issue for now.
