### ISSUE TITLE
V4- sparky src/dist - bug ?

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box#1582]
If I have a sparky task script file inside folders it does not work as expected.
Best behavior would be if it used scripts location as basepath for src and dest.

Ready to test version of script is here
https://github.com/vegarringdal/bug-4
scripts
* `npm run copy-bug1`
* `npm run copy-bug2`
* `npm run copy-hack`

```js
const PATH = process.argv[3];
if (PATH) {
  process.chdir(__dirname);
}

const { sparky } = require("fuse-box");
class Context {}
const { task, src } = sparky(Context);

task("copy-bug1", async context => {
  // expected behavior would be that this uses script location "_dirname" as basepath on both
  // with this one nothing happend because it does not find any files
  await src(`./src/**/*.*`)
    .dest(`./dist/ts`, `src`)
    .exec();
});

task("copy-bug2", async context => {
    // this will find files
    // but it will break and say it cant find file under :
    // .... package/cool/package/cool/src/index.ts
    // looks like it adds _dirname to the src path
    await src(`./package/cool/src/**/*.*`)
      .dest(`${PATH}/dist/ts`, `src`)
      .exec();
  });

task("copy-hack", async context => {
  await src(`./src/**/*.*`)
    // supply it with path './package/cool'
    .dest(`${PATH}/dist/ts`, `src`)
    .exec();
});


```

**Comment by vegarringdal** [comment]
closing

**Comment by nchanged** [comment]
@vegarringdal sorry did you get it resolved? ;-)

**Comment by vegarringdal** [comment]
I though I just messed up so removed it.
But now when I test more it looks like something goes very wrong when my file with the task in not on root where npm gets run from

**Comment by vegarringdal** [comment]
or Im just very tired messing up

**Comment by vegarringdal** [comment]
@nchanged 
Is this understandable ?

```js

// script gets started from "npm start"
// this runs : node ./package/cool/tasks copy-now


const { sparky } = require("fuse-box");
class Context {}
const { task, src } = sparky(Context);

// unless I have this it fails
process.chdir(__dirname);


task("copy-now", async context => {
  await src(`./src/**/*.*`)
    .dest('./package/cool/dist/ts', `/src/`) 
    // the dest() is not behaving like I expected, its like its not following process.cwd() or __dirname
    // but unless I set process.cwd() to __dirname it wont copy, but I still haveto use npm base ?
    .exec();
});

```

**Comment by vegarringdal** [comment]
@nchanged 
Im making a new sample repo so you can confirm if Im going crazy 😂

**Comment by vegarringdal** [comment]
@nchanged 

Tried to make a simple sample
https://github.com/vegarringdal/bug
Is this working like intended?
For me the behavior is messing up when not on root of project

### clone and npm install
* `git clone https://github.com/vegarringdal/bug`
* `npm install`

### Then run these scripts, then look into source of the first 2

* `npm run working1` runs : "node ./tasks working1"
* `npm run working2-but-weird` runs : "node ./package/cool/tasks working2-but-weird"
* `npm run failing-but-why` runs : "node ./package/cool/tasks failing-but-why"

**Comment by vegarringdal** [comment]
fixed
