### ISSUE TITLE
ReplacePlugin example is misleading

### ISSUE THREAD

**Issue by ericlenio** [fuse-box/fuse-box#1592]
On https://fuse-box.org/docs/plugins/replace-plugin it uses `$versionPlaceHolder` as a replacement key so I followed a similar pattern. But it did not work for me. In examining the code in ReplacePlugin I see that this is interpreted as RegExp so the use of the dollar sign meant the replacement would never actually work.

**Comment by nchanged** [comment]
@ericlenio that has been fixed in `v4` version. Please refer [here](https://github.com/fuse-box/fuse-box/blob/v4/docs/plugins/pluginReplace.md)
