### ISSUE TITLE
v4 - "npm run dist" fails with antd package as dependency

### ISSUE THREAD

**Issue by kurdin** [fuse-box/fuse-box#1593]
with FuseBox 4.0.0-alpha.84  and election, building production dist fails if using `antd` package as dependency in React app

bug repo:
https://github.com/kurdin/fuse-box4-electron-seed-run-production-dist-bug-with-antd

```
npm run dist

throws error

    Transpile "rc-util/es/Children/toArray" from rc-tree@2.0.0/es/util.js to rc-util/es/Children/toArray.js(node:53475) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'productionModule' of undefined
this error happends because of usage "antd": "^3.22.0" package

```

**Comment by nchanged** [comment]
It's fixed here. 
`fuse-box@4.0.0-next.89`

You would need to check [this one](https://github.com/fuse-box/fuse-box/blob/master/docs/logging.md#tweak-logging-messages) too
