### ISSUE TITLE
wild cards in v4

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#1594]
Hi, are wild card imports supported in v4 ?

**Comment by nchanged** [comment]
The same as with v3 - only for development

**Comment by tomitrescak** [comment]
Well, no matter how I specify the arithmetics in my "fuse.js" the files are not included in the bundle ...

**Comment by nchanged** [comment]
@tomitrescak if you didn't notice, that API has changed completely. There is no arithmetics anymore.

https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md

`fuse-box@next`
