### ISSUE TITLE
v4 module not resolved

### ISSUE THREAD

**Issue by DaveO-Home** [fuse-box/fuse-box#1598]
Similar to issue #1596
 → Running default
 → Running test
 → Running clean
 → Running copy
 ✔ Assemble completed
    WebIndex writing to index.html

⚙  FuseBox 4.0.0-next.90
 ⚠️  Completed with 38 warnings in 3s 817ms
 31 packages with 576 files
 HMR server is running on port 3080
 Development server is running at http://localhost:3080
 ⚠️  Cannot resolve ../components/start.component in /ng/public/fusebox/appl/router/index.ts

In top level src directory: entry.ts
`import { AppRoutingModule } from './router'`   <==== this is resolved.

In ./router/index.ts
`import { StartComponent } from '../components/start.component';` <===== not resolved

**Comment by nchanged** [comment]
@DaveO-Home hi, could you reproduce the issue?

**Comment by DaveO-Home** [comment]
@nchanged Well I disabled "aliases" and simply used relative and everything is resolve....I have other issues, will try to work them out.  By the way, with next.91 I got
`TypeError: Cannot read property 'error' of undefined
    at resolveStatement (/home/daveo/NetBeans/acceptance-tests-ng/public/node_modules/fuse-box/main/assemble.js:79:27)
    at /home/daveo/NetBeans/acceptance-tests-ng/public/node_modules/fuse-box/main/assemble.js:156:30
    at Array.forEach (<anonymous>)
    at processModule (/home/daveo/NetBeans/acceptance-tests-ng/public/node_modules/fuse-box/main/assemble.js:155:38)
    at /home/daveo/NetBeans/acceptance-tests-ng/public/node_modules/fuse-box/main/assemble.js:186:21
    at Array.forEach (<anonymous>)
    at processModule (/home/daveo/NetBeans/acceptance-tests-ng/public/node_modules/fuse-box/main/assemble.js:177:17)
    at /home/daveo/NetBeans/acceptance-tests-ng/public/node_modules/fuse-box/main/assemble.js:186:21
    at Array.forEach (<anonymous>)
    at processModule (/home/daveo/NetBeans/acceptance-tests-ng/public/node_modules/fuse-box/main/assemble.js:177:17)`

**Comment by nchanged** [comment]
@DaveO-Home you should try using `paths`  and `baseURL` in tsconfig.json

**Comment by DaveO-Home** [comment]
@nchanged  I have "baseUrl": "./appl" and my "src" is "appl".  What do you mean by "paths"?
This is an angular2 app with both .ts and .js modules.  I believe I had the same issue with fusebox3.

**Comment by nchanged** [comment]
@DaveO-Home there shouldn't any issues now. Don't use aliases use baseUrl and `paths` if nessesary 
https://github.com/fuse-box/fuse-box/blob/master/docs/monorepo.md

And a working lerna monorepo -> https://github.com/squidfunk/fusebox-lerna-multi-monorepo/

**Comment by DaveO-Home** [comment]
This is working, looks a little non-standard 
`import { StartComponent } from 'ts/start.component';` 

`"baseUrl": "./appl",

        "paths": {
            "js/*": ["./js/controller/*", "./js/utils/*", "./js/*"],
            "ts/*": ["./components/*", "./services/*", "./*"]
          }
`
Great job @ v4, I'm learning Sparky and now struggling with "copy"!!!

**Comment by nchanged** [comment]
FuseBox conforms to standards defined by typescript 100% - rest assured. I am not seeing where it's non-standard. 

Your implementation suggests the following: Everything starting with `ts/*` search in ./components and services. If you wish to have a different approach. Move your baseUrl higher, you can also remove paths it will still index your folders.

I think I am going to write a documentation on this one, **even** there is an [official doc](https://www.typescriptlang.org/docs/handbook/module-resolution.html)


Regarding sparky, maybe [this](https://github.com/fuse-box/fuse-box/blob/master/fuse.ts#L69-L73) could you help

**Comment by DaveO-Home** [comment]
I'm sure fusebox is totally compliant, just saying a JavaScript programmer would wonder about "js/..".
Well finally got  my copy task to work.  Turns out that "dest" is relative to `output: "../dist"`. So instead of `dest: "../dist"` it must be `dest: "dist"`.

Finally got the angular app to load, now I have to get font-awesome to load and the css files to load in the right sequence.  By the way, I couldn't get css @import to work.

**Comment by nchanged** [comment]
@DaveO-Home which CSS preprocessor? it all works like a charm with SCSS, less, postcss and stylus.

**Comment by DaveO-Home** [comment]
@nchanged I used SCSS in another app and it worked seamlessly.  The @imports are working fine, I believe the newer version of angular might work differently. With a few adjustments the app is now running v4 without a hitch, anyway under the HMR server. I'm sure there will be adjustments for production. Thanks for the help
