### ISSUE TITLE
Stylelint and eslit support

### ISSUE THREAD

**Issue by tonimain** [fuse-box/fuse-box#160]
Are there some plugins for those two? I think it's necessary for modern coding standards to prevent errors in code and preserve guidelines.

**Comment by devmondo** [comment]
@tonimain  welcome, yea we already have a user who created one we will have list of them soon, hang in :)

**Comment by tonimain** [comment]
@devmondo is there a link to the repo i need this for a new production environement starting next week. would be great to use it / test it /debug it so we could contribute back.

**Comment by nchanged** [comment]
@tonimain there is [something](https://github.com/fuse-box/fuse-box/blob/master/docs/third-party-plugins.md)

**Comment by DoumanAsh** [comment]
You can try my ESlint plugin https://github.com/DoumanAsh/fuse-box-eslint-plugin
Suggestions are welcome ;)

**Comment by devmondo** [comment]
Hope the above plugin works out for you.

Closing this for now, let us know otherwise :)
