### ISSUE TITLE
v4 static output file name without hash

### ISSUE THREAD

**Issue by kurdin** [fuse-box/fuse-box#1600]
It should be possible to just specify static output application name without hash, 

```
output: 'dist/injectapp/my-static-app-name.js'
```
In some cases hash is not possible to pickup for embedding filename into injected script in election for example. 

Option `hash: false`  not working in v4 as well.

**Comment by patrickmichalina** [comment]
Same issue here

**Comment by nchanged** [comment]
How about this [section](https://github.com/fuse-box/fuse-box/blob/master/docs/electron.md#production-builds) You have a manifest file.

**Comment by kurdin** [comment]
@kurdin I don't think manifest file can help in case of development. For production, hash help for sure but in development is just unnecessary overhead. Not sure how your HMR works in fusebox but it would be the best to have single output file with embedded HMR code that can detect source changes and do module reloading, same way as webpack-dev-server works, again adding hash in dev env in not needed in 90% of cases.

**Comment by nchanged** [comment]
@kurdin there is no hash during development. I mean there is, but that's necessary. That preffix is a  hash of `{homeDir + entryPoint}` since user might pipe in several instances with different entry points -> then there is a problem

**Comment by nchanged** [comment]
Besides, have you guys seen this? https://github.com/fuse-box/fuse-box/blob/master/docs/electron.md#launching

**Comment by kurdin** [comment]
>Besides, have you guys seen this
@nchanged yes I did and I was able to get bundle file name with something like `bundle.context.output.lastPrimaryOutput.filename` but still could not figure out to use it to replace static file path in my source file. I did not play with it much, I thought `hash: false` should fix my problem, still not sure why not to allow in some cases build output file without hash. I understand what you saying about hash but in some cases, for some bundles, it is useful to turn in off and use static file as `output` (why not). 

Now with electron I need 3 bundles, `main`, `renderer` and `inject` script that I use to inject my app into webview, why not to allow for third bundle has static file name, I don't understand.

**Comment by nchanged** [comment]
Could you guys describe a proposed solution to the problem you are facing . And maybe a more detailed picture of what's wrong

**Comment by kurdin** [comment]
@nchanged solution is simple, as we describe it before, `hash: false` should work as expected in v4, if bundle settings for `fusebox({})` has  `hash: false` and `output: : 'dist/main/$name'` then created bundle name in `dist/main/` should has no dynamic hash, just static filename with `$name` of the bundle.

**Comment by patrickmichalina** [comment]
PR: https://github.com/fuse-box/fuse-box/pull/1642

**Comment by patrickmichalina** [comment]
This should be closed as of `4.0.0-next.138` or `4.0.0-next.139` (139 will likely include fixes related to output names).

**Comment by charsleysa** [comment]
Closed due to inactivity.
