### ISSUE TITLE
SVG reference resolver

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#1606]
The contents of SVG should be optionally resolved.

should work via importing in CSS
```scss
background-image: url("./some.svg"); //   the contents should be resolved too
```

Via import

```ts
import some from "./some.svg"; // should be resolved here
```

The functionality can be enabled it by using a flag in `resources` field `svgResolveContentReferences` to avoid additional overhead for those who just import icons.
CC @bsl-zcs

**Comment by charsleysa** [comment]
Closed due to inactivity.
