### ISSUE TITLE
Support consolidate, the template engine consolidation library

### ISSUE THREAD

**Issue by patrickmichalina** [fuse-box/fuse-box#1609]
Fusebox v3 supported the ability to use template engines instead of plain HTML for generating the web-index file. This is particularly useful for passing in local variables/configuration that may need to change depending on dev/prod or for different targets.

[https://www.npmjs.com/package/consolidate](https://www.npmjs.com/package/consolidate)

**Comment by jeremy-coleman** [comment]
@patrickmichalina 
a pattern i have found increasingly useful is to separate transpiling and bundling logic, the main idea being the bundler should only see assets that are ready for browser use (js, css, json, resources). Normally i just point the bundler to a temp directory , usually using gulp.  Any ideas on a cleaner integration? it would solve this issue and any other asset type

**Comment by patrickmichalina** [comment]
@jeremy-coleman Yeah that totally works too - i'd prefer to no need an additional task to achieve this though. Especially considering this bundler actually creates the index.html file, I think its perfectly acceptable that it has a few more options for how that file is created. If you look at fusebox v3, there were many options to enable modifying the index.html output.

**Comment by kyr0** [comment]
@patrickmichalina I'll look into it

**Comment by kyr0** [comment]
Initial implementation is already done. I'll PR it tomorrow.

**Comment by kyr0** [comment]
PR #1621
