### ISSUE TITLE
Cannot resolve v8 or vm

### ISSUE THREAD

**Issue by patrickmichalina** [fuse-box/fuse-box#1616]
This worked perfectly fine in Fusebox v3.

```
const v8 = require('v8')
```

**Comment by nchanged** [comment]
@patrickmichalina just tried it with the latest `4.0.0-next.129`

```
import * as v8 from 'v8';
import * as vm from 'vm';
console.log(v8, vm);

```

No problems whatsoever. You need to upgrade

**Comment by patrickmichalina** [comment]
<img width="830" alt="Screen Shot 2019-09-06 at 7 45 57 AM" src="https://user-images.githubusercontent.com/6701211/64428873-69230100-d07a-11e9-85d9-10e857aedfb8.png">

**Comment by nchanged** [comment]
Then it can't find this module. It was bundled correctly for me

**Comment by patrickmichalina** [comment]
The code is there, when I console out the import it shows the functions. This module is part of Node, it's not an NPM package.

**Comment by nchanged** [comment]
@patrickmichalina got you now!!! so we should ignore it then. You should have been more specific tho ;-)

**Comment by nchanged** [comment]
@patrickmichalina try `@next`

**Comment by patrickmichalina** [comment]
You are right. I will be more specific next time, thanks.
