### ISSUE TITLE
Generate index.html if file not found when using webIndex

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#1618]
Generate index.html on the specific path (`src/index.html`) if file not found when using webIndex with default contents (which are available in the repository)

@kyr0  since you been tinkering with webIndex anyway, do you think you can take that one in to?

**Comment by kyr0** [comment]
Read it too late, but I'll do this in another PR then, it's simple.

**Comment by kyr0** [comment]
@nchanged Close? :)
