### ISSUE TITLE
Chrome Extension example

### ISSUE THREAD

**Issue by mattgi** [fuse-box/fuse-box#1622]
I use FuseBox for regular web app projects but am now looking to create a Chrome Extension. I assume this should be possible, but am wondering where to get started - how to generate a manifest file, what to include, etc.

Has anyone done this or does any guidance already exist?

If not, can a sample be added on how to use FuseBox for such a use case? (I really, really, really, don't want to revert to Webpack and Babel which appears to be what every react dev is doing in this space).

**Comment by nchanged** [comment]
Hey, I am 100% sure it's possible .

Have you checked v4 yet ?
https://codesandbox.io/s/github/fuse-box/react-example

You can try the live example

Join our slack channel slack.fuse-box.org we will help you, also it would make sense to share the knowledge and create a bootstrap project

**Comment by kyr0** [comment]
@mattgi I know your struggle, here is a sample chrome extension for my SpringType framework I created. You'd just need to make sure you include all the meta files. I the end your extension should consist of a folder with all the meta data and built JS (main.js) just like any other web app.

Start with the `manifest.json` and work your way thru the code :)

https://github.com/springtype-org/springtype/tree/master/src/devtools/src

**Comment by mattgi** [comment]
Thank guys.

I sat back for a while after posting and then realised I could probably hack it a bit from what I was used to.

Basically the end result is a single folder that includes the manifest, icons, and js files. On file change, it repackages and I can refresh the extension in Chrome and away I go

I have a src folder with my icons, manifest, and two typescript entry point files.. and then just hooked it all up as follows:

```
const { FuseBox, EnvPlugin, CopyPlugin, CSSPlugin, JSONPlugin, QuantumPlugin } = require("fuse-box");
const { src, task, context } = require("fuse-box/sparky");

context(
  class {

    async createBackground() {
      const fuser = FuseBox.init({
        homeDir: "src",
        output: "public/$name.js",
        sourceMaps: !this.isProduction,
        plugins: [this.isProduction && QuantumPlugin({ bakeApiIntoBundle: "background.js", containedAPI: true })]
      });
      const bundle = fuser.bundle("background").instructions("> Background.ts");
      if (!this.isProduction) {
        bundle.watch();
      }
      await fuser.run();
    }

    async createContent() {
      const fuser = FuseBox.init({
        homeDir: "src",
        output: "public/$name.js",
        sourceMaps: !this.isProduction,
        plugins: [JSONPlugin(), CSSPlugin(), EnvPlugin({ NODE_ENV: process.env.NODE_ENV }), this.isProduction && QuantumPlugin({ bakeApiIntoBundle: "content.js", containedAPI: true })]
      });
      const bundle = fuser.bundle("content").instructions("> Content.tsx");
      if (!this.isProduction) {
        bundle.watch();
      }
      await fuser.run();
    }
  }
);

task("clean", async () => {
  await src("public")
    .clean("public")
    .exec();
  await src(".fusebox")
    .clean(".fusebox")
    .exec();
  await src(["manifest.json", "icon-16.png", "icon-48.png", "icon-128.png"], { base: "./src" })
    .dest("public/")
    .exec();
});

task("default", ["clean"], async context => {
  context.createBackground();
  context.createContent();
});
```

I think it can be cleaner.. and I'm used to having a task that is more like:

```
  const fuse = context.getConfig();
  fuse.dev({ port: process.env.PORT || 3000, fallback: "index.html" });
  context.createBundle(fuse);
  await fuse.run();
```

but as I wanted the file copying and the two files I ended up with the above.. any improvements you see from a cursory glance?
