### ISSUE TITLE
Is there a comparable solution to webpack's require.resolveWeak?

### ISSUE THREAD

**Issue by verydanny** [fuse-box/fuse-box#1632]
I use webpack's `require.resolveWeak(module)` to gather the module ids that were just `renderToString`'d by React by my home-rolled solution based on React loadable.

Here is the repo: https://github.com/verydanny/ssr-example

FuseBox is extremely tempting to me because of the insanely fast Typescript compilation, but the thing holding me back is knowing which dynamic chunks to serve the client before the bundle is parsed. I don't want to parse the bundle, compile, then download the dynamic chunks on initial render.

Thanks to webpack's stats and `require.resolveWeak(module)` I can do a lookup between client and server stats to know which chunks are about to be rendered on the client. On the client I can again do a `__webpack_modules[require.resolveWeak(module)]` to make sure the chunk is loaded before rendering which results in a quicker hydration, and no need for React to patch client/server differences. This results in the server being fast and synchronously serving react routes quick, but the client still being dynamic after the initial render. 

I'm wondering if there's something like this in FuseBox, or a plugin I can write to implement something like this.

The documentation is still in development I'm sure, and I'm happy to contribute to something other than webpack.

**Comment by nchanged** [comment]
@verydanny I think you are talking about dynamic imports. Here is an [example](https://github.com/fuse-box/fuse-box/tree/master/playground/universal) in the playground

I am going to move it to a sandbox soon.

It basically consists of a [config](https://github.com/fuse-box/fuse-box/blob/master/playground/universal/src/app/config.ts) and a router:


https://github.com/fuse-box/fuse-box/blob/bed8cde42015758007ba576c3dba703d7997f002/playground/universal/src/app/Router.tsx#L17-L43

I Believe that's what you are looking for.

FuseBox is very powerful, and such tasks are solved elegantly without reinventing the wheel with some awkward functions ;-)

**Comment by nchanged** [comment]
@verydanny there you here is a [github repo](https://github.com/fuse-box/sandbox/tree/master/react-universal) and here is (god bless codesandbox) you can try it [live](https://codesandbox.io/s/github/fuse-box/sandbox/tree/master/react-universal)

**Comment by verydanny** [comment]
@nchanged 

That's not quite what I'm referring to. If you check out: 

https://github.com/verydanny/ssr-example/blob/master/src/server/middleware/render.tsx#L31-L47

My code allows me to know which JS chunks are about to be served to the client, for the server side. It's not just limited to routes, it's any React componnent, or any module import for that matter. When the server is rendering that React application, I know that X module is about to get served to client, so I can lookup the appropriate chunk that I need in my stats.json (manifest).

**Comment by verydanny** [comment]
This approach basically lets me use `PreloadAll` to preload all dynamic chunks on the server BEFORE the server starts so the promises to the `import()` is already resolved. Then I can load all the chunks before the main bundle on the client side so my client side code can hydrate quicker.

**Comment by nchanged** [comment]
@verydanny that's exactly what's happening the example.

https://github.com/fuse-box/sandbox/blob/3bac740adc3eed968a2aa101b652a63edc2fb6cc/react-universal/src/app/Router.tsx#L19-L20

However, I do certainly know which modules to load (they are in the config)

So you are saying that you would like to hack into dynamic imports and intercept the events? That's very ugly TBH.  Are you sure that it's the best approach to go about this issue? That can really introduce quite an amount of "very-hard-to-catch" bugs and such.

It's doable certainly, but require a runtime interceptor, we could have one via a plugin. If I had more specs tho. What I won't certainly tolerate is `resolveWeak` or any other magical functions.

**Comment by verydanny** [comment]
I also loathe the `require.resolveWeak` approach, but it is one way to intercept these dynamic imports before they're served to the client. It is useful for an initial client render because the client doesn't have to parse the bundle before knowing stuff like, "deep in bundle A, there is a dynamic import for Lodash, so I should start a fetch for that". I can already have Lodash downloading before the client finishes parsing the HTML document, much less the bundle. 

THEN if there's another dynamic component, say a modal or registration, etc. dynamic can work as intended and create a new request for the module.

This is another way of doing it: https://github.com/theKashey/react-imported-component#concurrent-loading

It's just even uglier in my opinion and requires massive libs, and a Babel plugin (ew).

**Comment by nchanged** [comment]
There is another thing - development bundles are much simpler by nature, and the amount of bundles varies drastically for production for the obvious reason - Speed. 

So, I assume we have no issues during development am I right? Let's imagine that we don't. 
Then during on production we could build a detailed manifest for split bundles which is [relatively easy](https://github.com/fuse-box/fuse-box/blob/master/src/production/stages/codeSplittingStage.ts#L45)

`codeSplittingStage` has entry points for all the split bundles along with all related modules.

I can help you implement a plugin If you feel like contributing ;-)

**Comment by verydanny** [comment]
I am trying to migrate our companies build away from webpack. I'd be happy too. I need somewhere to start in FuseBox though. I'm going to check out the source code.

Do you have a Discord or Slack? I have many questions. I'd love to write a plugin.

**Comment by nchanged** [comment]
https://slack.fuse-box.org/ please join ;-)

**Comment by charsleysa** [comment]
@verydanny can you please confirm if the issue still occurs with `fuse-box@4.0.0-next.400`?
Also see [here for info on major changes](https://github.com/fuse-box/fuse-box/blob/master/docs/changelog-fuse-compiler.md)

**Comment by charsleysa** [comment]
Closed as no response received.
