### ISSUE TITLE
UnhandledPromiseRejectionWarning when doing a prod bundle in v4

### ISSUE THREAD

**Issue by koffmoff** [fuse-box/fuse-box#1634]
Got an `UnhandledPromiseRejectionWarning` when doing a prod bundle:

```
source transform @stardust-ui/react-component-event-listener/dist/es/useEventListener.js(node:11852) UnhandledPromiseRejectionWarning: Error: Error replacing tree: The children of the old and new trees were expected to have the same count (2:1).
```

Repro-repo here: https://github.com/koffmoff/fuse-box-test

**Comment by charsleysa** [comment]
@koffmoff can you please confirm if the issue still occurs with the latest v4 alpha?

**Comment by nchanged** [comment]
here is a changelog https://github.com/fuse-box/fuse-box/blob/master/docs/changelog-fuse-compiler.md

**Comment by charsleysa** [comment]
Closed as no response received.
