### ISSUE TITLE
Add to bundle any files for some package

### ISSUE THREAD

**Issue by Pencroff** [fuse-box/fuse-box#1635]
Hi.

I would like to bundle `dialogflow` package (this is for function / serverless environment).
It has dependencies from `@grpc/proto-loader` and `google-gax`.

Both of them in runtime loading from `*.proto` files file system :

* @grpc/proto-loader [link](https://github.com/grpc/grpc-node/blob/master/packages/proto-loader/src/index.ts#L332)

example from repo:

```typescript
const wellKnownProtos = ['api', 'descriptor', 'source_context', 'type'];
  const sourceDir = path.join(
      path.dirname(require.resolve('protobufjs')), 'google', 'protobuf');
  for (const proto of wellKnownProtos) {
    const file = path.join(sourceDir, `${proto}.proto`);
    const descriptor = Protobuf.loadSync(file).toJSON();
    // @ts-ignore
    Protobuf.common(proto, descriptor.nested.google.nested);
  }
```

This package trigger error like `TypeError: require.resolve is not a function`.
I can fix it by usage `ReplacePlugin` like:

```javascript
    ReplacePlugin({
      "require.resolve('protobufjs')": `'${require.resolve('protobufjs').replace(/\\/g, '/')}'`,
    }),
```
in result I will have full path and I can work with it,
but this doesn't solve main mine issue adding in bundle set of files by `glob` pattern.

* google-gax [link](https://github.com/googleapis/gax-nodejs/blob/92a11c1a2e6794fa7b0301d2dabea2a0f8149ccc/src/grpc.ts#L45)

example from repo:

```typescript
const googleProtoFilesDir = path.join(__dirname, '..', '..', 'protos');

// INCLUDE_DIRS is passed to @grpc/proto-loader
const INCLUDE_DIRS: string[] = [];
INCLUDE_DIRS.push(googleProtoFilesDir);

// COMMON_PROTO_FILES logic is here for protobufjs loads (see
// GoogleProtoFilesRoot below)
const COMMON_PROTO_FILES = walk
  .sync(googleProtoFilesDir)
  .filter(f => path.extname(f) === '.proto')
  .map(f => path.normalize(f).substring(googleProtoFilesDir.length + 1));
```
This package trigger error like

```
Error: error reading first path in the walk protos
Error: ENOENT: no such file or directory, lstat 'protos'
```
I think it's because no `*.proto` file available in bundle.
They expected to be on file system in package.

I tried few ways to add `proto` files to bundle by existing plugins like (any of it doesn't work):

* `RawPlugin(['.proto']),`
* `CopyPlugin({ files: ['node_modules/google-gax/protos/**/*.proto'], dest: 'protos' }),`
* `['./node_modules/google-gax/protos/**/*.proto', RawPlugin()],`

#### **Could you please advise how I can bring any file to bundle under some package name?**

For example I provide config to some plugin or create my own:

```javascript
{
    'google-gax': './**/*.proto'
}
```
 and it fill add in scope of `google-gax` package all `proto` files as you can see below:

```javascript
FuseBox.pkg("google-gax", {}, function(___scope___){
    ___scope___.file("descriptor/abc.proto", function(exports, require, module, __filename, __dirname) {
        module.exports="content of proto file"; // As I saw in CSS plugin
    })
});
```
I would expect all implementations for `fs` works with bundle.

**Comment by Pencroff** [comment]
### Update:

I generated all dependencies by 
```
const { resolve } = require('path');
const { writeFileSync } = require('fs');
const glob = require("glob");
const options = {
  cwd: resolve('../'),
};
const filePath = resolve('../src/proto.ts');
glob('node_modules/**/*.proto', options, function (er, files) {
  if (er) {
    console.error('Error!');
    console.dir(er);
  }
  const data = '// DO NOT CHANGE THIS FILE\n// AUTOGENERATED CONTENT\n' +
    files
    .map((item) => item.replace('node_modules/', 'import \'')+'\';') // * as file${idx} from
    .join('\n') + '\n';
  writeFileSync(filePath, data);
});
```
and import all `proto` files to bundle.
But it does,'t solve an issue with walker in second case.

Would you suggest some solution?

**Comment by nchanged** [comment]
Hey, to begin with it looks like you are using v3, we are working on v4 which is out from the alpha test to the next stage, please upgrade to v4 as soon as possible, since v3 is no longer maintained.

One of the solutions is not to bundle this dependency as FS is a hard requirement for this module

**Comment by Pencroff** [comment]
Thank you for response. Found a solution by correct copy files beside of bundle.

**Comment by nchanged** [comment]
@Pencroff glad to hear that. However I will address computed statements later on. Feel free to join our slack for a chat! 
http://slack.fuse-box.org
