### ISSUE TITLE
Allow removal of lazy loaded hashes in output files.

### ISSUE THREAD

**Issue by patrickmichalina** [fuse-box/fuse-box#1636]
## Feature Request

Currently, when outputting production bundles that are "code-split" into lazy loaded modules they use a filename format that looks like `$hash-about-about.module.js`. Sadly, when an app uses service-workers for progressive web apps (PWA), the caching will request assets that are no longer available on stateless servers that do not maintain previous builds. This leads to a 404 until the users reloads the page. One solution is to upload ALL js assets to a bucket and reverse proxy if failed to find on the origin server - but this is a lot of extra work and billing for something that could be better handled by keeping the same file names.

[Angular's PWA docs](https://angular.io/guide/service-worker-communications#forcing-update-activation) mention this as well:
```Doing this could break lazy-loading into currently running apps, especially if the lazy-loaded chunks use filenames with hashes, which change every version.```

Maybe:
```js
fusebox({
    codeSplitting: { removeHashes: true }
}).runProd()
```

**Comment by nchanged** [comment]
I think we could just use hash false, there was a related ticket about it already
