### ISSUE TITLE
Documentation of extension not handled out of the box

### ISSUE THREAD

**Issue by delaneyj** [fuse-box/fuse-box#1637]
Fusebox 4@next has been working great for me.  Added a file @ `src/assets/shaders/msdf.pixi.vert` and getting `default/src/assets/shaders/msdf.pixi.vert has not been processed by any plugins ` error.  The documentation for the equivalent of `file-loader` from webpack doesn't seem to exist.  Any guidance here?

**Comment by nchanged** [comment]
Hi, it's just called differently :) v4 takes a lot of extensions by default, I assume this is what you are looking for 

https://github.com/fuse-box/fuse-box/blob/master/docs/resource_links.md#via-plugin

**Comment by delaneyj** [comment]
Sorry I'm probably missing something.  I wanted to load the contents of the file as a string/buffer instead of the url of the file.

**Comment by nchanged** [comment]
then `pluginRaw` is the one you need.

https://github.com/fuse-box/fuse-box/blob/master/src/plugins/core/plugin_raw.ts#L17

`pluginRaw("*.ver")`
