### ISSUE TITLE
ES6 to ES5 translation error of  "for of" loops targeting Set objects 

### ISSUE THREAD

**Issue by guins** [fuse-box/fuse-box#1638]
In my projet I have a node module dependency delivered in ES6 which is incorrectly translating to ES5 in my output bundle.

Indeed, I have "for of" loops wrongly translated to simple "for" loops, even when the target is a Set object. The problem being that the property `length` doesn't exist on a set object !
For exemple : 
```
let items = new Set();
for(item of items) { ... }
```
ouput like this:
```
let items = new Set();
for(let i=0; i<items.length; i++) {
     // Will never end up in this for loop because "items.length" will always be "undefined"
}
```

Any idea how to fix this ?

**Comment by nchanged** [comment]
@guins that's typescript, unfortunately we can't do much now. Not at this stage. You should set target `ES2017` then it will be transpiled correctly.  Alternatively add a polyfill to fix the issue

**Comment by charsleysa** [comment]
@guins can you please confirm if the issue still occurs with the latest v4 alpha?

**Comment by charsleysa** [comment]
Closed as no response received.
