### ISSUE TITLE
transformTypescript

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#164]
Implement `transformTypescript` in the Plugin API, to allow transforming typescript code before it gets transpiled.

**Comment by tomitrescak** [comment]
I just woke up and seen this good news;) way to start the day! Would you be kind and provide a small example on how to use it? If you already did in docs I apologize. Just got excited.

**Comment by nchanged** [comment]
Yeah I updated the docs! Good morning! :)

**Comment by tomitrescak** [comment]
Found it, thanks!
