### ISSUE TITLE
node css resources not copied when target is 'electorn'

### ISSUE THREAD

**Issue by Zaitsev** [fuse-box/fuse-box#1649]
way to reproduce:
https://github.com/Zaitsev/react-example
when target is 'browser'  `typeface-roboto` module's fonts copied to ./dist/resources
when target is 'electron' ./dist/resources is not created

**Comment by charsleysa** [comment]
@Zaitsev can you please confirm if the issue still occurs with `fuse-box@4.0.0-next.400`?
Also see [here for info on major changes](https://github.com/fuse-box/fuse-box/blob/master/docs/changelog-fuse-compiler.md)

**Comment by nchanged** [comment]
this has been fixed!
