### ISSUE TITLE
Error > Buffer is not defined

### ISSUE THREAD

**Issue by mrjjwright** [fuse-box/fuse-box#165]
I know this is a rookie mistake and I am sorry.  But I am getting the following error on a TypeScript/React only project.

<img width="656" alt="screen shot 2017-02-14 at 8 42 20 am" src="https://cloud.githubusercontent.com/assets/4343/22936073/a0fb6654-f291-11e6-8afc-eb13046ea5b0.png">

Here is my tsconfig.json

```es6
{
  "compilerOptions": {
    "sourceMap": true,
    "target": "es5",
    "module": "commonjs",
    "outDir": "build/",
    "lib": [
      "dom",
      "es2015",
      "es2016"
    ],
    "isolatedModules": false,
    "moduleResolution": "node",
    "jsx": "react",
    "allowJs": true,
    "skipLibCheck": true,
    "strictNullChecks": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "declaration": true,
    "noLib": true,
    "noEmitHelpers": true,
    "noImplicitAny": false,
    "removeComments": true,
    "preserveConstEnums": true,
    "suppressImplicitAnyIndexErrors": true
  },
  "compileOnSave": true,
  "buildOnSave": false,
  "exclude": [
    "node_modules",
    ".fusebox",
    "now"
  ]
}
```

```es6
const {
  FuseBox,
  TypeScriptHelpers,
  CSSPlugin,
  JSONPlugin,
  CSSResourcePlugin
} = require("fuse-box");

FuseBox.init({
  homeDir: "./app",
  outFile: "./now/public/dist/en/bundle.js",
  sourceMap: {
    bundleReference: "sourcemaps.js.map",
    outFile: "./now/public/dist/en/sourcemaps.js.map"
  },
  plugins: [
    TypeScriptHelpers(),
    JSONPlugin(),
    [CSSResourcePlugin({ inline: true }), CSSPlugin()]
  ]
}).devServer("> main.tsx", { port: 8088, root: "now/public" });
```

**Comment by nchanged** [comment]
@mrjjwright welcome! It might be related to the hot reload bug or cache. Please, remove `.fusebox` folder and restart the process.

**Comment by mrjjwright** [comment]
Great to be here!  Darn, that didn't work.

**Comment by nchanged** [comment]
Ok, please check what are you bundling that requires `https` module.

**Comment by mrjjwright** [comment]
I will just bundling the app back together from scratch piece by piece until I isolate that

**Comment by mrjjwright** [comment]
Hello world works.  :)

**Comment by nchanged** [comment]
Are you still getting `https not found` ?

**Comment by mrjjwright** [comment]
Yeah I get it on my app which I converted over.  I have removed almost all dependencies but there are still some like styled components, mobx, etc...  I will see if I can get it to work by commenting out different modules.

**Comment by nchanged** [comment]
That would be great!

**Comment by mrjjwright** [comment]
I noticed that my code is loaded into browser as ES6.  Is that to be expected?

<img width="944" alt="screen shot 2017-02-14 at 9 04 41 am" src="https://cloud.githubusercontent.com/assets/4343/22937091/bca30fc6-f294-11e6-9df9-326b0266ccf6.png">

Here is what the React-Reflux-seed example (which I am modeling) looks like:

<img width="1390" alt="screen shot 2017-02-14 at 9 02 52 am" src="https://cloud.githubusercontent.com/assets/4343/22937103/cf1ac856-f294-11e6-8a72-94dde6ce01cf.png">

**Comment by nchanged** [comment]
I think you are looking at sourcemaps here...

**Comment by mrjjwright** [comment]
Ok thought so, just making sure everything looks ok.

**Comment by nchanged** [comment]
gitter? It's easier if we chat online

**Comment by nchanged** [comment]
I think I know what's the problem. Some library is not explicitly requiring `buffer` resulting in error. 
You can figure out the line by removing the sourcemaps (next to your bundle).

**Comment by nchanged** [comment]
We might check Buffer and other globals in the AST Analysis module, and add require statement there. That should fix it.

**Comment by mrjjwright** [comment]
Ok, the offender appears to be `firebase`.  Removing it seemed to fix that issue.  I will have to see what is going on.  Any recommendations on a workaround?  Thanks!!

**Comment by nchanged** [comment]
Yes, can you please check `firebase` code? Does it use Buffer without actually requiring it?

**Comment by mrjjwright** [comment]
Yeah I will look into it later.  Switching back to my master branch for now with straight up webpack and will work on this some more when I get some spare time.   Thanks so much for the help, looking great overall!

**Comment by nchanged** [comment]
#165

**Comment by nchanged** [comment]
https://github.com/fuse-box/fuse-box/commit/7fc76045a12273cab4dd34d0f8f3571296d81176
