### ISSUE TITLE
global not  polyfilled in browser runProd

### ISSUE THREAD

**Issue by Zaitsev** [fuse-box/fuse-box#1654]
Some packages that uses global (global.localStoreage etc) works in runDev  but global is undefined in runProd

**Comment by nchanged** [comment]
@Zaitsev should it point to `window` for browser builds in your opinion?

**Comment by Zaitsev** [comment]
there is a new  [globalThis](https://caniuse.com/#search=globalThis) and polyfils. For browsers - yes, it should be window IMO

**Comment by Teoxoy** [comment]
I came across this issue too. Will put up a PR for this.
