### ISSUE TITLE
4.0 - next.139 fails with angular

### ISSUE THREAD

**Issue by DaveO-Home** [fuse-box/fuse-box#1656]
SyntaxError: expected expression, got '}'
02d5dbfd5_vendor.js:29103:6
uncaught exception: Package not found events 02d5dbfd5_dev.js:189:7
    $getRef http://localhost:3080/dist_test/fusebox/02d5dbfd5_dev.js:189
    $import http://localhost:3080/dist_test/fusebox/02d5dbfd5_dev.js:365
    require http://localhost:3080/dist_test/fusebox/02d5dbfd5_dev.js:416
    <anonymous> http://localhost:3080/dist_test/fusebox/02d5dbfd5_dev.js:650
    $import http://localhost:3080/dist_test/fusebox/02d5dbfd5_dev.js:433
    require http://localhost:3080/dist_test/fusebox/02d5dbfd5_dev.js:416
    <anonymous> http://localhost:3080/dist_test/fusebox/02d5dbfd5_dev.js:593
    $import http://localhost:3080/dist_test/fusebox/02d5dbfd5_dev.js:433
    import http://localhost:3080/dist_test/fusebox/02d5dbfd5_dev.js:451
    <anonymous> http://localhost:3080/dist_test/fusebox/02d5dbfd5_app.js:2037
uncaught exception: Package not found core-js 02d5dbfd5_dev.js:189:7
    $getRef 02d5dbfd5_dev.js:189
    $import 02d5dbfd5_dev.js:365
    require 02d5dbfd5_dev.js:416
    <anonymous> main.ts:1
    $import 02d5dbfd5_dev.js:433
    import 02d5dbfd5_dev.js:451
    main 02d5dbfd5_dev.js:485
    <anonymous> 02d5dbfd5_entry.js:1

fails in vendor.js

tsf = ts.filter = {
      regex: {
        regex: /^\/((?:\\\/|[^\/])+)\/([migyu]{0,5})?$/,
        child: /tablesorter-childRow/,
        filtered: /filtered/,
        type: /undefined|number/,
        exact: /(^[\"\'=]+)|([\"\'=]+$)/g,
        operators: /[<>=]/g,
        query: "(q|query)",
        wild01: /\?/g,
        wild0More: /\*/g,
        quote: /\"/g,
        isNeg1: /(>=?\s*-\d)/,
        isNeg2: /(<=?\s*\d)//
      },
      types: { 
        or: function (c, data, vars) { <=============== here - syntax error
          if ((tsfRegex.orTest.test(data.iFilter) || tsfRegex.orSplit.test(data.filter)) && !tsfRegex.regex.test(data.filter)) {
            var indx, filterMatched, query, regex, data2 = $.extend({}, data), filter = data.filter.split(tsfRegex.orSplit), iFilter = data.iFilter.split(tsfRegex.orSplit), len = filter.length;
            for (indx = 0; indx < len; indx++) {
              data2.nestedFilters = true;
              data2.filter = "" + (tsf.parseFilter(c, filter[indx], data) || "");
              data2.iFilter = "" + (tsf.parseFilter(c, iFilter[indx], data) || "");
              query = "(" + (tsf.parseFilter(c, data2.filter, data) || "") + ")";
              try {
                regex = new RegExp(data.isMatch ? query : "^" + query + "$", c.widgetOptions.filter_ignoreCase ? "i" : "");
                filterMatched = regex.test(data2.exact) || tsf.processTypes(c, data2, vars);
                if (filterMatched) {
                  return filterMatched;
                }
              } catch (error) {
                return null;
              }
            }
            return filterMatched || false;
          }
          return null;
        },

**Comment by patrickmichalina** [comment]
`Package not found core-js`

**Comment by DaveO-Home** [comment]
@patrickmichalina that's a result of the error....

**Comment by nchanged** [comment]
@DaveO-Home can you install it? ;))) if that won't help, please reproduce it

**Comment by DaveO-Home** [comment]
@patrickmichalina - I tried various installs and reinstalls -- did find that when reverting back to next.138 I have to remove package-lock.json. So are there other  packages being updated along with fusebox?  My working app is @  https://github.com/DaveO-Home/embedded-acceptance-tests-ng - you can update to next.139.

**Comment by nchanged** [comment]
@DaveO-Home could narrow it down and reproduce? 

FYI we are moving away from the typescript compiler in favour of **fuse-compiler** which will solve many problems and be 10x faster than typescript ;-) That's why I am holding off resolving the open issues.

**Comment by DaveO-Home** [comment]
@nchanged - failure happens before the app starts, hard to pinpoint - will stay on .138 and wait for your new compiler.

**Comment by patrickmichalina** [comment]
The only change for 139 was lay loading path improvements. Are you using lazy loaded module via `import` syntax?

**Comment by DaveO-Home** [comment]
@patrickmichalina @nchanged - here's the difference between the two versions:
< regex: /^\/((?:\\\/|[^\/])+)\/([migyu]{0,5})?$/,
---
> regex: /^/((?:\/|[^/])+)/([migyu]{0,5})?$/,
7c7
< exact: /(^[\"\'=]+)|([\"\'=]+$)/g,
---
> exact: /(^["'=]+)|(["'=]+$)/g,
10,12c10,12
< wild01: /\?/g,
< wild0More: /\*/g,
< quote: /\"/g,
---
> wild01: /?/g,
> wild0More: /*/g,
> quote: /"/g,
14c14
< isNeg2: /(<=?\s*\d)/
---
> isNeg2: /(<=?\s*\d)//

looks like next.138 is getting escaped.

**Comment by nchanged** [comment]
Is it related to code generation then ? A ts but?

**Comment by nchanged** [comment]
@DaveO-Home could you compile a file sample that demonstrates the issue?

**Comment by DaveO-Home** [comment]
Using next.141 same results 
[fusebox.zip](https://github.com/fuse-box/fuse-box/files/3693595/fusebox.zip)

**Comment by nchanged** [comment]
@DaveO-Home would be nice to have the source ;-) this build won't' help much

**Comment by DaveO-Home** [comment]
@nchanged - the build was from; https://github.com/DaveO-Home/embedded-acceptance-tests-ng/tree/master/public/fusebox

**Comment by nchanged** [comment]
@DaveO-Home but that looks like v3?!

**Comment by nchanged** [comment]
@DaveO-Home If you try to execute this one:
```
const regex = /^/((?:\/|[^/])+)/([migyu]{0,5})?$/
```

In here https://meriyah.github.io/meriyah/

You will see that this regex is invalid

**Comment by DaveO-Home** [comment]
@nchanged  - is part of the package.json file - find fuse-box.... 
By default the app works with next.138 - to get the error - update fuse-box.

{
  "name": "embedded-acceptance-tests-ng",
 
  "license": "ISC",
  "sideEffects": true,
  "dependencies": {
    "@angular/animations": "^8.2.9",
    "@angular/common": "^8.2.9",
    "@angular/compiler": "^8.2.9",
    "@angular/compiler-cli": "^8.2.9",
    "@angular/core": "^8.2.9",
    "@angular/forms": "^8.2.9",
    "@angular/http": "^7.2.15",
    "@angular/platform-browser": "^8.2.9",
    "@angular/platform-browser-dynamic": "^8.2.9",
    "@angular/router": "^8.2.9",
    "babel-polyfill": "^6.26.0",
    "bootstrap": "^4.3.1",
    "browserlist": "^1.0.1",
    "dodex": "^1.3.0",
    "dodex-input": "^1.2.0",
    "dodex-mess": "^1.1.0",
    "font-awesome": "^4.7.0",
    "handlebars": "^4.4.2",
    "helpers": "0.0.6",
    "jquery": "^3.4.1",
    "lodash": "^4.17.15",
    "lodash-es": "^4.17.15",
    "marked": "^0.7.0",
    "moment": "^2.24.0",
    "pager": "^0.1.3",
    "pdfjs-dist": "^2.2.228",
    "popper.js": "^1.15.0",
    "redux": "^4.0.4",
    "rxjs": "^6.5.3",
    "rxjs-compat": "^6.5.3",
    "tablesorter": "^2.31.1"
  },
  "devDependencies": {
    "@ngtools/webpack": "^8.3.8",
    "@types/core-js": "^2.5.2",
    "@types/jasmine": "^3.4.2",
    "@types/jquery": "^3.3.31",
    "@types/lodash": "^4.14.141",
    "@types/node": "^12.7.11",
    "@types/webpack": "^4.39.2",
    "@typescript-eslint/eslint-plugin": "^2.3.2",
    "@typescript-eslint/parser": "^2.3.2",
    "auto-reload-brunch": "^2.7.1",
    "autoprefixer": "^9.6.1",
    "babel-brunch": "^7.0.1",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-loader": "^8.0.6",
    "babel-plugin-external-helpers": "^6.22.0",
    "babel-preset-angular2": "0.0.2",
    "babel-preset-env": "^1.7.0",
    "babel-preset-es2015": "^6.24.1",
    "browser-sync": "^2.26.7",
    "browserify": "^16.5.0",
    "browserify-css": "^0.15.0",
    "browserify-shim": "^3.8.14",
    "buffer": "^5.4.3",
    "clean-css-brunch": "^2.10.0",
    "copy": "^0.3.1",
    "copy-webpack-plugin": "^5.0.4",
    "copycat-brunch": "^1.1.1",
    "core-js": "^2.6.9",
    "css-loader": "^3.2.0",
    "cssify": "^1.0.3",
    "csslint": "^1.0.5",
    "de-indent": "^1.0.2",
    "del": "^4.1.1",
    "envify": "^4.1.0",
    "eslint-brunch": "^3.12.0",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.1",
    "events": "^3.0.0",
    "extract-text-webpack-plugin": "^3.0.2",
    "fancy-log": "^1.3.3",
    "file-loader": "^4.2.0",
    "fs": "0.0.1-security",
    "fuse-box": "^4.0.0-next.138",    <===================== look's like v4
    "google-closure-compiler": "^20190909.0.0",
    "gulp": "^4.0.2",
    "gulp-better-rollup": "^4.0.1",
    "gulp-bootlint": "^0.11.0",
    "gulp-copy": "^4.0.1",
    "gulp-csslint": "^1.0.1",
    "gulp-env": "^0.4.0",
    "gulp-eslint": "^6.0.0",
    "gulp-filelog": "^0.4.1",
    "gulp-flatten": "^0.4.0",
    "gulp-noop": "^1.0.0",
    "gulp-parcel": "^0.3.5",
    "gulp-remove-code": "^3.0.4",
    "gulp-rename": "^1.4.0",
    "gulp-run-command": "0.0.9",
    "gulp-sourcemaps": "^2.6.5",
    "gulp-strip-code": "^0.1.4",
    "gulp-typescript": "^5.0.1",
    "gulp-uglify": "^3.0.2",
    "gulp-uglify-es": "^1.0.4",
    "html-webpack-plugin": "^3.2.0",
    "jasmine-core": "^3.5.0",
    "jasmine-jquery": "^2.1.1",
    "jasmine-promise-wrapper": "0.0.3",
    "karma": "^4.3.0",
    "karma-browserify": "^6.1.0",
    "karma-brunch": "^1.0.6",
    "karma-chrome-launcher": "^3.1.0",
    "karma-commonjs": "^1.0.0",
    "karma-firefox-launcher": "^1.2.0",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-jquery": "^0.1.1",
    "karma-mocha-reporter": "^2.2.5",
    "karma-opera-launcher": "^1.0.0",
    "karma-steal-npm": "^0.1.5",
    "karma-story-reporter": "^0.3.1",
    "karma-typescript": "^4.1.1",
    "karma-typescript-angular2-transform": "^4.1.1",
    "karma-typescript-preprocessor": "^0.4.0",
    "loose-envify": "^1.4.0",
    "mini-css-extract-plugin": "^0.8.0",
    "node-sass": "^4.12.0",
    "optimize-css-assets-webpack-plugin": "^5.0.3",
    "parcel": "^1.12.3",
    "parcel-bundler": "^1.12.3",
    "parcel-plugin-strip": "file:parcel/appl/js/parcel-plugin-strip",
    "postcss-import": "^12.0.1",
    "postcss-url": "^8.0.0",
    "raw-loader": "^3.1.0",
    "resolve-url-loader": "^3.1.0",
    "rollup": "^1.23.0",
    "rollup-plugin-alias": "^1.5.2",
    "rollup-plugin-commonjs": "^9.3.4",
    "rollup-plugin-livereload": "^1.0.3",
    "rollup-plugin-node-resolve": "^4.2.4",
    "rollup-plugin-postcss": "^2.0.3",
    "rollup-plugin-progress": "^1.1.1",
    "rollup-plugin-replace": "^2.2.0",
    "rollup-plugin-serve": "^1.0.1",
    "sass-loader": "^8.0.0",
    "steal": "^2.2.3",
    "steal-css": "^1.3.2",
    "steal-tools": "^2.2.2",
    "steal-typescript": "^0.5.0",
    "stripcode-brunch": "file:brunch/appl/js/stripcode-brunch",
    "terser-brunch": "^3.0.0",
    "tsify": "^4.0.1",
    "tslib": "^1.10.0",
    "typescript": "^3.5.3",
    "typescript-brunch": "^2.3.0",
    "uglify-es": "^3.3.9",
    "uglify-js": "^3.6.0",
    "url-loader": "^2.2.0",
    "vinyl-buffer": "^1.0.1",
    "vinyl-source-stream": "^2.0.0",
    "watchify": "^3.11.1",
    "webpack": "^4.41.0",
    "webpack-dev-server": "^3.8.2",
    "webpack-merge": "^4.2.2",
    "webpack-stream": "^5.2.1",
    "webpack-strip-block": "^0.2.0",
    "zone.js": "^0.10.2"
  },
  }

**Comment by nchanged** [comment]
Yeah but the config looks like v3. Check out how it should look:

https://github.com/fuse-box/react-example/blob/master/fuse.ts

v4 is a brand new version

**Comment by nchanged** [comment]
Sorry for being stupid, I see the build file now. Anyway, could you give me the original regex from that lib

**Comment by DaveO-Home** [comment]
@nchanged - If you build the app with next.138 and then search for it in "vendor.js" you will get the original.

**Comment by DaveO-Home** [comment]
@nchanged - the expression....
regex: {
            regex     : /^\/((?:\\\/|[^\/])+)\/([migyu]{0,5})?$/, // regex to test for regex
            child     : /tablesorter-childRow/, // child row class name; this gets updated in the script
            filtered  : /filtered/, // filtered (hidden) row class name; updated in the script
            type      : /undefined|number/, // check type
            exact     : /(^[\"\'=]+)|([\"\'=]+$)/g, // exact match (allow '==')
            operators : /[<>=]/g, // replace operators
            query     : '(q|query)', // replace filter queries
            wild01    : /\?/g, // wild card match 0 or 1
            wild0More : /\*/g, // wild care match 0 or more
            quote     : /\"/g,
            isNeg1    : /(>=?\s*-\d)/,
            isNeg2    : /(<=?\s*\d)/
        },

**Comment by nchanged** [comment]
@DaveO-Home this expression is invalid
https://regex101.com/r/Cr8dAs/1

**Comment by DaveO-Home** [comment]
@nchanged - so why is it getting modified?

**Comment by nchanged** [comment]
@DaveO-Home I guess typescript is trying to "correct it" or the generator. But that's a javascript error with invalid syntax 100%

**Comment by DaveO-Home** [comment]
@nchanged - typescript is looking at vendor *.js files?

**Comment by nchanged** [comment]
ok what is the exact lib that has it? I will try bundling it jquery.tablesorter?

**Comment by DaveO-Home** [comment]
"tablesorter": "^2.31.1" - but in tablesorter/dist there are serveral flavors - use the *combined* flavor.

**Comment by nchanged** [comment]
@DaveO-Home I am off to bed now, but I will check it tomorrow. Are you on slack? https://slack.fuse-box.org/ it's probably easier to communicate there

**Comment by DaveO-Home** [comment]
Yes-I'll login tomorrow

**Comment by DaveO-Home** [comment]
@nchanged - Good news - tablesorter package main was pointing to the un-minimized src. I changed my import to the minimized version and it now works.  There is still the questions "why?".

**Comment by DaveO-Home** [comment]
@nchanged - This issue is resolved with next.142 using the default src.
FYI; I had code using the javascript string continuation \\, not exactly best practice.

```
footer: "<button class=\"btn btn-sm btn-primary submit-modal mr-auto raised submit-login\">{{submit}}</button> \
<button class=\"btn btn-sm close-modal raised\" data-dismiss=\"modal\" aria-hidden=\"true\">{{close}}</button>"
```
and meriyah failed with a unclosed string exception.  Changed to;
```
footer: `<button class=\"btn btn-sm btn-primary submit-modal mr-auto raised submit-login\">{{submit}}</button>
<button class=\"btn btn-sm close-modal raised\" data-dismiss=\"modal\" aria-hidden=\"true\">{{close}}</button>`
```
to get a compile.  Very difficult to figure out from the exception message.
