### ISSUE TITLE
Production vendor code duplicated

### ISSUE THREAD

**Issue by DaveO-Home** [fuse-box/fuse-box#1658]
Trying to implement canjs with v4.
This and other modules are duplicated in the production bundle;
'use strict';
var namespace = require('can-namespace');
var Globals = require('./can-globals-proto');
var globals = new Globals();

if (namespace.globals) {
    throw new Error("You can't have two versions of can-globals, check your dependencies");
} else {
    module.exports = namespace.globals = globals;
}

fuse-box bundle;
1:
// can-globals/can-globals-instance.js
$fsx.f[20] = (module, exports) => {
'use strict';
var namespace = $fsx.r(3);
var Globals = $fsx.r(19);
var globals = new Globals();
console.log("NAMESPACE*****************", namespace.globals, namespace);
if (namespace.globals) {
    throw new Error("You can't have two versions of can-globals, check your dependencies");
}
else {
    module.exports = namespace.globals = globals;
}

}

2:
// can-globals/can-globals-instance.js
$fsx.f[117] = (module, exports) => {
'use strict';
var namespace = $fsx.r(3);
var Globals = $fsx.r(19);
var globals = new Globals();

if (namespace.globals) {
    throw new Error("You can't have two versions of can-globals, check your dependencies");
}
else {
    module.exports = namespace.globals = globals;
}

}

App fails during second execution;  All other bundlers, webpack, browserify etc only have one copy in their bundles.

**Comment by nchanged** [comment]
Thanks for reporting that. I am re-writing the production logic. Could you reproduce this issue? I will check it later once it's done.

**Comment by DaveO-Home** [comment]
@nchanged - Requires the complete app to reproduce - I can check once you publish the new version.

**Comment by charsleysa** [comment]
@DaveO-Home can you please confirm if the issue still occurs with `fuse-box@4.0.0-next.400`?
Also see [here for info on major changes](https://github.com/fuse-box/fuse-box/blob/master/docs/changelog-fuse-compiler.md)

**Comment by DaveO-Home** [comment]
@charsleysa are there docs on custom plugins, in next.165 this worked `fuse-box/core/Context`. Can't test without the plugin.

**Comment by nchanged** [comment]
@DaveO-Home which plugin are you using?

**Comment by DaveO-Home** [comment]
@nchanged my own custom plugin - its strips development code.

**Comment by DaveO-Home** [comment]
@nchanged 
```import { Context } from "fuse-box/core/Context";
import { parsePluginOptions } from "fuse-box/plugins/pluginUtils";

export type IPluginStripProps = { [key: string]: any };
export function pluginStripCode(a?: IPluginStripProps | string | RegExp, b?: IPluginStripProps) {
  const [opts, matcher] = parsePluginOptions<IPluginStripProps>(a, b, {});

  return (ctx: Context) => {

    ctx.ict.on("assemble_fast_analysis", props => {
      if ((matcher && !matcher.test(props.module.props.absPath)) || 
        /node_modules/.test("can")) {
        return;
      }
      const { module } = props;

      ctx.log.info("pluginStripCode", "stripping code in $file \n", {
        file: module.props.fuseBoxPath,
      });

      const startComment =  opts.start || "develblock:start"; 
      const endComment =  opts.end || "develblock:end";
      const regexPattern = new RegExp("[\\t ]*(\\/\\* ?|\\/\\/[\\s]*\\![\\s]*)"
            + startComment + " ?[\\*\\/]?[\\s\\S]*?(\\/\\* ?|\\/\\/[\\s]*\\![\\s]*)"
            + endComment + " ?(\\*\\/)?[\\t ]*\\n?", "g");

      module.read();
      module.contents = module.contents.replace(regexPattern, "");
      return props;
    });
  };
}
```

**Comment by nchanged** [comment]
@DaveO-Home 

```ts
export function pluginStripCode(a?: IPluginStripProps | string | RegExp, b?: IPluginStripProps) {
  const [opts, matcher] = parsePluginOptions<IPluginStripProps>(a, b, {});

  return (ctx: Context) => {

    ctx.ict.on("module_init", props => {
    const { module } = props;
      if ((matcher && !matcher.test(module.absPath)) || 
        /node_modules/.test("can")) {
        return;
      }
      

      ctx.log.info("pluginStripCode", "stripping code in $file \n", {
        file: module.publicPath,
      });

      const startComment =  opts.start || "develblock:start"; 
      const endComment =  opts.end || "develblock:end";
      const regexPattern = new RegExp("[\\t ]*(\\/\\* ?|\\/\\/[\\s]*\\![\\s]*)"
            + startComment + " ?[\\*\\/]?[\\s\\S]*?(\\/\\* ?|\\/\\/[\\s]*\\![\\s]*)"
            + endComment + " ?(\\*\\/)?[\\t ]*\\n?", "g");

      module.read();
      module.contents = module.contents.replace(regexPattern, "");
      
    });
  };
}
```

**Comment by DaveO-Home** [comment]
@nchanged - the problem is here `return (ctx: Context) => {`  how does Context get resolved?  It seems that the new config doesn't recognize { plugins:[] }.  import { Context } from "fuse-box/core/Context"; is no longer getting resolved.

**Comment by nchanged** [comment]
@DaveO-Home 
```
 import { Context } from "fuse-box/core/context";
```

**Comment by DaveO-Home** [comment]
@nchanged  Production now works; just have to get font-awesome working....

**Comment by nchanged** [comment]
@DaveO-Home you should try the following btw:

```
if( process.env.NODE_ENV === "development" ) {

} else {

}
```

It computes it during the runtime for dev and prod and unwraps the statements
