### ISSUE TITLE
v4: create some sensible module resolution fallbacks

### ISSUE THREAD

**Issue by martaver** [fuse-box/fuse-box#1659]
In cases where a package's `package.json` has errors, fuse-box will (correctly) fail at resolving those modules. Example is using ´formik-wizard´- it's package.json references dist files that don't exist, however ìndex.js` specifies the correct configuration.

Ordinarily, it would be sufficient to hail down curses upon the author of the library, however our arch nemesis `webpack` handles this situation fine. Reason being, it has some sensible fallbacks for module resolution.

Fuse-box should do the same, probably where if the cjs/esm modules specified in the `package.json` don't exist, then it starts searching for alternatives, such as ìndex.js`, or similar files with/without a `.min.js` extension.

**Comment by charsleysa** [comment]
Closed due to inactivity.
