### ISSUE TITLE
Browser gets "update-bundle-errors" on HMR

### ISSUE THREAD

**Issue by cscalfani** [fuse-box/fuse-box#1660]
I'm doing the following in `fuse.js`:

```js
fuse
 .bundle(bundle)
 .instructions(instructions)
 .hmr({reload : true})
  .watch("build/**");
```

The `watch` is working and rebundles whenever I change something in the `build` directory.

The page in the browser is NOT reloaded. When I inspect the Websocket Messages in Chrome, I get every time it's rebundled:

```
{"type":"update-bundle-errors","data":{"bundleName":"index","messages":[]}}
```

The webpage is NOT reloaded.

The same behavior is exhibited when `hmr` doesn't have the `reload` option.

I'm using version 3.7.0.

**Comment by patrickmichalina** [comment]
Have you tried version 4?

I don’t think anyone will be working on v3 related fixes anytime soon.

**Comment by nchanged** [comment]
@cscalfani yes, please migrate to `fuse-box@next` and join [slack](http://slack.fuse-box.org) for updates. There is something big coming very soon.

**Comment by paxperscientiam** [comment]
@nchanged Is the slack working? i'm getting error 502 bad gateway

**Comment by nchanged** [comment]
@paxperscientiam should be up now!

**Comment by charsleysa** [comment]
Closing as related to v3.x which is no longer supported.
