### ISSUE TITLE
Tree shaking marks for removal tsx file names with dots

### ISSUE THREAD

**Issue by joseluisq** [fuse-box/fuse-box#1661]
I'm using Preact v10.0.1 with FuseBox v3.7.1. When I use for example component file names with dots the Tree shaking feature marks it for removal and then I got `Uncaught TypeError: Cannot read property 'SchedulerBodyComponent' of undefined`. 
But when I change the name to, for example using dashes instead, everything is fine. Details below.

__Dependencies:__

- Preact: v10.0.1
- FuseBox v3.7.1
- Typescript: v3.6.4
- NodeJS: v12.12.0

__Using a name with dot:__ `scheduler.body.tsx` (cause the error)

Fusebox output:

```sh
  → tree shaking: Mark for removal default/components/calendar-day/scheduler.body.jsx
  → tree shaking: Mark for removal process/index.js
  → tree shaking: Mark for removal fuse-box-css/index.js
  → tree shaking: Mark for removal preact/dist/preact.js
.....
```

![image](https://user-images.githubusercontent.com/1700322/67151941-19b52f00-f2ce-11e9-9501-658c67c0a5d4.png)

__Using a name with dash:__ `scheduler-body.tsx` (ok)

Fusebox output:

```sh
  → tree shaking: Remove SchedulerRowComponent from default/components/calendar-day/scheduler-body.jsx
  → tree shaking: Mark for removal process/index.js
  → tree shaking: Mark for removal fuse-box-css/index.js
  → tree shaking: Mark for removal preact/dist/preact.js
......
```

**Comment by nchanged** [comment]
@joseluisq thanks for reporting this!

v3 is no longer maintained, and we are working hard on v4 which features massive improvements over the current version. Join our [slack](http://slack.fuse-box.org) channel for updates!

Here are the [docs](https://github.com/fuse-box/fuse-box/tree/master/docs) for `v4`

**Comment by joseluisq** [comment]
Ok, I think this issue it should keep open until v4.
I'm stay tuned anyway.

**Comment by charsleysa** [comment]
Closing as related to v3.x which is no longer supported.
