### ISSUE TITLE
V4 ,,dynamic" imports using pluginReplace not working

### ISSUE THREAD

**Issue by bogdandv** [fuse-box/fuse-box#1662]
I need to import all files in a folder in a v4 production build.
The equivalent of `FuseBox.import("~/features/**");`

if I import manually my file:
`import "path_to_file/fileName";`
All works well

If in my App.tsx file I have:
`//LIST_OF_IMPORTS`
and I add in fuse.ts
``
plugins: [pluginReplace("App.tsx", { "//LIST_Of_IMPORTS": `import "path_to_file/fileName"`})]
``

I get an error message: 

` Problem when resolving require "./features/Layouts/2ColLayout/index" in default/App.jsx`
Doesn't pluginReplace replace the text before it is processed?
Why is the resulting code different?

**Comment by nchanged** [comment]
@bogdandv actually, it should happen before transpiling. Check the output. It should work

**Comment by bogdandv** [comment]
This gets generated:

`require("./features/Layouts/2ColLayout/index");`

code that throws `App.tsx:14 Uncaught ReferenceError: require is not defined`

**Comment by nchanged** [comment]
That this file cannot be resolved. Is it during production?

**Comment by bogdandv** [comment]
Yes, during production

**Comment by nchanged** [comment]
@bogdandv that is a bug yes. However, you might want to use `dependencies` field as described [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md#dependencies)

**Comment by charsleysa** [comment]
@bogdandv can you please confirm if the issue still occurs with `fuse-box@4.0.0-next.400`?
Also see [here for info on major changes](https://github.com/fuse-box/fuse-box/blob/master/docs/changelog-fuse-compiler.md)

**Comment by charsleysa** [comment]
Closed as no response received.
