### ISSUE TITLE
Fusebox setup

### ISSUE THREAD

**Issue by bogdandv** [fuse-box/fuse-box#1665]
How do you configure FuseBox 4.0 to compile from typescript to ECMA 5 javascript **production** code? 
Changing target to "browser@es5" generates a code that throws `$fsx is not defined` and `process is not defined` (same as in 3.7.1)

(Side question: How do you configure the Css generated from Less to be stored in a file?)

Current SetUp:
```
class Context {
    runServer;
    getConfig = (useSourceMap) =>
        fusebox({
            target: "browser",
            homeDir: "homeDir",
            entry: "entry.tsx",
            output: 'outputFolder/$name',
            webIndex: {
                target: "WebIndexTargetFolder/index.html"
            },
            tsConfig: 'tsconfig.json',
            cache: true,
            devServer: this.runServer,
            useTypescriptCompiler: true,
            sourceMap: useSourceMap
        });
}
const { task } = sparky<Context>(Context);
task("buildProduction", async ctx => {
    ctx.runServer = false;
    const fuse = ctx.getConfig(true);
    await fuse.runProd({
        uglify: false,
        // target: 'ES5'
    });
});
```

**Comment by nchanged** [comment]
@bogdandv set `es5` target in your `tsconfig.json` 
Don't modify the browser target.

CSS is automatically generated when doing production builds

**Comment by bogdandv** [comment]
This is my tsconfig.json:
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "checkJs": true,
    "allowJs": true,
    "jsx": "react",
    "module": "ES2015",
    "strictNullChecks": true,
    "moduleResolution": "node",
    "noImplicitAny": false,
    "plugins": [
      { "name": "tslint-language-service" }
    ],
    "skipDefaultLibCheck": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true,
    "target": "ES5",
    "experimentalDecorators": true,
    "downlevelIteration": true
  },
  "typeAcquisition": {
    "exclude": [ "node" ],
    "enable": false
  },
  "exclude": [
    "fuse.ts"
  ]
}

```

**Comment by bogdandv** [comment]
So is there any other way to bundle to es5 in v4 other than changing the target?

**Comment by nchanged** [comment]
I just remember there is a flag on runProd screwIE ) try it, it that won't help I will check it

**Comment by Marcisbee** [comment]
I'm facing the same issue. Bundle is created with arrow functions with `screwIE` true and with false too.

![image](https://user-images.githubusercontent.com/16621507/67510785-46868f00-f69e-11e9-88e7-1af53a2a4265.png)

**Comment by nchanged** [comment]
I have just checked it:
```
// default/src/index.jsx
$fsx.f[10] = function(module, exports){
```

```
await fuse.runProd({
    uglify: false,
    screwIE: false,
    cleanCSS: {
      compatibility: {
        properties: { urlQuotes: true },
      },
    },
  });
```
Works just fine

**Comment by Marcisbee** [comment]
Sorry I got a brainfart. That solved it yeah.

**Comment by nchanged** [comment]
Perfect, so we're done here then ;-)

**Comment by Marcisbee** [comment]
But I see another issue: https://github.com/fuse-box/fuse-box/blob/a1eb8e8ab132cf139daee3b29926a3c2ec049550/src/production/api/production.api.js#L56

Here arrow function is used and it breaks on IE.

**Comment by Marcisbee** [comment]
Awesome! Thanks!

**Comment by bogdandv** [comment]
ScrewIE set to false solves my problem as well. 
Thank you!

**Comment by paxperscientiam** [comment]
@nchanged , so this is still a bug, is it not? fuse-box does not seem to be honoring the target setting in tsconfig.json.compilerOptions nor the `conf.target` setting for `.runProd(conf)`. Targeting ES3, for instance, should produce a result without arrow functions.

Setting screwIE to false does lead to result without arrow functions ... but why should setting screwIE to true override the target setting?

**Comment by nchanged** [comment]
Target is respected during the production build, set in your tsconfig it should work

**Comment by paxperscientiam** [comment]
Not my experience. Here's a minimum:

fuse.ts
```typescript
import { fusebox } from 'fuse-box';
fusebox({
  entry: 'src/test.ts',
  target: 'web-worker',
  useSingleBundle: true,
  output: "dist",
  codeSplitting: {
    useHash: false,
  },
  webIndex: false,
  devServer: false,
  watch: {
    ignored: [/flycheck/i],
  },
}).runProd({
  target: 'ES3',
  screwIE: true,
  uglify: false,
})
```
test.ts
```typescript
const x = () => {
  return 33
}
```

**Comment by nchanged** [comment]
You should set the target in `tsconfig.json` It might be misleading, but we will fix it
