### ISSUE TITLE
How do you stop fuse-box v4 from bundleling resources

### ISSUE THREAD

**Issue by bogdandv** [fuse-box/fuse-box#1670]
My project has .less files. In order to make the code more repeatable and to keep with DRY, we wrote in less code like `url("@{image}")`.
When bundleling, these instances give `Failed to resolve @{image} in C:\file\path\:123:45` warnings.

The result is a bundle that uses some images from the generated resources bundle, and some images from the original image folder.

How do you stop resources from bundleling?

**Comment by nchanged** [comment]
I guess a better question is, how to stop v4 from complaining about it. I know how to fix it

**Comment by bogdandv** [comment]
Other info about my dilema:
I am passing in some cases to
Variables:
```
.background(@image)
{ 
     background-image: url("@{image}");
}
```
Widget style:
```
.className1 {
    .background("../../../sources/images/testImage");
}
```
and in some cases 
```
.className2 {
    background-image:  url("../../../sources/images/testImage")
}
```
In the final bundle, in production, Elements with the class "className2" will download their image from `/dist/resources/images/213hber12347.png`, while elements with "className1" will download their images from `sources/images/testImage.png`.

I am trying to avoid this behaviour either by bundleling all images or none of the images.
How can I solve this problem either way?

**Comment by nchanged** [comment]
@bogdandv CSS URL resolver handles `url()` only. But we can make an optional flag to resolve other attributes. What I am not understanding is why wouldn't you reference `url` directly, instead of proxy. If you need to tweak the paths, you can use macros
https://github.com/fuse-box/fuse-box/blob/master/docs/stylesheet.md#using-macros

But you should use something else `$` sign, since that's a variable in many languages.

**Comment by bogdandv** [comment]
We are not referencing the url directly to not repeat code. The example I gave was basic, in most cases each` .background` class has more "arguments" (variables) and more css attribute. Also we have more than one class with url proxy arguments.

In fuse v3.7 the less code compiled correctly, and no resource bundleling was used, all url were given compared to the server root. Now url are given compared to the file location, and they look for the given resource to bundle it (making migration harder).

**Comment by nchanged** [comment]
@bogdandv it wasn't working correctly in v3. It's looking for resources relative to the actual file. Of course, how else would you expect it to work?

**Comment by bogdandv** [comment]
I expected it to just give a link and then put the server url to that link. I wish to do something simple and easy to read: give the path to where the resource will be on the server, not where it is now on the file system

**Comment by nchanged** [comment]
Ok, Do you want to have a flag that would prevent resources from being resolved? We can have it. But In this case, you won't be able to mix those. 

Another option if to keep as is, and don't spit warnings if the resource hasn't been located

**Comment by bogdandv** [comment]
a flag that would prevent resources from being resolved would be usefull

**Comment by charsleysa** [comment]
@bogdandv can you please confirm if the issue still occurs with `fuse-box@4.0.0-next.400`?
Also see [here for info on major changes](https://github.com/fuse-box/fuse-box/blob/master/docs/changelog-fuse-compiler.md)

**Comment by charsleysa** [comment]
Closed as no response received.
