### ISSUE TITLE
HMR not working

### ISSUE THREAD

**Issue by amygdaloideum** [fuse-box/fuse-box#1673]
At my job, I have several project using the same basic structure, and HMR on the dev server is not working for any of them. I have read the documentation in detail but after several hours of scratching my head I have not yet found the problem.

This is my dev server:

```
const { FuseBox } = require('fuse-box');
const proxyServer = require('./proxy');
const getPlugins = require('./resources/fusebox-config/plugins');
const aliases = require('./resources/fusebox-config/aliases');
require('dotenv').config();

const config = {
  tsConfig: "./resources/fusebox-config/compiler-options.json",
  homeDir: '../src',
  output: '../dist/$name.js',
  sourceMaps: true,
  target: 'browser@es5',
  useTypescriptCompiler: true,
  allowSyntheticDefaultImports: true,
  log: {
    showBundledFiles: false, // Don't list all the bundled files every time we bundle
    clearTerminalOnBundle: true, // Clear the terminal window every time we bundle
  },
  alias: aliases,
  plugins: getPlugins('dev'),
};

const fuse = FuseBox.init(config);
fuse.dev({ port: 4001, root: false }, server => proxyServer(server.httpServer.app));
fuse
  .bundle('app')
  .instructions('> index.jsx')
  .hmr();
fuse.run();
```

Currently I have to add `.watch()` to the chain in order to get the page to reload on each file change. With the above configuration, nothing happens when I save, I see nothing in the logs.

I've seen this message [in the docs](https://fuse-box.org/docs/development/development-server#setup): `To avoid problems with HMR settings (below) set your development server config before you define further bundle configuration`. But I'm not sure what it means or if its related to my problem.

If you need additional information please tell me and I will be happy to comply.

**Comment by nchanged** [comment]
hey @amygdaloideum v3 is out scope now. We're focusing on v4. 
Here is a valid react example 
https://github.com/fuse-box/react-example/blob/master/fuse.ts

Using `fuse-box@next` Here are the [docs](https://github.com/fuse-box/fuse-box/tree/master/docs) 

If you have problems migrating join us on slack. We can help you ;-)
https://slack.fuse-box.org/

**Comment by nchanged** [comment]
Closing this for now. Re-open if still relevant
