### ISSUE TITLE
namespace and class with same name breaks output

### ISSUE THREAD

**Issue by jpike88** [fuse-box/fuse-box#1675]
```
export class Image
{
    constructor ()
    {
        this.state = Image.State.Idle;
    }

    state: Image.State;
}

export namespace Image
{
    export enum State
    {
        Idle,
        Loading,
        Ready,
        Error
    }
}
```

**Comment by nchanged** [comment]
@jpike88 
http://www.typescriptlang.org/play/?experimentalDecorators=true&emitDecoratorMetadata=true&ssl=9&ssc=2&pln=1&pc=1#code/KYDwDg9gTgLgBAYwDYEMDOa4EkC2KDmwAUAN5FwWIQB2aMUArgjNHABQCU5lZlfcMABYBLNADo6KGMDgBebHkJiAyjCnAxWACZJgAbm4UAvkUNxJ0gFwKCG1eoMmioSLDjUUOYGjAoEM3FtSMxdoeGBqBhw4e2kzXn4KbV0AGjM+ABkIFC1hanw0xIoAJWAcgE9CooBRKChoMxMjIA

Typescript, for example, doesn't export the namespace in case of the scope collision. Why do you have in the first place?

**Comment by jpike88** [comment]
I'm a dumbass I didn't closely check the example


```
export class Image
{
    wat: number;
}

export namespace Image
{
    export enum State
    {
        Idle,
        Loading,
        Ready,
        Error
    }
}
```

Even without the collision it doesn't work

**Comment by nchanged** [comment]
It's the same, you export the same name twice

**Comment by jpike88** [comment]
Huh it used to work though with next

**Comment by nchanged** [comment]
@jpike88 I will check it. I probably need to ignore `export` from `namespace` since it won't be exported. And man, don't use namespace ;-) You're making it 2x slower

**Comment by jpike88** [comment]
yeah ill try to move to modules... but this works in vanilla typescript and worked in fusebox next

**Comment by charsleysa** [comment]
@jpike88 can you please confirm if the issue still occurs with `fuse-box@4.0.0-next.400`?
Also see [here for info on major changes](https://github.com/fuse-box/fuse-box/blob/master/docs/changelog-fuse-compiler.md)

**Comment by charsleysa** [comment]
Closed as no response received.
