### ISSUE TITLE
potential file name issue in output

### ISSUE THREAD

**Issue by jpike88** [fuse-box/fuse-box#1676]
```21fe3766_dev.js:189 Uncaught Package not found @client/app.module```

filename of import is ```app.module.ts```

original code:
```import '@client/app.module';```

**Comment by nchanged** [comment]
That happens when your server is running and you hit save in alpha, right? 
That's a know issue, it doesn't change the paths

**Comment by jpike88** [comment]
this issue occurs on load of the page without any changes.

its as if the @client alias is being used to look in the external node packages folder

I have a few aliases that use the @ symbol prefix

<img width="1120" alt="Screen Shot 2019-11-02 at 10 30 09 AM" src="https://user-images.githubusercontent.com/9585787/68065573-d80c9580-fd5d-11e9-8653-6d325bb26525.png">

**Comment by nchanged** [comment]
Can u repro it ?

**Comment by jpike88** [comment]
I found the culprit:

```
import { AppModule } from '@client/app.module';
import '@client/app.module';
```

Sure, not ideal, but the behaviour is still incorrect

**Comment by jpike88** [comment]
Maybe an error saying an import has been done twice in the same file... I'm surprised typescript/tslint hasn't complained

**Comment by charsleysa** [comment]
@jpike88 can you please confirm if the issue still occurs with `fuse-box@4.0.0-next.400`?
Also see [here for info on major changes](https://github.com/fuse-box/fuse-box/blob/master/docs/changelog-fuse-compiler.md)

**Comment by nchanged** [comment]
this one is fixed ;-) closing it
