### ISSUE TITLE
@ng-select/ng-select package causing issue on alpha

### ISSUE THREAD

**Issue by jpike88** [fuse-box/fuse-box#1678]
try this code:

```

import { NgSelectModule } from '@ng-select/ng-select';

const x = NgSelectModule; // force it to be run

console.log('wat')
```

![Screen Shot 2019-11-04 at 11 20 42 am](https://user-images.githubusercontent.com/9585787/68099439-2607d180-fef5-11e9-90ea-75a73147cc72.png)

Buffer is being imported and pooping in the output

**Comment by nchanged** [comment]
fixed in `alpha.246`
