### ISSUE TITLE
Package not picked from a correct location

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#1680]
Hi, I have a monorepo and I followed your instructions in the docs, setting my base dir to '../../'. This is my config:

```
const { fusebox } = require('fuse-box');

const fuse = fusebox({
  target: 'browser@es5',
  entry: 'app/client/src/index.tsx',
  homeDir: '../../',
  devServer: true,
  webIndex: {
    template: 'src/index.html'
  }
});

fuse.runDev();
```

The issue is that I have multiple version of the `date-fns` package. In the "client" directory there is node_module/date_fns with version 2.x. Yet, in the root directory there is a version "1.x". Unfortunately, fuse-box is picking up the "1.x" version and crashes on start as it is searching for non-existing files.

**Comment by nchanged** [comment]
@tomitrescak You have an invalid target there. I believe it will work right after you've fixed it.
`target: 'browser`

**Comment by nchanged** [comment]
And In regards to your local modules
I believe the code below will help, it will lookup first in the folders you've defined
```ts
fusebox({
  module : ["./node_modules"]
})
```

**Comment by tomitrescak** [comment]
Thanks! That did the trick.
