### ISSUE TITLE
V4 bundle and runtime errors appears.

### ISSUE THREAD

**Issue by MrFoxPro** [fuse-box/fuse-box#1681]
After switching to V4, I got these errors
from dependencies:
![image](https://user-images.githubusercontent.com/17229619/68488017-fd216c80-0265-11ea-9435-c5680b316429.png)
Could somebody suggest, why this errors happening and which plugins should I use? 
Code in dom-helpers library, **off.js**
```
"use strict";

var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");

exports.__esModule = true;
exports.default = void 0;

var _inDOM = _interopRequireDefault(require("../util/inDOM"));

var off = function off() {};

if (_inDOM.default) {
  off = function () {
    if (document.addEventListener) return function (node, eventName, handler, capture) {
      return node.removeEventListener(eventName, handler, capture || false);
    };else if (document.attachEvent) return function (node, eventName, handler) {
      return node.detachEvent('on' + eventName, handler);
    };
  }();
}

var _default = off;
exports.default = _default;
module.exports = exports["default"];
```
**react-transition-group\CSSTransition** contains only package.json file
```
{
  "name": "react-transition-group/CSSTransition",
  "private": true,
  "main": "../cjs/CSSTransition.js",
  "module": "../esm/CSSTransition.js"
}
```

in my code with "react-redux":
![image](https://user-images.githubusercontent.com/17229619/68488057-13c7c380-0266-11ea-8e70-24973f343ad7.png)

my **fuse.ts** config
```
import { fusebox, pluginCSS, pluginJSON, pluginLink } from 'fuse-box';

const fuse = fusebox({
  target: 'browser',
  homeDir: "./src",
  entry: 'index.tsx',
  modules: ["./node_modules"],
  devServer: true,
  tsConfig: "./tsconfig.json",

  // sourceMap: {
  //   project: true,
  //   vendor: true
  // },
  allowSyntheticDefaultImports: true,
  output: "dist/$name",
  json: {
    useDefault: true
  },
  webIndex: {
    template: 'src/index.html'
  },
  dependencies: {
    include: ['tslib'],
    ignoreAllExternal: false
  },
  plugins: [pluginCSS(), pluginJSON()],
  cache: false,
});

fuse.runDev();
```
Same project works with V3, similiar settings
Thank you in advance.

**Comment by nchanged** [comment]
@MrFoxPro I think you might need to reproduce it. Why do you have `modules : ["./node_modules"]` it should be picking up automatically, unless you're in a deep forest of monorepos. There might be a bug with merging modules. Try removing it

**Comment by charsleysa** [comment]
@MrFoxPro can you please confirm if the issue still occurs with `fuse-box@4.0.0-next.400`?
Also see [here for info on major changes](https://github.com/fuse-box/fuse-box/blob/master/docs/changelog-fuse-compiler.md)

**Comment by charsleysa** [comment]
Closed as no response received.
