### ISSUE TITLE
multiple bundlers with fuse-box v4 / electron 

### ISSUE THREAD

**Issue by jounii** [fuse-box/fuse-box#1683]
This is support request.

With lack of documentation and help of source code/ type-defs, I refactored my fuse.ts 3.7 -> 4. Using fuse-box to bundle and run electron app. 

I got more or less the two bundle bundling to work (I think) but stuck a bit how to get correct output. I can't say the new v4 way is better or worse, just different, however setup with Electron is expecting now out/main.js as the entrypoint (from package.json) but fuse-box is spitting out all sort of files. Not sure how to set it back how it used to output.

Also could not find any help how to setup CopyPlugin properly. I understand much of is done now automatically, right now it's used to root all assets to 'assets/'

Primary reason for trying the v4 was that the 3.7.1 is no fully compatible with typescript 3.7. Going back to fuse-box 3.7.1 now and using setting "skipLibCheck": true in tsconfig.json solves the problem quickly, but not ideal solution.

**Comment by nchanged** [comment]
CopyPlugin is removed cuz it's not needed any more, check pluginLink, also useSingleBundle option will get a single bundle for you

**Comment by charsleysa** [comment]
@jounii can you please confirm if the issue still occurs with `fuse-box@4.0.0-next.400`?
Also see [here for info on major changes](https://github.com/fuse-box/fuse-box/blob/master/docs/changelog-fuse-compiler.md)

**Comment by nchanged** [comment]
The latest next version supports custom output. Closing this one.
