### ISSUE TITLE
VueComponentPlugin support Functional Vue component

### ISSUE THREAD

**Issue by TrungRueta** [fuse-box/fuse-box#1685]
hi!
I working in big project with 300+ vue components and i start switch from webpack to fusebox because webpack compile so slow. I love fusebox a lot but a big problem when deal with vue framework is VueComponentPlugin missing support Functional component. 

Detail about how Vue-loader support it from here:
[Vue loader functional support](https://vue-loader.vuejs.org/guide/functional.html)

Hope we have same feature soon.
Trung

**Comment by charsleysa** [comment]
@TrungRueta can you please confirm if the issue still occurs with `fuse-box@4.0.0-next.400`?
Also see [here for info on major changes](https://github.com/fuse-box/fuse-box/blob/master/docs/changelog-fuse-compiler.md)

**Comment by charsleysa** [comment]
Closed as no response received.
