### ISSUE TITLE
v4 - source-maps break after reload

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#1688]
Hi, am on v4 - 151.
The hot reload correctly loads new file and shows it in the "resources" in dev tools.
But, when I manually reload page, it loads the old file. As a result, debugging is a bit problematic.
When I change file, I have to kill the dev server and run it again.

Repro:
1. Create typescript file
2. Load it in the broser
3. Add `debugger` line
4. after hot reload correcty displays the  line with `debugger`
5. manual reload and the debugger line is no longer present

Is this something that is known?

**Comment by nchanged** [comment]
I think it's related to FTL, set cache {FTL:false} that should help, I will take a look

**Comment by tomitrescak** [comment]
@nchanged, I'll give it a go ... but not sure where to set this.

**Comment by nchanged** [comment]
I told you, cache : { FTL : false }

**Comment by charsleysa** [comment]
@tomitrescak can you please confirm if the issue still occurs with `fuse-box@4.0.0-next.400`?
Also see [here for info on major changes](https://github.com/fuse-box/fuse-box/blob/master/docs/changelog-fuse-compiler.md)

**Comment by nchanged** [comment]
This has been fixed. We can close it.
