### ISSUE TITLE
V4 - incorrectly generates imports

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#1689]
V4 has problems when esModuleInterop is set in the tsconfig.json
Try to use package evergreen-ui, for example render a Popover component. 
All default imports will be empty. CRA works.
I have not tried to disable esModuleInterop but I know that previously in V3 it helped. If you need I’ll prepare repro.

**Comment by nchanged** [comment]
Can you not use it ? allowSynteticDefaultImports should work just fine

**Comment by tomitrescak** [comment]
I'd have to convert all my imports to the `*` notation, e.g. `import React from 'react'` to `import * as React from 'react'`. Doable but less sustainable. What talks in your favor is that youare supporting idiomatic React, not the commonjs legacy crap.

**Comment by nchanged** [comment]
No you don't need to convert anything, fuse polyfils that automatically, not ts

**Comment by nchanged** [comment]
@tomitrescak Ok, to clarify. `allowSynteticDefaultImports` tells typescript to not complain about the imports however it doesn't polyfill it. But FuseBox picks that on up and polyfills by itself without ts knowing about it. Long story short, don't set `esModuleInterop` as it breaks the logic set by FuseBox

**Comment by tomitrescak** [comment]
@nchanged, still no luck .... ;( those defualt imports remain empty.

**Comment by nchanged** [comment]
@tomitrescak can't be. It's been working like this since v3. Clear the cache

**Comment by tomitrescak** [comment]
Yah, sorry. It is happening:

![image](https://user-images.githubusercontent.com/2682705/69404135-95345100-0d50-11ea-87c5-a843f0972d16.png)

And debug info:

![image](https://user-images.githubusercontent.com/2682705/69404162-ad0bd500-0d50-11ea-8ac4-1e42b8706c35.png)

the __req7__.default import is undefined ;(

**Comment by tomitrescak** [comment]
Weirdly the `__req7__` is actually `true`.

This is my tsconfig.json

```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react",
    "baseUrl": "src",
    "plugins": [
      {
        "name": "typescript-styled-plugin",
        "lint": {
          "validProperties": ["label"]
        }
      }
    ]
  },
  "include": ["src"]
}

```

**Comment by tomitrescak** [comment]
Ok, got the repro for you:

https://github.com/tomitrescak/react-example

Just click on the "Show" Button, the popover does not appear.
To see the messed up import put the breakpoint onto line: `30099` in the generated vendor file, click on "Show" button and see that the import `__req7__` is just `true` and not an object.

**Comment by tomitrescak** [comment]
This definitely looks like a bug since you are removing `_interopRequireDefault` from the original code and replacing it with your own `require`.

You resolve `const __req7__ = require("dom-helpers/util/inDOM");` to `true`, which is somehow correct as it IS the default import, yet you forget yo replace the `_inDOM.default` in the same code, thus `true.default` is evaluated to `false`.

**Comment by nchanged** [comment]
Hey, do you  think you could fix that object instead? `syntheticDefaultExportPolyfill`

**Comment by tomitrescak** [comment]
Hello, no, this is coming from external library: `require("dom-helpers/util/inDOM")` whic hby default returns `true` or `false`. Also, it is external library calling this.

**Comment by tomitrescak** [comment]
Ah, I think I know what you mean. Unfortunately, the fix can't be applied in `syntheticDefaultExportPolyfill` since it is already boolean value passed into it. You cannot properties to atomic types.

**Comment by tomitrescak** [comment]
Hello, any luck with merging this? You reckon it will make the merge?

**Comment by nchanged** [comment]
It has been fixed properly in alpha, so the build is coming this week

**Comment by tomitrescak** [comment]
K, thanks! Closing then.
