### ISSUE TITLE
"Smarter" suggestions when plugin dependency is missing

### ISSUE THREAD

**Issue by paxperscientiam** [fuse-box/fuse-box#1690]
This is an easy one for anyone else who wants to pick it up, but I'm happy to also.

Looking at the sass plugin, i saw this error message that is given when node-sass is not installed in the project:
```
'Module "sass" is required, Please install it using the following command',
          'npm install node-sass --save-dev',
```
Would be neat if, as part of environment detection, the likely package manager could be identitfied.

presence of .yarnrc => yarn
presence of pnpm-lock.yaml => pnpm
presence of package-lock.json => npm
We could then set some variable PKG_MANAGER accordingly.

So. `'npm install node-sass --save-dev'` becomes ``${PKG_MANAGER} install node-sass --save-dev``

**Comment by nchanged** [comment]
@paxperscientiam sounds like a great idea, however not the biggest priority ATM. Do you want to take a look and make a PR?

**Comment by paxperscientiam** [comment]
@nchanged yes!

**Comment by charsleysa** [comment]
Closed due to inactivity.
