### ISSUE TITLE
Feat request:  monoRepoHomeDir config item

### ISSUE THREAD

**Issue by SephReed** [fuse-box/fuse-box#1692]
I've set up a mono repo a few times with fuse-box, but it's always kind of difficult.

How difficult would it be to create a `monoRepoHomeDir` config item which makes it possible to reach out of the project without having to update any of the other paths?

For instance, I have project with a lot of imports like this:
```
import {thing} from "Components/some-thing";
```

When I change homeDir, all of these have to be updated too.  If I could just supply a `monoRepoHomeDir` and maybe do imports from that with a `@monoRoot/OtherPackageINeeded` that would make for a much smoother stage in project scaling.

**Comment by nchanged** [comment]
@SephReed I believe all that can be achieved by tweaking `tsconfig.json` and paths. I don't think you need to change your code base...

**Comment by SephReed** [comment]
tsconfig works for interfaces and type definitions, but any functions or values I pull from above the project homeDir come up undefined.  If I change the homeDir, I have to update every non relative url in the codebase.

**Comment by nchanged** [comment]
@SephReed that's not correct. You use `baseUrl` and `paths`
Read more [here](https://github.com/fuse-box/fuse-box/blob/master/docs/monorepo.md#configuring-paths) for example. It's really a powerful mechanism to arrange your paths.

**Comment by SephReed** [comment]
Oh, wow!  I had not realized that tsconfig was used by fuse-box as configuration.  Really neat feature.
