### ISSUE TITLE
Babel7Plugin config file catch-22

### ISSUE THREAD

**Issue by mweiczorek** [fuse-box/fuse-box#1693]
FuseBox version  3.7.1 (npm latest version)

I'm using Fuse with a Typescript/Electron application. Since electron uses (packages) an older version of node, I need to run babel on a few external libraries in the node_modules directory.

I have a `babel.config.js` file used as configuration in the project root.

```
  homeDir: __dirname,
  plugins: [
    Babel7Plugin({
      configFile: 'babel.config.js'
    })
  ]
```

When I try and run, I get this error:
```
Error: .filenameRelative is only allowed in root programmatic options
    at /home/user/project/node_modules/@babel/core/lib/config/validation/options.js:95:13
```
If I include the entire directory:
```
  homeDir: __dirname,
  plugins: [
    Babel7Plugin({
      configFile: path.resolve(__dirname, 'babel.config.js')
    })
  ]
```

It can't find the config file because it treats the absolute path as relative:
```
Error: Babel7Plugin - configuration file not found on path /home/user/project/home/user/project/babel.config.js
```

So.... if I use the relative path, babel chokes. If I use the absolute path, fuse chokes. What's the problem here?

**Comment by SephReed** [comment]
Is babel choking after the bundle completes?

If so, you can perhaps use the replacePlugin to find the path it's choking on, and update it to a path that works.

**Comment by mweiczorek** [comment]
No, babel never runs as far as I know. I have, however, upgraded the Electron version since (that can deal with ES7+), so my need for this is now moot. I do have the older, un-updated project on another computer that I can use if you're still interested in fixing this issue.

**Comment by SephReed** [comment]
I'm just getting acquainted with the codebase (ie, I couldn't do the fix yet).  

But, on occasion, I've had to manually fix paths and the replacePlugin is a lifesaver for those situations.

**Comment by charsleysa** [comment]
Closing as related to v3.x which is no longer supported.

**Comment by kiruh** [comment]
Is that issue resolved?
