### ISSUE TITLE
V4 Feature request: Differential Serving

### ISSUE THREAD

**Issue by bergkvist** [fuse-box/fuse-box#1697]
## ES5-bundle sizes and polyfills can significantly impact load times in modern browsers
As an optimization, it is possible to do what is known as "Differential Serving" (https://css-tricks.com/differential-serving/).

This means you serve an ES5-bundle to legacy browsers (like IE), and a more modern version (ES6+) to modern browsers (Chrome, Firefox, Safari etc.)

Below is an example of how this can be done in `index.html`:
```html
<!-- Browsers with ES module support load this file. -->
<script type="module" src="main.mjs"></script>

<!-- Older browsers load this file (and module-supporting -->
<!-- browsers know *not* to load this file). -->
<script nomodule src="main.es5.js"></script>
```

Example with Webpack: https://github.com/johnstew/differential-serving#how-to-create-two-bundles

### Suggestion for interface:
```ts
import { fusebox } from 'fusebox'
fusebox({
  target: 'browser',
  entry: 'src/index.ts',
  webIndex: {
    template: 'src/index.html',
    differentialServing: { legacyTarget: 'ES5', modernTarget: 'ES6' },
  }
}).runProd()
```

**Comment by SephReed** [comment]
Not an expert.  At the moment I do think it's possible to have bundling configuration which uses 
```
dependencies?: {
	ignorePackages?: Array<string>;
};
```
To ignore certain things.  If you listed all of the polyfills in here, you'd have a bundle without them.  You can also have multiple bundles being created by the same `fuse.ts` file.

I do like your suggestion, but if you're in a hurry I think you might be able to do it now.

**Comment by charsleysa** [comment]
Closed due to inactivity.
