### ISSUE TITLE
Svelte support?

### ISSUE THREAD

**Issue by aarongeorge** [fuse-box/fuse-box#1698]
Hey guys, just curious if there's any planned Svelte support for Fuse-Box?

Thanks

**Comment by nchanged** [comment]
@aarongeorge Svelte has its own compiler that's very hard to replicate and I don't think it makes sense tho.

**Comment by SephReed** [comment]
@aarongeorge What js are you trying to bundle?  It looks like Svelte handles most of the compilation/bundling itself.

**Comment by aarongeorge** [comment]
@nchanged, @SephReed I was just curious as to if I could use Svelte with Fuse-Box in a similar way to how I can with Parcel (Referencing .svelte files in my .ts files and have it compile)

I guess I'm just looking for best practices with Fuse-Box if Svelte was my "framework" of choice.

I use PostCSS, Tailwind, Svelte for my builds. How would you suggest configuring this to utilise Fuse-Box, or would you not use Fuse-Box?

**Comment by SephReed** [comment]
If you can figure out what is supposed to happen to a raw text svelte file (like maybe it gets passed to some function), it'd be really easy to make a Svelte plugin that catches the raw text of those imports and passes it in on.

If that interests you, relevant steps would be:
1. Figure out how to pass raw text to Svelte
2. Figure out what comes out the other side (and when)
3. Read up on how to make a plugin (https://github.com/fuse-box/fuse-box/blob/seph-docs/docs/development/plugins.md)

Currently fuse-box has preprocessors for sass and less built in.. they operate potentially similarly.

**Comment by aarongeorge** [comment]
Okay, thanks @SephReed, I'll look into this

**Comment by charsleysa** [comment]
Closed due to inactivity.
