### ISSUE TITLE
v4 Monorepo instructions not fully working.

### ISSUE THREAD

**Issue by SephReed** [fuse-box/fuse-box#1699]
I set up an example monorepo project:  https://github.com/fuse-box/fuse-mono

Currently, vscode is happy with all the tsconfig stuff.  Intellisense is working correctly.

But on compile I'm getting the following errors:
```
⚠️  Unable to extend tsconfig with ../tsconfig.paths.json. Make sure the file exists and readable 
⚠️  Cannot resolve "hash-tool" / Import statement: "hash-tool" i
```

If you could clone and debug this example project, I'll take note of any changes and add instructions for them to the docs.

Also, sorry if I wasn't supposed to create any repos here.  I can move it elsewhere if you prefer.

**Comment by SephReed** [comment]
Working with it a bit more, I'm pretty sure the `"extends"` part of tsconfig is the issue

**Comment by vegarringdal** [comment]
Busy atm but I have a weird little mono repo here,
Dunno if this can help in any way,

https://github.com/simple-html/simple-html

**Comment by SephReed** [comment]
I think I've narrowed my problem down to this one line of code:
https://github.com/fuse-box/fuse-box/blob/2318e3ffabe4f6bdbdbbdc1ef82747d7ad71e218/src/main/assemble.ts#L88

Retrieving typescriptPaths does not currently take `extends` into account... I think.  Still trying to back trace it.

**Comment by SephReed** [comment]
Nvm.  Found the real line:
https://github.com/fuse-box/fuse-box/blob/2318e3ffabe4f6bdbdbbdc1ef82747d7ad71e218/src/tsconfig/configParser.ts#L127

**Comment by SephReed** [comment]
Wrong again.  It appears "extends" should work by default.

https://github.com/fuse-box/fuse-box/blob/2318e3ffabe4f6bdbdbbdc1ef82747d7ad71e218/src/tsconfig/configParser.ts#L69

I'm at a loss as to why it doesn't follow the extend path correctly.

**Comment by vegarringdal** [comment]
@SephReed 

I also tried it shortly.
Not sure its complaining. But sample is not how I use the mono part..

Tried my own just incase it was broken.
https://github.com/simple-html/simple-html

Just ran `npm install`
Then it looks like samples are working fine like `npm run grid-sample`

Typechecking is also working (made type errors just to test)

![image](https://user-images.githubusercontent.com/2901416/70475994-0e180480-1ad6-11ea-95ea-7c70ecdb2dae.png)

**Comment by SephReed** [comment]
I found the issue.  Any extended tsconfig files must be valid json (tsconfig.json is not valid json).

Put in a PR for better error messaging, but **I'm still getting issues further down the line**.

https://github.com/fuse-box/fuse-box/pull/1700

The current issue is that including neighbor packages works, but the `node_modules` they use fail to get included in the bundle...

I'm kind of putting monorepo through the ropes.

**Comment by vegarringdal** [comment]
k
Im only using 1 common node_modules folder at the root of my mono-repo.
So maybe thats why Im not getting any issues.

That solution might not work well with how others need it. But for my need its very simple to add more packages and samples. run them and debug/edit both sample and package source with watch running.

**Comment by SephReed** [comment]
I've got a really fucky scenario.

I need to be able to export my individual packages as their own repos.  It's a massive pain in the ass, but it's the only way to make internal development void of concurrency issues, while making small parts of the monorepo open source.

**Comment by vegarringdal** [comment]
dunno if I follow... but its late. 😂 

So you want a open source mono repo but you dont want it to have all the packages ?

**Comment by SephReed** [comment]
I want a closed source mono repo with open source sub projects.

There's a lot of support tools I'm making.  I want them to be OSS.  The main projects, not so much.

**Comment by SephReed** [comment]
Do you know if resolver has any form of stack?  

Like an array of all the files that it's working within the context of in terms of includes.  So file a includes b includes c.  Currently in file c.

**Comment by SephReed** [comment]
Once again... it appears the code for this already has been implemented:

https://github.com/fuse-box/fuse-box/blob/2318e3ffabe4f6bdbdbbdc1ef82747d7ad71e218/src/main/assemble.ts#L209-L216

**Comment by SephReed** [comment]
For some reason the module has no meta:
```
 compiler default/HashTool/src/index.jsModule {
  props:
   { absPath: '/Shared/Code/examples/fuse-mono/HashTool/src/index.ts',
     ctx:
      Context {
        config: [PrivateConfig],
        log: [FuseBoxLogAdapter],
        weakReferences: [WeakModuleReferences],
        assembleContext: [Object],
        ict: [Object],
        webIndex: [Object],
        taskManager: [ContextTaskManager],
        writer: [Object],
        tsConfig: [Object],
        devServer: [Object] },
     extension: '.ts',
     fuseBoxPath: 'HashTool/src/index.js' },
  pkg:
   Package {
     props: { ctx: [Context], meta: [Object] },
     modules: [ [Module], [Circular] ],
     userEntries: [],
     externalPackages: [ [Package] ],
     isFlat: true,
     isDefaultPackage: true,
     entry:
      Module {
        props: [Object],
        pkg: [Circular],
        assembled: true,
        header: [],
        moduleDependencies: [Array],
        externalDependencies: [Array],
        errored: false,
        _isStylesheet: false,
        _isExecutable: true,
        contents:
         'import {localHashTool} from "hash-tool";\nimport { helloWorld } from "path1";\n\n\ndocument.addEventListener("DOMContentLoaded", () => {\n\tdocument.title = helloWorld;\n\tdocument.body.innerHTML += `\n\t\tA random hash: ${localHashTool(Math.random(), "FOO")}<br>\n\t\t(refresh to update)\n\t`;\n});',
        _isJavascriptModule: false,
        ast: [Object],
        analysis: [Object] } },
  assembled: false,
  header: [],
  moduleDependencies: [],
  externalDependencies: [],
  errored: false,
  _isStylesheet: false,
  _isExecutable: true,
  contents:
   'import stringHash from "string-hash";\n\n\nexport function localHashTool(txt: string | number, salt: "FOO" | "BAR") {\n  return stringHash(txt + salt);\n}',
  _isJavascriptModule: false,
  ast:
   { type: 'Program',
     sourceType: 'module',
     body: [ [Object], [Object], [Object] ] },
  analysis: { imports: [ [Object] ] } } undefined
```

**Comment by SephReed** [comment]
Found the issue.  The following assumes that package.json is in the src directory of the project:

https://github.com/fuse-box/fuse-box/blob/2318e3ffabe4f6bdbdbbdc1ef82747d7ad71e218/src/resolver/fileLookup.ts#L109-L112


`console.log(packageJSONPath); --> /Shared/Code/examples/fuse-mono/HashTool/src/package.json`

**Comment by SephReed** [comment]
Put in PR to help with some of these issues

https://github.com/fuse-box/fuse-box/pull/1702
