### ISSUE TITLE
Direct export throws SyntaxError

### ISSUE THREAD

**Issue by vanthiyathevan** [fuse-box/fuse-box#17]
when you export from another module like `export App from './App'` throws `SyntaxError`

```
SyntaxError: Unexpected token (1:7)
    at Parser.pp$4.raise (/home/mohan500/project/git/github.com/react-example/node_modules/acorn/dist/acorn.js:2431:15)
    at Parser.pp.unexpected (/home/mohan500/project/git/github.com/react-example/node_modules/acorn/dist/acorn.js:616:10)
    at Parser.pp.expect (/home/mohan500/project/git/github.com/react-example/node_modules/acorn/dist/acorn.js:610:28)
    at Parser.pp$1.parseExportSpecifiers (/home/mohan500/project/git/github.com/react-example/node_modules/acorn/dist/acorn.js:1324:10)
    at Parser.pp$1.parseExport (/home/mohan500/project/git/github.com/react-example/node_modules/acorn/dist/acorn.js:1260:30)
    at Parser.pp$1.parseStatement (/home/mohan500/project/git/github.com/react-example/node_modules/acorn/dist/acorn.js:754:71)
    at Parser.parseStatement (/home/mohan500/project/git/github.com/react-example/node_modules/acorn-es7/acorn-es7.js:72:28)
    at Parser.pp$1.parseTopLevel (/home/mohan500/project/git/github.com/react-example/node_modules/acorn/dist/acorn.js:658:25)
    at Parser.parse (/home/mohan500/project/git/github.com/react-example/node_modules/acorn/dist/acorn.js:528:17)
    at Object.parse (/home/mohan500/project/git/github.com/react-example/node_modules/acorn/dist/acorn.js:3309:39)
```

[Fork](https://github.com/vanthiyathevan/react-example)

**Comment by nchanged** [comment]
Okay, are you sure that App has default exports? Cuz if it does not, you will get this error

try `export { App } from './App.jsx';`

**Comment by vanthiyathevan** [comment]
Yes it does. see [fork](https://github.com/vanthiyathevan/react-example)

**Comment by nchanged** [comment]
It says `Declaration or statement expected`

**Comment by vanthiyathevan** [comment]
Sorry about that. Fixed the import. Still same error

**Comment by nchanged** [comment]
If acorn complains that means that you have a syntax error

**Comment by devmondo** [comment]
@vanthiyathevan is it possible that you are using some feature that needs some babel plugin, or you are just using the original repo code?

**Comment by eisisig** [comment]
I'm actually getting this error (Unexpected token) and error reporting from acorn really doesn't help.

**Comment by devmondo** [comment]
@vanthiyathevan i checked the project,

first there is syntax error here [react example](https://github.com/vanthiyathevan/react-example/blob/master/src/App/App.jsx#L7)
`cons` should be `const`
also
`export App  from './App';`
should be 
`export { App } from './App';`

after i fixed those, build is passing fine, hope this helps

**Comment by nchanged** [comment]
Also please, make sure you references make sense
https://github.com/vanthiyathevan/react-example/blob/master/src/App/index.js#L1
You don't have `App.js` file in that folder.

**Comment by vanthiyathevan** [comment]
the difference to this working vs the the error 
this throws error
```js
export App from './App'
```

This compiles as expected.
```js
import App from './App'
export { App };
```

@devmondo It is possible. I've switched to using presets `latest`, `stage-0`, and `react` and explicitly added [`transform-export-extensions`](https://babeljs.io/docs/plugins/transform-export-extensions/). Still same acorn error.

**Comment by devmondo** [comment]
@vanthiyathevan thanks for update,

can you try this `export {App} from './App' directly without import statement.

**Comment by vanthiyathevan** [comment]
@devmondo 
Hmm interesting. export {App} from './App' works. But given the `./App` is default export, Shouldn't `export App from './App'` be working?

**Comment by nchanged** [comment]
`export App from './App'` is not a valid syntax. 
Please. read up [here](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/export)

**Comment by vanthiyathevan** [comment]
I see now. the syntax I am using are part of proposal 
- https://github.com/leebyron/ecmascript-export-default-from
- https://github.com/leebyron/ecmascript-export-ns-from


and stage 1 supported by babel and not by acorn.
see the astexplorer.net
- [bable](https://astexplorer.net/#/6tzQZSkgaD)
- [acorn](https://astexplorer.net/#/fZJ39jJX3n/1)

**Comment by nchanged** [comment]
I see. I think we can use babel AST as an alternative. I will implement this feature

**Comment by nchanged** [comment]
`1.3.13` has it fixed. stage-0 does not spit an error, however, is not giving me expected code back.
It transpiles it as "undefined". So it must be related to that plugin. Nonetheless, all questions to babel.

**Comment by vanthiyathevan** [comment]
Thanks for the quick response. But if I specify my own `test` without `limit2project` this reverts to using only acron AST only because of [This](https://github.com/fuse-box/fuse-box/commit/3862f7b77e45b2ad2a4d55f9043de4fba88c6375#diff-cce8c4ee9af60947caba11bb839e6f30R37)

**Comment by nchanged** [comment]
Sorry, my bad. FIxed in `v1.3.15`

**Comment by devmondo** [comment]
i can confirm that Error reporting in `v1.3.16` is awesome now!!!

**Comment by nchanged** [comment]
Nice! @devmondo  Thanks,
Let's wait for @vanthiyathevan to confirm that BabelPlugin is now using babel AST instead of acorn.

**Comment by vanthiyathevan** [comment]
Thanks. This works. Yes the error message is very cool. Will try it on a real project and let you know. 
The `undefined` is because of babel transpiling. 
Although when export is pointing to a non existing file, The transpiling goes through without errors. May be it should warn the file doesn't exist?

**Comment by nchanged** [comment]
Hi!
Thanks!
Certainly a warning can be optional. But in essence, a user might require a file that's not in a bundle. And get it via `dynamic imports`. So this has to be though through. 

Thanks again for submitting this issue, it led to an amazing improvement on BabelPlugin and the core itself.

Cheers.

**Comment by vanthiyathevan** [comment]
Thanks. I'm going to try this on a fairly large project.
