### ISSUE TITLE
Feature Suggestion: addPackage(...) to override what ever is under node_modules/or add new

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box#170]
Could be useful if we could add a package that overrides what ever is under node_modules
This could also be used when making plugins and you want it to load normally in the sample/demo

```
const fb = require("fuse-box");
const fuse = fb.FuseBox;

let fuseBundle= fuse.init({
    homeDir: "./src",
    outFile: "./vendor-bundle.js",
    tsConfig : "tsconfig.json",
    useCache:false,
    plugins: [
        fb.CSSPlugin(),
        fb.HTMLPlugin({ useDefault: true }),
        fb.TypeScriptHelpers()
    ],
    sourceMap: {
        bundleReference: "./vendor-bundle.js.map",
        outFile: "./vendor-bundle.js.map",
    }
})

fuseBundle.addPackage({
    name:"somethingCool",
    path:"./node_modules/somethingCool/dist/commonjs",
    main:"something.js"
    resources :`
        + **/*.html 
        + utils/**/*.js
        + styles/**/*.css
    `
})

fuseBundle.addPackage({
    name:"evenCooler",
    path:"./node_modules/evenCooler/src",
    main:"index.ts"
    resources :`
        + **/*.html 
        + utils/**/*.js
        + styles/**/*.css
    `
})

fuseBundle.addPackage({
    name:"evenCooler",
    path:"./plugin",
    main:"index.ts"
    resources :`
        + **/*.html 
        + /**/*.js
        + /**/*.css
    `
})



fuseBundle.devServer(`
    > main.ts
    + **/*.html 
    + **/*.ts 
    + **/*.css
    + evenCooler
    + somethingCool`
)

```

Update:
From gitter

> @vegarringdal that one need some work and discussion hahaahha
yes, I would like if I could also add plugins to a package, in case I want to build it from source instead of using built source

**Comment by devmondo** [comment]
@vegarringdal yes we have this in works, it works kind of like `JSPM` mapping :)

**Comment by nchanged** [comment]
Hm could be useful...

**Comment by vegarringdal** [comment]
> Hm could be useful...

This could be VERY useful 😄

**Comment by leon-andria** [comment]
hi guys,

This is like déjà à la Aurelia cli config. Even it's like Aurelia requirements, it is more than that.
This kind of feature need to be clear tackle properly because it's a feature inside hidden feature.
In theory, it's behave like "modulesFolder", or having  a kind of multi bundle or code splitting with lazy loading :-), or even like adding many package in the bundle.
Seriously, we should take one by one from the start. The concept of Aurelia by using plugin with "string" name (good luck tree shaking for exemple) can't be look up dependencies but Aurelia expect that package should be there. So, FuseBox should accept a kind of mapping with "pre-defined" names. Take care about pre-defined name because this will also can introduce the code splitting or lazy loading deps on-demand depending on the execution context, so it's not easy.
FuseBox should manage all of these with a kind of smart metadata to lookup packages or bundle inside bundle :-)
Also, we need to keep in mind the simplicity (this is the challenge) for managing the configuration. Trust me, the example that @vegarringdal is just an overview how it can be big regarding the kind of projects.
@vegarringdal I fully understand your concern from Support Aurelia because it's right and require a good solution for this or the other issues.
I will prepare a suggestion and architecture design when i can asap.
hth,

**Comment by vegarringdal** [comment]
@leon-andria 

Its not just aurelia, want something super simple, fast and fun :-)
If we get something a lot more advanced then thats ok ,  can make a wrapper to make it simple then:-)

Atm https://github.com/vegarringdal/aurelia-fusebox-test/blob/master/fuse.js test at adding extra resources to a module/plugin was not working as expected... I would love if someone could tell me why I dont have a entry if I skip the aurelia-v-grid in the devServer

**Comment by Thanood** [comment]
Well, the proposal *does* look like Aurelia CLI config. 😃 

I agree to @devmondo though. JSPM and Webpack both have an overriding mechanism should it be necessary. I think it is very useful - I've been using JSPM overrides a lot.

I also agree with @leon-andria in that this should be prepared carefully and easy to use.

**Comment by nchanged** [comment]
I will just leave it here. I am a crazy guy

```js
fuseBundle.bundle(`
    > main.ts
       + **/*.html 
       + **/*.ts 
       + **/*.css
       + evenCooler
       + somethingCool

    // Allow comments here
    + somethingCool (
         > node_modules/somethingCool/dist/commonjs
            + **/*.html 
            + /**/*.js
            + /**/*.css
      )

   // Some cool stuff
   + evenCooler (
         > node_modules/somethingCool/dist/commonjs
              + **/*.html 
              + /**/*.js
              + /**/*.css
     )
`)
```

**Comment by nchanged** [comment]
```
fuseBundle.addPackage({
    name:"somethingCool",
    root:"./node_modules/somethingCool/dist/commonjs",
    rules :`
        > something.js
          + **/*.html 
          + utils/**/*.js
          + styles/**/*.css
    `
});
```
isn't more consistent @vegarringdal ?

**Comment by Thanood** [comment]
I kinda like that actually..

Something like what @vegarringdal proposed is still possible (if users want to) and could just prepare the strings of these (let's call it) "submodules". And it's still an arithmetic expression so it should be in line with FuseBox's concept.

**Comment by devmondo** [comment]
i say we have an option to pass this as json strucuture `include/exclude` or with api.addpackage like @vegarringdal  suggeted.

with some project it gets really complicated, and putting all this in a string is really confusing and not maintainable, not to mention that some people have in house tools to build the config.

anyways i think having more than one option is always good as it covers all styles

**Comment by nchanged** [comment]
@devmondo having too many options is not good either.  It has to be consistent enough.

**Comment by devmondo** [comment]
@nchanged  it is not about to many options, it is about style coverage, maybe I phrased it wrongly. in reality it will be 2, either string as now, or JSON, but hey I fully agree we need to be consistent, maybe we keep it as it is now and everyone use his own  arithmetic string builder, we can’t cover all cases, what if people are using MS build, well they have to build their custom arithmetic string builder.

so all in all i agree maybe we should leave this up to the user requirement.

**Comment by vegarringdal** [comment]
```fuseBundle.addPackage({
    name:"somethingCool",
    root:"./node_modules/somethingCool/dist/commonjs",
    rules :`
        > something.js
          + **/*.html 
          + utils/**/*.js
          + styles/**/*.css
    `
});
```
>isn't more consistent @vegarringdal ?

Sure :+1: 
Will we be able to add plugins to a package, or will that only be part of the init?
Was thinking incase 1 package needs something special... dunno really if this will ever be the case

**Comment by nchanged** [comment]
@vegarringdal we should keep that in mind. If it's convenient for development! Of course! That's our mission here.

**Comment by vegarringdal** [comment]
@nchanged Great :-)
Will it be done this week ? :joy:

**Comment by nchanged** [comment]
Man, believe it or not, i would like all issues to be resolved TODAY.

**Comment by vegarringdal** [comment]
@nchanged 
That would have been awesome 👍

**Comment by vegarringdal** [comment]
@nchanged 

On this we will need to be able to set entry too without it executing :-)

**Comment by vegarringdal** [comment]
https://github.com/fuse-box/fuse-box/issues/312

**Comment by vegarringdal** [comment]
Played a little more around with this and how it could be done
Here is a complete build for how I would like to do a sample catalog in a Aurelia plugin
If this was possible it would have been **Amazing!**

```javascript

var buildPluginSample(){

    const fb = require("fuse-box");
    const fuse = fb.FuseBox;

    // build our sample catalog
    let fuseBundle = fuse.init({
        homeDir: "./sample/src",
        outFile: "./sample/bundle/fb-app-bundle.js",
        useCache: false,
        sourceMap: {
            bundleReference: "./fb-app-bundle.js.map",
            outFile: "./sample/bundle/fb-app-bundle.js.map",
        },
        plugins: [
            fb.CSSPlugin(),
            fb.HTMLPlugin({
                useDefault: true
            }),
            fb.TypeScriptHelpers(),
            fb.SourceMapPlainJsPlugin()
        ],
        // new way of overriding packages that gets added...
        packages: [{
            name: "aurelia-v-grid",
            path: "./src", // source of my plugin, but could have been a nodemodule
            main: "index.ts",
            tsConfig: "../tsconfig.json",
            plugins: [
                fb.CSSPlugin(),
                fb.HTMLPlugin({ useDefault: true }),
                fb.TypeScriptHelpers()
            ],
            sourceMap: true, //sourcemap gets added to main sourcemap
            watch: true, // if true main emitter triggers on changes
            resources: `
        + [**/*.html] 
        + [**/*.js]
        + [**/*.css]`
        }]
    });

    fuseBundle.devServer(`
            > main.ts
            + **/*.html 
            + **/*.ts 
            + **/*.css
            + aurelia-framework
            + aurelia-something`, {
            root: './sample'
        }
    );

}
```

@nchanged, @devmondo  I know you will be busy with the BTI, but will this possible? or to complicated?

@Thanood Anything you see that would not work for you popular "Aurelia-materialize-bridge"

**Comment by devmondo** [comment]
@nchanged  we need to solve dear sweet @vegarringdal  issue :)

**Comment by arabsight** [comment]
Hi, @vegarringdal I'm wondering why you put tsConfig and plugings inside the package definition, since packages are third-party (usualy npm package) libraries that are already transpiled.

**Comment by vegarringdal** [comment]
@arabsight 
Hi, well I also want to use fusebox while developing a Aurelia plugin too.
So in a plugin repo I would have a sample catalog where I actually use the source of the plugin, this is also why I also have a watch.
These would be options:
* tsConfig
* plugin
* watch
 
For the plugin I would also have build task(gulp) for the plugin to generate amd, commonjs, system & es2015 distributions under ```dist```

Like I do here:
https://github.com/vegarringdal/vGrid

**Comment by arabsight** [comment]
oh, got it, didn't pay attention to this: *path: "./src"*. you want to build your plugin from within your client app.

**Comment by vegarringdal** [comment]
@arabsight 👍 
Yes, one that sample code I wanted to show that part
So watch, plugins, tsConfig would have to be optional

We are able to make packages if you accept seperate bundle now, here is a sample where I do it
Using the src so I get the sourcemaps too in this one, kinda liked that, and I didnt include them in the dist/commonjs for some reason
https://github.com/vegarringdal/aurelia-fusebox-test/blob/master/build/fb-aurelia-v-grid-build-bundle.js

**Comment by arabsight** [comment]
good :+1: by the way I'm also writing a loader for aurelia https://github.com/arabsight/aurelia-loader-fusebox (trying to use aurelia's css resources instead of fuse's CSSPlugin)

**Comment by vegarringdal** [comment]
We have a loader we created here that works too

https://github.com/fuse-box/fuse-box-aurelia-loader

You can do ```<require from="../csstest.css"></require>``` with that one

csstest.css
```
body {
    background-color: yellow;
}
```

**Comment by arabsight** [comment]
that injects the css directly with fusebox right, which means you can't use aurelia's css-ressource's scoped option: *<require from="../csstest.css" as="scoped"></require>* for firefox and shadowDom.

**Comment by vegarringdal** [comment]
I just load the css from the bundle when Aurelia asks for it and returns it

No idea how scoped works :-)

Maybe you can just add plugin using this:
https://github.com/fuse-box/fuse-box-aurelia-loader/blob/master/src/fuse-box-aurelia-loader.ts#L184-L190

If you tell me more I will be happy to do adjustments to make the current loader better as long as we dont break anything thats working :-)

**Comment by arabsight** [comment]
when aurelia-templating-resources is loaded it automatically adds *css-resource-plugin* to the loader that's why you get 'css-resource-plugin!styles.css', which means css gets loaded with css-resource plugin which is responsible for injecting the css in the head or adds scoped attribute for firefox or inject the css in element boundary if its using shadowDom, but if you load css with fusebox all it does is inject the css in the head and the css-resource plugin will be ignored, meaning if you put as="scoped" on require it will have no affect.

**Comment by vegarringdal** [comment]
ok

Looks like you can override the inject part
```
fb.CSSPlugin({
                outFile: (file) => `bundle/${file}`,
                inject: false,
            }),
```

**Comment by Thanood** [comment]
@vegarringdal @arabsight I think you two should really join forces creating an Aurelia loader. 😃

**Comment by arabsight** [comment]
sure @Thanood :+1: 
@vegarringdal  that just writes a css file, but there's a problem with CSSPlugin it doesn't return the content, so if you do FuseBox.import('style.css') it will return an empty object, meaning aurelia css-resourec will fail to load it. that's why I'm loading css as text using RawPlugin.

**Comment by vegarringdal** [comment]
👍 
@arabsight do you have a ```css-resource-plugin``` plugin ?
you want this to load it as pure text then right when using it with raw
So much I dont know about this part so need help 😂

**Comment by arabsight** [comment]
css-resource-plugin is built-in with aurelia-templating-resources [here](https://github.com/aurelia/templating-resources/blob/master/src/aurelia-templating-resources.js#L66) (if you inspect your loader instance at runtime you'll see it in the list of *loaderPlugins*), the other loaders feed it text using text plugins, fusebox equivalent is RawPlugin.

**Comment by nchanged** [comment]
```
fuse.register('stuff', {
    root : "./node_modules/somethingCool/dist/commonjs",
    instructions : `
        > something.js
            + **/*.html 
            + utils/**/*.js
            + styles/**/*.css
    `
})
```
This is what I have in mind. But there is something to sleep on. That should play nicely with the latest discussion on lazy `imports`
1) One should make a separate bundle based on this config
2) Include to the primary bundle (optionally)
3) Watch for changes

**Comment by vegarringdal** [comment]
@nchanged but will you be able to set main without it executing when you have it like that ?

Will it support making modules where you need to compile the typescript too ?
Needed for development

**Comment by nchanged** [comment]
That's the thing, i would like to have full specs on that one ;-)

**Comment by vegarringdal** [comment]
How I imagined it was that it was able to do what I do here:
https://github.com/vegarringdal/aurelia-fusebox-test/blob/master/build/fb-aurelia-v-grid-build-bundle.js

Just with out separate but part if the app bundle, and being able to watch for changes so if you are using the devServer you can have it reloading :-)

I could actually live fine with what I have if I can combine 2 bundles into one (with source-map working)
Because I could just use gulp watch to watch for changes, but would be nice if it was built in :-)

**Comment by vegarringdal** [comment]
@arabsight 

I played around with the loader and faced it to use the "plugin.fetch" of the css.resources, when using the raw plugin, hoping it would then load the css using the loadText of the loader, but really not sure why its not doing more, but its late and Im tired :-)

**Comment by vegarringdal** [comment]
@arabsight 
note, Ive started rewriting the loader using the webpack as a start point
Ill know more how this goes in a hour or two

**Comment by vegarringdal** [comment]
yep, light work well

@arabsight 

atm this is the plugin part
```
et bundle = fuse.init({
            homeDir: "./src",
            outFile: "./bundle/fb-app-bundle.js",
            useCache: false,
            sourceMap: {
                bundleReference: "./fb-app-bundle.js.map",
                outFile: "./bundle/fb-app-bundle.js.map",
            },
            plugins: [
                [/\.css$/, fb.RawPlugin({extensions: ['.css']})],
                fb.HTMLPlugin({
                    useDefault: true
                }),
                fb.TypeScriptHelpers(),
                fb.SourceMapPlainJsPlugin()
            ]
        });
```


And ```<require from="./test.css"></require>```  is loading very well by aurelia framework it self/injecting css

Ill update update my own repo and update the sample part
@arabsight Will need help from you to test if the loader is working like you expected when Im done

**Comment by vegarringdal** [comment]
@nchanged @devmondo 
* Given this more thought on how it could work ? 
* is it possible ?
* something that will be hard to implement ?

Yes I know you guys have a lot to do 😄

**Comment by devmondo** [comment]
@vegarringdal  of course man, this should be part of the next code splitting milestone, please elaborate on this in that issue too, sometimes you have to push... push...push until it pops!

**Comment by vegarringdal** [comment]
> @vegarringdal of course man, this should be part of the next code splitting milestone, please elaborate on this in that issue too, sometimes you have to push... push...push until it pops!

@devmondo So milestone .124 then ? 😂 

Btw the does have so much to do with code splitting as it does giving you control what gets included in packages... something that is needed for aurelia plugins where we have css, html etc that you cant get by just having ref to a entry.

Also helps if for some reason the main in json isnt commonjs..

**Comment by devmondo** [comment]
@nchanged  valid concerns here !

**Comment by vegarringdal** [comment]
>valid concerns here !

@devmondo Yes 👍

**Comment by vegarringdal** [comment]
@nchanged 1.4.1 maybe? 😂

**Comment by nchanged** [comment]
@vegarringdal 1.4.2 because 1.4.1 will open doors for this feature. Don't think I forgot about that feature ;-)

**Comment by vegarringdal** [comment]
@nchanged I had to try 👍

**Comment by vegarringdal** [comment]
@nchanged 
Was this in the preview now ?

**Comment by nchanged** [comment]
It's not yet complete :) i will create a demo today, after I have finished refining it

**Comment by nchanged** [comment]
Don't worry man, it's partly implemented already, you will get this feature nice and shiny :)

**Comment by vegarringdal** [comment]
ok :-) Just wanted to test it if it was ready :-)

**Comment by vegarringdal** [comment]
@nchanged 

```
fuse.register('aurelia-v-grid', {
        homeDir: 'node_modules/aurelia-v-grid/dist/commonjs',
        main: 'index.js',
        instructions: '**/*.{html,css,js}',
    });
```

You can add this to the 1.4.1 milestone now, since its in...
