### ISSUE TITLE
v4: Uncaught Package not found tslib

### ISSUE THREAD

**Issue by bogdandv** [fuse-box/fuse-box#1706]
When I try to bundle my app I get an Uncaught Package not found tslib error in dev mode without dev server. Please note that in production mode all works well

```
class Context {
    runServer;
    getConfig = (useSourceMap) =>
        fusebox({
            target: "browser",
            homeDir: "HomeDir",
            entry: "boot-client.tsx",
            output: 'root/$name',
            webIndex: {
                target: "root",
            },
            tsConfig: 'tsconfig.json',
            cache: false,
            devServer: false,
            useTypescriptCompiler: true,
            sourceMap: useSourceMap
        });
}
const { task } = sparky<Context>(Context);
task("start:dev", async ctx => {
    ctx.runServer = false;
    const fuse = ctx.getConfig(true);
    await fuse.runDev();
});
```

**Comment by nchanged** [comment]
```ts
dependencies: {
    include: ['tslib'],
 }
```

**Comment by bogdandv** [comment]
It Works :)
Thank you! 
And sorry for the dumb issue...

**Comment by SephReed** [comment]
Do you think maybe this should be a default include?

**Comment by nchanged** [comment]
@SephReed I am working on production mode in alpha based on fuse-compiler. There won't be any need for `tslib` after that ;-)

**Comment by SephReed** [comment]
Awesome.

Is there a good place to add an error message that says something like:

> Uncaught Package not found `common-package`.  Perhaps add `dependencies: { include: ['common-package'], }` to your fuse config.

**Comment by nchanged** [comment]
Either resolver or assemble )

**Comment by SephReed** [comment]
It seems like here might be the place:  
https://github.com/fuse-box/fuse-box/blob/85597f7ba183e2c7b246a5dee67d63404b863688/modules/fuse-loader/index.js#L187-L189

```
throw `Package not found ${pkgName}.  If this is a core dependency, you may want to include "dependencies: { include: ['common-package'], }" to your fuse config`;
```
