### ISSUE TITLE
Question: Vendor App in development mode

### ISSUE THREAD

**Issue by bogdandv** [fuse-box/fuse-box#1708]
How can I set fusebox v4 in development mode to generate two files (vendor.js and app.js)?

Now it generates 4 files:
05SOMECODE_app.js
05SOMECODE_dev.js
05SOMECODE_entry.js
05SOMECODE_vendor.js

All files are imported in index.html.

**Comment by nchanged** [comment]
@bogdandv not ATM, but I am working on customising the output in v4 alpha!

**Comment by SephReed** [comment]
For documentation, there's another issue with a similar problem/solution set.

https://github.com/fuse-box/fuse-box/issues/1694

**Comment by nchanged** [comment]
That's correct @SephReed thanks for referencing it!

**Comment by nchanged** [comment]
relevant https://github.com/fuse-box/fuse-box/issues/1756

**Comment by charsleysa** [comment]
@bogdandv can you please confirm if the issue still occurs with `fuse-box@4.0.0-next.400`?
Also see [here for info on major changes](https://github.com/fuse-box/fuse-box/blob/master/docs/changelog-fuse-compiler.md)

**Comment by nchanged** [comment]
Custom output has been implemented in the latest version. We can close this one.
