### ISSUE TITLE
Fuse Compiler / transformer specs 

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#1714]
I would need some help regarding this topic
https://github.com/fuse-box/fuse-box/tree/fuse-compiler/src/compiler/transformers

Fuse Compiler is a custom build transpiler built on top of [buntis](https://github.com/buntis/buntis) and [meriyah](https://github.com/meriyah/meriyah/). It uses only one transformer for both languages. But I am hitting a wall when trying to design the transformers properly

Those are the following rules/conditions for transformers

### A transformer can be applied for javascript or typescript or both files. 

Currently, it's solved by using `transformerAtPath` API. But I am having doubts about that.
Would the following be better?

```ts
export function transformer(){
  return {
     test : /.jsx?/,
    ... rest
  }
}
```

### Development and production

Development (or main) transformer should be fast, however it plays a big role at collecting the dependency tree. For example, a transformer might emit some helper dependency, that's required for runtime. 

```ts
export function transformer(){
  return {
    main : () => {}
  }
}
```

Since main transformers transform the code and destroy the es-module structure, we'd need to flush it all for production (after the dep. tree has been built) and start over (in order to do code splitting and tree-shaking)

```ts
export function transformer(){
  return {
    main : () => {},
    productionPre () => {
    }
  }
}
```

**productionPre** here I'd do tree shaking and code splitting. 

However, we also need an initialiser to get prepared

```ts
export function transformer(){
  return {
    main : () => {},
    productionInit(ctx, packages) => {},
    productionPre () => {
    }
  }
}
```

`productionInit` with `packages` is where we receive the whole dependency tree. `productionPre` could pick up required data from `ProductionContext`

And finally, we have the stage where `main` section should be re-applied. Remember the AST tree needs to be flushed before we go for the production build.

```ts
export function transformer(){
  const handlers =  {
    main : () => {},
    productionInit(ctx, packages) => {},
    productionPre () => {
    },
   productionFinal() => {
      return handlers.main()
   }
  }
  return handlers;
}
```

**Comment by SephReed** [comment]
@nchanged Could you list your current known stages of transforms (ie `typecheck, precompile, compile, treeshake`).

Basically, any place where a person might ever want to interject and modify `ctx`.

**Comment by nchanged** [comment]
@SephReed What I described earlier. There are plugins where a user can modify the `ctx`
But with the production stage it gets a bit more complex since we might need to know when the whole process has started. 

1. Development stage
2. Production init
3. Flush AST ror all modules. **Start over**
4. Treeshake / code splitting
5. **Development stage** + custom handlers for it.

**Comment by SephReed** [comment]
There's a lot to parse here

<img width="338" alt="Screen Shot 2019-12-17 at 3 05 23 PM" src="https://user-images.githubusercontent.com/14002040/71034270-addd2000-20de-11ea-8ffe-34b4cd05236b.png">

It seems like every file that ends with `Transformer` would be a reasonable place to expect someone to want to add some work before or after.

Which of these have an inherent order?  Maybe they can be grouped into phases of parallelism.

For instance `exportTransformer` and `inputTransformer` should never have an order, so they could be grouped as the `import-export-phase`

**Comment by tomitrescak** [comment]
Hi, Will there be a support for custom transformers such as in v3?
