### ISSUE TITLE
$fsx is not defined in runProd()

### ISSUE THREAD

**Issue by SephReed** [fuse-box/fuse-box#1716]
I searched dist for `$fsx =` and it appears to never be set.  Where is it supposed to be set?  App or Vendor?

**Comment by nchanged** [comment]
It should be in API.js or dev.js

**Comment by SephReed** [comment]
<img width="272" alt="Screen Shot 2019-12-28 at 1 01 04 PM" src="https://user-images.githubusercontent.com/14002040/71548311-290dc400-2972-11ea-8f88-af6446ccb1ff.png">

**Comment by nchanged** [comment]
@SephReed then it should be in vendor.js at the very top

**Comment by SephReed** [comment]
<img width="813" alt="Screen Shot 2019-12-29 at 4 53 52 PM" src="https://user-images.githubusercontent.com/14002040/71563832-d27cb480-2a5b-11ea-90f1-fb44eaa255fd.png">
I can see where it would be.  I've just been adding it myself to make things work.

But it's not there by default.

**Comment by nchanged** [comment]
I think your configuration is missing "target" that's why it's not there ...

**Comment by SephReed** [comment]
which targets will should add it, and which should not?

**Comment by nchanged** [comment]
@SephReed I think there is a bug with undefined target... Could you verity that?

**Comment by SephReed** [comment]
setting target does the trick.

**Comment by SephReed** [comment]
Given that these settings work fine for dev, it would probably be nice if they continued working for prod.

**Comment by charsleysa** [comment]
@SephReed can you please confirm if the issue still occurs with `fuse-box@4.0.0-next.400`?
Also see [here for info on major changes](https://github.com/fuse-box/fuse-box/blob/master/docs/changelog-fuse-compiler.md)

**Comment by charsleysa** [comment]
Closed as no response received.
