### ISSUE TITLE
[v4] Hard reload when watched files change

### ISSUE THREAD

**Issue by Teoxoy** [fuse-box/fuse-box#1717]
I am developing a WebGL application that can't be easily made to work with HMR. I would like the app to be reloaded for changes to js/ts files and hot reloaded for css files. Is this currently possible?

I have tried `hmrServer: false` option but it ended up not reloading the browser at all.

Related issue for HTML files: #1597

**Comment by Teoxoy** [comment]
@nchanged What do you think about a config option that when turned on will hard reload (not hot reload) on js/ts file changes? This config option should also only apply to js/ts files - html should always be hard reloaded (as per #1597) and css can always be hot reloaded.

The logic for reloading will be added to fix #1597 and I think this would be a nice addition since not all application can support hot reloading.

**Comment by nchanged** [comment]
I agree with you, there should be an API for that too

**Comment by vegarringdal** [comment]
ugly hack for reloading until there is a option for hard reload
```js
if(document.body){
    window.location.reload()
}
```
ofc. this might blow up if you load js in or after body tag.. 😂

**Comment by Teoxoy** [comment]
@vegarringdal a hack is fine for the time being but how does the hack above work? Is `document.body` ever undefined?

**Comment by vegarringdal** [comment]
> Is document.body ever undefined?

yes during header load (if you have the entry js/ts file loaded here)
So 2nd time it wont be undefined..

**Comment by Teoxoy** [comment]
Oh, I see what you mean.

I ended up doing it like this:

```ts
if (window.loaded) {
    window.location.reload()
}
window.loaded = true
```

because I load the js in the body.

@vegarringdal thanks for the tip!

**Comment by vegarringdal** [comment]
That works too. :-)

**Comment by thscott** [comment]
The hardReloadScripts option seems to have been removed (though it's still mentioned in the docs in a few places, such as [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/full-config.md).
