### ISSUE TITLE
optional chaining not suported in "fuse-box": "^3.7.1"

### ISSUE THREAD

**Issue by AnasBoulmane** [fuse-box/fuse-box#1722]
optional chaining and other features supported by typescript are not working with "fuse-box": "^3.7.1"
![image](https://user-images.githubusercontent.com/17661697/71521778-6f0b4f00-28c2-11ea-9483-549110b3ae5c.png)

I'm using typescript `"^3.7.4"` and when I'm running it using `tsc -p tsconfig.json` it works fine

**Comment by nchanged** [comment]
@AnasBoulmane `v3` is no longer supported. Please give `v4` a try! Let me know if you need any help
