### ISSUE TITLE
[v4] Use relative paths (or option to) for bundles

### ISSUE THREAD

**Issue by SephReed** [fuse-box/fuse-box#1723]
The following is an excerpt from `index.html`

```html
<link href="/4a9f0499-styles.css" rel="stylesheet"/>
  </head>
  <body>
    <script type="text/javascript" src="/7b74a28a-vendor.js"></script>
<script type="text/javascript" src="/775531c6-app.js"></script>
```

These paths only work if index.html is at the root of the server.  It would be nice for the paths to instead have a leading `.`  (e.g. `./4a9f0499-styles.css`) so the index.html file will load files correctly when in a subfolder.  If there are cases where this shouldn't happen, it'd be nice to have it as a config field for `webIndex`.

**Comment by SephReed** [comment]
This one is really messing me up today.  I'm having to manually fix index.html with every render.  The hashes make it impossible to just use the same index.html.

**Comment by nchanged** [comment]
Does [this](https://github.com/fuse-box/fuse-box/blob/master/src/config/IPublicConfig.ts#L35) help?

**Comment by SephReed** [comment]
This totally works, but I still kind of think it should be the default.  When wouldn't the bundle ever be in the same folder as webIndex?

I can think of many examples where webIndex is not at the root of the server though.

**Comment by nchanged** [comment]
Agreed, we should have it by default!

**Comment by SephReed** [comment]
Just tested, and the following does not do the trick:

```
webIndex: {
   publicPath  : "./"
}
```

**Comment by nchanged** [comment]
well, It should work, the problem is that it doesn't actually add `./` but just remove it all

**Comment by SephReed** [comment]
Sorry, I was wrong.  It is working.  I was looking for the `./`
