### ISSUE TITLE
V4 High RAM usage for production builds (> 1GB)

### ISSUE THREAD

**Issue by bergkvist** [fuse-box/fuse-box#1724]
### Keeping the RAM usage of the bundler well belov 1GB is advantagous for being able to bundle code in lightweight envionments.

To give some examples:

 - The cheapest droplet on DigitalOcean has 1GB of RAM ($5).

 - The free Netlify builder only has 1GB of RAM available.

In my case, my Netlify build crashes because it runs out of memory.

---
*For reference, I have included information about my environment*

#### dependencies
- "@turf/turf": "^5.1.6",
- "@types/d3": "^5.7.2",
- "@types/mapbox-gl": "^1.6.1",
- "d3": "^5.14.2",
- "d3-scale-chromatic": "^1.5.0",
- "fuse-box": "^4.0.0-next.160",
- "mapbox-gl": "^1.6.1"

#### dev-dependencies:
- "node-sass": "^4.13.0",
- "tslib": "^1.10.0",
- "typescript": "^3.7.4"

#### src/
 - index.ts
 - style.scss
 - index.html
 - data.csv

#### fuse.js
```js
const { fusebox, pluginLink } = require('fuse-box')

fusebox({
    webIndex: { template: './src/index.html' },
    entry: './src/index.ts',
    target: 'browser',
    plugins: [
        pluginLink(/\.csv/, { useDefault: true })
    ],
}).runProd({ uglify: true, target: 'ES6', screwIE: true })
```

**Comment by patrickmichalina** [comment]
This is a goal of the fuse-compiler work being done now that will ultimately replace typescript-compiler (tsc) and possibly Terser in the future.

**Comment by nchanged** [comment]
@bergkvist yep, I am aware of that issue. TypeScript is super heavy by nature, we're trying to make the builds super light.  Be patient, I was hoping we'd have alpha rolling in January!

**Comment by jeremy-coleman** [comment]
Ts likely isnt the problem, its probably node sass getting recursively bundled. U should try running node sass (or the js sass is easier) manually first and import the css instead of the scss. Even in dev , fuse box is like ~150mb rss (total allocated mem) for me. For reference , browserify is ~40, webpack ~500mb

**Comment by patrickmichalina** [comment]
I don’t use node-scss and still immense sums of memory used during production build.

**Comment by jeremy-coleman** [comment]
hmm, tsc wouldn't have that large of memory use, it must be something else

**Comment by patrickmichalina** [comment]
I see similar issues with the Angular-CLI (webpack). Big big apps this is an issue I do believe it is TSC.

**Comment by patrickmichalina** [comment]
Can not assume it’s efficient just because Microsoft devs built it ;)

**Comment by jeremy-coleman** [comment]
im not assuming, i use RSS logs with most of my builds, typescript's never been above 150mb (with type checking) on 100k+ lines. fusebox also uses transpile module , so its gonna be way less. I'm confident something else in the bundle pipeline is at fault, 1GB is a LOT

**Comment by nchanged** [comment]
Typescript eats an insane amount of memory along with ts-morph which uses the typecheker API. It has been solved already. Ts removed ) hang in there guys.

**Comment by charsleysa** [comment]
@bergkvist can you please confirm if the issue still occurs with `fuse-box@4.0.0-next.400`?
Also see [here for info on major changes](https://github.com/fuse-box/fuse-box/blob/master/docs/changelog-fuse-compiler.md)

**Comment by charsleysa** [comment]
Closed as no response received.
