### ISSUE TITLE
[v4] [docs] port field is misrepresented

### ISSUE THREAD

**Issue by SephReed** [fuse-box/fuse-box#1725]
<img width="948" alt="Screen Shot 2019-12-30 at 2 26 14 PM" src="https://user-images.githubusercontent.com/14002040/71599411-5c865500-2b10-11ea-8a86-33c064d53e25.png">

It's missing from `IPublicConfig` is all

**Comment by SephReed** [comment]
Nvm, this is a docs issue:

https://github.com/fuse-box/fuse-box/blob/master/docs/devServer.md

**Comment by charsleysa** [comment]
Closed due to inactivity.
