### ISSUE TITLE
[V4] Feat: Plugin replace regexp

### ISSUE THREAD

**Issue by SephReed** [fuse-box/fuse-box#1727]
Plugin replace options for RegExp.

Suggestion:
```
export type IPluginReplaceRegexpItem = {
  regexp: RegExp,
  replace: (match: string, ...groups: string[]) => string
}

export declare type IPluginReplaceProps = {
    [key: string]: string | number | IPluginReplaceRegexpItem;
};
```

Usage:
```
pluginReplace({
  "$foo": "bar",
  "thing": {
      regexp: /th([ia])ng/,
      replace: (match, g1) => { return g1 === "a" ? "dat thang" : "this thing"; } 
  }
})
```

**Comment by SephReed** [comment]
Found this does do regexp.  

https://github.com/fuse-box/fuse-box/blob/169169effb779bd29931fdb5ec0f951b72516539/src/plugins/core/plugin_replace.ts#L10-L14

I still think this feature would be nice for being able to supply a non-string version of regexp.  Mostly this is just a docs issue (https://github.com/fuse-box/fuse-box/blob/master/docs/plugins/pluginReplace.md)

**Comment by nchanged** [comment]
@SephReed the problem is `safeRegex` thingy here, it escapes `$`

**Comment by SephReed** [comment]
Hmm... well, I think it might be nice to be able to pass an object then.  But first, I need to figure out how to do replace normally.

**Comment by nchanged** [comment]
@SephReed do you think you can add those improvements?

**Comment by SephReed** [comment]
@nchanged May take me a bit, but given I'm the only one asking for them, that should be okay.

**Comment by charsleysa** [comment]
Closed due to inactivity.
