### ISSUE TITLE
[V4] Feat: Import raw js (no module)

### ISSUE THREAD

**Issue by SephReed** [fuse-box/fuse-box#1728]
I'm trying to reuse code from an old html/js project.

Most of the js expects a global context in which to define things.  For instance:

```js
// someTool.js
function doThing() { alert("Thing Done"); }
```

The tool above has no exports, and _I can not make it have exports without breaking the site_.  The best quick solution is to be able to import the raw js as part of the bundle. 

```ts
import from "raw::/public_html/js/someTool.js"
```

Anything imported this way could be prepended to the bundle in order of import.

**Comment by SephReed** [comment]
As an alternative, for the time being, I'm just going to modify my webIndex template to include a bunch of script paths in the `<HEAD>`.  It would be so much nicer to be able to include these files in the bundle though.

**Comment by SephReed** [comment]
I've got a better idea.

**Comment by SephReed** [comment]
Oh, it does do regexp.  Just need to update docs now.

**Comment by nchanged** [comment]
@SephReed should we keep it open? Has it been solved?

**Comment by SephReed** [comment]
I'm going to leave this open for a bit while I think about it.  I think the solution I have right now is a little bit hacky.

**Comment by charsleysa** [comment]
Closed due to inactivity.
