### ISSUE TITLE
Bundle 2nd level color is invisible on solarized dark

### ISSUE THREAD

**Issue by tyrsius** [fuse-box/fuse-box#173]
Here is a fun one, I thought these lines were just empty until this ran on my build server.

![image](https://cloud.githubusercontent.com/assets/1187432/22954631/66710ada-f2cc-11e6-84ba-367f9630cab8.png)

The color shows up under highlight, and under other themes (like solarized light). It just happens to be the background color for Solarized Dark.

**Comment by devmondo** [comment]
@tyrsius  you mean the grey color of those files ?

**Comment by tyrsius** [comment]
@devmondo Yea, notice how after the highlight the filename stops, and there is nothing below it? That filename is `util/appHistory.js`. You can't see it becuase the font color is the same as the background color. The label they are nested under, `default`, shows up fine. It is just the files nested under the project that are invisible.

**Comment by nchanged** [comment]
@tyrsius could you take a look at this [file](https://github.com/fuse-box/fuse-box/blob/master/src/Log.ts#L37) as it's so much easier for you fix it?

**Comment by tyrsius** [comment]
Today is going to be busier than expected, I will make a PR for this tonight
