### ISSUE TITLE
Uncaught Error: MobX Provider: The set of provided stores has changed

### ISSUE THREAD

**Issue by a-neumann** [fuse-box/fuse-box#1730]
I'm unable to use fuse-box v4 with [mobx-react](https://github.com/mobxjs/mobx-react)

The browsers (Firefox/Chrome, both newest) debug console prints this error:
`Uncaught Error: MobX Provider: The set of provided stores has changed`

The same project works without errors with fuse-box v3.
It's a fork of the react example.
fuse-box does not print any errors or warnings when compiling / running the _default_ task.

[Link to my repo](https://github.com/a-neumann/react-example/tree/mobx-inject-bug)

Tested with versions:
4.0.0-next.132
4.0.0-next.160

**Comment by a-neumann** [comment]
The full error message is:
```
0304e6fae_vendor.js:26453 Uncaught Error: MobX Provider: The set of provided stores has changed. See: https://github.com/mobxjs/mobx-react#the-set-of-provided-stores-has-changed-error.
    at MobXProvider (0304e6fae_vendor.js:26453)
    at renderWithHooks (0304e6fae_vendor.js:18286)
    at mountIndeterminateComponent (0304e6fae_vendor.js:20182)
    at beginWork$1 (0304e6fae_vendor.js:21040)
    at HTMLUnknownElement.callCallback (0304e6fae_vendor.js:7643)
    at Object.invokeGuardedCallbackDev (0304e6fae_vendor.js:7667)
    at invokeGuardedCallback (0304e6fae_vendor.js:7698)
    at beginWork$$1 (0304e6fae_vendor.js:24783)
    at performUnitOfWork (0304e6fae_vendor.js:24078)
    at workLoopSync (0304e6fae_vendor.js:24063)
```

The error description mobx refers to (link in console output) dosn't make sense to me because the injected dependencies (`a` and `b`) are static numeric values that are not changed/mutated at any time.

**Comment by nchanged** [comment]
@a-neumann yeah, I have just checked the reference. Are you sure that the setup is 100% correct?  Could you reproduce the exact same thing with v3? Since the dependency tree is exactly the same along with the transpilation.

**Comment by a-neumann** [comment]
@nchanged I'm pretty sure. Did not used [fuse-box/react-example](https://github.com/fuse-box/react-example) for the v3 testing. I discovered the error in my own private project after upgrading to v4.
I'll try to use the recommended decorator syntax for _mobx inject_ in react-example, just  to make sure it's not the setup...

**Comment by a-neumann** [comment]
I used the decorator syntax for inject `@inject("a", "b")` just to make sure it's not the cause. Had to add `dependencies: { include: ['tslib'] }` after i got the _Uncaught Package not found tslib_ just saying..
The mobx error still occured.

Next i downgraded my react-example fork to fuse-box v3 to make sure it dosn't have the same error. And it worked fine with fuse-box v3.

[Link to repo with fuse v3 branch](https://github.com/a-neumann/react-example/tree/mobx-inject-bugfree-v3)

**Comment by nchanged** [comment]
@a-neumann please try the latest alpha build

**Comment by a-neumann** [comment]
@nchanged you mean 4.0.0-next.165 ? I did but got the same error

**Comment by nchanged** [comment]
`4.0.0-alpha.267`

**Comment by a-neumann** [comment]
I tried `4.0.0-alpha.267` and `4.0.0-alpha.277` and also tried to disable the watch option. Both had no effect on the error. I also deleted the cache-files and disabled the cache option.

**Comment by nchanged** [comment]
just checked it with `4.0.0-alpha.277` there is one minor bug in the compiler with `process` Will fix it tomorrow, other than that it works ;-)

**Comment by a-neumann** [comment]
You are right, sorry. Had the `ReferenceError: process is not define` before crashing at the MobXProvider component (because it is the top most react component in the tree).

**Comment by a-neumann** [comment]
I reinstalled `4.0.0-next.165` today and updated `react-mobx` and `mobx` **and suddenly it worked**.

Can't figure out the reason - it might be an updated peer dependency. I pushed the updated package.json and package-lock.json in the [mobx-inject-bug](https://github.com/a-neumann/react-example/tree/mobx-inject-bug) branch if someone is interested.

**Comment by HikaruKun** [comment]
same issue for version 5.15
