### ISSUE TITLE
[v4] More direction towards tsconfig for user on-boarding?

### ISSUE THREAD

**Issue by SephReed** [fuse-box/fuse-box#1744]
The fact that `tsconfig.json` is a somewhat core part of fuse configuration is very easy to miss.  I've added it to the docs as best I can, but I forsee it still being an issue.

Any ideas on how to make this more obvious?

I'm thinking it might make sense to have this information displayed when running fuse eg:
```
⚙️ FuseBox 4.0.0-next.162
     Mode: development
     Entry: My-Project/src/index.ts
     Import Paths: My-Project/tsconfig.json    <----- this bit
     Cache: /path/to/cache
     FTL reload: enabled
```
... though this could very easily be overlooked as well.

**Comment by nchanged** [comment]
Maybe relevant: https://github.com/fuse-box/fuse-box/issues/1756

**Comment by SephReed** [comment]
I'm not sure if bundling config would make this clearer, but maybe.

**Comment by charsleysa** [comment]
Closed due to inactivity.
