### ISSUE TITLE
sales-tax npm package not working with fusebox bundler 

### ISSUE THREAD

**Issue by stijnvanlieshout** [fuse-box/fuse-box#1745]
Hi there, 
I'm trying to use the [sales-tax module](https://github.com/valeriansaliou/node-sales-tax) but cannot get it to work in my Fusebox project (it works fine in a boilerplate create-react-app project).

The functions in the sales-tax library return the wrong tax results as explained in [this issue](https://github.com/valeriansaliou/node-sales-tax/issues/18). 

Expected tax log:
```
  {
        type     : "vat",
        rate     : 22.00,  // IT VAT rate
        ...
   }
```

Actual tax log:
```
  {
        type     : "vat",
        rate     : 0,
        ...
   }
```

Something in the fusebox build process seems to be underlying this issue. 

I came to this conclusion through a simple test. I created two repos:
1. [Create react app project](https://github.com/stijnvanlieshout/create-react-app-sales-tax) --> run `npm start` visit the page and `tax` will log the expected result (22% VAT)
2. [Fusebox project](https://github.com/stijnvanlieshout/fusebox-sales-tax) --> run `npm start` visit the page and `tax` will **not** log the correct expected result (0% VAT)

Any idea why this library is working as expected in my create react app but not in my fusebox project?

**Comment by nchanged** [comment]
Hi!
v3 is no longer supported, please upgrade to v4. Read up [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

**Comment by stijnvanlieshout** [comment]
I just updated to v4 and the problem persists. 

In v3: The sales-tax lib did not break but was returning incorrect values (while if I install the lib from within a create react app project without fusebox it worked fine)

In v4: The sales-tax lib breaks on import with the error `Uncaught Package not found base64-js`. I have created [another test repo using your react template for v4](https://github.com/stijnvanlieshout/fusebox4-sales-tax) so that you can reproduce this.

Any idea how I can make it work in v4?

**Comment by nchanged** [comment]
By installing `base64-js` ?

**Comment by nchanged** [comment]
@stijnvanlieshout `fuse-box@4.0.0-next.165` this one should have them!

**Comment by stijnvanlieshout** [comment]
@nchanged I did try installing `base64-js` under `4.0.0-next.132` but that did not work. I just updated to `4.0.0-next.165` and that solved the issue. The library works as expected now. 

Thanks for the help and keep up the great work!
