### ISSUE TITLE
Concat ALL css into single file

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#175]
Hi, Am trying to use your API to bundle all CSS into a single file. I tried several apporaches along with ConcatPlugin to no avail. would you have any pointers on how to do it? Sorry to spam your issues though ;/

**Comment by tomitrescak** [comment]
e.g. I hve no ide what bundle: true in css plugin does as it seems not to produce any file.

**Comment by nchanged** [comment]
Let's move it here #177
