### ISSUE TITLE
[v4] pluginReplace does not seem to work for scss/css files

### ISSUE THREAD

**Issue by SephReed** [fuse-box/fuse-box#1754]
I'm trying to use pluginReplace to change some paths that differ between my dev and prod setups.

pluginReplace does not seem to be working for scss/css though.

I know there was an issue with this recently (https://github.com/fuse-box/fuse-box/issues/1729).  Maybe something similar is happening?

```
pluginReplace("*.scss", {
  "url": "HERE",
  // "url(\"\/": "url(\"http://localhost:9000/",  <-- what I'm actually trying to do
})
```

**Comment by SephReed** [comment]
If I simplify to this:

```
pluginReplace({
  "url": "HERE",
})
```

"url" is correctly replaced in all my js/ts files, but not in any of my css/styling

**Comment by nchanged** [comment]
Maybe [macros](https://github.com/fuse-box/fuse-box/blob/master/docs/stylesheet.md#using-macros) could help.  Needs to check double checked

**Comment by SephReed** [comment]
Macros look like they would work.  I'd rather use `pluginReplace` though, if possible.

**Comment by charsleysa** [comment]
Closed due to inactivity.
