### ISSUE TITLE
[v4] Feat/Discussion: clear cache on total reset?

### ISSUE THREAD

**Issue by SephReed** [fuse-box/fuse-box#1755]
I've had cache bugs more than a few times.  Just noticed a new one today:

https://github.com/fuse-box/fuse-box/issues/1750

I think it would make sense for caching to be cleared between fuse runs, unless specified.

Something like:
```
{ cache: true } === { cache: { enabled: true; clearOnFuseStart: true; } }
```

This would make it so the traditional method of "turn it off, then back on again" would solve any corrupt cache issues.  It would still give users the option to not clear cache on fuse start, if that's what they prefer.

**Comment by nchanged** [comment]
@SephReed I've been thinking of getting rid of the FS cache concept completely. Since we're going to have such a fast compiler, we don't really need it. On top of that, I was planning to introduce threading in the compiler that would further speed things up and compile a monstrous project in less than 5s, which is tolerable.

**Comment by SephReed** [comment]
If the caching is difficult to support, I think that might be very logical.  But if it's all the same, I think every bit helps.  Someone might be running this on a Raspberry pi.

Maybe caching could be false by default?  My worry is about how confusing it is when suddenly nothing works and reseting doesn't help.

**Comment by Teoxoy** [comment]
I also think cache should be cleared between runs and only be used and reused when in dev mode.
Basically delete the cache when you start the dev server.

**Comment by nchanged** [comment]
The new caching interface

```ts
export type ICacheStrategy = 'fs' | 'memory';
export interface ICacheProps {
  enabled?: boolean;
  root?: string;
  strategy?: ICacheStrategy;
}
```

Now we can choose `memory`, however, the module has been re-written from scratch and fully tested. So the `fs` caching should be very reliable. 

It will be available for testing very soon ;-)

**Comment by charsleysa** [comment]
Closed due to inactivity.
