### ISSUE TITLE
CSSPlugin brushup

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#177]
Based on a feedback, CSSPlugin requires a deep reconsideration.

* `write` should be deprecated (moved a hidden place with big red warning)
* `serve` should be deprecated (moved a hidden place with big red warning)

 ## Pipe option
```
CSSPlugin({ pipe : "css/bundle.css"})
```

The plugin should create a bundle group. Using `fie.createFileGroup`. This would open a flexible bundle possibilities for people. For example you have 2 processors:

```
[ SassPlugin(), CSSPlugin({ pipe : "css/bundle.css"}) ],
[ LessPlugin(), CSSResourcePlugin(), CSSPlugin({ pipe : "css/bundle.css"}) ]
```

Each of them is doing own "magic" but will result being in `css/bundle.css`, which is going to be "officially" registered in the dependency tree (and it is cool 🔥 )

`css/bundle.css` will be treated individually by any plugin that supports `Bundle Grouping`. We can introduce `CSSBundleGroupPlugin` which could accept various options of dealing with such task. (Writing it to the file system, inline bundle e.t.c)

Tell me what you think.

**Comment by devmondo** [comment]
@nchanged  do we respect order of plugins? and order of plugins when chained too ?

**Comment by devmondo** [comment]
i am really not fan of too many `CSS` plugins that do small stuff, why not have one CSS plugin that do all major stuff, so user won’t have to scratch his head about what to add, of course i am not talking about `PostCSS` plugin capabilities.

in other words for example i think we should merge `CSS Plugin` and `CSSResource Plugin`

**Comment by mitsoe** [comment]
For my use case I would like to bundle all css files including images and fonts into my app.js

**Comment by nchanged** [comment]
I will just leave it here https://github.com/fuse-box/fuse-box/issues/179

**Comment by devmondo** [comment]
@mitsoe  working on it now ;)

**Comment by nchanged** [comment]
@devmondo you sure it's not #179

**Comment by devmondo** [comment]
@nchanged  true also here he mentioned `For my use case I would like to bundle all css files including images and fonts into my app.js`

**Comment by nchanged** [comment]
https://github.com/fuse-box/fuse-box/commit/13529a8b72b2eb1d73375280a25f605830a94939

**Comment by nchanged** [comment]
# Updates in master

```
CSSPlugin({ bundle: `bundle.css` })]
```

Now in master. Will bundle all files into 1 file.

```
require("./a.css");
require("./b.css");
```

**Comment by indrimuska** [comment]
Hi guys, for that I see in the code, there's no option to bundle all CSS files in a single output file, isn't it?

**Comment by cellog** [comment]
The bundling is done in transformGroup in the CSSPlugin

**Comment by nchanged** [comment]
@indrimuska this functionality is not yet released. Coming with the next one.

**Comment by indrimuska** [comment]
Thank you @nchanged. However, as you can see from the screenshot above, in the master I don't see any option to save the CSS bundle into a file in the file system. Am I missing something?

**Comment by nchanged** [comment]
@indrimuska it's happening in [tranformGroup](https://github.com/fuse-box/fuse-box/blob/master/src/plugins/CSSplugin.ts#L80)

**Comment by indrimuska** [comment]
Ok, thank you. Can you help please help me understand how to fire that method?
After debugging my environment I see that `CSSPluginClass::transformGroup` is never called, this is my fuse.js file:

```javascript
const fuseBox = fsbx.FuseBox.init({
    cache: false,
    homeDir: 'src/',
    sourceMap: {
        bundleReference: 'app.js.map',
        outFile: './dist/app.js.map',
    },
    outFile: './dist/app.js',
    plugins: [
        fsbx.TypeScriptHelpers(),
        [ /styles\/.+\.css/, fsbx.CSSPlugin({ bundle: 'app.css' }) ]
    ]
});

fuseBox.bundle('>main.ts');
```

I've also tried these configurations:

```javascript
[ /styles\/.+\.css/, fsbx.ConcatPlugin(), fsbx.CSSPlugin({ bundle: 'app.css' }) ]
```
```javascript
[ /styles\/.+\.css/, fsbx.CSSPlugin({ bundle: 'app.css' }) ],
fsbx.ConcatPlugin()
```

**Comment by nchanged** [comment]
```
plugins: [
        fsbx.TypeScriptHelpers(),
        fsbx.CSSPlugin(), // this one actually captures the app.css
        [ /styles\/.+\.css/, fsbx.CSSPlugin({ bundle: 'app.css' }) ]
    ]
```

Transform group happens later. `app.css` is added to the dependency tree. So imagine a real file app.css with won't get matched by  /styles\/.+\.css/ that's why you need to add a generic CSSPlugin

**Comment by nchanged** [comment]
https://github.com/fuse-box/fuse-box/blob/master/test/css_plugin.js#L23
More tests are coming

**Comment by cellog** [comment]
That double call of CSSPlugin is... unintuitive

Calling CSSPlugin to make a bundle sounds like a job for a BundlePlugin 
instead, as I was hinting at in our other conversation.

**Comment by nchanged** [comment]
@cellog doesn't increase complexity? Besides that's how chaining works, feel free to suggest your solution. We can chat on gitter you like.

**Comment by indrimuska** [comment]
Sorry, even following your instructions I'm am not able to bundle such CSS file in `dist` folder.
Here it is my very basic app: [**angular2-test-app.zip**](https://github.com/fuse-box/fuse-box/files/786985/angular2-test-app.zip), could you please check it out?

**Comment by nchanged** [comment]
Right, this version is not released yet. You have to wait for `1.1.119` https://github.com/fuse-box/fuse-box/milestone/5

**Comment by nchanged** [comment]
Finally, it's here fully covered!
https://github.com/fuse-box/fuse-box/blob/master/test/css_plugin.js

**Comment by indrimuska** [comment]
@nchanged just tried the [latest release](https://github.com/fuse-box/fuse-box/releases/tag/v1.3.119) but I am not able to make this feature work.
Can you please help me figure out what I'm missing?

zip file here: [angular2-test-app.zip](https://github.com/fuse-box/fuse-box/files/790283/angular2-test-app.zip)

After running `npm i && npm start`, no file css will be generated in the `dist` folder. :weary:

**Comment by nchanged** [comment]
```
[ /styles(\/|\\).+\.css/, fsbx.CSSPlugin({ group: 'app.css', outFile : "dist/app.css" }) ],
```
It's not documented yet. But will be soon.

**Comment by indrimuska** [comment]
Does it really work for you?
Could you please send me the whole fixed project you've tested?

**Comment by nchanged** [comment]
I don't really know what you want to achieve. Have you cleaned the cache?

**Comment by indrimuska** [comment]
Sure, even with cache disabled I don't see the CSS bundle file in the dist folder.
My scope is to have only one css file `dist/app.css` for all the stylesheets in `src/styles` folder.

**Comment by nchanged** [comment]
DId you copy exactly like i said? cuz i see it there!

**Comment by nchanged** [comment]
[angular2-test-app-2.zip](https://github.com/fuse-box/fuse-box/files/790417/angular2-test-app-2.zip)

**Comment by indrimuska** [comment]
Wow, same source code, same fuse.js file, different result.
You're version seems to compile very well, instead mine doesn't!

![image](https://cloud.githubusercontent.com/assets/1561134/23172177/3258f472-f855-11e6-84b3-8ffadf97ddaa.png)

I will investigate on this.. thank you for the support. :)

**Comment by nchanged** [comment]
you sure you have 119 installed? Can you nuke everything

**Comment by indrimuska** [comment]
Yes, tried but with no success.

[angular2-test-app-working.zip](https://github.com/fuse-box/fuse-box/files/790769/angular2-test-app-working.zip)
[angular2-test-app-not-working.zip](https://github.com/fuse-box/fuse-box/files/790768/angular2-test-app-not-working.zip)

For me these project are identical!

**Comment by devmondo** [comment]
@indrimuska 
i just downloaded the not working zip and ran it, and i see it working
![image](https://cloud.githubusercontent.com/assets/1266367/23174759/df672546-f876-11e6-8160-9ba1b0d12c98.png)

**Comment by indrimuska** [comment]
It's absolutely unbelievable! If I download the zip and compile it the file appears.
Ok, let's end up the discussion with an unsolved question.
Thank you again guys! :)

**Comment by devmondo** [comment]
@indrimuska  maybe u installed fuse globally, or have some cahe somewhere, or your system is screwed up, happens to all of us :)

**Comment by indrimuska** [comment]
I have not installed Fuse globally. Anyway, can fuse cache something in a folder different than `.fusebox`? Can fusebox cache something even if the cache: false property is set?

**Comment by devmondo** [comment]
@indrimuska sometimes cache misbehaves and you are right we only store it `.fusebox`

**Comment by indrimuska** [comment]
FINALLY GOT IT!
This was not caused by caching system or something similar, it's a more dangerous issue!
It's not just related to this thread, but to all plugins in the case the users makes use of RegExp before applying each plugin itself.
To explain it better I'm going to open a new issue.
