### ISSUE TITLE
Babel plugin output is not used

### ISSUE THREAD

**Issue by leops** [fuse-box/fuse-box#178]
I'm currently trying to convert an existing library from webpack to fuse-box, but I can't get Babel to run.

This is the build script I'm using:
```js
#!/usr/bin/env node

const path = require('path');
const {
    FuseBox,
    BabelPlugin,
    CSSPlugin,
} = require('fuse-box');

const config = {
    homeDir: path.resolve(__dirname, 'src'),

    plugins: [
        CSSPlugin(),
        BabelPlugin({
            test: /\.jsx?$/,
            config: {
                plugins: ['inferno'],
                presets: [
                    ['env', {
                        modules: 'commonjs',
                        targets: {
                            browsers: 'last 2 versions',
                            android: '4.4',
                            ios: 8,
                        },
                    }],
                ],
            },
        }),

    ],

    outFile: path.resolve(__dirname, 'dist', 'bundle.js'),
};

FuseBox.init(config).bundle('>index.js');
```

My `devDependencies`:
```json
{
    "babel-core": "^6.23.1",
    "babel-generator": "^6.23.0",
    "babel-plugin-inferno": "^1.7.0",
    "babel-preset-env": "^1.1.8",
    "babylon": "^6.15.0",
    "fuse-box": "^1.3.114"
}
```

And a sample from the output:
```js
___scope___.file("index.js", function(exports, require, module, __filename, __dirname){ 
var process = require("process");
import Inferno from 'inferno';
import { Provider } from 'inferno-redux';

import App from './components/app';
import { prepareState } from './state';
import createStore from './store';

export class Container {
    constructor(element, data, options = {}) {
        try {
            this.element = element;
            this.bootstrap(data, options);
        } catch(err) {
            console.error(err);
        }
    }

    bootstrap(data, options) {
        const state = prepareState(options, data);
        this.store = createStore(state);

        Inferno.render(
            <Provider store={this.store}>
                <App />
            </Provider>,
            this.element
        );
    }
}

});
```

Running Babel alone yields the expected result, with the imports replaced with `require` calls and the class / JSX correctly transpiled. Am I missing something obvious here ?

**Comment by nchanged** [comment]
Ok, it might be related to caching if you added the `BabelPlugin` afterwards. You can try removing `.fusebox` folder. It should help!

**Comment by leops** [comment]
Clearing the cache is one of the first things I tried, but it doesn't solve the problem.

**Comment by nchanged** [comment]
How about removing your `test`.
Does this work for you? https://github.com/fuse-box/react-example

Plugins are fine?

**Comment by leops** [comment]
Removing the `test`property changes nothing, as does renaming all the source files to `.jsx`.
(The last part is something I tried to match the react example, which works perfectly fine.)
The CSS plugins seems to be working correctly, as I can see my stylesheets in the final bundle.

**Comment by nchanged** [comment]
Hm, clearly it's related to Babel. `.babelrc` maybe it's conflicting?!

**Comment by leops** [comment]
I did remove my `.babelrc` file and inlined it in the configuration file, again this solved nothing. A quick check confirmed I have no other Babel related file upper in the filesystem.
Additionally, removing the `inferno` plugin makes the bundler crash with babylon complaining about the JSX so this config is at least used somewhere.

**Comment by nchanged** [comment]
Oh. I think I got it. Related to this issue #155 
https://github.com/fuse-box/react-example/blob/master/.babelrc#L2 should solve it, and I think I should start fixing it this instance.

**Comment by leops** [comment]
Ok, adding the `sourceMaps` property fixes it. Thanks !

**Comment by nchanged** [comment]
No problem, i will add this bug to the milestone

**Comment by nchanged** [comment]
#180
