### ISSUE TITLE
[v4] Support for Yarn v2 plug'n'play

### ISSUE THREAD

**Issue by mekwall** [fuse-box/fuse-box#1786]
The current module resolver doesn't support [Yarn v2](https://next.yarnpkg.com) that uses it's own [Plug'n'play system](https://next.yarnpkg.com/features/pnp) to install and resolve modules, which is similar to how [pnpm](https://pnpm.js.org) does it, and which also doesn't seem to be supported according to #1006.

I am guessing fuse-box need something similar to [pnp-webpack-plugin](https://github.com/arcanis/pnp-webpack-plugin). Perhaps resolvers should be part of the plugin system as it is with Webpack?

**Comment by nchanged** [comment]
That looks good ! We are in the middle of a huge refactor ATM (branch grand-refactor)

I would include this feature by default . If you want to help with it, please pitch in )

**Comment by mekwall** [comment]
> That looks good ! We are in the middle of a huge refactor ATM (branch grand-refactor)
> 
> I would include this feature by default . If you want to help with it, please pitch in )

I can give it a shot. Do you want me to base it off of the `grand-refactor` branch?

**Comment by nchanged** [comment]
@mekwall yeah! that's the one we're working on

**Comment by mekwall** [comment]
Closing this since it was added with #1788
