### ISSUE TITLE
CSSResourcePlugin does not bundle Fonts

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#179]
If anyone wants to fix it, some place [here](https://github.com/fuse-box/fuse-box/blob/master/src/plugins/CSSResourcePlugin.ts#L123)

**Comment by mitsoe** [comment]
https://github.com/247even/gulp-cssfont64
does something similiar

**Comment by nchanged** [comment]
Great, should be an easy fix

**Comment by devmondo** [comment]
@mitsoe working on it now ;)

**Comment by nchanged** [comment]
Good job @devmondo

**Comment by mitsoe** [comment]
Too fast :)

**Comment by devmondo** [comment]
@mitsoe  the Fuse Spirit :)
