### ISSUE TITLE
v4 fuse-box ignores 'browser' entrypoint in grandchild dependencies

### ISSUE THREAD

**Issue by martaver** [fuse-box/fuse-box#1791]
Heya, using 4.0.0-next.165 over here.

Been working on an issue with ´@splitsoftware/splitio´ where fuse-box is bundling node code, even though ´target: 'browser'´ is set.

In ´splitio´, their package is set up as a monorepo, with many sub-packages, some of which contain a separate entry point based on whether we have a ´browser´or ´node´ environment. 

You can find an example of a sub-package here, check out its ´package.json´: https://github.com/splitio/javascript-client/tree/development/src/client

I have an issue with ´@splitsoftware/splitio´ here: https://github.com/splitio/javascript-client/issues/355

It seems like ´fuse-box´ is loading these sub-packages through ´main´ resulting in ´nodejs´ code being loaded in the browser.

Fuse should be loading the deps from the ´browser´ entry point whenever available across the hierarchy.

**Comment by charsleysa** [comment]
@Martaver can you please confirm if the issue still occurs with `fuse-box@4.0.0-next.400`?
Also see [here for info on major changes](https://github.com/fuse-box/fuse-box/blob/master/docs/changelog-fuse-compiler.md)

**Comment by Martaver** [comment]
Yeah, it's still trying to load code that depends on 'dns' from the main entry, instead of the 'browser' entry.

**Comment by charsleysa** [comment]
@Martaver can you please provide a minimal reproduction?

**Comment by charsleysa** [comment]
Closed as no response received.

**Comment by Martaver** [comment]
Hey don't close this. This is an important bug as it concerns parity with webpack.

As of 411, this is still an issue. Repro is here: https://github.com/Martaver/react-example/tree/split-repro

If you follow the deps of packages in '@splitsoftware/splitio' you will see 'browser' entry points in their package.json files, but fuse-box ignores them loading main instead. This results in incorrect references to node packages in browser.

**Comment by nchanged** [comment]
@Martaver did you try `@next` ?

**Comment by Martaver** [comment]
Repro is with next.411

**Comment by nchanged** [comment]
@warrenfalk do you mind taking a look at this ?

**Comment by charsleysa** [comment]
Closed due to inactivity.
