### ISSUE TITLE
Feat: Auto generated webindex docs hint

### ISSUE THREAD

**Issue by SephReed** [fuse-box/fuse-box#1792]
If you have 
```{ webIndex: true }```

An index.html file is automatically generated.  This is generally very useful, but figuring out that it's actually a preset template requires searching the docs in the correct way.

Simple helper idea: Add an html comment to the source code stating "This is a preset template, and you can customize this html code.  Check out linkTo.docs/webIndex"

Then when new users first look into the generated index.html file, they'll immediately learn how to customize it (ie, don't modify its text).

**Comment by nchanged** [comment]
@SephReed wanna add it yourself in`grand-refactor` branch? ;-)

**Comment by SephReed** [comment]
I do, but I might not get around to it.  I'm juggling.  This might also be a good one for anyone looking for an easy win.

**Comment by charsleysa** [comment]
Closed due to inactivity.
