### ISSUE TITLE
Is it possible support React Fast Refresh?

### ISSUE THREAD

**Issue by foisonocean** [fuse-box/fuse-box#1798]
reference:
https://www.youtube.com/watch?v=Mjrfb1r3XEM
https://github.com/facebook/react/issues/16604#issuecomment-528663101

React Fast Refresh in an official HMR tool for React from React team, which can significantly improve the developer experience for React developers, so I really hope fuse-box can integrate with this feature.

BTW it might be harder for fusebox to integrate this than other bundlers, since React Fast Refresh requires a babel plugin but fusebox is using TypeScript as transformer instead of babel, so rewriting the babel plugin to a typescript custom transformer is necessary.

**Comment by nchanged** [comment]
@foisonocean oh yes. the new HMR plugin coming to fusebox, very soon. In the meantime, you could try the [demo](https://github.com/fuse-box/sandbox/tree/master/hmr-plugin-example)

If you want to try to implement a plugin - please do so. The documentation for the HMR plugins is coming next week.

Shortly, here is a simple [hmr plugin](https://github.com/fuse-box/sandbox/blob/master/hmr-plugin-example/src/hmr.ts)

Here is the [helper](https://github.com/fuse-box/fuse-box/blob/grand-refactor/modules/fuse-box-hot-reload/clientHotReload.ts#L31)

You can do many things at runtime, as well as port the babel plugin to fuse-compiler. Here is the [JSXTransformer](https://github.com/fuse-box/fuse-box/blob/grand-refactor/src/compiler/transformers/shared/JSXTransformer.ts) that is used for typescript and js files accordingly. 

The current branch in development is `grand-refactor` The latest build is `4.0.0-alpha.304`

Please note, there are breaking changes, which I will be documenting soon. So follow this [fuse.ts](https://github.com/fuse-box/sandbox/blob/master/hmr-plugin-example/fuse.ts)

**Comment by nchanged** [comment]
@foisonocean and let me know if you need any help. I am very interested in the subject too, And I want this HMR plugin implemented. All I know for sure, the latest FuseBox is capable of this, and we can make a nice plugin for fuse `pluginReactHMR()` that will handle everything. All the user will need to do it is add it to the config.

**Comment by Martaver** [comment]
Yeah this is really important... fuse-box / fast refresh combo will be fearsome. It will bring the dev experience into line with flutter.

**Comment by bergkvist** [comment]
Would this be something that would work together with FTL reloads in fuse-box? The developer experience would be absolutely amazing.

**Comment by charsleysa** [comment]
@foisonocean can you please confirm if the issue still occurs with `fuse-box@4.0.0-next.400`?
Also see [here for info on major changes](https://github.com/fuse-box/fuse-box/blob/master/docs/changelog-fuse-compiler.md)

**Comment by nchanged** [comment]
@charsleysa would be nice to actually implement this one ;-)

**Comment by foisonocean** [comment]
@charsleysa I upgrade fusebox to v4.0.0-next.403, and it seem there are still some bugs in this version that I can't run my simple todo list app, so I can not confirm whether the new HMR works. I'll open a new issue to describe bugs I faced in the v4.0.0-next.403

**Comment by charsleysa** [comment]
Closed due to inactivity.
