### ISSUE TITLE
Minor issue: shell signals

### ISSUE THREAD

**Issue by paxperscientiam** [fuse-box/fuse-box#1799]
FB does not emit exit codes other than "0".  At the very least, FB should return an exit code of "1" when exiting due to error.

**Comment by charsleysa** [comment]
@paxperscientiam can you please confirm if the issue still occurs with `fuse-box@4.0.0-next.400`?
Also see [here for info on major changes](https://github.com/fuse-box/fuse-box/blob/master/docs/changelog-fuse-compiler.md)

**Comment by paxperscientiam** [comment]
will do

**Comment by paxperscientiam** [comment]
@charsleysa , still not there. 
```typescript
import { fusebox } from 'fuse-box';
fusebox({
    target: 'browser',
    entry: 'src/index.tsx',
    webIndex: {
        template: 'src/index.html',
    }
}).runProd()
```

with random junk in src/index.tsx

So, the expected error message is spit out, but the shell error code is still 0.

I can look into it.
BTW, just tested with 4.0.0-next.409

**Comment by charsleysa** [comment]
Closed due to inactivity.
