### ISSUE TITLE
Global variable does not work correctly in v4 production

### ISSUE THREAD

**Issue by bogdandv** [fuse-box/fuse-box#1801]
Behaviour:
Trying to bundle a draft-js dependency (into vendor).
Said bundle uses the "global" variable

In fusebox v4 development mode global is initialized with window: 

```
// Patching global variable
if ($isBrowser) {
  g['global'] = $isWebWorker || $isServiceWorker ? {} : window;
}
```
In production mode these types of code get generated:
```

$fsx.f[441] = function(module, exports){
"use strict";
var global = {};
```
and then  `var selection = global.getSelection();` throws an error. If I initialise global = window, and remove the `var global = {}` lines from the vendor.js code works properly.

**Comment by nchanged** [comment]
thanks! This has been fixed in the latest alpha. I will be posted a list of breaking changes shortly for you to migrate.

**Comment by bogdandv** [comment]
problem has been fixed in the latest version. Thank you!
