### ISSUE TITLE
@font-face src url not importing properly

### ISSUE THREAD

**Issue by sulf** [fuse-box/fuse-box#1816]
Here's an example of a .css file:

```
@font-face {
  font-family: 'EncodeSans';
  src: url("./fonts/EncodeSans-Regular.ttf");
  font-weight: normal;
  font-style: normal;
}
```

I see that fusebox properly copies the ttf file over, but I'm getting this error:
<img width="943" alt="image" src="https://user-images.githubusercontent.com/42768/75470977-22da9a80-5957-11ea-957c-9814ffbb4299.png">

Weirdly though:
<img width="406" alt="image" src="https://user-images.githubusercontent.com/42768/75471009-2f5ef300-5957-11ea-8df7-a237c058e178.png">

**Fusebox version:** ^4.0.0-next.153

## Fusebox config:
```
{
    output: `dist/renderer/${name}/$name`,
    target: 'electron',
    homeDir: 'src/renderer',
    entry: `windows/${name}/index.tsx`,
    dependencies: { include: ['tslib'] },
    logging: { level: 'succinct' },
    webIndex: {
      publicPath: './',
      template: `src/renderer/windows/${name}/index.html`,
    },
    cache: {
      enabled: false,
      root: `.cache/${name}Window`,
    },
    devServer: {
      httpServer: false,
    },
    hmr: true,
    plugins: [
      pluginLink(/.+\.wav/),
      pluginLink(/.+\.weba/),
      pluginLink(/.+\.webm/),
      pluginJS(),
    ],
  }
```

**Comment by nchanged** [comment]
You should set resources config to adjust public paths it will work after that

**Comment by charsleysa** [comment]
@sulf can you please confirm if the issue still occurs with `fuse-box@4.0.0-next.400`?
Also see [here for info on major changes](https://github.com/fuse-box/fuse-box/blob/master/docs/changelog-fuse-compiler.md)

**Comment by sulf** [comment]
The resource config actually fixed the issue. This can be closed.
