### ISSUE TITLE
Incorrect bundling of native module

### ISSUE THREAD

**Issue by starsolaris** [fuse-box/fuse-box#1822]
fuse-box bundle native .node files as text to resulted vendor.js
I am skip those files with next plugin:
```
ctx.ict.on('module_init', (props) => {
 const module = props.module;
 if (module.extension === '.node') {
  module.contents = "";
 }
});
```

in alpha.311 and later i cannot prevent bundling files with this functionality

**Comment by charsleysa** [comment]
@starsolaris version `4.0.0-alpha.326` now supports bundling `.node` files
