### ISSUE TITLE
Not loading template in WebIndexPlugin

### ISSUE THREAD

**Issue by l4nn1312** [fuse-box/fuse-box#1826]
I'm trying to load a template into WebIndexPlugin but it appears to not be recognizing the configuration because it isn't loading the index.html file I have in my `client` directory. Do you have any advice here?

**Comment by nchanged** [comment]
hey @l4nn1312 please try `v4`.  [This](https://github.com/fuse-box/fuse-box/blob/grand-refactor/playground/react/fuse.ts#L19) is how it looks in `4.0.0-alpha.321` which is about to be merged to master
