### ISSUE TITLE
[v4] .sass files treated as .scss

### ISSUE THREAD

**Issue by bsl-zcs** [fuse-box/fuse-box#1834]
```
body
  color: red
```

`❌ Invalid CSS after "b": expected 1 selector or at-rule, was "body" in ...`

tried to pass `indentedSyntax: true` to `pluginSass` - it doesn't help

**Comment by gleba** [comment]
i have same message with **FuseBox 4.0.0-next.413**

please fix support **.sass** files

**Comment by gleba** [comment]
![image](https://user-images.githubusercontent.com/1052840/80565019-1a0a5180-89f8-11ea-991a-ddb96d5babfa.png)
indentedSyntax absolutely unsupported now

**Comment by gleba** [comment]
option indentedSyntax is really missed in node-sass render function

**Comment by gleba** [comment]
fixed in **^4.0.0-next.430**
@bsl-zcs @charsleysa 
now u can resolve/close issue
