### ISSUE TITLE
[v4] ~ (node_modules alias) in SASS doesn't work

### ISSUE THREAD

**Issue by bsl-zcs** [fuse-box/fuse-box#1835]
```
@import "~bulma/bulma.sass";
```

`❌ File to import not found or unreadable: ~bulma/bulma.sass.`

it works in 3.7

**Comment by bsl-zcs** [comment]
my bad, just noticed that i'm testing not the latest version (because `-next.165` is lexicographically greater than `-alpha.328` and `"^4.0.0-alpha.328"` actually fetches `@next`).

in latest alpha it works.  sorry for disinformation.

**Comment by gleba** [comment]
in `FuseBox 4.0.0-next.415` it breaks again
`  ❌ Invalid CSS after "*": expected 1 selector or at-rule, was "*" in /mnt/a/lo
cus/js/src/front/pages/root.sass`

**Comment by nchanged** [comment]
@gleba there were no changes related to CSS recently.  Cache?

**Comment by chumbalum** [comment]
I'm having the same problem with fuse-box 4.0.0-next.430.

**index.tsx**
```
import "./styles/app.scss";
```

**app.scss - not working**
```
@import "~bootstrap/scss/bootstrap.scss";

File to import not found or unreadable: ~bootstrap/scss/bootstrap.scss. in D:\Internet\Development\git\GPYO\web\src\styles\app.scss
```


**app.scss - working**
```
@import "node_modules/bootstrap/scss/bootstrap.scss";
```

Fusebox Cache is disabled

**Comment by nchanged** [comment]
You need to add macros option to stylesheet field, and replace that . Mind the trailing slash

**Comment by chumbalum** [comment]
Thanks for the hint. With the following config, it's working. Not very intuitive, though. I didn't find a documentation on that and in older fusebox, tilde was working out of the box.

```
fusebox({
    entry: "src/index.tsx",
    target: "browser",
    cache: true,
    webIndex: {
        template: "src/index.html"
    },
    stylesheet: {
        macros: {
            "~": path.join(__dirname, "node_modules/")
        }
    }
}).runDev({
    bundles: {
        distRoot: "../app/dist"
    }
});
```

**Comment by avizcaino** [comment]
Sorry to reopening the topic but I'm having trouble with this in fuse 4.0.0-next.439. This is my config:

```
import { fusebox, pluginSass, pluginLink, pluginReplace } from 'fuse-box';
import { join, resolve } from 'path';
// import { runUpdateSimulation } from './simulate';

const workspaceRoot = join(__dirname, '../..');
console.log('Workspace Root:', workspaceRoot);

// set AUTOMOD to true to automatically update some files to trigger the watcher
// runUpdateSimulation(!!process.env.AUTOMOD);

export const fuse = (entry: string, baseStyles: string, webIndex: string, devServer: boolean) =>
  fusebox({
    cache: false,
    compilerOptions: {
      tsConfig: 'tsconfig.json',
    },
    devServer,
    hmr: true,
    entry,
    target: 'browser',
    watcher: {
      root: [workspaceRoot],
    },
    stylesheet: {
      macros: {
        '~': join(__dirname, 'node_modules/'),
      },
      autoImport: [
        { file: baseStyles, capture: 'packages/*/src' },
      ],
    },
    plugins: [
      pluginLink(/.+\.png/, { useDefault: true }),
      pluginLink(/.+\.svg/, { useDefault: true }),
    ],
    webIndex: { template: webIndex },
  });
```

And this is my error:
```
@lerna-fuse/app:   ❌ File to import not found or unreadable: ~@uxland/style-utilities/material-colors.scss. in /Users/alexvizcaino/Documents/dev/lerna-fuse/packages/app/src/components/shell/styles.scss 
```

Any clue what I'm doing wrong?

**Comment by nchanged** [comment]
@avizcaino 
```
 macros: {
        '~': join(__dirname, 'node_modules/') + "/",
      }
```

path.join removes the slash at the end. You need to add it manually

**Comment by avizcaino** [comment]
@nchanged not working either... 😞

**Comment by nchanged** [comment]
It really should, I have a similar setup in some project. Debug the output path and make sure it's reachable.

**Comment by avizcaino** [comment]
@nchanged my bad, the problem was that my fuse config is not at the root of the project but in another directory, so the final path after the replace was not pointing correctly to `node_modules`.

Thanks!
