### ISSUE TITLE
consider switching to dart sass from node-sass

### ISSUE THREAD

**Issue by bsl-zcs** [fuse-box/fuse-box#1836]
for several reasons:

1. the dart sass is the primary implementation now and other implementations are lagging behind on latest features support (such as `@use` and new module system)
1. node-sass requires a native binary, which has to be downloaded (if the current environment fits in a limited set of platform/node version/node-sass version combinations of their pre-built binaries) or built locally - that's problematic on windows, docker containers, etc.

**Comment by patrickmichalina** [comment]
https://www.npmjs.com/package/sass

**Comment by patrickmichalina** [comment]
`This package is a distribution of Dart Sass, compiled to pure JavaScript with no native code or external dependencies. It provides a command-line sass executable and a Node.js API.`

**Comment by charsleysa** [comment]
Closed due to inactivity.

**Comment by RedMser** [comment]
Not sure why this was closed without discussion.
I took a very superficial look at the problem (I only learned about fuse-box today), and here's how you can hack it together:

- Replace references to `node-sass` with `sass` in `node_modules/fuse-box/plugins/core/plugin_sass.js`
- Replace references to `node-sass` with `sass` in `node_modules/fuse-box/stylesheet/sassHandler.js`
- Uninstall `node-sass` and instead install `sass` in your project

Then try running the dev server. Changes to .scss files should build as expected! Didn't check if this works for all cases, but this could be a good starting point for a PR.

**Comment by nchanged** [comment]
Could you submit a PR yourself? That would be a real help!

**Comment by jpike88** [comment]
fixed and merged
