### ISSUE TITLE
sourcemaps have some minor bugs

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box#1838]
Code sometimes does not stop on the correct line.
Like on the picture below it should have stopped on the debugger statement
![image](https://user-images.githubusercontent.com/2901416/76160100-540d5480-6127-11ea-8a2e-30d31243d528.png)

**Comment by charsleysa** [comment]
@vegarringdal can you please confirm if the issue still occurs with `fuse-box@4.0.0-next.400`?
Also see [here for info on major changes](https://github.com/fuse-box/fuse-box/blob/master/docs/changelog-fuse-compiler.md)

**Comment by vegarringdal** [comment]
@charsleysa @nchanged 
yes still an issue.

used the sandbox and updated fusebox only

![image](https://user-images.githubusercontent.com/2901416/76322906-3fc28680-62e4-11ea-9395-8b68f7a8a11e.png)

![image](https://user-images.githubusercontent.com/2901416/76322835-26b9d580-62e4-11ea-88b9-34d1d298ab2e.png)

**Comment by charsleysa** [comment]
cc @nchanged
