### ISSUE TITLE
css bundleling settings

### ISSUE THREAD

**Issue by bogdandv** [fuse-box/fuse-box#1847]
this:
```
let { fusebox, sparky, pluginReplace } = require("fuse-box");

class Context {
    runServer;
    getConfig = (useSourceMap, watch) =>
        fusebox({
            target: "browser",
            entry: "ClientApp2/boot-client.tsx",
            webIndex: {
                target: "wwwroot",
            },
			//hmr : { plugin : "src/hmr.ts"},
            tsConfig: 'tsconfig.json',
            cache: true,
            devServer: false,
            useTypescriptCompiler: true,
            sourceMap: useSourceMap,
            watcher: watch,
            dependencies: {
                include: ['tslib'],
            }
        });
}

task("build:prod", async ctx => {
    ctx.runServer = false;
    const fuse = ctx.getConfig(false, false);
    await fuse.runProd({
		bundles: {
			distRoot: 'wwwroot',
			app: { path: 'app.js'},
			vendor: { path: 'vendor.js'},
			css: {path: 'styles.css' }
		},
        uglify: false,
        screwIE: true
    });
});
```
does not bundle the css as expected.  (it does not create a styles.css file)
Am I doing something wrong?

**Comment by nchanged** [comment]
It's odd,there are integration tests for it. 

Remove dependencies field to start with, and css option it should pick it up automatically. Then import your css using a normal import it should work

**Comment by charsleysa** [comment]
@bogdandv can you please create a minimal reproduction?

**Comment by bogdandv** [comment]
Created a minimal reproduction
[Example.zip](https://github.com/fuse-box/fuse-box/files/4317155/Example.zip)

Using yarn to run:
yarn install
yarn build:prod

Expected behaviour: create in wwwroot `app.js`,` vendor.js`,` styles.css` and `index.html`
a styles folder is being created that contains `styles.14ff9eca.css` (the correct style)

yarn version v1.12.3
node version v12.14.0

**Comment by Gouigouix** [comment]
Hello,
I have the same problem with the version `4.0.0-next.409` of fuse-box.

Here is the error I have below when I use a font in `TTF` format, by the way I have no problem with the `WOFF` format!

```
  ❌ `ttf` contains an unsupported font file format. Must be `woff` and/or `woff2`. in C:\workspace\project\src\styles\index.scss 
```

Thx

**Comment by nchanged** [comment]
this has been fixed

**Comment by bogdandv** [comment]
In version 420 this issue is not fixed. Is it fixed in some other version? Is the setup in my reproduction wrong?

**Comment by nchanged** [comment]
it's `styles` and not `css`

**Comment by bogdandv** [comment]
Issue solved. Thank you!
