### ISSUE TITLE
Broken compatibility with Lit-element

### ISSUE THREAD

**Issue by hollowcat** [fuse-box/fuse-box#1849]
_Originally posted by @hollowcat in https://github.com/fuse-box/fuse-box/issues/1556#issuecomment-597111305_

Steps to reproduce:
1. Clone https://github.com/fuse-box/react-example/tree/v4 and `npm install lit-element`
2. Add my-element.ts under /src with the following code

```
import { LitElement, html, customElement, property } from 'lit-element';

@customElement('my-element')
export class MyElement extends LitElement {

  @property()
  foo = 'foo';

  render(){
    return html`<p>${this.foo}</p>`;
  }
}
```

(as in [docs](https://lit-element.polymer-project.org/guide/start))

3. Add this line to src/index.tsx: `import './my-element.ts';`

This issue emerged somewhere between fusebox versions alpha.278 and alpha.304.

**TypeError: Object.assign(...) is not a function** in modern FF and chrome.

**Comment by nchanged** [comment]
The bug has been confirmed and fixed in `fuse-box@4.0.0-next.406`

Let me know if you have any more issues!
