### ISSUE TITLE
`xxx.default` is not a function

### ISSUE THREAD

**Issue by foisonocean** [fuse-box/fuse-box#1853]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/15059605/76520154-56600d80-649d-11ea-986a-f0e5dd8b196d.png">
<img width="591" alt="image" src="https://user-images.githubusercontent.com/15059605/76520192-6b3ca100-649d-11ea-9818-300c17172990.png">

I set a breakpoint here in the chrome devtools, and found `inheritsLoose_1` is already a function, so call `inheritsLoose_1.default` would cause an error.

Source (`@emotion/core@10.0.28`): 

```js
// node_modules/@emotion/core/dist/core.browser.esm.js
import _inheritsLoose from '@babel/runtime/helpers/inheritsLoose';
import { createContext, forwardRef, createElement, Component } from 'react';
import createCache from '@emotion/cache';
import { getRegisteredStyles, insertStyles } from '@emotion/utils';
import { serializeStyles } from '@emotion/serialize';
import { StyleSheet } from '@emotion/sheet';
import css from '@emotion/css';
export { default as css } from '@emotion/css';

var EmotionCacheContext = createContext( // we're doing this to avoid preconstruct's dead code elimination in this one case
// because this module is primarily intended for the browser and node
// but it's also required in react native and similar environments sometimes
// and we could have a special build just for that
// but this is much easier and the native packages
// might use a different theme context in the future anyway
typeof HTMLElement !== 'undefined' ? createCache() : null);
var ThemeContext = createContext({});
var CacheProvider = EmotionCacheContext.Provider;

var withEmotionCache = function withEmotionCache(func) {
  var render = function render(props, ref) {
    return createElement(EmotionCacheContext.Consumer, null, function (cache) {
      return func(props, cache, ref);
    });
  }; // $FlowFixMe


  return forwardRef(render);
};

// thus we only need to replace what is a valid character for JS, but not for CSS

var sanitizeIdentifier = function sanitizeIdentifier(identifier) {
  return identifier.replace(/\$/g, '-');
};

var typePropName = '__EMOTION_TYPE_PLEASE_DO_NOT_USE__';
var labelPropName = '__EMOTION_LABEL_PLEASE_DO_NOT_USE__';
var hasOwnProperty = Object.prototype.hasOwnProperty;

var render = function render(cache, props, theme, ref) {
  var cssProp = theme === null ? props.css : props.css(theme); // so that using `css` from `emotion` and passing the result to the css prop works
  // not passing the registered cache to serializeStyles because it would
  // make certain babel optimisations not possible

  if (typeof cssProp === 'string' && cache.registered[cssProp] !== undefined) {
    cssProp = cache.registered[cssProp];
  }

  var type = props[typePropName];
  var registeredStyles = [cssProp];
  var className = '';

  if (typeof props.className === 'string') {
    className = getRegisteredStyles(cache.registered, registeredStyles, props.className);
  } else if (props.className != null) {
    className = props.className + " ";
  }

  var serialized = serializeStyles(registeredStyles);

  if (process.env.NODE_ENV !== 'production' && serialized.name.indexOf('-') === -1) {
    var labelFromStack = props[labelPropName];

    if (labelFromStack) {
      serialized = serializeStyles([serialized, 'label:' + labelFromStack + ';']);
    }
  }

  var rules = insertStyles(cache, serialized, typeof type === 'string');
  className += cache.key + "-" + serialized.name;
  var newProps = {};

  for (var key in props) {
    if (hasOwnProperty.call(props, key) && key !== 'css' && key !== typePropName && (process.env.NODE_ENV === 'production' || key !== labelPropName)) {
      newProps[key] = props[key];
    }
  }

  newProps.ref = ref;
  newProps.className = className;
  var ele = createElement(type, newProps);

  return ele;
};

var Emotion =
/* #__PURE__ */
withEmotionCache(function (props, cache, ref) {
  // use Context.read for the theme when it's stable
  if (typeof props.css === 'function') {
    return createElement(ThemeContext.Consumer, null, function (theme) {
      return render(cache, props, theme, ref);
    });
  }

  return render(cache, props, null, ref);
});

if (process.env.NODE_ENV !== 'production') {
  Emotion.displayName = 'EmotionCssPropInternal';
} // $FlowFixMe


var jsx = function jsx(type, props) {
  var args = arguments;

  if (props == null || !hasOwnProperty.call(props, 'css')) {
    // $FlowFixMe
    return createElement.apply(undefined, args);
  }

  if (process.env.NODE_ENV !== 'production' && typeof props.css === 'string' && // check if there is a css declaration
  props.css.indexOf(':') !== -1) {
    throw new Error("Strings are not allowed as css prop values, please wrap it in a css template literal from '@emotion/css' like this: css`" + props.css + "`");
  }

  var argsLength = args.length;
  var createElementArgArray = new Array(argsLength);
  createElementArgArray[0] = Emotion;
  var newProps = {};

  for (var key in props) {
    if (hasOwnProperty.call(props, key)) {
      newProps[key] = props[key];
    }
  }

  newProps[typePropName] = type;

  if (process.env.NODE_ENV !== 'production') {
    var error = new Error();

    if (error.stack) {
      // chrome
      var match = error.stack.match(/at (?:Object\.|)jsx.*\n\s+at ([A-Z][A-Za-z$]+) /);

      if (!match) {
        // safari and firefox
        match = error.stack.match(/.*\n([A-Z][A-Za-z$]+)@/);
      }

      if (match) {
        newProps[labelPropName] = sanitizeIdentifier(match[1]);
      }
    }
  }

  createElementArgArray[1] = newProps;

  for (var i = 2; i < argsLength; i++) {
    createElementArgArray[i] = args[i];
  } // $FlowFixMe


  return createElement.apply(null, createElementArgArray);
};

var warnedAboutCssPropForGlobal = false;
var Global =
/* #__PURE__ */
withEmotionCache(function (props, cache) {
  if (process.env.NODE_ENV !== 'production' && !warnedAboutCssPropForGlobal && ( // check for className as well since the user is
  // probably using the custom createElement which
  // means it will be turned into a className prop
  // $FlowFixMe I don't really want to add it to the type since it shouldn't be used
  props.className || props.css)) {
    console.error("It looks like you're using the css prop on Global, did you mean to use the styles prop instead?");
    warnedAboutCssPropForGlobal = true;
  }

  var styles = props.styles;

  if (typeof styles === 'function') {
    return createElement(ThemeContext.Consumer, null, function (theme) {
      var serialized = serializeStyles([styles(theme)]);
      return createElement(InnerGlobal, {
        serialized: serialized,
        cache: cache
      });
    });
  }

  var serialized = serializeStyles([styles]);
  return createElement(InnerGlobal, {
    serialized: serialized,
    cache: cache
  });
});

// maintain place over rerenders.
// initial render from browser, insertBefore context.sheet.tags[0] or if a style hasn't been inserted there yet, appendChild
// initial client-side render from SSR, use place of hydrating tag
var InnerGlobal =
/*#__PURE__*/
function (_React$Component) {
  _inheritsLoose(InnerGlobal, _React$Component);

  function InnerGlobal(props, context, updater) {
    return _React$Component.call(this, props, context, updater) || this;
  }

  var _proto = InnerGlobal.prototype;

  _proto.componentDidMount = function componentDidMount() {
    this.sheet = new StyleSheet({
      key: this.props.cache.key + "-global",
      nonce: this.props.cache.sheet.nonce,
      container: this.props.cache.sheet.container
    }); // $FlowFixMe

    var node = document.querySelector("style[data-emotion-" + this.props.cache.key + "=\"" + this.props.serialized.name + "\"]");

    if (node !== null) {
      this.sheet.tags.push(node);
    }

    if (this.props.cache.sheet.tags.length) {
      this.sheet.before = this.props.cache.sheet.tags[0];
    }

    this.insertStyles();
  };

  _proto.componentDidUpdate = function componentDidUpdate(prevProps) {
    if (prevProps.serialized.name !== this.props.serialized.name) {
      this.insertStyles();
    }
  };

  _proto.insertStyles = function insertStyles$1() {
    if (this.props.serialized.next !== undefined) {
      // insert keyframes
      insertStyles(this.props.cache, this.props.serialized.next, true);
    }

    if (this.sheet.tags.length) {
      // if this doesn't exist then it will be null so the style element will be appended
      var element = this.sheet.tags[this.sheet.tags.length - 1].nextElementSibling;
      this.sheet.before = element;
      this.sheet.flush();
    }

    this.props.cache.insert("", this.props.serialized, this.sheet, false);
  };

  _proto.componentWillUnmount = function componentWillUnmount() {
    this.sheet.flush();
  };

  _proto.render = function render() {

    return null;
  };

  return InnerGlobal;
}(Component);

var keyframes = function keyframes() {
  var insertable = css.apply(void 0, arguments);
  var name = "animation-" + insertable.name; // $FlowFixMe

  return {
    name: name,
    styles: "@keyframes " + name + "{" + insertable.styles + "}",
    anim: 1,
    toString: function toString() {
      return "_EMO_" + this.name + "_" + this.styles + "_EMO_";
    }
  };
};

var classnames = function classnames(args) {
  var len = args.length;
  var i = 0;
  var cls = '';

  for (; i < len; i++) {
    var arg = args[i];
    if (arg == null) continue;
    var toAdd = void 0;

    switch (typeof arg) {
      case 'boolean':
        break;

      case 'object':
        {
          if (Array.isArray(arg)) {
            toAdd = classnames(arg);
          } else {
            toAdd = '';

            for (var k in arg) {
              if (arg[k] && k) {
                toAdd && (toAdd += ' ');
                toAdd += k;
              }
            }
          }

          break;
        }

      default:
        {
          toAdd = arg;
        }
    }

    if (toAdd) {
      cls && (cls += ' ');
      cls += toAdd;
    }
  }

  return cls;
};

function merge(registered, css, className) {
  var registeredStyles = [];
  var rawClassName = getRegisteredStyles(registered, registeredStyles, className);

  if (registeredStyles.length < 2) {
    return className;
  }

  return rawClassName + css(registeredStyles);
}

var ClassNames = withEmotionCache(function (props, context) {
  return createElement(ThemeContext.Consumer, null, function (theme) {
    var hasRendered = false;

    var css = function css() {
      if (hasRendered && process.env.NODE_ENV !== 'production') {
        throw new Error('css can only be used during render');
      }

      for (var _len = arguments.length, args = new Array(_len), _key = 0; _key < _len; _key++) {
        args[_key] = arguments[_key];
      }

      var serialized = serializeStyles(args, context.registered);

      {
        insertStyles(context, serialized, false);
      }

      return context.key + "-" + serialized.name;
    };

    var cx = function cx() {
      if (hasRendered && process.env.NODE_ENV !== 'production') {
        throw new Error('cx can only be used during render');
      }

      for (var _len2 = arguments.length, args = new Array(_len2), _key2 = 0; _key2 < _len2; _key2++) {
        args[_key2] = arguments[_key2];
      }

      return merge(context.registered, css, classnames(args));
    };

    var content = {
      css: css,
      cx: cx,
      theme: theme
    };
    var ele = props.children(content);
    hasRendered = true;

    return ele;
  });
});

export { CacheProvider, ClassNames, Global, ThemeContext, jsx, keyframes, withEmotionCache };
```

**Comment by nchanged** [comment]
But that only means the error in their code , since the reference is set to a default object

**Comment by nchanged** [comment]
He is the typescript playground. WHich has transpiled it exactly like fuse-compiler did:

http://www.typescriptlang.org/play/?experimentalDecorators=true&emitDecoratorMetadata=true&module=1&ssl=1&ssc=1&pln=4&pc=17#code/JYWwDg9gTgLgBAfWAOwBYFMrBgZwDIQQ7pwBmUEIcA5AAIBGAhvegDYD0UArsjKOuwyswmHOxQYsuAkXTUA3AChQkWHADecAMZR0jGOgDCEXugAeMADRloAd0ZQAJgCV0pazr0GAoq3Qh0XmtjcBNA+ABfMgoqal1GLRgFZVC1T30jBIxoyhpafwg+E3YtLLklFWh4TQBzdBhXGuAcA11HAGUYAE8-HGsUYlhOnvQcOCjyXLoCouR2Lj5WHGTKtU1B4EZWYAAvdGHe8ZzY-JBC4GKNrd3ylNVquAP9jHqjyZOZi7mcF6SK1PgWhwY3eeU+xSByyU5nuGjgjjcjC4rHgjDGkLeMTBZ1mJWByUUADcHHBvDivoYysZTBY4ABebTxAzUgwWAAUcHY7DgtjkunhEBQNTgMFQzRFEDgjEJgsccDAui0Jha3ES1DGCMYcqVCLgbFAKH0XzgKBFYrGYW0aPQii5cBYpS4xDN4rOjmRJHFCtADmArC6JtMyARctI0DNJHoFFsgylwbgyAgCNt3PoCxNSTGWxwkt0AEcuMA2oG4PFEgmjYSSIx4zgDawSYFCUWTAFeGMcwE+AEcCm43LedoIMi5ahpdW4DgRFpNqx7YXWHKAFZO+BhqBm-R9tPwUXi11cLSoPVo4CYfsRit8KvyhIAa0YdV7dpAwBqqHgTonjmApFImHCCMAiHGl4FNUUSFIBYuH5GsunsLpFG6EQIFIOAAAkABUAFk8F8fxAIAQjpBlqB4BFSBQdBHGoOAAH5GS8TIj3QNkAEo4AALgTZFWDYpRiQ3TCMACFlzHgBl0mZExWRgNl1AifiiRJSkWIABQoZsEQ3BkyXOExVIwMSLAAOg0iAtMwJRlI3WxsFQPTZkMkgGSg5BEmNOzRUcikyjZNytA49RFDgOBBNLQJtPpMgeA8kwIuDTA2QVCAwD6CLSCCkLQoimAYOQRiMnwts5J8gyqRk8STOpHAuACKBrGQXjrAC2Y4DZUoWKynKct0PKoAKgLkooNKPDKaxdEypQesU6bxnkTluQAEgAMVYCBbBW4AzGwm1FGyvr8psKB7CcVxSDZXREqgJSImsu1RSdHkSBMf0E3QaiJQisAGy0EhbDHMCszC65tTHKAElaY64AAKXaawdwTQpocMdp2n28KcBrbAbgASQRXhfzPHSYvctqseQHG9nx8IiaS4ACb4SjMG63KjoZ2nmagEzdB+hJWPYAAdJb2BqaxqAAWmoW7rPC5D0HMsAADlGGA0iEAQbxsIAeUw3HtaVhBMIATTU7wEDUvCAEF2nNgARbWECV3WEAAVVtjXknChsWFYRWVbVmgNa13X9cNvArYAIW8PALetj2Hadl33fNhAvZJMccG12xkEVzBumi7X6CXdBEhMlKYEKLoRBMzPs9zkb866WWSSuqLXNitq26SzqMGsFLRqA9AJrcVnwshRXoogtWSJ41g5wYgecBMjFuKXlfgTZaf0H4xbJ0lUV9DgJ0hTgAADSEz+Oc-wWQK+azlMA0TrZBhQgiLapRL734xAeeWgO8vZQp2kTPAJ+wJT7v10E0FoAFtRlC+lcbYewnhjAdEiZ02B-4jmyi+Rgd4SB-VgIwU0TBfZwFSt2ZoRplRIzAUQOs9A-D7VCr+dq8tULaGBJPEipEVRClogAMkEVaFiPN0AwNaNRAA2hPEaABdOAxEGTkTcFRRwrNQpyNStFXu6BxGSLgbI7hCi5oRBYSDDc8topL2kfLf2qt0DyLmuFaBzQpEdG6IcBkxicCK2cdlceDZgQBxcjQAkrC0Jb2rugTh68tDBJwKE+ks91QwCwK-aWGhspaMSckhkdQGgSPcXA1BHUygGJKW0Eehi2ioP7iNZeCTn6hKUqFKIbBMFRPiXkxxSiGRNXnpo7QvTA49JaX0gA1HAAARLMsxFjMaYFnDcOUDIkE3DKW42BdSvGjCUtlNhw0IB-WBCZJsJlnZ23Nt4JWAA1fppEUrujisgIRIiNl7EcCZZAjiTIoARGYbWF1JZZN4XACWABGYZ3tmBsBWjETo94bGNOkT7NgDiAgBJySaKJ6LWAIsoEirQd5hmhU+Z9dZyzrgoL2TgNk0iKWOHFvizitFpn4sJSAYld44DTIUNQeRbScrmPaYs1uHoxgMgGPnMpejrBMusBwtC1jwVpIyTUaWc1mkhKmZJCpBCAzTJmRLOZ0ymU-McS4kkyB0C2EVlKjQd0LHrnauFQ1JYl7DKOXXHOedYBdBXlsVgxzB6Go4sIuAHrlE0EhO8qN6AAwxvsSNZJkbjmnOXhcq5Nz7kpKeRQF5sxaIAB8S0JqTbPfFmKd5kveva1FhrFEMlsU2uaYqxXZVtQ21Ky9JrRUmnNbtDqV6jLCTqpJVrAmNj8Lopk6BirhGiSIRqdqHUHNCodAaeo-BKGdTZUk5J4p0ltAAKjgAAYg1mpV2zhU5wFPewRQXkHJHuQM5fyndjShvSvKjKrM7RfjgMZGA4itTQ3ftvHkGACrYHVJOGAzBmGRPYTEuJjSN5StSa1L4WTgo9S3QVKSC6-AlTZMJAiIHqrKjqpgRqzVSavPYSJHe2SeqbvqEdbuUByksQab2pVLGR5TRxbNbK5iDqce3dx3jfd5SNPo-PYTt0DlHJSpm85yBCSXO1tczWeaY3UGeYeYtrMyrIBMj+KcDYuj5JoOZwwJjUq41MANLYyQoh2lWutTa21dr7QPUuHAZhoo4fikFswy7h7yd7WPEkDgaiOoS7R9s1kUM-pSXPOcZalG+obqlJuQb54-vFnGtiwyvNrQ2ltHaNoCNSaI-OxdvATKMDAD9LobJVGUVtcyqUUBEvCok+l9Tows1aZ03p25DzDPGdefG5VMW0qYfzTQfhmS4CRrtCxEluKIz8nFIwLhGpS4NghrMbK8SzkAvMMCtk1A2UcRjVC4Zopoz1tJFACgPGZmdA1VmfkoCpTzw2p9NEx2lsg1YFwUY-c-DWh5BDMAGYSxHYxAYcADYDBwG2K0LY19phvrxMsHHwACEuhwNxS+ZqltNOBHy2ZZ8ZlDfFRuBL+BAg1FFNFdnJk-Cv1FNajcxHmswCtgN8XEMAwDLtXASXjBOvs7wJz0UwqRekfCOLmo8uujSIAAzNsPfpZAQv60OuigpNL0M2TusTZ6xp3qol5f9d0IrIal7WHDXW4djbE2G9bX79t4xxMWJ972uxMSa2G-llbtTFANPZt07mmbqS5umbYzlcKmBvvRW7Z9777Erfpez9AEyLR7x1u26gGIdX2PhRAPoI80US-c3LySkyDeYBHjZOwI+bI6KcSLiXRIgsTIlrYhFkyp7BbIEFjgSZffpFWwlgALXkUv1fjAJY7CWvIyZHF2AbvY0cwinejx1uAdyLGpBfQXkopNCAZgcU9TP8eBkLey+Ifb6-nvU+Z8MuXzXw3xXy3x3z3zYloEPyD07XYz2zZFfwvzN1RWrVTUcUNwpipnQBpkJi5ngMb1QGkUhSFWgODxmhD2ynVwIl4C1x10IMNzDzSit1dRtxJGAGigACYFo2CAAefrRLZXAXVALgyZffDPLRJrDXagiXL7BXaRYAQ3dnOQgJdpPebzarPzPaSTfqRrJiUXVrdrf0NkQZVgDwCQqgsXaQqXGWDGEkU6XrK2egYcGARzPxEaFaaAAAcXWiYDnFcmzHQAEhJC8IgB8PpDPUvWvVvXvUfWfXsgcz8jCwKhK1EQwFZjjxOTG0020xzX0xTwLSTBM1w02xEUIjsOogcKcJcMVncKgGCNCPTT3h215VdQnWSXB15HnknBQD+kvC-A3GaFwW5BSjITehPlfkvC0FXFyEoJKmg2ACPEGLgACBrDGCwTsk6JYBFHyk+hQErilBGQmWAgHkWLUN81qzgFxgFDeXgHiHngDHsF4C+i1DlCwT2MgxiS6Pck9HgB+GHEXGuPtBIC-EcEuww1aL6RyyuxwHKzEJAhzD8HOS+2gDZBmVxngHWggEAVJ3Jy6GHDiCBJfjfmyF-hGgoQKjqK2GsB-DlFxK4CWL0AKj2KA3fhaBGDGD-gGAMC1DomZyDzKMcAqIWCqLcM8O8PxwZHSRhwWWnQ3FZO8Vp0-zZNjyiUWzlNGFW2oESLwxxUI0Kh8EkLkgo1EkqlMhqlowaiyxai-Xii3hYzrSWSwBpUpUnGpWQX2DpQZTVPpW3jYmIOfzZm3RmKXRc1tVqLFJMNhJ6iZW4kVX9K0TKCpzKH9LExmhZxlJdMdLdLWQzJWVpTZM9LpT9I420L1JI3MLZBDMwApIjPwxymjJzKdOZRxT0UTJYnExU3um5Ab12JIQKj5h6IsnPF0G42Xj7BQBxnx242vijA2kGH6GQEGBgEjjcGgEIRNNAx+A+lA0Q0S310UXDDYSOzVLgEzgBJYECEDEXM+ggn5C6HqGsDaxEGDEMDFEXDHMpj4HxwSTPF4AljrF1CnNBDRmcGsCA37JejQlQC6EcHO0gUfAPUrLDJCPFLPSvQtiiI1hiMSPagQFcEhiWhCEgFtV4FZiQDQGWWkEIGIArOQFDOrOsFwr0ESAIsoCIvCCP2wsQurOSKVFAlArAEcAyBulhN1MYvwsIrCBa1KGKz3HSg9xAlkn4sEtaA4hy1kulNCnCgQArklAZC4vDPLgoErhjwsW0qMogBXlYskpgDtgZmwmHEeI7jJmNCVFCGIpsrsocrkle3NDL1+Fz1lyeHaF+Hkn9MNW4lksMt7SDTEQ9WNQlhqHDJmUsH9MTC+Iit8viQqU3PqB+RMD+hStgN4sQyoigAyuaCiuWz0T8q3Mst4F7MwFE13kqx8xq38xxXCkTF1AZEcBORS1AwLEwC6HaDYFLkrh+zVOkWUq31vlNQZ0iqytirt2NTpEFhmRpwWowwtV+WAmNTWvkV5IsXSy6pIBjWMLrUipyu3MfGXjACdFQCMKTB3iD2GxyiOU2uiuqqupMh3OXn5y51QAut8u+pYHXDCQ+qquyt+B+pur3JeqOop3+QXNlQ9KGytzMsKAstcrYt4FsscFdgEoyFC2tKIysvcrxoJuUtYgVHQEJHXVhLj1ppHW2r6WTUyq2tdNWUtQCCBoqplSGFRvhvaXRp0qRsXNQWJucvin5pgFQSWkhXYgZpVPZuiu2vEkeWPkSh62okr25BlorXIEcSAWP2RoFvzIhqaXGkRvXjVosCVW4GetEwRveuBuht+r5xV0BsjL3jYVkoFFGABPMHcQjFg3gHWLnE2OMP3kvGPNGtmPDsBKlHa0imon9KzwNKnldtqt+rsSztyvdv+u5wljgCIJ+XElF3aGACYSFBIMuuhtBtXObwNNrrztA1IGhx+ELydpxQtpiowDFvzhROSuto5szNWUEwqqupan8LRtMtFuxusoAHU-RWBXZkAzgeAJJGM2oF73Ll75416N7eBFbazQo67ar277qu7ha57zLxFrpJamMZMsodSGssszErddT9LkLWA902QJL3KDlbcuhDaexH62pDVQHRgT70yZakNx0zlHzDCZQGY4A9cHyBt+roTTcdqwkZlsZO8vg5rpk4GmF9FcGFoWr1DasLFdTT6KwAhuJcHCq6y6VuIZlaBIGIYwGadcGGcZl1AadSGESvT+GIhkqcUCHuJIUWGz6IA-shRuJsLK4FHX4YHYDdSZlNYdYEANrfK+HjVdH5rga6V+HtHHYZkhb5pFB90gln5cHHVsKJ0HG2R2c4sNx+cecBs-rPbTc2CGQ9dTcElHVqAIlrcuC4BeD+dhDRD6HwoEsvHdz5Cg8jkEnZ5zqFKUApSOqSRK4rZHBsyUG5RAmEacAvIm8otOEEs61ShnRqBHCIB4c3lOI4z7R4g7wi8cpamSBqAQjh8kgWnYDQp6HYCjkdd-kcAddXGBsYSRmhm8mCndFEkXHqmSCZod1nQ5nYCFnszQnOmhnrd3VUcZnvaDnUmBtpE7xFFI1SVTmDmJR8m5R00dm+VSIaBhV7n2MXnJkGQOnWnYDRVPnSD7nXqDmow9A-mDnQWcoKIkQURBmhmtmcoXmGQEs1ngWYC3qVSIBHmamlhij2pgnXmaB3mSCiWfmHmCmrHXrdTgm91rJsL6o6hLpikdlqIPBgQPAx13GIpalqIJafFlDLFSxGBbBDAx1opClGgql+WPTtkPEakZXPE2SuXDjHbDkol5XSk6UPbBDIm4B2DhlaWx0NKAyCoIYxWJXplIQWW+XlXehbobCNxxW1XHUX14iWJP0pakj5LirxJWZaWzCyMjSjB1zqMFzzTFMIzsLbSCIYUM40RXBrpnSb8lgAiEbx56cnKmMbW60fVE2U7ixI1RszlE8psDNU9C1CiTBtSDm3sNoPtvAkSeNqAMRSgCpXoAxNjgT4QYJT5uMtVkyEbQpmCtLPHUXMGSofHBCMHEsArbA5cZDOsEB+c2IGKPUAmFoEAPVeCV3Agt3DURDEDFDt2-dEmsHpFT2ughWyC06SQmVooKUyl2cPAw2tW2gj8eokWZa5V1yFVOavlp602PmRVh2zWFKqo4rZliGGyszub02ZpOnx4Qts2d7Is82ncC3k2nmRES3xtsik9ciNajMq35tED62F288m2C9W2Qt22yS3pu3iA5R3QNUEptJB2AWwPR2SQ93kB2Dz2p3dWAbZ3HU88pm+PDX13E0BPN3EBDUBPd3+dOD5OZOj27mT2FOFDJ3wgcBL2tOSDoXiyjomXWI-XTJ332XjtVXgQVnvHysXqkOSQ-XHLvbIQqdOX-StAzAqczBZHkWWMMqCJRMg906wl4lXyYLAgOpKoSKg9M4k3tJnTJT03X6SzRqzEOz9oYQqg4RnJzJLILSXXdUexrB6K4AQ2QNrAItPdE0oH0p3W31nJ5ogA

**Comment by nchanged** [comment]
@foisonocean  actually you don't have it set. If you did, the following output on the line would take place:

```ts
var InnerGlobal = (function (_React$Component) {
  inheritsLoose_1d.default(InnerGlobal, _React$Component);
  function InnerGlobal(props, context, updater) {
    return _React$Component.call(this, props, context, updater) || this;
  }
})
```
`inheritsLoose_1d` that how the variable should be named. 

Set it like this:
```ts
fusebox({
 compilerOptions: {
      esModuleInterop: true,
    }
})
```

or in your `tsconfig.json` 

Either way, the problem should be solved.

**Comment by foisonocean** [comment]
@nchanged 
Is there a way to override tsconfig.json in fusebox config? I actually prefer to set `esModuleInterop` and `isolatedModules` to `false` for my project, so it could be much better if I can override it in fusebox config.

**Comment by nchanged** [comment]
Yes its done the way I posted in the previous message. Either way if it's not going to be overriden we should create a new issue, thanks for helping out !
