### ISSUE TITLE
watch not working [4.0.0-next.413]

### ISSUE THREAD

**Issue by fiftymissioncap** [fuse-box/fuse-box#1864]
setup a fusebox - react project. simple hello world to start. everything is working fine but the watch option is not detecting changes and rebuilding the bundle on source file canges

**fuse.ts**

```ts

import { fusebox } from 'fuse-box';
const fuse = fusebox({
  entry: 'src/app.tsx',
  target: "browser",
  devServer: {
      enabled: true,
      httpServer: {
          port: 8181
      }

  },
  webIndex: {
    template: 'public/index.html',
  },
  watcher: {
    enabled: true,
    include: [ "src/" ],
    chokidarOptions: {
     
         interval: 500,
         usePolling: true,

    }
  },
  logging: { level: 'verbose' },
  hmr: true,
  cache: true,
});


fuse.runDev();

```

build is working and output is showing up in the browser. HMR looks to be working as well:

![hmr](https://user-images.githubusercontent.com/5166624/77178157-1a303c80-6a9d-11ea-87a5-ce95f333886b.PNG)

build results:

![fusebox-logging](https://user-images.githubusercontent.com/5166624/77178301-451a9080-6a9d-11ea-9c39-11b01f8800c9.PNG)

package.json:

```json
   "@types/react": "^16.9.23",
        "@types/react-dom": "^16.9.5",
        "fuse-box": "^4.0.0-next.413",
        "react": "^16.13.1",
        "react-dom": "^16.13.1",
        "ts-loader": "^6.2.1",
        "ts-node": "^8.7.0",
        "typescript": "^3.8.3"
```

have tried a number of different config options for the "**watch / chokidar**" config as well.

any suggestions?

thanks.

**Comment by vegarringdal** [comment]
tried relative path `include: [ "./src" ],`

thats what Im using atm
![image](https://user-images.githubusercontent.com/2901416/77180843-cdfbf100-6aca-11ea-8aee-e53fd0f20e1a.png)

**Comment by nchanged** [comment]
Could chokidar options affect this ? Could you remove it ?

**Comment by fiftymissioncap** [comment]
> Could chokidar options affect this ? Could you remove it ?

tried both the relative path: include: [ './src' ], and removing chokidar options:

```ts
 watcher: {
    enabled: true,
    include: [ './src' ],
    /* chokidarOptions: {
     
         interval: 500,
         usePolling: true,

    } */
  },
```

same result. file changes are not being picked up by the process

**Comment by nchanged** [comment]
Wait but how come you are saying that HMR is working ? HMR is triggered by the watcher

**Comment by nchanged** [comment]
Oh that's docker right, set awaitWriteFinish 
You should experiment with chokidarOptions, it's not a common env you are running it in

**Comment by fiftymissioncap** [comment]
> Oh that's docker right, set awaitWriteFinish
> You should experiment with chokidarOptions, it's not a common env you are running it in

ok. will try some more options. its ubuntu 18 on vagrant. similar to running in docker.

i've got a similar setup setup running on the same VM with webpack -- hmr is working with polling enabled.

let me try the other combinations.

**Comment by fiftymissioncap** [comment]
i think this issue is related to this PR: https://github.com/fuse-box/fuse-box/pull/1859#issue-389783687 

i think the config is picking up the wrong APP_ROOT. i don't have a monorepo but my node_modules is a symlink 

i think the option to override the default and specify the root will help

**Comment by nchanged** [comment]
Oh gotcha, I will merge the PR and cut the version soon

**Comment by fiftymissioncap** [comment]
i just tried installing 4.0.0-next.**414** to test out the new **root** wathcer config option

i may have done something wrong but i don't get the new option recognized:

```js
fuse.ts:26:5 - error TS2322: Type '{ enabled: boolean; root: string; include: string[]; chokidarOptions: { awaitWriteFinish: { pollInterval: number; stabilityThreshold: number; }; interval: number; usePolling: boolean; }; }' is not assignable to type 'boolean | IWatcherPublicConfig'.
  Object literal may only specify known properties, and 'root' does not exist in type 'IWatcherPublicConfig'.

26     root: workspace,
       ~~~~~~~~~~~~~~~

  node_modules/fuse-box/config/IConfig.d.ts:50:5
    50     watcher?: IWatcherPublicConfig | boolean;
           ~~~~~~~
    The expected type comes from property 'watcher' which is declared here on type 'IPublicConfig'
```

it looks like the old code is still there:

```ts
export interface IWatcherPublicConfig {
    chokidarOptions?: WatchOptions;
    enabled?: boolean;
    ignore?: Array<string | RegExp>;
    include?: Array<string | RegExp>;
}
```
config/IWatcher.d.ts

**Comment by nchanged** [comment]
That was from my branch, I need to merge it first, will do it today

**Comment by nchanged** [comment]
@fiftymissioncap `fuse-box@4.0.0-next.415`

**Comment by fiftymissioncap** [comment]
> @fiftymissioncap `fuse-box@4.0.0-next.415`

thank-you. just tested **next.415** and its working. can supply the root setting to watcher config:

```ts
const workspace = path.dirname(__dirname)
...
const fuse = fusebox({
   ...
   watcher: {
       enabled: true,
       root: workspace,
```


watch and HMR is working as expected.

**Comment by nchanged** [comment]
@fiftymissioncap I am happy to hear it! ;-) I guess we can close this one now.
