### ISSUE TITLE
loading stylesheets [4.0.0-next.415]

### ISSUE THREAD

**Issue by fiftymissioncap** [fuse-box/fuse-box#1869]
i may be doing something wrong but the build process is not picking up stylesheets to process. i have a simple (hello world) react app and the stylesheet is co-located in the source directory. i'd like to use to sass and css modules but for now just want the stylesheet to be processed: ```import style from './app.css' ```

i'm following the directions as per: https://github.com/fuse-box/fuse-box/blob/master/docs/stylesheet.md 

i've specified the path in fuse.ts:

```ts
...
stylesheet: {
    paths: [cssPaths],
   
  },
...


```

probably just need an example of working solution with: _The only condition is having the corresponding CSS preprocessor(s) installed._

**Comment by nchanged** [comment]
You would need to Include plugin sass and set asModule option as per documentation. The paths field you set it unrelated , it's a folder lookup list which is used to resolve internals css imports

**Comment by nchanged** [comment]
[this](https://github.com/fuse-box/fuse-box/blob/master/playground/sass) can help

```
pluginSass('some/*.scss', { asModule: {} })
```

Alternatively to use it with `default` import

```
pluginSass('mod.scss', { asModule: {}, useDefault : true })
```

**Comment by nchanged** [comment]
Also the [documentation](https://github.com/fuse-box/fuse-box/blob/master/docs/stylesheet.md#importing-as-css-module) you probably should read it till the then ;-)

**Comment by fiftymissioncap** [comment]
thanks for the tips. that worked. everything is good now.
