### ISSUE TITLE
FuseBox Needs Your Help! Documentation!

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#187]
We want to make the best product in the world of JS, but that requires your input as well. There many edge cases that require clarification at the moment.

To start with, we really need to improve our docs. If you see an inconsistency or even a typo, please submit a PR. That would probably take 5-10 minutes of your time but will help a LOT. 

Thank you!

**Comment by liadbiz** [comment]
@nchanged 
I am glad to help. 

but, to tell the truth, I am new to understand how a bundler actually work. I have tried to learn webpack, but it's too big and  overstaffed and with terrible documentation, I can not find a proper way to contribute.

So could you give some suggestion or imformation to better understand  this project? I am not sure how to get started right now= =

**Comment by devmondo** [comment]
@liadbiz great idea, yeah we would have some kind of manifesto for Docs Contribution :)

**Comment by liadbiz** [comment]
@devmondo 
thanks! 

Do you hava plans to add some information about how you build this project or how to source code are orgnized? just like [babeljs](https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/plugin-handbook.md#introduction) so that more contributer can 
contribute some code ,plugins or something.

Don't mind if I have been bothering you :)

**Comment by devmondo** [comment]
@liadbiz by all means keep bothering us, your input === awesomeness :)

regarding guidelines for contribution, we have https://github.com/fuse-box/fuse-box/blob/master/CONTRIBUTING.md

admittedly it is crap now and we should improve it, so please keep your ideas coming :)

**Comment by liadbiz** [comment]
@devmondo 
you are so kind!
I have checked out project's contributing guide.  but found not much= =.
thanks again for your response and I will keep watching :+1:
