### ISSUE TITLE
Code splitting not splitting @fullcalendar/core

### ISSUE THREAD

**Issue by TiTi** [fuse-box/fuse-box#1870]
Hello,

I'm discovering fuse-box, it looks promising.
However, when using code splitting, I cannot understand why one of my imports is not put in a separate file, but end up in my `.bundle("app")`

I've made a simple repo. to reproduce the issue : https://github.com/TiTi/fusebox-codesplitting-issue
As you can see:
- The app is working (no css so it looks ugly, but no error in console and calendar is instanciated).
- i'm using the QuantumPlugin (to be able to use code splitting)
- i'm using dynamic import

**Expected:**
dist_fuse/app.js to be way smaller, to only contain:
- // default/main.js
- // default/other.js
- fusebox code

**Got:**
dist_fuse/app.js is ~286KB and contains @fullcalendar/core
`var fc = import("@fullcalendar/core");` ends up inside my "app" bundle:
```
// @fullcalendar/core/main.esm.js
$fsx.f[2] =
```

-----

There is a cryptic sentence in the documentation, which might be related:
> FuseBox will detect which modules and files are shared and which belong only to this specific bundle. Long story short - let FuseBox take care of that.

I tried to reference `@fullcalendar/core` from elsewhere but still end up with a big app.js

-----

At last, how can I get proper TypeScript autocompletion?
Because right now:
- `var calendar` ends up of type "any"
- despite having proper types in "node_modules\@fullcalendar\core\main.d.ts"
When using `import { Calendar } from "@fullcalendar/core";`, typescript autocompletion is working fine, but then i can't use code-splitting so the whole module is bundled with my code.
I'd like app.js to contain only my changes, not the whole fullcalendar library.

**Comment by charsleysa** [comment]
@TiTi that looks to fuse-box v3 which is no longer supported. Please upgrade to v4 using `fuse-box@next`

**Comment by nchanged** [comment]
@TiTi here is a [getting started](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md) for you

**Comment by TiTi** [comment]
hmm too bad the documentation i read - https://fuse-box.org/docs/getting-started/installation -  isn't up to date

got an error ` Error: Cannot find module 'worker_threads'`
-> had to first update to node 12.16.1 LTS ok ok

Then I could not use fuse.js, got error:
```
import { fusebox } from 'fuse-box';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

Ok switching to **fuse.ts**... yeah working


ok so i've upgraded https://github.com/TiTi/fusebox-codesplitting-issue

and indeed the bundling is working better 😃 
I'm not able to use [a dir different than dist/](https://github.com/fuse-box/fuse-box/blob/master/fuse.ts#L33) but that's manageable.


Thanks guys, happy to see it working.

And looking forward an up to date documentation, to be able to minify output !

**Comment by TiTi** [comment]
ok `fuse.runProd({ uglify: true });`

and for TypeScript : need to use `await import("@fullcalendar/core");` and then autocompletion is ok

**Comment by nchanged** [comment]
Check the doc folder , there is everything you need, so change dist set distRoot in runDev bundles

**Comment by nchanged** [comment]
https://github.com/fuse-box/fuse-box/blob/master/docs/output.md
