### ISSUE TITLE
resources not processed [v 4.0.0-next.415]

### ISSUE THREAD

**Issue by fiftymissioncap** [fuse-box/fuse-box#1873]
i could be doing something wrong (again) but am following the docs for bundling assets.

```tsx
import * as file  from './abc.png'

```
based on the docs: https://github.com/fuse-box/fuse-box/blob/master/docs/resource_links.md 

it seems that these types of resources should be handled without additional configuration.

have also added the resource path in fuse.ts:

```
resources: {
    resourceFolder: resourcePath,
  },
```

i don't see the files being copied to my output (dist/) folder

is there any examples i can look to? i saw this one: https://github.com/fuse-box/react-example which had assets to be bundled

**Comment by nchanged** [comment]
Have you cleared the cache? It might be related. Otherwise, here is the [code](https://github.com/fuse-box/fuse-box/blob/master/src/plugins/core/plugin_link.ts#L31) for reference. It follows the configuration. Unless something is broken on the way.

**Comment by fiftymissioncap** [comment]
tried clearing the cache -- no luck.

the code links helped. i don't see the callback invoked (**plugin_link.ts**):

```ts
 return (ctx: Context) => {
    ctx.ict.on('bundle_resolve_module', props => {
      if (!props.module.captured) {
        // filter out options
```
i added the following as well to fuse.ts:

```ts
  plugins: [pluginSass('app.scss', { asModule: {} }), pluginLink(/\.png/, { useDefault: true })],
```


not sure if its needed given that **png** resource types are handed without extra configuration

**Comment by nchanged** [comment]
So is it working now ? If not please reproduce it

**Comment by fiftymissioncap** [comment]
its still not working, even with adding the link plugin... as for reproducing:

* i have a simple react (typescript) app building with fuse-box
   - watcher/HMR are working for react components, sass compilation and HMR for styles is working

when i add a png resource in the src/ folder its not getting picked up. it looks like the **pluginLinkHandler** is not getting called or more specifically the callback to the '**bundle_resolve_module**' event set in the **pluginLink**() method.

is there a test case i can run in an environment for resources such as a .png? just to confirm is a code issue or a config setup issue

**Comment by nchanged** [comment]
@fiftymissioncap there is really weird. I've just tried it myself

```
import logo from './logo.png';
```

No configuration set whatsoever, it's being correctly copied:

<img width="214" alt="Screenshot 2020-03-25 16 26 03" src="https://user-images.githubusercontent.com/1629088/77553640-599fc400-6eb5-11ea-9127-b6690f0aae3f.png">

* Which OS are you using? Mac/Windows/Linux
* DIsable cache and try again.

**Comment by nchanged** [comment]
@fiftymissioncap it just occurred to me:

If the import is unused it will not be bundled.

```
import abc  from './abc.png'
console.log(abc);
```
if you remove `console.log` the statement will be removed.

**Comment by fiftymissioncap** [comment]
just added the log statement ... bingo! ... its working

i thought i had tried that before but probably doing too many other things.

anyway, thanks for the help. really enjoying using this package/tool.

**Comment by nchanged** [comment]
You are welcome :)
