### ISSUE TITLE
Asset (e.g. png) bundling is broken 

### ISSUE THREAD

**Issue by JKAnderson409** [fuse-box/fuse-box#1884]
I am not certain if this is a bug in the software or a misunderstanding due to a lack of documentation.

When configuring FuseBox, neither the "resources" configuration property nor "dependencies" property allows FuseBox to bundle external asset files.

```TypeScript
import ref from "some.path"

document.body.innerHTML += '<img src="${ref}">'
```

This snippet from another issue can get the code running but the "resources" configuration still does not work as described. It does not name the bundled asset folder as specified and does not look for assets as specified. Using the DOM to make FuseBox aware of the file is the only way to bundle such an image file with FuseBox v4 that has worked for me. For now, "use the folder name 'src/resources' to keep paths consistent, then import and append to the DOM" is a hack that works but this is not a permanent solution. As I am making a WebGL application with a stand-alone resource loader for GPU processing, I do not intend for these files to touch the DOM at all.

EDIT: Fixes Markdown syntax.

**Comment by nchanged** [comment]
@JKAnderson409 
Version ? Please paste your config too.
Just so understand, unused imports are removed. If you need just to copy files into dist you can use sparky. Importing images will copy the files into dist and give you a public link.

Also, cached files won't verify the presence of it's assets, so if you are clearing the dist folder each time your start the process that's the result.

**Comment by JKAnderson409** [comment]
I was able to reproduce this on the most recent release of version 4 (as of two days ago), even with a minimal configuration from the version 4 docs.

**Comment by nchanged** [comment]
Config please ?

**Comment by charsleysa** [comment]
Closed due to inactivity.
