### ISSUE TITLE
Question regarding resource bundleling

### ISSUE THREAD

**Issue by bogdandv** [fuse-box/fuse-box#1886]
I am trying to use bundled resources.
after I use url('../resource/nameOfImage'), it generates url('/resources/abcdser.png')
How do I remove the slash ("/"). I want to generate url('resources/abcdser.png')?

**Comment by nchanged** [comment]
```
resources?: IResourceConfig = {
	resourcePublicRoot?: string; //default: "/resources"
	resourceFolder?: string; //default: "{YOUR_DIST_FOLDER}/resources"
}
```

**Comment by bogdandv** [comment]
Thank you!
