### ISSUE TITLE
Watcher does not start in v4

### ISSUE THREAD

**Issue by jeremija** [fuse-box/fuse-box#1891]
#### fuse.ts

```typescript
import { fusebox } from 'fuse-box'

fusebox({
  target: 'browser',
  entry: 'test.js',
  cache : true,
  devServer: false,
  watcher: true,
})
.runDev({
  bundles: {
    distRoot: '.',
    app: './build/index.js',
  },
})
```

#### test.js

```javascript
console.log('test')
```

When I run fuse, the process exits as soon as the first bundle is generated:

```bash
$ ./node_modules/.bin/ts-node fuse.ts

  ⚙  FuseBox 4.0.0-next.424
     Mode: development
     Entry: /<redacted>/test.js


   SUCCESS   Completed without build issues in 41ms


$
```

Am I missing something here?

**Comment by nchanged** [comment]
Could it be related to devServer false ? I will check it later , but this part has been polished

**Comment by jeremija** [comment]
I thought it might be too, but the bundle doesn't update for me after I modify a source file, and refresh the page, even when `devServer` is set to `true`.

**Comment by vegarringdal** [comment]
watcher: {
                enabled: true,
                include: ['./src'],
                ignored: ['dist']
            },

What if you add something like this, just incase there is a bug between simple and advanced setup.
Anything special in the redacted part? 
Entry: /<redacted>/test.js

**Comment by jeremija** [comment]
>  Anything special in the redacted part?
Just my home folder path :)

Yes your example works, but you have a typo: it's `ignore`, not `ignored`.

As soon as I remove the `ignore` property, the process exits immediately!

**Comment by nchanged** [comment]
Set distRoot to build, the watcher is going crazy picking up the changes, or add build to ignored paths

**Comment by vegarringdal** [comment]
@jeremija 
You are right , I had a typo. Thank you for pointing this out :-)
But it really didnt matter from what I can see since my dist folder isnt within the folders beeing watched :-)
