### ISSUE TITLE
Watcher breaks build

### ISSUE THREAD

**Issue by starsolaris** [fuse-box/fuse-box#1895]
Example:
https://github.com/starsolaris/semantic-ui-fuse-box

1. yarn start
2. open http://localhost:4444/
3. change color in src/semantic-ui/themes/grey/elements/button.variables
4. update http://localhost:4444/
receive next error in browser:
```
Uncaught Error: Module 4 was not found
    at f.r (app.js:19)
    at 1 (index.ts:2)
    at Object.f.r (app.js:24)
    at vendor.js:362
    at Object.f.bundle (app.js:10)
    at vendor.js:1
```

vendor.js lost all modules

This issue from fuse-box@4.0.0-next.424
As i understand, after this: https://github.com/fuse-box/fuse-box/pull/1882

**Comment by nchanged** [comment]
@starsolaris hey I think I managed to fix it in `fuse-box@4.0.0-next.427`

However, there is another bug where this module is busted on a simple change of `app.tsx`

Please, help debug it. I have very limited time nowadays, but I will try to find the time.

**Comment by starsolaris** [comment]
Ok, i will try.

**Comment by nchanged** [comment]
I am assuming this can be closed?

**Comment by starsolaris** [comment]
The initial scenario of this issue is working fine now. 
There is another issue:
- change text of button in app.tsx
- fuse start to rebuild less files included in app.tsx (i assume that fuse should get them from cache if they are not changed)

**Comment by nchanged** [comment]
It is not indented , but I couldn't reproduce it locally, and it's hard to debug your repo (too complex ) do you think you can reproduce in a simpler manner ?
