### ISSUE TITLE
Babel Plugins - fuse-box 4

### ISSUE THREAD

**Issue by kodemaan** [fuse-box/fuse-box#1896]
I am trying to convert my project to use fuse-box 4 and it's failing because i'm using class properties. I looked at the docs and couldn't find out how to do it but is there a way to add babel transformers to the fusebox 4 config? I know the BabelPlugin seems to be deprecated in this new release. Thanks.

**Comment by nchanged** [comment]
Hi, v4 is using its own compiler, Babel isn't supported, we support custom transformers, but then somebody needs to make it

**Comment by kodemaan** [comment]
Ok thanks :) I might have to hold off on a conversion then because a lot of my code uses custom Babel transpilers but I'll look into custom transformers too and see if that's viable option.
