### ISSUE TITLE
Deeper customization in WebIndex

### ISSUE THREAD

**Issue by seivan** [fuse-box/fuse-box#1899]
The real question is, how can I modify `$bundles` in such way that I can for instance reduce it, and add "module" and "nomodule" versions of it and *only* for legacy outputs prepend polyfills. 
 
It seems like it's very static, and that would be fine if there was a way to generate index.html file yourself using whatever "data" fuse-box generates as arguments (like `Array<Bundles>`) but I can't seem to find anything about that in the docs.

**Comment by seivan** [comment]
Looking at this PR, there seem to have been at least at some point a way to add attributes to a script tag. 
It's however missing now, not to mention that wouldn't be enough as I would like to duplicate each script with both `module` and `nomodule` attributes.

**Comment by nchanged** [comment]
@seivan I think we add a "reducer" to script tags in `webIndex.ts`

Do you think you can take a look at it?  You need to emit an object which can be modified.

**Comment by seivan** [comment]
@nchanged There is nothing called `reducer` in `webIndex.ts` I assume it was not meant literal? 
Looking there, whatever it is, it needs to be called before 
`getEssentialWebIndexParams` as that is what generates the script tags before writing it into the template. 

Are you referring to the event that gives the bundles and then generates them? 
```ts
  ctx.ict.on('complete', ({ bundles }) => self.generate(bundles));
```
?

**Comment by seivan** [comment]
Ok I think I got part of it. Just not sure what's expected here.. 

```ts
function myCustomWebIndexTransformPlugin(options?: any) {
  return async (ctx: Context) => {
    ctx.ict.waitFor(
      'before_webindex_write',
      async (props: {
        filePath: string;
        fileContents: string;
        bundles: Array<IBundleWriteResponse>,
        scriptTags: Array<string>,
        cssTags: Array<string>
      }) => {
       const unsortedBundles = bundles.reduce({module: [], noModule: []}, (memo, next) => {
          //interpolate two script tags and add them to either "module" or "nomodule" 
        })
        const sortedBundles = [ ...unsortedBundles.module, ...unsortedBundles.noModule]
      // ?? 
        return props;
      },
    );
  };
```

A few questions

1) Will bundles only contain a ) All javascript b) Only entry points javascript c) All sort of file types
2) Do I need to alter the `props.scriptTags` as well? 
3) How do I later other parts/tags of the `html.index` based on the content added available in props?

**Comment by nchanged** [comment]
In this case, we need to change how the script tags are generated. We need to be able to override the default generation to be more precise. 


```ts
const outputContext = { bundles, jsScripts, cssScripts, outputJSTags, outputCSSTags }
ict.sync("webindex-scripts", outputContext)
if( outputContext.outputJSTags) outputJSTags = "default script collection" 
```

Something like that. Then a plugin would set those values. If nothing was set after the sync we could default it to how it's done RN.

Feel free to introduce improvements to the flow. webindex is the one that needs a good refactor.

**Comment by seivan** [comment]
Sorry I don't follow here.
What type is `jsScripts`? 
What am I actually altering and returning? 

There are several issues at play here.
One is the ability to use said values in the CSP meta tags, the other is using the same values to get a hash for subresource integrity. 

So the script stuff was just an example, the actual question is how do I get access to something that fuse-box has generated and amplify it before allowing me to use it to generate portions of index.html. 

I imagine using a template language inside the `html.index` and loop over these new values and either interpolate the entire tags, or the actual values and define the tags in the `html.index` directly. 

The only thing I can point at is Webpacks approach to this.

**Comment by nchanged** [comment]
in `v4` there is a thing called `Interceptor` 

So shorty


implementation:
```
props = { context : {} }
sync("foobar",props)

if(!props.context.foo) props.context.foo = "bar"
```

any plugin

```
ict.on("foobar", props => {
 props.context.foo = "hello world";
// this is how we set a value for foo
})
```

It could be done this way. So In you're case you'd create a plugin and handle script tags they way you want.

**Comment by seivan** [comment]
Right, so what I am asking is what am I actually getting in that callback, as in what actual data, or if it's easier, what TS types and what do I need to return?
I assume in the end, `$bundle` will be outputted, but if I create my own `$cspMetaTags: Array<MyMetaTags>` how do I make sure they are properly injected in the html template?

**Comment by nchanged** [comment]
@seivan you'd manipulate the contents directly? Do you need any help implementing it? Join our slack to discuss it.

**Comment by seivan** [comment]
I’m good. Thanks.
