### ISSUE TITLE
react_ssr_csr from playground not working

### ISSUE THREAD

**Issue by karibertils** [fuse-box/fuse-box#1900]
I am testing SSR from playground/react_ssr_csr.

After running
```ts-node -T fuse.ts dist```
dist/client/vendor.js has "undefined" as content

In commit b301e6c94fd837bc2ffb5bdc887aa3e2ab9624b4 vendor.js is OK. After 9ff035b25c64dc3b00cf09a6e6e9556cca79a871 vendor.js breaks.

**Comment by nchanged** [comment]
Maybe clearing the cache will help? There are a few issues when jumping between versions

**Comment by karibertils** [comment]
There is no .cache folder and fuse.ts has ```cache.enabled = false```

**Comment by nchanged** [comment]
I will check the configuration has changed in the recent version

**Comment by nchanged** [comment]
@karibertils you were right. A bug was fixed
https://github.com/fuse-box/fuse-box/pull/1903/files
