### ISSUE TITLE
?. error on parsing module

### ISSUE THREAD

**Issue by bogdandv** [fuse-box/fuse-box#1905]
Writting a syntax like:
data?.element1 shows the following error message:
 Error while parsing module /path/
 ' Expression expected.

Note that this error is only shown the first time after deleting cache. Any change to the file results in a succesfull message.

**Comment by nchanged** [comment]
version? It should work just fine with `fuse-box@next` 
But you'd need a migration
https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md

**Comment by bogdandv** [comment]
fuse-box@next420
does it work in the newest version?

**Comment by nchanged** [comment]
yes optional chaining is supported there

**Comment by bogdandv** [comment]
can confirm all works well
