### ISSUE TITLE
How to use .env file in process.env.some-var-form-.env?

### ISSUE THREAD

**Issue by Relaxe111** [fuse-box/fuse-box#1907]
Hello i'm apolorgyze if it is stupid question but i can't figure out how to import env variables from .env file? is use fuse-box4. I managed to find out that is a env variable in fusebox and from there i can add variables but i need to read them from .env like files from project root location for example.
Eventually have a posibility to specify which .env.--environment to use in development and production?
thanks

**Comment by nchanged** [comment]
https://www.npmjs.com/package/dotenv
I hope that answers your question

**Comment by Relaxe111** [comment]
I need that for my react spa application. Shall I use dotenv for in react too?)

**Comment by Relaxe111** [comment]
Ohh sorry I'm so stupid. I shall try dotenv)

**Comment by Relaxe111** [comment]
By the way is fusebox 4 production ready?

**Comment by nchanged** [comment]
I think all of us are using v4 for production, the compiler is stable , I am just polishing what's left

**Comment by Relaxe111** [comment]
Wonderful. Thank-you for a such cool product.
