### ISSUE TITLE
Is possible to do smaller bundles with fusebox 4?

### ISSUE THREAD

**Issue by Relaxe111** [fuse-box/fuse-box#1908]
Hello I compiled one of my projects with fusebox 4 and total size (gzipped is 1.1 mb) while with my old bundler give me 870 kb. I found out that there is something with tree-shaking. 
What possibilities do I have to minimize bundle med fusebox? Maybe it is written about this somewhere? Thnks.

**Comment by nchanged** [comment]
V4 doesn't have tree shaking yet. So yes, that's the reason. although we have a full blown analysis implemented, we just need to implemented an algorithm

**Comment by Relaxe111** [comment]
Cool. Is there any expectations where we could see this feature on v4?

**Comment by nchanged** [comment]
What do you mean by expectations ? I will do it whenever I have time for it, unless someone else does it before me

**Comment by Relaxe111** [comment]
I see. Thnks help.
