### ISSUE TITLE
[v4] Error bundling import from a type definitions only module

### ISSUE THREAD

**Issue by a-neumann** [fuse-box/fuse-box#1909]
I have a module in my repo that is goning to be bundled and has this import of "csstype" in it that is re exported

```
export { FontFace } from "csstype";
```
I get this warning when bundling:

```
FuseBox 4.0.0-next.430
     Mode: development
     Entry: C:\path-to-my-repo\src\index.tsx

  compiler Completed node_modules/fuse-box/modules/fuse-box-hot-reload/clientHot  compiler Completed node_modules/@babel/runtime/helpers/esm/assertThisInitializ  compiler Completed node_modules/@babel/runtime/helpers/esm/taggedTemplateLiter  compiler Completed node_modules/@babel/runtime/helpers/esm/isNativeReflectCons  ⚠️  Error while resolving csstype in src/styles/index.ts

   WARNING   Completed with 1 warning in 1s 403ms
```
When i try to open the dev server page in the browser (Firefox), it says:

`Error: Module csstype was not found`

What may be special with csstype is that it contains no JS code, just Typescript interfaces for CSS.
The same happens when i import csstype with `import type { ...`

I cleaned the cache (npm and fuse-box .cache folder).
Here are my package dependencies:
```
"csstype": "^2.6.10",
"fuse-box": "^4.0.0-next.430",
"ts-node": "^8.10.1",
"tslib": "^1.11.2",
"typescript": "^3.8.3",
```

**Comment by nchanged** [comment]
@a-neumann thanks for brining this up.
I believe `4.0.0-next.432` will fix your problem

```
export type { FontFace } from "csstype";
```

I've added the support for importKind in `432`. [This](https://github.com/fuse-box/fuse-box/pull/1910/files#diff-878a7045c59f1510de62da9b75e70cfb) should get it fixed
