### ISSUE TITLE
Got an error when a module has an empty export

### ISSUE THREAD

**Issue by dpinart-uxland** [fuse-box/fuse-box#1917]
Hi.
I'm trying to use fuse-box in a project that uses polymer webcomponents library. There are some modules in polymer (like /@polymer/polymer/lib/utils/boot.js) that do not export nothing and end with an empty export 'export {}'. Fuse-box compiles these modules fine but app crashes at runtime with the following error 'SyntaxError: export declarations may only appear at top level of a module'.

I can manually remove the empty export and then apps runs as expected.

Fuse-box version is 4.0.0-next.432.

You can reproduce this issue  in the following project
https://github.com/uxland/test-fuse-monorepo.git
just run 'yarn install' and yarn serve

**Comment by nchanged** [comment]
`fuse-box@4.0.0-next.435`
