### ISSUE TITLE
syntax error in vendor.js

### ISSUE THREAD

**Issue by karibertils** [fuse-box/fuse-box#1925]
I am testing fuse-box@4.0.0-next.435 on a working webpack project.

I deleted node_modules dist and .cache and I get
```SUCCESS   Completed without build issues```

vendor.js has this error
![image](https://user-images.githubusercontent.com/5122320/83342221-3f7ec980-a2dc-11ea-8c9d-a3c1e5c9e1f5.png)

Here is the original source line that is breaking
https://github.com/ianstormtaylor/slate/blob/44675c2080e3f6a2523170430bb92e426b7647e2/packages/slate/src/interfaces/editor.ts#L469

**Comment by nchanged** [comment]
@karibertils please verify the fix in `4.0.0-next.437`

**Comment by karibertils** [comment]
@nchanged working now :+1:
