### ISSUE TITLE
function default arguments error if value is exported

### ISSUE THREAD

**Issue by Zaitsev** [fuse-box/fuse-box#1927]
if `const` is exported and used as default value in function in the same module, default value is `undefined`

![image](https://user-images.githubusercontent.com/127843/84019604-c50c1480-a981-11ea-857d-53bb762c022c.png)

**Comment by nchanged** [comment]
Can't reproduce

```
export const initialState = {};
export const Some = (state = initialState) => {};
```

Compiles into:
```
exports.__esModule = true;
exports.initialState = {};
exports.Some = (state = exports.initialState) => {};
```

Tested with `4.0.0-next.438`

If you think it's still there, please re-open and provide a faulty snippet
