### ISSUE TITLE
html special symbols like '&nbsp' escaped

### ISSUE THREAD

**Issue by Zaitsev** [fuse-box/fuse-box#1928]
special symbols in JSX compiled as strings
![image](https://user-images.githubusercontent.com/127843/84052055-54302100-a9b0-11ea-8dc9-6cd4d9cb953c.png)

**Comment by nchanged** [comment]
Please verify the fix in `4.0.0-next.439`

**Comment by Zaitsev** [comment]
Verified - it works, thanks

**Comment by Zaitsev** [comment]
Unicode Hex Character Code &#x26a0; rendered wrong
