### ISSUE TITLE
Cache not found fixes

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#193]
This [line](https://github.com/fuse-box/fuse-box/blob/master/src/ModuleCache.ts#L241) and somewhere there, is very annoying. 

To reproduce.
* Bundle a project
* Hack into .fusebox folder
* Remove any of those files:

<img width="426" alt="screenshot 2017-02-16 22 17 06" src="https://cloud.githubusercontent.com/assets/1629088/23041623/c7a58b30-f495-11e6-8321-12f17f710591.png">

I don't have a solution yet. Just leave it be here for now.

**Comment by basarat** [comment]
Can we move cache to be in memory?

I had to delete the `.fusebox` folder to get it it to pickup my locally patched `module` files https://github.com/fuse-box/fuse-box/blob/36e437185bd684fccab20ffd6ad17f8dc21c9f58/modules/fusebox-hot-reload/index.js . Of course local patching isn't really recommened so feel free to ignore me 😄 :rose:

**Comment by devmondo** [comment]
@basarat  we already implemented memory caching algorithms it would be great to make it all in memory yeah :)

**Comment by nchanged** [comment]
It's all in memory, and yeah modules are treated like any other npm package

**Comment by nchanged** [comment]
It's  just when It failed  to retrieve a file from cache it does not re-trigger the bundle process on that package
