### ISSUE TITLE
fusebox 4 still doesn't work with aws-amplify

### ISSUE THREAD

**Issue by erikdao** [fuse-box/fuse-box#1930]
I'm trying to build a react webapp with fusebox v4 as bundler and `aws-amplify` for user authentication and I just can't get fusebox v4 and aws-amplify working (both 2.x and 3.x versions).

---

```
aws-amplify: 3.0.17
fusebox: ^4.0.0-next.439
react: ^16.13.1
```
---
My `index.ts` is as simple as this

```ts
import * as React from "react";
import * as ReactDOM from "react-dom";
import { Auth } from "@aws-amplify/auth";

import App from "./App";

const config = {
    cognito: {
        region: "us-west-2",
        userPoolId: "us-west-2_xxxxx",
        userPoolWebClientId: "abcdefg123455",
        authenticationFlowType: "USER_PASSWORD_AUTH",
        identityPoolId: "us-west-2:12345fghjd",
    },
}

Auth.configure(config.cognito);

ReactDOM.render(React.createElement(App), document.getElementById("root"));

```

Here is my `fuse.ts`

```ts
const fs = require("fs");
const path = require("path");
const branch = fs.readFileSync(".git/HEAD").toString().trim().replace("ref: ", "");
const hash = fs.readFileSync(`.git/${branch}`).toString().trim();

const production = process.env.NODE_ENV === "production";

const env = {
    ENV: process.env.ENV,
    NODE_ENV: process.env.NODE_ENV,
    VERSION: process.env.npm_package_version,
    BUILD: `${branch}:${hash}`,
};

console.log(env);

import { fusebox } from "fuse-box";

const fuse = fusebox({
    env,
    entry: "src/index.ts",
    target: "browser",
    webIndex: {
        template: "src/index.html",
    },
    sourceMap: true,
    devServer: !production && {
        httpServer: {
            port: 8081,
        },
        proxy: [
            {
                path: "/api",
                options: {
                    target: "http://localhost:8000",
                },
            },
        ],
    },
  
    logging: {
        level: "verbose",
    }
});

production ? fuse.runProd() : fuse.runDev();
```

When I try to compile and start the dev server with: `./node_modules/.bin/ts-node fuse.ts`

I've always got this error:
```
  proxy [HPM] Proxy created: /  -> http://localhost:8000
  development HMR server is running on port 8081
  ⚠️  Error while resolving http2 in node_modules/@aws-sdk/node-http-handler/build/node-http2-handler.js

   WARNING   Completed with 1 warning in 7s 353ms
```

I also tried to install the `http2` package, the compilation error was disappeared by when I accessed `localhost:8081/`, I received the following error:
<img width="589" alt="Screen Shot 2020-06-13 at 16 55 41" src="https://user-images.githubusercontent.com/26970731/84565902-dcd70480-ad96-11ea-9a5b-33206ad70429.png">

<img width="419" alt="Screen Shot 2020-06-13 at 16 56 21" src="https://user-images.githubusercontent.com/26970731/84565907-e1032200-ad96-11ea-99a8-ad7c6c388de6.png">

The issue seems to be from the `@aws-sdk` version 3.x. I've also tried to downgrade `aws-amplify` and `aws-sdk` to version 2.x but similar errors are still occurred.

---
Previously, in another project, I was able to get fusebox v3.x to work with aws-amplify 2.x, but I really want to upgrade both things to latest versions because of all great improvements their new versions have. 
I'm also well-aware that this might not be a fusebox issue, but I hope someone can shed some lights on how to resolve this problem.

**Comment by nchanged** [comment]
@erikdao it looks like there is no shim for http2 package. To solve this issue, do the following:

```ts
fusebox({
  modules : ["./shims"]
})
```


Create a folder `shims/http2` add copy-paste an appropriate shim package for http2 for the browser. I am pretty sure it doesn't require much since it's a browser build.

**Comment by erikdao** [comment]
@nchanged Thanks for the response. I actually wasn't sure which "shim" to include for `http2` so I digged deeper into the above error trace and realized that the error was related to `runtimeConfig` so I changed my `fuse.ts` to include:
```
    alias: {
        "./runtimeConfig$": "./runtimeConfig.browser",
    },
```
And the issue was gone!
I'll close the issue.
