### ISSUE TITLE
HMR / auto-compile not working

### ISSUE THREAD

**Issue by SephReed** [fuse-box/fuse-box#1937]
I have no idea why, but I have to restart fuse with every change I make now. 

`cache: false` will break auto-bundling for .ts files for me.

`.scss` files never trigger a change and require stopping and starting fuse.ts

**Comment by SephReed** [comment]
Oof.  I don't know what's happening, but file changes not creating updates is a very serious bug.

Is there anyway I can get some insight into why it's not responding?  Maybe throw a console.log() on one of the lines near where it should be responding to file changes?

**Comment by SephReed** [comment]
@nchanged If you could help me figure out how deep this bug goes, I'd really appreciate it.

I need this feature to work and don't have long before I'll be forced to switch bundlers if it does not.

**Comment by SephReed** [comment]
Or, potentially, is there a way I can force it to reload with any file change whatsoever?

I would really rather it be inefficient than... well, very very broken.

**Comment by SephReed** [comment]
https://github.com/fuse-box/fuse-box/blob/e0f40f4d375fffe1221dfccbde2eb7fe97103d66/src/watcher/bindWatcherReactions.ts#L41-L43

`console.log("Watcher See", reactionStack);` => `Watcher See []`

I don't know why, but the reaction stack is empty.  This is the source of the bug.  For now, I'm just going to make it run no matter what by modifying my `.js` in `node_modules`.

**Comment by SephReed** [comment]
Okay.  I have mine working again.  It just runs `bundleDev_1.bundleDev({ ctx, rebundle: true });` on every `watcher_reaction` event.  Highly recommend figuring out this bug.  It's makes a huge difference the usability of this bundler.

**Comment by SephReed** [comment]
Okay.  Figured out the "bug".  It was semi-user-error.  My root file is not at the root of the project (src/components/App.ts).

These are the lines where changes were being filtered out:
https://github.com/fuse-box/fuse-box/blob/89c2f50375bfe5727ca2535e7df7f46ef19c2ac6/src/watcher/watcher.ts#L110-L127

Adding a line like this:
```
if (reactionStack.length === 0) {
  console.log(`Project file change outside of watcher scope: ${absPath}`)
}
```

After all the attempt to add to reactionStack have completed would make this user-error much, much less spooky.

**Comment by nchanged** [comment]
@SephReed you should just adjust the `watcher` paths
add `include` 

That happens because by default fuse picks the root folder of your entry file.

**Comment by SephReed** [comment]
I did figure it out.  But this is still very confusing behavior.

By default it seems it should watch all included files, regardless of root.  Only when specified would I expect it to exclude anything.

But I also trust there are very good reasons that is not the default, and if that is the case, it should (seemingly) give some sort of warning about the files it is not observing.

**Comment by nchanged** [comment]
We could print the default folder that is being watched. I think that might help

**Comment by jpike88** [comment]
This is actually due to a bug that got fixed earlier this week, the watcher root paths weren't locking in properly
