### ISSUE TITLE
web worker not loading

### ISSUE THREAD

**Issue by drayalliance-johnpittman** [fuse-box/fuse-box#1938]
I am trying to use a web worker just like your playground example but the files never get transpiled and moved. I have cloned this project and run the playground webworker example but that does not load the web worker either. What's missing?

```
ts-node -T playground/webworker/fuse
```

![image](https://user-images.githubusercontent.com/48923701/87596328-c75e3e80-c6a4-11ea-92fe-66f0a2f5c865.png)

**Comment by Ulydev** [comment]
Hey @drayalliance-johnpittman, could you explain how you solved this? I have the same issue. The worker isn't transpiled / does not appear anywhere in /dist, and throws the same "Unexpected token '<'" on load.
