### ISSUE TITLE
[v4] Fusebox 4 doesn't find `less` when using Yarn 2

### ISSUE THREAD

**Issue by ccapndave** [fuse-box/fuse-box#1939]
I'm using Yarn 2 "Berry" with PnP with a basic config containing a `less` plugin:

```
const app = fusebox({
  entry: "../app/js/loader.ts",
  target: "browser",
  plugins: [
    pluginLess("app/style/preloader.less", {}),
  ],
  webIndex: {
    template: "index.html.hbs"
  }
});

app.runDev();
```

Although I have `less` in my `package.json`, this fails with the following output:

```

  ⚙  FuseBox 4.0.0-next.439
     Mode: development
     Entry: /Users/dave/Projects/Couloir/ctp/title-cp/app/js/loader.ts

  compiler Completed app/js/loader.ts   FATAL  Fatal error when capturing /Users/dave/Projects/Couloir/ctp/title-cp/app/style/preloader.less

  - Module "less" is required, Please install it using the following command
  - npm install --save-dev less
```

It seems that the `require("less")` check is failing in the plugin, even though `require("less")` *does* work in `yarn ts-node` or in the `fuse.ts` script itself.

**Comment by nchanged** [comment]
hey, but that's related to the node.js module resolution. I doubt there is something we can do about it tho.

**Comment by ccapndave** [comment]
I wonder if this is something that can be fixed by using the latest version of `resolve`?  This is based on reading https://yarnpkg.com/advanced/migration#make-sure-you-use-resolve19, so I could be very wrong about this.

**Comment by charsleysa** [comment]
Hi @ccapndave I have been unable to produce your issue using yarn 2.

Can you please provide a small stripped down project with the issue so that I can reproduce it on my machine?

Thanks!

**Comment by charsleysa** [comment]
Closed due to inactivity.
