### ISSUE TITLE
Compilation fails with terser 5.0.0

### ISSUE THREAD

**Issue by misantronic** [fuse-box/fuse-box#1941]
When upgrading terser to 5.0.0 compilation doesnt work anymore.

`QuantumPlugin({ uglify: true })` fails with:

```
TypeError: Cannot read property 'toString' of undefined
    at UserOutput.write (/node_modules/fuse-box/core/UserOutput.js:123:46)
```

Somehow the `content` in that write-function is undefined.
According to the [terser changelog](https://github.com/terser/terser/blob/master/CHANGELOG.md) there are a few breaking changes:

> BREAKING: minify() is now async and rejects a promise instead of returning an error.
BREAKING: Internal AST is no longer exposed, so that it can be improved without releasing breaking changes.
BREAKING: Lowest supported node version is 10

I use node 10.15.3

**Comment by charsleysa** [comment]
@misantronic this sounds like an issue with fuse-box v3 which is no longer supported.
