### ISSUE TITLE
Compiler fails to erase non-value namespaces

### ISSUE THREAD

**Issue by warrenfalk** [fuse-box/fuse-box#1944]
imported.ts
```typescript
export namespace Dual {
    export type SomeType = {
    }
}
export const Dual = {} as any;
Dual.testing = "this should be visible outside the module";
```

index.ts
```typescript
import {Dual} from "./imported";
console.log("Dual.testing:", Dual.testing);
```

Output:
```
Dual.testing: undefined
```

Expected
```
Dual.testing: this should be visible outside the module
```

I confirmed that Typescript prints the correct output.

Fusebox compiles to:
```javascript
exports.__esModule = true;
var Dual;
(function (Dual) {})(Dual || (Dual = {}));
exports.Dual = Dual;
exports.Dual = {};
Dual.testing = "I can modify the object";
```

Typescript does this:
```javascript
Object.defineProperty(exports, "__esModule", { value: true });
exports.Dual = void 0;
exports.Dual = {};
exports.Dual.testing = "I can modify the object";
```

It looks like Fusebox does not erase the namespace above, but Typescript does because Typescript will erase a namespace that doesn't export any values (exporting types don't count)

**Comment by nchanged** [comment]
@warrenfalk yeah,  we don't really fully support namespaces, Is it in the third-party library ?

**Comment by warrenfalk** [comment]
Ha, well, it was about to be in a third party library.  I've built an idiomatic Typescript generator for protocol buffers that I'm getting ready to release, but the code it generates can't be used by fuse-box because of this issue.  I think, there might be a workaround which is to switch the order of the declarations (value first, then namespace).

When you say "we don't really fully support namespaces".  Does that mean "at the moment"... I mean, would you be open to a PR if someone else wanted to tackle it?

**Comment by nchanged** [comment]
@warrenfalk absolutely. However, namespaces are dead. They were introduced by TypeScript to help onboard those legacy es5 modules. But we are in 2020 now ;-)

**Comment by warrenfalk** [comment]
@nchanged, I hear you, but Namespaces remain the only way in typescript to declare Type names that are nested.  If you are generating `.ts` modules from `.proto` files, then there's no reasonable way around this.  If you have a `.proto` file with message nesting like "Shape.Polygon.Square" then the only way to have a `.ts` module with types of that name is to use namespaces.

```typescript
type Shape = {
}
namespace Shape {
    type Polygon = {
    }
    // etc...
}
```

If I were writing the Typescript here by hand, I would have separate modules in a folder structure instead of namespaces, but because we want the typescript module structure to mirror the protocol buffer file structure (and there are good reasons for this), we have to do the nesting of the type names within the module and namespaces are the only option.

**Comment by charsleysa** [comment]
Closed as wontfix.
