### ISSUE TITLE
[Sparky][Questions] Several questions regarding tasks/tasknames and help.

### ISSUE THREAD

**Issue by freehuntx** [fuse-box/fuse-box#1949]
## Background
After long time not using fusebox i came back to try it out again.
I saw the CLI Plugin is not available anymore, instead there is the "help" api which is neat!
If i understand correctly, its just triggered when you call fusebox with "help".
But i would like to show the help for example, if a invalid task was executed.

## Questions
**a)** Is it possible to show help when invalid/no tasks were run?
**b)** Is it possible to define a task name as regex/wildcard?
**c)** Is it possible to define a "fallback task"? E.g. if no task was found.
**d)** Is it possible to add "arguments" to a task? E.g. running "node fuse myTask --foo 0"

**Comment by nchanged** [comment]
@freehuntx currently Sparky in v4 is simplified and doesn't have the same functionality in v3. Pull requests are always welcome and the API is very simple ;-)

**Comment by freehuntx** [comment]
Ive created a PR for RegExp feature.
For CLI i might create a plugin :)

**Comment by charsleysa** [comment]
Closed by #1950
