### ISSUE TITLE
"missing fusebox.xml" 

### ISSUE THREAD

**Issue by Tyler-Nolan** [fuse-box/fuse-box#1951]
Hello friends,

I am running into a little issue when opening a webpage on one of my servers. I continuously get a "missing fusebox.xml" error. I have verified permissions(to the best of my knowledge) and i have verified that the .xml is actually in the folder where the web page says it can't find it at. I'm not sure what else to do to get the xml to be found. Has anyone ran into this issue before? Any help would be greatly appreciated.

**Comment by patrickmichalina** [comment]
@Tyler-Nolan are you talking about this framework https://en.wikipedia.org/wiki/Fusebox_(programming)? This repo is unrelated.

**Comment by Tyler-Nolan** [comment]
I've been sent around to a bunch of forums telling me that i'm in the wrong area and need to try *insert url here*. So i'm not sure. Just kind of hoping that one of these will have someone that knows what i'm talking about.

**Comment by nchanged** [comment]
It definitely doesn't belong here, we have no clue what you are talking about, sorry
