### ISSUE TITLE
DevServer enable HTTPS

### ISSUE THREAD

**Issue by wearevilla** [fuse-box/fuse-box#196]
I see there is a way to manipulate express, but I cant seem to get the fusebox devserver and HTTPS playing nicely.

Anyone out there have any advice? Thanks!

**Comment by devmondo** [comment]
@wearevilla  what is the issue? 

@nchanged i think we should have option `https:true`  and use `https.createServer();` 
i could take stab at it easy one!

**Comment by wearevilla** [comment]
if there is an easy 'https:true' option, that would be awesome! 😀

**Comment by devmondo** [comment]
@wearevilla  yeah that is what i suggested :)

**Comment by wearevilla** [comment]
@devmondo awesome! yeah i fumbled around with express but couldnt figure out where to find fusebox's call to http.createServer();

Thanks for your help!! :)

**Comment by wearevilla** [comment]
@devmondo i dont want to pressure you, i know you guys are working hard on fusebox and trust me, it is much appreciated. 

Im trying to use this in production though and time of the essence for me, so if anyone out there can point me in the right direction to doing this myself, the help would be much appreciated!!

Thanks again :)

**Comment by nchanged** [comment]
Please, take a look at this [seed](https://github.com/fuse-box/fuse-box-express-seed) 
You can use your own express server with any configuration!

**Comment by devmondo** [comment]
@wearevilla  you can fork fuse :)  and do below if you cant wait 

require `https` npm module in your code and instead of doing this`let server = http.createServer();` at
https://github.com/fuse-box/fuse-box/blob/master/src/devServer/HTTPServer.ts#L39
do this `let server = https.createServer();`

or you can ignore Fuse dev server and use your own express check this [seed](https://github.com/fuse-box/fuse-box-express-seed) 

we are trying our best, and the community is getting bigger and more awesome PRs are coming, so hang in there , Fuse will be the best ;)

**Comment by wearevilla** [comment]
AHHH you guys are awesome thank you!!!! Fusebox is the best thing thats happened since sliced bread!!!

**Comment by wearevilla** [comment]
Hey guys!

I followed the [Express Seed](https://github.com/fuse-box/fuse-box-express-seed) git and got it serving up on https, but the hot reload does not work anymore. 

Is there anything special I need to do to get the hmr working with https? 

I notice that fuse listens on a different port (4446) than what the server is on, and when visiting the port fuse is listening to the page says 'Upgrade Required'. Files are being served out over https at 3446 though. 

Thanks again for your help!!! You guys are awesome!

**Comment by wearevilla** [comment]
@devmondo @nchanged oh i forgot to mention, it looks like the hmr is trying to work, in the console i get the following error:

> ebSocket connection to 'wss://localhost:4446/' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED

I hope that helps! Thanks!

**Comment by nchanged** [comment]
Thanks, moving it here https://github.com/fuse-box/fuse-box/issues/208

**Comment by devmondo** [comment]
@wearevilla it seems we need to make some other changes on the rest of the pipeline :)
