### ISSUE TITLE
[3.7.1] add bigint support

### ISSUE THREAD

**Issue by draoncc** [fuse-box/fuse-box#1966]
Currently running into an Acorn error when trying to compile code that contains bigints (`0n`). Acorn is pending support with [7.0.0](https://github.com/acornjs/acorn/issues/862), until then [acorn-bigint](https://www.npmjs.com/package/acorn-bigint) could be used here: https://github.com/fuse-box/fuse-box/blob/v3.7.1/src/analysis/FileAnalysis.ts#L12 to amend the issue in FuseBox 3.7

**Comment by charsleysa** [comment]
Hi @draoncc, fuse-box v3 is no longer supported, please upgrade to v4.

**Comment by draoncc** [comment]
To my understanding, v4 doesn't yet offer the full set of features we're using to manage our monorepo with fusebox v3.

Thank you for the quick response though. :) I'm very excited for the first stable release of v4.
