### ISSUE TITLE
PostCSS plugin doesn't do anything with opts?

### ISSUE THREAD

**Issue by cellog** [fuse-box/fuse-box#197]
The PostCSS plugin does not pass opts into postcss.  Just seems like an omission.  The opts are essential for implementing CSS modules in PostCSS.

Thanks!

**Comment by nchanged** [comment]
Thanks!

**Comment by cellog** [comment]
👍

**Comment by unlight** [comment]
Wrong fix, please reopen.

**Comment by unlight** [comment]
@cellog Provide link to postcss plugin which requires options?

**Comment by cellog** [comment]
https://github.com/css-modules/postcss-modules/blob/master/README.md

**Comment by nchanged** [comment]
@unlight @cellog please figure it out guys
https://github.com/fuse-box/fuse-box/pull/211

**Comment by unlight** [comment]
Yep, #211 is the correct fix. It should work for me.

**Comment by cellog** [comment]
I just was pointing out that the opts were never used. Haven't installed 
fuse box yet, just looking over the source to see how it could work for me 
and saw that bug. So fix is probably fine since it has tests

**Comment by nchanged** [comment]
Thanks!
