### ISSUE TITLE
Unable to make "watcher" work based off docs

### ISSUE THREAD

**Issue by SephReed** [fuse-box/fuse-box#1976]
```
- editor
- web-ui
  - fuse.ts
```

I'm trying to watch `editor` in the example above.  The following config does not do it:

```
const fuse = fusebox({
  // omitted
  watcher: {
    include: [
      "../editor/src", 
      join(__dirname, "../editor/src"),  //
    ]
  }
});
```

How is watcher supposed to work?  https://fuse-box.org/docs/development/watcher

**Comment by nchanged** [comment]
```
 chokidarOptions?: WatchOptions;
  enabled?: boolean;
  ignore?: Array<string | RegExp>;
  include?: Array<string | RegExp>;
  /**
   * The root folder(s) to watch
   * Passed to chokidar as paths
   */
  root?: string | string[];```

That should be correct, I wonder is something wrong with the root?

**Comment by SephReed** [comment]
I tried setting root to `"."` and that didn't work either.  :/ 

I'm having to update my app file every time I update anything else.

**Comment by SephReed** [comment]
If I `console.log(join(__dirname, "../editor/src"))` it's exactly correct.

So I've given a verified correct absolute path to include and it's just not watching it for some reason.

**Comment by nchanged** [comment]
@SephReed try resetting `ignore` I think it might be just ignoring everything

**Comment by SephReed** [comment]
You're definitely on to something.  It is ignoring anything.  Setting `ignore` didn't fix it though.

```
watcher: {
    include: [
      join(__dirname, "../editor-ui/src"), 
      join(__dirname, "../engine/src")
    ],
    ignore: []
  }  
```

**Comment by SephReed** [comment]
Found the bug:  https://github.com/fuse-box/fuse-box/blob/3c04a72bdd544c5537402e6f49ad167c98a82232/src/watcher/watcher.ts#L158-L160

Watcher only watches `absRoots`.  So even if `includePaths` contains a path, only `absRoot` counts.

I can put a PR in to fix this.  My proposed solution:

1. If `watcher.root` is unset, simply add the `include` paths to `absPath`
2. If `watcher.root` is not set and an `include` path has no `absPath` to cover it, throw an error

In addition, if `watcher.include` is set but does not include a root folder of `entry`, give a warning.  Otherwise it won't be watched.
