### ISSUE TITLE
Bug: Automatically changed tsconfig.json at end of build process

### ISSUE THREAD

**Issue by DannyvanderJagt** [fuse-box/fuse-box#1979]
I've been using fusebox for a while now in production, definitely liking it. After upgrading from 4.0.0-next.447 to 4.0.0, without any other changes (or any change to the build file). The build process (prod) works fine, but in dev the process builds everything and then at the end it does something weird. It detects some kind of change and cleans everything out, except nothing changed.

To confirm:
- I've downgraded back to 4.0.0-next.447 (& 4.0.0-next.445), with empty node_modules install, everything works fine
- I've run the same config in prod, also works fine.
- I've run the config in dev, without a watcher, and it fails the same way.
*(For each test I cleaned out the cache & .fusebox)*

```
  webindex Detected changes to webIndex source. Will regenerate now
  webindex writing to index.html
  changed tsconfig.json

  ⚠️  Your configuration has changed. 
  ⚠️  Cache has been cleared 
  ⚠️  Exiting the process 
```

My config file:
```
import { fusebox, sparky } from 'fuse-box'
import * as path from 'path'
import * as fs from 'fs-extra'

const client = process.env.CLIENT || 'platform'

const entryDir = path.join(__dirname, '../src')
const garageDir = path.join(__dirname, '../garage')
const clientDistDir = path.join(__dirname, '../dist')
const serverDistDir = path.join(__dirname, '../dist/server')
const clientCacheDir = path.join(__dirname, `../.cache/${client}`)
const serverCacheDir = path.join(__dirname, '../.cache/server')

const fuseBaseConfig = {
  sourceMap: true,
  modules: ['node_modules'],
  env: {
    NODE_ENV: 'development',
    CLIENT: process.env.CLIENT
  },
  webIndex: {
    template: `${entryDir}/index.html`
  },
  stylesheet: {
    paths: [entryDir, './node_modules']
  }
}

class Context {
  isProduction
  runServer

  getServerBundle = () => (
    fusebox({
      ...fuseBaseConfig,
      cache: {
        enabled: true,
        root: serverCacheDir
      },
      target: 'server',
      entry: `${entryDir}/index.tsx`,
      devServer: false,
      watcher: {
        enabled: this.runServer
      }
    })
  )
  getClientBundle = () => (
    fusebox({
      ...fuseBaseConfig,
      cache: {
        enabled: true,
        root: clientCacheDir
      },
      entry: `${entryDir}/index.tsx`,
      target: 'browser',
      devServer: this.runServer,
      watcher: {
        enabled: this.runServer,
        include: [entryDir, garageDir]
      }
    })
  )
}

const { rm, task } = sparky<Context>(Context)

const clientBundleOutput = {
  uglify: false,
  bundles: {
    app: 'app.js',
    distRoot: clientDistDir
  }
}

const serverBundleOutput = {
  bundles: {
    app: 'ssr-app.js',
    distRoot: serverDistDir
  }
}

task('default', async (ctx) => {
  ctx.runServer = true
  ctx.isProduction = false
  
  await fs.copy(`${entryDir}/core/assets`, `${clientDistDir}/assets`)

  const client = ctx.getClientBundle()
  await client.runDev(clientBundleOutput)
})

// With SSR
task('start-with-ssr', async (ctx) => {
  await rm(clientDistDir)
  await rm(serverDistDir)

  ctx.runServer = true
  ctx.isProduction = false

  const client = ctx.getClientBundle()
  await client.runDev(clientBundleOutput)

  const server = ctx.getServerBundle()
  const { onComplete } = await server.runDev(serverBundleOutput)
  onComplete(({ server }) => {
    server.start()
  })
})

task('build', async (ctx) => {
  await rm(clientDistDir)
  await rm(serverDistDir)

  ctx.runServer = false
  ctx.isProduction = true

  const client = ctx.getClientBundle()
  await client.runProd(clientBundleOutput)

  const server = ctx.getServerBundle()
  await server.runDev({
    ...serverBundleOutput,
    uglify: true
  })

  await fs.copy(`${entryDir}/_redirects`, `${clientDistDir}/_redirects`)
  await fs.copy(`${entryDir}/assets`, `${clientDistDir}/assets`)
})
```

**Comment by nchanged** [comment]
@DannyvanderJagt that must be related to `tsconfig.json` file that has been detected by the watcher. Make sure that the watcher is ignoring it. I think that the tsconfig.json is being copied to dist folder somehow and that triggers the watcher to clean it all.

**Comment by jpike88** [comment]
I had this problem to when updating from 4.0.0-next.443 to 4.0.0

**Comment by nspaeth** [comment]
I have also had this problem and asked about it in slack.

**Comment by jpike88** [comment]
Ok it looks like I solved it.

My watcher config used to have an ignore, but now I used an include instead and it worked good.

old:

```
watcher:  {
					ignore: ['server'],
			  }
```

new: 

```
watcher: {
			include: ['./client/src/components/'],
		},
```

I think it's really just a config thing. ill close unless someone still has problems

**Comment by jpike88** [comment]
im wrong its still a problem. reopening

**Comment by jpike88** [comment]
-"chokidar": "3.4.3",
+ "chokidar": "3.5.1",

https://github.com/fuse-box/fuse-box/commit/0c14846959e2aadbdd34050e9b77192102b5721d#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L32

This is maybe the issue

**Comment by mayyyc** [comment]
have the same issue on mac but works fine on linux, maybe it's mac related.

**Comment by DannyvanderJagt** [comment]
A couple of findings:
- `tsconfig.json` doesn't seem to be copied into `dist`
- excluding `tsconfig.json` doesn't help
- I forked fusebox (`4.0.1-next.1`) and downgraded chokidar to `3.4.3`, also no change.

**Comment by jpike88** [comment]
problem still exists on ```^4.0.1-next.4```... downgrading back to ```4.0.0-next.447```

**Comment by jpike88** [comment]
im going to fix this this week, did anyone else manage to get any more insight?

**Comment by jpike88** [comment]
I've found the issue. @warrenfalk this function ```excludeRedundantFolders ``` isn't working right :(

The root path I specified: [ '/Users/joshpike/Projects/aquipa/server/src/' ]

The root it forced: [ '/Users/joshpike/Projects/aquipa' ]

I'll fix the function up now
