### ISSUE TITLE
angular 11.0.6 breaks with runProd + ES5 target

### ISSUE THREAD

**Issue by jpike88** [fuse-box/fuse-box#1983]
**UPDATED**

How to repro:

- Use angular_playground in this repo
- Use Typescript version 4.1.4
- Run something like node-check-updates on the angular_playground, which will fast forward angular to 11.1.2
- add ```buildTarget: 'ES5'``` to runProd config
- Look at page, you will see a broken template tag (See screenshot)
<img width="475" alt="Screenshot 2021-02-10 at 1 22 24 AM" src="https://user-images.githubusercontent.com/9585787/107409149-6f09f500-6b3e-11eb-9e0d-a87330bdb00c.png">

This issue is not present with angular 11.0.5, it appears when switching to 11.0.6.

Here's code to easily install/switch between versions:

```npm i @angular/animations@11.0.5 @angular/common@11.0.5 @angular/compiler@11.0.5 @angular/core@11.0.5 @angular/forms@11.0.5 @angular/platform-browser@11.0.5 @angular/platform-browser-dynamic@11.0.5 @angular/router@11.0.5 @angular/cli@11.0.5 @angular/compiler-cli@11.0.5 @angular/language-service@11.0.5 --force```

**Comment by jpike88** [comment]
@nchanged I tried a couple of other targets like es2015, es6 and they worked ok, just es5 doesn't work

**Comment by jpike88** [comment]
@nchanged breakthrough! issue is related to angular version, starts to happen between version 11.0.5 and 11.0.6

**Comment by jpike88** [comment]
completely forgot about this. looks like this is blocking till I can figure it out

**Comment by jpike88** [comment]
@nchanged any clue/thoughts about this? it's a weird one

**Comment by jpike88** [comment]
Somewhere in the following commits, something broke fuse-box.

https://github.com/angular/angular/commits/master?before=5b9c981b6d4e4f96236858773f84750a46260986+35&branch=master
https://github.com/angular/angular/commits/master?after=5b9c981b6d4e4f96236858773f84750a46260986+21&branch=master

@nchanged does a quick skim of these show anything problematic? I'm going to build specific commits and find the breaking one now

**Comment by jpike88** [comment]
@nchanged had another stab at this... no idea what could be causing it.

**Comment by nchanged** [comment]
@jpike88 does it happen without typescript? I mean if you remove buildTarget: 'ES5'

Because if it's ok, that means that the actual typescript is corrupting your build.

**Comment by jpike88** [comment]
without ES5, it builds fine.

I've tried with typescript 4.0.2 all the way to current 4.4-rc

I've tried with angular 11.0.6 onwards, up until 12.2.1...

The only thing I can clearly tell is breaking anything is when angular 11.0.5 upgrades to 11.0.6. 11.0.5 even works with latest typescript. and there are no issues reported regarding TS causing template binding to just not work.

I think something weirder is going on

**Comment by jpike88** [comment]
@nchanged will you have some time in the next week or two to investigate? I've tried a few times to diagnose the problem here and am out of ideas

**Comment by nchanged** [comment]
First make the build without ES5, then take this module and try compiling
it in the playground. I think we will see the differences. It's most
definitely a typescript problem..

**Comment by jpike88** [comment]
All my testing has been in the playground

**Comment by nchanged** [comment]
I mean here =>
https://www.typescriptlang.org/play

**Comment by jpike88** [comment]
I took both the app.js and vendor.js, and converted them in the TS playground using the ES5 target. I then pasted them back into their files locally.. worked fine

**Comment by jpike88** [comment]
closing cause I'm just going to drop es5 support
