### ISSUE TITLE
4.0.0 pluginSass: using scss variable for resources 

### ISSUE THREAD

**Issue by dloibl** [fuse-box/fuse-box#1984]
Hi,

we are migrating a quite large codebase from 3.7.1 to 4.0.0 and I'm almost there 👍. Just having the problem that 
css resources are not collected when the import url is using scss variables. 
Unfortunately I can't change this since it's third party scss.

In 3.7 I chained SassPlugin -> CssPlugin -> CssResourcePlugin, so I guess it worked there since scss variables where already resolved.

Should this work in 4.0.0 out of the box? Or can I somehow resolve css resource after the sass compiler has run?

So this works perfectly fine:
```styles.scss
.icon {
  background: url("icons/some.svg");
}
```
But not when using a variable:
```styles.scss
$icon-path: "icons/some.svg";
.icon {
  background: url($icon-path);
}
```

**Comment by nchanged** [comment]
@dloibl hey, that isn't supported, what you could do instead is:
```
$icon-path: "icons/";
.icon {
  background: url($icons/some.svg);
}
```

that configuring `stylesheet.macros`

```
stylesheet : {
  macros : { $icons : "that path"}
}  
```

**Comment by dloibl** [comment]
Thanks @nchanged for the quick reply. Unfortunately the svg file names are also wrapped in scss variables so I would need a lot of macros there. But I might be able to do it dynamically.

My current workaround is to copy those resources manually to `dist/resources/images` with sparky.
