### ISSUE TITLE
sparky src.dest base parameter error

### ISSUE THREAD

**Issue by Zaitsev** [fuse-box/fuse-box#1985]
I'm using  project full path like this `/a/b/c/SRC/d/e/f/SRC/assets`
then 
```
    await src('./src/assets/**/*.ttf')
        .dest('./dist/renderer/assets','./SRC')
        .exec()
    ;
```
`dets` base path is `./src' and in [sparkyChain.runActivities](https://github.com/fuse-box/fuse-box/blob/3c04a72bdd544c5537402e6f49ad167c98a82232/src/sparky/sparky_chain.ts#L33)
file path is split into 3 parts 
```
[
'/a/b/c/',
'/d/e/f/'
'/assets/fonts/some.ttf'
]
```
and[ s[1] ](https://github.com/fuse-box/fuse-box/blob/3c04a72bdd544c5537402e6f49ad167c98a82232/src/sparky/sparky_chain.ts#L51)is a wrong base path.
I think is should use just last, not 1 or 2 or any other hard-coded part number.

**Comment by charsleysa** [comment]
Closed by #1987.
