### ISSUE TITLE
alias with absolute path on fuse-box@v4

### ISSUE THREAD

**Issue by zeniroy** [fuse-box/fuse-box#1992]
Hi, recently i moved to v4 from v3.
On v3, i was using homeDir option for alias some files on my project.
With homeDir, i could use "\~/" for aliasing path from project root.
But on v4, there is no homeDir option.
So i tried to use absolute path for aliasing instead of "~/", but it didn't work.

Is there anyway to alias file of absolute path? or path from project root?

**Comment by nchanged** [comment]
@zeniroy you can still use aliases with fusebox, on top of that you can tsconfig `baseDir` to define your home directory and then referencing that directly

```
import "components/something"
```

or 

```
import "src/foo"
```

Depends on your baseDIr in the tsconfig

**Comment by zeniroy** [comment]
How about "js" file? also influenced by baseDir of tsconfig?

**Comment by nchanged** [comment]
yes, no problem there too.

**Comment by zeniroy** [comment]
Ok, i see. Thanks a lot!
