### ISSUE TITLE
Difference between test and context.allowExtension()

### ISSUE THREAD

**Issue by Shepless** [fuse-box/fuse-box#20]
Hi,

Thanks for the awesome tool! I've been playing writing some basic plugins and I'm not 100% sure here. What is the difference between setting `test` in the plugin constructor and `context.allowExtension()` inside of of the `init()` method?

Many Thanks.

**Comment by leon-andria** [comment]
test is used to match your file path (or extension) and allowExtension() enable you to add your custom file extension if it doesnt in the default wellknown extension ie .html, .css, .jsx, .js,.ts, .json

**Comment by nchanged** [comment]
Ok, some people using weird naming like ''my.module.name", so in order to understand that, we have to have a list with allowed extensions.

**Comment by TombolaShepless** [comment]
@nchanged yeah I think the allowedExtensions should probably be abstracted out from a per plugin basis and to be a "top level config option". The plugin has it's own `test` to determine if it should transform the file, whether that file is originally included (in my mind) isn't the plugins duty.

Let me know what you think.

**Comment by nchanged** [comment]
@TombolaShepless I agree with 100%. For now, it's there for a good reason. Many tests will fail. Javascript projects are crazy, and sometimes people use so weird conventions all over the place. It must be treated with care.  And `FuseBox` respects them all.

I know that part may cause confusion, I will try to resolve it as soon as I have finished with other critical fixes.

**Comment by nchanged** [comment]
We have to stick to it for now... 
Let's bear that in mind and make it simpler when a solution is found.

I am closing it now.
