### ISSUE TITLE
Loader Plugin documentation

### ISSUE THREAD

**Issue by leon-andria** [fuse-box/fuse-box#202]
To make a doc more readable for any level, the code written should be more explicit: http://fuse-box.org/#loader-plugins

The exemple code here is like "obfuscated" for people that not familiar with this syntax.

**Comment by nchanged** [comment]
Agreed, we need to have a seed as well!

**Comment by nchanged** [comment]
Let's kindly ask @basarat to put some examples here https://github.com/fuse-box/fuse-box-hmr-examples ;-)

@basarat you have a write access. Thanks a lot!

**Comment by leon-andria** [comment]
Excellent! Thank you

**Comment by basarat** [comment]
@leon-andria code is what is used in here : https://github.com/fuse-box/fuse-box-ts-react-reflux-seed so you can take it for a spin and play with it :heart:

Will add a blog post once a few more things are done :rose:

**Comment by basarat** [comment]
> The exemple code here is like "obfuscated" for people that not familiar with this syntax.

TypeScript syntax: Can't help much there, but I did [write a free book on it](https://github.com/basarat/typescript-book) Any attempt to explain the types without TypeScript generally results in creating a *new* syntax that you have to infer yourself while reading docs :rose: 

Over all code complexity: 
- `FuseBox.flush`: Function is not documented right now, but used in HMR. @nchanged can I have a short description of what the function does. I will add to docs :rose:
- `FuseBox.dynamic` already covered : http://fuse-box.org/#dynamic-modules :rose:
- `FuseBox.import` already covered : http://fuse-box.org/#import 
- `FuseBox.mainFile` not documented. Its the main entry point for the default bundle. Will add to docs :rose:

The default HMR behavior used these function already. You now get to customize how you call them. Does that clear stuff up? :rose:

**Comment by basarat** [comment]
Simplified the docs to remove the concept overload. The objective should have been just to show how to add a plugin and I think https://github.com/fuse-box/fuse-box/pull/221 achieves it well :rose: :heart:
