### ISSUE TITLE
FuseBox console log provider

### ISSUE THREAD

**Issue by leon-andria** [fuse-box/fuse-box#203]
Is it possible to have a provider for the FuseBox console.log during execution?

**Comment by nchanged** [comment]
what console.log sorry? you mean just logging?

**Comment by devmondo** [comment]
@nchanged  i think he means the output of fusebox bundling log details yea, custom providers allows the log to be customized and fed to other things like logging in database,etc...

**Comment by nchanged** [comment]
Sure, it's all happening here.
https://github.com/fuse-box/fuse-box/blob/master/src/Log.ts

We need specs for that

**Comment by devmondo** [comment]
i think simple TS interface would do

**Comment by leon-andria** [comment]
@nchanged The link you provided is good. It's what i meant. @devmondo, you understand my requirements.
I would like to make the output to a different stream rather than having it just in a console. For instance, i would like to broadcast it remotely.

**Comment by devmondo** [comment]
@leon-andria  yeah interface for that, then we implement logProvider option on bundler will do , right @nchanged ?

**Comment by leon-andria** [comment]
@devmondo Just to be clear, I would like to forward the output, not to implement the log.

**Comment by devmondo** [comment]
Unfortunately, we won't be able to provide this, but our logging is very rich now, especially with `debug` option.

we will close this for now but let us know otherwise :)

**Comment by aretecode** [comment]
@devmondo I do have this on my radar so keep it open

**Comment by devmondo** [comment]
if you use Fuse in node process, u can chain the log to that process output, will close this for now but let us know otherwise :)
