### ISSUE TITLE
Interceptor

### ISSUE THREAD

**Issue by leon-andria** [fuse-box/fuse-box#205]
I would like to know if there is a way to intercept all require, import, FuseBox.import calls ?
I should be good to intercept every requests on modules, packages, ....
So having a such implementation would be nice.

**Comment by nchanged** [comment]
http://fuse-box.org/#fusebox-events

**Comment by leon-andria** [comment]
Awesome, this is enough for me as long as Any import statement call or FuseBox.import goes this event.
