### ISSUE TITLE
Lazy import during bundling process

### ISSUE THREAD

**Issue by leon-andria** [fuse-box/fuse-box#206]
When we bundle, we do import or require at the beginning of the file. But we can also do a require inside a function.
Does the bundle process will detect the dependency required inside the function?
Also, what happen if we do FuseBox.import() ? or FuseBox.Lazy() ? Does the bundle process will detect the deps ?

How about having a convention to say that it's lazy ?
import { ImLazy } from ':~/libs/code-mirror'

Notice the "double colon" (:) before the "tilde" (~), this is just for example but other meaning character would be great. ImLazy will like a promise that waiting for a call by the developper.
```
ImLazy.import(() => {
   ....
})
````

The purpose of this is to unify the API rather than having multiple way to do something. Also, the benefit I can have here is to bundle separately some lazy package.

**Comment by nchanged** [comment]
Good suggestion, let's move the discussion here https://github.com/fuse-box/fuse-box/issues/185

**Comment by nchanged** [comment]
#312

**Comment by devmondo** [comment]
To Focus efforts and make sure your suggestions are taken into account we will close this and move to #312 :)
