### ISSUE TITLE
Ability to load all modules in folder

### ISSUE THREAD

**Issue by devmondo** [fuse-box/fuse-box#21]
here is one case we are facing on a project,

we have 100 files in folder, and each has default export, so we need those exports to be added to an array when loaded, the current workflow is to have 100 import statements! then after import we add each module manually to the array.

but `FuseBox` has awesome Lazy Loading feature, so if we can do the following it would be awesome
`FuseBox.import('somePath/myModules/*')` or `require ('somePath/myModules/*')`

as we know when using`FuseBox`,  `require` or `FuseBox.import` has second param as callback, so we can do this
```
let dynamicModules = [];
FuseBox.import ('somePath/myModules/*',function(results){
    results.forEach(function(module){
        dynamicModules.push(module.default);
    })
})
```
100 lines of code can be shortened to 5 lines!!!

i also think that the path should respect globbing pattern, as the target folder may have CSS, image, etc... but we are only interested in loading JS files.

**Comment by nchanged** [comment]
`FuseBox.import('somePath/myModules/*')` should be working synchronously. Because you cannot require a bunch of unknown files via ajax. But it will work with a callback as well (it does not matter)

**Comment by devmondo** [comment]
@nchanged of course you are right, i was just merely referencing the syntax

**Comment by nchanged** [comment]
[Implemented](https://github.com/fuse-box/fuse-box/blob/master/README.md#wildcard-import)

**Comment by leon-andria** [comment]
Just confirm that this works pretty nicely.

**Comment by nchanged** [comment]
Thanks, great!

**Comment by devmondo** [comment]
works awesomely!!!

also tested globbing and works exactly as it should be.

for anyone who sees this thread in the future, you can use this feature with both `FuseBox.import` and `require`.

i wll go ahead and close this thread as it is fulfilled ;)
