### ISSUE TITLE
serverBundle should not bundle in browser code

### ISSUE THREAD

**Issue by tyrsius** [fuse-box/fuse-box#212]
When using FuseBox for bundling code that will run on a server it provides `serverBundle`, but all this does is ensure the `FuseBox.isServer` check is always true. It could go much further and not include the browser shims and native node module redirects. It could cut out a good chunk of the resulting bundle.

This is probably going to be difficult, possibly even requiring a different LoaderAPI for server-only bundles. I wanted an issue to start tracking the work and get feedback, I'd like to contribute on this.

**Comment by nchanged** [comment]
I believe people were requesting that feature to work with `electron`. I think if you just running your code on server, you should not be doing that.. as fusebox knows the environment. 
Correct me if I am wrong.

**Comment by tyrsius** [comment]
FuseBox doesn't guess the environment wrong, the issue is that if you are bundling code that will never be used in a browser that some of what FuseBox adds is unnecessary.

**Comment by nchanged** [comment]
Right, that issue can be solved relatively easy. By checking for a condition `FuseBox.isBrowser` or `FuseBox.isServer`  and removing the unnecessary code. That's doable.

**Comment by nchanged** [comment]
serverBundle is removed in 2.0 
http://fuse-box.org:3333

Feel free to open a separate discussion. But I think we have many related issues. And one of them is `target` it will come in 2.0 at some point.
