### ISSUE TITLE
Bundler error

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#214]
Hi, when I include one of my own packages I receive following error during bundling and rebundlinf. I am not sure what am I looking at:

/Users/tomi/Github/packages/bimbam/.fusebox/cache/1.3.117/%2FUsers%2Ftomi%2FGithub%2Fpackages%2Fwebpack2-typescriptpublic%2Flouis.js/indexof%400.0.0 was not found

**Comment by tomitrescak** [comment]
This error does not appear in initial build but only on rebuild ... following that Chrome goes crazy boiling CPU trying to snatch 'indexof' in HMR loop.

What is this indexof anyways? Thanks for any help!

These are references I have in my package:

```
"dependencies": {
    "mobx": "x.x.x",
    "mobx-react": "x.x.x",
    "rc-collapse": "^1.6.12",
    "react": "^15.4.2",
    "typestyle": "^1.1.1",
    "yester": "x.x.x"
  },
  "devDependencies": {
    "@types/react": "^15.0.10"
  }
```

**Comment by leon-andria** [comment]
can you nuke your .fusebox cache ?

**Comment by tomitrescak** [comment]
I did, no luck, had to do `npm i indexof` and manually specify +indexof in bundler. It work like this so I consider this as resolved.

**Comment by nchanged** [comment]
You can autoImport API to fix that!
