### ISSUE TITLE
How to load a bundle from the main bundle ?

### ISSUE THREAD

**Issue by leon-andria** [fuse-box/fuse-box#217]
I have bundled 2 files:
1. bundle.js --> this is my main entry
2. p1.js is my second bundle

I would like to load p1.js from bundle.js code ?

Looks like Fuse.import or require or import not working, always return undefined !!!!
How to say to fuse, hey, this is another package that is not in bundle.js.

Below is my fuse bundle:
```` js
fuse.bundle({
  'build/runtime.js':'> index.ts [libs/*.ts] - libs/c.ts',
  'build/p1.js': '+ libs/c.ts'
})
````
How to put p1.js as a package called "my-awesome-lib" ?

**Comment by nchanged** [comment]
Like [this](https://github.com/fuse-box/fuse-box-ts-react-reflux-seed/blob/master/src/client/components/HelloWorld.tsx#L26) 

Thanks =)

**Comment by leon-andria** [comment]
This is browser, i want for nodejs.

**Comment by leon-andria** [comment]
Also how to called my-awesome-lib ? In this way multi bundle?

**Comment by devmondo** [comment]
@leon-andria are u asking for the ability to assign `packge` name for each entry in the multi bundle above ?

**Comment by nchanged** [comment]
@leon-andria you just require a bundle first. 
```js
require("./my-awesome-bundle.js");
// at this point everything is loaded into the scope
require("./my/awesome/module.js")
```

**Comment by nchanged** [comment]
+ When you bundle your code, make sure you don't have  require statements to bundles outside the homeDir

**Comment by nchanged** [comment]
Any updates?

**Comment by leon-andria** [comment]
I only test for nodejs because web is more easier.
p1.js is on the same place as bundle.js
This architecture is the requirements. And can have more than p2.js.
Also for the web, i wondering how to substitute path to a cdn url when you do just fuse.import("p1")?

**Comment by leon-andria** [comment]
A tips, think it like loading p1, p2 as a plugin to you application.
P1 contains supplain chain module
P2 contains human resource module

**Comment by devmondo** [comment]
@leon-andria `FusEBox.import` should work both client and server and in node it does not care about path as long as we can find it(it is lazy import) if it does not work then this is a bug.

regarding `cdn` yes same thing,  `FusEBox.import`  understands cdn imports.
does not not work with you partially or all cases above ?

**Comment by leon-andria** [comment]
When you do import, you dont put full cdn path.
You should have a mapping strategy where to load a package name by substitution or hook like a reverse reproxy:-)

**Comment by devmondo** [comment]
@leon-andria what i am saying is that FuseBox understands CDN imports thus don't bundle them and lazy load them.

what you are referring to is a la `JSPM` mapping, a feature on the roadmap :)

**Comment by leon-andria** [comment]
Sure, the mapping should be not statically.
The mapping can be provisionned at runtime by code. Not like in jspm that you predefined it in advance. You see what i mean?

**Comment by devmondo** [comment]
@leon-andria  great Idea, we need to enable more runtime stuff in Fuse as it is already so powerful, this would open the doors for wild possibilities!!!

**Comment by nchanged** [comment]
Please create another issue that describes the feature above. And reference this issue please

**Comment by leon-andria** [comment]
Great guys,
I will make the proposal architecture for the all concept of code splitting, lazy load, whatever the name we give it to all these things. 
Hope it will align everyone in the same level and making fusebox unique in javascript world:-)

**Comment by nchanged** [comment]
@leon-andria thanks!
Please, check that one as well https://github.com/fuse-box/fuse-box/issues/185#issuecomment-280257659

**Comment by leon-andria** [comment]
Looks like what i said here.
So i will sum up all of these like a pro and we decide when to implement it.

**Comment by nchanged** [comment]
@leon-andria absolutely, people seem to be frustrated with the code splitting. What we have in mind is `Dynamic Instructions` that come from the code itself.

**Comment by leon-andria** [comment]
Mate, you will get orgasm when you get my proposal.

**Comment by vegarringdal** [comment]
@leon-andria 

> You will enjoy to implement what is coming from the proposal i'm preparing.

Have you created a proposal ? Would like to see it

**Comment by leon-andria** [comment]
I'm polishing it now :-) take times to shape it like a Pro .

**Comment by vegarringdal** [comment]
ok, in an hour then 👍  😂

**Comment by leon-andria** [comment]
here we go 
[Fuse Code Splitting proposal.pdf](https://github.com/fuse-box/fuse-box/files/799469/Fuse.Code.Splitting.proposal.pdf)
Tell us about your feedbacks.

**Comment by nchanged** [comment]
#312
