### ISSUE TITLE
 do not require .babelrc

### ISSUE THREAD

**Issue by aretecode** [fuse-box/fuse-box#223]
- currently requires having a .babelrc file at root
- takes in a config so it should not be required to work

**Comment by devmondo** [comment]
@aretecode  currently you can use either inline config or `.bablerc` and none of them is required unless your code needs that like `babel plugins` etc...

in fact even if you provide `.babelrc` and you provide inline config, your inline config will override `.babelrc`

**Comment by aretecode** [comment]
<img width="757" alt="screen shot 2017-02-18 at 4 15 51 am" src="https://cloud.githubusercontent.com/assets/4022631/23093186/07b21c10-f591-11e6-8083-89cbe152b892.png">


without .babelrc, this error happens for me <img src="https://files.gitter.im/fusebox-bundler/Lobby/Edmi/Screen-Shot-2017-02-18-at-12.41.21-AM.png" />
even when I pass the config into babel plugin <img src="https://files.gitter.im/fusebox-bundler/Lobby/Edmi/Screen-Shot-2017-02-18-at-12.41.15-AM.png" />

**Comment by aretecode** [comment]
you can also see in this example https://github.com/aretecode/react-example

**Comment by devmondo** [comment]
@aretecode thanks alot for the report! we areinvestigating

**Comment by aretecode** [comment]
http://fuse-box.org/#babel-plugin
