### ISSUE TITLE
Cannot read property 'env' of undefined

### ISSUE THREAD

**Issue by JiDai** [fuse-box/fuse-box#225]
Hi,

I use `EnvPlugin` and I have an error in first call to `process.env` : `Cannot read property 'env' of undefined`
In the top of bundle I have a `__process_env__` object defined with all values
Modules have a row  at its top : `var process = require("process");`

What I am missing ?

**Comment by nchanged** [comment]
Could it be related to HMR? Can I refresh the page? That's a known bug on the list

**Comment by devmondo** [comment]
@JiDai  order of plugins matter, could you show your fuse config ?

**Comment by JiDai** [comment]
Here is my config : 

```

const fuseBox = new fsbx.FuseBox({
    homeDir: "static/app/",
    outFile: "./build/bundle.js",
    modulesFolder: "node_modules",
    plugins: [
        fsbx.EnvPlugin(env),
        fsbx.JSONPlugin(),
        [
            fsbx.SassPlugin({
                includePaths: [
                    path.resolve('./static/sass'),
                    path.resolve('./static/images')
                ]
            }),
            fsbx.CSSResourcePlugin({
                dist: "build/images",
                resolve: (f) => `/images/${f}`
            }),
            fsbx.CSSPlugin(),
        ],
        fsbx.SVGPlugin(),
        fsbx.BabelPlugin({
            config: {
                sourceMaps: true,
                presets: ["es2015", "react", "stage-0"],
                plugins: [
                    "react-hot-loader/babel",
                    "transform-class-properties"
                ]
            }
        })
    ]
});

``

**Comment by JiDai** [comment]
It happens at page load, not after HMR reload.

**Comment by basarat** [comment]
> Modules have a row at its top : var process = require("process");

Think this is invalid. `process` is a node global https://www.google.com.au/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=nodejs+process. Remove the line ` var process = require("process");` and try again :rose:

**Comment by JiDai** [comment]
My target is the browser. That's why I use this plugin, and this is the plugin that add these lines

**Comment by basarat** [comment]
> My target is the browser. That's why I use this plugin, and this is the plugin that add these lines

my bad. Sorry :heart:

**Comment by basarat** [comment]
I can actually use `process.env` in browser without `require('process')`. At least I can with webpack / browserify, is fusebox different here?

**Comment by JiDai** [comment]
I suppose, with wepack I have not this behaviour but I use the `DefinePlugin` to get `process.env` on browser

**Comment by devmondo** [comment]
@basarat  we have `envplugin` for this and that is what @JiDai  is trying to do :)

**Comment by nchanged** [comment]
So this test does not work for you? https://github.com/fuse-box/fuse-box/blob/master/test/process_variable.js

**Comment by JiDai** [comment]
The test pass.
I tried to debug in chrome on 2 similar project : 
On the first one, it fails and I have in compiled bundle `process` module contents : 

```
// for now just expose the builtin process global from node.js
module.exports = global.process;
```

On the second it works and I have the shim module

```
// shim for using process in browser
if (FuseBox.isServer) {
    if (typeof __process_env__ !== "undefined") {
        Object.assign(global.process.env, __process_env__);
    }
    module.exports = global.process;
    ...
```

It helps ?

**Comment by nchanged** [comment]
Hm, which modules are you trying to run?

**Comment by JiDai** [comment]
I don't understand. I just run node fuse.js

**Comment by nchanged** [comment]
Could you show the code please? Some test repo.

**Comment by aretecode** [comment]
https://github.com/fuse-box/fuse-box/pull/235 may be related

**Comment by JiDai** [comment]
I can't, it is a private project. I update all my deps to last version, I re-run and and the error is no more. But the process.env object is empty. I have find this in bundle.js

```
FuseBox.pkg("process", {}, function(___scope___){
___scope___.file("browser.js", function(exports, require, module, __filename, __dirname){ 

// shim for using process in browser

var process = module.exports = {};
```

I suppose another version of process module was resolved

**Comment by nchanged** [comment]
@JiDai yes! that's the problem, you have something that fusebox does not support. Any ideas on how to solve it?

**Comment by JiDai** [comment]
This is what I was looking for, I assumed that there were other dependencies to `process` module. I found 2 but after removing them, I still have the problem.

**Comment by JiDai** [comment]
I finally find it : I set `modulesFolder` to value 'node_modules' in fuse file. This causes  `this.context.customModulesFolder` to be true in `PathMaster.getNodeModuleInformation` and resolving fail. I removed the setting

**Comment by devmondo** [comment]
@JiDai  can we close this now :)

**Comment by nchanged** [comment]
Thanks!
