### ISSUE TITLE
 breaks dev server when just logging

### ISSUE THREAD

**Issue by aretecode** [fuse-box/fuse-box#226]
I wanted to contribute to the htmlplugin here https://github.com/fuse-box/fuse-box/blob/master/docs/builtin-plugins.md but the first thing I changed broke it

https://github.com/aretecode/react-example/tree/justlogs

<img width="336" alt="screen shot 2017-02-18 at 5 02 24 am" src="https://cloud.githubusercontent.com/assets/4022631/23093435/4e0a20fc-f598-11e6-8a9e-73656d738397.png">
<img width="1167" alt="screen shot 2017-02-18 at 5 02 16 am" src="https://cloud.githubusercontent.com/assets/4022631/23093436/50697118-f598-11e6-8570-d6df678d2dac.png">
<img width="243" alt="screen shot 2017-02-18 at 5 09 14 am" src="https://cloud.githubusercontent.com/assets/4022631/23093443/6910f5e2-f598-11e6-83ab-45b0947c1fed.png">

**Comment by nchanged** [comment]
So what is exactly broken?

**Comment by nchanged** [comment]
HTMLPlugin has no relation to your devServer whatsoever. You need to create your own HTML file next to your build.

**Comment by aretecode** [comment]
and so I learned it is nothing like https://github.com/ampedandwired/html-webpack-plugin 👍 
it is just exclusively html _loader_, thanks
