### ISSUE TITLE
💣🛅🏗🔙🔚  backend building exporting running issues

### ISSUE THREAD

**Issue by aretecode** [fuse-box/fuse-box#227]
see the comments in the files
https://github.com/aretecode/react-example/tree/moose

requiring the built file:
<img width="488" alt="screen shot 2017-02-18 at 5 46 59 am" src="https://cloud.githubusercontent.com/assets/4022631/23093672/a64724b2-f59e-11e6-9a66-30be165e56ba.png">

importing or requiring other files that should be being transformed with the babel loader:
<img width="418" alt="screen shot 2017-02-18 at 5 45 56 am" src="https://cloud.githubusercontent.com/assets/4022631/23093675/af2b1606-f59e-11e6-877e-b1419c2c3ff0.png">

**Comment by nchanged** [comment]
You code is not transpiled by babel.

**Comment by nchanged** [comment]
Closing this one now, it's better to discuss on gitter
