### ISSUE TITLE
@font-face best practice

### ISSUE THREAD

**Issue by wearevilla** [fuse-box/fuse-box#228]
Hi there!

Just wondering what the best practices are for utilizing and bundling up @font-face files with fuse-box.

Thanks!!!! :)

**Comment by devmondo** [comment]
@wearevilla `CSSResourcePlugin` will inline them and also inline images for you
http://fuse-box.org/#cssresourceplugin

**Comment by nchanged** [comment]
@wearevilla 
```
plugins : [
   [ CSSResourcePlugin({inline : true}), CSSPlugin() ]
]
```

**Comment by wearevilla** [comment]
You guys are the best! Thank you! :)

**Comment by wearevilla** [comment]
hey guys sorry to bother you again, adding the CSSResourcePlugin gives me the following errors:

- 'File contents for ... were not loaded. Missing a plugin?'
- WebSocket connection to 'ws://localhost:4444/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

Here is how i have it in my fuse.js file:
`cache : false,
    plugins: [
        fsbx.SVGPlugin(),
        [
          fsbx.CSSResourcePlugin({inline : true}),
          fsbx.LESSPlugin({outputStyle: 'compressed'}),
          fsbx.CSSPlugin()
        ],
        fsbx.BabelPlugin({
            test: /\.jsx$/, // test is optional
            config: {
                sourceMaps: true,
                presets: ["es2015"],
                plugins: [
                    ["transform-react-jsx"]
                ]
            }
        }),
        //fsbx.UglifyJSPlugin()
    ]`

Thanks again for all your great work and help!! :)

**Comment by nchanged** [comment]
Which file are you trying to import?

**Comment by devmondo** [comment]
@wearevilla  the order of plugins matter, can you move the `CSSResourcePLugin` after the `LessPlugin`

**Comment by devmondo** [comment]
maybe this can help
http://stackoverflow.com/a/33506169

**Comment by wearevilla** [comment]
Ah ok good to know! Thank you! 🙌🏻
