### ISSUE TITLE
importing modules that export default cause an issue

### ISSUE THREAD

**Issue by venil7** [fuse-box/fuse-box#229]
when importing for example `import createLogger from 'redux-logger';` this causes an issue,
a temporary fix I found is to use the following syntax:
`import * as createLogger from 'redux-logger';`

**error**
```
VM8348:7 Uncaught TypeError: redux_logger_1.default is not a function
    at eval (eval at <anonymous> (store.ts:15), <anonymous>:7:48)
    at Number.<anonymous> (store.ts:15)
    at d (store.ts:15)
    at w.require (store.ts:15)
    at Number.<anonymous> (App.jsx:5)
    at d (store.ts:15)
    at w.require (store.ts:15)
    at Number.<anonymous> (index.jsx:3)
    at d (store.ts:15)
    at Function.n.import (store.ts:15)
(anonymous) @ VM8348:7
(anonymous) @ store.ts:15
d @ store.ts:15
w.require @ store.ts:15
(anonymous) @ App.jsx:5
d @ store.ts:15
w.require @ store.ts:15
(anonymous) @ index.jsx:3
d @ store.ts:15
n.import @ store.ts:15
client.on @ store.ts:15
EventEmitter.emit @ store.ts:15
client.onmessage @ store.ts:15
```

**Comment by devmondo** [comment]
@venil7  that is the correct syntax for ES6 imports, if a package dont have exports

**Comment by aretecode** [comment]
same issue encountered here https://github.com/fuse-box/fuse-box/issues/227

**Comment by devmondo** [comment]
maybe this could help
http://stackoverflow.com/a/33506169

**Comment by venil7** [comment]
As per this article http://www.2ality.com/2014/09/es6-modules-final.html
a module may have default and named exports, if it has default export then I should be able to:
`import arbitraryName from 'library'`

if it has a number of named exports, then I could import them all under one name:
`import * as arbitraryName from 'library'`
and later use like `arbitraryName.hello()`

The issue I'm having is when library has default export: `export default const sum (a,b) => a+b;` 
and I'm unable to import it with arbitrary name, as described above, getting an error.

A simple example is React, I should be able to 
`import React, {Component} from 'react'`
instead I have to `import * as React from 'react';` to overcome the above issue..

**Comment by wagerfield** [comment]
Dropping this here as per @aretecode's suggestion https://github.com/59naga/babel-plugin-add-module-exports

It goes against the spec, but I think it would save a lot of headaches esp. when importing React when using JSX:

```js
// Currently have to do
import * as React from 'react'
import { Component } from 'react'

// Ideally want to do
import React, { Component } from 'react'
```

**Comment by devmondo** [comment]
@wagerfield  good analysis, we should work on that and find middle grounds for how this should function elegantly :)

**Comment by nchanged** [comment]
@wagerfield @venil7  will be resolved with introducing "imports" as we discussed earlier

**Comment by devmondo** [comment]
@wagerfield @venil7 the webpack team reached out to us earlier and asked us to stay within the specs realm so all the bundlers will align and users would not have strange behaviours

**Comment by wagerfield** [comment]
I do agree that the specs _should_ be followed...but there are soooo many React tutorials ([including the official React docs](https://facebook.github.io/react/docs/jsx-in-depth.html#react-must-be-in-scope) 😆 ) that use:

```js
import React from 'react'
export default function Button({ text }) {
  return <button>{text}</button>
}
```

...so the issue then becomes a case of either standing by the specs and responding to issues like this one where people are encountering the `Uncaught TypeError: some_module.default is undefined` _OR_ deviating from the spec to counter the erroneous usage of ES6 modules that people have grown accustomed to.

**Comment by devmondo** [comment]
If you are using Typescript with FuseBox, unfortunately, we can't do much as this is how it works. on the other hand, if you use Babel then there is already a plugin for it.

we will close this for now but let us know otherwise :)
