### ISSUE TITLE
Error when importing module by node_module/path

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#234]
In my scenario I generate vendor bundle.

In my code I do following requires:

```
const ReactElementPlugin = require('pretty-format/build/plugins/ReactElement');
const ReactTestComponentPlugin = require('pretty-format/build/plugins/ReactTestComponent');
```

These plugins are not referenced from the entry of the 'pretty-print' and possibly are not bundled in vendor.js.

As a result, FuseBox starts importing ReactElement and ReactTestComponent from xhr 'http://localhost:3000/pretty-format/build/plugins/ReactElement' which starts to produce unlimited loop and blows up the browser.

**Comment by devmondo** [comment]
@tomitrescak  we have seen this before, @nchanged we solved this issue before, anything wrong here ?

**Comment by nchanged** [comment]
@tomitrescak well, can you bundle them? =)

**Comment by tomitrescak** [comment]
Hi, what do you mean? I had to manually recreate the package (copy all files) in my app. Doing +pretty-print on main bundle did not help.

**Comment by nchanged** [comment]
ok, i see your point, you can't make 

```
+ pretty-format/build/plugins/ReactElement
```

Which is a bug, yes. What about having a functionality that would allow you to automatically extract dependencies. So pretty much anything external that your code requires. Would that help?

**Comment by tomitrescak** [comment]
What about extending the bundling process so that you would be able to specify which files go to which bundle. Example having:

```js
fsbx.FuseBox.init({
        homeDir: "src",
        ...
        bundles: [
            { match: /node_modules/, file: 'vendor.js' }
            { match: /my_module/, file: 'my_module.js' }
        ],
        outFile: 'app.js'
    }).devServer("> [client/index.tsx]");
```

Above, based on `outFile` and `bundles` definition would create three bundles. I no longer would have to manually specify all the modules I have to create for vendor bundle. How difficult would it be to implement this? Would you consider this?

**Comment by nchanged** [comment]
@tomitrescak did you read this one? 
https://github.com/fuse-box/fuse-box/issues/185#issuecomment-280257659

We have been discussing that a lot, and I think we are getting somewhere real interesting.

**Comment by tomitrescak** [comment]
@nchanged yeah, I read your reply. I also like where the discussion is going. Yet, this issue is orthogonal to the #185.
- The goal of #185 is to automatically split bundle at a **specific split point** and **dynamically** load the split bundle during runtine
- The goal of the proposal above is to split bundle with modules at **specific** path and create a bundle that is **statically** included in the app (e.g. via <script />).
- If we throw in **tree shaking** into the game, we suddenly have the holy grail of production builds ;)

**Comment by leon-andria** [comment]
Hi guys,

Just to keep in touch, my upcoming proposal will solve (the concept is almost done :-)) nicely these kind of requirements.

**Comment by nchanged** [comment]
Coming with the next one

**Comment by tomitrescak** [comment]
Guys, it still does not work for me. In my code I do: 'require('pretty-format/build/plugins/ReactElement')'

This require returns `undefined`.

The pretty-format is packaged in the vendor bundle with +pretty-format command.

**Comment by nchanged** [comment]
so, you do `pretty-format/build/plugins/ReactElement` right? You sure there is a file?

**Comment by tomitrescak** [comment]
Yes I'm sure, the only way to make it work was to add +pretty-format in the entry bundle (main bundle). But I'm happy with it as well.

**Comment by tomitrescak** [comment]
Guys, I am very confused. I cannot import HRM plugin as the require statement is always undefined.

```js
import {setStatefulModules} from 'fuse-box/modules/fuse-hmr'; // THIS FAILS as the import is always undefined

setStatefulModules(name => {
  return /state/.test(name);
});
```

this is my config

```js
fsbx.FuseBox.init({
        homeDir: "src",
        tsConfig : "tsconfig.fuse.json",
        cache: true,
        log: false,
        sourceMap: {
            bundleReference: '/libs/luis/luis.js.map',
            outFile: `${devReactFolder}/libs/luis/luis.js.map`
        },
        shim: {
            "crypto": {
                exports: "{ randomBytes: () => crypto.getRandomValues(new global.Uint16Array(1))[0] }"
            },
            "console": {
                exports: "{ Console: class Console { log(m) { console.log(m) } } }"
            }
        },
        plugins: [
            typescriptTransform,
            fsbx.JSONPlugin(),
            fsbx.TypeScriptHelpers(), [
                fsbx.CSSResourcePlugin({
                    resolve: (f) => `/resources/${f}`
                }),
                fsbx.CSSPlugin()
            ],
            
        ],
        outFile: `${devReactFolder}/libs/luis/luis.js`,
    }).devServer("> [client/modules/_stories/stories.tsx] +pretty-format +fuse-box", {
        httpServer: false,
        port: 5680
    });
```

And I tried clearing .fusebox cache, deleting file and whatnot ... do you see anything striking what am I doing wrong?

**Comment by tomitrescak** [comment]
OK. changing

```
.devServer("> [client/modules/_stories/stories.tsx] +pretty-format +fuse-box"
```

to

```
.devServer("> client/modules/_stories/stories.tsx"
```

helped, but I really want to isolate vendor bundle ... is this possible to do with my original config?

**Comment by nchanged** [comment]
`.devServer("> [client/modules/_stories/stories.tsx]"`
;-)

**Comment by tomitrescak** [comment]
@nchanged no luck, I had that +pretty-format +fuse-box there exactly because of the issue that those paths were not found.

**Comment by nchanged** [comment]
Why are you including fuse-box in your bundle?
@basarat could you help us here?

> import {setStatefulModules} from 'fuse-box/modules/fuse-hmr'; // THIS FAILS as the import is always undefined

**Comment by tomitrescak** [comment]
@nchanged it was a desperate attempt to get this running : import {setStatefulModules} from 'fuse-box/modules/fuse-hmr'

**Comment by suhdev** [comment]
Any update on this guys, I'm still getting this error, currently using react-sortable-tree, builds fine with webpack, but fuse-box seems to bundle packages fine up to a certain depth i.e. depenencies of dependencies, and then stops.

**Comment by nchanged** [comment]
@suhdev interesting? FuseBox doesn't care about the depth. Can you reproduce in the repository and create an issue?
