### ISSUE TITLE
FuseBox.defaultPackageName is undefined when package is not set

### ISSUE THREAD

**Issue by arabsight** [fuse-box/fuse-box#236]
when setting *package* in the options *FuseBox.defaultPackageName* returns the defined package name but when *package* is not set it returns undefined.
expected behavior: *FuseBox.defaultPackageName* should return *'default'* when the package is not set.

**Comment by devmondo** [comment]
@nchanged  is this a minor regression as a result of the new `package` refactoring ?

**Comment by arabsight** [comment]
I asked to make the defaultPackageName public a few days ago, and I just tested it, I don't know if its the result of *package* refactoring.

**Comment by arabsight** [comment]
here's the problem: https://github.com/fuse-box/fuse-box/blob/master/src/BundleSource.ts#L185 its adding it only if its not *'default'*

**Comment by nchanged** [comment]
@arabsight that's by design.
```
let pkg = FuseBox.defaultPackageName || "default"
```

**Comment by nchanged** [comment]
FuseBox is adding a lot of information to a bundle, that was an attempt to make it smaller =)

**Comment by arabsight** [comment]
that's what I'm doing, but it didn't seem right to hard-code *'default'* in my code

**Comment by nchanged** [comment]
Can we live with it for now? "default" name isn't going to be changed.
