### ISSUE TITLE
FuseBox event - import

### ISSUE THREAD

**Issue by leon-andria** [fuse-box/fuse-box#241]
as "before-import" is only called once if it's already loaded. Can we have this ?
FuseBox.on("import", (exports, require, module, __filename, __dirname, pkg) => {  
});

The goal is that we can be notified every time even if it's already laoded.

**Comment by nchanged** [comment]
It won't be possible, since FuseBox caches the imports. Circular dependencies won't work, a massive performance bottleneck will take place e.t.c That's how nodejs works btw.

**Comment by leon-andria** [comment]
I need it because i would like to know where in any place i do import or require. If its already loaded, the events will not be fired, thats make sense.
I want something that fired every time i do import.

**Comment by nchanged** [comment]
Yes, we can think about it. However it might affect the performance.

**Comment by leon-andria** [comment]
You are right but this is only dev mode and also we do not manipulate anything, just informational. Think it like you do a console.log inside it.

**Comment by devmondo** [comment]
According to the new `quantum` feature, `dynamic imports` and tree shaking. this is mostly not gonna happen as it would defeat the purpose of those new enhancements.

we will close this for now but let us know otherwise :)
