### ISSUE TITLE
FuseBox startup event

### ISSUE THREAD

**Issue by leon-andria** [fuse-box/fuse-box#242]
When the entry fusebox.main is called, can we have a kind of startup method that having the instance of fuse?
I would like for instance to create a plugin and this plugin will initialize the subscription to fusebox.on events.

**Comment by nchanged** [comment]
Closing this for now. Please feel free to check the latest bleeding edge version `fuse-box@2.0.0-beta.8`
and documentation for it http://fuse-box.org:3333 You are welcome to re-open it elsewise ;-)
