### ISSUE TITLE
Unable to import highlight.js

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#244]
It seems that I cannot import package "highlight.js" ... I suspect that bundler thinks of it as a javascript file.

**Comment by nchanged** [comment]
Thanks!
I will check it

**Comment by devmondo** [comment]
@tomitrescak 
just made a test and everything works

`npm install highlightjs -S`

code in app.ts
```js
import * as highlightjs from 'highlightjs';
import  'highlightjs/styles/default.css';
highlightjs.initHighlightingOnLoad();
```

code in index.html
```html
<pre><code>#include <iostream>

int main(int argc, char *argv[]) {

  /* An annoying "Hello World" example */
  for (auto i = 0; i < 0xFFFF; i++)
    cout << "Hello, World!" << endl;

  char c = '\n';
  unordered_map <string, vector<string> > m;
  m["key"] = "\\\\"; // this is an error

  return -2e3 + 12l;
}</code></pre>
```

result
![image](https://cloud.githubusercontent.com/assets/1266367/23123211/f21f83f0-f780-11e6-8459-e2c0252686bf.png)

**Comment by tomitrescak** [comment]
Hmm, no idea then, I keep receiving 'cannot find package 'highlight.js' ... I will work on it and report back. I'll close it for now then.

**Comment by devmondo** [comment]
@tomitrescak  clean the cache :)
