### ISSUE TITLE
[feature request] Web worker loader 

### ISSUE THREAD

**Issue by venil7** [fuse-box/fuse-box#247]
A web worker loader is required such that worker code is bundled with the main bundle, and not requested as a separate file by the browser.

some equivalent of https://github.com/webpack-contrib/worker-loader

**Comment by aretecode** [comment]
I was about to put in this same request ^ nice

**Comment by venil7** [comment]
I'd be happy to submit a PR to implement this, but I need some initial guidance

**Comment by nchanged** [comment]
@venil7 we are thinking bigger here. Feel free to poke on gitter

**Comment by devmondo** [comment]
@venil7  we are cooking something big that will cover this use case and introduce pure awesomeness in many other places, hang on with us :)

**Comment by venil7** [comment]
Any update on this issue?

**Comment by nchanged** [comment]
@aretecode ?

**Comment by thomas-jeepe** [comment]
Is there progress on web worker support?

**Comment by nchanged** [comment]
I don't think there is an update. You think you can try implementing it @thomas-jeepe

**Comment by thomas-jeepe** [comment]
@nchanged Unlikely.

**Comment by aretecode** [comment]
@nchanged @devmondo remind me again to link what I did on this

**Comment by dakom** [comment]
is there any way to currently use web workers with fuse-box (under both dev and distribution builds)? I tried different things like multiple producers etc. but I keep getting an `undefined globals` error (I think because the FuseBox api tries to access that)

**Comment by Shepless** [comment]
@devmondo @nchanged for v3 roadmap?

**Comment by nchanged** [comment]
Yep, we can make a sep. plugin for that in v3
