### ISSUE TITLE
Documentation or small startup for writing plugins

### ISSUE THREAD

**Issue by tonimain** [fuse-box/fuse-box#249]
Heyho and nice work with fusebox. Is there some how-to for writing own plugins. Best practice guides or a short intro. I'm working on implementing assemble as a fusebox plugin but the biq question mark is how to get started. Should we write in typescript, es6 or what is preferred. Who are the helper libraries working, what's up with Workflow Context. Would be great to get some starting points right now.

**Comment by leon-andria** [comment]
Official documentation is here: http://fuse-box.org/#plugin-api

**Comment by devmondo** [comment]
if the Docs. above are not enough please reopen with better suggestion :)

**Comment by tarwich** [comment]
I came here from Google, so I'm correcting this for other travelers. The new page is:

http://fuse-box.org/page/plugin-api

**Comment by devmondo** [comment]
@tarwich thanks :)
