### ISSUE TITLE
FuseBox.dynamic

### ISSUE THREAD

**Issue by leon-andria** [fuse-box/fuse-box#25]
How can we overwrite an existing dynamic module or simply remove it ?

It should be good to have a kind of option overwrite to true.
Today FuseBox.dynamic has string in first param, why not to have an object like 
```
FuseBox.dynamic( { path: "stuff/boo.js", overwrite: true }, .....) ?
```
Or having a method to remove modules ? I will be more in this way because in a bundle, you may have many modules that you are lazy load them and release when it's not necessary to save memory :-)

**Comment by devmondo** [comment]
@leon-andria Currently i don't think there is method to remove Modules, ( though it has been discussed internally ) but for now you can kind of override any module by simply adding new value like below

first time:
`FuseBox.dynamic("./dynamic/module-a.js", "module.exports = {hello : 'dynamic'}; require('./foo')")`
second time: 
`FuseBox.dynamic("./dynamic/module-a.js", "module.exports = {secondHello : 'dynamic'}; require('./foo')")`

and to make it empty just  add null as a value
`FuseBox.dynamic("./dynamic/module-a.js", null)`

i marked this issue as enhancement :)

**Comment by leon-andria** [comment]
@devmondo This is what i'm doing at this stage :-)

**Comment by nchanged** [comment]
That was a wrong commit, sorry
Here you [go](https://github.com/fuse-box/fuse-box/blob/master/src-frontend/FuseBox.ts#L422)
