### ISSUE TITLE
Problem with SASS

### ISSUE THREAD

**Issue by trickydisco78** [fuse-box/fuse-box#251]
For some reason it's complaining about a class?!

Uncaught SyntaxError: Unexpected token .

![capture](https://cloud.githubusercontent.com/assets/3627429/23132092/59a2a2f2-f784-11e6-97a4-6b383fa91e43.PNG)

(in stdin)

config is

// Create FuseBox Instance
let fuseBox = fsbx.FuseBox.init({
  homeDir: "src/",
  sourceMap: {
    bundleReference: "sourcemaps.js.map",
    outFile: "./build/sourcemaps.js.map"
  },
  outFile: "./build/out.js",
  plugins: [
    fsbx.SVGPlugin(),
    fsbx.SassPlugin({ outputStyle: "compressed" }),
    fsbx.CSSPlugin(),
    fsbx.BabelPlugin()
  ]
});

fuseBox.devServer(">index.jsx");

**Comment by nchanged** [comment]
Hi!
you need chain it
```
plugins : [
   SVGPlugin(),
   [SassPlugin(), CSSPlugin()],
  BabelPlugin()
]
```
