### ISSUE TITLE
Uncaught Package was not found "parse"

### ISSUE THREAD

**Issue by mbilling** [fuse-box/fuse-box#252]
I'm stuck here while trying to move from webpack to fb

Repro:
- git clone https://github.com/mbilling/fuse-box-ts-react-reflux-seed.git
- yarn install
- gulp dev
- open http://localhost:3000
- view console

Did I miss something?

Fantastic project btw, I believe its gonna save me a lot of waiting!

**Comment by nchanged** [comment]
Thanks! ;-)
https://github.com/mbilling/fuse-box-ts-react-reflux-seed/blob/master/gulpfile.js#L22


Please add. Or just use 1 bundle to avoid that.
const REACT_DEPS = `
    +react 
    +react-dom 
    +reflux
    +parse
`
I just tried and it works without errors. Welcome @mbilling !
