### ISSUE TITLE
GZip output support

### ISSUE THREAD

**Issue by GunterGlad** [fuse-box/fuse-box#253]
This may already exist but I was not sure where to ask. But we would like to gzip the output for production use. This means we can disable dynamic compression. Would you support this?

**Comment by nchanged** [comment]
Welcome @GunterGlad 
Absolutely! as soon as we finish fixing the critical bugs, we can move on to features and additional plugins.

**Comment by GunterGlad** [comment]
OK, thank you. I will keep this open, I will find an alternative solution for now. So not urgent, thanks.

**Comment by cellog** [comment]
This is the kind of thing a generic bundle plugin would be great for. Take 
output from previous stuff, make it into 1 file, apply optional 
compression.

Perhaps Combine or Merge is a better name to avoid confusion with the 
larger bundle.

**Comment by devmondo** [comment]
as mentioned above, this is outside the scope of FuseBox, it should be handled on HTTP Servers

**Comment by aretecode** [comment]
there is gzip size reporting though in beta

**Comment by GunterGlad** [comment]
When we bundle we gzip, the reason we do this is to now need the web server to do that on the fly, that means less cpu demand to get the bundle. I know it is small, but everything adds up when you start getting thousands of requests

**Comment by aretecode** [comment]
@GunterGlad if you already do this, you could add a plugin for it?

**Comment by devmondo** [comment]
@GunterGlad, could you add a plugin like @aretecode said ?

**Comment by GunterGlad** [comment]
Sorry to clarify. We do a gzip in web pack. I am looking to switch to fuse instead and want to get the same results. In webpack we use "compression-webpack-plugin".

**Comment by devmondo** [comment]
@GunterGlad, we will reopen this, for now, to see how we can tackle it :)

**Comment by Shepless** [comment]
@devmondo @nchanged one for v3?

**Comment by deamme** [comment]
Gzip support Quantum output would be awesome! I may have a look on and see if I can get a PR going.

**Comment by patrickmichalina** [comment]
This would be a good plugin. Using an HTTP on the fly gzipper is much slower than having it pre zipped and serving on demand. Since our bundles are static, it makes sense.

**Comment by benbieler** [comment]
Any news?
