### ISSUE TITLE
optimize for memory usage instead of time?

### ISSUE THREAD

**Issue by cellog** [fuse-box/fuse-box#254]
Hi,

I have a project running on a virtual machine which exhausts the piddly 2GB of memory available while building with webpack.  It would be amazing if fusebox had an option to minimize memory usage instead of build time.

**Comment by nchanged** [comment]
Great idea, let's keep track on that. Can we have some real numbers bundling with fuse and with webpack?

**Comment by nchanged** [comment]
Closing it for now. Please re-open if you get some information.
