### ISSUE TITLE
Implicit index.jsx support

### ISSUE THREAD

**Issue by andrew-oneill** [fuse-box/fuse-box#256]
Hi all, fantastic bundler! Would it be possible to add support for implicit loading of `index.jsx` within a directory using ES6 import syntax?

With the directory structure:
```
src
  - containers
    - App
      - index.jsx
  - index.jsx
```
And `src/index.jsx` of:
```
import React from 'react';
import ReactDOM from 'react-dom';

import App from './containers/App';

ReactDOM.render(
  <App/>,
  document.getElementById('root')
);
```
I get the console error: `./containers/App was not found upon request`.

However if I rename `src/containers/App/index.jsx` to `index.js`, the error disappears and the app boots up fine.

My fusebox config is identical to the react example in the docs, except `outFile` is set to `'./build/bundle.js'`.

If I am looking in the right place I believe a case would need added to `https://github.com/fuse-box/fuse-box/blob/master/src/loader/LoaderAPI.ts` around line 287.

**Comment by ConneXNL** [comment]
Also came across this issue. It's a common pattern to use index files for React Components. F.e. https://github.com/Automattic/wp-calypso/tree/master/client/components/card and then use the component by only referencing the directory import Card from './components/card' instead of  './components/card/index'.

**Comment by nchanged** [comment]
Thanks guys!
It's been added to the next milestone!

**Comment by nchanged** [comment]
Coming soon!; -)
https://github.com/fuse-box/fuse-box/blob/master/test/path_resolver.js#L62
