### ISSUE TITLE
HRM issue, not hotloading my .tsx file

### ISSUE THREAD

**Issue by mbilling** [fuse-box/fuse-box#259]
I made a repro here: **https://github.com/mbilling/fuse-box-hmr-repro**
I have, removed fuse cache, reinstalled node_modules, restarted bundling and read the doc.
I have tested the repro on 2 machines  prior to this issue submit.

When saving my file changes in **App.tsx** fuse-box logs **Source changed for App.less** 
I expect it to log **Source changed for App.tsx**
In the browser console logs **Updating "App.less" ...**

If I make changes to App.less, i works fine.

Thanks
Michael

**Comment by nchanged** [comment]
hi @mbilling 
Just got it working. You have a few issues here
1) Upgrade fuse-box to 1.3.119 ;-)
2) Set cache : true (HMR won't work without it) or remove that competly
3) Remove that event listener
```
//document.addEventListener("DOMContentLoaded", function(event) { 
   ReactDOM.render(<App/>, document.getElementById('react'));
//});
```
4) You can try using [this](https://github.com/fuse-box/fuse-box/blob/master/src/modules/fuse-hmr/index.ts#L54) custom HMR 
`require("hmr")` 
@basarat promised to provide some examples on that

**Comment by mbilling** [comment]
Ok, totally get 1-3

4? Something I should need to know about :) 
What does it do, whats the difference from the out-of-the-box hmr?

**Comment by nchanged** [comment]
It allows you to customise HMR behaviour ;-) What to reload, for example.

**Comment by mbilling** [comment]
Ah, yes of course!

I just really like the minimal config goal you set from start.
IMHO, you should activate all plugins per default. (if its possible)
Cache whatever plugins are hit.
and then build the user-interface around 

**fuse**               (runs the fuse.js script, uses existing caches or creates them)
**fuse /flush**     (flushes all caches, then runs **fuse**)

This would be perfect for on-boarding users. (which is important for any product)

E.g.
I'm still struggling moving to fuse-box. So I make these small projects for breaking it down, since I can't send you my whole source code.
It's hard to figure out which of tons of parameters (fuse, my code, libs etc.) has the bugs/misconfiguration :)
e.g. see screenshot of my latest roadblock.
I'll spend a lot of time stabbíng in the blind. Even though it works fine running webpack.

![image](https://cloud.githubusercontent.com/assets/973790/23170119/70ee2e3e-f84e-11e6-9902-414c9b14ab4f.png)

**Comment by nchanged** [comment]
Could you send a sample code that produces that error? FuseBox is a very young project, and we are trying out best to fix it all ;-)

**Comment by mbilling** [comment]
i'm on it
It will take sooome time ;)

**Comment by nchanged** [comment]
Thanks, @mbilling !
It's really helpful!

**Comment by nchanged** [comment]
I think I have an idea why that's happening. Cuz `require("buffer")` returns an object `{Buffer : Buffer}`, but should return an actual Buffer object.

I will check that, it might be a bug.

**Comment by nchanged** [comment]
@mbilling Could you search in your bundle 
```
/* fuse:injection: */
```

til you find Buffer, please.

**Comment by mbilling** [comment]
this is the first time

___scope___.file("lib/helpers.js", function(exports, require, module, __filename, __dirname){ 
/* fuse:injection: */ var process = require("process");
/* fuse:injection: */ var Buffer = require("buffer");
'use strict'

you want the bundle?

**Comment by nchanged** [comment]
Ok, now, it breaks in this file right? Yes please ;-)

**Comment by nchanged** [comment]
Yep, i found the issue 
https://github.com/fuse-box/fuse-box/issues/263

**Comment by mbilling** [comment]
ahh, sry didn't see you wanted the bundle file..
but great you found the bug

**Comment by nchanged** [comment]
There will be a hot fix release very soon. Stay tuned =)
