### ISSUE TITLE
FuseBox.dynamic path

### ISSUE THREAD

**Issue by leon-andria** [fuse-box/fuse-box#26]
in the doc
```
FuseBox.dynamic("stuff/boo.js", "module.exports = {hello : 'dynamic'}; require('./foo')")
```
In the doc, it said stuff/boo.js to get the module but this doesn't work, the correct syntax is (after tested):
```
require("~/stuff/boo.js") or require("~/stuff/boo") 
```

**Comment by devmondo** [comment]
@leon-andria `"stuff/boo.js"` is absolute path, did u try it with `"./stuff/boo.js"` ? 

and i think what you did is right, as it tells `FuseBox` that this modules virtual path starts from the root, so other modules can reference it correctly.

i think Docs should be updated to explain this.

**Comment by leon-andria** [comment]
@devmondo I tried both "./stuff/boo.js" and "stuff/boo.js", none of them is working except with the tilde.
Personnally i like that because it enforces that everything is coming from the root.

**Comment by nchanged** [comment]
`stuff/boo.js` means that your `boo.js` is in `stuff` folder. So you need to follow folder structure. If you are in `~/foo/myFile.js`, you need to require like so `require("../stuff/boo.js")`
