### ISSUE TITLE
Would it be possible to produce/bundle .d.ts as well?

### ISSUE THREAD

**Issue by lmartorella** [fuse-box/fuse-box#261]
Hello,
Since fusebox can be used to create libraries as well (with the 'package' feature), would it be possible to export the Typescript declaration file as well?
Or, at least, to produce non-bundled .d.ts (one for each source .ts file) in addition to the bundled JS file?

This feature would be great! No other products (like webpack and similar) can do something like that. 
The only similar project around right now is [dts-bundler](https://www.npmjs.com/package/dts-bundle).

Thank you very much!

**Comment by devmondo** [comment]
@lmartorella  we already plug to TS config, so this should be possible with some pipeline improvment there

**Comment by nchanged** [comment]
@lmartorella absolutely! Could propose the specs?

**Comment by lmartorella** [comment]
Typescript would be able to bundle the .d.ts file when the outFile property is used.
I think TS is nothing more sophisticated that a simple concatenation of the .d.ts of the files in that case.
The problem is that the 'outFile' property can only be used with AMD or System [module flavor](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#concatenate-amd-and-system-modules-with---outfile)

For that reason I think some vendor (see angular2) are selling 'unbundled' .d.ts files, in the same position of the original .ts file, probably directly using _tsc_ on each TS file.

Both solutions above (bundled or unbundled) are viable to produce a library package, I think.
Thx!

**Comment by vegarringdal** [comment]
I might be able to add this to the typechecker I made by overriding tsconfig, setting amd and outfile.

**Comment by devmondo** [comment]
@vegarringdal  any update on this ?

**Comment by patrickmichalina** [comment]
Updates?

**Comment by nchanged** [comment]
Tsc from sparky can do it 😃
Besides you can add to:main to package.json
