### ISSUE TITLE
ResourceCSSPlugin -> handle hashtags in urls

### ISSUE THREAD

**Issue by juank11memphis** [fuse-box/fuse-box#262]
I am trying to include the semantic-ui-css file using the ResourceCSSPlugin, but I am getting this error: 
(node:45936) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: ENOENT: no such file or directory, open '/myprojectpath/node_modules/semantic-ui-css/themes/default/assets/fonts/icons.svg#icons'

The problem is that fusebox is not handling that hashtag at the end (#icons).

**Comment by nchanged** [comment]
https://github.com/fuse-box/fuse-box/commit/80227013c380d4e6e4c96f1cb85cc7c3ced77a7d
