### ISSUE TITLE
Buffer is not bundled correctly

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#263]
subj

**Comment by mbilling** [comment]
great, and I was just about ready to give you a repro project :)

**Comment by nchanged** [comment]
@mbilling could you? I need to be sure =)

**Comment by mbilling** [comment]
yes, i'll push it

**Comment by mbilling** [comment]
here it is
https://github.com/mbilling/fuse-box-hmr-repro
don't mind the name :)

**Comment by nchanged** [comment]
Ok, I managed to fix it all except for this bug:

<img width="1268" alt="screenshot 2017-02-21 19 12 18" src="https://cloud.githubusercontent.com/assets/1629088/23178184/caf94844-f869-11e6-8f37-21e67f1bca20.png">

There is some problem with Utils. Could you install this version
```
npm install fuse-box-test@1.3.120-test --save-dev
```
and change the require statement to `require("fuse-box-test")`

**Comment by nchanged** [comment]
There is the same error over here:
http://stackoverflow.com/questions/30426420/node-js-object-prototype-may-only-be-an-object-or-null-with-redis

**Comment by nchanged** [comment]
Ok, that's a different issue. `1.3.120` is published. You have some crazy dependency tree there =) Full of node.js specific modules ;-)

**Comment by mbilling** [comment]
yes - i really enjoy the node environment for client and server :o)
The truth is I really don't think too much about it. I use what I need, and expect the bundler to fix the rest.
I'll keep you posted if I find more issues

**Comment by nchanged** [comment]
Thank you very much for reporting, Few missing NodeJS libraries were added (`https` and `tls`)

**Comment by mbilling** [comment]
Any time!
btw, check the webpack.config.js file
maybe you can get inspired by some of the other quirks I had to add to get the old code to run when porting from browserify to webpack.
e.g.
   node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      child_process: "empty"
   }

**Comment by nchanged** [comment]
FuseBox like JSPM has this awesome collection https://github.com/fuse-box/fuse-box/tree/master/modules

So your bundle will work in both environments ;-)

**Comment by devmondo** [comment]
@mbilling  you can also add and shim your own modules in your project using http://fuse-box.org/#custom-modules-folder

**Comment by mbilling** [comment]
Thanks for the bugfix.

I have updated to fuse-box 1.3.120
I get the same error you get. Something about Util lib that one of my deps uses.

My latest repro works fine with webpack, but not with fuse-box
https://github.com/mbilling/fuse-box-hmr-repro

I you want to take stab at it, run **webpack** and then **node fuse.js**

Webpack bundle: http://localhost:5555/webpack.htm
FB bundle: http://localhost:5555/index.htm

I would expect that both should work equally fine. :o)
