### ISSUE TITLE
CSSResourcePlugin creates random generated file names

### ISSUE THREAD

**Issue by lordgreg** [fuse-box/fuse-box#264]
As discussed in Gitter, I'm opening an issue for CSSResourcePlugin.

Using it as documented:
```
   [/node_modules.*\.css$/,
      build.CSSResourcePlugin({
          dist : "build/resources",
          resolve : (f) => `/resources/${f}`
      }), build.CSSPlugin()]
```

Generates:

![image](https://cloud.githubusercontent.com/assets/480546/23179002/b9b32354-f86c-11e6-9f5b-a321f8d3074e.png)

I was at least expecting original file-names :)

**Comment by nchanged** [comment]
You still want to have original names? Remember our discussion on gitter?

**Comment by lordgreg** [comment]
We can close the issue if you also give others exolanation on why this
isn't implemented. I found it was a proper reason.

👍
