### ISSUE TITLE
Package executes on bundle load

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box#266]
@nchanged as requested 👍 

**_Sample:_**
https://github.com/vegarringdal/fusePackageTest

**_To get up and running_:**
```npm install```

```node fuse```

**Package is very simple:**

```javascript
console.log("I WON!!!!")
console.log("But only because I executed on bundle load, and did not wait")
console.log("MOOOHAHAHA :-)")

export class somePackage{

    constructor(){
        
    }

    sayhello(){
        
    }
}
```

**Package is build like this:**
```javascript
var buildPackage = function () {

    let fb = require("fuse-box");
    let fuse = fb.FuseBox;

    let bundle = fuse.init({
        package: "my-package",
        homeDir: "./myPackage/",
        outFile: "./my-package-bundle.js",
        globals: {
            "my-package": "my-package"
        },
        sourceMap: {
            bundleReference: "./my-package-bundle.js.map",
            outFile: "./my-package-bundle.js.map",
        },
        plugins: [
            fb.TypeScriptHelpers(),
            fb.SourceMapPlainJsPlugin()
        ]
    })

    bundle.bundle(`
          > [index.ts]
        `);
}
```
**Loaded in index.html before app bundle**

```html
<script src="./my-package-bundle.js"></script>
<script src="./app-bundle.js"></script>
```

But a you can see in console, the code executes

![image](https://cloud.githubusercontent.com/assets/2901416/23179492/63e3cfe4-f86e-11e6-9638-617c59cec6ab.png)

**Comment by nchanged** [comment]
so, the desired functionality would be to have `entry` option for packaging? right?

**Comment by nchanged** [comment]
```
package: {
    name :  "my-package",
    entry : "index.js"
}
```

**Comment by vegarringdal** [comment]
Yes, because you dont want packages to execute on load.

**Comment by devmondo** [comment]
i like what @vegarringdal said, let us treat it the same way as `package.json` `main` property

**Comment by vegarringdal** [comment]
@devmondo 
Its kinda a bug, since without entry you cant really load it without this to you code...
```
FuseBox.pkg("my-package", {}, function(___scope___) {
        ___scope___.entry = "index.js"
});
```

And normally you dont want a package to execute on load


But if calling this a feature gets me closer to this: https://github.com/fuse-box/fuse-box/issues/170 then lets not call it a bug, but a feature 👍 😄

**Comment by vegarringdal** [comment]
please remember to think about #170 when fixing this, since both will need the entry to work in the same way.
👍

**Comment by nchanged** [comment]
```
FuseBox.init({
    package: {
        name: "super-name",
        entry: "index.ts"
    },
    homeDir: `${__dirname}/src2`,
    outFile: `${__dirname}/build/out2.js`,
    cache: false
}).bundle("index.ts")
```

**Comment by vegarringdal** [comment]
very nice, keep up the good work :-)

**Comment by devmondo** [comment]
how about we call it `main` instead of `entery` to be semantic with `package.json` ?

**Comment by nchanged** [comment]
@devmondo perfect idea!

**Comment by vegarringdal** [comment]
> how about we call it main instead of entery to be semantic with package.json ?

Agree
Thats why I also used "main" when making this in first post
https://github.com/fuse-box/fuse-box/issues/170

Any chance #170 might reach next milestone ? (yes I know Im asking al the time, but really want it  to make it simple to bundle in pakages that is kind aspecial and enable debuggin/watch on them when developing)

**Comment by devmondo** [comment]
@vegarringdal  we should increase our Red Bull dose then ;)

**Comment by vegarringdal** [comment]
hehe :-)

**Comment by vegarringdal** [comment]
just got around to try this after Ive got all my other issues fixed
this still executes when loaded...

Im I doing something wrong here ?
```
    let fb = require("fuse-box");
    let fuse = fb.FuseBox;

    let bundle = fuse.init({
        package: {
            name:"aurelia-v-grid",
            main: "index.ts"
        },
        homeDir: "./node_modules/aurelia-v-grid/src/",
        outFile: "./bundle/aurelia-v-grid/fb-aurelia-v-grid-bundle.js",
        globals: {"aurelia-v-grid": "aurelia-v-grid"},
        sourceMap: {
            bundleReference: "./fb-aurelia-v-grid-bundle.js.map",
            outFile: "./bundle/aurelia-v-grid/fb-aurelia-v-grid-bundle.js.map",
        },
        plugins: [
            fb.CSSPlugin(),
            fb.HTMLPlugin({
                useDefault: true
            }),
            fb.TypeScriptHelpers(),
            fb.SourceMapPlainJsPlugin()
        ]
    })


    // include everything in grid (html elements/css and attribute)
    bundle.bundle(`
    + [**/*.html] 
    + [**/*.ts]
    + [**/*.css]
`);
```

**Comment by vegarringdal** [comment]
for anyone else reading this I needed to remove the globals.. if that is added it fill execute right away
