### ISSUE TITLE
Tree Shaking?

### ISSUE THREAD

**Issue by viankakrisna** [fuse-box/fuse-box#267]
Is there any plans to work for it?

**Comment by devmondo** [comment]
@vanthiyathevan  hang in there mate, we are working on a commonjs solution that will rock this field :)

**Comment by viankakrisna** [comment]
curious how you guys implement it :) is there any pr / branch i can see?

**Comment by xdave** [comment]
Lol too much info.  I can see the headline(s) now:

"FuseBox Developer Claims Possibility Of Tree-Shaking With CommonJS Modules!  You'll Never Believe What Happens Next!"

**Comment by nchanged** [comment]
closing this for now
