### ISSUE TITLE
Aliasing doesn't work for preact/preact-compat

### ISSUE THREAD

**Issue by xdave** [fuse-box/fuse-box#269]
When using an alias such as:

```js
FuseBox.init({
    alias : {
        "react" : "preact-compat",
        "react-dom" : "preact-compat"
    }
})
```

Which is required to use `preact` as a drop-in replacement for React, results in a runtime error:

```
Uncaught Package was not found "preact-compat-dom"
c @ events@0.0.0:307
d @ events@0.0.0:307
w.require @ events@0.0.0:307
(anonymous) @ index.jsx:4
d @ events@0.0.0:307
n.import @ events@0.0.0:307
(anonymous) @ events@0.0.0:307
(anonymous) @ events@0.0.0:307
```

`index.tsx:4` is `import * as ReactDOM from 'react-dom';`.

Switching the order of the aliases does work-around the problem; however, further problems show up, for example, when using the `react-redux` package:

`Uncaught Package was not found "preact-compat-redux"` ... etc

My suggestion would be to try and match the package name with `===` if there are no path components.

**Comment by xdave** [comment]
The offending code is here: https://github.com/fuse-box/fuse-box/blob/4c7ace31f99bc111de3085f25d316fa0cbcc1679/src/FileAnalysis.ts#L111
```js
        for (let alias in aliasCollection) {
            if (aliasCollection.hasOwnProperty(alias)) {
                if (requireStatement.indexOf(alias) === 0) {
                    requireStatement = requireStatement.replace(alias, aliasCollection[alias]);
                    // only if we need it
                    this.requiresRegeneration = true;
                }
            }
        }
```

So, if even part of the name of the alias matches the required module, it will work, which is why this is occurring.

**Comment by devmondo** [comment]
@xdave  good catch man !!!

**Comment by nchanged** [comment]
https://github.com/fuse-box/fuse-box/blob/master/test/alias_test.js#L46

**Comment by xdave** [comment]
@nchanged Thanks, but I'm not sure if it's totally been fixed yet.. which is weird....  Here's a test repo I made really quickly to demonstrate the issue: https://github.com/xdave/fuse-box-alias-test

**Comment by xdave** [comment]
@nchanged to be more specific, here's the generated code:

Before:
```js
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { Provider, connect } from 'react-redux';
```
After:
```js
var React = require('preact-compat');
var ReactDOM = require('preact-compat-dom');
var react_redux_1 = require('preact-compat-redux');
```

Expected:
```js
var React = require('preact-compat');
var ReactDOM = require('preact-compat');
var react_redux_1 = require('react-redux');
```

**Comment by nchanged** [comment]
It's has not been released yet:)

**Comment by nchanged** [comment]
No, that is a different fix :) very soon

**Comment by John0x** [comment]
@nchanged has it been fixed yet?

**Comment by nchanged** [comment]
Of course, i am presonally using react-compat
