### ISSUE TITLE
Plugins incorrectly applied

### ISSUE THREAD

**Issue by indrimuska** [fuse-box/fuse-box#270]
### Problem

Using a configuration file that makes use of conditionally applied plugins (plugins that needs to be applied if the given RegExp success) will return an unexpected bundle process.

### Configuration

Given the following directory structure, I have a very simple Angular2 application and I want to bundle all CSS files contained in the `styles` folder in an single stylesheet bundle. On the other side, I want to merge all the stylesheets inside my application, so basically injecting their content in the single javascript bundle.

```
angular2-test-app/
  ├── src/
  │   ├── app/
  │   │   ├── app.component.css
  │   │   ├── app.component.ts
  │   │   └── app.module.ts
  │   ├── styles/
  │   │   └── main.css
  │   └── main.ts
  ├── fuse.js
  └── package.json
```

`main.ts` is responsible of including the `main.css` file in the project:

```javascript
import './styles/main.css';
```

That being said, that's the configuration file to run fuse-box.

```javascript
// fuse.js
const fsbx = require('fuse-box');

fsbx.FuseBox.init({
    cache: false,
    homeDir: 'src/',
    outFile: './dist/app.js',
    plugins: [
        fsbx.TypeScriptHelpers(),
        fsbx.HTMLPlugin({ useDefault: false }),
        [ /app(\/|\\).+\.css$/, fsbx.RawPlugin() ],
        [ /styles(\/|\\).+\.css/, fsbx.CSSPlugin({ group: 'app.css', outFile : "dist/app.css" }) ],
    ]
}).bundle('>main.ts');
```

### Result & Analysis

As I mentioned in #177, after running `node fuse.js` I notice that no CSS file were produced in the `dist` folder. But sometimes (apparently random) it will, so I start debugging this issue.

I was able to recreate two working environments:

 1. [angular2-test-app.zip](https://github.com/fuse-box/fuse-box/files/791384/angular2-test-app.zip): bugged version to reproduce the issue
 2. [angular2-test-app-2.zip](https://github.com/fuse-box/fuse-box/files/791385/angular2-test-app-2.zip): not affected version

These two package are not apparently identical, they are completely identical!
Anyway I started debugging and for the first project the `CSSPluginClass::transformGroup` was never called. Neither `CSSPluginClass::transform` was called! On the other side, project number 2 fires every time those methods. My researches end with this screenshot:

![schermata 2017-02-21 alle 20 25 03](https://cloud.githubusercontent.com/assets/1561134/23183070/05a79908-f87b-11e6-9519-4a99ad2fe5c9.png)

In the `dist/commonjs/File.js` file, in the piece of code where fuse-box tests if a plugin should be applied for a given file or not using the given RegExp something fails. Above you can see the test of the first regexp, the one regarding the files in the `app` folder (`/app(\/|\\).+\.css$/`). When the test is made for the `main.css` file that's the result:

 - `/Users/indrimuska/Downloads/angular2-test-app-2/src/styles/main.css` returns `false` and no RawPlugin will be applied
 - `/Users/indrimuska/Downloads/angular2-test-app/src/styles/main.css` returns `true` because the full path contains the string `"app/"` and ends with `".css"`. And `"app/"` comes from the name of the folder! This case the RawPlugin is applied even for the file in the `styles` folder and the CSSPlugin will never be used.

### Solution

The problem here is that all tests are made using the full path of the file. Why should I care about where my project is placed? This should simply check the path in the current project folder (`angular2-test-app|-2`), or at least in the `homeDir` directory (e.g., `src`).

**Comment by devmondo** [comment]
@indrimuska amazing analysis , thank you ver much!!!

**Comment by indrimuska** [comment]
Thank you @devmondo! :)
I think you can replace `this.absPath` with `this.info.fuseBoxPath`

![image](https://cloud.githubusercontent.com/assets/1561134/23184211/38590752-f87f-11e6-9b0a-5e5e6ae796fd.png)

If you like I can open a PR for this.

**Comment by devmondo** [comment]
@indrimuska  by all means man, go ahead :)

**Comment by nchanged** [comment]
@indrimuska thanks!!!
Could you try this version `fuse-box@1.3.121-alpha.1`

**Comment by indrimuska** [comment]
Sure, give me 5

**Comment by indrimuska** [comment]
Just tried, issue still persist.

**Comment by nchanged** [comment]
I finally got you problem. WE can't solve it with your PR, that's an incorrect fix. 

What we can introduce, is globbing (simpler than RegeExp), which would look like

`["$home/app/*.css", CSSPlugin()]`

**Comment by indrimuska** [comment]
Ok, anyway I've updated the PR in order to support all files from the project folder (and so event those in node_modules).

**Comment by nchanged** [comment]
Thanks!
