### ISSUE TITLE
Image in parent of root folder

### ISSUE THREAD

**Issue by JiDai** [fuse-box/fuse-box#271]
Hi,

How to reproduce: 

- I cloned react example, I created a folder `images` in root folder (same level as `src`)
- I move `logo.svg` in this image folder
- In `App.jsx` I changed the import to have `./logo.svg` to `../images/logo.svg`

And it does not work.

In other words, how can I import image from a folder at a higher level than root folder
If i put my folder `images` in `src folder (and change import), it works

See attachment below

<img width="623" alt="screen shot 2017-02-21 at 21 45 13" src="https://cloud.githubusercontent.com/assets/507737/23184567/92f1c432-f880-11e6-8847-bee752f61a03.png">

**Comment by devmondo** [comment]
@JiDai  fuse respects your `src` property on your bundle config, so you need to put that image folder under that config

**Comment by nchanged** [comment]
@JiDai logo.svg does not export default property
`import * as logo from "../images/logo.svg"`

**Comment by nchanged** [comment]
besides yes, you are locked in your homeDir ;-)

**Comment by JiDai** [comment]
ok, noted, thanks :)
