### ISSUE TITLE
proxying / stubbing imports

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#275]
Guys, would you have any recommendation on how can I stub / proxy imports when doing unit tests? Thanks!

[EDIT]

I mean related to fusebox packaging. Since proxyquire and others probably will not work.

**Comment by tomitrescak** [comment]
The naive version I thought will be possible was to substitute the FuseBox.import functionality.
This, is not possible as requires in FB are using a local anonymous version not the global FuseBox.import.

The other idea was to write a plug that would rewrite all requires (this plugin would execute AFTER typescript compilation). 

It would rewrite require as:

```js
require('path')
```

to

```js
proxyRequirePath(require, 'path')
```

Then, I would be able to require a specific module with stubbed dependencies as following

```js
proxyRequire('$modulePath', {
 '../my/path': stub1 // same path as in $modulePath
 './my/path2: stub2
}, require)

// where

function proxyRequire(path, stubs, require) {
   global.$_stubs_$ = stubs;
   return require(path);
   global.$_stubs_$ = null;
}

function proxyRequirePath(require, path) {
   return global.$_stubs_$[path] || require(path);
}
```

where proxyRequire would check if global parameter $_stubs_$ does contain some substitutions. If path would be in substit

**Comment by tomitrescak** [comment]
Not sure if someone is watching this, but I rolled out a package that allows easy stubbing of modules in fusebox, node.js and possibly webpack (webpack not tested).

https://github.com/tomitrescak/proxyrequire

**Comment by devmondo** [comment]
@tomitrescak  thanks a lot man, added to third party plugins in docs :)
