### ISSUE TITLE
Multiple __fsbx_decorate generated

### ISSUE THREAD

**Issue by leon-andria** [fuse-box/fuse-box#277]
Class having decorators has multiple this line generated:
var __decorate = __fsbx_decorate(arguments);

The behavior is that like their is a singleton increment so the line below increase in every class that have decorator.

**Comment by nchanged** [comment]
you mean file? can you show the output please

**Comment by nchanged** [comment]
and it's absolutely normal to have it every file that uses a decorator, as it patches it

**Comment by leon-andria** [comment]
After saving file with filewatcher to bundle, like 4 times, it's ended with
```javascript
var __decorate = __fsbx_decorate(arguments);
            var __decorate = __fsbx_decorate(arguments);
            var __decorate = __fsbx_decorate(arguments);
            var __decorate = __fsbx_decorate(arguments);
            var __decorate = __fsbx_decorate(arguments);
            var __decorate = __fsbx_decorate(arguments);
            var __decorate = __fsbx_decorate(arguments);
            var __decorate = __fsbx_decorate(arguments);
            var __decorate = __fsbx_decorate(arguments);
            var __decorate = __fsbx_decorate(arguments);
```
this happen for every files
