### ISSUE TITLE
Sass Includepaths keeps growing causing import issues

### ISSUE THREAD

**Issue by ConneXNL** [fuse-box/fuse-box#278]
https://github.com/fuse-box/fuse-box/blob/master/src/plugins/SassPlugin.ts#L30-L38

The following lines create a situation where options.includePaths === this.options.includePaths which results in the includePath growing which each SCSS compile.

This results in all sorts of errors as the includepaths will contain an array of false paths for each SCSS file after the first.

The issue I had because of this was that "./mixin.scss" resolved to the wrong error thus resulting in "Error: no mixin named xxx" errors.

**Comment by nchanged** [comment]
Thanks!
Could you propose a change?

**Comment by ConneXNL** [comment]
Here you go https://github.com/fuse-box/fuse-box/pull/285
