### ISSUE TITLE
Sourcemaps for TSX files lose original name when being passed through babel

### ISSUE THREAD

**Issue by orta** [fuse-box/fuse-box#280]
We use TypeScript with React + Relay, which means we run our tsx files through babel as well as tsc. We have sourcemaps working through both TypeScript and Babel, and that works 👍 

The only issue is that right now the hand-off process from TS -> Babel changes the file names inside the sourcemaps to refer to non-existent files.

I have an OSS example, https://github.com/artsy/reaction-force/tree/orta-sourcemaps ( specifically  https://github.com/artsy/reaction-force/commit/9f4b4ba8ff8f7ebb6ebc22f375f60b132e02d6b4 ) 

Which you can run via

``` sh
git clone https://github.com/artsy/reaction-force
cd reaction-force
git checkout 9f4b4ba8ff8f7ebb6ebc22f375f60b132e02d6b4
yarn install
node fuse.js
```

It will generate a file `reaction-force.js.map` which looks like this:
```json
{"version":3,"sources":["components/__stories__/artwork.jsx","components/artwork.jsx","relay/config.ts","relay/root_queries.ts","components/__stories__/artwork_grid.jsx","components/artwork_grid.jsx","packages/default"],"names":[],"mappings":";;;;;;;;;;;;;;;;AAAA,+BA...
```

For it work correctly, it would need to look like:
```json
{"version":3,"sources":["components/__stories__/artwork.tsx","components/artwork.tsx","relay/config.ts","relay/root_queries.ts","components/__stories__/artwork_grid.tsx","components/artwork_grid.tsx","packages/default"],"names":[],"mappings":";;;;;;;;;;;;;;;;AAAA,+BA...
```

If I manually make these changes, everything hooks up perfectly

**Comment by orta** [comment]
I've taken two attempts at making a work around:

- A plugin/hook that changes the file directly. This is hard to do - I've looked at the source, and I can't find any callbacks that happen after [this function](https://github.com/fuse-box/fuse-box/blob/d0f48c54a1d7a01726b21eef248ccc34a5222d17/src/FuseBox.ts#L273). I explored using the HMR aspect of the dev server, but that also runs before the process of writing the file.

- Looking into editing the concat instances directly inside a plugin, which I'm exploring right now.

**Comment by orta** [comment]
Editing the concat objects doesn't really work very well:

```js
const fs = require("fs")

const ArraySet = require("../../node_modules/source-map/lib/array-set").ArraySet

module.exports = function() {
  return {
    bundleEnd: function(context) {

      const concat = context.source.getResult();
      concat._sourceMap._sources = ArraySet.fromArray(concat._sourceMap._sources.toArray().map(f => f.replace(/\.jsx/g, ".tsx")))

      const contents = concat._sourceMap._sourcesContents
      for (let file in contents) {
        const code = contents[file]
        delete contents[file]
        contents[file.replace(/\.jsx/g, ".tsx")] = code
      }
      
      debugger
    }
  }
}
```

Think it's not worth trying to do a workaround, this is a bit too much digging into the guts.

**Comment by nchanged** [comment]
Also:
[This](https://github.com/fuse-box/fuse-box/blob/master/src/plugins/BabelPlugin.ts#L102) might help or [this](https://github.com/fuse-box/fuse-box/blob/master/src/File.ts#L346)

**Comment by orta** [comment]
I wonder if the fix is as simple as changing this line, https://github.com/fuse-box/fuse-box/blob/master/src/File.ts#L349 to include tsx :D

**Comment by nchanged** [comment]
absolutely!
