### ISSUE TITLE
Add minimum required node version in docs

### ISSUE THREAD

**Issue by peterhudec** [fuse-box/fuse-box#283]
There is no mention as to what minimal Node.js version FuseBox requires. The `require('fuse-box')` statement raises a syntax error related to array destructuring on Node < 6.0.

I would suggest to add a requirements section to the docs.

**Comment by aretecode** [comment]
https://github.com/fuse-box/fuse-box/commit/68954cf0b590f29f611980ac4a0241cf7537a5df
