### ISSUE TITLE
PostCssResourcePlugin cannot recover from error in watch mode

### ISSUE THREAD

**Issue by geowarin** [fuse-box/fuse-box#284]
First, thank you for fuse-box, it's the most amazing thing that happened to me during my web devs years! Pure awesomeness.

The error I'm reporting happens in watch mode when an url cannot be resolved by the resource loader.

Example:

main.css
```css
.something {
   url(/non/existing.jpg)
}
```

The error is correctly reported:

```
  Error: ENOENT: no such file or directory, open '/non/existing.jpg'
  
  - fs.js:558 Object.fs.openSync
    fs.js:558:18
  
  - fs.js:468 Object.fs.readFileSync
    fs.js:468:33
  
  - base64-img.js:54 Object.exports.base64Sync
    [myprivateadvisor]/[base64-img]/base64-img.js:54:17
  
  - CSSResourcePlugin.js:120 Object.fn
    [myprivateadvisor]/[fuse-box]/dist/commonjs/plugins/CSSResourcePlugin.js:120:48
  
  - PostCSSResourcePlugin.js:29 css.walkDecls.declaration
    [myprivateadvisor]/[fuse-box]/dist/commonjs/lib/postcss/PostCSSResourcePlugin.js:29:49
```

If I then proceed to remove the offending line, save the file, the watch mode picks it up but the error persists.

The transform method of the CSSResourcePlugin does not get called again so I assume this is due to the cache not getting invalidated.

**Comment by devmondo** [comment]
@geowarin  thanks a lot for the kind words, we are sooo happy you see it this way.

could you enable `cache` when you use `hmr` feature and let us know.

rest assured we are working actively and daily on making this better, and we will solve this issue for you :)

**Comment by geowarin** [comment]
`Cache: true` or `cache:false` does not seem to make a difference.
Here is [a repro](https://github.com/geowarin/fuse-repro)

**Comment by devmondo** [comment]
@geowarin  we are investigating :)
