### ISSUE TITLE
~ in SASS files to include files from node_modules

### ISSUE THREAD

**Issue by ConneXNL** [fuse-box/fuse-box#286]
```
                includePaths: [
                    './node_modules/',
                ]
```
Makes it possible to include node_modules in sass files. However...
                
I am not sure its a "sass feature", but its a common practice since https://github.com/webpack-contrib/sass-loader#imports to import files from /node_modules/ when using a ~ and it seems like node-sass has a way to add custom importers to make that happen. https://github.com/danderu/node-sass-custom-importer being an example.

Well-known libraries like Blueprint are using the same ~ to reference other node_modules, example:
https://github.com/palantir/blueprint/blob/master/packages/core/src/common/_font-imports.scss

Until this is fixed one cannot include the scss file from blueprint as it cannot resolve the ~ they are using.

**Comment by ConneXNL** [comment]
Made a branch https://github.com/ConneXNL/fuse-box/tree/css-tilde-support that shows a potential implementation. What do you think?

**Comment by nchanged** [comment]
@ConneXNL i think it's terrific! Could you write some tests?

**Comment by ConneXNL** [comment]
Working on a test but I will require a fuse-box/fuse-box-testcase4 with a simple style.scss file to include.

**Comment by nchanged** [comment]
You don't need to! You can use this approach
https://github.com/fuse-box/fuse-box/blob/master/test/bundle_in_a_bundle.js#L13

It creates a valid "npm" module.

**Comment by nchanged** [comment]
@ConneXNL could you make a PR please?

**Comment by nchanged** [comment]
http://fuse-box.org/#sassplugin

**Comment by ConneXNL** [comment]
It seems like no changes were done to CSSResourcePlugin so you cannot use it to reference fonts and images.

This is however, what other libraries are doing too.
