### ISSUE TITLE
Importing from modules with `.` causes them to not be bundled

### ISSUE THREAD

**Issue by aretecode** [fuse-box/fuse-box#292]
for example, importing from `lodash.merge` will not work, while importing the entire `lodash` will.

**Comment by devmondo** [comment]
@aretecode what is the import syntax you use ?

**Comment by aretecode** [comment]
`var _merge = require('lodash.merge')`
@devmondo

**Comment by devmondo** [comment]
@aretecode should it not be `var _merge = require('lodash/merge')` ?

**Comment by aretecode** [comment]
@devmondo https://www.npmjs.com/package/lodash.merge

**Comment by nchanged** [comment]
I cannot reproduce it.

```js
console.log(require('lodash.merge'));
```

```
└── default (1 files,  263 Bytes)
      index.js
└── fusebox-hot-reload (1 files) 1.8 kB
└── fusebox-websocket (1 files) 2.8 kB
└── events (1 files) 9.8 kB
└── lodash.merge (1 files) 57.1 kB
└── process (1 files) 3 kB
└── object-assign-polyfill (1 files) 1 kB

    Bundle
    Size: 75.8 kB
    Time: 376ms
```

![screenshot 2017-02-23 10 32 02](https://cloud.githubusercontent.com/assets/1629088/23253098/8ead4c6e-f9b3-11e6-8e51-ca5f00636851.png)

**Comment by aretecode** [comment]
thanks, turns out I had babel ignore it
