### ISSUE TITLE
Include a sub package in a bundle

### ISSUE THREAD

**Issue by geowarin** [fuse-box/fuse-box#293]
Hello,

This is probably my own ignorance, but I did not find a way to include a subpackage in my vendor bundle.

A created [a small project](https://github.com/geowarin/fusebox-datefns) demonstrating the issue.

The gist of the problem is that the locales of the package date-fns are in a subpackage.
I tried to include them like this:

```js
fsbx.FuseBox.init({
  homeDir: `./src`,
  cache: false,
  log: false
}).bundle({
  [`dist/vendor.js`]: "+date-fns +date-fns/locale/fr"
})
```

But this does not work as I expected.
Could you suggest another way to accomplish this?

**Comment by nchanged** [comment]
@geowarin thanks for reporting!

Yeah, it's a known "bug" you can't really add it like so. But this will be fixed. 
You can make a workaround for now:
```
require("date-fns/locale/fr")
```

**Comment by geowarin** [comment]
Ok. Yeah there is an [easy workaround](https://github.com/geowarin/fusebox-datefns/compare/workaround#diff-8beed842be7e0d8daa6f0716f83e5f90) for those interested.

additionalVendors.js
```js
require('date-fns/locale/fr');
```

fuse.js
```js
vendor.bundle({
  [`dist/vendor.js`]: "+date-fns additionalVendors.js"
})
```

**Comment by nchanged** [comment]
Thanks there seems to be a problem with distinguishing what is a node module reference and what is a file. Gotta keep that issue in mind.
Thanks.

**Comment by nchanged** [comment]
Coming with the next one
