### ISSUE TITLE
Crypto

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#296]
Hi, it would be nice to have a simple implementation for crypto library as many test runners are using it:

```
"crypto": {
    exports: "{ randomBytes: () => crypto.getRandomValues(new global.Uint16Array(1))[0] }"
}
```

**Comment by nchanged** [comment]
We have it here https://github.com/fuse-box/fuse-box/blob/master/modules/crypto/index.js
That's an old bug, i know ;-)

**Comment by Shepless** [comment]
@nchanged @tomitrescak Am I ok to close this?

**Comment by tomitrescak** [comment]
I'll help you ;)
