### ISSUE TITLE
Importing modules which contain "process" fails

### ISSUE THREAD

**Issue by shripadk** [fuse-box/fuse-box#297]
I tried to import: https://github.com/postcss/postcss-js into my code but was always failing at this line:

```
const cssObj = postcssJs.objectify(root);
```

Upon further inspection of the `postcss-js` code I realized that fusebox was inadvertently replacing every occurrence of _any_ variable named `process` in legitimate code: https://github.com/postcss/postcss-js/blob/master/objectifier.js making it impossible for me to use the function.

If I `console.log(postcssJs)` this is what I get (you can see that the `objectify` key points to Node's `process` instead of the module's function):

![actual](https://cloud.githubusercontent.com/assets/189344/23292923/fa4cf5ca-fa88-11e6-89e0-21eb2810688f.png)

Is there an option to skip shimming of certain modules?

**Comment by nchanged** [comment]
hi @shripadk 
thanks for submitting the issue! We will fix that as soon possible.

**Comment by nchanged** [comment]
[test](https://github.com/fuse-box/fuse-box/blob/master/test/auto_import.js#L202)
