### ISSUE TITLE
Fusebox went wrong when bundle project with symlinks.

### ISSUE THREAD

**Issue by LucasIcarus** [fuse-box/fuse-box#299]
Seems that fusebox could not get the real path of symlinked file, no matter homeDir wrapped the origin dir or not..

here is the file structure (just made for test)

![](http://youzan-fancy.oss-cn-shanghai.aliyuncs.com/github-issues/structure.png)

The code down below is most simple way to recurrence the status

`src/index.js` as an entry

```js
import AnObject from './assets';
console.log(AnObject);
```
The assets in src is created by run shell `ln -s ../assets/ assets` in src dir.

`AppRootPath/assets/index.js`

```js
import SomeConstantString from '../others';
export default { a: SomeConstantString };
```

`AppRootPath/others/index.js`

```js
export default 'Constant String'
```

here is the outlog of fusebox.. when homeDir set to `./src` and `./`

![](http://youzan-fancy.oss-cn-shanghai.aliyuncs.com/github-issues/terminal.png)

Any plan to fix this?

**Comment by nchanged** [comment]
Hi!
Could put this on Github? It's hard to tell now.

**Comment by devmondo** [comment]
@LucasIcarus 
does this help, it is undocumented yet
https://github.com/fuse-box/fuse-box/blob/08fd83618afdb550edcf48fcaf3b46ab96d6bfef/src/Config.ts#L6

specially if you are on windows

**Comment by LucasIcarus** [comment]
@nchanged  Sorry for the unclear declaration...  I will update the issue, soon.

@devmondo I'm not in windows and this problem is not only  involve npm I think.

**Comment by LucasIcarus** [comment]
@nchanged  Hope I make it clear. And the github sample will be created later..

**Comment by LucasIcarus** [comment]
@nchanged @devmondo 
Here is a demo on Github.
https://github.com/LucasIcarus/FuseBox-Issue-Reporter

**Comment by nchanged** [comment]
Unfortunately, that's not a bug. That's how fusebox works. You cannot go outside of your `homeDir`
First linking works fine and goes into assets, but then:
```
import SomeConstantString from '../others';
```
breaks it because it's not within you homeDir

**Comment by nchanged** [comment]
Suggestion: change your `homeDir`, and use aliases

**Comment by LucasIcarus** [comment]
@nchanged  I try to change homeDir to wrapp the assets, with homeDir is equal to AppRootPath, where the real assets dir is in, fuse-box still could not get '../others' correctly.

**Comment by nchanged** [comment]
`homeDir: './src'` this one. You can't go outside of it. I am not sure if what you want to achieve is doable.

**Comment by LucasIcarus** [comment]
@nchanged  set the homeDir to './' then call `bundle(>src/index.js)`, fuse-box will treat `require('../others')` as an unlocated js file... 

I find this when I try to migrate webpack to fuse-box within an old project which run with no error through webpack. 

After the chat above, I do some background search, and find an old issue https://github.com/webpack/webpack/issues/1643

This new bundler is awsome, hope it will open a new era in FE. I'm reading the source code, trying to find the locate strategy for now.

At last I have a question that has noting to do with this issue. Is it an official opinion that fuse-box don't support Node 4.x? 

Thanks to your patience, have a good day.  (๑•̀ㅂ•́)و✧

**Comment by nchanged** [comment]
Yeah, it's NodeJs 6+
