### ISSUE TITLE
Question: how could I generate a bundle for product envirtonment?

### ISSUE THREAD

**Issue by xiechao06** [fuse-box/fuse-box#300]
When I check the generated outfile, it contains something like:
```js
if (FuseBox.isServer) {
   // codes work in server
} else {
  // codes work in browser
}
```
this is redundant when I only develop for browser/node environment, is there a way that I could generate a bundle of a target platform? 
BTW, if I use the typescript compiler to generate the final bundle, it won't accept the statement "require('main.css')".
Thanks! 

--- TO BE REMOVED --

Before summiting an issue, please make sure that:

* You have removed the `.fusebox` folder in your project root
* Removed node_modules, (re-installed everything) 
* Started the bundling process again. 
* Read the documenation on your subject here -> fuse-box.org

**Comment by nchanged** [comment]
Hi!
@xiechao06 thanks for the issue.

We are working on improving it. 

`require('main.css')` means you are calling a package on NPM called `main.css`, if you want to import a file, please use relative imports 

```
`require('./main.css')`
```

**Comment by xiechao06** [comment]
@nchanged Thanks for your response, I mean typescript compiler won't accept "require('./main.css')", so I can't rely typescript compiler to generate the bundle if I require some css files.

**Comment by nchanged** [comment]
@xiechao06 please check this repo https://github.com/fuse-box/mastering-css

**Comment by nchanged** [comment]
https://github.com/fuse-box/fuse-box/issues/354
