### ISSUE TITLE
Support for scopes npm packages in arithmetic instructions

### ISSUE THREAD

**Issue by ConneXNL** [fuse-box/fuse-box#301]
Npm allows scopes to be used which makes packages have names like "@blueprint/core". However, the arithmetic instructions does not support this and doesn't recognize "@blueprint/core" as an npm package because of https://github.com/fuse-box/fuse-box/blob/master/src/Arithmetic.ts#L124.

In other words, `>app.tsx -@blueprint/core` incorrectly bundles the `@blueprint/core` npm package.

https://docs.npmjs.com/misc/scope "A scope follows the usual rules for package names (url-safe characters, no leading dots or underscores). When used in package names, preceded by an @-symbol and followed by a slash, e.g."

Better to verify an npm package name by using:
https://github.com/npm/validate-npm-package-name

**Comment by nchanged** [comment]
```
// npm install react-addons-css-transition-group react react-dom @blueprintjs/core 
app.devServer(`
    > index.ts 
    + @blueprintjs/core 
`);
```
