### ISSUE TITLE
support loading js with typescript

### ISSUE THREAD

**Issue by aretecode** [fuse-box/fuse-box#302]
<img width="427" alt="screen shot 2017-02-23 at 6 38 54 am" src="https://cloud.githubusercontent.com/assets/4022631/23301565/6635c400-fa3f-11e6-886e-c77e111f6bdd.png">

escodegen will often break when using babel, enabling the option to make typescript parsing js will make it faster by reducing the time it takes to load the parsers, allow more options, and hopefully fix the issue

**Comment by xdave** [comment]
Hi, so I've encountered this.... it would work if we could simply provide a glob or pattern for what to pass through to the typescript compiler in the same way that we can for plugins that do other transforms.

**Comment by devmondo** [comment]
this is already solved.

we will close this for now but let us know otherwise :)

**Comment by aretecode** [comment]
@devmondo since when was this solved? is there an example of using ts to compile js when you want it to? by using quantum ensure-es5? links?

**Comment by devmondo** [comment]
@nchanged is this still not solved?

**Comment by xdave** [comment]
ya i wanna know, too...

**Comment by xdave** [comment]
@nchanged ping

**Comment by nchanged** [comment]
@xdave it's not that easy, cuz of module resolution. But we could add it to the next milestone

**Comment by devmondo** [comment]
This is fixed now, let us know otherwise.
