### ISSUE TITLE
Error output written in white causes frustration

### ISSUE THREAD

**Issue by Crevil** [fuse-box/fuse-box#303]
When using `fuse-box` errors are printed with a white text color. In terminals with a white background, e.g. Mac OS X Terminal, the output is hidden.

This is the output with a JSON load error:

![image](https://cloud.githubusercontent.com/assets/6881694/23302143/cd34bc3a-fa8d-11e6-8269-a54eccc1b58c.png)

When selecting the text, the message appears:

![image](https://cloud.githubusercontent.com/assets/6881694/23302140/c6bb15de-fa8d-11e6-8d09-dadaf5076fe4.png)

**Comment by nchanged** [comment]
Thanks for the issue!
Will be fixed in the next release!

**Comment by Crevil** [comment]
GJ @nchanged Thanks
