### ISSUE TITLE
Banner Plugin

### ISSUE THREAD

**Issue by dogancelik** [fuse-box/fuse-box#31]
Can we add a _BannerPlugin_, I'm writing a Greasemonkey / Tampermonkey script and `// ==UserScript==` has to be at top of the file

https://webpack.github.io/docs/list-of-plugins.html#bannerplugin

![untitled](https://cloud.githubusercontent.com/assets/486818/21444155/6f7831e6-c8b3-11e6-8960-7e63f46dcace.png)

Or is there another way to do this with Fusebox?

**Comment by Shepless** [comment]
@dogancelik @nchanged I have put up a proposal PR of how we can add the functionality in (along with a basic BannerPlugin too). Let me know if the proposal is ok.

**Comment by nchanged** [comment]
Thanks @Shepless it has been [merged](https://github.com/fuse-box/fuse-box#bannerplugin), good job!
