### ISSUE TITLE
Source mappings not working for node_modules directory with DevServer

### ISSUE THREAD

**Issue by arjendeblok** [fuse-box/fuse-box#310]
I cannot get source maps for the packages included in the node_modules folder.
I can (sometimes) see that there is a /packages/ folder in Chrome but if I click on any of them I see an empty file. 
I can see my the source maps for my own code however.
Does anyone has an example where this works?

**Comment by nchanged** [comment]
@arjendeblok source maps are not generated for node_modules just yet. But could be implemented as an option.

**Comment by vegarringdal** [comment]
+1 for option for sourcemaps
I would like this option, was very confusing when I was not able to see anything of other modules code when working on the Aurelia-loader

**Comment by nchanged** [comment]
let's plan it for the next release! it's annoying i agree

**Comment by vegarringdal** [comment]
👍 nice

**Comment by nchanged** [comment]
![screenshot 2017-03-03 11 37 00](https://cloud.githubusercontent.com/assets/1629088/23548003/cdceb682-0005-11e7-9e12-912fe37e94bb.png)

Done. But it takes sooooo long time to generate it. We should make it optional.

**Comment by vegarringdal** [comment]
yes should be optional, but very usefull during development, to speed it up during development someone could create a seperate bundle for the libs they bring inn so they only need to bundle it once.

**Comment by nchanged** [comment]
but it has to be in the vendor package. Cuz it takes 7 seconds to generate it......

**Comment by arjendeblok** [comment]
@nchanged You closed this issue, but I cannot still see the contents of the vendor files. I can see that source maps are generated (takes about 30 seconds), but because I cannot see the contents of the vendor files, I cannot check if the source maps are right.

**Comment by nchanged** [comment]
Please disable cache (it says in docs)

**Comment by arjendeblok** [comment]
@nchanged Disabled cache, but still vendor files are not served by DevServer.
@vegarringdal Do you have a working sample with source maps from files in node_modules folder.

**Comment by nchanged** [comment]
@arjendeblok please remove the existing ones (sourcemaps) I can provide an example later

**Comment by vegarringdal** [comment]
looks like it
when I did a test just now:

![image](https://cloud.githubusercontent.com/assets/2901416/23631035/7bd1c454-02bd-11e7-83ee-e04fb32f2326.png)
![image](https://cloud.githubusercontent.com/assets/2901416/23631191/f28b3850-02bd-11e7-9c41-86c43afe17b9.png)



Here is the build I tried it with, but takes like 19 sec in my virtual pc to do this, so this should be a seperate bundle (would be nice if the aurelia-fuse-box-seed had this)
cache need to be set to false, hmr will kill it on saves


```
var build = function() {

    let fb = require("fuse-box");
    let fuse = fb.FuseBox;

    let bundle = fuse.init({
        homeDir: "./src",
        outFile: "./bundle/fb-app-bundle.js",
        cache: false,
        plugins: [
            [/\.css$/, fb.RawPlugin({extensions: ['.css']})],
            fb.HTMLPlugin({
                useDefault: true
            }),
            fb.TypeScriptHelpers(),
            fb.SourceMapPlainJsPlugin(),
            fb.EnvPlugin({ 
                FB_AU_LOG: false,
                FB_AU_HMR: false,
                FB_AU_RELOAD: true 
            })
        ],
        sourcemaps:{
            project:true,
            vendor:true
        }
    });

    // Start dev server
    bundle.devServer(`
        > [main.ts]
        + [**/*.html] 
        + [**/*.ts] 
        + [**/*.css]
        + aurelia-bootstrapper
        + aurelia-framework
        + aurelia-pal
        + aurelia-metadata
        + aurelia-polyfills
        + aurelia-fetch-client
        + aurelia-pal-browser
        + aurelia-animator-css
        + aurelia-logging-console 
        + aurelia-templating-binding 
        + aurelia-templating-resources 
        + aurelia-event-aggregator 
        + aurelia-history-browser 
        + aurelia-templating-router
        + aurelia-hot-module-reload
        `, {
        root: './'
    })

}

build();
```

**Comment by nchanged** [comment]
Yeah guys, source maps are extremely heavy to generate. Nothing you can do it about. And cache : false breaks it. I don't have a good solution to fix it just yet.
What you can do is a separate task for a vendor bundle. And make it once in a while ;-)

**Comment by vegarringdal** [comment]
cache set to false made it work here, cant have i set to true, hmr breaks it then.
but generating vendor bundle is ok (for me) mosly done that all the time since I never saw the need for bundling all modules over and over again, just didnt do it in that one since I needed process to work, but after 1.4.1 thats solved :-)

**Comment by arjendeblok** [comment]
@vegarringdal  I can also see a tree with files in Chrome, but when I click on a file then I see an empty file.
Can you really see the contents of the vendor files? And can you set breakpoints inside them?

I agree to have a separate vendor bundle with its own mapping file.

**Comment by vegarringdal** [comment]
@arjendeblok you are right, cant see the code, looks like a bug, pretty sure I managed ot do this in the preview, but might be mising it with the loader where I generate a package from src/ts files and get full sourcemaps

![image](https://cloud.githubusercontent.com/assets/2901416/23632285/87cbcb5c-02c1-11e7-9ed5-77bb335d9587.png)

**Comment by arjendeblok** [comment]
@vegarringdal I have done some research on this and it could never have worked. Because the DevServer just serves physical files on disk and there is no vendor folder in your dist directory.
The vendor folder is just a virtual folder made by fuse-box and the DevServer is unaware of this.
I am busy on a pull request to make this work.

Maybe I can also try to get the source mappings work in a seperate process just as we are doing for typescript checks.

**Comment by arjendeblok** [comment]
@nchanged @vegarringdal I found the issue. When using the SourceMapPlainJsPlugin the source maps are correctly generated with a correct `sourcesContent` property in `File.sourceMap`. In the following line the source map is generated again, but without content.

https://github.com/fuse-box/fuse-box/blob/master/src/core/File.ts#L338

If you remove this line then everything works perfectly and you can debug Aurelia.

@nchanged can you reopen this issue? Should I make a PR for this?.

**Comment by nchanged** [comment]
@arjendeblok sure, but this one actually generates them with {vendor : true}

So we should not break it

**Comment by arjendeblok** [comment]
@nchanged Maybe I do not understand how it supposed to work.

If I add the SourceMapPlainJsPlugin to my build then it will always generate a mapping file for all processed files. It does not check on {vendor: true}. So even on the files in node_modules.

The line at https://github.com/fuse-box/fuse-box/blob/master/src/core/File.ts#L338 also generates a mapping but does not include the source content, so I don't see any code in my browser.

Should the SourceMapPlainJsPlugin also check on {vendor:true}? Or do I miss an option in my fuse-box initialization for SourceMapPlainJsPlugin ?

**Comment by nchanged** [comment]
Well you don't need SourceMapPlainJsPlugin to generate sourcemaps for vendor, that's the thing

**Comment by arjendeblok** [comment]
@nchanged  @vegarringdal All problems seems to be part of including the SourceMapPlainJsPlugin.
If you do not include this then everything works OK.
Maybe the documentation must be changed so that it informs the users that the SourceMapPlainJsPlugin is deprecated.

**Comment by Shepless** [comment]
@nchanged @arjendeblok any word on this one?

**Comment by nchanged** [comment]
We should create an issue related to sourcemaps and combine all of them

**Comment by nchanged** [comment]
There is an issue and I have it partially working in Quantum , I just don't have enough time now. You want to try and test it?

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
