### ISSUE TITLE
SVG logo

### ISSUE THREAD

**Issue by JimiC** [fuse-box/fuse-box#318]
We have been requested to add an icon for `fuse-box` in `vscode-icons`. Is there an SVG version of the logo somewhere, as we only use SVG for icons in our `vscode` extension?

**Comment by nchanged** [comment]
Hi! We have it!  I will attach it here in a bit 
Thanks!

**Comment by nchanged** [comment]
[here](https://github.com/fuse-box/fuse-box/blob/master/logo.svg) it is. Thanks!
