### ISSUE TITLE
jsnext:main / module support

### ISSUE THREAD

**Issue by screendriver** [fuse-box/fuse-box#319]
There are some libraries out there (and getting more) that support the `jsnext:main` / `module` flag. Are there any plans to support this feature?

If you not familiar with it you can read about it here https://github.com/jsforum/jsforum/issues/5 or [here](https://github.com/rollup/rollup/wiki/pkg.module) for example.

**Comment by nchanged** [comment]
Hi!
We are always open to new ideas and suggestions.The main problem is transpiling. As this module needs to be converted to commonjs in fusebox.

**Comment by screendriver** [comment]
> As this module needs to be converted to commonjs in fusebox

Does this mean that fusebox can only deal with CommonJS modules?

**Comment by nchanged** [comment]
It will bundle them, but you would need to transpile.

**Comment by nchanged** [comment]
http://fuse-box.org/#rollup
rollup understands it now. Let's open another one later when we need to bundle it outside rollup.
