### ISSUE TITLE
Lazy loading CSS

### ISSUE THREAD

**Issue by JiDai** [fuse-box/fuse-box#320]
Hi,

I just tried to lazy load a css file (Robot Font), the HTTP request is executes but Fuse add a `script` tag in DOM rather than a `link` tag.

To reproduce I jest download the react example and add this in App.jsx : 

```
FuseBox.import("https://fonts.googleapis.com/css?family=Roboto:100,400,500,700", (module) => {
})
```

Thanks!

**Comment by nchanged** [comment]
It's pretty much impossible to detect it's a CSS file or not. Could you consider loading it in the CSS?

**Comment by JiDai** [comment]
What do you mean by 'loading it in the CSS' ?

**Comment by nchanged** [comment]
I mean using SASS imports or:

https://css-tricks.com/snippets/css/using-font-face/

**Comment by JiDai** [comment]
Ah, I had forgotten this method :). So, yes it works. 
But it will be possible to inject css with `FuseBox.import` ?

**Comment by devmondo** [comment]
this is supposed to be fixed in version 2.0 and the new CSSPLugin update

we will close this for now, but feel free to open it otherwise :)

**Comment by vegarringdal** [comment]
import('https: //fonts.googleapis.com/css?family=Titillium+Web:700|Source+Serif+Pro:400,700|Merriweather+Sans:400,700|Source+Sans+Pro:400,300,600,700,300italic,400italic,600italic,700italic');

is this supposed to be working ?

**Comment by merlinnot** [comment]
What do you want to achieve with this import? I'd use the following syntax:
```html
<style type="text/css">
  @import url('https: //fonts.googleapis.com/css?family=Titillium+Web:700|Source+Serif+Pro:400,700|Merriweather+Sans:400,700|Source+Sans+Pro:400,300,600,700,300italic,400italic,600italic,700italic');
</style>
```

**Comment by vegarringdal** [comment]
be able to have it in my main.ts and have none blocking loading :-)
was mostly wondering if it was supposed to work

**Comment by vegarringdal** [comment]
and wanted to see if it would help my project her:
https://github.com/mframejs/mframejs-sample-realworld

**Comment by merlinnot** [comment]
As a web developer I'd recommend using [font-display](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display) to manage the behaviour of font loading. It doesn't have to be blocking.

You shouldn't try to bundle fonts in any way.

**Comment by vegarringdal** [comment]
Thx for the link.
Will have a look at. Also need to find out how much I can edit to add it to realworld app site.
Atm I dont like that its using css thats messing with my lighthouse audit on accessibility.
But have everything green now atleast :-)
