### ISSUE TITLE
Loading css without injecting when using cssPlugin

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box#321]
Is there a way I can import/get text content without triggering the inject ? I need inject to work when someone does import in ts/js files, but I need to override it when Aurelia loads it

>nchanged @nchanged 23:38
hm...
good point
i got you man
let’s a have an issue
it does not export anything
so aurelia would load it itself right

>devmondo @devmondo 23:39
yeha!
that is why he wants it

>nchanged @nchanged 23:39
sure, let’s have a ticket =)

**Comment by nchanged** [comment]
@vegarringdal lemme clarify here, you don't want fuse to do anything with the css? just return it right?

**Comment by devmondo** [comment]
@nchanged  he wants just the content of the file

**Comment by vegarringdal** [comment]
@nchanged I think I just want better control

Like :
```import 'css!yourstyle.css';``` if you want it to inject the code..

Because importing css and having it injected into the header will override aurelia ```<require>``` tags
Aurelia will do the inject then..

But you had something like that easier and removed it from what you told me.

For just getting the content I can use the raw plugin instead...
But to be honest I really dont know enough about this to say what correct or wrong.

@Thanood, @arabsight  any comments ?

**Comment by vegarringdal** [comment]
@devmondo 
"discussion required" is prob. better tag for this for now 👍

**Comment by devmondo** [comment]
@vegarringdal  at your service :)

**Comment by devmondo** [comment]
this is supposed to be fixed in version 2.0 and new upgrade to the CSS plugin.

we will close this for now, but feel free to open it otherwise :)
