### ISSUE TITLE
less : unexpected token .

### ISSUE THREAD

**Issue by cocodrino** [fuse-box/fuse-box#322]
Hi guys, sorry for the noob question, I'm using the [react-example](https://github.com/fuse-box/react-example) but I've change the css module for the less module

my fuse file
```js
const fsbx = require("fuse-box");


// Create FuseBox Instance
let fuseBox = new fsbx.FuseBox({
    homeDir: "src/",
    sourceMap: {
        bundleReference: "sourcemaps.js.map",
        outFile: "./build/sourcemaps.js.map",
    },
    outFile: "./build/out.js",
    plugins: [
        fsbx.SVGPlugin(),
        fsbx.LESSPlugin(),
        fsbx.BabelPlugin()
    ]
});

fuseBox.devServer(">index.jsx");

```

and I've renamed the css files to less extension and did some minor tweaks to create valid less code

after run node fuse.js the bundle is created and I don't get any error in the shell, but when I open the browser it's empty, the browser console shows

Uncaught SyntaxError: Unexpected token .   App.less:1

the first line in the App.less is 

```less
.App {
    text-align: center;
}
```

if I compile my less file usinc lessc this works perfect, so it's not a problem with my less file
these are the dependencies
I ran npm install less --save-dev before use less

├─┬ babel-core@6.23.1 
│ ├─┬ babel-code-frame@6.22.0 
│ │ ├── esutils@2.0.2 
│ │ └── js-tokens@3.0.1 
│ ├─┬ babel-generator@6.23.0 
│ │ ├─┬ detect-indent@4.0.0 
│ │ │ └─┬ repeating@2.0.1 
│ │ │   └─┬ is-finite@1.0.2 
│ │ │     └── number-is-nan@1.0.1 
│ │ ├── jsesc@1.3.0 
│ │ └── trim-right@1.0.1 
│ ├── babel-helpers@6.23.0 
│ ├── babel-messages@6.23.0 
│ ├─┬ babel-register@6.23.0 
│ │ ├── core-js@2.4.1 
│ │ ├─┬ home-or-tmp@2.0.0 
│ │ │ └── os-tmpdir@1.0.2 
│ │ └── source-map-support@0.4.11 
│ ├─┬ babel-runtime@6.23.0 
│ │ ├── core-js@2.4.1 
│ │ └── regenerator-runtime@0.10.3 
│ ├── babel-template@6.23.0 
│ ├─┬ babel-traverse@6.23.1 
│ │ ├── globals@9.16.0 
│ │ └── invariant@2.2.2 
│ ├─┬ babel-types@6.23.0 
│ │ └── to-fast-properties@1.0.2 
│ ├── babylon@6.16.1 
│ ├── convert-source-map@1.4.0 
│ ├─┬ debug@2.6.1 
│ │ └── ms@0.7.2 
│ ├── json5@0.5.1 
│ ├── lodash@4.17.4 
│ ├─┬ minimatch@3.0.3 
│ │ └─┬ brace-expansion@1.1.6 
│ │   ├── balanced-match@0.4.2 
│ │   └── concat-map@0.0.1 
│ ├── path-is-absolute@1.0.1 
│ ├── private@0.1.7 
│ ├── slash@1.0.0 
│ └── source-map@0.5.6 
├─┬ babel-plugin-transform-react-jsx@6.23.0 
│ ├── babel-helper-builder-react-jsx@6.23.0 
│ └── babel-plugin-syntax-jsx@6.18.0 
├─┬ babel-preset-latest@6.22.0 
│ ├─┬ babel-preset-es2015@6.22.0 
│ │ ├── babel-plugin-check-es2015-constants@6.22.0 
│ │ ├── babel-plugin-transform-es2015-arrow-functions@6.22.0 
│ │ ├── babel-plugin-transform-es2015-block-scoped-functions@6.22.0 
│ │ ├── babel-plugin-transform-es2015-block-scoping@6.23.0 
│ │ ├─┬ babel-plugin-transform-es2015-classes@6.23.0 
│ │ │ ├── babel-helper-define-map@6.23.0 
│ │ │ ├── babel-helper-function-name@6.23.0 
│ │ │ ├── babel-helper-optimise-call-expression@6.23.0 
│ │ │ └── babel-helper-replace-supers@6.23.0 
│ │ ├── babel-plugin-transform-es2015-computed-properties@6.22.0 
│ │ ├── babel-plugin-transform-es2015-destructuring@6.23.0 
│ │ ├── babel-plugin-transform-es2015-duplicate-keys@6.22.0 
│ │ ├── babel-plugin-transform-es2015-for-of@6.23.0 
│ │ ├── babel-plugin-transform-es2015-function-name@6.22.0 
│ │ ├── babel-plugin-transform-es2015-literals@6.22.0 
│ │ ├── babel-plugin-transform-es2015-modules-amd@6.22.0 
│ │ ├─┬ babel-plugin-transform-es2015-modules-commonjs@6.23.0 
│ │ │ └── babel-plugin-transform-strict-mode@6.22.0 
│ │ ├─┬ babel-plugin-transform-es2015-modules-systemjs@6.23.0 
│ │ │ └── babel-helper-hoist-variables@6.22.0 
│ │ ├── babel-plugin-transform-es2015-modules-umd@6.23.0 
│ │ ├── babel-plugin-transform-es2015-object-super@6.22.0 
│ │ ├─┬ babel-plugin-transform-es2015-parameters@6.23.0 
│ │ │ ├── babel-helper-call-delegate@6.22.0 
│ │ │ └── babel-helper-get-function-arity@6.22.0 
│ │ ├── babel-plugin-transform-es2015-shorthand-properties@6.22.0 
│ │ ├── babel-plugin-transform-es2015-spread@6.22.0 
│ │ ├─┬ babel-plugin-transform-es2015-sticky-regex@6.22.0 
│ │ │ └── babel-helper-regex@6.22.0 
│ │ ├── babel-plugin-transform-es2015-template-literals@6.22.0 
│ │ ├── babel-plugin-transform-es2015-typeof-symbol@6.23.0 
│ │ ├─┬ babel-plugin-transform-es2015-unicode-regex@6.22.0 
│ │ │ └─┬ regexpu-core@2.0.0 
│ │ │   ├── regenerate@1.3.2 
│ │ │   ├── regjsgen@0.2.0 
│ │ │   └─┬ regjsparser@0.1.5 
│ │ │     └── jsesc@0.5.0 
│ │ └─┬ babel-plugin-transform-regenerator@6.22.0 
│ │   └── regenerator-transform@0.9.8 
│ ├─┬ babel-preset-es2016@6.22.0 
│ │ └─┬ babel-plugin-transform-exponentiation-operator@6.22.0 
│ │   ├─┬ babel-helper-builder-binary-assignment-operator-visitor@6.22.0 
│ │   │ └── babel-helper-explode-assignable-expression@6.22.0 
│ │   └── babel-plugin-syntax-exponentiation-operator@6.13.0 
│ └─┬ babel-preset-es2017@6.22.0 
│   ├── babel-plugin-syntax-trailing-function-commas@6.22.0 
│   └─┬ babel-plugin-transform-async-to-generator@6.22.0 
│     ├── babel-helper-remap-async-to-generator@6.22.0 
│     └── babel-plugin-syntax-async-functions@6.13.0 
├─┬ fuse-box@1.3.122 
│ ├── acorn@4.0.11 
│ ├─┬ acorn-es7@0.1.0 
│ │ └── acorn@2.7.0 
│ ├─┬ acorn-jsx@3.0.1 
│ │ └── acorn@3.3.0 
│ ├── ansi@0.3.1 
│ ├── app-root-path@2.0.1 
│ ├─┬ base64-img@1.0.3 
│ │ ├─┬ ajax-request@1.2.1 
│ │ │ └── utils-extend@1.0.8 
│ │ └─┬ file-system@2.2.2 
│ │   └── file-match@1.0.2 
│ ├── base64-js@1.2.0 
│ ├── concat-with-sourcemaps@1.0.4 
│ ├─┬ escodegen@1.8.1 
│ │ ├── esprima@2.7.3 
│ │ ├── estraverse@1.9.3 
│ │ ├─┬ optionator@0.8.2 
│ │ │ ├── deep-is@0.1.3 
│ │ │ ├── fast-levenshtein@2.0.6 
│ │ │ ├── levn@0.3.0 
│ │ │ ├── prelude-ls@1.1.2 
│ │ │ ├── type-check@0.3.2 
│ │ │ └── wordwrap@1.0.0 
│ │ └─┬ source-map@0.2.0 
│ │   └── amdefine@1.0.1 
│ ├─┬ express@4.14.1 
│ │ ├─┬ accepts@1.3.3 
│ │ │ └── negotiator@0.6.1 
│ │ ├── array-flatten@1.1.1 
│ │ ├── content-disposition@0.5.2 
│ │ ├── content-type@1.0.2 
│ │ ├── cookie@0.3.1 
│ │ ├── cookie-signature@1.0.6 
│ │ ├─┬ debug@2.2.0 
│ │ │ └── ms@0.7.1 
│ │ ├── depd@1.1.0 
│ │ ├── encodeurl@1.0.1 
│ │ ├── escape-html@1.0.3 
│ │ ├── etag@1.7.0 
│ │ ├─┬ finalhandler@0.5.1 
│ │ │ ├─┬ debug@2.2.0 
│ │ │ │ └── ms@0.7.1 
│ │ │ ├── statuses@1.3.1 
│ │ │ └── unpipe@1.0.0 
│ │ ├── fresh@0.3.0 
│ │ ├── merge-descriptors@1.0.1 
│ │ ├── methods@1.1.2 
│ │ ├─┬ on-finished@2.3.0 
│ │ │ └── ee-first@1.1.1 
│ │ ├── parseurl@1.3.1 
│ │ ├── path-to-regexp@0.1.7 
│ │ ├─┬ proxy-addr@1.1.3 
│ │ │ ├── forwarded@0.1.0 
│ │ │ └── ipaddr.js@1.2.0 
│ │ ├── qs@6.2.0 
│ │ ├── range-parser@1.2.0 
│ │ ├─┬ send@0.14.2 
│ │ │ ├─┬ debug@2.2.0 
│ │ │ │ └── ms@0.7.1 
│ │ │ ├── destroy@1.0.4 
│ │ │ └─┬ http-errors@1.5.1 
│ │ │   └── setprototypeof@1.0.2 
│ │ ├── serve-static@1.11.2 
│ │ ├─┬ type-is@1.6.14 
│ │ │ └── media-typer@0.3.0 
│ │ ├── utils-merge@1.0.0 
│ │ └── vary@1.1.0 
│ ├─┬ glob@7.1.1 
│ │ ├── fs.realpath@1.0.0 
│ │ ├─┬ inflight@1.0.6 
│ │ │ └── wrappy@1.0.2 
│ │ ├── inherits@2.0.3 
│ │ └── once@1.4.0 
│ ├── ieee754@1.1.8 
│ ├─┬ mkdirp@0.5.1 
│ │ └── minimist@0.0.8 
│ ├─┬ postcss@5.2.15 
│ │ ├── js-base64@2.1.9 
│ │ └─┬ supports-color@3.2.3 
│ │   └── has-flag@1.0.0 
│ ├─┬ pretty-time@0.2.0 
│ │ ├─┬ is-number@2.1.0 
│ │ │ └─┬ kind-of@3.1.0 
│ │ │   └── is-buffer@1.1.4 
│ │ └── nanoseconds@0.1.0 
│ ├── prettysize@0.0.3 
│ ├─┬ realm-utils@1.0.8 
│ │ └── app-root-path@1.4.0 
│ ├─┬ request@2.79.0 
│ │ ├── aws-sign2@0.6.0 
│ │ ├── aws4@1.6.0 
│ │ ├── caseless@0.11.0 
│ │ ├─┬ combined-stream@1.0.5 
│ │ │ └── delayed-stream@1.0.0 
│ │ ├── extend@3.0.0 
│ │ ├── forever-agent@0.6.1 
│ │ ├─┬ form-data@2.1.2 
│ │ │ └── asynckit@0.4.0 
│ │ ├─┬ har-validator@2.0.6 
│ │ │ ├─┬ is-my-json-valid@2.16.0 
│ │ │ │ ├── generate-function@2.0.0 
│ │ │ │ ├─┬ generate-object-property@1.2.0 
│ │ │ │ │ └── is-property@1.0.2 
│ │ │ │ └── jsonpointer@4.0.1 
│ │ │ └─┬ pinkie-promise@2.0.1 
│ │ │   └── pinkie@2.0.4 
│ │ ├─┬ hawk@3.1.3 
│ │ │ ├── boom@2.10.1 
│ │ │ ├── cryptiles@2.0.5 
│ │ │ ├── hoek@2.16.3 
│ │ │ └── sntp@1.0.9 
│ │ ├─┬ http-signature@1.1.1 
│ │ │ ├── assert-plus@0.2.0 
│ │ │ ├─┬ jsprim@1.3.1 
│ │ │ │ ├── extsprintf@1.0.2 
│ │ │ │ ├── json-schema@0.2.3 
│ │ │ │ └── verror@1.3.6 
│ │ │ └─┬ sshpk@1.10.2 
│ │ │   ├── asn1@0.2.3 
│ │ │   ├── assert-plus@1.0.0 
│ │ │   ├── bcrypt-pbkdf@1.0.1 
│ │ │   ├─┬ dashdash@1.14.1 
│ │ │   │ └── assert-plus@1.0.0 
│ │ │   ├── ecc-jsbn@0.1.1 
│ │ │   ├─┬ getpass@0.1.6 
│ │ │   │ └── assert-plus@1.0.0 
│ │ │   ├── jodid25519@1.0.2 
│ │ │   ├── jsbn@0.1.1 
│ │ │   └── tweetnacl@0.14.5 
│ │ ├── is-typedarray@1.0.0 
│ │ ├── isstream@0.1.2 
│ │ ├── json-stringify-safe@5.0.1 
│ │ ├─┬ mime-types@2.1.14 
│ │ │ └── mime-db@1.26.0 
│ │ ├── oauth-sign@0.8.2 
│ │ ├── qs@6.3.1 
│ │ ├── stringstream@0.0.5 
│ │ ├─┬ tough-cookie@2.3.2 
│ │ │ └── punycode@1.4.1 
│ │ ├── tunnel-agent@0.4.3 
│ │ └── uuid@3.0.1 
│ ├─┬ watch@1.0.2 
│ │ ├─┬ exec-sh@0.2.0 
│ │ │ └── merge@1.2.0 
│ │ └── minimist@1.2.0 
│ └─┬ ws@1.1.2 
│   ├── options@0.0.6 
│   └── ultron@1.0.2 
├─┬ gulp@3.9.1 
│ ├── archy@1.0.0 
│ ├─┬ chalk@1.1.3 
│ │ ├── ansi-styles@2.2.1 
│ │ ├── escape-string-regexp@1.0.5 
│ │ ├─┬ has-ansi@2.0.0 
│ │ │ └── ansi-regex@2.1.1 
│ │ ├── strip-ansi@3.0.1 
│ │ └── supports-color@2.0.0 
│ ├── deprecated@0.0.1 
│ ├─┬ gulp-util@3.0.8 
│ │ ├── array-differ@1.0.0 
│ │ ├── array-uniq@1.0.3 
│ │ ├── beeper@1.1.1 
│ │ ├── dateformat@2.0.0 
│ │ ├─┬ fancy-log@1.3.0 
│ │ │ └── time-stamp@1.0.1 
│ │ ├── has-gulplog@0.1.0 
│ │ ├── lodash._reescape@3.0.0 
│ │ ├── lodash._reevaluate@3.0.0 
│ │ ├── lodash._reinterpolate@3.0.0 
│ │ ├─┬ lodash.template@3.6.2 
│ │ │ ├── lodash._basecopy@3.0.1 
│ │ │ ├── lodash._basetostring@3.0.1 
│ │ │ ├── lodash._basevalues@3.0.0 
│ │ │ ├── lodash._isiterateecall@3.0.9 
│ │ │ ├─┬ lodash.escape@3.2.0 
│ │ │ │ └── lodash._root@3.0.1 
│ │ │ ├─┬ lodash.keys@3.1.2 
│ │ │ │ ├── lodash._getnative@3.9.1 
│ │ │ │ ├── lodash.isarguments@3.1.0 
│ │ │ │ └── lodash.isarray@3.0.4 
│ │ │ ├── lodash.restparam@3.6.1 
│ │ │ └── lodash.templatesettings@3.1.1 
│ │ ├── minimist@1.2.0 
│ │ ├─┬ multipipe@0.1.2 
│ │ │ └─┬ duplexer2@0.0.2 
│ │ │   └── readable-stream@1.1.14 
│ │ ├── object-assign@3.0.0 
│ │ ├── replace-ext@0.0.1 
│ │ ├─┬ through2@2.0.3 
│ │ │ ├─┬ readable-stream@2.2.3 
│ │ │ │ ├── buffer-shims@1.0.0 
│ │ │ │ ├── isarray@1.0.0 
│ │ │ │ ├── process-nextick-args@1.0.7 
│ │ │ │ └── util-deprecate@1.0.2 
│ │ │ └── xtend@4.0.1 
│ │ └─┬ vinyl@0.5.3 
│ │   ├── clone@1.0.2 
│ │   └── clone-stats@0.0.1 
│ ├── interpret@1.0.1 
│ ├─┬ liftoff@2.3.0 
│ │ ├─┬ findup-sync@0.4.3 
│ │ │ ├─┬ detect-file@0.1.0 
│ │ │ │ └── fs-exists-sync@0.1.0 
│ │ │ ├─┬ is-glob@2.0.1 
│ │ │ │ └── is-extglob@1.0.0 
│ │ │ ├─┬ micromatch@2.3.11 
│ │ │ │ ├─┬ arr-diff@2.0.0 
│ │ │ │ │ └── arr-flatten@1.0.1 
│ │ │ │ ├── array-unique@0.2.1 
│ │ │ │ ├─┬ braces@1.8.5 
│ │ │ │ │ ├─┬ expand-range@1.8.2 
│ │ │ │ │ │ └─┬ fill-range@2.2.3 
│ │ │ │ │ │   ├─┬ isobject@2.1.0 
│ │ │ │ │ │   │ └── isarray@1.0.0 
│ │ │ │ │ │   ├── randomatic@1.1.6 
│ │ │ │ │ │   └── repeat-string@1.6.1 
│ │ │ │ │ ├── preserve@0.2.0 
│ │ │ │ │ └── repeat-element@1.1.2 
│ │ │ │ ├─┬ expand-brackets@0.1.5 
│ │ │ │ │ └── is-posix-bracket@0.1.1 
│ │ │ │ ├── extglob@0.3.2 
│ │ │ │ ├── filename-regex@2.0.0 
│ │ │ │ ├── normalize-path@2.0.1 
│ │ │ │ ├─┬ object.omit@2.0.1 
│ │ │ │ │ ├─┬ for-own@0.1.5 
│ │ │ │ │ │ └── for-in@1.0.1 
│ │ │ │ │ └── is-extendable@0.1.1 
│ │ │ │ ├─┬ parse-glob@3.0.4 
│ │ │ │ │ ├─┬ glob-base@0.3.0 
│ │ │ │ │ │ └── glob-parent@2.0.0 
│ │ │ │ │ └── is-dotfile@1.0.2 
│ │ │ │ └─┬ regex-cache@0.4.3 
│ │ │ │   ├── is-equal-shallow@0.1.3 
│ │ │ │   └── is-primitive@2.0.0 
│ │ │ └─┬ resolve-dir@0.1.1 
│ │ │   └─┬ global-modules@0.2.3 
│ │ │     ├─┬ global-prefix@0.1.5 
│ │ │     │ ├─┬ homedir-polyfill@1.0.1 
│ │ │     │ │ └── parse-passwd@1.0.0 
│ │ │     │ ├── ini@1.3.4 
│ │ │     │ └─┬ which@1.2.12 
│ │ │     │   └── isexe@1.1.2 
│ │ │     └── is-windows@0.2.0 
│ │ ├─┬ fined@1.0.2 
│ │ │ ├── expand-tilde@1.2.2 
│ │ │ ├── lodash.assignwith@4.2.0 
│ │ │ ├── lodash.isempty@4.4.0 
│ │ │ ├── lodash.pick@4.4.0 
│ │ │ └─┬ parse-filepath@1.0.1 
│ │ │   ├─┬ is-absolute@0.2.6 
│ │ │   │ └─┬ is-relative@0.2.1 
│ │ │   │   └─┬ is-unc-path@0.1.2 
│ │ │   │     └── unc-path-regex@0.1.2 
│ │ │   ├── map-cache@0.2.2 
│ │ │   └─┬ path-root@0.1.1 
│ │ │     └── path-root-regex@0.1.2 
│ │ ├── flagged-respawn@0.3.2 
│ │ ├── lodash.isplainobject@4.0.6 
│ │ ├── lodash.isstring@4.0.1 
│ │ ├── lodash.mapvalues@4.6.0 
│ │ ├── rechoir@0.6.2 
│ │ └─┬ resolve@1.3.2 
│ │   └── path-parse@1.0.5 
│ ├── minimist@1.2.0 
│ ├─┬ orchestrator@0.3.8 
│ │ ├─┬ end-of-stream@0.1.5 
│ │ │ └── once@1.3.3 
│ │ ├── sequencify@0.0.7 
│ │ └── stream-consume@0.1.0 
│ ├── pretty-hrtime@1.0.3 
│ ├── semver@4.3.6 
│ ├─┬ tildify@1.2.0 
│ │ └── os-homedir@1.0.2 
│ ├─┬ v8flags@2.0.11 
│ │ └── user-home@1.1.1 
│ └─┬ vinyl-fs@0.3.14 
│   ├── defaults@1.0.3 
│   ├─┬ glob-stream@3.1.18 
│   │ ├── glob@4.5.3 
│   │ ├─┬ glob2base@0.0.12 
│   │ │ └── find-index@0.1.1 
│   │ ├── minimatch@2.0.10 
│   │ ├── ordered-read-streams@0.1.0 
│   │ ├─┬ through2@0.6.5 
│   │ │ └── readable-stream@1.0.34 
│   │ └── unique-stream@1.0.0 
│   ├─┬ glob-watcher@0.0.6 
│   │ └─┬ gaze@0.5.2 
│   │   └─┬ globule@0.1.0 
│   │     ├─┬ glob@3.1.21 
│   │     │ ├── graceful-fs@1.2.3 
│   │     │ └── inherits@1.0.2 
│   │     ├── lodash@1.0.2 
│   │     └─┬ minimatch@0.2.14 
│   │       ├── lru-cache@2.7.3 
│   │       └── sigmund@1.0.1 
│   ├─┬ graceful-fs@3.0.11 
│   │ └── natives@1.1.0 
│   ├─┬ strip-bom@1.0.0 
│   │ ├── first-chunk-stream@1.0.0 
│   │ └── is-utf8@0.2.1 
│   ├─┬ through2@0.6.5 
│   │ └── readable-stream@1.0.34 
│   └─┬ vinyl@0.4.6 
│     └── clone@0.2.0 
├─┬ gulp-server-livereload@1.9.2 
│ ├─┬ commander@2.9.0 
│ │ └── graceful-readlink@1.0.1 
│ ├─┬ connect@3.1.1 
│ │ ├─┬ debug@1.0.4 
│ │ │ └── ms@0.6.2 
│ │ └─┬ finalhandler@0.1.0 
│ │   └── escape-html@1.0.1 
│ ├── connect-inject@0.3.2 
│ ├─┬ glogg@1.0.0 
│ │ └── sparkles@1.0.0 
│ ├── gulplog@1.0.0 
│ ├── node-watch@0.3.5 
│ ├─┬ node.extend@1.0.10 
│ │ └── is@0.3.0 
│ ├── open@0.0.5 
│ ├── proxy-middleware@0.15.0 
│ ├─┬ serve-index@1.1.6 
│ │ ├─┬ accepts@1.0.7 
│ │ │ ├── mime-types@1.0.2 
│ │ │ └── negotiator@0.4.7 
│ │ └── batch@0.5.1 
│ ├─┬ serve-static@1.5.4 
│ │ ├── escape-html@1.0.1 
│ │ └─┬ send@0.8.5 
│ │   ├── debug@1.0.4 
│ │   ├── depd@0.4.4 
│ │   ├── destroy@1.0.3 
│ │   ├── fresh@0.2.2 
│ │   ├── mime@1.2.11 
│ │   ├── ms@0.6.2 
│ │   ├─┬ on-finished@2.1.0 
│ │   │ └── ee-first@1.0.5 
│ │   └── range-parser@1.0.3 
│ ├─┬ socket.io@1.7.3 
│ │ ├── debug@2.3.3 
│ │ ├─┬ engine.io@1.8.3 
│ │ │ ├── base64id@1.0.0 
│ │ │ ├── debug@2.3.3 
│ │ │ └─┬ engine.io-parser@1.3.2 
│ │ │   ├── after@0.8.2 
│ │ │   ├── arraybuffer.slice@0.0.6 
│ │ │   ├── base64-arraybuffer@0.1.5 
│ │ │   ├── blob@0.0.4 
│ │ │   └── wtf-8@1.0.0 
│ │ ├── has-binary@0.1.7 
│ │ ├── object-assign@4.1.0 
│ │ ├─┬ socket.io-adapter@0.5.0 
│ │ │ └── debug@2.3.3 
│ │ ├─┬ socket.io-client@1.7.3 
│ │ │ ├── backo2@1.0.2 
│ │ │ ├── component-bind@1.0.0 
│ │ │ ├── component-emitter@1.2.1 
│ │ │ ├── debug@2.3.3 
│ │ │ ├─┬ engine.io-client@1.8.3 
│ │ │ │ ├── component-emitter@1.2.1 
│ │ │ │ ├── component-inherit@0.0.3 
│ │ │ │ ├── debug@2.3.3 
│ │ │ │ ├── has-cors@1.1.0 
│ │ │ │ ├── parsejson@0.0.3 
│ │ │ │ ├── parseqs@0.0.5 
│ │ │ │ ├── xmlhttprequest-ssl@1.5.3 
│ │ │ │ └── yeast@0.1.2 
│ │ │ ├── indexof@0.0.1 
│ │ │ ├── object-component@0.0.3 
│ │ │ ├─┬ parseuri@0.0.5 
│ │ │ │ └─┬ better-assert@1.0.2 
│ │ │ │   └── callsite@1.0.0 
│ │ │ └── to-array@0.1.4 
│ │ └─┬ socket.io-parser@2.3.1 
│ │   ├── component-emitter@1.1.2 
│ │   ├─┬ debug@2.2.0 
│ │   │ └── ms@0.7.1 
│ │   └── json3@3.3.2 
│ ├─┬ through2@0.5.1 
│ │ ├─┬ readable-stream@1.0.34 
│ │ │ ├── core-util-is@1.0.2 
│ │ │ ├── isarray@0.0.1 
│ │ │ └── string_decoder@0.10.31 
│ │ └── xtend@3.0.0 
│ └─┬ vinyl-fs@1.0.0 
│   ├─┬ duplexify@3.5.0 
│   │ ├─┬ end-of-stream@1.0.0 
│   │ │ └── once@1.3.3 
│   │ ├─┬ readable-stream@2.2.3 
│   │ │ └── isarray@1.0.0 
│   │ └── stream-shift@1.0.0 
│   ├─┬ glob-stream@4.1.1 
│   │ ├── glob@4.5.3 
│   │ ├── minimatch@2.0.10 
│   │ ├─┬ through2@0.6.5 
│   │ │ └── xtend@4.0.1 
│   │ └─┬ unique-stream@2.2.1 
│   │   ├─┬ json-stable-stringify@1.0.1 
│   │   │ └── jsonify@0.0.0 
│   │   └── through2-filter@2.0.0 
│   ├── glob-watcher@0.0.8 
│   ├─┬ merge-stream@0.1.8 
│   │ └─┬ through2@0.6.5 
│   │   └── readable-stream@1.0.34 
│   ├── object-assign@2.1.1 
│   ├─┬ through2@0.6.5 
│   │ └── xtend@4.0.1 
│   └─┬ vinyl@0.4.6 
│     └── clone@0.2.0 
├─┬ less@2.7.2 
│ ├─┬ errno@0.1.4 
│ │ └── prr@0.0.0 
│ ├── graceful-fs@4.1.11 
│ ├── image-size@0.5.1 
│ ├── mime@1.3.4 
│ └─┬ promise@7.1.1 
│   └── asap@2.0.5 
├─┬ react@15.4.2 
│ ├─┬ fbjs@0.8.9 
│ │ ├── core-js@1.2.7 
│ │ ├─┬ isomorphic-fetch@2.2.1 
│ │ │ ├─┬ node-fetch@1.6.3 
│ │ │ │ ├─┬ encoding@0.1.12 
│ │ │ │ │ └── iconv-lite@0.4.15 
│ │ │ │ └── is-stream@1.1.0 
│ │ │ └── whatwg-fetch@2.0.2 
│ │ ├── setimmediate@1.0.5 
│ │ └── ua-parser-js@0.7.12 
│ ├── loose-envify@1.3.1 
│ └── object-assign@4.1.1 
├── react-dom@15.4.2 
├── reflect-metadata@0.1.10 
├── run-sequence@1.2.2 
└── typescript@2.2.1 

thank you guys!!!

**Comment by nchanged** [comment]
welcome @cocodrino 
You need to chain it into the CSSPlugin()

```
const {FuseBox, SVGPlugin,  LESSPlugin, BabelPlugin } = require("fuse-box");

// Create FuseBox Instance
let fuseBox = new fsbx.FuseBox({
    homeDir: "src/",
    sourceMap: {
        bundleReference: "sourcemaps.js.map",
        outFile: "./build/sourcemaps.js.map",
    },
    outFile: "./build/out.js",
    plugins: [
        SVGPlugin(),
        [LESSPlugin(), CSSPlugin() ],
        BabelPlugin() 
    ]
});

fuseBox.devServer(">index.jsx");
```

**Comment by cocodrino** [comment]
@nchanged oh..thank you!!!..it works..thanks!!!...
