### ISSUE TITLE
'bundle' function not well documented (promise or callback?)

### ISSUE THREAD

**Issue by lmartorella** [fuse-box/fuse-box#327]
Hi,
From the documentation it seems that the main 'bundle' function is synchronous.
However it returns a promise _and_ take a ready callback as a second undocumented property.

Trying to use the promise API will return before the output files are written, since at the end of the writing the callback is called.
How fusebox is supposed to be called in a script that needs to work with the produced files?
Shouldn't be better to only expose one method for completion callback?
Thank you,
 Luciano

**Comment by nchanged** [comment]
Hi Luciano.
`then` is resolved when bundle is ready.

And a callback is called when fusebox finished writing. 
```
bundle(">index.ts", () => {
// finished writing the ouput
})
```


I hope it's clear now

**Comment by lmartorella** [comment]
Yep, I exactly discovered this debugging my scripts going inside fuse-box after found that the files was not yet ready when the promise was triggered. I used the returned promise because it seemed right that all async operations would be completed at is completion.

Would you say that the current API is intuitive? Why promise and callback has different meaning (writing the file _and_ prepare the bundle)?
I would tend to remove one of the two concepts, only leaving the promise or the callback. Once done, this should be triggered only at the end of all activities (i.e. when the file are written).

In any way, the doc should mention this. The most common usage of fuse API is to do something when the bundle is completed...
Thx L

**Comment by nchanged** [comment]
@lmartorella The thing is, that users might not want to write anything to files, `then` happens when a bundle is truly ready. It gives you the source of your bundle. A Callback happens when it's written. Not very intuitive, I agree.

**Comment by geowarin** [comment]
Here is what I'm using for my project:

```js
fsbx.bundle({
  ['pages.js']: "> lib/renderer.ts"
}).then(bundle => {
  if (!bundle) throw new Error("Could not generate bundle")
});
```

So that the build fails when the bundle errors.
Maybe bundle() should throw by default?

**Comment by nchanged** [comment]
like that?
```
fsbx.bundle({
  'pages.js': "> lib/pages.ts"
}).then(bundle => {
  if (!bundle) throw new Error("Could not generate bundle")
});

**Comment by nchanged** [comment]
Closing this one for now.
