### ISSUE TITLE
"Bundle in a bundle" example wanted

### ISSUE THREAD

**Issue by lmartorella** [fuse-box/fuse-box#328]
Hi,
I'm searching a way to split my codebase in two layers: an API + third-party libraries and the 'application' layer. Using Typescript, I would prefer to include in the package.json of the application the same dependencies exposed by my lib (@angular and all its dependencies like core-js, rxjs, etc...).

The [bundle in a bundle](http://fuse-box.org/#bundle-in-a-bundle) feature would be great in that case, allowing the application to import from the API/third-party lib all the angular2 stuff.

However the feature is not well documented. I was struggling to understand how fusebox should be used in a simple case like this:
- library A (base) that imports third-party T
- library B (app) that depends on A (and hence on T).

How can be fuse-box used to bundle T inside A and let B to NOT bundle A nor T?
A github sample (like the fusing one) could be great.

Thank you,
 Luciano

**Comment by nchanged** [comment]
Luciano!
You can achieve that by using arithmetic instructions like so:

`> a.ts -t`

In this case, fusebox will bundle everything that's related to file `a.ts` and its dependents except for the library `t`

If you need an explicit example we can do that later.

**Comment by lmartorella** [comment]
Ah ok, I thought this to be an automatic process. The creator of the B (app) library should instead manually exclude packages as they are already included in the A (base) package.
Ok thanks, L.
