### ISSUE TITLE
A better way to store plugins

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#33]
We started having more and more and plugins, and it makes sense to have a different approach to storing them. Will be happy to hear your ideas on how and why.
@Shepless suggests `monorepo` for example.  I don't mind it, but there are downsides to it. 

What's on your mind?

**Comment by devmondo** [comment]
personally i prefer to have all essential plugins as part of fuse, like `JSON, HTML, CSS, TEXT`, etc.. 
because those are 90% common in any web project so it makes snese to have them built in.

as for extra stuff like `less, postcss` etc, it makes sense to have them in their own dedicated repos.

**Comment by nchanged** [comment]
Yeah, core plugins stay in the repository. I agree.

**Comment by leon-andria** [comment]
I agree too

**Comment by Shepless** [comment]
I think we can maybe do both. I think maybe something like:

```npm i @fusebox/core``` <--- Bundler, Essential Plugins
```npm i @fusebox/plugin-a``` etc. etc.

**Comment by devmondo** [comment]
@Shepless good suggestion :) , maybe i am wrong but i see that for new comers we want them to feel that `npm i fuse-box` is all what they need to do to start any generic web project without thinking about minimal requirements.

**Comment by Shepless** [comment]
@devmondo My honest take on this is keep things separate. E.g. `@fuse-box/bundler`, `@fuse-box/css-plugin` etc. My reasons are:

- Tight coupling of plugins with bundler distribution, versioning and release cycles
- How does a "core plugin" get determined? It's very relative. What is core for my needs may be obscure for yours
- I see this as the responsibility of tooling/community efforts. For example, we should (and probably will) provide a CLI Tool for FuseBox that can offer a single command to install the "core-plugins": e.g. `fusebox install core-plugins`. Taking that a step further - the community could combine individual plugins to create their own "plugin group + config" and submit those for inclusion?

E.g. `angular-less-typescript-boilerplater` <--- This includes all plugins and a starter fusebox.js config file to get started, there isn't anything easier than that!

**Comment by nchanged** [comment]
@Shepless CLI version sounds very good. It could list available plugins with versions as well!

**Comment by Shepless** [comment]
@nchanged to manage that properly we should probably have a separate repo for "fusebox plugin groups", it can be curated and the community to contribute new configurations to it. This is also where the CLI will probably query for the list and version checks. What do you think?

**Comment by nchanged** [comment]
@Shepless I think that's the way to go. But if we have a CLI in place and it's so easy to install plugins, why would we go for plugin groups? If a person uses `less` he does not need 10 more plugins installed.

**Comment by Shepless** [comment]
@nchanged the plugin groups is a feature on top of the individual install. E.g.

#### Individual Install
`fusebox install @fusebox/less-plugin`

#### Group/Boilerplate Install
`fusebox list-groups`
...
`fusebox install-group some-persons-boilerplater` <-- includes bundler config and all required plugins

**Comment by nchanged** [comment]
@Shepless we can do both right. And boilerplates are a great idea!

**Comment by devmondo** [comment]
i dont want to be the pessimistic guy here, but seriously, this is going in a direction that is making having fuse installed and get running a more boilerplate.

dont get me wrong i am not against any of those ideas, they are all great, but for me , one of the biggest positives of fuse is that i can do install and boom it works.

@Shepless i respectfully disagree :) there are still generic web projects, and not only that, sometimes i want to do fast prototype or jsfiddle kind of example thus i dont need more than simple HTML, CSS and JS.

i strongly believe in keeping Fuse ability to be used out of the box without extra steps required, again that does not mean there should be no CLI or any of the above suggested features.

**Comment by Shepless** [comment]
@devmondo You can do that in two commands with what I'm proposing:

`npm i @fusebox/bundler`
`fubsebox install-group html5` 

The "groups" would only do the following:

- Auto add the config from the group, e.g. `Fusebox.init()`
- Install the plugins listed in the group (e.g. `npm i @fusebox/css-plugin @fusebox/html-plugin` etc

So you're output from that is - a correct fusebox config ready to run your bundle and all required plugins installed. Using this approach we cater for the "get up and running with 0 effort" but also for people who want more complex "boilerplaters" e.g. React etc.

**Comment by devmondo** [comment]
@Shepless i am not disagreeing at all, i have lots of projects with jspm and i tried webpack, and i really had big issues with clients and devs when it comes to this, they just want things to work, lazy...

i cool approach i see is that 
`npm i fuse-box`
`fuse-box init`
then cli asks you questions about what is your home-dir, install default plugins, etc...

**Comment by Shepless** [comment]
@devmondo that sounds cool. With that we can still use the mono repo approach and deployment plugins individually, but the CLI tool makes it simple/fast to get up and running. I like 😄

**Comment by leon-andria** [comment]
I'm not a fan of CLI here.
The reason is that the all about FuseBox is Simplicity. Today, creating a plugin with it is so simple lets say that it took 10min :-)
No need about templates or whatever, the readme or a link to gist is faster and easy to maintain.
A CLI means support and extra work and effort.

**Comment by vanthiyathevan** [comment]
Hello,
i've written an eslint plugin with tests https://github.com/vanthiyathevan/fuse-box-plugin-eslint
will wait for the outcome of this issue before publishing to npm

**Comment by eisisig** [comment]
I think you should try to use the package managers as much as possible to utilize their strengths. Private repos for private plugins, cache etc...

The "group" thing is essentially the babel preset idea. And that is just a npm package which has other plugins as dependencies so they get installed when you install the preset (in simple terms)...

So I don't think creating a cli for this is needed at the beginning. I have created few for our internal processes and it sucks maintaining them. The line of what should be included, what it should be doing, how, why etc... Then just the extra effort of extra code that is just doing somthing that can be done with npm and js in it basic form...


```bash
yarn install fuse-box fuse-box-preset-react fuse-box-plugin-less
```

My 2c
