### ISSUE TITLE
Declaration files not built and full paths for sourcemaps files

### ISSUE THREAD

**Issue by thamak** [fuse-box/fuse-box#330]
Hello,

I am trying to debug with vscode a simple project with this config :
```
const fb = require("fuse-box");
const FuseBox = fb.FuseBox;

const fuse = FuseBox.init({
    homeDir: "src",
    outFile: "dist/app.js",
    log: true,
    debug: true,
    cache: false,
    tsConfig: 'tsconfig.json',
    sourceMap: {
        bundleReference: 'app.js.map',
        outFile: 'dist/app.js.map',
    }
}).bundle("> index.ts");
```

with this tsconfig.json file :
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "noImplicitAny": false,
        "sourceMap": true,
        "declaration": true,
        "declarationDir": "dist/dec/"
    }
}
```

the console tell me that my tsconfig is used but I don't see any declaration file (index.d.ts, foo.d.ts) built. With tsc command, I get my declaration files though. Am i missing something ?

Secondly, how can I tell fuze to add the full path to my sources in the sourcemaps files ? 
This is what I got actually :
```{"version":3,"sources":["index.ts","foo.ts",...```
This is what I wish :
```{"version":3,"sources":["../src/index.ts","../src/foo.ts",...```
I looked around but could not find anything (plugin ?) to do this. 

Thank you !

**Comment by nchanged** [comment]
Hi! Thanks for the issue. It's on our list.

**Comment by thamak** [comment]
Is the full path to the sourcemaps file also on your list ? 
I need this to debug properly using the integrated console of vscode. 
Thanks

**Comment by nchanged** [comment]
@thamak sourcemaps are generated accordingly to the virtual fusebox' paths. That's how fusebox works, but certainly, we could have a discussion on that (like an option or something)

Please, suggest your ideas!

**Comment by thamak** [comment]
Oh I see, it makes sense now. 
Maybe we could imagine having another property on the sourceMap node like :
```
sourceMap: {
    bundleReference: 'app.js.map',
    outFile: 'dist/app.js.map',
    srcRoot: 'src'
 }
```
where srcRoot (or srcDir ?) represents the root directory where the sources are stored.

**Comment by nchanged** [comment]
Yep , that could be done!

**Comment by thamak** [comment]
Ok I found a workaround, adding the `sourceRoot` property to the tsconfig.json like this :
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "noImplicitAny": false,
        "sourceMap": true,
        "sourceRoot": "../src"
    }
}
```
makes it work just fine.
I can still continue working on the feature to support the option on the sourceMap node, but is it still worth it ?

**Comment by nchanged** [comment]
I think could just mention your trick in the documentation?!

**Comment by eddow** [comment]
Good news! I wanted to open an issue on their github, but since last month, they corrected it ... !

**Comment by eddow** [comment]
Up - about the sourceMap full path
The work-around is tough to get working (I still didn't succeed) and, anyway, it is a workaround...
Sourcemap path would - I think - definitely deserve several kind of treatment - at least one for the server and one for the client. Indeed, the present behaviour is perfect client-side - so the `srcRoot` solution is relevant

**Comment by nchanged** [comment]
I believe this has been solved with the latest beta

http://fuse-box.org/page/configuration#hosting-source-files
