### ISSUE TITLE
Simplified REGEXP (strings) 

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#331]
Make it possible to define a simplified string RegEx on the plugin list.
e.g

```
plugins : [
     ["styles/*.css", CSSPlugin()]
]
```

**Comment by stoffeastrom** [comment]
Maybe even the more advanced version

```
plugins: [
  ['styles/*.css', 'views/*.html', RawPlugin()]
  ['styles/*.css', 'views/*.ts', CSSPlugin()]
]
```
The first element would be the file that is requested
The second element would be the file that initiates the request

**Comment by stoffeastrom** [comment]
I mean that it could support both the short version and the above of course :)

**Comment by nchanged** [comment]
```
plugins: [
  ['styles/*.css|views/*.html', RawPlugin()]
}
```
Looks more consistent?!

**Comment by cellog** [comment]
Just want to say that if the 2 regexes have different meanings (one is the css files, the other is the file that requires them) then an array is the wrong structure. You want to use a map so that someone can instantly know the meaning of each regex.

**Comment by nchanged** [comment]
[tests](https://github.com/fuse-box/fuse-box/blob/master/src/tests/String2Regexp.test.ts)
