### ISSUE TITLE
New arithmetic symbol ~

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#335]
UPD.
# `~` will be introduced in `1.3.123`

`~  index.ts ` Will do exactly the opposite of  what `[ index.ts ]` does.

`~ index.ts ` Means that index.ts and every single file in the dependency tree (related to your homeDir) will **NOT** be bundled, only related libraries (from node_modules) will be included.

You can call it - an **automatic** vendor extraction

## Variations
* `~  index.ts` 
*  `~ **/lib/**.ts`
*  `~ **/lib/**.ts + some_cool_lib_which_is_no_in_the_dep_tree`

**Comment by con-ssc** [comment]
I find the [] notation already confusing, not a big fan of this one neither.

**Comment by nchanged** [comment]
@con-ssc you can't use absolute paths there. That's your problem =)

**Comment by arabsight** [comment]
very helpful :smiley: node_modules getting fused

**Comment by con-ssc** [comment]
@nchanged okay different example
```
${my_saved_path_variable}/{not_a_variable.ts}
```
