### ISSUE TITLE
Emit `source-changed` for the `RawPlugin`

### ISSUE THREAD

**Issue by stoffeastrom** [fuse-box/fuse-box#337]
The RawPlugin doesn't emit `source-changed`like the `CSSPlugin`. This makes it impossible for the `fuse-box-aurelia-loader`to react on css changes.

**Comment by nchanged** [comment]
Cool.
How about some improvement to usability? 

```
RawPlugin(["*.scss", "lib/styles/*.css"])
```

**Comment by nchanged** [comment]
Available in the preview `fsbx@1.3.123-preview.11`
