### ISSUE TITLE
`EnvPlugin` wrong type arguments

### ISSUE THREAD

**Issue by stoffeastrom** [fuse-box/fuse-box#346]
`banner: string` should be `env:any`

[this](https://github.com/fuse-box/fuse-box/blob/master/src/plugins/EnvPlugin.ts#L16) should probably change to [this](https://github.com/fuse-box/fuse-box/blob/master/src/plugins/EnvPlugin.ts#L10)

**Comment by nchanged** [comment]
Thanks, you are so right ;-)

**Comment by stoffeastrom** [comment]
;-)

**Comment by devmondo** [comment]
thanks, done https://github.com/fuse-box/fuse-box/commit/1a2655c5a854a0e619d9dc7f24e102ed6afca327
