### ISSUE TITLE
Breaking changes: outFile -> output

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#349]
Due to the limitations of `outFile` it will be replaced with `output`.
Which will:

* Allow cache busting
* Reference original folder for plugins (+ cache busting)
* Fix the mess with `multibundle`

`output : "dist/$name.js`

If no `multi-bundle` specified filename will be 'bundle' 

In a case of a multi-bundle:
```
bundle({
   "vendor" : "~ index.ts",
   "app" : " > [index.ts]"
})
```

2 files will be created `dist/vendor.js` and `dist/app.js`

Setting 
`hash : true`

Will automatically append file cache to the `$name` unless `$hash` is found in the `output` string.
e.g.

```
output : "dist/$name-$hash.js"
```

**Comment by wagerfield** [comment]
Will setting `hash: true` default to using md5? We had discussed that `hash` could potentially be a string too that would allow different hashing algorithms to be used. So hash could be either a falsey value (`false|null|undefined|''), `true` (to default to md5) or a string for another hashing algorithm that might get added in the future.

**Comment by nchanged** [comment]
@wagerfield exactly like you said ;-)

**Comment by wagerfield** [comment]
`devServer` will also need addressing in this update. Right now it relies on `outFile` and doesn't support multiple bundles.
