### ISSUE TITLE
Unable to remove process module from bundle

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box#351]
I have this that I want to keep as own bundle since it will not change, and generating sourcemaps will take a while.

But for some reason Im not able to get process away with ```- process```
tried with and without sourcemaps, standalone, I deleted cache before I tried..
Even tried ```[module]```.. but no luck
Using fuse-box 1.3.123, windows 10

Maybe something Ive overlooked ?

```
var build = function () {

    let fb = require("fuse-box");
    let fuse = fb.FuseBox;

    let bundle = fuse.init({
        outFile: "./bundle/fb-aurelia-framework-bundle.js",
        sourcemaps: { project : true, vendor : true}
    })

    bundle.bundle(`
          aurelia-bootstrapper
        + aurelia-framework
        + aurelia-pal
        + aurelia-metadata
        + aurelia-polyfills
        + aurelia-fetch-client
        + aurelia-pal-browser
        + aurelia-animator-css
        + aurelia-logging-console 
        + aurelia-templating-binding 
        + aurelia-templating-resources 
        + aurelia-event-aggregator 
        + aurelia-history-browser 
        + aurelia-templating-router
        + aurelia-hot-module-reload
        - process
    `);

}

build();
```

![image](https://cloud.githubusercontent.com/assets/2901416/23592341/fa09de94-0207-11e7-8e12-9f5d42fa6408.png)

**Comment by nchanged** [comment]
Yeah, i see what's happening. Some of the modules require process. Therefore fuse can't just ignore it. We need to find a way to `ban` modules

**Comment by vegarringdal** [comment]
ok, little bit unsure why it still adding it, I have no entry point...

**Comment by vegarringdal** [comment]
```
bundle.bundle(`
         aurelia-dependency-injection
        + aurelia-event-aggregator
        + aurelia-history
        + aurelia-logging
        + aurelia-path
        + aurelia-route-recognizer
        + object-assign-polyfill
        + aurelia-router
    `);
```

with this one I can remove the router (last line and process goes away

I just dont see why it adds it...
https://github.com/aurelia/router

**Comment by nchanged** [comment]
Cuz it uses process.env?

**Comment by vegarringdal** [comment]
Looks like its getting tricked by this one from what I can see

![image](https://cloud.githubusercontent.com/assets/2901416/23617628/5d829d10-0296-11e7-890a-545c6c800c53.png)


But again, a way to ban/ decline a module to get added would help, or just the ```-process``` would override the autoimport

**Comment by vegarringdal** [comment]
This can be tagged as a bug now, or ? :-)

**Comment by vegarringdal** [comment]
👍 
Nice

**Comment by vegarringdal** [comment]
@nchanged 

```var isNodeLike = typeof process !== 'undefined' && !process.browser;```

Looks like this still triggers it
https://github.com/aurelia/bootstrapper/blob/master/dist/commonjs/aurelia-bootstrapper.js#L20
https://github.com/aurelia/bootstrapper/blob/master/dist/commonjs/aurelia-bootstrapper.js#L80

When we are not requiring it, it should not be added, should it?
