### ISSUE TITLE
Introducing target ( universal, server, browser )

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#354]
Some cases require targeting.
For example this one https://github.com/fuse-box/fuse-box/issues/258

If we respect `browser` field regardless of targeting, server builds will be broken.

```
target : "universal" | "server" | "browser"  
```

A default is one is `universal` as of now. Setting is to `browser` will allow to properly handle `browser` field in `package.json`

Addition:

`server` builds will ignore browser shims like that [one](https://github.com/fuse-box/fuse-box/tree/master/modules/path) But that comes later.

**Comment by aretecode** [comment]
and `electron` which allows depreciating `.serverBundle`

**Comment by cmseguin** [comment]
@nchanged I don't know if this is the right place for this, but if I bundle my server code __dirname does not return the full dir path, but just the dir name... 

You think this will fix it?

**Comment by nchanged** [comment]
@cmseguin it can't be `fixed`, as there is nothing to fix. Fusebox works with virtual files, therefore does not preserve `__dirname`, it gives your a virtual path e.g `component/myStuff.js`. IF you want to bundle for server, make sure to isolate your dependencies `[index.ts]`
