### ISSUE TITLE
Improve UX of CLI output

### ISSUE THREAD

**Issue by alloy** [fuse-box/fuse-box#356]
For UX reasons, I prefer CLI output to be as silent as possible by default, otherwise it risks a (new) user to miss important output as it gets clouded by noise. Case in point is that multiple of my co-workers have thus far asked at which port the dev-server runs, even though it’s stated right there in the output.

To that end, I would propose the following design (which has worked really well for our users of [CocoaPods](http://github.com/CocoaPods/CocoaPods)):

* By default (which would correspond to a `log: "info"` option), only log files that were actually compiled and the entry point they belong to. Note that I included the full URL of the dev-server in the examples, because some terminals allow users to click links.

  Example:

  ```
  $ node fuse.js 
  🚀 Server launched at http://localhost:4444

  [23:48:21] Built ./assets/reaction-force.js
  └── default (3 files,  6.5 kB)
        index.js
        provider.js
        preview.js
  ```

* When passed the `log: "silent"` option, only log that a file was rebuilt, which is the minimum required output for the user to know that their change has been picked up.

  Example:

  ```
  $ node fuse.js 
  🚀 Server launched at http://localhost:4444

  [23:48:21] Built ./assets/reaction-force.js
  ```

* When passed the `log: "verbose"` option, log all the details as is done currently, which is meant to debug, e.g. check if certain files are indeed cached.

  Example:

  ```
  $ node fuse.js 
  🚀 Server launched at http://localhost:4444

  [23:48:21] Built ./assets/reaction-force.js
  └── default (3 files,  6.5 kB)
        index.js
        provider.js
        preview.js
  └── @kadira/storybook-ui@3.11.0 (0 files) 69.6 kB
  └── babel-runtime@6.22.0 (0 files) 7.2 kB
  └── core-js@2.4.1 (0 files) 48 kB
  └── mantra-core@1.7.0 (0 files) 5.8 kB
  └── react-simple-di@1.2.0 (0 files) 3.2 kB
  └── react@15.4.2 (0 files) 119.6 kB
  └── object-assign@4.1.1 (0 files) 2.2 kB
  └── fbjs@0.8.9 (0 files) 33.3 kB
  └── process@0.0.0 (0 files) 3 kB
  └── object-assign-polyfill@0.0.0 (0 files) 1 kB
  └── hoist-non-react-statics@1.2.0 (0 files) 1.6 kB
  └── react-komposer@1.13.1 (0 files) 20.3 kB
  └── invariant@2.2.2 (0 files) 1.7 kB
  └── shallowequal@0.2.2 (0 files) 1.4 kB
  └── lodash.keys@3.1.2 (0 files) 6.6 kB
  └── lodash._getnative@3.9.1 (0 files) 4 kB
  └── lodash.isarguments@3.1.0 (0 files) 5.8 kB
  └── lodash.isarray@3.0.4 (0 files) 5.2 kB
  └── mobx@2.7.0 (0 files) 106 kB
  └── podda@1.2.2 (0 files) 4.2 kB
  └── immutable@3.8.1 (0 files) 139.3 kB
  └── lodash.pick@4.4.0 (0 files) 13.1 kB
  └── keycode@2.1.8 (0 files) 2.9 kB
  └── events@0.0.0 (0 files) 9.8 kB
  └── react-dom@15.4.2 (0 files) 550.2 kB
  └── @kadira/react-split-pane@1.4.7 (0 files) 22.4 kB
  └── react-komposer@2.0.0 (0 files) 9.4 kB
  └── react-stubber@1.0.0 (0 files) 2.7 kB
  └── fuzzysearch@1.0.3 (0 files) 670 Bytes
  └── lodash.sortby@4.7.0 (0 files) 71.1 kB
  └── react-modal@1.6.5 (0 files) 15.2 kB
  └── exenv@1.2.0 (0 files) 1 kB
  └── lodash.assign@4.2.0 (0 files) 16.5 kB
  └── element-class@0.2.2 (0 files) 1.7 kB
  └── react-fuzzy@0.3.3 (0 files) 7.9 kB
  └── classnames@2.2.5 (0 files) 1.3 kB
  └── fuse.js@2.6.1 (0 files) 23.9 kB
  └── qs@6.3.0 (0 files) 16.4 kB
  └── @kadira/storybook-addons@1.6.1 (0 files) 2.5 kB
  └── @kadira/storybook-channel-postmsg@2.0.1 (0 files) 4.4 kB
  └── @kadira/storybook-channel@1.1.0 (0 files) 4.4 kB
  └── json-stringify-safe@5.0.1 (0 files) 1.1 kB

      Bundle
      Size: 1.3 MB 
      Time: 264ms
  ```

**Comment by stoffeastrom** [comment]
>Case in point is that multiple of my co-workers have thus far asked at which port the dev-server runs, even though it’s stated right there in the output.

Maybe it should be put at the bottom instead?

**Comment by mquandalle** [comment]
For reference, Create-React-App [v2](https://facebook.github.io/react/blog/2017/05/18/whats-new-in-create-react-app.html) has an excellent CLI UX.

**Comment by aretecode** [comment]
@magnushiie this is wip, `filelist` can be filtered out currently

**Comment by nchanged** [comment]
sorry @magnushiie I am sure, @aretecode meant @mquandalle

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
