### ISSUE TITLE
typescript importing types complains 

### ISSUE THREAD

**Issue by vanthiyathevan** [fuse-box/fuse-box#36]
I'm writing a eslint plugin. But having trouble importing types and interface
 when importing typescript interface for plugin, the `tsc` is complains about missing `plugins.d.ts` that can be fixed with empty `index.d.ts` inside `plugins` folder.

**Comment by nchanged** [comment]
A little bit more info please.
Are we missing typings?

**Comment by vanthiyathevan** [comment]
I am not sure if this is because of missing typings. but when I am building [this](https://github.com/vanthiyathevan/fuse-box-plugin-eslint) I get the following error.

`error TS2688: Cannot find type definition file for 'plugins'.`

I added file `index.d.ts` inside the `node_modules/fuse-box/dist/typings/plugins` dir. after that it builds fine.

**Comment by vanthiyathevan** [comment]
Why not publish typings to `@types`?

**Comment by nchanged** [comment]
We are not going for it just yet. Please, read my comment on your PR.
We can discuss that later on gitter.
