### ISSUE TITLE
define cli functionality

### ISSUE THREAD

**Issue by aretecode** [fuse-box/fuse-box#369]
- build files from cli
- flip presets
- use arithmetics 
- show help
- build configs
- parse configs
- auto detect configs

**Comment by DrMabuse23** [comment]
- Build boilerplates React etc...

**Comment by DrMabuse23** [comment]
- Migration informations

**Comment by devmondo** [comment]
lots of community members expressed that we shall keep fuse simple with no CLI, so I think we will close this :)
