### ISSUE TITLE
Typed CSS Modules 

### ISSUE THREAD

**Issue by mohsen1** [fuse-box/fuse-box#37]
I'm interested in using [Typed CSS Modules](https://github.com/Quramy/typed-css-modules) with FuseBox. What's the best way of doing it? I tried making it work with Webpack but there was lots of [issues](https://github.com/olegstepura/typed-css-modules-loader/pull/8)

**Comment by nchanged** [comment]
Anything is possible. FuseBox supports typescript out of the box and works directly with the compiler, therefore any extension can be loaded.

Let us get familiar with the project. 
Cheers

**Comment by nchanged** [comment]
If you feel impatient, you could try taking [this](https://github.com/fuse-box/fuse-box/blob/master/src/plugins/HTMLplugin.ts) as a base and use `file` [api](https://github.com/fuse-box/fuse-box/blob/master/src/File.ts) to obtain info about the source using `file.info` to create a typings file.

Merry Christmas!

**Comment by mohsen1** [comment]
I am not familiar with FuseBox to hack on it yet. I'm curious to see how this is going to work with it since Webpack loader phases completely block loaders from adding new files to the dependency graph

**Comment by nchanged** [comment]
It is possible with fuse, you can add even addtional npm libs to bundle

**Comment by forabi** [comment]
I think I have a better approach. Typed CSS Modules are just one type of imports that need to have type definitions so they can be imported in TypeScript. So what if we **require** that each fuse-box plugin generate those typings for every import automatically. For example a plugin equivalent to Webpack's file loader could generate an `*.d.ts` file which exports a `string`.

**Comment by mohsen1** [comment]
now that TS supports plugins it can be done in a plugin without generating `css.d.ts` files:

https://github.com/HerringtonDarkholme/ts-css-plugin

**Comment by nchanged** [comment]
@mohsen1 @forabi you guys think you could help here?
