### ISSUE TITLE
Code in bundle is not deduplicated.

### ISSUE THREAD

**Issue by cseufert** [fuse-box/fuse-box#371]
I have an example if this here:
https://github.com/cseufert/fp-bundle-dup-test/tree/master

Fuse-box is not looking in the bundles, just bindly re-packaging them.

**Comment by nchanged** [comment]
Hm, it does exactly what you ask it to do.
If you want to remove duplicates, you need to do:
```
bundle("-alpha")
bundle("-beta") 
```
to self exclude it.
Your instructions are isolated, therefore fuse has nothing to do with your code, it's they way you bundle it. 

There is one thing also tho, you are missing `homeDir`

Please, read up [here](http://fuse-box.org/#arithmetic-instructions) and [here](http://fuse-box.org/#home-directory)
