### ISSUE TITLE
fuse-box eslint-loader

### ISSUE THREAD

**Issue by PodaruDragos** [fuse-box/fuse-box#374]
I can't seem to be able to configure the plugin to actually throw errors in the console. it always compile.

**Comment by aretecode** [comment]
@PodaruDragos seems like an issue for https://github.com/DoumanAsh/fuse-box-eslint-plugin
if you want to throw errors, you'll need to throw them.

**Comment by devmondo** [comment]
Will close this for now. Let us know if this is still an issue :)
