### ISSUE TITLE
Only first plugin that matches Plugin.test regex is used

### ISSUE THREAD

**Issue by cseufert** [fuse-box/fuse-box#378]
I am tring to use 2 plugins that both work in js files, howver only the first one is ever being applied.

See:
https://github.com/fuse-box/fuse-box/blob/master/src/core/File.ts#L208
and
https://github.com/fuse-box/fuse-box/blob/master/src/core/File.ts#L226

It just finds the first match, once found, stop looking for more plugins, btw that whole section of code seems rather complicated. I will have a go at making a fix for it, but i am a little concerned that this is by design.

**Comment by nchanged** [comment]
That is by design. Yes

**Comment by cseufert** [comment]
I guess ill just write a plugin that lets you run multiple plugins...
