### ISSUE TITLE
Isomorphic HMR with React

### ISSUE THREAD

**Issue by mattoni** [fuse-box/fuse-box#384]
Is there an example somewhere that shows how to use fusebox with an isomorphic react app? I'd love to switch over from webpack, but having trouble finding a good isomorphic sample.

Thanks!

**Comment by devmondo** [comment]
@mattoni 
our HMR is fully express server, so you can hack into it however you like :)
also these might help
https://github.com/fuse-box/fuse-box-express-seed
https://github.com/fuse-box/react-example
https://github.com/fuse-box/fuse-box-ts-react-reflux-seed

this article about how to customize HMR 
https://medium.com/@basarat/rethinking-hot-module-reloading-58ce15b5f496#.cquql38hr

**Comment by mattoni** [comment]
Thanks, @basarat 's article is what led me to fuse-box in the first place. I think it would be really great if there was an official example with SSR, since it's a huge topic these days :)

**Comment by devmondo** [comment]
@mattoni good idea! do you want to PR something :)

**Comment by mattoni** [comment]
I would, I'm a bit tight on time so if somebody could knock it out faster that might be better, but I'll see if I can get to it. Is it alright to be a bit opinionated on it? My favorite stack is Typescript + MobX + React (+ Fuse-box now ;) )

**Comment by mattoni** [comment]
I'm working on a repo for this right now. Ran into an issue though, I'm unable to use the paths set up in my tsconfig.json file. For example, in the server file, I import a component with 
`import { Html } from "containers/Html";`

But it is not pulled into the bundle, and the server crashes saying the module wasn't found. 
Changing it to relative paths:
`import { Html } from "../containers/Html";`

Works (until it hits another non-relative import). How can I get it to import properly so I don't have to use relative paths everywhere?

Repo here:
https://github.com/mattoni/fusemob-ssr

Thanks for the help.

**Comment by nchanged** [comment]
@mattoni at the moment `tsconfig.json` does not affect paths. You can use alias as of now 
http://fuse-box.org/#alias

But it would be a great improvement to have.

**Comment by nchanged** [comment]
@mattoni closing this for now =) Clean up before the release.
