### ISSUE TITLE
Resolving relative typescript paths not working

### ISSUE THREAD

**Issue by mattoni** [fuse-box/fuse-box#385]
I'm working on a UI library, where the components exist in ./src, but the docs exist in ./docs. In the docs, I'm building a view based on the components in ./src for demos. 

In ./docs/App.tsx, I want to import a component in src, ../src/Component.tsx. When bundled with fuse-box, I get `App.tsx:12 ../src/Component not found on request`. It looks like it resolves a full path name, but keeps the relative path name in the bundle (../src/Component.tsx).

Is there a way to make this scenario work? I don't want to adjust the base path in the tsconfig, since it resolves everything just fine.

Thanks in advance.

**Comment by nchanged** [comment]
It's quite easy, change your homDir (in fusebox you seen locked in there)

**Comment by mattoni** [comment]
If I change my home directory to the /src folder, then the files structuring the docs in the /docs folder won't be tracked for changes and recompile. How can I get it to watch changes in both folders and resolve them correctly?

Thanks!

**Comment by nchanged** [comment]
You can't talk to 2 different source folders, fusebox won't allow that, cuz it works with a virtual structure which requires a homeFolder as a base.

**Comment by devmondo** [comment]
@mattoni you could use `modulesFolder` or `bundle.register`, maybe create a sparky task to bundle your `src` first to a shared folder then use this output in your `docs` folder?

**Comment by mattoni** [comment]
I ended up getting it working, and with HMR support too. 

```
Sparky.task('bundle', () => {
    const fuse = FuseBox.init({
        homeDir: '.',
        output: 'docs-build/bundle.js',
        hash: isProd,
        cache: !isProd,
        plugins: [
            EnvPlugin({ NODE_ENV: process.argv[2] }),
            isProd && UglifyJSPlugin(),
        ],
        sourceMaps: { project: true, vendor: true },
    });

    fuse.dev({
        port: 3000,
        root: 'docs-build',
    });

    const bundle = fuse.bundle('bundle.js')
        .instructions('> docs/index.tsx');

    if (!isProd) {
        bundle
            .hmr()
            .watch('(src/**|docs/**)');
    }

    fuse.run();
});
```

And then npm publish just runs `tsc` and outputs it since it's meant to be imported as a lib.

**Comment by devmondo** [comment]
@mattoni as usual, you are da playa with Fuse ;)
