### ISSUE TITLE
Regression in 1.3.124, cannot bundle axios

### ISSUE THREAD

**Issue by geowarin** [fuse-box/fuse-box#387]
Hello !

Since the upgrade to 1.3.124, I can no longer bundle axios and uglify it.
It seems related to the JSONLoader trying to load bogus files.

I have a repro [here](https://github.com/geowarin/repro-fuse).

**Comment by nchanged** [comment]
@geowarin hm.... and which version did it without problems?

**Comment by geowarin** [comment]
1.3.123, it's in the repro README

**Comment by nchanged** [comment]
Sorry, I will check it, there seems to be another bug with custom versions ...

**Comment by nchanged** [comment]
I am really sorry about it. A very bad thing happened to Buffer
![screenshot 2017-03-11 23 44 14](https://cloud.githubusercontent.com/assets/1629088/23827481/af4a7d62-06b4-11e7-8806-a7e8a236b432.png)

I will revert it now, and we will release a hot fix really soon.

**Comment by aretecode** [comment]
If that was the bug, why isn't this issue closed? I don't see what is invalid with the buffer change you have in your screenshot.

**Comment by nchanged** [comment]
Coming with 1.3.127

**Comment by nchanged** [comment]
https://github.com/fuse-box/fuse-box/milestone/16?closed=1

**Comment by geowarin** [comment]
Don't be sorry @nchanged. Fusebox is great.
 Thanks for your awesome work and for the quick fix!
