### ISSUE TITLE
"Acorn error" with MapboxGL

### ISSUE THREAD

**Issue by ugogo** [fuse-box/fuse-box#388]
Hi, I'm getting an "Acorn error" while trying to bundle my app with MapboxGL

In my `.jsx` file

```js
import mapboxgl from "mapbox-gl/dist/mapbox-gl";
```

---

```bash
$ rm -rf node_modules .fusebox
$ yarn install && node fuse.js
```

![capture d ecran 2017-03-11 20 29 22](https://cloud.githubusercontent.com/assets/5040476/23826269/7ab489dc-0699-11e7-9887-3d338664e193.png)

**Comment by nchanged** [comment]
hi! It's not a valid JavaScript your are bundling there. You need to use typescript if you want to use typings (like in your case)

**Comment by ugogo** [comment]
Hey, the `mapbox-gl/dist/mapbox-gl` file i'm importing, is a `.js` file.
The point is, it works fine with webpack 😕

**Comment by nchanged** [comment]
Then when am seeing an invalid JavaScript code you are bundling?

**Comment by ugogo** [comment]
I only followed the Mapbox's instructions, so I don't think I'm missing something? (am I?)

![capture d ecran 2017-03-12 10 21 32](https://cloud.githubusercontent.com/assets/5040476/23830551/bc39c268-070d-11e7-874f-3185923006eb.png)

Here is my `fuse.js`

```
const { FuseBox, JSONPlugin, CSSPlugin, SVGPlugin, SassPlugin, BabelPlugin } = require("fuse-box");

const fuse = new FuseBox({
  homeDir: "src/",
  sourcemaps: true,
  outFile: "./build/app.js",
  plugins: [
    SVGPlugin(),
    [SassPlugin({ outputStyle: "compressed" }), CSSPlugin()],
    BabelPlugin(),
    JSONPlugin(),
  ],
});

fuse.devServer(">index.jsx");
```

I also tried with the `TypeScriptHelpers`, same issue.

Am I missing something?

**Comment by devmondo** [comment]
@ugogo  you are importing the source file wich uses` flow` for typing. it is not your problem, it is the library vendor issue to have npm package pointing to none transpiled files :(

to solve this, you need to add `flow` plugins to babel https://babeljs.io/docs/plugins/syntax-flow/
also you need to use our option `limit2project: true` so we can tell fuse to force babel plugin to transpile `npm_modules` files. check full config here http://fuse-box.org/#full-config

hope this helps

**Comment by ugogo** [comment]
@devmondo What I don't understand is: how does Webpack? Even with a basic configuration, it works.

Using the `limit2project` option make the whole compilation really slow.

Thanks for your help anyway,
I'd love to use fuse-box on this new project.
Maybe next time.

Otherwise, without this issue everything works really fine, keep up with the great work 💪

**Comment by nchanged** [comment]
You should use cache to make it fast :) and I have not checked this issue out. Will do later if you still interested

**Comment by ugogo** [comment]
Sure, sure, I thought you gave up 😛 
I let you reopen the issue when you start working on it.
Let me know if I can help you in any way

**Comment by nchanged** [comment]
Sorry, did not read the whole thread through.

like @devmondo said -  it's not related to FuseBox. A distribution must not contain non-transpiled code, or even worse - rely on webpack configuration. Unfortunately, I cannot help here.

**Comment by ugogo** [comment]
I'm not saying this package rely on a webpack configuration, I'm only saying that I already use this package with a basic webpack configuration

**Comment by devmondo** [comment]
@ugogo can you share your webpack configuration

**Comment by ugogo** [comment]
@devmondo, sure.

You can try with [create-react-app](https://github.com/facebookincubator/create-react-app) or 

```js
var HtmlWebpackPlugin = require('html-webpack-plugin');
var CaseSensitivePathsPlugin = require('case-sensitive-paths-webpack-plugin');
var paths = require('./paths');

module.exports = {
  devtool: 'cheap-module-source-map',
  entry: [
    paths.appIndexJs
  ],
  output: {
    path: paths.appBuild,
    pathinfo: true,
    filename: 'static/js/bundle.js',
    publicPath: '/'
  },
  resolve: {
    fallback: paths.nodePaths,
    extensions: ['.js', '.json', '.jsx', '']
  },

  module: {
    loaders: [{
      exclude: [
        /\.html$/,
        /\.(js|jsx)(\?.*)?$/,
        /\.json$/
      ],
      loader: 'url',
      query: {
        limit: 10000,
        name: 'static/media/[name].[hash:8].[ext]'
      }
    }, {
      test: /\.(js|jsx)$/,
      include: paths.appSrc,
      loader: 'babel'
    }, {
      test: /\.json$/,
      loader: 'json'
    }
    ]
  },
  plugins: [
    new HtmlWebpackPlugin({
      inject: true,
      template: paths.appHtml,
    }),
    new CaseSensitivePathsPlugin()
  ],
  node: {
    fs: 'empty',
    net: 'empty',
    tls: 'empty'
  }
};
```

**Comment by devmondo** [comment]
@ugogo thanks, 
well if not wrong, the way webpack loader config you have here includes `npm_modules` folder by default.
```js
 {
      test: /\.(js|jsx)$/,
      include: paths.appSrc,
      loader: 'babel'
    }
```

but this slows things down, from their docs :
 ```Modify webpack.config.js to process all .js files using babel-loader.

 module.exports = {
     entry: './src/app.js',
     output: {
         path: './bin',
         filename: 'app.bundle.js',
     },
     module: {
         loaders: [{
             test: /\.js$/,
             exclude: /node_modules/,
             loader: 'babel-loader'
         }]
     }
 }
We are excluding node_modules here because otherwise all external libraries will also go through Babel, slowing down compilation.
```

that is why we don't enable it by default, but if you disable `limit2project` and enable caching, you would get what you want :)

**Comment by ugogo** [comment]
Thanks @devmondo, looks good

**Comment by devmondo** [comment]
@ugogo awesome man :)
