### ISSUE TITLE
Sourcemaps errors while compiling scss files form node_modules

### ISSUE THREAD

**Issue by cesaraaron** [fuse-box/fuse-box#389]
config:
```
const { FuseBox, SassPlugin, CSSPlugin } = require('fuse-box')

const fusebox = FuseBox.init({
  homeDir: './',
  outFile: './dist/index.js',
  plugins: [
    [
      SassPlugin(),
      CSSPlugin({ outFile: (name) => 'styles/style.css' })
    ],
  ],
})
fusebox.bundle('>index.scss')
```
index.scss:
```@import 'node_modules/foundation/scss/foundation';```

Log:
> Error: No element indexed by 3
>     at ArraySet_at [as at] (/mnt/c/Users/cesaraaron/Desktop/scss/node_modules/source-map/lib/array-set.js:92:9)
>     at BasicSourceMapConsumer.<anonymous> (/mnt/c/Users/cesaraaron/Desktop/scss/node_modules/source-map/lib/source-map-consumer.js:143:67)
>     at Array.map (native)
>     at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (/mnt/c/Users/cesaraaron/Desktop/scss/node_modules/source-map/lib/source-map-consumer.js:142:14)
>     at Concat.add (/mnt/c/Users/cesaraaron/Desktop/scss/node_modules/concat-with-sourcemaps/index.js:58:18)
>     at group.subFiles.forEach.file (/mnt/c/Users/cesaraaron/Desktop/scss/node_modules/fuse-box/dist/commonjs/plugins/stylesheet/CSSplugin.js:53:20)
>     at Array.forEach (native)
>     at CSSPluginClass.transformGroup (/mnt/c/Users/cesaraaron/Desktop/scss/node_modules/fuse-box/dist/commonjs/plugins/stylesheet/CSSplugin.js:51:24)
>     at promises.push.Promise (/mnt/c/Users/cesaraaron/Desktop/scss/node_modules/fuse-box/dist/commonjs/core/ModuleCollection.js:122:59)
>     at context.fileGroups.forEach (/mnt/c/Users/cesaraaron/Desktop/scss/node_modules/fuse-box/dist/commonjs/core/ModuleCollection.js:121:35)
> Error: No element indexed by 3
>     at ArraySet_at [as at] (/mnt/c/Users/cesaraaron/Desktop/scss/node_modules/source-map/lib/array-set.js:92:9)
>     at BasicSourceMapConsumer.<anonymous> (/mnt/c/Users/cesaraaron/Desktop/scss/node_modules/source-map/lib/source-map-consumer.js:143:67)
>     at Array.map (native)
>     at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (/mnt/c/Users/cesaraaron/Desktop/scss/node_modules/source-map/lib/source-map-consumer.js:142:14)
>     at Concat.add (/mnt/c/Users/cesaraaron/Desktop/scss/node_modules/concat-with-sourcemaps/index.js:58:18)
>     at BundleSource.addFile (/mnt/c/Users/cesaraaron/Desktop/scss/node_modules/fuse-box/dist/commonjs/BundleSource.js:61:31)
>     at files.forEach.f (/mnt/c/Users/cesaraaron/Desktop/scss/node_modules/fuse-box/dist/commonjs/CollectionSource.js:18:33)
>     at Array.forEach (native)
>     at CollectionSource.get (/mnt/c/Users/cesaraaron/Desktop/scss/node_modules/fuse-box/dist/commonjs/CollectionSource.js:17:15)
>     at Object.addDefaultContents (/mnt/c/Users/cesaraaron/Desktop/scss/node_modules/fuse-box/dist/commonjs/core/FuseBox.js:204:50)

When change the config of `CSSPlugin({ outFile: (file) => './dist/style.css' })` :

> Error: Invalid mapping: {"generated":{"line":98,"column":6},"source":"node_modules/foundation/scss/foundation/components/_global.scss","original":{"line":121,"column":-5},"name":null}
>     at SourceMapGenerator_validateMapping [as _validateMapping] (/mnt/c/Users/cesaraaron/Desktop/scss/node_modules/source-map/lib/source-map-generator.js:277:13)
>     at SourceMapGenerator_addMapping [as addMapping] (/mnt/c/Users/cesaraaron/Desktop/scss/node_modules/source-map/lib/source-map-generator.js:101:12)
>     at /mnt/c/Users/cesaraaron/Desktop/scss/node_modules/concat-with-sourcemaps/index.js:60:28
>     at Array.forEach (native)
>     at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (/mnt/c/Users/cesaraaron/Desktop/scss/node_modules/source-map/lib/source-map-consumer.js:155:14)
>     at Concat.add (/mnt/c/Users/cesaraaron/Desktop/scss/node_modules/concat-with-sourcemaps/index.js:58:18)
>     at BundleSource.addFile (/mnt/c/Users/cesaraaron/Desktop/scss/node_modules/fuse-box/dist/commonjs/BundleSource.js:61:31)
>     at files.forEach.f (/mnt/c/Users/cesaraaron/Desktop/scss/node_modules/fuse-box/dist/commonjs/CollectionSource.js:18:33)
>     at Array.forEach (native)
>     at CollectionSource.get (/mnt/c/Users/cesaraaron/Desktop/scss/node_modules/fuse-box/dist/commonjs/CollectionSource.js:17:15)

windows10.
node: v7.4.0.
fuse-box: 1.3.126

**Comment by devmondo** [comment]
This is fixed now, let us know otherwise.
