### ISSUE TITLE
convert tests from mocha to fuse-box-test-runner

### ISSUE THREAD

**Issue by aretecode** [fuse-box/fuse-box#391]
mocha tests use outdated `createEnv` and should be ported to ts, and use `fuse-box-test-runner`

**Comment by orta** [comment]
Jest works really well with TypeScript (and then you can also use [vscode-jest](https://github.com/orta/vscode-jest#readme) ) - would recommend that, if you can

**Comment by aretecode** [comment]
as does https://github.com/avajs/ava
