### ISSUE TITLE
Can I force a bundle to include a file?

### ISSUE THREAD

**Issue by Thanood** [fuse-box/fuse-box#393]
I'm trying to bundle Google's MDL with FuseBox.

Here's my configuration:

```js
const fb = require('fuse-box');
const FuseBox = fb.FuseBox;

const appPackages = `
    > main.ts 
    + **/*.ts                   
    + **/*.html
    + **/*.css
    + material-design-lite
    + material-design-lite/dist/material.css
    + material-design-lite/dist/material.indigo-pink.min.css
`;

const appBundle = FuseBox.init({
    homeDir: './src',
    outFile: './dist/app-bundle.js',
    cache: false,
    log: true,
    debug: false,
    sourceMaps: { vendor: false, project: true },
    plugins: [
        fb.CSSPlugin(),
        fb.HTMLPlugin({ default: true }),
        fb.TypeScriptHelpers()
    ]
});

appBundle.devServer(appPackages, { root: './', port: 4444 });
```

If I *don't* `import` any of the css files, only `material-design-lite/dist/material.js` is bundled. No CSS files.
If I *do* `import 'material-design-lite/dist/material.css';` the css file is bundled, too.

I guess this is a good thing. 😃 

Now, I'd like to use (something like) this with Aurelia, which can import css with a custom element `<require>` instead of using `import`. To do this, I think I'd need to tell FuseBox "include that file, regardless of what I'm doing". Is that possible? Did I miss it in the docs?

Now, what I'd really like to do is to bundle an app using [aurelia-materialize-bridge](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge) which has a lot of html and css files that would need to be included in the bundle.

The only workaround for that seems to be to create a separate bundle for that library but then I have the same problem with Materialize and its css file (I can't include `materialize.css`).
So I've tried to recreate the issue with a smaller library which would be easier to test, thus the hint to bundling MDL. 😃

**Comment by vegarringdal** [comment]
for the bridge it sounds like #170 ive been trying to fight for would help :-)
Atm you will be able to create own package like I do with my grid, so thats kinda a workaround.
I managed to use modulefolder to include my grid to, but to get it to work like expected I had to first import the module so it loaded the resources and overwrites the package/module like loading the bundle in index.html would have done.
easiest fix/features for this sounds like a way to include/concat bundles (with sources maps if possible) but guess loading a seperate bundle during development isnt the worst thing to do.

**Comment by Thanood** [comment]
@vegarringdal I'm aware of the workaround but where does that end? Maybe I'd also like to add dragula, flatpickr, toastr, v-grid, any-other-lib-that-provides-css.. 😃 

But I can see that `addPackage()` would help there.

Btw. I've noticed just now if I omit the css files from bundle declaration like this:

```js
const appPackages = `
    > main.ts 
    + **/*.ts                   
    + **/*.html
    + **/*.css
    + material-design-lite
`;
```

But import the MDL css file: `import 'material-design-lite/dist/material.css';`, it is included in the bundle.

```
$ node build/build-app.js
07:15:56 : Launching dev server on port 4444
  → Typescript config file was not found. Improvising
└── default (1 files,  2.8 kB)
      main.js
└── material-design-lite (2 files) 422.8 kB

    Bundle
    Size: 425.6 kB
    Time: 1s 48ms
07:15:57 : HMR is disabled. Caching should be enabled and {hmr} option should be NOT false
```

So the line `+ material-design-lite/dist/material.css` doesn't have any effect, right?
If it's like that (and not a cool bug), maybe it could as well be treated as "include this file regardless of what I do".

**Comment by vegarringdal** [comment]
Hopefully @nchanged @devmondo have a plan to improve this part.
If its with ```fuse.addPackage(/*something*/)``` or some ```fuse.defineModuleResources(/*something*/)``` or ```fuse.addAndImportBundle(/*path to bundle*/)```

**Comment by devmondo** [comment]
@vegarringdal yes we will :)

**Comment by Thanood** [comment]
I wonder what this line is supposed to do:

```
+ material-design-lite/dist/material.css
```

It doesn't seem to have any effect. 😃 
If this works as intended I just thought maybe this could be a way to "force" the file into the bundle.

**Comment by Thanood** [comment]
Btw: this is working with `"fsbx": "^1.4.1-preview.6",` ✨

**Comment by vegarringdal** [comment]
yay :-)

**Comment by devmondo** [comment]
awesome 👍

**Comment by nchanged** [comment]
Closing this for now. Please feel free to check the latest bleeding edge version `fuse-box@2.0.0-beta.8`
and documentation for it http://fuse-box.org:3333. You are welcome to re-open it elsewise ;-)
