### ISSUE TITLE
Uncapitalize plugins

### ISSUE THREAD

**Issue by cmseguin** [fuse-box/fuse-box#394]
I know this can be a very personal question, but is there a reason why all the plugins are capitalized?

I personally use eslint, and I always heard that best practice is to only capitalize for constructor functions.

You can see the eslint rule here: http://eslint.org/docs/rules/new-cap

**Comment by devmondo** [comment]
@cmseguin usually Class Names are Capitalized in ES6, specially coming from c# :)

**Comment by cmseguin** [comment]
That's what I meant by "constructor functions" hehe.

I completely agree that the plugin itself be capitalized,
but here you are exporting the instances of the class:
https://github.com/fuse-box/fuse-box/blob/master/src/index.ts

Should the instance of the class be uncapitalized?

**Comment by devmondo** [comment]
@cmseguin good catch :)
@nchanged should we keep this or not

**Comment by cmseguin** [comment]
@devmondo @nchanged It's not a dealbreaker, but I find it quite annoying to have to turn off my eslint for the fuse file :P I can't be the only one in this situation hehe :)

**Comment by aretecode** [comment]
maybe a happy medium is export both cammelCase and ClassCase :3?

**Comment by cellog** [comment]
Users coming from webpack will find the current code standard more intuitive.  You can add a per-file rule in 1 line that turns off only that eslint rule for that file:

```js
/* eslint new-cap: 0 */
```

or if you're afraid of missing something else:

```js
/*eslint new-cap: ["error", { "capIsNewExceptions": ["CSSPlugin"] }]*/
```

and so on.

**Comment by cmseguin** [comment]
It would for sure break a lot of code to make such a change...

however, look at the following: 
https://webpack.js.org/concepts/plugins/

The plugins in webpack seems to be classes... I personally don't think it's a good idea to use capitalized plugins just because it would be easier for the people coming from webpack. Fusebox is quite different from webpack anyway.

Perhaps @aretecode's suggestion would work and we could deprecate the capitalized version to ease the transition for the people already using the current version & also for the people coming from webpack.

**Comment by nchanged** [comment]
Not changing it anytime soon, it has been established for a very long time.
Also, check the upcoming version `fuse-box@2.0.0-beta.8`
here http://fuse-box.org:3333/
