### ISSUE TITLE
Is there an event for when a bundling has completed?

### ISSUE THREAD

**Issue by cmseguin** [fuse-box/fuse-box#395]
I personally would like to manage processes once everything is done bundling.

Is there a way to do that? I looked at the documentation quite a bit, and could not find anything..

Thanks :)

**Comment by devmondo** [comment]
@cmseguin yea the bundle command returns a promise so you can use `then`, but it also takes  a second param as callback, where you guarantee the file is written.

**Comment by cmseguin** [comment]
Cool perfect thanks! :)
