### ISSUE TITLE
Globs in require mentions

### ISSUE THREAD

**Issue by vtabary** [fuse-box/fuse-box#398]
Hi all,

I was wondering if it was possible to use globs in the ```require``` or ```Fusebox.import``` in order to dynamically import specs in a bundle.

Today, using webpack, I'm using the "magic" ```require.context``` to import all the *.spec.ts files. But since fuxebox can manage some specific paths like ```~```, is it possible to use something like in my main.ts file :
```
require('~/lib/**/*.spec.ts')
```
Or 
```
Fusebox.import('~/lib/**/*.spec.ts')
```

I tried to bundle them by writing :
```
fuse.bundle('>tests/main.ts lib/**/*.spec.ts');
```

It worked, but, of course, there are not used, only bundled. So the file main.ts, which my entry point, won't know them.

Is something like this planned ? Or maybe do you have some other suggestions ?

By the way, many thanks for this awesome project !

**Comment by nchanged** [comment]
Hi @vtabary ! 
It's all [Wildcard imports](http://fuse-box.org/#wildcard-import)

**Comment by vtabary** [comment]
Yep, I tried it too, but it seems to do nothing but it doesn't seem to be recursive.

Here is the log with require('~/lib/common/**/*.spec.ts'):
```
  → Typescript config:  /tsconfig.json
└── default (5 files,  1.3 kB)
      tests/browser/main.js
      lib/common/**/*.spec.js
```

When I use ```Fusebox.import('~/lib/common/**/*.spec.ts')```, the bundle doesn't import all my spec.ts files. So I added them to the bundle configuration : 
```
fuse.bundle('>tests/browser/main.ts lib/**/*.spec.ts');
```

But the specs files are still not executed.

Maybe it's related to my project. I'll try to create a sample project tomorrow and I'll add the link to the repository to this thread.

**Comment by devmondo** [comment]
@vtabary , when using wildcard imports or dynamic modules, you have to bundle those files :)

**Comment by nchanged** [comment]
I believe you can't use `require` and wildcard imports. You need to use `FuseBox.import`
And bundle them like so: `fuse.bundle('>tests/main.ts +lib/**/*.spec.ts');`

If you notice it's a wildcard, not a glob, so use only one `*`

**Comment by vtabary** [comment]
I made a sample repository. 

You can find it here https://github.com/vtabary/sample-fusebox 

By requiring the files one by one, it's working.

By using require('./**/*.spec'), or FuseBox.import('./**/*.spec.js'), it's not.

I tried with ou without extension, and with or without explicitly bundling the files.

I don't see how to use it in an other way. 

Could you help me on this ? 

Thanks

**Comment by vtabary** [comment]
I made a sample repository, and inserted your last remarks

You can find it here https://github.com/vtabary/sample-fusebox 

By requiring the files one by one, it's working.

By using ```require('./lib/*')```, it doesn't seem to be supported because the log shows that is trying to load a file named ```*``` :

```
  → Typescript config file was not found. Improvising
└── default (4 files,  685 Bytes)
      main.js
      lib/*.js
      lib/a/a.spec.js
      lib/b/b.spec.js
```

By using ```FuseBox.import('./lib/*')``` and bundling explicitly the files, it's not working either.

I don't see how to use it in an other way. 

Could you help me on this ? 

Thanks

**Comment by nchanged** [comment]
@vtabary 
```
const files = FuseBox.import('./lib/*/*.spec');
```
This one gives want you want. And there is a room for improvement here https://github.com/fuse-box/fuse-box/issues/401

**Comment by vtabary** [comment]
Great !

Thanks a lot for your help. 

I updated my repository if someone has the same problem.

**Comment by vtabary** [comment]
An update : 

In fact, the wildcard is not recursive.

If I add a file in a subdirectory, it won't be imported. I have to specify an import with a wildcard for each level like:
```
FuseBox.import('./lib/*/*.spec');
FuseBox.import('./lib/*/*/*.spec');
```

Look at my branch subdirectory : https://github.com/vtabary/sample-fusebox/tree/subdirectory

So it's a workaround, but not really easy to use.

**Comment by nchanged** [comment]
@vtabary #401  =)

**Comment by vtabary** [comment]
Yep, saw that before :p

My comment was only here to add some information. 

Love the #401 ;)
