### ISSUE TITLE
1.4.1 Specs - BREAKING CHANGES

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#400]
Let's summarise! 
With the help of #382 

## outFile will become `output`  
#349 
```js
FuseBox.init({
   	output : "dist/$name.js"
})
```

or:

```
{ output : "dist/$name-$hash.js" }
```

Cache busting #350 is achieved by setting

#### Automatically pick md5 alg
```js
{ hash : true }
```

#### Pick a predefined algorithm

```js
{ hash : 'md5' }
```

#### Use your own algorithm

```js
{ hash : (context) => context.source.length }
```

## Api structure

First of all, `bundle` will no longer execute instruction but accept a bundle name. These
changes are required because we are changing the `output` and want to solve multibundle problems

### Simple example
```js
const fuse = FuseBox.init({
   	output : "dist/$name.js"
});

fuse
  .bundle("app")
  .exec("~ index.ts");

fuse
   .bundle("vendor")
   .exec("~ index.ts");

```

Whereas `fuse` is a bundle factory, which clones your settings.

### DevServer

`devServer` will no longer accept instructions, options instead

```
fuse.devServer({
	bundle : "app",
	root : "./"
})
```

Whereas `bundle` is a bundle name which will send HMR events to the client. We could possibly pick the first one automatically.

### Watching

It will be possible to watch bundles separately

```js
fuse
	.bundle("app1")
	.watch("app1/*")
	.exec("[app1/**/*.ts]");

fuse
	.bundle("app2")
	.watch("app2/*")
	.exec("[app2/**/*.ts]");
```

FuseBox will have only one watcher instantiated. The factory will be aware of the amount of bundles in the scope, therefore it will be possible to define Regular Expressions to match changed files and react accordingly

```js
fuse.watch(/lib\/.*/)
```

Or a simplified RegExp

```js
fuse.watch("lib/*")
```

### Resolve bundle state

And of course in order to ensure your bundle state

**In memory**

```js
fuse
  .watch("lib/*")
  .exec("> index.ts", (context) => {
       // Bundle is in memory but not written yet
   })
```

**Written to disk**
```js
fuse
  .watch("lib/*")
  .exec("> index.ts")..then( context => {
    // Bundle is written to disk (cycle complete)
  })
```

### Register packages

Like `modulesFolder` it should be possible to customise package. For example I want to mock a library `foo` that has 2 css files, it would do the following

```
fuse.
   register("foo", {
   	  root 	: "custom/foo/",
   	  main 	: "index.js" // by default, does not need to be specified
   	  include : ["css/*"]
   })
```

In order to have it bundle you either require it your code
```
require("foo")
```

Or add to arithmetics
```
exec("> index.ts +foo")
```
A custom package `foo` will have the highest priority. Therefore is will come on top of `node_modules` module resolution.

Whereas `include` is a list that contains simplified RegExp expressions. `root` is important here, cuz it will be matched accordingly.

I was thinking of adding arithmetics here, but they are not really required here. Correct me if I am wrong.

### Simplified RegExp improvements

`**` should match slashes as well. This will be introduced before `1.4.1`
For example  `**.(html|css)` will match files in all folders

---

Your input is very important!! If there is something misssing of unclear, let's make it clear and update the spec.

**Comment by cellog** [comment]
Why "watch?"

Is this referring to files watched for changes for hmr or something else?

**Comment by mattoni** [comment]
are we able to return a promise for when the bundle is complete? An `await`able flow would be preferred for those of us doing multiple builds.

**Comment by nchanged** [comment]
@cellog to re-bundle.
@mattoni absolutely!! Updated it

**Comment by nchanged** [comment]
@cellog for example, you are making a server bundle and you re-build on file change.

**Comment by arabsight** [comment]
@nchanged can we use fuse.register with node packages, like if I want to override the main entry of a package (some packages' main points to a source file rather then a dist one, others are amd or whatever) something like:

```js
fuse.register("mapbox-gl", {
   	  root : "node_modules/mapbox-gl",
   	  main : "dist/mapbox-gl.js"
   });
```
 will *include* accept globs, some aurelia plugins contains a lot of files spread over many directories and using this: **/*.{html,css} is easy to get them all.

**Comment by nchanged** [comment]
@arabsight I think this instruction will override Fuse initial node_module resolve strategy once `mapbox-gl` is seen. So yes, we can even treat these properties as an override for `package.json`

**Comment by nchanged** [comment]
@arabsight and think we can introduce a simplified regexp with two `**` like  `**.(html|css) ` that will include `/ symbol`

**Comment by arabsight** [comment]
perfect, thanks.

**Comment by nchanged** [comment]
@arabsight I have added it to the spec.

**Comment by cellog** [comment]
Why note use "files" instead of watch?

**Comment by nchanged** [comment]
@cellog sorry, i did not get you.

**Comment by cellog** [comment]
Sorry :) 

fuse.watch('lib/')

This is telling fuse to look in 'lib/' for the files to bundle, and to watch for changes to those files, right? For a user new to fuse, "watch"  may be less intuitive than "files" for this.

**Comment by nchanged** [comment]
@cellog I think watch allows you to re-bundle. For example, you would not want to watch when you bundle for production right? `Files` can be misleading, as we keep the arithmetics. So `watch` should tell fuse when it's needed to kick in the process again. And most certainly, you would like to limit it by providing a mask.

**Comment by cellog** [comment]
So would it be fair to say that for many projects, fuse.watch() would be enough? And that watch() is a feature for development only? I ask because this can be clarified, since both watch and exec accept paths

**Comment by nchanged** [comment]
Absolutely! Except exec does not really accept paths, it accepts instructions. And yes, this should be clarified. Omg, so much of documentation is ahead! I hope you could help out on this.

**Comment by devmondo** [comment]
@/all please have as much input as possible, these changes we going to introduce are crucial, so say your word before we hit the lab for good :)

**Comment by leon-andria** [comment]
It should be to highlight all options from the init.
Because it's so confusing when we have root and homeDir. Personally, i prefer root.
Also, how about settings from init that be overrided during the bundle factory process? I need to specify another root or additional plugin settings,...
Does the watcher can be defined in the init? To avoid to define on each bundle process.
The option main could be named entry for the entry point.
The register package, the second params should look like the init or inherits from it. And rather than to have include, i would prefer to exec to keep consistency with the bundle. The rule of thumb is having similar signature so it's helping for better documentation.

**Comment by cellog** [comment]
I would love to help with docs on this. In fact the questions I'm asking are with that in mind. 

I'd like to see examples of bundling using the new API that show bundling a simple app with js, css, html. Another showing making a npm module. Another with hmr, another with a server bundle, all using the new API. That should help clarify what the things do for docs

**Comment by nchanged** [comment]
@leon-andria i agree, we will discuss it later, when i get to it.

**Comment by nchanged** [comment]
@cellog still want to help with the docs? =)
