### ISSUE TITLE
New bundle API

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#402]
First of all, `bundle` will no longer execute instruction but accept a bundle name. These
changes are required because we are changing the `output` and want to solve multi-bundle problems

### Simple example
```js
const fuse = FuseBox.init({
   	output : "dist/$name.js"
});

fuse
  .bundle("app")
  .exec("~ index.ts");

fuse
   .bundle("vendor")
   .exec("~ index.ts");

```

Whereas `fuse` is a bundle factory, which clones your settings.

**Comment by nchanged** [comment]
https://github.com/fuse-box/fuse-box/issues/400

**Comment by aretecode** [comment]
Big ups, this is the right direction! https://github.com/fuse-box/fuse-box/issues/365

**Comment by aretecode** [comment]
While improving the API, I think it would be worthwhile to consider `devServer` for nodejs, which would simply `try catch` require your nodejs `output` whenever hmr emits 👍

**Comment by aretecode** [comment]
https://github.com/fuse-box/fuse-box/issues/354 related to api changes
