### ISSUE TITLE
"self" is not defined

### ISSUE THREAD

**Issue by mattoni** [fuse-box/fuse-box#404]
Trying to import the "[isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch)" package so that I can use fetch on the server (node env.) 

It errors out with this: 

```
module.exports = self.fetch.bind(self);
ReferenceError: self is not defined
```

the output of the bundle is this: 

![image](https://cloud.githubusercontent.com/assets/5110855/23934029/ae25d358-08ff-11e7-8a54-5e1f497b3a2a.png)

Looks like there is no self object being defined. Is this something that needs to be defined in the fusebox config? I've never had an issue using this in webpack.

Thanks!

**Comment by nchanged** [comment]
I think I know what's happening, we need to update docs .. bundle your server like this: [index.ts]

**Comment by mattoni** [comment]
That did fix it, sorry for the late reply. Could you give me some more info on what that changes? 

Thanks!

**Comment by nchanged** [comment]
So it did help?

**Comment by mattoni** [comment]
Yes, that removed the error I was seeing. Was wondering what wrapping it in `[]` changes.

**Comment by nchanged** [comment]
it's called `bundle isolation` =) You don't need to bundle libraries on npm for server bundles -)
