### ISSUE TITLE
Incorrect sourcemaps in vendor bundle

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#405]
Hi, when I split my bundle into vendor bundle, the sourcemaps stop working.
they work correctly for the mail bundle, but not for the vendor bundle.

**Comment by aretecode** [comment]
http://fuse-box.org/#sourcemaps
<img width="752" alt="screen shot 2017-03-14 at 11 47 21 pm" src="https://cloud.githubusercontent.com/assets/4022631/23936652/9d74b720-0910-11e7-8cb6-af0dacac51a3.png">

**Comment by tomitrescak** [comment]
@aretecode Thanks, I missed that, if it's a known bug I can close this issue since it's tracked somewhere else. If you would not mind, can you write here an issue where it is tracked? I'd love to follow. Thanks!
