### ISSUE TITLE
make it simpler to keep examples up to date

### ISSUE THREAD

**Issue by aretecode** [fuse-box/fuse-box#406]
- symlink all example seeds
- script to update
- script to deploy back to original repos

**Comment by devmondo** [comment]
Done, we now have [ fuse-box-examples ](https://github.com/fuse-box/fuse-box-examples)

we will close this for now but let us know otherwise :)

**Comment by aretecode** [comment]
@devmondo not all examples are in there, for example, vue example, angular example

**Comment by devmondo** [comment]
@aretecode those are seeds and not the core example.

@nchanged should we reopen this?

**Comment by nchanged** [comment]
No, these examples will stay in separate repositories

**Comment by devmondo** [comment]
@aretecode is it clear? or you have more input?
