### ISSUE TITLE
Conditionnal compilation

### ISSUE THREAD

**Issue by leon-andria** [fuse-box/fuse-box#408]
There is a way to do like this https://msdn.microsoft.com/en-us/library/aa691099(v=vs.71).aspx ?

//#If SERVER
... any code
//#endif

I would like that fuse not include in the bundle inside "any code" if it's not SERVER ?

**Comment by devmondo** [comment]
@leon-andria could be created as plugin easily, so maybe we should include it as built in plugin, as this is very common style in `.NET`

**Comment by leon-andria** [comment]
Perfect!
If this works, we are able to build bundles optimized for a specific condition, it doesn't need to say that it will reduce the size and no need to split code with different bundles :-)

**Comment by nchanged** [comment]
i think that's a part of tree shaking with `FuseBox.isServer` condition

**Comment by devmondo** [comment]
also, it could work in coordination with this #354

**Comment by leon-andria** [comment]
Yes it's a king if tree shaking.
#354 is really perfect, we can add any target.

**Comment by aretecode** [comment]
this is what you'd want to use https://github.com/fuse-box/fuse-box/blob/master/src/plugins/ReplacePlugin.ts for

**Comment by leon-andria** [comment]
Yes this is an alternative but Im looking for something better where it should be conditional.

**Comment by nchanged** [comment]
yeah, that will be done eventually, when target is introduced

**Comment by unlight** [comment]
@leon-andria 
`fusebox-gulp-plugin` with `gulp-preprocess` plugin can do that.

**Comment by devmondo** [comment]
done FuseBox.isServer replaced with Quantum.

we will close this for now but let us know otherwise :)
