### ISSUE TITLE
Plugin init, need to know if user is running devServer or Bundle

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box#409]
Plugin init, need to know if user is running devServer or Bundle

You might have other threads working in a plugin, so need to know if you need to quit these

**Comment by nchanged** [comment]
But this has to wait until `1.4.1`. It is actually coming sooner than expected. We will be able to try out a preview already in a few days!!!

**Comment by vegarringdal** [comment]
np, added a temp fix for it in the typechecker for now

**Comment by vegarringdal** [comment]
Any new updates on the preview how to figure out if dev server is being used?

It will kind be connected to this one
https://github.com/fuse-box/fuse-box/issues/435

If we had a final complete event for plugins I would know there is dev server was used and if I needed to quit the slave process after its done

**Comment by nchanged** [comment]
I will resolve it tomorrow =)

**Comment by nchanged** [comment]
Try `context.bundle.producer.devServerOptions !== undefined`
