### ISSUE TITLE
homeDir location changed to the fuse.js file location

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#411]
Currently
```
FuseBox.init({
  homeDir : "src/"
})
```

Means that we take the actual project path, the same level as node_modules. But it would make more sense to take `require.main` location to make it relative to `fuse.js` file. 

```
- foo
     - src:
      - fuse.js
```

With this structure, you would do `homeDir : "src"` as opposed to `homeDir : "foo/src"`

What do you think?

**Comment by cellog** [comment]
I don't understand. Where is fuse.js before, and how is it changed by this proposal?

**Comment by nchanged** [comment]
fuse.js is now next to `node_modules`, so nothing will change in this case. But if you move `fuse.js` to a different folder `foo` then i suggest we resolve paths from it.

**Comment by cellog** [comment]
oh I see.  In that case, yes, this is how package.json works.
