### ISSUE TITLE
devServer naming change proposal for 1.4.1

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#412]
Currently, you can launch a devServer without actually having a devServer... with `httpServer : false`
Which does not make much sense

Ideas combined:

### fuse.dev
```
// everything included
fuse.dev({ port : 4444 }) 

// just socket (for hmr)
fuse.dev({ socket : true, server : false, port : 4444 }) 

// just http server
fuse.dev({ socket : false, port : 4444 }) 

// or like this
fuse.dev({ server : true, socket : false, port : 4444 }) 

```

### fuse.development

How about `fuse.development`

### fuse.playground

```
// everything included
fuse.playground({ port : 4444 }) 

// just socket (for hmr)
fuse.playground({ socket : true, server : false, port : 4444 }) 

// just http server
fuse.playground({ socket : false, port : 4444 }) 

// or like this
fuse.playground({ server : true, socket : false, port : 4444 }) 

```

**Comment by aretecode** [comment]
:+1 to dev for standard convention

I think if only socket true is passed in, `server` should default to false, example: `fuse.dev({ socket: true }) `

**Comment by nchanged** [comment]
Thumbs up for `fuse.dev`

**Comment by nchanged** [comment]
Thumbs up for `fuse.development`

**Comment by nchanged** [comment]
Thumbs up for `fuse.playground`

**Comment by nchanged** [comment]
`fuse.dev` it is ;-)
