### ISSUE TITLE
ES2015 Template String and Arrow Function Unexpected token

### ISSUE THREAD

**Issue by mishengqiang** [fuse-box/fuse-box#413]
Using webpack and browserify are no errors, only Fusebox is wrong.

![template string](https://cloud.githubusercontent.com/assets/9413032/23989203/9598d7fe-0a6c-11e7-8a0a-bfb0e786e51c.png)

![arrow function](https://cloud.githubusercontent.com/assets/9413032/23989678/5af358a2-0a6e-11e7-963c-906dd3aabb25.png)

tsconfig.json
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": false,
        "sourceMap": false,
        "preserveConstEnums": true,
        "newLine": "CRLF",
        "allowUnusedLabels": true,
        "allowUnreachableCode": true,
        "noEmitHelpers":true,
        "lib": [
            "dom",
            "scripthost",
            "es5",
            "es2016",
            "es2015.promise"
        ]
    },
    "include": [
        "src/**/*.ts"
    ]
}
```

gulpfile.js

```js
gulp.task('test:appjs', function () {
    fsbx.FuseBox.init({
        homeDir: "./src/",
        sourceMaps: true,
        plugins: [
            fsbx.HTMLPlugin({ useDefault: true }),
            fsbx.TypeScriptHelpers()
        ],
        outFile: "./tmp/js/app.js"
    }).bundle(">appdev.ts");
});
```

**Comment by nchanged** [comment]
How do you import that file? Typescript does not seem to compile it.

**Comment by devmondo** [comment]
the error above means the file was not transpiled with TS, how do you import it in your code ?

**Comment by mishengqiang** [comment]
Part of the code is imported using the require method, and the other part of the code is imported using the import of ES2015.

**Comment by mishengqiang** [comment]
I found that the arrow function modified to normal anonymous functions and template string modified to normal string, it is correct.
It seems that this is not a TypeScript compiler problem, but fuse-box caused.

**Comment by nchanged** [comment]
@mishengqiang FuseBox does not alter your code, unless you use aliases

**Comment by mishengqiang** [comment]
Now I will have the arrow function test.ts as entry file, the result is still wrong.
![Uploading image.png…]()

**Comment by nchanged** [comment]
Something is off with your typescript configs. Works perfectly for me

**Comment by mishengqiang** [comment]
@nchanged Oh! My! God! 
I modified the contents of the tsconfig.json file, and then restored, but the run task is correct, in fact I did not change tsconfig.json content.
This is amazing.

**Comment by nchanged** [comment]
Maybe you did not restart?

**Comment by mishengqiang** [comment]
I tried many times and found that if you remove tsconfig.json targe attribute will not be an error, otherwise there is still an error.

**Comment by nchanged** [comment]
can we close it now?
