### ISSUE TITLE
Cache file name & path too long.

### ISSUE THREAD

**Issue by charles-mathieus-jomedia** [fuse-box/fuse-box#415]
Because the name of my folder is a bit too big, I get that error:

Error: ENAMETOOLONG: name too long, mkdir '/home/cmseguin/dev/git/react-express-boilerplate/.fusebox/cache/1.3.128/%2Fhome%2Fcmseguin%2Fdev%2Fgit%2Freact-express-boilerplate%2Fhome%2Fcmseguin%2Fdev%2Fgit%2Freact-express-boilerplate%2Fdist%2Fpublic%2Fapp%2Findex.js'

As soon as I rename it to something shorter, it works.

Could we hash/compress the whole thing?

**Comment by nchanged** [comment]
Oh yes, absolutely! Thanks for the issue

**Comment by nchanged** [comment]
<img width="318" alt="screenshot 2017-03-17 10 30 00" src="https://cloud.githubusercontent.com/assets/1629088/24037097/cbdb6ff8-0afc-11e7-861e-e042b2c1e623.png">

Coming soon ;-)

**Comment by johndevs** [comment]
@nchanged So was this fixed?

I'm still getting this with fusebox 3.7.1 on Ubuntu.

```
  errno: -36,
  code: 'ENAMETOOLONG',
  syscall: 'open',
  path: '/home/john/Repositories/zervantui/.fusebox/cache/3.7.1/1UEMsX-client%2Fvendor/static/client%2Fcomponents%2Finvoices%2FInvoiceInfo%2FInvoiceEventsTimeline%2FInvoiceTimelineEvents%2FEventShared%2FArchiveDownloadLink%2FArchiveDownloadLink.jsx.js' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Exit status 1
```

**Comment by nchanged** [comment]
v3 is no longer supported. Please move to `v4`
