### ISSUE TITLE
Bundle promise should be fulfilled after file write is complete.

### ISSUE THREAD

**Issue by cmseguin** [fuse-box/fuse-box#417]
So I am trying to get the content of the bundled file in the `.then`, but I only get partial content... If I put a setTimeout, then it's fine!

**Comment by devmondo** [comment]
@cmseguin with 1.4.1 release coming soon, you ill have `run()` function that is a full promise.

but regarding current API, the `bundle` function itself returns a promise but it has an optional second param that takes a callback where the content is guaranteed to be written.
