### ISSUE TITLE
BabelPlugin + ReplacePlugin do not run together

### ISSUE THREAD

**Issue by aretecode** [fuse-box/fuse-box#424]
- add babel plugin 
- add replace plugin 
- only the first babel plugin runs
- same thing happens if order is reversed 
- same thing happens if you use two babel plugins

**Comment by yihongang** [comment]
have you tried doing this with a nested array? e.g.

```
plugins: [
    [
      BabelPlugin(),
      ReplacePlugin({
        "process.env.NODE_ENV": JSON.stringify("production")
      }),
      UglifyJSPlugin()
    ]
  ]
```

I don't know why, but the `tryPlugins` code seem to only allow for 1 target plugin (or 1 target chain of plugins)

**Comment by nchanged** [comment]
@aretecode Quantum solves this issue already

**Comment by devmondo** [comment]
and you need to put `.js` extension. `[“.js”, ReplacePlugin()] `

we will close this for now but let us know otherwise :)

**Comment by patgoley** [comment]
@nchanged Any possible solution for someone on fuse-box version 1.3.131? It seems Quantum would do the trick but not available in my current version. I've tried a few things here including:

Basically I'd like to change which config file is required across the app depending on process.env.APP_ENV.
I've tried the following:
1. Use ReplacePlugin after Babel as described above by @yihongang 
2. `const config = require("./config/" + process.env.APP_ENV);`
    - `process.env.APP_ENV` is _not_ replaced.
3. Use ReplacePlugin before Babel. 
   - I get errors about valid ES6 code, so I assume Babel is not running all together.
4. Don't use replace plugin, just relying on `require("./config/" + process.env.APP_ENV);` at runtime.
   - Doesn't work as `require("./config/dev")` isn't resolved at compile time so the `./config/dev` module is not included in the optimized build.
5. Alias option:
`
alias : {
    "'~/config'" : `'./config/${process.env.APP_ENV}'`
},
`
  - Seems to have no effect. All require paths are still ~/config in the build.

Any advice for me here or is my only option to migrate to fuse-box 2.x to start using Quantum?

**Comment by nchanged** [comment]
Yep, I think you should upgrade, there has been so many changes and improvements

**Comment by patgoley** [comment]
@nchanged Thanks. Is there any kind of migration guide from 1.x -> 2.x? I've tried updating the fuse-box module to 2.2.31 but I'm not sure how my config needs to be updated to match; currently getting errors in fuse box when trying to build.

**Comment by nchanged** [comment]
I think it's all there
http://fuse-box.org/page/bundle
You just need to create separate bundles

**Comment by patgoley** [comment]
@nchanged Thanks. I didn't end up needing separate bundles or Quantum. I updated to Fuse Box 2.0 and was able to use ReplacePlugin and BabelPlugin in a nested array in my plugins. This worked fine and I didn't have the same problems from 1.x where only one of them would run, but _make sure_ you have them in an array together. Like so:

```
fuse = new FuseBox({
            modulesFolder: path.join(srcDir, 'modules'),
            homeDir: srcDir,
            sourceMaps: !isProduction,
            hash: isProduction,
            cache: !isProduction,
            output: path.join(targetDir, '$name.js'),
            plugins: [
                EnvPlugin({
                    "NODE_ENV": process.env.NODE_ENV,
                    "APP_ENV": process.env.APP_ENV
                }),
                SVGPlugin(),
                [
                    SassPlugin({ importer: true, includePaths: [path.join(process.cwd(), 'node_modules')] }),
                    CSSPlugin({ outFile: (file) => `${targetDir}/${file}`, inject: false })
                ],
                CSSPlugin(),
                WebIndexPlugin({ template: path.join(srcDir, 'index.html'), path: './', }),
                [
                  ReplacePlugin({ "process.env.APP_ENV": process.env.APP_ENV }), 
                  BabelPlugin({
                    config: {
                        sourceMaps: !isProduction,
                        plugins: ["transform-class-properties", "transform-function-bind", "transform-object-rest-spread", "transform-decorators-legacy"],
                        presets: ["es2015", "react"]
                    }
                  })
                ],
                isProduction && QuantumPlugin({ removeExportsInterop: false, uglify: true })]
        });
```
