### ISSUE TITLE
Root config should override app-root-path

### ISSUE THREAD

**Issue by aretecode** [fuse-box/fuse-box#425]
currently, app root path is used to resolve the root, which can often be wrong:
- if I have a monorepo, 
- or any subfolders with a package json, 
- or I put the fusebox build config in a reusable package

Babel plugin (and possibly others) only checks app-root-path and does not respect my root, since I cannot set my own app root.  The `root` property in `WorkflowContext` should be used for all.

**Comment by nchanged** [comment]
Eh, it's already changed in 1.4.1 :) no more appRoot :)

**Comment by devmondo** [comment]
shall we close this then :)

**Comment by nchanged** [comment]
I guess Babel Plugin needs to be checked

**Comment by aretecode** [comment]
https://github.com/fuse-box/fuse-box/blob/1.4.1/src/plugins/js-transpilers/BabelPlugin.ts#L3

**Comment by aretecode** [comment]
https://github.com/fuse-box/fuse-box/issues/424

**Comment by devmondo** [comment]
The recommended usage is as in https://github.com/fuse-box/fuse-box/issues/424#issuecomment-332936407

will close this for now :)
