### ISSUE TITLE
No step by step guide

### ISSUE THREAD

**Issue by skiabox** [fuse-box/fuse-box#426]
--- TO BE REMOVED --

Before summiting an issue, please make sure that:

* You have removed the `.fusebox` folder in your project root
* Removed node_modules, (re-installed everything) 
* Started the bundling process again. 
* Read the documenation on your subject here -> fuse-box.org

Please create a step by step guide.

**Comment by nchanged** [comment]
Hi, thanks!
`--- TO BE REMOVED --` i think that line explicitly says to remove it from the body.

**Comment by skiabox** [comment]
No prob man.
I am writing here because in the gitter channel I saw a very light atmosphere and although I am trying to help you some kids in there were laughing at me.
Keep up the good work.

**Comment by skiabox** [comment]
You might have the best product in the market and loose clients because of bad docs.

**Comment by devmondo** [comment]
@skiabox  no worries man, and thanks for your interest, we will constantly keep improving fuse :)

**Comment by skiabox** [comment]
If I rate the product with 10 the docs are rated with 2.

**Comment by nchanged** [comment]
@skiabox Instead of ranting how bad docs are fork this repository and start improving.

**Comment by devmondo** [comment]
@skellock thanks for the honest words, again, by all means, if you have anything you see can be added or rewritten, this project is open source, u can fork the docs and improve them and we will be more than happy :)

a fresh perspective is always needed

**Comment by skiabox** [comment]
I am working on a personal project so I don't have the time for a second job.

**Comment by devmondo** [comment]
@skiabox whenever you get time, don't hesitate to contribute

**Comment by skellock** [comment]
@devmondo I think you accidently summoned me 3 posts up.  Sadly I am not a genie and you do not get 3 wishes.

Instead, have these 3 cookie: 🍪 🍪 🍪

**Comment by devmondo** [comment]
@skellock so sorry man :) and thank you for the delicious cookies :)

**Comment by Thanood** [comment]
I think a step by step guide would be a good idea.

The way I've been using fuse-box is mix and match examples.

Maybe I can take a shot at a guide when 1.4.1 is out of preview. If nobody else is faster. 😃 
I'd rather get my hands on a guide for 1.4.1 - I like the usage.

**Comment by pejalo** [comment]
I've started a guide called "Getting Started with FuseBox from Scratch" in my quest to get FuseBox working. A link to the draft, updates, and my n00b questions will all be shared in the FuseBox [gitter](https://gitter.im/fusebox-bundler/Lobby) chat room.

**Comment by devmondo** [comment]
glad to tell you it is there now :)
[fusebox-faster-webpack-alternative](https://www.sitepoint.com/fusebox-faster-webpack-alternative)

we will close this for now but let us know otherwise :)
