### ISSUE TITLE
There's no output.

### ISSUE THREAD

**Issue by trusktr** [fuse-box/fuse-box#429]
I have a simple fusebox.js file in my project:

```js
const FuseBox = require('fusebox').FuseBox

let fuse = FuseBox.init({
    homDir: './src',
    outDir: './fusebox_test',
    cache: true,
    log: false,
    debug: false,
})

fuse.bundle('> main.ts')
```

When I run `node fusebox.js`, nothing happens. There's no `outDir` created.

What am I missing?

**Comment by trusktr** [comment]
I tried the following which doesn't work:

```js
const FuseBox = require('fusebox').FuseBox

let fuse = FuseBox.init({
    homDir: 'src',
    outFile: 'fusebox_test/main.js',
    cache: true,
    log: false,
    debug: false,
})

fuse.bundle('> main.ts')
```

**Comment by trusktr** [comment]
Ah, but this works:

```js
const FuseBox = require('fusebox').FuseBox

let fuse = FuseBox.init({
    homDir: './src',
    outFile: './fusebox_test/main.js',
    cache: true,
    log: false,
    debug: false,
})

fuse.bundle('> main.ts')
```

Note the extra `./` in front of the file names.

I'm just trying to get this to work as quickly as possible. I think this shows that some things can be improved to make the API more intuitive.

For example, if I supply an `outDir` but not `outFile`, just take my file and put it there. Also make it work without the `./`.

**Comment by trusktr** [comment]
Is there a way to compile all files in a directory? Or do I need to manually make a FuseBox.init for each file?

**Comment by trusktr** [comment]
Not sure what made me try `outDir`. That isn't even.. listed in the docs.

**Comment by Thanood** [comment]
Just for completeness sake: your `homeDir` is spelled `homDir`. 😃
