### ISSUE TITLE
Fusebox 1.4.1, plugin events

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box#435]
Hi

Would have been nice with a "completed" event for plugins when all bundles are done/ and is re-bundled.

Also looks like bundleEnd is triggering twice during first run. 
Ive tried disable the dev server to see if that helped, buit it did not.

On 1.4.1:preview.7 atm

Ref plugin:
https://github.com/fuse-box/fuse-box-typechecker/issues/9

**Comment by nchanged** [comment]
I was looking into it.. and there seems to be a complication with watches, as it defers the calls (locks/unlocks) Do you think it's better to setup a plugin individually instead?

`fuse.bundle("app").plugin(TypescriptChecker())` ?

**Comment by vegarringdal** [comment]
> I was looking into it.. and there seems to be a complication with watches, as it defers the calls (locks/unlocks)

Lost me on this one.

>Do you think it's better to setup a plugin individually instead?
fuse.bundle("app").plugin(TypescriptChecker()) ?

This could be useful, maybe not all bundles need same plugins

I was thinking just a "complete" event when all bundle have run "bundleEnd".
Because withing 1 bundle there is usually just one tsConfig, so I really just need to run it once.

**Comment by nchanged** [comment]
You can use now 
```
const producerEvents = context.bundle.producer.sharedEvents;
producerEvents.addEventListener("producer-done", () = {

})`
```
You have to put on plugin `init`.  It has be bound once, 

Let me know if it works, and close the issue ;-)
