### ISSUE TITLE
HMR not work in preact

### ISSUE THREAD

**Issue by xyyjk** [fuse-box/fuse-box#445]
Each edit will copy the previous component:

![](https://ww4.sinaimg.cn/large/006tKfTcly1fe4xj8vs9xj31kw0yjjxm.jpg)

Example: https://github.com/xyyjk/fusebox-preact-example

**Comment by nchanged** [comment]
Well of course, because each time it executes your entry point. You need to hande it OR create your own HMR

http://fuse-box.org/#loader-plugins

**Comment by devmondo** [comment]
@xyyjk this will help you getting started
https://medium.com/@basarat/rethinking-hot-module-reloading-58ce15b5f496
