### ISSUE TITLE
Bundling lodash-es doesn't work as desired

### ISSUE THREAD

**Issue by wiredprairie** [fuse-box/fuse-box#446]
I am trying to bundle `lodash-es` into a project with FuseBox

As a sample, I've used the [React Reflux Seed](https://github.com/fuse-box/fuse-box-ts-react-reflux-seed) to replicate the issue.

With that repo:

    npm i -S lodash-ex

Add lodash to `REACT_DEPS` in `gulpfile.js`:

    +lodash-es

And then `gulp dev`.

If you look at `vendor.js` which now includes `lodash-es`, the syntax isn't valid for the browser:

    export { default as add } from './add.js';
    export { default as after } from './after.js';

(And many many more like that).

I've experimented with the `BabelPlugin`, but no option that I tried had any noticeable impact. 

Is there a method for getting it to work? 

Ultimately, I might need to see if there's some clean way of using `@types/lodash` and just loading the standard `lodash` library into the global namespace rather than using modules.

**Comment by devmondo** [comment]
@wiredprairie  hi :)
did u try aliases?
http://fuse-box.org/#alias

**Comment by aretecode** [comment]
@wiredprairie I know you said you experimented with the BabelPlugin, but I'd like to check: have you tried using `limit2project: false` ?

**Comment by wiredprairie** [comment]
Yes, I did try that.

**Comment by nchanged** [comment]
@wiredprairie after you toggled it, you need to clear the cache. (remove `.fusebox` folder)

**Comment by wiredprairie** [comment]
I deleted the cache directory with the `limit2project` set to `false` and it still doesn't work. The code is left unchanged as shown above.

**Comment by nchanged** [comment]
Does your babel preset convert es6 to es5?

**Comment by wiredprairie** [comment]
For a few other reasons, I've decided to stop using Fuse-Box for my current project, so I won't have time to look at this further. Sorry for the interruption.
