### ISSUE TITLE
tsconfig.json suggestions

### ISSUE THREAD

**Issue by zgredzik** [fuse-box/fuse-box#45]
A couple of ideas that popped into my mind when trying to get FuseBox to work with TS and React (all in reference to [getTypeScriptConfig()](https://github.com/fuse-box/fuse-box/blob/master/src/WorkflowContext.ts#L357))
* documenting the existance of the `tsConfig` option (I don't think I've seen it anywhere in the docs or the site)
* letting users specify the location of the `tsconfig.json` file (by default it looks in `homeDir`, but I think I'm not the only one that prefers to keep his `tsconfig.json` in project's root and not in `src` dir together with the sources, nor do I find it *clean* to add symlinks); one can work around the lack of this feature by reading the contents of `tsconfig.json` from a different location and feeding it to FuseBox through the `tsConfig` option, but I believe this to be a common enough use-case to consider adding it as a separate option
* finding some less strict way of parsing the JSON contents of the `tsconfig.json` than using `require` (afaik TS lets you keep comments in your config, `require` is too strict about the JSON structure for that and it would be nice to reuse the same ts config across all tools)
* (this one is more a question than an idea or an issue, mostly because I haven't had the time to dug deeper into FuseBox's code); just wanted to point out that `.tsx` files do not to trigger [switching to typescript mode](https://github.com/fuse-box/fuse-box/blob/master/src/Arithmetic.ts#L136) and yet my project bundles without problems (probably because of things like [this](https://github.com/fuse-box/fuse-box/blob/master/src/File.ts#L246) and [this](https://github.com/fuse-box/fuse-box/blob/master/src/PathMaster.ts#L42)) also I don't know the significance of [ensureFolderAndExtensions](https://github.com/fuse-box/fuse-box/blob/master/src/PathMaster.ts#L180) but it seems to depend on `tsMode` and assume a `.ts` extension

**Comment by nchanged** [comment]
Thank you very much for the ideas.
Good thinking. I was expecting someone to raise that topic sooner or later =)

* tsconfig.json will be configurable (it was on my list)
* -
* Can be done (any suggestions how?)
* I guess it's a bug. `.tsx` should trigger typescript mode. 

When you are in typescript mode and do an import that looks like `import foo from "./foo"` FuseBox has to know that you are referring to a `.ts` extension not `.js`

Let me know what you think

Cheers

**Comment by zgredzik** [comment]
Regarding the strictness: I think [this suggestion](https://plus.google.com/+DouglasCrockfordEsq/posts/RK8qyGVaGSr) is a plausible approach (read the contents, minify, feed into `JSON.parse`).
Another way to do this would be to mimic the behaviour of ts itself, as depicted in the [pr that introduced comments to tsconfig](https://github.com/Microsoft/TypeScript/pull/5450/files).

**Comment by devmondo** [comment]
the way i see it is really simple, just provide option to take the path relative to project dir, and feed it to TS and that is all. Fuse is now and should always be transparent about plugins, in essence it should only receive content wither it is compiled or not and do the bundling.

**Comment by devmondo** [comment]
this is now supported, please reopen if otherwise :)
