### ISSUE TITLE
Anything equivalent to html-webpack-plugin?

### ISSUE THREAD

**Issue by knpwrs** [fuse-box/fuse-box#451]
Is there anything in the FuseBox ecosystem that matches the functionality of the [`html-webpack-plugin`](https://www.npmjs.com/package/html-webpack-plugin)? Essentially it generates your `index.html` for you, either from a base template or a template that you provide, and then injects any script tags needed for your app wherever you want (head, bottom of body, etc). I did a little searching and didn't see anything, and I also looked at the FuseBox API but it seems more suited to transforming source files than creating new files.

**Comment by devmondo** [comment]
hi @knpwrs 
we already have `HTMLPlugin` http://fuse-box.org/#html-plugin

but what you are looking for we call it `CopyPlugin` it is currently in 1.4.1 branch which will be released soon but you can check it out and try it :)
https://github.com/fuse-box/fuse-box/blob/1.4.1/docs/plugins/CopyPlugin.md

**Comment by arabsight** [comment]
this looks close enough https://github.com/fuse-box/preview-1.4.1/blob/master/examples/react-code-splitting/fuse.js#L61

**Comment by knpwrs** [comment]
I saw `html-plugin` but that seems to be closer to [`html-loader`](http://npm.im/). `html-webpack-plugin` creates `index.html` but you don't get a reference to the file anywhere in the code, it just acts as your application's entry point, one large advantage being if your bundle name has a hash in it you don't need to worry about including the right file on the page.

`CopyPlugin` seems closer, but still not quite there. No automatic injection and it seems to add hashes to file names (not optional, if I'm reading properly)?

I'd like to be able to just add an `IndexHtmlPlugin()` to my plugins array, fire up a dev server, and be good to go without having to write an `index.html` file.

**Comment by knpwrs** [comment]
Here is my minimal example: https://github.com/knpwrs/minimal-webpack-html

Just run the following:

```
npm install
npm start
```

You'll get a server running on 8080 serving the bundle and an `index.html` file that has a script tag pointing at the bundle. Notice that the repository doesn't include an `index.html` file, this is because it is generated. The bundle will always be included properly regardless of the filename (hashed or not) and regardless of where the output directory is.

**Comment by devmondo** [comment]
@nchanged any input on this ?

**Comment by knpwrs** [comment]
Just to make this more generic, essentially webpack has the ability to emit artifacts which are not based on source. Plugins are able to just pop artifacts into existence, and they can base those artifacts based on other artifacts. `html-webpack-plugin` is the most common usage of this, but there are others as well.

**Comment by nchanged** [comment]
@knpwrs plugins are in fuse-box transform files, however, it makes sense to perform that kind of operations. We need to introduce onProducerEnd in the plugin API, which will get triggered once.

**Comment by aretecode** [comment]
I am working on one, small bits at a time.

**Comment by nchanged** [comment]
It's here temporarily http://fuse-box.org:3333/plugins/webindexplugin
please try `fuse-box@2.0.0-beta.8`
