### ISSUE TITLE
FuseBox.addPlugin

### ISSUE THREAD

**Issue by jperezruiz** [fuse-box/fuse-box#461]
Hi!
I'm trying to add a hmr plugin, reading the doc for http://fuse-box.org/#loader-plugins I see FuseBox.addPlugin but it throws an exception:
![image](https://cloud.githubusercontent.com/assets/11233351/25150705/1adc52d0-2483-11e7-850f-a45e82791f71.png)

Trying to do the same with the fuse instance results in the same:
![image](https://cloud.githubusercontent.com/assets/11233351/25150738/3c4fc258-2483-11e7-9bd6-6e909cd7f421.png)

Looking the code, I saw LoaderAPI.ts that declares FuseBox class with addPlugin method, but the class instatiated by FuseBox.init doesn't have this method.

What I'm doing bad?

**Comment by nchanged** [comment]
Hi!
Sorry for the late reply. You should do it at runtime. 
https://github.com/fuse-box/fuse-box-ts-react-reflux-seed/blob/master/src/client/hmr.ts
