### ISSUE TITLE
improve debug output

### ISSUE THREAD

**Issue by Thanood** [fuse-box/fuse-box#466]
Currently, when running with debug and log activated, I'm getting an output like this:

```
$ node build/bundle

app ->


17:37:11 : Typescript : Captured  index.js

17:37:11 : TypeScript : Transpile index.js
  → Typescript config file was not found. Improvising

17:37:11 : BabelPluginClass : Captured index.js

17:37:11 : BabelPlugin :
        Configuration: {"sourceMaps":true,"presets":["es2015"]}

17:37:11 : BabelPluginClass : Captured index.js

17:37:12 : BabelPluginClass : Captured foundation.js

17:37:12 : BabelPluginClass : Captured component.js

17:37:12 : BabelPluginClass : Captured foundation.js

17:37:12 : BabelPluginClass : Captured constants.js

17:37:12 : BabelPluginClass : Captured util.js
└── default (1 files,  321 Bytes)
      index.js
└── @material/ripple (4 files) 42.6 kB
└── @material/base (3 files) 17.3 kB

    Size: 60.3 kB in 1s 3ms
```

There are several `index.js` and `foundation.js` and I would like to know the directory of these files.
Also, are the double newlines necessary? 😃

**Comment by nchanged** [comment]
We could polish it sure. Feel free to submit a PR ;-) We are busy with 2.0 ATM

Please feel free to check the latest bleeding edge version `fuse-box@2.0.0-beta.8`
and documentation for it http://fuse-box.org:3333

**Comment by aretecode** [comment]
https://github.com/fliphub/fliplog

**Comment by Thanood** [comment]
Sure, I can try. I just don't know where to start. 😃 
Probably `IPathInformation` and classes which use that I guess.. I will have a look.

**Comment by Thanood** [comment]
If anyone is interested in status, I completely failed to do it. 😃 

There are some TypeScript transpiler errors because of wrong type declaration and I don't know if I should try to fix that. Maybe I can set my TS to ignore them.

Also, I failed to find the correct spot.

That's not to say I'm giving up. 😏

**Comment by nchanged** [comment]
@Thanood I've removed extra spaces already =) But it requires improvements anyway.
