### ISSUE TITLE
Can not bundle internal package.json that has relative` main` like a redux-saga

### ISSUE THREAD

**Issue by mizchi** [fuse-box/fuse-box#470]
For example, this is `node_modules/redux-saga/effects/package.json`

```
{
  "name": "redux-saga/effects",
  "private": true,
  "main": "../lib/effects.js",
  "module": "../es/effects.js",
  "jsnext:main": "../es/effects.js"
}
```

next code passes but has no reference.

```
// source
import effects from 'redux/effects' 

// compiled
var _effects = require('redux-saga/effects'); //=> undefined
```

**Comment by nchanged** [comment]
hi @mizchi we are not covering package.json in sub folders just yet, that's quite a heavy procedure. You can solve it using aliases for now.

**Comment by mizchi** [comment]
@nchanged OK, thx. I solved by replacing to `redux-saga/lib/effects`

**Comment by nchanged** [comment]
I will close this for now, as there are many related issues.

**Comment by knpwrs** [comment]
I ran into this problem earlier today using TypeScript. The typings will not resolve properly for `redux-saga/lib/effects` so you have to add the following to the FuseBox configuration:

```js
// ...
  alias: {
    'redux-saga/effects': 'redux-saga/lib/effects',
  },
// ...
```

Then you can use `redux-saga/effects` directly and typings will work.
