### ISSUE TITLE
SassPlugin on Windows 10

### ISSUE THREAD

**Issue by dragosbulugean** [fuse-box/fuse-box#471]
SassPlugin with options { importer: true } doesn't work on Windows 10.
It generates an @import from full filesystem path with backslashes and doesn't import it.

Also, SassPlugin only works with .scss files (.sass files (prettier syntax) don't get picked up)

**Comment by devmondo** [comment]
@dragosbulugean for `.sass` format, from the docs 
n order to use Sass indented syntax set indentedSyntax option:
```
fuse.plugin(
    SassPlugin({
       indentedSyntax: true
    }), CSSPlugin()
)
```

**Comment by sjahan** [comment]
I also encounter the same problem, not about the indentedSyntax, but about the import, is that normal? 

I use this configuration: 
```
const fuse = FuseBox.init({
    'homeDir': 'src',
    'output': '$name',
    'sourceMaps': !prod,
    'plugins': [
        [
            /\.s?css$/,
            SassPlugin({
                'importer': true,
                'outputStyle': 'compressed',
                'sourceMap': `.${module}.css.map`
            }),
            CSSPlugin({
                'group': 'app.css',
                'outFile': './app.css'
            })
        ],
        BabelPlugin({
            'config': {
                'sourceMaps': !prod,
                'presets': [ 'es2015' ],
                'plugins': [ 'transform-react-jsx' ]
            }
        }),
        WebIndexPlugin({
            'path': '.',
            'template': 'src/index.html'
        }),
        prod && QuantumPlugin({
            'removeExportsInterop': false,
            'uglify': true
        })
    ]
});
```

But in my final css, I get: 
`@import url(/...my project path.../node_modules/normalize.css/normalize.css);`
The path is ok, but the content of the file is not included :(

I imported the file like that: 
`@import "~normalize.css/normalize.css";`

**Comment by nchanged** [comment]
If you see no contents, that means that the file is not there.
