### ISSUE TITLE
Path problems in 2.0 when starting from gulp

### ISSUE THREAD

**Issue by guillaume86** [fuse-box/fuse-box#475]
There's a path issue when starting fusebox 2.0 from gulp (paths are resolved relative to the global gulp.js file).

The issue seems to originate from the line mentioned here:
https://github.com/fuse-box/fuse-box/commit/835221e30b0e5b57392eaccfbd9a52c90e07a5a4#commitcomment-21989868

**Comment by nchanged** [comment]
Thanks, you think we could add a process variable to override it?
Like 
```js
process.env.PROJECT_ROOT
```

**Comment by guillaume86** [comment]
It's ok for me, and maybe add a console.warning with this information if the main require filename is "gulp.js".

**Comment by nchanged** [comment]
`fuse-box@2.0.0-beta.11`

**Comment by guillaume86** [comment]
Just a little touch: you can skip the warning if process.env.PROJECT_ROOT is set.

A little note for future users: you have to set the env variable before requiring fuse-box (just made the mistake).
