### ISSUE TITLE
Example of using SVGPlugin in TS?

### ISSUE THREAD

**Issue by Martaver** [fuse-box/fuse-box#480]
Hey guys, great framework! Am leaving webpack in the wind for fuse-box.

So, I have nuked `.fusebox` and `node_modules` and rebuilt. Also tried several versions of fuse-box including `1.3.26`, `1.3.30`, `1.3.31` and even `2.0.0-beta.11` (since that's what the `react-example` repo is using).

In none of these scenarios have I been able to get the SVGPlugin working with Typescript. My img tag referencing my SVG always renders without its `src` attribute and no image is displayed.

The react-example repo is babel - has anyone done with with Typescript successfully?

**Comment by nchanged** [comment]
Thanks :) and welcome
http://fuse-box.org:3333/plugins/image-base64-plugin

Try that one please with the latest beta. It should be working

**Comment by nchanged** [comment]
Besides, make sure you import it correctly, note that it does not export defaults. Try import * as img from

Sorry for formatting, on my phone

**Comment by Martaver** [comment]
Thanks!

I got the SVGPlugin working by using the * as syntax as your described e.g.

```
import * as logo from './logo.svg';
```
And consume it as:
```
<img src={logo} />
```

In order for the `.svg` import to play nice with ts-lint, I added a:
```
declare module '*.svg';
```
in my `types` directory.

Overall, I find the `import * as logo` unexpected, and unnecessary. Any chance we can get this exporting as default so we can just do `import logo from`...?

**Comment by nchanged** [comment]
Yep, for example, CSSModules has a neat switch `useDefault` - http://fuse-box.org:3333/plugins/cssmodules-plugin#options

We could add it to SVGPlugin. In fact, I think we need to remove SVGPlugin and leave Imagebase64Plugin only, as the latter converts all image formats.

And get familiar with the new version, there are many jaw-dropping features! ;-) It's coming soon.

http://fuse-box.org:3333

**Comment by Martaver** [comment]
Switched to ImageBase64Plugin and works on SVGs like a charm.
SVGPlugin seems distracting - agree it should go.

Fuse-box is insane. I feel like I've discovered some kind of cheat.

I'll be working with this for a while I think, maybe I can contribute to the docs?

**Comment by nchanged** [comment]
@Martaver that would be lovely! Docs need some love, i've been doing them for like 1 month in a row already, any help is greatly appreciated! We are so close to the release!

https://github.com/fuse-box/fuse-box/tree/master/docs

**Comment by nchanged** [comment]
Ok

**Comment by nchanged** [comment]
http://fuse-box.org:3333/plugins/image-base64-plugin#options
