### ISSUE TITLE
LESSPlugin doesn't find relative imports from .less files

### ISSUE THREAD

**Issue by nspaeth** [fuse-box/fuse-box#491]
`node fuse.js` reports that it is unable to find files that are imported from less files.

I've created a repro here: [nspaeth/fuse-box-less](https://github.com/nspaeth/fuse-box-less)

**Comment by leedut** [comment]
I also found this bug when I bundle my react-app with [antd](https://github.com/ant-design/ant-design) . 

antd uses [less-importer](https://github.com/webpack-contrib/less-loader) to import its styles. 

So `@import './index.less'` caught errors.

**Comment by devmondo** [comment]
@nchanged did we fix the paths for this ?

**Comment by nchanged** [comment]
Will check it soon

**Comment by nchanged** [comment]
Thanks to @CantGetRight82 `fuse-box@2.0.0-beta.22`

**Comment by devmondo** [comment]
we will close this, for now, feel free to open it otherwise
