### ISSUE TITLE
Support Vue template preprocessors (e.g. Pug)

### ISSUE THREAD

**Issue by NGPixel** [fuse-box/fuse-box#492]
It would be great if custom template languages, such as Pug, could be used when using .vue components.

```
# Standard HTML template (works)
<template>
  <div class="panel">{{ msg }}</div>
</template>

# Pug template (doesn't work)
<template lang="pug">
  .panel {{ msg }}
</template>
```

vue-loader handles the `lang` parameter on `<template>` and `<style>` blocks. Fuse-box should provides similar support.

Thanks,
Nick

**Comment by nchanged** [comment]
hi @NGPixel the VuePlugin isn't working 100% as it supposed it, The original plugin is tightly coupled with WebPack, so we are missing some features. Please feel free to improve it.

**Comment by nchanged** [comment]
If you interested in helping - that's the [place](https://github.com/fuse-box/fuse-box/blob/master/src/plugins/VuePlugin.ts#L47) where we could abstract things, and attach different HTML compilers

**Comment by NGPixel** [comment]
Sure, I'll implement it.

**Comment by nchanged** [comment]
Closing this one
