### ISSUE TITLE
Sparky.watch() should have a way to define a basepath

### ISSUE THREAD

**Issue by Sirikon** [fuse-box/fuse-box#493]
I have a test project using FuseBox with a folder called `src` on root. Inside that, `assets/logo.png`

With the next sparky task:
```js
Sparky.task('copyAssets', () => {
    return Sparky.watch('./src/assets')
        .dest('./dist')
})
```
Will work as expected, create `src/assets/logo` inside `dist`, but I need to copy just `assets` inside `dist`. not `src`.

There's no documented way to to this, but found out that the watch() method can accept a second parameter which is a chokidar watch() method options parameter. So, using this:

```js
Sparky.task('copyAssets', () => {
    return Sparky.watch('./assets', { cwd: './src' })
        .dest('./dist')
})
```

Creates the file structure correcty... except the `logo.png`. Using the debugger, saw that the cwd param is used by chokidar, but isn't used to correctly build the paths that chokidar is returning.

So:

- Sparky watches `assets` inside `src`
- Chokidar watches `assets` inside `src`
- Chokidar returns `assets/logo.png`
- Sparky injects to the flow `assets/logo.png`, instead of `src/assets/logo.png`

**Comment by Sirikon** [comment]
## Fixing this

If I'm correct with my assumptions, the way to fix this would be:

Here: [SparkyFlow.ts#41](https://github.com/fuse-box/fuse-box/blob/master/src/sparky/SparkFlow.ts#L41), should add the content of `opts.cwd` at the start of `fp`.

In this file: [SparkyFlow.ts#42](https://github.com/fuse-box/fuse-box/blob/master/src/sparky/SparkFlow.ts#L42), should add the content of `opts.cwd` at the end of `info.root`.

This way, filepath and root are both correct using the defined `opts.cwd`.

Also, would be nice to have a `SparkFlowWatchParams` Typescript struct, to have a more consistent API and prevent leveraging API definitions to 3rd party modules.

**Comment by devmondo** [comment]
@Sirikon yep you are right about this.

if you are interested in a temporary workaround until we enhance it. below will keep file structure as you like.

```js
Sparky.task("watch:images", () => {
    return Sparky.watch([`./src/client/**/*.+(svg|png|jpg|gif)`])
        .file(``, (file) => {
            const destPath = file.filepath.replace(/\\/g, "/").replace(`src/`, `dist/`);
            ensureDirectoryExistence(destPath);
            fs.writeFileSync(destPath, file.read().contents.toString());
        });
});

function ensureDirectoryExistence(filePath) {
    var dirname = path.dirname(filePath);
    if (fs.existsSync(dirname)) {
        return true;
    }
    ensureDirectoryExistence(dirname);
    fs.mkdirSync(dirname);
}
```

**Comment by devmondo** [comment]
works perfectly :)
we shall update the Docs accordingly.

**Comment by devmondo** [comment]
i think we have an issue, watch used to accept string or array of globs, now it is throwing if we pass array, as it accepts string only.

**Comment by devmondo** [comment]
i also found another issue, 
it is failing on system paths (which used to work before)
`C://customModules/sharedLib/package.json`

**Comment by devmondo** [comment]
@Sirikon could you take a look at that please :)

**Comment by Sirikon** [comment]
@devmondo Sure! Will look at it tomorrow morning :)

**Comment by devmondo** [comment]
@Sirikon thank you again for the contribution :)

**Comment by nchanged** [comment]
I guess we can close this one =)
