### ISSUE TITLE
 characters in bundle.js is not all utf-8 encoded

### ISSUE THREAD

**Issue by leedut** [fuse-box/fuse-box#501]
I used react + fuse-box@2.0 in my website. But I found that some chinese characters in JSX would be encoded into unicode , but some chinese characters woudld not.

e.g.
1. `<Input placeholder="中文"/>`, this writing style would be encoded as `<Input placeholder="\u4e2d\u6587" />` 

2. `const str = '中文';` or `<Input placeholder={"中文"} />`, these writing styles would not be encoded in bundle.js. 

So is this a bug of fuse-box's loader? Or I miss some config in my fuse.js?

**Comment by nchanged** [comment]
Hm, do you need some config set for babel? Cuz I don't think we encode those...

**Comment by devmondo** [comment]
your first `jsx` Chinese characters are encoded because of the `jsx` compiler capable of that as it is a string. but the rest is out of its scope because it is interpreted as normal js code. I don't think this is a FuseBox responsibility.

will close this issue for now, but let us know otherwise :)
