### ISSUE TITLE
Upgrade Postcss

### ISSUE THREAD

**Issue by geowarin** [fuse-box/fuse-box#504]
Hello!

I'm using FuseBox 2.0.0-beta20 and I'm loving it so far.

However, I have some problems with postcss because versions in fuse-box's package.json do not match latest version available on github. 

I'm getting this error:

```
Your current PostCSS version is 5.2.17, but postcss-nested uses 6.0.1. Perhaps this is the source of the error below.
```

Workaround is to downgrade postcss and related plugins, for now.

I guess postcss should be a peer dependency of fuse-box with a large version range to let the user install whichever version he wants?

AFAIK, [latest release](https://github.com/postcss/postcss/releases/tag/6.0.0) of postcss should not be breaking for fuse-box.

**Comment by devmondo** [comment]
@geowarin welcome to the party :)
we don't include plugins deps so we won't bloat the source, you should be fine installing them on your own. 

let us know :)

**Comment by devmondo** [comment]
oh, after checking this one slipt the radar! we shall remove it

**Comment by nchanged** [comment]
@devmondo we can't remove it. We are using it internally. We just need to upgrade it. Thanks @geowarin

**Comment by nchanged** [comment]
This should
