### ISSUE TITLE
as-needed/configurable api 

### ISSUE THREAD

**Issue by aretecode** [fuse-box/fuse-box#509]
## configurable

> things that should be configurable

- [ ] node backend stuff
- [ ] css loading stuff
- [ ] hmr stuff
- [ ] dynamic socket stuff **including `new Function` / `eval`**
- [ ] electron stuff
- [ ] plugin adding event stuff
- [ ] target - should help improve this

## related
https://github.com/fuse-box/fuse-box/issues/354

**Comment by aretecode** [comment]
https://github.com/fuse-box/fuse-box/blob/master/src/core/WorkflowContext.ts#L400 in refactor, this should be in plugin

**Comment by nchanged** [comment]
@aretecode this should NOT be in a plugin. Typescript should work without plugins in fusebox

**Comment by aretecode** [comment]
@nchanged for code structure, was meant to be on this https://github.com/fuse-box/fuse-box/issues/511
