### ISSUE TITLE
magic detect 

### ISSUE THREAD

**Issue by aretecode** [fuse-box/fuse-box#511]
should have some sort of detection logic, and it should have plugins to allow for extendability on what the detection should do: 

# what

### ts
- when ts is detected, tsplugin is configured
- tsplugin is the same one the user uses, so the core logic is not in the core domain, leaking logic, duplicating the ts bundling (can be seen if you use tsplugin and enable logging, everything is done twice)

### es6
- when es6 is detected, 
- and there is a target, 
- Babel can be auto configured

### vue
- when there is .vue in the instructions or in the parsed require statements, 
- Vue plugin is added (if it is not in `plugins`)

### html 
- when you're running a dev server with web target and no HTML, 
- web index plugin is added (if it is not in `plugins`)
- when there is HTML, and no HTML plugin, auto add `export: default` HTML plugin

### json 
- when there is JSON, 
- add the JSONPlugin (if it is not in `plugins`)

## production
- when no [uglify or babili plugin](http://fuse-box.org:3333/plugins/uglifyjs-plugin#uglifyjs-plugin)
- add [replace plugin](http://fuse-box.org:3333/plugins/replace-plugin)

# when 

- the detection should happen when calling .run, so if the user already configured TS plugin, fusebox doesn't have to add it internally
- the `magic detect` mode could be disabled, as with any other config (`magic: false`)

# related 
- https://github.com/fuse-box/fuse-box/issues/509
- https://github.com/fuse-box/fuse-box/issues/510

**Comment by devmondo** [comment]
We have now http://fuse-box.org/page/configuration#language-level for TS 
and for Vue we now have a great plugin in collaboration with @Shepless 

The rest we think it is too much magic, as fuse by nature would require very less config compared to other bundlers, so we want to keep things clear for users and let them decide their requirement.
