### ISSUE TITLE
half-dynamic requires

### ISSUE THREAD

**Issue by eddow** [fuse-box/fuse-box#512]
Some libraries (I had this with mongo-db) use half-dynamic requires that look like this :
`var package = require(__dirname + '/../package.json')`
It makes fuse-box react badly : it doesn't find the 'lib/../package.json' file

**Comment by nchanged** [comment]
Oh yeah, fusebox can't handle it. All dynamic imports are evil

**Comment by eddow** [comment]
Good news! I wanted to open an issue on their github, but since last month, they corrected it ... !

**Comment by devmondo** [comment]
this shall be closed then :)
