### ISSUE TITLE
SourceMap files path

### ISSUE THREAD

**Issue by eddow** [fuse-box/fuse-box#513]
When making bundles in subdirectories, the sourceMappingURL gets the path based on the "dist" root folder

example:
with `fuse.bundle("server/express")`,the last line of `dist/server/express.js` is:
`//# sourceMappingURL=server/express.js.map`

I am using the module `source-map-loader` as it seems nothing was planned natively in node nor fuse-box to use the sourceMap server-side, but therefore that relative path is problematic : the relative path to the map is `express.js.map` instead of `server/express.js.map`

Did I miss something about using the sourceMap on the server-side?

**Comment by devmondo** [comment]
Thank you very much :)
