### ISSUE TITLE
The socketURI property is not used in fusebox 2.0

### ISSUE THREAD

**Issue by RPDeshaies** [fuse-box/fuse-box#515]
>FYI : My app uses HTTPS

I was using the following code in v1

```js
 fuse.dev({
    port: 4444,
    httpServer: false,
    socketURI: 'ws://localhost:4444',
  })
```
And it was working fine.

But since v2, Fusebox always try to connect to the web socket using the `port` but doesn't care about the `socketURI` property.

e.g. If I change the `port` to `3333` but leave the `socketURI` to `ws://localhost:4444`, I can see the following log in the chrome dev tool : 

```sh
Connecting to fusebox HMR at wss://127.0.0.1:3333
VM6514:35 WebSocket connection to 'wss://127.0.0.1:3333/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
libs.min.js:58175 Object {reason: undefined, message: "Socket error"}
```

So it seems like it's not even taking the `socketURI` in consideration anymore and only uses the `port` property

**Comment by nchanged** [comment]
try 

`hmr({ socketURI: 'ws://localhost:4444' })`
it will work there, i forgot to update that in the docs

**Comment by RPDeshaies** [comment]
Fixed ! Thank you
