### ISSUE TITLE
Uncaught syntax error

### ISSUE THREAD

**Issue by eddow** [fuse-box/fuse-box#519]
A syntax error in the source file goes unnoticed and gets an uncaughts exception from fuse source

Buggy source file:
`import {stuff} from require('module')`
Will be transpiled into :
`const module_1 = require();`
Will throw TypeError: Cannot read property 'type' of undefined at FileAnalysis.nodeIsString (.../node_modules/fuse-box/dist/commonjs.analysis.FileAnalysis.js:71:20)
```
    nodeIsString(node) {
        return node.type === "Literal" || node.type === "StringLiteral";
    }
```
This function tells if the argument is a string ... and there is no argument

The best I guess would be to catch this error in the transpilation.

**Comment by devmondo** [comment]
that’s invalid javascript
that’ s like doing import {stuff} from alert(“hello world“) 
will close this, for now, let us know otherwise :)
