### ISSUE TITLE
Create a Service Worker plugin or boilerplate code example.

### ISSUE THREAD

**Issue by rquast** [fuse-box/fuse-box#520]
I am requesting a new feature:

A service worker plugin, similar to the popular offline-plugin for webpack.

https://github.com/NekR/offline-plugin

Initially, just some boilerplate code/example to do this would be enough, if the task is too big.

Thanks!

**Comment by nchanged** [comment]
```
QauntumPlugin({
   containedApi : true,
   bakeApiIntoBundle : "app"
})
```

That's it, your worker bundle is ready

**Comment by rquast** [comment]
Nice work! I'll be sure to check it out soon. Thanks! :)
