### ISSUE TITLE
Package exports

### ISSUE THREAD

**Issue by eddow** [fuse-box/fuse-box#522]
If I understood well, a bundle should expose the exports of its main file.
Well, it just doesn't - we tried with @devmondo
I made a little repository here:  https://github.com/eddow/fuse-exports-bug
There is 20 lines of code in total.

```
node fuse
node test
```
Trying this, we can see that the imported member is undefined

**Comment by devmondo** [comment]
@nchanged can we look at this with priority

**Comment by arabsight** [comment]
using fuse-box api you can access the exports:
```js
require('./dist/bndl.js');
var imps = FuseBox.import('pack/index.js');
console.dir(imps.test);
```

**Comment by devmondo** [comment]
@arabsight that is true, but we should be able to access it like any NPM package and that is what `package` option provides

**Comment by nchanged** [comment]
@eddow how about that one? http://fuse-box.org/page/configuration#global-variables

**Comment by eddow** [comment]
Well, this is a way of exporting values, yes - that's not the way NPM does for a good reason : if all libraries export on the global object, this one is going to end up "full".
Here, I noticed that trying to use Fuse for my npm libraries indeed - and I can definitely not publish a general library that demands a special syntax for import aka `FuseBox.import('pack/index.js')` nor that exposes its functionalities on the global object

**Comment by devmondo** [comment]
@eddow, i cloned your repo and i was able to make it work, you just did not do correct NPM conventions :)
first, you need to provide `package.json` file in your npm package folder.
second, your bundled file name is `bndl` because of the below you did
```
fuse.bundle("bndl")
	.instructions('> index.ts');
```

if you do that, you need to add `main` property to your npm package `package.json` so any bundler would know that this is the entry file. otherwise, anyone wants to use your package will assume that there is entry file called `index.js` (convention). So in your case do something like `main:bndl.js`, or rename your final bundle file to `index.js`.

it all worked and i used your package in my project and here is log to show that it worked
![image](https://cloud.githubusercontent.com/assets/1266367/26026857/affea6a2-3814-11e7-9d1f-96ec88c2c7cb.png)

hope this helps :)

**Comment by eddow** [comment]
So, as we were chatting, I don't understand how an external script (not transpiled nor using Fuse) can access "pack" as there are no `pack.js` file.
Also, the test-repo is still giving `undefined` after `node fuse` - `node test`; I am afraid I miss something on the resolution.

**Comment by devmondo** [comment]
@eddow your package output should be used as npm link on mac or use `customModules` fuse feature if u r on windows as there is a problem with symlink on windows. all of this is required only for local testing!
if you bundle your project after i added the fix and publish it to npm it should work.

let me know if you need more details, i still have a doubt that you are not acquainted with NPM package publishing, so excuse my assumption :)

**Comment by eddow** [comment]
I think there is a real misunderstanding on what to achieve.
If a file touches its `module.export` and set a value in there, there is no question of symlimk.
If a file.js sets `module.exports = { test: 42 };`, it will export a test-value of 42 - under mac, windows or whatever.
Here, the bundle file only exports `{ FuseBox: [Object] }`

I tried to publish a little library : https://www.npmjs.com/package/ts-json-schema-decorator - but it needs a loader.js to unpack the exports behind fuse

**Comment by eddow** [comment]
okokokok - I understood by looking at the loaderAPI : it was indeed in the 'global' configuration; @nchanged was right and I misunderstood the meaning of "global".
The "global" configuration indeed doesn't modify the global variable (global/window) but the global exports of the bundle - I look more but I reached some results already.

**Comment by eddow** [comment]
So, after readings and testing, I understand better now the logic under "globals".
I still see a little problem though, in how the configuration sometimes writes in the global object (in browser), sometimes in the exports (in node)
If someone wants to make a library, the library is to be used without knowledge of the bundler used to build that library - so, the one who `require` the bundle shouldn't have even to know about fuse and still have his exported values.

Now, the "module.exports" possibility is far from specific to node - someone ignorant of fuse might use browserify to bundle his application that uses the library.
Someone who makes a libray doesn't always intend to make a jQuery and wish not to pollute the global object ;-)

I think that this line (/src/loader/LoaderAPI.ts:58) `__root__ = !$isBrowser `[...]` ? module.exports : __root__;` should be reviewed to take into considerations the simple case of existence of `module.exports` instead of the browser-sideness of the execution - or even get the clue on the host system like most do (I c/p here a common library exposing entry-point)

```
(function (global) {
    // AMD support
    if (typeof define === 'function' && define.amd) {
        define(function () { return MyModule; });
    // CommonJS and Node.js module support.
    } else if (typeof exports !== 'undefined') {
        // Support Node.js specific `module.exports` (which can be a function)
        if (typeof module !== 'undefined' && module.exports) {
            exports = module.exports = MyModule;
        }
        // But always support CommonJS module 1.1.1 spec (`exports` cannot be a function)
        exports.MyModule = MyModule;
    } else {
        global.MyModule = MyModule;
    }
})(this);
```

And then, after, in the doc, I really had the first fast impression that `globals` was just about the global variable :"> The name might be a bit misleading

**Comment by devmondo** [comment]
@eddow check the new [npm package seed](https://github.com/fuse-box/fuse-box-npm-package-seed) we have

**Comment by eddow** [comment]
That seed is a pretty good idea.
Now, I got bad news ... it doesn't seem to work ...

I git-cloned `fuse-box-npm-package-seed` in the `node_modules` of an empty project (of course `npm install` and `node fuse`) and wrote a test `index.js` :
```
console.dir(Object.keys(require('fuse-box-npm-package-seed')));
```
 The result is how I expected somehow : `[ 'FuseBox' ]`

**Comment by devmondo** [comment]
@eddow, u have to clone it, and npm link it then in your other project you can use it. or publish it online and install it.

it really works, we have at least 10  shared libs like this on our team :)

**Comment by eddow** [comment]
Ok, could you publish it then? or should I?
note: I see in the package.json that fuse-box is in the dependencies - I understand why it is in the dev-dependencies but I would make a test without dependencies to export a const string

**Comment by devmondo** [comment]
@eddow you can publish it to test it.

FuseBox is there because it is a seed project so people can run it, bundle it :)

**Comment by devmondo** [comment]
oh crap, I see what u mean, fixed and pushed, thank you :)

**Comment by eddow** [comment]
https://www.npmjs.com/package/fuse-box-npm-package-seed
https://github.com/eddow/fuse-exports-bug
The file test-npm contains `console.dir(Object.keys(require('fuse-box-npm-package-seed')));` (with `npm install` after `git pull`)

And desperately the same result : `[ FuseBox ]`

Please try,
```
git clone https://github.com/eddow/fuse-exports-bug.git
cd fuse-exports-bug
npm install
node test-npm
```

**Comment by devmondo** [comment]
@eddow thank you very much for your patience, I think you helped us discovering a bug :) it seems that fuse can't find the entry file of your npm package if the `main` property in `package.json` for that package is not pointing to an entry file in the root. 

so this wont work for now` "main":"./dist/index.js"` but this works ` "main":"./index.js"` .
so for now if your bundle output goes to package root instead of `dist` it will work!

just one note, are you using windows or mac ? 

thank you again for your help on this, and we shall fix it ASAP!

**Comment by nchanged** [comment]
Sorry, that was closed automatically ;-)
I guess we could do a beta to test it right?

**Comment by nchanged** [comment]
Please. verify it with `fuse-box@2.1.0-beta.1`

**Comment by devmondo** [comment]
@eddow, could you please try `npm install fuse-box@2.1.0-beta.1` and let us know :)

**Comment by eddow** [comment]
So, I made some tests with no luck yet.
What I did :
- In `fuse-box-npm-package-seed`:
```
npm install [...-beta]
rm -please cache+dist
node fuse
npm publish
```
- in `fuse-exports-bug`:
```
npm install fuse-box-npm-package-seed@1.0.1
node test-npm
```

I got the annoying usual `[ 'FuseBox' ]` (reminder: it's the export's object keys, it means only `FuseBox` is exported)

I should give you the access to the fuse-box-npm-package-seed npm package : I don't know how this work, that's why I proposed you to publish it :p - so that you can run this test cycle by yourself

**Comment by nchanged** [comment]
@eddow I will look into this bug ASAP, I know it's origin.

**Comment by nchanged** [comment]
Should be fixed in here `fuse-box@2.1.0-beta.2`

**Comment by devmondo** [comment]
i confirm on my side it works :)

**Comment by tomitrescak** [comment]
Guys, I cannot make this work.
When I use the fuse seed I am getting error that "default" package already exists.
When I add `package: { name: 'my-package' }` to Fuse.init, this error disappears but another appears `​​Error: Failed: "Package not found default"​​`

Any idea here? Thanks

**Comment by tomitrescak** [comment]
And when I try to put the instruction as `index.js` instead of `> index.js` I am getting error: `SyntaxError: The string did not match the expected pattern.` I also tried `+ index.js` to no avail.

**Comment by clitetailor** [comment]
Me too, how to build target node?!

**Comment by clitetailor** [comment]
This is such annoying because we want to export the lib toward node and receive FuseBox instance! Is there any clear documentation on this problem?!

**Comment by clitetailor** [comment]
Actually `.instructions(`> index.js`)` fixes the error to me. Wonder why it doesn't work with `.instructions(`~ index.js`)`

**Comment by clitetailor** [comment]
It seems like i mistake between `~ index.js` and `> [index.js]` sorry for this! 🤣
