### ISSUE TITLE
__rest helper missing in TypeScriptHelpers plugin

### ISSUE THREAD

**Issue by guillaume86** [fuse-box/fuse-box#523]
It would be nice to have this one as well :)

**Comment by devmondo** [comment]
@guillaume86, we are thinking of deprecating this plugin, as with Typescript 2.2 and higher u dont need this anymore, just install TSLib https://github.com/Microsoft/tslib

**Comment by guillaume86** [comment]
Thanks it did the trick (don't know why it wouldn't work earlier today...).

**Comment by devmondo** [comment]
maybe cache :)
