### ISSUE TITLE
If bundle name contains dot, no extension will be added in output file

### ISSUE THREAD

**Issue by JiDai** [fuse-box/fuse-box#525]
Hi,

```
const fuse = FuseBox.init({
    homeDir: "src",
    output: "dist/$name.js",
});
fuse.bundle("my.app")
    .instructions(`>app.tsx`);

fuse.run()
```

Will generate a `dist/my.app` file instead of `dist/my.app.js`

**Comment by nchanged** [comment]
That's not a bug, but expected behavior.  FuseBox thinks that you set an extension

**Comment by JiDai** [comment]
Ok, I expected there will be an extension because I put `.js` in output setting

**Comment by devmondo** [comment]
will close this for now, let us know otherwise :)
