### ISSUE TITLE
Stop method on fuse.run

### ISSUE THREAD

**Issue by fullc0ntr0l** [fuse-box/fuse-box#530]
When I'm clossing electron window, fuse.run() is still there and running. How I would stop it inside this promise? Can't find anything inside docs. Can we have some featured methods?

> fuse.run().then((bundle) => {
  if (electron) {
    const electronWindow = spawn('${__dirname}/node_modules/electron/cli.js', ['electron.js']);
    electronWindow.on('close', (code) => {
      console.log(code); // How I would stop bundle here?
    })
  }
});

**Comment by devmondo** [comment]
we will solve this, but for now, you can do `process.exit() ` :)

**Comment by devmondo** [comment]
This is supposed to be solved in latest, let us know if it does not.
