### ISSUE TITLE
Importing a node_module with imports in JS

### ISSUE THREAD

**Issue by Inlustra** [fuse-box/fuse-box#531]
To explain the issue, I've created a repository with an example package that causes the issue at: 
https://github.com/Inlustra/fusebox-ionic-import-bug-test

**The issue:**
Importing the @ionic-native/facebook module causes an `Uncaught SyntaxError: Unexpected token import` when using it in the browser.

The cause for this is that the module itself imports other files: 
```
FuseBox.pkg("@ionic-native/facebook", {}, function(___scope___){
___scope___.file("index.js", function(exports, require, module, __filename, __dirname){

var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
import { Injectable } from '@angular/core';  <---------- This import is not replaced.
import { Cordova, Plugin, IonicNativePlugin } from '@ionic-native/core';
/**
```

How do you get around this?

**Comment by devmondo** [comment]
@Inlustra , that is because the code above is not transpiled :)

**Comment by devmondo** [comment]
you need to use Typescript or babel plugins to compile your code to es5
http://fuse-box.org/plugins/babelplugin or
http://fuse-box.org/page/typescript

**Comment by Inlustra** [comment]
@devmondo Thanks for the swift response! 

For context, this using ionic, Webpack was handling the compilation automatically and I guess I haven't really understood how to easily do this with fuse-box.

Is it safe to say then that I would need to compile the modules manually using typescript before going through fusebox?

**Comment by devmondo** [comment]
@Inlustra , u r welcome :) all bundlers need to transpile something, in your case, it is really simple, you have es5 code that browser don't understand (import statement) so u need to plug in a transpiler. 

i it is really simple, check our ionic seed https://github.com/fuse-box/fuse-box-ionic2-seed

**Comment by devmondo** [comment]
oh, and just to make sure, i was clear, fusebox has typescript support built in, you just need to set your typescript config if you want :)

**Comment by devmondo** [comment]
by the way, your fuse.js looks fine, try to clear `.fusebox` cache folder and rebundle.

**Comment by devmondo** [comment]
also, just so you would know, we are going to auto transpile `import` statements in the near future for you, stay tuned for awesome new enhancements coming to a cinema near you :)

**Comment by Inlustra** [comment]
@devmondo Hmm, I've tried removing the .fusebox folder to no avail. Is there a way I can get more detailed logging of the typescript output other than: http://fuse-box.org/page/configuration#debug-and-log ?

The output was:
```
app ->

  → Typescript config:  /tsconfig.json
└── default (1 files,  495 Bytes)
      main.js
└── fusebox-hot-reload (1 files) 1.8 kB
└── fusebox-websocket (1 files) 2.9 kB
└── events (1 files) 9.8 kB
└── @ionic-native/facebook (1 files) 14.4 kB

    Size: 29.3 kB in 344ms
```

Again thanks for taking the time!
As for the new features; awesome, I look forward to ditching Webpack!

**Comment by devmondo** [comment]
@Inlustra, please don't give up, we will help you till it works :)

i downloaded your sample and found out many issues
* Your `tsconfig` is not set to ` "module": "commonjs",` and ` "target": "es6" `
* The `@ionic-native/facebook` has es6 code inside of it!!! and Typescript won't reach it, this is why we add babel plugin like this to fix it `BabelPlugin({limit2project: false})`
* you don't have any of the following  required libs installed
```
"@angular/core": "^4.1.2",
    "@ionic-native/core": "^3.8.0",
    "@ionic-native/facebook": "^3.8.0",
    "rxjs": "^5.4.0"
```
* you have some syntax errors in your `fuse.js`

after fixing all of those, I ran the bundling and all passed :)
here is a zip file containing the result just do `npm install` then  `node fuse.js` and all will work fine 
https://ufile.io/pu0w6

**Comment by Inlustra** [comment]
@devmondo You put me to shame! 

I purposefully didn't add the required libs rather to just demonstrate the lack of transpilation :) 

Perhaps this is something that could be added to the https://github.com/fuse-box/fuse-box-ionic2-seed ?
I think all of the @ionic-native packages will likely have the same issue, when I get a moment I could possibly put in a pull-request even if it's just to add it to the readme :)

Awesome thanks so much, looking forward to seeing the potential in fuse-box! :)

**Comment by devmondo** [comment]
@Inlustra  awesome man:) we are soo happy that u r feeling better with fuse.

please don't shy from doing your PR we need your help :)
