### ISSUE TITLE
Element imports whole VueJS library whenever a module is imported on demand

### ISSUE THREAD

**Issue by marko-mlinarevic** [fuse-box/fuse-box#537]
in my app file I have

```
import './style/main.scss'
import * as Vue from 'vue/dist/vue.common.js'
import * as Vuex from 'vuex'
import * as axios from 'axios'
import * as element from 'element-ui'
import 'element-ui/lib/theme-default/index.css'
import * as App from './components/App.vue'
```

and this is my fuse.js

```
const {FuseBox, VuePlugin, HTMLPlugin, SassPlugin, CSSPlugin, WebIndexPlugin, Sparky, JSONPlugin, BabelPlugin, CSSResourcePlugin} = require("fuse-box");

const fuse = FuseBox.init({
    homeDir: "./src",
    output: "dist/$name.js",
    plugins: [
        JSONPlugin(),
        VuePlugin(),
        BabelPlugin(),
        [/node_modules.*\.js$/,
            BabelPlugin()
        ],
        [
            /node_modules.*\.css$/,
            CSSResourcePlugin({inline: true}),
            CSSPlugin()
        ],
        [
            SassPlugin({importer: true}),
            CSSResourcePlugin(),
            CSSPlugin({group: "app.css", outFile: "./dist/app.css"})
        ],
        HTMLPlugin({useDefault: false}),
        WebIndexPlugin({template: "./src/index.html"})
    ],
});

fuse.dev();

fuse.bundle("app.js")
    .cache(false)
    .plugin(
        CSSResourcePlugin(),
        CSSPlugin()
    )
    .plugin(
        BabelPlugin()
    )
    .instructions("> index.ts + components/**")
    .watch();

fuse.run();

Sparky.task("default", () => {
        return Sparky.watch("./assets", {base: "./src"})
            .dest("./dist");
    }
);
```
There was a same problem with webpack and they said in that post

https://github.com/ElemeFE/element/issues/2553

that the solution is using "webpack commonsChunk" is there something like that for fuse.js

**Comment by devmondo** [comment]
@marko-mlinarevic  u can try code splitting http://fuse-box.org/page/code-splitting
it is the equilibrant of webpack's common chunk

**Comment by nchanged** [comment]
I don't think it's related to code splitting. Does the Vue dist contain everything in the first place?

**Comment by devmondo** [comment]
@nchanged he is using `import * as element from 'element-ui'` and if you check it here https://github.com/ElemeFE/element/blob/dev/src/index.js you would see why this is happening.

So, I think he needs to split his code, maybe i am wrong :)

**Comment by nchanged** [comment]
@devmondo code splitting works on your default project only. There is something else we need to do

**Comment by devmondo** [comment]
@nchanged  u r correct, but that is why webpack advised him to do chunking, the way this lib is structured is cumbersome as it is. so we indeed we need a solution

**Comment by nchanged** [comment]
@marko-mlinarevic so webpack solved by NOT bundling some files from that repository?

**Comment by marko-mlinarevic** [comment]
@nchanged yes

**Comment by nchanged** [comment]
@marko-mlinarevic this has to wait for 2.1.0+ where tree shaking will be introduced. It will remove these modules automatically. Keep tracking this issue.

**Comment by marko-mlinarevic** [comment]
Will do.. Looking foward to it

**Comment by devmondo** [comment]
The new release is out with awesome Vue support it should fix this.

will close this, for now, let us know otherwise :)
