### ISSUE TITLE
Shimming issue when using a separate vendor bundle

### ISSUE THREAD

**Issue by guillaume86** [fuse-box/fuse-box#538]
I'm using shimming for jQuery and including it in my vendor bundle:

```js
fuse.bundle("vendor")
    .shim({
      "jquery": {
        source: "node_modules/jquery/dist/jquery.js",
        exports: "jQuery",
      }
    })
    .instructions(`~ application.tsx`);
```

It works fine with the production bundles, but in dev mode (hmr + watch), it works at first launch then fails after a hot reload occurs (after I change a source file). Once it has failed, the only solution is to clear the cache before starting the server again.

I just get an error `Uncaught Package not found jquery` in the browser when it fails.

A workaround for the moment is to add the shims to both bundles (vendor + app) in dev mode.

Note: maybe the issue is more an instructions problem, when I first specified the shims in the common config, the `!> [application.tsx]` instructions still included the shims at the top of the app bundle (so they were in both bundles), that's the reason I switched to adding the shims to the vendor bundle only.

**Comment by nchanged** [comment]
Thanks for reporting! We will get to it soon.

**Comment by nchanged** [comment]
I can't seem to reproduce your issue. Could you check [this](https://github.com/fuse-box/jquery-shimming-example) repository please?

**Comment by guillaume86** [comment]
Ha, so there must be something else causing this. I'm trying to reproduce the minimal case and get back to you.

**Comment by guillaume86** [comment]
I didn't manage to reproduce in the minimal repo it's weird, but I did fixed my issue by removing `.watch().hmr()` from my vendor bundle!

Sorry for the waste of time...

**Comment by nchanged** [comment]
@guillaume86 no worries, I wonder is `watch` is killing it. Does it work with `hmr()` in place?

**Comment by guillaume86** [comment]
So it gets weirder... I just restarted the dev server and I have the jquery not found again.

The issue was just delayed it seems:

1. with .hmr().watch() on vendor
- clean .fusebox
- start server
- open in browser OK
- change file
- browser fails (via HMR)
- restart server
- open in browser fails

2. without .hmr().watch() on vendor
- clean .fusebox
- start server
- open in browser OK
- change file
- HMR in browser OK
- reopening the page OK
- restart server
- open in browser fails

**Comment by nchanged** [comment]
So odd.. can't reproduce any of that ;-((
Doesn't work at all for you?

**Comment by devmondo** [comment]
i confirm on my side it works now!

@guillaume86 
* upgrade to latest beta
* make sure delete cache 
* make sure to delete dist folder
* show us your full config :)

**Comment by guillaume86** [comment]
I tried the latest beta with the usual clearing everything and still has the issue, it's not a dealbreaker as I just need to include the shims in the app bundle in dev mode to workaround, the dist/ bundles are ok.

Here's my config for reference (extracted the revelant parts from my gulpfile):

```js
// @ts-check
const httpProxy = require("http-proxy");

// help fuse-box figure out the project path
process.env.PROJECT_ROOT = __dirname;
const fsbx = require("fuse-box");

// paths
const srcPath = 'src/';
const devPath = '.fusebox/dev/';

// fusebox config
const alias = {
  "src": "~/",
  "react-bootstrap-custom": "~/lib/react-bootstrap-custom",
  "lodash-custom": "~/lib/lodash-custom",
  "moment-custom": "~/lib/moment-custom",
  "animated-dom": "animated/lib/targets/react-dom",
};

const shim = {
  "jquery": {
    source: "node_modules/jquery/dist/jquery.js",
    exports: "jQuery",
  },
  "modernizr": {
    source: "assets/plugins/modernizr.custom.js",
    exports: "Modernizr",
  },
};

const configureProxy = (server) => {
  const package = require('./package.json');
  if (!package.proxy) return;

  // must do this to be after the fuse handler
  process.nextTick(() => {  
    const app = server.httpServer.app;
    const proxy = httpProxy.createProxyServer({});

    // Listen for the `error` event on `proxy`.
    proxy.on('error', function (err, req, res) {
      res.writeHead(500, {
        'Content-Type': 'text/plain'
      });
      res.end('Something went wrong: ' + err);
    });

    app.use(function (req, res) {
      proxy.web(req, res, {
        target: package.proxy,
        changeOrigin: true
      });
    });
  });
};

const Development = () => {

  const fuse = fsbx.FuseBox.init({
    homeDir: srcPath,
    tsConfig : srcPath + "tsconfig.json",
    output: devPath + "$name.js",
    cache: true,
    sourceMaps: true,
    plugins:[
      fsbx.JSONPlugin(),
      [
        fsbx.LESSPlugin(), 
        fsbx.CSSPlugin()
      ],
    ],
    alias,
  });

  fuse.dev({ 
    root: devPath, 
    port : 3000,
  }, configureProxy);

  const vendor = fuse.bundle("vendor")
    .shim(shim)
    .instructions(`~ application.tsx`);

  const app = fuse.bundle("app")
    //.shim(shim)
    .instructions("!> [application.tsx]");

  //vendor.hmr().watch();
  app.hmr().watch();

  return fuse.run();
}
```

**Comment by guillaume86** [comment]
@nchanged would it help if I sent you the vendor.js from my dev folder? or do you need to look at something in the app.js too (I can look for you but not share it unfortunately).

**Comment by nchanged** [comment]
It would help if you managed to reproduce the issue  in a repository ;-)

**Comment by guillaume86** [comment]
I tried from your example repo but didn't manage, I don't know what's different in my ~300 .tsx files project...

I diffed the broken and working vendor.js files and here's what I found:

![image](https://cloud.githubusercontent.com/assets/441850/26145813/2c6a1a6a-3aee-11e7-8cdf-f399ba739a1e.png)

**Comment by devmondo** [comment]
@guillaume86 any news on this? did u try with the latest fuse ?
