### ISSUE TITLE
How to generate an UMD library?

### ISSUE THREAD

**Issue by josdejong** [fuse-box/fuse-box#540]
I'm trying to create a library that can be used both in node.js and the browser, a standalone UMD library. With some puzzling with the configuration of package name and globals I managed to generate a bundle that can be used from node.js, but I can't manage to get the library working in a browser by exposing it on `window`. This is my configuration:

```js
const { FuseBox, BabelPlugin } = require('fuse-box')

const fuse = FuseBox.init({
    homeDir: './src',
    output: './dist/$name.js',
    package: {
        name: 'myLibrary',
        main: 'src/index.js'
    },
    globals: { 
        myLibrary: '*' 
    },
    plugins: [
        BabelPlugin({
            presets: ['es2015']
        })
    ]
});

fuse.bundle('myLibrary')
    .instructions(`> index.js`)

fuse.run()
```

In node.js I can use the library like:
```js
const myLibrary = require('./dist/myLibrary')
console.log(myLibrary.myFunction)
```
In the browser I try:
```html
<!DOCTYPE html>
<html>
<head>
  <script src="./dist/myLibrary.js"></script>
</head>
<body>

<script>
    console.log(myLibrary.myFunction) // doesn't work
</script>

</body>
</html>
```
But `myLibrary` is not exposed on `window`. Any idea what I'm overlooking? Following [the docs](http://fuse-box.org/page/configuration#global-variables) I expected the globals to do the trick.

I saw #522 which may be related, I tried `fuse-box@2.1.0-beta.1` but no luck.

**Comment by nchanged** [comment]
Hi!
I think your main file is wrong
You homDir points to `src`

```js
 main: 'src/index.js'
```
Could you try it without src?

**Comment by josdejong** [comment]
Thanks for your fast reply. I tried `main: 'index.js'` and `main: './index.js'`, both no success in the browser (and all work fine in node.js)

**Comment by nchanged** [comment]
Could you copy paste the last bit of your bundle? It can find by searching for `FuseBox.expose`

I will check the functionality later on today, to verify it.

**Comment by josdejong** [comment]
I think you mean this part of the bundle:

```js
FuseBox.expose([{"alias":"*","pkg":"myLibrary/index.js"}]);
FuseBox.main("myLibrary/index.js");
FuseBox.defaultPackageName = "myLibrary";
```

**Comment by nchanged** [comment]
@josdejong thanks a lot for your patience. I confirm the bug related to the recent change to the [root](https://github.com/fuse-box/fuse-box/blob/master/src/loader/LoaderAPI.ts#L58)

It points to an external FuseBox reference where all modules are stored. That will be fixed today/tomorrow.

**Comment by josdejong** [comment]
That's good news, thanks for all your work!

**Comment by aretecode** [comment]
@josdejong https://twitter.com/_developit/status/844260377546440705

**Comment by josdejong** [comment]
@aretecode I don't use AMD myself but when publishing a library I think it's still relevant to have it working in AMD too.

**Comment by nchanged** [comment]
@josdejong false alarm!
After an investigation, it turns out you are using globals wrongly.  By setting `*` you are actualy exposing every single **exported** object to window. To achieve want you want, please change `*` to any suitable name.

I have prepared a [github](https://github.com/fuse-box/fuse-box-globals-example) example and updated the [docs](http://fuse-box.org/page/configuration#global-variables) to make it clear.

I hope this will solve your problem

**Comment by josdejong** [comment]
Changing `myLibrary: '*'` to `myLibrary: myLibrary` indeed solves the issue in the browser, but that gave a problem with node.js: you then have to load the library like `const { myLibrary } = require('myLibrary')` instead of `const myLibrary = require('myLibrary')`. I found the configuration I'm looking for by using `default` global and removing the package name:

```js
const { FuseBox, BabelPlugin } = require('fuse-box')

const fuse = FuseBox.init({
    homeDir: './src',
    output: './dist/$name.js',
    package: {
        // !no package name, use default!
        main: 'index.js'
    },
    globals: {
        default: 'myLibrary'
    },
    plugins: [
        BabelPlugin({
            presets: ['es2015']
        })
    ]
});

fuse.bundle('myLibrary')
    .instructions(`> index.js`)

fuse.run()
```

Thanks for your help and for clarifying the docs! I still see the sentence _"In order to expose your package, a bundle must have a package name"_, which apparently is not the case? I had to *remove* it to get my library exposed correctly.

**Comment by nchanged** [comment]
@josdejong indeed that is not the case, I will fix that ;-)
Closing the issue now, feel free to re-open elsewise ;-)
