### ISSUE TITLE
Vue import are not bundled

### ISSUE THREAD

**Issue by eddow** [fuse-box/fuse-box#542]
When a `file.vue` imports a module (local or npm), this one is not included in the result bundle, resulting in an `Error: Cannot find module`

https://github.com/eddow/eddow-bug-expo/tree/vue-import

**Comment by devmondo** [comment]
it is `import * as testImp from './testImp'` not `import * as testImp from 'testImp'` as it is relative file and not node module.

will close this for now, feel free to open otherwise :)

**Comment by eddow** [comment]
The typo is corrected - the bug is still there

**Comment by nchanged** [comment]
@eddow you think the latest implementation fixes it? 
https://github.com/fuse-box/fuse-box/blob/master/src/plugins/VuePlugin.ts#L59

**Comment by eddow** [comment]
Is this change already deployed in 2.2.0?
I just tried with the little bug-expo after upgrading fuse-box, it didn't made a change there.

**Comment by nchanged** [comment]
have you tried with the latest beta?

**Comment by eddow** [comment]
Okay, with the beta.12, I first had to solve `Error: Cannot find module 'acorn'`.
Once solved, the test unfortunately let the results unchanged.
I had a peek inside of the last modifications of VuePlugin.js and we effectively have the last version in beta.12. Looking around, I saw no modification that might have corrected it so far indeed.

**Comment by eddow** [comment]
So, as the bug is still not resolved, I investigated a bit (I for now have to maintain a library files as importing files from a `.vue` source does not make the import bundled)

In [File.consume](https://github.com/fuse-box/fuse-box/blob/4e519489694f00a8b25d0aab838267d480ca6ea3/src/core/File.ts#L387), we can see that `.ts`, `.js` and other files have different treatment. "Other" files have a treatment through the plugin - and this treatment occurs in a promise that is [queued](https://github.com/fuse-box/fuse-box/blob/4e519489694f00a8b25d0aab838267d480ca6ea3/src/core/File.ts#L265)
Therefore, the dependencies of a `.vue` file, that will be used [right after](https://github.com/fuse-box/fuse-box/blob/4e519489694f00a8b25d0aab838267d480ca6ea3/src/core/ModuleCollection.ts#L383) the file is `consume`-d will be empty as this will happen before the promise is effected, the plugin applied and the `.vue` file analysed

**Comment by nchanged** [comment]
Are we still seeing it?

**Comment by eddow** [comment]
I tried with the last version from git and it is solved !
Thanks a lot! I will finally be able to remove and stop upkeeping my redundant-lib-list-file :)

**Comment by eddow** [comment]
Okay, this was weird - I made a test with one library import and it worked, and I was quick to conclude it was solved ...
Unfortnately, it is the only one that was working (beeing imported even if it was only referenced in `*.vue` files) - all the remaining still make problems...

**Comment by nchanged** [comment]
You think u can help solving it?

**Comment by eddow** [comment]
I would have to dive back into it as things might have changed - beside I cannot promise I do this soon, it can be quite time consuming ...

**Comment by TombolaShepless** [comment]
@eddow #832

**Comment by Shepless** [comment]
@nchanged this can be closed with next release

**Comment by devmondo** [comment]
the new release is out :) try it and let us know.
