### ISSUE TITLE
modulesFolder loses files

### ISSUE THREAD

**Issue by aretecode** [fuse-box/fuse-box#545]
https://github.com/aretecode/fuse-flop

- files are in the bundle
- running the code says the request cannot be found, even though the files are in the bundle

**Comment by nchanged** [comment]
@aretecode you can't require files outside of a modules homeDir` here https://github.com/aretecode/fuse-flop/blob/master/example/modules/eh/index.js#L1

**Comment by aretecode** [comment]
@nchanged why? it *includes my files in the output bundle* https://github.com/aretecode/fuse-flop/raw/master/Screen%20Shot%202017-05-17%20at%202.35.12%20AM.png

**Comment by nchanged** [comment]
@aretecode it won't work =) that's against fusebox concepts
