### ISSUE TITLE
Add ability to pass chokidar options

### ISSUE THREAD

**Issue by whitecolor** [fuse-box/fuse-box#547]
Add ability to pass chokidar options.

**Comment by nchanged** [comment]
Be more specific,  please where and why?

**Comment by whitecolor** [comment]
For example `usePolling` is needed for watching docker attached volume (on docker for windows), and other SMB attached volumes would require the same. I think that probably other options maybe needed as well in some scenarios.

But if you wan't to abastract this layer from chokidar, well this issue maybe about adding `polling` option to watch.

**Comment by nchanged** [comment]
Have you tried that one? http://fuse-box.org/page/sparky#watch
you can pass options there. `watch` on a bundle works differently

**Comment by whitecolor** [comment]
@nchanged it is not clear for me from docs what it is about.

I'm talking about watching sources for bundling, in such config

```ts
const fuse = FuseBox.init({
  homeDir: 'client',
  output: 'build/app.js'
})

fuse
  .dev({
    root: '.',
    port  
  }, (server) => {
    server.httpServer.app.use(express.static(join(__dirname)));
    server.httpServer.app.get('*', function (req: any, res: any) {      
      res.sendFile(join(__dirname, 'index.html'));
    })
  })

fuse.bundle('app.js')
  .instructions(`> app.ts`)
  .hmr()
  .watch()

fuse.run()
```

**Comment by nchanged** [comment]
## Sparky
Sparky is a Task-Runner like Gulp or Grunt, but what sets it apart is that it is built on top of FuseBox technology. This means that it takes benefit of the whole architecture behind, This includes an ability to use FuseBox plugins and many other things.
----

`.watch()` on bundle works differently. But with sparky you can pass anything you like there and launch a process manually

```js
const app = fuse.bundle('app.js')
  .instructions(`> app.ts`)
  .hmr()

Sparky.task("default", [], () => {
   Sparky.watch("your glob", {/* options here*/})
     .file("*", file => {
         app.exec()
     })
})

});
```

**Comment by devmondo** [comment]
@whitecolor,
if you use the approach above, you can pass whatever options to `chokidar` using `sparky` `watch`

the concept is simple, with ` app.exec()` you basically manually kick bundling, which will achieve what you want.

**Comment by whitecolor** [comment]
@nchanged why not add such ability to :

```
fuse.bundle('app.js')
  .instructions(`> app.ts`)
  .hmr()
  .watch("your glob", {/* options here*/})
```

**Comment by nchanged** [comment]
@whitecolor because a producer can have many bundles in it. In fact `run()` initiates everything

**Comment by whitecolor** [comment]
> because a producer can have many bundles in it. In fact run() initiates everything

And what? Not sure why I understand why you can't:

```ts
fuse.bundle('app.js')
  .instructions(`> app.ts`)
  .hmr()
 .watch() // <-- pass watch options here
```

**Comment by nchanged** [comment]
@whitecolor because one chokidar instance is responsible to all the bundles in the producer. That's why

**Comment by whitecolor** [comment]
Then need to add this ability to pass this options in other place, without using sparkly, not to complicate config.

```ts
const fuse = FuseBox.init({
  homeDir: 'client',
  output: 'build/app.js'
})
```

or here:
```ts
fuse
  .dev({
    root: '.',
    port  
  },
```

**Comment by nchanged** [comment]
It can be in `run()` options yes.

**Comment by aretecode** [comment]
@devmondo isn't this added now? https://github.com/fuse-box/fuse-box/pull/494

**Comment by devmondo** [comment]
@aretecode yes, thank you for the reminder :) will close this now.
