### ISSUE TITLE
modulesFolder import empty

### ISSUE THREAD

**Issue by jperezdavinchi** [fuse-box/fuse-box#548]
Good afternoon,
I hope someone could help us.
We are developing a web framework and we would like to import it inside the project using the npm name (for developing purposes)

We have the project divided into 2 parts, each one with his own fuse-box bundle:
- dev: Playground, with```homeDir``` to the root of the project and with ```modulesFolder``` to ```dev/modules```.
- src: The source, with ```homeDir``` to  ```src```, with ```package``` configuration and ```output``` to ```dev/modules/@haztivity/core``` .

When we execute ```fuse``` the ```@haztivity/core``` is generated correctly by ```fuseCore``` but it appears in ```fuseDev``` with a different weight and when we do the import of```@haztivity/core``` fuse-box found the module but the object is empty

## Project structure
```
project-root
     |- dev
     |   |- course
     |   |   |- sco
     |   |       |- index.ts//import @haztivity/core
     |   |- modules
     |       |- @haztivity
     |           |- core
     |- src
     |   |- /files/
     |   |- index.ts
     |- fuse.js
```
## fuse.js
```typescript
const {FuseBox,SassPlugin,CSSPlugin,UglifyJSPlugin,TypeScriptHelpers} = require("fuse-box");
const {PugPlugin} = require("fusebox-pug-plugin");
const fuseCore = FuseBox.init(
    {
        homeDir: "src",
        output: "dev/modules/@haztivity/core/$name.js",
        cache:false,
        package:{
            name:"@haztivity/core",
            main:"index.ts"
        }
    }
);
fuseCore.bundle("index")
        .instructions(`index.ts`)//.instructions(`>index.ts`)
        .watch("src/**");
fuseCore.run();
const fuseDev = FuseBox.init(
    {
        homeDir: ".",
        output:"dev/$name.js",
        cache: false,
        log: true,
        debug: true,
        tsConfig:"dev/course/tsconfig.json",
        modulesFolder:"dev/modules",
        plugins: [
            [
                SassPlugin(
                    {
                        outputStyle: 'expanded',
                        importer: true
                    }
                ), CSSPlugin()
            ],
            CSSPlugin(),
            PugPlugin()
        ]
    }
);
fuseDev.dev(
    {
        root: "."
    }
);
fuseDev.bundle("sco")
       .instructions(`>dev/course/sco/index.ts`)
       .watch("dev&course/**");
fuseDev.run();
```
## Generation
![image](https://cloud.githubusercontent.com/assets/28526655/26216090/1f4c8e10-3c03-11e7-9783-b39c1c526eab.png)

## Import
![image](https://cloud.githubusercontent.com/assets/28526655/26215903/6650e348-3c02-11e7-9a42-689cd43e68fb.png)

We tested what append if we remove ```fuseCore``` and write in ```dev/modules/@haztivity/core/index.js```:
```javascript
module.exports = {
    test:"test"
}
```
and the import works
![image](https://cloud.githubusercontent.com/assets/28526655/26216480/8caac4c6-3c04-11e7-82c4-a069dbc456f9.png)

Could be some problem with the synchronization between ```fuseCore``` and ```fuseDev```?

**Comment by nchanged** [comment]
@jperezdavinchi Hi!
A warm welcome to the community!

We will solve your problem, no worries. But before that, it would be nice to have a test repository, it's a little hard to grasp at once what are you trying to achieve here.

* How are you requiring your submodules?  If you use the actual bundle - you should not use file exports from a virtual package explicitly (there is only 1 file)
 
* You package name is wrong. Because what you are trying to mimic here is a scoped repository. Therefore your name should be `haztivity-core` (or something like that). Please, read up [here](https://docs.npmjs.com/misc/scope) After you are ready with the package, you should put it under `haztivity/core` with package.json and `index.js` file.

* Try taking advantage here by tricking your dev environment with [aliases](http://fuse-box.org/page/configuration#alias)

**Comment by jperezdavinchi** [comment]
@nchanged Hi!
Thanks for the welcome and for your fast answer.
I created a branch for test [here](https://github.com/haztivity/core/tree/fusebox)

All the submodules are imported with```import {submodule} from "@haztivity/core"``` I never import files directly like ```import {submodule} from "@haztivity/core/somefile"```, but the exports in the core bundle are (inside src folder)
```typescript
export {Navigator,INavigatorPageData} from "./navigator/Navigator";
export * from "./di/decorators";
```
I tried also with aliases but the same happened and it took a lot of time to load the pages.

I'm going to change the package and try piping the core.

**Comment by nchanged** [comment]
@jperezdavinchi I will check it later, but what is wrong for sure, is your `@` in the name. 

`@` is used to identify a scoped package. So this should be renamed. You will use `@` when referring to your package though.

**Comment by aretecode** [comment]
https://github.com/fuse-box/fuse-box/issues/545

**Comment by jperezdavinchi** [comment]
Hi @aretecode!
I already saw that post, but my custom package is inside of the homedir of the devBundle, the ouput of the custom module is `"dev/modules/@haztivity/core/$name.js"` and the homedir of  the devBundle is "."

**Comment by jperezdavinchi** [comment]
Thank you for your patience, I finally found how to do this and it was pretty simple: remove `modulesFolder` and add the output of fuseCore to the html file.
```typescript
const {FuseBox,SassPlugin,CSSPlugin,UglifyJSPlugin,TypeScriptHelpers} = require("fuse-box");
const {PugPlugin} = require("fusebox-pug-plugin");
const fuseCore = FuseBox.init(
    {
        homeDir: "src",
        output: "dev/$name.js",
        package:{
            name:"@haztivity/core",
            main:"index.ts"
        },
        cache:false
    }
);
fuseCore.bundle("core")
        .instructions(`> index.ts`)
        .watch("src/**");
fuseCore.run();
const fuseDev = FuseBox.init(
    {
        homeDir: "dev",
        output:"dev/$name.js",
        cache: false,
        log: true,
        debug: true,
        tsConfig:"dev/course/tsconfig.json",
        plugins: [
            [
                SassPlugin(
                    {
                        outputStyle: 'expanded',
                        importer: true
                    }
                ), CSSPlugin()
            ],
            CSSPlugin(),
            PugPlugin()
        ]
    }
);
fuseDev.dev(
    {
        root: "dev"
    }
);
fuseDev.bundle("sco")
       .instructions(`>course/sco/index.ts`)
       .watch("dev/course/**");
fuseDev.run();
```
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Haztivity example</title>
    </head>
    <body>
        <main data-hz-app></main>
        <script src="../../core.js"></script>
        <script src="../../sco.js"></script>
    </body>
</html>
```
Thank you!

**Comment by serkon** [comment]
Could you try just add after first bundle below code. I think `const fuseDev` constant not need.

fuseCore.bundle("sco")
       .instructions(`>course/sco/index.ts`)
       .watch("dev/course/**");
