### ISSUE TITLE
bug with Node compression module and require

### ISSUE THREAD

**Issue by devmondo** [fuse-box/fuse-box#55]
wen i import `compression` module or if there is any module requires it, this is the error i get
```
var debug = require('debug')('compression')
                            ^

TypeError: require(...) is not a function
```

**Comment by nchanged** [comment]
Please, provide more details, can't reproduce

<img width="871" alt="screenshot 2017-01-01 21 15 56" src="https://cloud.githubusercontent.com/assets/1629088/21582604/8d9c0f2e-d067-11e6-8f89-13ec9f9a551d.png">

**Comment by devmondo** [comment]
i dont know how to offer more details, i am using Fuse with TypeScript Compiler, could it be the reason ?

also i went back to Fuse version `1.3.23` and problem does not exist

**Comment by devmondo** [comment]
same as in #54 this error goes away up till version `v1.3.33`

**Comment by nchanged** [comment]
i hope it's fixed in `1.3.38`

**Comment by devmondo** [comment]
not yet :)

**Comment by devmondo** [comment]
with `1.3.39` it is solved :)
