### ISSUE TITLE
Any migration path from angular-cli?

### ISSUE THREAD

**Issue by nth-commit** [fuse-box/fuse-box#552]
Has anyone been down this path?

Love angular-cli but it is painfully slow to build, compared to the couple of years I've had with JSPM. Would love to give FuseBox a try now.

**Comment by devmondo** [comment]
@nth-commit welcome to FuseBox :)
did you check this example https://github.com/fuse-box/angular2-example ? 
it so simple, fast and works :)

do you have any specific suggestions? we are opened ears :)

**Comment by Tenvan** [comment]
Hi,
this sample didn't work with current angular 4.

**Comment by devmondo** [comment]
@Tenvan check https://github.com/fuse-box/fuse-box/issues/324#issuecomment-302967564

**Comment by nth-commit** [comment]
@devmondo This is what I got stuck as well, thanks.

**Comment by JohnGalt1717** [comment]
Also it doesn't support server side pre-rendering.

**Comment by nchanged** [comment]
Well, you guys could poke angular so they could help us. It seems like the stuck with webpack.

**Comment by patrickmichalina** [comment]
@nth-commit I am working on a decent starter, but we will need to write some AOT/Lazy Loading plugins... Working on some of that now. Also, @JohnGalt1717, this starter is SSR by default:

https://github.com/patrickmichalina/fusebox-angular-universal-starter

**Comment by devmondo** [comment]
@patrickmichalina should we get more details about ur starter :)

**Comment by patrickmichalina** [comment]
@devmondo What do you mean good sir?

**Comment by devmondo** [comment]
Dear @patrickmichalina, in other words, should we use your starter above and close this thread :)

**Comment by patrickmichalina** [comment]
@devmondo Ahh ok I see. Well, the Angular CLI is a lot more substantial than what I have made so far. It includes and API, and Identity Server (coming soon). So its a bit more opinionated than the more generic Angular-CLI and associated tools.

Current shortcomings with my starter project: 
- Vert specific stack (express, angular-material, etc..)
- It hasn't been well tested on Windows
- AOT compilation is not working
- Quantum & Rollup are not being used for prod builds
- Could leverage newer features of FuseBox better
- It is geared toward server rendered apps, not client-only like most seeds

I like having a showcase fusebox-angular but could some more help :)

I think you can close this issue though, since it was more of an inquiry and kind of outside the scope of fuse-box bundler.

**Comment by devmondo** [comment]
@patrickmichalina thanks a lot for the details man.

fiar enough, also angular 5 is introducing new AOT compiler, so, I think we should have a plugin one day or something.

I also checked and your seed is already on fuse website, so, I think it is safe to close this for now :)

**Comment by patrickmichalina** [comment]
Preview menu :)
<img width="836" alt="screen shot 2018-05-11 at 7 32 21 pm" src="https://user-images.githubusercontent.com/6701211/39953990-0eef8536-5552-11e8-86a0-624f20d70be2.png">

**Comment by nchanged** [comment]
@patrickmichalina wow!!! That's terrific!!!! When it's ready we make a big announcement! Let me know if you need my help

**Comment by patrickmichalina** [comment]
@nchanged thanks, will do!

**Comment by patrickmichalina** [comment]
For anyone who wants to follow along with the status of this project:

https://github.com/patrickmichalina/fusing-angular-cli

**Comment by patrickmichalina** [comment]
Been making steady progress on this. Hopefully in the next few days will have a more complete release. But right now you can create an Angular Universal app via my CLI tool, with the most optimal build outputs. It also has Jest unit test support included.

**Comment by patrickmichalina** [comment]
I never quite finished this and with the imminent release of fusebox v4, it would need some tweaks! I may consider finishing it out though. The Angular team looks to be moving away from Webpack and using Bazel in Angular 9. This may end up being the answer for angular projects.
