### ISSUE TITLE
.watch doesn't detect file changes on a mounted volume in Docker for Windows

### ISSUE THREAD

**Issue by tobico** [fuse-box/fuse-box#553]
Docker for Windows (and also Docker for Mac) runs software inside of a Linux VM, with configurable volumes from the host system mounted in, so that your latest development code is accessible from the VM. 

When my assets are being compiled by an instance of FuseBox running inside of Docker, with the `.watch` option on, changes to files on the host system are not detected by FuseBox. With FuseBox running natively on the host system, the `.watch` command works as expected.

Is FuseBox using some kind of operating system events to detect file changes? I know many other development servers provide the option to use polling instead of OS events to watch files, for situations like this where the file change events don't get correctly sent through from a mounted file system. Is such an option available in FuseBox, or any other way I can get this working correctly?

**Comment by devmondo** [comment]
@tobico welcome :)

FuseBox uses `chokidar` under the hood, so it seems we need to add the ability to pass options for `chokidar` to use pooling. stay tuned, we are working on it :)

**Comment by nchanged** [comment]
http://fuse-box.org/page/development#chokidar-options

**Comment by nchanged** [comment]
Please test the beta.

**Comment by ryan-edge-ck** [comment]
Any updates on this issue?

**Comment by nchanged** [comment]
I think you can pass any options to chokidar in fuse.run

**Comment by devmondo** [comment]
yes we can since a while now.

**Comment by devmondo** [comment]
we will close this for now if the issue still persists let us know :)
