### ISSUE TITLE
Uncaught Package not found fusebox-hot-reload

### ISSUE THREAD

**Issue by dziamid** [fuse-box/fuse-box#559]
Importing a json file without JSONPlugin() produces this error message, which is hard to correlate to the actual problem. Would be great if error message were more descriptive so it is easier to introduce FuseBox to existing webpack-driven codebases.

**Comment by nchanged** [comment]
Yep, that happens in you get a syntax error

**Comment by dziamid** [comment]
So are you working to improve error handling or something? I tried running some of my webpack-driven codebases with fusebox and always got stuck with error and didn't have a clue how to fix it.

**Comment by devmondo** [comment]
@dziamid as a temporary solution, u can disable `HMR` and test your app to see if there is any syntax error and then enable it. usually `HMR` works with errors as it would be reported to you in the browser, but sometimes, there are those severe errors that would prevent it from working, we should improve that :)

**Comment by nchanged** [comment]
The solution is to clear the cache. (remove `.fuse-box` folder)

**Comment by nchanged** [comment]
Feel free to re-open, if it didn't helpl

**Comment by masaeedu** [comment]
So the approved solution is for users to go nuts trying to figure out the nonsensical error, arrive at this issue, then realize the issue has nothing to do with `fusebox-hot-reload`.

**Comment by nchanged** [comment]
@masaeedu are you still experiencing it?

**Comment by masaeedu** [comment]
@nchanged Yes. I fixed the missing import in my code that was causing the error, but I was still seeing the irrelevant `fusebox-hot-reload` error message yesterday.

**Comment by nchanged** [comment]
@masaeedu but there should be 2 stack traces, one about the missing imports and the other one whenever fuse has failed to update.

**Comment by tnurmi82** [comment]
Just wondering if has been improved since 2017?

In our project we were adding some code. At some point a '-' character was simply accidentally misplaced in code, effectively causing a syntax error. About an hour later the new code was being tried out for the first time, and we got this "Uncaught Package not found fusebox-hot-reload". Luckily it didn't take us too long to figure it out and fix the typo. But still, this is very annoying.

**Comment by nchanged** [comment]
there is a new version `4.0.1` that doesn't have this issue
