### ISSUE TITLE
setting package name seems to ignore babel plugin output

### ISSUE THREAD

**Issue by matthiasak** [fuse-box/fuse-box#56]
See the screenshots attached. It looks like when I set a package name, the stage-0 / babel process is being ignored.

![screenshot from 2017-01-01 09-41-23](https://cloud.githubusercontent.com/assets/900775/21581847/b87ba23c-d007-11e6-8e55-d3ca4a7cd15d.png)
![screenshot from 2017-01-01 09-44-31](https://cloud.githubusercontent.com/assets/900775/21581848/b87ce142-d007-11e6-9411-d3ab01bff505.png)

**Comment by nchanged** [comment]
Thanks for the issue, fixed in `1.3.36`
