### ISSUE TITLE
Transpile es6 modules in node_modules automatically

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#560]
2.1.0 will automatically detect module type and transpile the code seamlessly.
No need in Babel. Even in node_modules.

Finally.

🎆 
!!!!!!
`2.1.0-beta.9`

**Comment by aretecode** [comment]
https://github.com/fuse-box/fuse-box/issues/511

**Comment by nchanged** [comment]
It's magical already

**Comment by guillaume86** [comment]
Not sure it's related to this but it might be:

I have a dependency of a dependency (only-react-css-property-operations) which uses `const` and it is not getting transpiled when using the `browser` target (I also tried `browser@es5`). Should I file an issue or is it something I can configure/force?

**Comment by nchanged** [comment]
Can we have a separate issue?

**Comment by guillaume86** [comment]
Sure I'm creating it in a minute.
