### ISSUE TITLE
Support for baseUrl and paths options of tsConfig

### ISSUE THREAD

**Issue by geowarin** [fuse-box/fuse-box#563]
Hello,

In a ts project, I could not get `baseUrl` to work as I expected.

My wish is to get the following to work:

With this tsConfig:

```
"compilerOptions": {
    "baseUrl": "src",
}
```

And given the following structure:

```
├── src
│   ├── components
│   │   └── Root.tsx
│   └── index.ts
└── tsconfig.json
```

Importing `Root.tsx` from `index.ts` should work by writing:

```ts
import {Root} from "components/Root"
```

instead of 

```ts
import {Root} from "./components/Root"
```

Related is the [paths](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping) option of the typescript compiler.

Is this something you plan on supporting?

Thanks!

**Comment by nchanged** [comment]
isn't it easier to set `homeDir` to point to `src/` ?

**Comment by geowarin** [comment]
My `homeDir` does points to `src`.
It doesn't seem to impact module resolution from source files, though.

It is supposed to?
I thought that homeDir was used to resolved source in bundle arithmetics.

Another thing is I will need to keep `baseUrl` in my typescript config anyway since I need to tell the compiler about my intentions.

**Comment by nchanged** [comment]
I see now what you mean
```
import {Root} from "components/Root"
```

That is an `npm_module` We don't support this kind of black magic yet. Cuz `components` could be easily in `node_modules`

Aliases, yes - it could be solved with aliases.
Let's think about it

**Comment by nchanged** [comment]
Answering to your original question - of course, if it comes with typescript we should support it ;-)

**Comment by devmondo** [comment]
Rock on!!!

**Comment by geowarin** [comment]
It's kind of like aliases but dynamic:

pseudo-code:
```js
const dirs = fs.readdirSync(homeDir);

const bundle = fuse.bundle("app")

for (let dir of dirs) {
    bundle.alias(dir, `~/${dir}`)
}
```

PS: ❤️  you guys

**Comment by nchanged** [comment]
@geowarin I don't think that a pseudo code ;-) that' exactly how you do it =)

**Comment by devmondo** [comment]
the comment above seems like a solution.

we will close this for now but let us know otherwise :)

**Comment by tinchoz49** [comment]
Hi @geowarin, your solution works great but I had problems with the sourcemap files resolutions.

For example, I have this structure in my project:
```
src/
----utils/
--------index.js
----index.js
```
and I define the alias for `utils`
```javascript
// fuse.js
const plugins = [
    BabelPlugin({
      sourceMaps: true,
      presets: ['es2015']
    }),
    WebIndexPlugin({
      template: 'public/index.html'
    })
  ];
const fuse = FuseBox.init({
    homeDir: 'src',
    output: 'dist/$name.js',
    target: 'browser',
    sourceMaps: true,
    plugins,
    alias: {
      utils: '~/utils'
    }
  });

const vendor = fuse.bundle('vendor').instructions('~index.js');
const app = fuse.bundle('app').instructions('!>[index.js]');
```

```javascript
// index.js

import utils from 'utils';
```
The bundle process works fine but I get a wrong sourcemap.

The principal `src/index.js` disappear of my sourcemap:

```
packages/
src/
----utils/
--------index.js
----index.js (missing)
app.js
vendor.js
```

Is there anyone with the same issue?

**Comment by nchanged** [comment]
Clearing cache helps sometimes ;-)
