### ISSUE TITLE
Livereload Support

### ISSUE THREAD

**Issue by bradenhs** [fuse-box/fuse-box#569]
Currently to get classic live reload support you have to do something like this:

fuse.ts
```javascript
fuse.bundle('bundle').instructions('>index.ts').watch().hmr()
fuse.dev()
fuse.run()
```

index.ts
```javascript
import { setStatefulModules } from 'fuse-box/modules/fuse-hmr'
setStatefulModules(() => true)
```

Since every module is marked as stateful any change in your app will result in a page reload which is the desired behavior.

With webpack this is a simple as running `webpack-dev-server`. I'm not sure the best way to resolve this but I think it should definitely be consolidated to the fuse.ts file instead of having to put build configuration code in your bundle. Since reloading the webpage on every change isn't really hot module reloading using `hmr()` probably shouldn't be required since it isn't intuitive. Here's a few thoughts about how to resolve this:

- In the main config object include a `livereload` boolean option
- Include a `livereload()` function in the bundle chain
- In the optional object passed to the watch function add a `livereload` option
- If the `dev()` function's option pass in a `livereload` option

Maybe `livereload` isn't the best name. Any other thoughts on how to achieve this behavior in an intuitive way?

**Comment by devmondo** [comment]
This is possible  now http://fuse-box.org/page/development#auto-reload-page
 let us know otherwise.

**Comment by bradenhs** [comment]
Works great!

**Comment by bradenhs** [comment]
Only thought would be: is it possible to make this work with Quantum?

**Comment by devmondo** [comment]
@bradenhs, do you use quantum uring dev process?  usually, you do quantum only when you want to create a production-ready build. none the less, if you feel it should happen, kindly create a seprate issue for this :)

**Comment by bradenhs** [comment]
Don't use Quantum at all yet but this would be useful when developing production specific parts of the code base (i.e. stuff that runs only when `process.env.NODE_ENV==='production'` is true)

**Comment by nchanged** [comment]
@bradenhs http://fuse-box.org/page/quantum#dead-code-elimination
