### ISSUE TITLE
[SassPlugin] problem with resolving relative paths when `includePaths` option is explicitly specified

### ISSUE THREAD

**Issue by zgredzik** [fuse-box/fuse-box#57]
When provided with an input instead of a path to a file (as is the current way of `SassPlugin`), `node-sass` requires the path pointing to the original file (from which the contents have been used as the input data) to be among the `includePaths` in order to be able to resolve relative include paths.

The problem is that when someone wants to specify additional `includePaths`, [Object.assign()](https://github.com/fuse-box/fuse-box/blob/96b646a632f886f296a533ccf4c45f436cf443f3/src/plugins/SassPlugin.ts#L31) will completely overwrite [the default value](https://github.com/fuse-box/fuse-box/blob/96b646a632f886f296a533ccf4c45f436cf443f3/src/plugins/SassPlugin.ts#L36) that includes the currently processed file's absolute path.

I think the `includePaths` should have the file's location implicitly appended as I don't imagine adding an additional `includePaths` entry for every single `.scss` in my project that has a relative import.

If anyone sees a problem with always adding `file.info.absDir` to the list of include paths, then I guess it could be available as a plugin configuration option?

**Comment by nchanged** [comment]
Absolutely!

**Comment by nchanged** [comment]
released `1.3.37`
