### ISSUE TITLE
VuePlugin: module imports not working correctly

### ISSUE THREAD

**Issue by NGPixel** [fuse-box/fuse-box#574]
import statements are not working as expected.

# Case 1

The following line works in a standard .js file:
```js
import $ from 'jquery'
```
using the same import inside a <script> tag in a .vue file won't work.
The following workaround must be used instead:
```js
import * as $ from 'jquery'
```

# Case 2

The following line works in a standard .js file:
```js
import debounce from 'lodash/debounce'
```
using the same line inside a <script> tag in a .vue file results in the debounce code not being included in the bundle. Therefor, it tries to load the file via HTTP and throw an errors. Using the `import * as debounce from 'lodash/debounce'` syntax doesn't work either in this case.

**Comment by nchanged** [comment]
Import * as is.l not a workaround. Check our FAQ please ... You don't have default exports. Regarding bundling, that's true there is a bug.

**Comment by nchanged** [comment]
I believe it has been fixed with the updates to [VuePlugin](https://github.com/fuse-box/fuse-box/blob/master/src/plugins/VuePlugin.ts#L59)

Closing it for now, feel free to re-open elsewise.
