### ISSUE TITLE
Using Typescript and Babel

### ISSUE THREAD

**Issue by timsuchanek** [fuse-box/fuse-box#577]
Is it possible to still use babel after the typescript loader? Our use case is, that we run a custom babel plugin https://github.com/zeit/styled-jsx, that is not available for TypeScript.
Besides that, keep up the awesome work!

**Comment by nchanged** [comment]
Yes, you can do that!

**Comment by timsuchanek** [comment]
Ok, I tested it, actually that doesn't seem to be the problem,
but the real problem is the following:
I would like to set `"jsx": "preserve"` in the tsconfig.json.

This is how my tsconfig.json looks like
```json
{
  "compilerOptions": {
    "target": "es2015",
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "jsx": "preserve",
    "sourceMap": true,
    "removeComments": true,
    "preserveConstEnums": true,
    "strictNullChecks": false,
    "lib": ["es7", "dom"]
  },
  "files": [],
  "exclude": [
    "node_modules",
    "dist"
  ]
}
```

In  a webpack project this works. (this is needed so babel and not typescript is reading the jsx)

Is that possible with fuse? Thanks!

**Comment by devmondo** [comment]
i think it should work, as FuseBox is not responsible for that, FuseBox only takes what ts Transpiles, are u sure you have your `tsconfig` in root of your project ?

**Comment by nchanged** [comment]
@timsuchanek compiler options are respected. What might have happened, is that you transpiled your code, then changed `tsconfig.json` but the cache wasn't busted. Remove `.fusebox` folder and see what happens.

**Comment by nchanged** [comment]
Closing this issue, for now, feel free to re-open elsewise.
