### ISSUE TITLE
Opinionated Project Structure

### ISSUE THREAD

**Issue by stevensheehy** [fuse-box/fuse-box#581]
All the other web build tools seem to take a configuration-centric or a code-centric approach. I really like how fuse-box instead takes a more convention over configuration/code approach than the others. Having an opinionated project structure would help further this goal, while still allowing users to override defaults if they want a different structure.

Coming from the Java world with its [Maven](http://maven.apache.org) building tool, I think it would be useful if fuse-box would take a more opinionated view of how projects should be structured like [maven does](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html). That is, not maven's specific directory layout but a best practice layout for web projects so that newcomers can get up and running with zero config if they follow the proper layout. As an example, these variables could be set to defaults:

homeDir: 'src/',
output: 'dist/$name$hash.js'

Along with these, maybe a testDir with default folder of 'test/' for the test runner and possibly some default vendor and app bundles based upon an index.ts.

**Comment by nchanged** [comment]
hi @stevensheehy thanks for suggestions. There is a convention for testing. IT does not really matter which folder your tests are in. If you have `Foo.test.ts` it will be picked up by the test runner. Pattern `*.test.ts` is a convention.
