### ISSUE TITLE
Default Sparky Tasks

### ISSUE THREAD

**Issue by stevensheehy** [fuse-box/fuse-box#583]
It would be nice if fuse-box came with some default Sparky tasks for common tasks out of the box. This would reduce code duplication across projects and allow developers to get their projects up and running faster. Example tasks (missing necessary implementations):

```javascript
Sparky.task("help", () => {});
Sparky.task("default", ["package"], () => {});
Sparky.task("clean", () => {});
Sparky.task("build", ["clean"], () => {});
Sparky.task("test", ["build"], () => {});
Sparky.task("run", ["test"], () => {});
Sparky.task("integration-test", ["run"], () => {});
Sparky.task("package", ["integration-test"], () => {});
```
Then the user would configure with FuseBox.init({...}) and run:

```bash
$ node fuse
Launch "default"
Resolve "clean"
Resolve "build"
...
```

Having default tasks would provide a standardized project lifecycle/phases where one task flows into the next. Any task could be redefined by a user if they choose and a FuseBox.disableDefaultTasks() could turn them all off. Having defined phases would make the configuration more declarative and less imperative, allowing for enhancements like avoiding the cumbersome production flag to determine the task flow and instead relying upon the current task phase for its context state.

**Comment by nchanged** [comment]
I agree with you, so in a nutshell "dist" task would enable hashing and uglify, right!

**Comment by steven-sheehy** [comment]
Yes, exactly. I called "dist" in the example above "package", but same thing. Although, advanced functionality like automatically enabling plugins could be done in a later iteration. So init(), bundle(), etc. would declaratively configure FuseBox to tell it _what_ to do and the tasks would determine _when_ to do them. So the run task may be a no-op if the user didn't configure a devServer() and the test task may be a no-op if test() wasn't configured.
