### ISSUE TITLE
Bundling `.node` files (as required by the bindings util)

### ISSUE THREAD

**Issue by calebboyd** [fuse-box/fuse-box#589]
Great Project! I've been working on identifying an adequate way to handle bundling in [nexe](https://github.com/nexe/nexe/tree/next) And I concluded that a virtual filesystem for modules was the best route, and it looks like fusebox has solved that problem quite well. So my goal is to use it as the primary opt in bundling tool for the project. I had a few questions before I began. (might need separate issues)

While its simple enough to build a `.node` loader plugin similar [to this one](https://github.com/calebboyd/xbin/blob/master/xbin-loader/index.js)
I was wondering if there were any suggestions for enabling support for the `bindings` [module](https://www.npmjs.com/package/bindings). Its gist, is that it uses an Error object to determine the root path of invokation and then scans some (further) dynamic directories for the `.node` dll.

Additionally -- Is there a mechanism to emit the bundle in memory instead of writing an output file?

I appreciate any guidance!

**Comment by devmondo** [comment]
@calebboyd welcome and thank you for the kind words :)

Yes, FuseBox takes a great approach to creating a virtual file system.

Did you check FuseBox Dynamic Modules feature http://fuse-box.org/page/loader-api#dynamic-modules?  we use it all the time in our project to dynamically create and load modules.

Regarding other questions @nchanged could you elaborate please.

**Comment by nchanged** [comment]
Welcome @calebboyd 
From what I understood you want to modify the behaviour at runtime, Which is possible with plugins.
A simple plugin would look like:

```
FuseBox.init({
  plugins : {
    myPlugin : {
      transform : (file) = { file.contents = "hello world" }
    }
  }
})
```

Please describe the logic there, we will help you.

**Comment by calebboyd** [comment]
Thanks for your fast replies. 

>Did you check FuseBox Dynamic Modules feature

I don't think this will help at all for enabling `bindings` to discover the `.node` file. I'd also note that it isn't clear in the docs that its referring to the global FuseBox present inside the bundle. It held me a up a bit since the only static method on the FuseBox class is `.init`. Am I correct in assuming that the dynamic module declarations should be emitted in transforms, Or should they be used in user code?

@nchanged Here is a small example of what i'm trying to accomplish ([gist](https://gist.github.com/calebboyd/c5144a319b2f676345c0f1c9913eae1b))

You can clone that gist and `npm i` will emit two bundles
My goal is to have `index.js`'s bundle behave like the `index-node.js` bundle. 

I think this might be possible if I can identify each module that has `bindings` as a direct dependency. in addition to `bindings` I'd also want to make it work with `node-pre-gyp#find`

**Comment by calebboyd** [comment]
>I think this might be possible if I can identify each module that has bindings as a direct dependency

Attaching to bundleEnd and inspecting `context.nodeModules` doesn't appear to have `dependencies` set. 
Is there some hook that would work better to pursue my approach (or will that approach even work)

**Comment by nchanged** [comment]
Isn't it easier to process this [part](https://gist.github.com/calebboyd/c5144a319b2f676345c0f1c9913eae1b#file-fuse-js-L17-L22)
at build time? and write the actual contents?

**Comment by nchanged** [comment]
If you want to add dependencies, try

```js
file.analysis.dependencies.push('./relative-path')
``` 
OR
```js
file.analysis.dependencies.push('~/from-root/path')
```

**Comment by calebboyd** [comment]
>Isn't it easier to process this part
at build time? and write the actual contents?

Since the bundle is for [nexe](https://github.com/nexe/nexe/tree/next) the goal is a single file. Other than that, when is "build time" if not when fusebox is running?

I noticed that the dependencies don't populate until the files are analyzed. How can I have a plugin trigger for node_modules. It seems if I use a test `\.js$` it only triggers for "Your Own Code"

**Comment by nchanged** [comment]
Of course, we analyse it and then populate the dependencies, how else? ;-)
What do you mean? You can trigger any module from your plugin.  And inject any code that triggers anything. Please clarify, maybe easier if you write down the steps

**Comment by calebboyd** [comment]
Hah, excuse my naiveté as I discover the api. I found that my `.allowExtension` call more restrictive than my `test` regexp.

**Comment by nchanged** [comment]
So it's all good now?

**Comment by calebboyd** [comment]
Sorry, I haven't had much of a chance to look into it more.
There isn't much documentation on the `ast` parameter of the transform function

- When is it populated? 
- If changes are made to the ast do they need to be serialized to `file.contents`? Or will that be done automatically if ast exists (or when it is created using makeAnalysis)

**Comment by nchanged** [comment]
* during the AST traversing 
* yes, you can set a flag and fusebox will generate the code (requiresRegenation or something)

**Comment by calebboyd** [comment]
Haha, Yes, of course. I should've phrased my question differently. It sounds like it is the responsibility of the plugin to invoke "makeAnalysis" if the ast is not already populated when the plugin's transform function is invoked.

Following up with a previous question:

Is there a mechanism to emit the bundle in memory instead of writing to a file? For example, webpack uses `memory-fs` for this.

**Comment by aretecode** [comment]
would be fairly simple if one could hook into `context.bundle.bundleSplit.beforeMasterWrite` & `context.writeOutput` & `context.output.writeStaticCache`
