### ISSUE TITLE
Dependencies not being bundled

### ISSUE THREAD

**Issue by a-s-o** [fuse-box/fuse-box#591]
Hi,

I am just trying out fuse-box with a very simple file and it is not bundling the dependencies of that file. Here is my sample code:

src/index.ts

```
import * as m from 'mithril'

const ROOT = document.querySelector('#app') as HTMLElement

m.mount(ROOT, {
  view () {
    return m('pre', 'App started')
  },
})
```

~/fuse.js

```
const { FuseBox } = require('fuse-box')

const fuse = FuseBox.init({
    homeDir: 'src/',
    output: 'dist/$name.js',
})

fuse.bundle('app').instructions('>index.ts')
fuse.run()
```

After running `node fuse` from the root folder, I end up with the following code in dist/app.js:

```
(function(FuseBox){FuseBox.$fuse$=FuseBox;
FuseBox.pkg("default", {}, function(___scope___){
___scope___.file("index.js", function(exports, require, module, __filename, __dirname){

"use strict";
exports.__esModule = true;
var m = require("mithril");
var ROOT = document.querySelector('#app');
m.mount(ROOT, {
    view: function () {
        return m('pre', 'App started');
    }
});

});
});

FuseBox.import("default/index.js");
FuseBox.main("default/index.js");
})
// omitted fusebox api included on last line
```

I would expect to see whole of the `mithril` package included in the bundle since I am importing it in index.ts

Any help would be appreciated. I have been scanning the docs for a couple of hours and no dice.

Thank you

**Comment by nchanged** [comment]
Hi! Is that lib properly installed? Can we have a repo to reproduce it?

**Comment by nchanged** [comment]
Are u using tsx with pragma? That might be a problem, add +mithril to instructions

**Comment by a-s-o** [comment]
> Are u using tsx with pragma?

Yes, that is what I was doing. Thanks and you suggestion fixed it. Appreciate the help and thanks for providing such a great package. Keep up the good work.

As an aside, I think the test runner might be the killer feature for FuseBox.

**Comment by nchanged** [comment]
Thanks, we have a test runner already, check it out in the docs :)
