### ISSUE TITLE
css plugin link broken for example

### ISSUE THREAD

**Issue by aretecode** [fuse-box/fuse-box#592]
link is broken, goes to here
http://fuse-box.org/plugins/css-plugin#css-plugin
http://fuse-box.org/plugins/Plugin%20configuration

**Comment by devmondo** [comment]
for me the first one is working, where is the second one location?

**Comment by aretecode** [comment]
` #list-of-plugins ` link on first page

**Comment by aretecode** [comment]
@devmondo the https://github.com/fuse-box/mastering-css link is broken on there too, all on the very first line

**Comment by andrew-w-ross** [comment]
This is still broken, anything happening with it?

**Comment by nchanged** [comment]
I think it that repo was removed

**Comment by devmondo** [comment]
the docs are updated. will close this :)

**Comment by andrew-w-ross** [comment]
@devmondo I think you need to reopen this issue, the link still isn't working
