### ISSUE TITLE
FuseBox Quantum 

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#599]
And finally, 2.1.0 is out with its grand, the most challenging-to-implement feature.

# Quantum

http://fuse-box.org/page/quantum

Make sure to check it out and let us know what you think. It required lots of effort and thinking. I hope you guys could start testing it and submit your ideas and of course, our favourite - bugs.

https://github.com/fuse-box/angular2-example
https://github.com/fuse-box/react-example

```
node fuse dist
```
Tree shaking example is [here](https://github.com/fuse-box/fuse-box-examples/tree/master/examples/quantum_tree_shaking) It manages to shake out some code of angular2 btw 

Cheers!

**Comment by yihongang** [comment]
The docs mention that uglify is enabled by default but it requires an `{ uglify: true }` passed to Quantum.

Also, why does it generate 

`var A = $fsx.r('index.js');`

when I can only see number ids? The code works when I change the `'index.js'` into the correct number, that I have to find by going through `$fsx.r`. 

Also what's the correct way of using it with the babel plugin? The docs on `removeExportsInterop` is a little hard to read and I can't tell if it should be true or false. Setting it to false causes  `exports is not defined`

**Comment by nchanged** [comment]
`> Also, why does it generate $fsx.r('index.js')`

It wasn't able to find a node module (and it is an invalid node module that you put there)
Check your bundle without Quantum.

You should `import "./index.js"` and not `import("index.js")` furthermore, please read up on javascript import statement basics.

You can use any plugin you like, Quantum does processing after everything else (babel, typescript it doesn't care). And use it for production builds.

Regarding uglify, that i will fix, thanks

**Comment by yihongang** [comment]
The build worked before adding Quantum, and I am also not doing imports like that

I am doing `import * as Abc from "abc";` as instructed from http://fuse-box.org/page/faq#imports-exports

**Comment by nchanged** [comment]
Ok, could you reproduce the error, please?  (in a GitHub repository)

**Comment by yihongang** [comment]
Try this: https://github.com/yihongang/test_quantum

Thanks for the fast response. If it's an issue with how I am doing stuff, I apologise in advance.

**Comment by nchanged** [comment]
@yihongang that was an easy one
```
fuse.bundle('vendor').instructions('~ client.tsx')
fuse.bundle('client').instructions('!> [client.tsx]')
fuse.run()
```

Make sure you have the right order. 
First `vendor` then `client`

All started working after I have swapped them.

**Comment by yihongang** [comment]
Welps that was embarrassing. Is there somewhere where this is documented? Thanks for the help! 😅

**Comment by nchanged** [comment]
@yihongang no worries, I don't think so but, I though it goes without saying ;-) As vendor should be loaded first ;-)
