### ISSUE TITLE
File path using backslash on windows

### ISSUE THREAD

**Issue by joselee** [fuse-box/fuse-box#60]
* operating system: Windows 10
* fuse-box version: 1.3.37
* node version: 6.9.1
* npm version: 3.10.8

After upgrading from fuse-box-1.3.33 to 1.3.37, the app builds fine, but I get runtime errors in the browser console. They are 404s, but only for my application-specific imports.

Looking at the bundled js, those file paths have backslashes instead of forward slashes.

For example:
`___scope___.file("todo\todo-list.component.js", function(exports, require, module, __filename, __dirname){ `

Manually changing those backslashes to forward slashes seems to make things work again.

**Comment by nchanged** [comment]
Yeah, i am trying to figure out what's wrong now ..

**Comment by devmondo** [comment]
will be fixed ASAP :)

**Comment by nchanged** [comment]
Fixed in `1.1.38`

**Comment by joselee** [comment]
1.3.38 works great! thanks
