### ISSUE TITLE
Sourcemaps for split bundles

### ISSUE THREAD

**Issue by xdave** [fuse-box/fuse-box#603]
I'm not getting working source maps with split bundles.  Is this expected behavior at the moment?  Or am I missing something that's not currently documented?

**Comment by nchanged** [comment]
yes, source maps for split bundles aren't working yet. But they should!

**Comment by nchanged** [comment]
These bundle source maps should load source maps dynamically, I am not sure how that would be possible in the context. But feel free to suggest your ideas

**Comment by xdave** [comment]
Shouldn't the JS runtime pick up the source map url in the file when it needs it?  As far as I know, only if console.log() happens or debugging.

**Comment by nchanged** [comment]
@xdave yes and no. A split bundle is instantiated via `new Function` So there are some limitations.

**Comment by xdave** [comment]
So, it seems that the JS universe is moving towards the in-browser module system (via the `import` function, if it exists or poly-filled).  Typescript 2.4 RC just added `await import(...)` syntax, which they expect bundlers to optimize for code-splitting purposes.

In either case, perhaps loading the bundle some other way would allow the source map to load?  What about JSONP ?

**Comment by xdave** [comment]
https://medium.com/webpack/how-to-use-webpacks-new-magic-comment-feature-with-react-universal-component-ssr-a38fd3e296a

**Comment by xdave** [comment]
https://github.com/tc39/proposal-dynamic-import#using-host-specific-mechanisms

**Comment by xdave** [comment]
(window || global).import() in FuseBox could work such that:

- If the module is not resolved,
    - Assuming that the parent bundle is already loaded
    - If any part of path resolves to something that may be in a split bundle
        - Load that split bundle,
        - Load that module from the split bundle

This would require that the parent bundle already know where it's child bundle's files are.

**Comment by nchanged** [comment]
Yep, you have just described how lazyLoad works with code splitting :) we just need to make a support for "import" statement!

**Comment by nchanged** [comment]
#605

**Comment by xdave** [comment]
@nchanged so, for loading a split bundle with source maps, why not use this?

```ts
const loadBundle = (path: string) =>
    new Promise<void>((resolve, reject) => {
        const s = document.createElement('script');
        s.setAttribute('type', 'text/javascript');
        s.setAttribute('src', path);
        s.setAttribute('async', 'true');
        s.addEventListener('error', reject);
        s.addEventListener('load', () => resolve(s.remove()));
        document.documentElement.appendChild(s);
    });
```

**Comment by xdave** [comment]
It works as is for now, except that the source for any modules inside of the bundle point to the bundle itself, because the bundle doesn't have it's own sourcemap.

**Comment by xdave** [comment]
So, with the latest changes, it looks like this is fixed.  Because split bundles are not technically split with the vanilla API, source maps work for them now.

**Comment by nchanged** [comment]
@xdave that's correct!
