### ISSUE TITLE
import statement and code splitting proposal for 2.2.0

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#605]
Typescript will support `dynamic imports` in 2.4, therefore it's imperative for FuseBox to officially support it too.

https://blogs.msdn.microsoft.com/typescript/2017/06/12/announcing-typescript-2-4-rc/

In light of these changes some things like `code splitting` need to be reconsidered and consolidated.

The proposal follows:

## Actual splitting in Quantum
Quantum is a powerful extension on top of FuseBox. Code splitting doesn't need to happen in development mode.

We provide a simple polyfill for development mode (so the actual files stay in the main bundle). That will remove many problems like HMR e.t.c and make the development flow easier.  The syntax will stay the same, and the current functionality will be kept for a while to give time for users to migrate. 

If `Quantum` is injected, FuseBox will switch to a new mode, where the actual splitting happens when making production builds.

## import will replace lazyLoad

Currently, we import `fuse-tools` and use `lazyLoad` function.  That will be redundant and will go away in favour of `await import`

```
import("about").then(module => )
// or
await import("about")
```

## Build time instructions (splitting without configuration)

It will be possible to split bundles without configuring anything. Using arithmetic instructions, of course ;-)
New symbol `=` will be introduced
```
import("+routes/about/** > routes/about/AboutComponent = about")
```

Which will do exactly the same thing:
```
fuse.split("routes/about/**", "about > routes/about/AboutComponent.tsx")
```

It won't be necessary to use `=` sign if a bundle doesn't need to be re-used.  

Tell us what you think guys!

The release should happen in sync with the official Visual Studio code [release](https://www.visualstudio.com/en-us/news/releasenotes/vs2015-update3-vs)

---

Release Date: June 27, 2016

**Comment by xdave** [comment]
What I described in https://github.com/fuse-box/fuse-box/issues/603#issuecomment-308314921 involves resolving individual files from a bundle, which is (I believe) what the `async import()` syntax will want.  ie. Typescript will actually resolve the module and it's exports.

**Comment by xdave** [comment]
Here's an example of how `import()` is supposed to work: https://github.com/tc39/proposal-dynamic-import#example

**Comment by nchanged** [comment]
It will work exactly like it in the next release

**Comment by xdave** [comment]
@nchanged 

So, simplifying the split syntax would be cool.

```ts
const Widget = await import(/* fbxSplit: 'widget' */ '../components/Widget');
```
Which would be shorthand for:
```ts
fuse.split("components/Widget/**", "widget > components/Widget/index.tsx")
```

- Helps with resolving what bundle the module is coming from at runtime
- Ensures that FuseBox's `import()` function doesn't have semantics that stray from the standard
- Ensures that Visual Studio Code can infer the module types for Widget, etc

**Comment by nchanged** [comment]
@xdave so you want us to copy Webpack? ;-) I find this solution extremely tedious.

**Comment by nchanged** [comment]
@xdave we could use generic types, I hope those will be available
```
import<AboutComponent>("about")
// about is the name of a bundle
```

**Comment by xdave** [comment]
I think vscode is going to want to resolve the module in the same way as
```ts
import AboutComponent from "about"';
```
would.

So, "about" would need to be a module it can do a type lookup with, not a bundle.

**Comment by xdave** [comment]
OK, how about just
```ts
const Widget = await import(/* widget */ '../components/Widget/index.tsx');
```

If you copy webpack, people will switch.  The less code they have to change, the better.

**Comment by nchanged** [comment]
I have a solution in mind of mapping to a bundle
```
await import( '../components/Widget');
```
It's possible, but there will difficulties with the Vanilla API, Quantum, however, has no problems with it.

**Comment by nchanged** [comment]
Since we know the entires

```
fuse.split("components/Widget/**", "widget > components/Widget/index.tsx")
```

There should not be any problems achieving the goal without any extra comments and not breaking typescript. But as I said, Vanilla API won't really like it.

**Comment by xdave** [comment]
Another thing to consider: https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#dynamic-import-expressions

> Many bundlers have support for automatically splitting output bundles based on these import expressions, so consider using this new feature with the esnext module target.

**Comment by xdave** [comment]
If you don't use the `esnext` module target, it translates the `import()` call to `require()`

**Comment by xdave** [comment]
I'm testing this with typescript@next right now, and even vscode is playing nicely with it.

**Comment by xdave** [comment]
Can't use module type `es2015`:

> src/index.ts(2,29): error TS1323: Dynamic import cannot be used when targeting ECMAScript 2015 modules.

**Comment by nchanged** [comment]
@xdave I just did it.. AND OH MY LORD!!!
https://github.com/fuse-box/fuse-box/blob/master/src/quantum/plugin/modifications/DynamicImportStatements.ts#L14

```js
import("./routes/home/HomeComponent").then(home => {
    console.log(home);
});
```

with the config
```js
.split("routes/home/**", "home > routes/home/HomeComponent.ts")
```

It's automatically mapped and resolved!!!!

P.S Vscode doesn't really like the syntax (it's a June update right)?

**Comment by xdave** [comment]
I'm using vscode 1.13.1 and I have `"typescript.tsdk": "./node_modules/typescript/lib",` in my settings.

So when installing `typescript@next`, it uses that version.

**Comment by nchanged** [comment]
@xdave btw, fusebox doesn't require `typescript@next` for dynamic imports. It's replaced long before it actually gets to transpiling

**Comment by xdave** [comment]
I know that much, I was talking about vscode support.

**Comment by nchanged** [comment]
![screenshot 2017-06-17 22 26 03](https://user-images.githubusercontent.com/1629088/27256083-fee04a84-53ab-11e7-809d-b3e4c2c90bbc.png)
I got it working! And FuseBox maps it and lazy loads a bundle!!!

**Comment by xdave** [comment]
nice.

**Comment by xdave** [comment]
Only thing we lose is the ability to declare the split config when the dynamic module is imported.  However, that would require more info in the code (such as a comment or other magic).

**Comment by nchanged** [comment]
What do you mean? it will be in the config yes.

**Comment by nchanged** [comment]
@xdave https://github.com/fuse-box/fuse-box-examples/blob/2.2.0/examples/code-splitting/src/index.ts

```
node fuse dist
```

**Comment by xdave** [comment]
So, with `2.2.0-beta.7`, it seems that the vanilla API has a couple of issues:

- The split bundles are not processed
- Hot reloading does not occur for files in a split bundle anymore

**Comment by nchanged** [comment]
@xdave what do u mean not processed? There is a bug yes, but not related to processing, check the demos I sent

**Comment by xdave** [comment]
What I meant was the files for a split bundle are not separated with the vanilla API, they're included in the parent bundle.  It otherwise works as if I didn't do the split at all.

**Comment by devmondo** [comment]
i confirm this.

**Comment by nchanged** [comment]
Yes and this is by design

**Comment by nchanged** [comment]
Physical split happens with quantum, vanilla is just faking it for development purposes

**Comment by xdave** [comment]
OK, understood.  However, the hot reloading of the files inside of a split bundle (vanilla API) does not work.

**Comment by nchanged** [comment]
Hm, it should, but I will check, that's for sure.
