### ISSUE TITLE
How to writing tests also with typescript or es6?

### ISSUE THREAD

**Issue by lygstate** [fuse-box/fuse-box#61]

**Comment by nchanged** [comment]
You can probably read on the Internet how to write tests, fusebox has nothing to do with the issue

**Comment by lygstate** [comment]
I am not talking about how to running tests, but writing tests but still can be tests with fuse-box

**Comment by nchanged** [comment]
Fusebox bundle is like any other JavaScript module, so nothing is changing there. Nothing at all, you can use any tutorial
