### ISSUE TITLE
Browser target and deep overrides

### ISSUE THREAD

**Issue by erkkaha** [fuse-box/fuse-box#610]
There seems to be and issue with deep browser overrides. Issue is reproduced [here](https://github.com/erkkaha/react-example)

Problem is in this case [asap](https://github.com/kriskowal/asap/blob/master/package.json)
from asap package.json
```
  "main": "./asap.js",
  "browser": {
    "./asap": "./browser-asap.js",
    "./asap.js": "./browser-asap.js",
    "./raw": "./browser-raw.js",
    "./raw.js": "./browser-raw.js",
    "./test/domain.js": "./test/browser-domain.js"
  }
```

"./asap.js" --> "./browser-asap.js" works fine, but "./browser-asap.js" requires  "./raw" and that is not resolved to "./browser-raw.js".

Same issue can be reproduced with uuid as well, where index.js requires v4.js, which requires ./lib/rng.js, which should resolve to "./lib/rng-browser.js"

Tested with fuse-box 2.1.0 and node 8.0

**Comment by nchanged** [comment]
Fixed in `fuse-box@2.2.0-beta.7`
