### ISSUE TITLE
Server Side Pre-Rendering ReferenceError: FuseBox is not defined

### ISSUE THREAD

**Issue by JohnGalt1717** [fuse-box/fuse-box#616]
HI there. I'm trying to get an angular 4 project working and everything works fine (ng2-fused works nicely except for lazy loading) on browser side however I can't get the server side node execution to recognize FuseBox.

I tried adding this to my entry point: import { FuseBox } from 'fuse-box';

But it doesn't seem to work.

How would i get node.js to recognize fuse.js and execute?

Thanks!

**Comment by nchanged** [comment]
hi @JohnGalt1717 don't import `FuseBox` in your code. It's already recognised by server. Just use it, it's global.

**Comment by xdave** [comment]
If you're using typescript, you could do:
```ts
import { FuseBox } from 'fuse-box/dist/typings';
```

Imported types are removed by the typescript compiler after.

**Comment by xdave** [comment]
I guess you'll have to do something like:
```ts
declare const FuseBox: any;
```
At the top of the file or something.

**Comment by devmondo** [comment]
@xdave have a file called `declarations.d.ts` in your project and put the line you mentioned above, and it should work.

**Comment by nchanged** [comment]
@JohnGalt1717 a side note, you can try `import()` statement instead with `2.2.0-beta.12`

**Comment by JohnGalt1717** [comment]
Ok thanks!

**Comment by nchanged** [comment]
@JohnGalt1717 https://github.com/fuse-box/fuse-box-examples/blob/2.2.0/examples/code-splitting/fuse.js#L9

**Comment by patrickmichalina** [comment]
@JohnGalt1717 I have SSR running in my new seed project, check it out here https://github.com/patrickmichalina/fusebox-angular-universal-starter

also, nice handle :)

**Comment by devmondo** [comment]
this seems to be solved with the suggestions above. 

will close this for now, but feel free to let us know otherwise.

**Comment by nchanged** [comment]
@patrickmichalina good job!

**Comment by nchanged** [comment]
@patrickmichalina I have added your seed to our list if you don't mind, so others could find it.
http://fuse-box.org/page/examples-and-seeds#angular-universal

**Comment by patrickmichalina** [comment]
@nchanged thanks for the listing! I am having a few issues with getting quantum to work, but have de-prioritized it until I wrap up some other features first. FuseBox is amazing and hope to abstract some of my work into plugins instead of Sparky tasks later on.
