### ISSUE TITLE
Quantum is removing Provider from react-redux

### ISSUE THREAD

**Issue by xdave** [fuse-box/fuse-box#617]
I'm using it like this:

FuseBox plugins:
```ts
...
prod && QuantumPlugin({
    removeExportsInterop: false,
    uglify: true
})
...
```

Entry point `index.tsx`:
```ts
...
import { connect, Provider } from 'react-redux';
...
class AppContainer extends React.Component<{}, {}> {
    render() {
        return (
            <Provider store={store}>
                {this.props.children}
            </Provider>
        )
    }
}
```

Quantum output:
```
...
  → Process package react-redux
  →   Files: 15
...
  → tree shaking: Remove createProvider from lib/index.js
  → tree shaking: Remove __esModule from lib/components/Provider.js
  → tree shaking: Remove default from lib/components/Provider.js
...
  → Stats
      warnings : 0
```

Runtime Error in production mode:
```
7675e848-app.js:1 Uncaught ReferenceError: exports is not defined
    at e.f.(anonymous function) (http://localhost:4444/7675e848-app.js:1:62)
    at Object.r.r (http://localhost:4444/e0a179ca-api.js:1:192)
    at http://localhost:4444/7675e848-app.js:1:192687
    at http://localhost:4444/7675e848-app.js:1:192692
```

Test project to reproduce: https://github.com/xdave/fuse-box-quantum-test

**Comment by nchanged** [comment]
Thanks! in the meantime please disable tree shaking, it's in a very early stage ATM

**Comment by nchanged** [comment]
Ok, I cracked it. Two easy-to-fix bugs:

1) Removed `export` from a function should listen to `removeExportsInterop`
2) Removed `default` property. Should listen to `removeExportsInterop`

**Comment by nchanged** [comment]
Here you go `2.2.0-beta.5`

**Comment by xdave** [comment]
Nice.  Works, thanks.

**Comment by xdave** [comment]
Hmm, this appears to have regressed.  Getting this problem again with 2.3.1-beta.21.  I haven't used Quantum in a while, so I'm not sure when it regressed.

**Comment by nchanged** [comment]
@xdave it happens because that variable isn't used - therefore not bundled. That's how typescript works.
