### ISSUE TITLE
dev server with an extra route

### ISSUE THREAD

**Issue by davidanaya** [fuse-box/fuse-box#621]
Hi,

I have a problem with the dev server.

I'm using jsonServer in my development build to simulate a server on json data. So, what I want is to access my app (Angular) with http://localhost:4444 and my api with http://localhost:4444/api.

If I try this

```
use.dev(server => {
  const app = server.httpServer.app;
  app.use('/api', jsonServer.router('db.json'));
});
```

my app works but my /api doesn´t.

If I try this

```
use.dev({ root: false}, server => {
  const app = server.httpServer.app;
  app.use('/api', jsonServer.router('db.json'));
});
```

then my /api works but my app doesn´t.

I also tried

```
fuse.dev({ root: false }, server => {
  const dist = path.resolve('./dist');
  const app = server.httpServer.app;
  app.use('/api', jsonServer.router('db.json'));
  app.get('/', function(req, res) {
    res.sendFile(path.join(dist, 'index.html'));
  });
});
```
so trying to define both my base root and the api, but it also does not work.

Am I doing something wrong? How am I supposed to configure this?

Thanks

**Comment by nchanged** [comment]
hi @davidanaya and welcome to the community!
To begin with, that's just an express [server](https://github.com/fuse-box/fuse-box/blob/master/src/devServer/HTTPServer.ts#L30)

So technically you could wire up any functionality or even create your own server in java or any other language. Make sure your setup works without `dev server` in fusebox and then you can easily port it to fusebox, or simply you use your [own](http://fuse-box.org/page/development#existing-server)

**Comment by davidanaya** [comment]
Hi @nchanged, thanks for your reply and sorry I know this is not the place for this question but there's still not much support out there.

This is the setup I'm using at the moment in webpack and it works nicely. 
  ```
devServer: {
    historyApiFallback: true,
    setup: function (app) {
      app.use('/api', jsonServer.router('db.json'));
    }
  }
```
But it's like something with { root: false } is not doing what I expected :(

**Comment by davidanaya** [comment]
Ok, I got it.

It seems that when you define a route you also HAVE to define the root. I thought that would be done automatically.
So I tried this
```
fuse.dev({ root: 'dist' }, server => {
  const app = server.httpServer.app;
  app.use('/api', jsonServer.router('db.json'));
});
```
and it works! 👍
