### ISSUE TITLE
PostCSSResourcePlugin not bundling multiple src urls

### ISSUE THREAD

**Issue by UncleDave** [fuse-box/fuse-box#622]
[Example in fresh project.](https://github.com/UncleDave/fuse-box-css-resource-plugin-font-issue)

FontAwesome declares its font-family with multiple font formats:

```
@font-face {
  font-family: 'FontAwesome';
  src: url('#{$fa-font-path}/fontawesome-webfont.eot?v=#{$fa-version}');
  src: url('#{$fa-font-path}/fontawesome-webfont.eot?#iefix&v=#{$fa-version}') format('embedded-opentype'),
    url('#{$fa-font-path}/fontawesome-webfont.woff2?v=#{$fa-version}') format('woff2'),
    url('#{$fa-font-path}/fontawesome-webfont.woff?v=#{$fa-version}') format('woff'),
    url('#{$fa-font-path}/fontawesome-webfont.ttf?v=#{$fa-version}') format('truetype'),
    url('#{$fa-font-path}/fontawesome-webfont.svg?v=#{$fa-version}#fontawesomeregular') format('svg');
//  src: url('#{$fa-font-path}/FontAwesome.otf') format('opentype'); // used when developing fonts
  font-weight: normal;
  font-style: normal;
}
```

In this form, after being run through CSSResourcePlugin it seems to process the .woff, the .eot(s), and the .svg, while it skips the .woff2 and the .ttf.

However, when I change the above code to:

```
@font-face {
  font-family: 'FontPawesome';
  src: url('#{$fa-font-path}/fontawesome-webfont.ttf?v=#{$fa-version}') format('truetype');
  font-weight: normal;
  font-style: normal;
}
```

or

```
@font-face {
  font-family: 'FontPawesome';
  src: url('#{$fa-font-path}/fontawesome-webfont.woff2?v=#{$fa-version}') format('woff2');
  font-weight: normal;
  font-style: normal;
}
```
It does manage to do the .ttf and the .woff2, so I'm unsure why in the failure case it picks the .woff, .eot, and .svg to work, but the others to fail.

I had a bit of a poke and I suspect the cause lies in the [PostCSSResourcePlugin.](https://github.com/fuse-box/fuse-box/blob/master/src/lib/postcss/PostCSSResourcePlugin.ts)

The regex in this file does appear to match everything correctly:

`let re = /url\((.*?)\)/g;`

So I'm guessing line 27 may have something to do with this issue.

`const value = match[1];`

**Comment by nchanged** [comment]
You are absolutely right, we are not processing lists of fonts. That's a good catch.

**Comment by nchanged** [comment]
The next beta will be tomorrow. And we getting very close to a release ;-)
