### ISSUE TITLE
Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by rosensama** [fuse-box/fuse-box#624]
Spawned from #444 

Requested repro in https://github.com/rosensama/fuse-box_cannot_read_prototype

**Comment by nchanged** [comment]
I might know, you are using auth lock, try setting target : browser (and clear the cache)

**Comment by nchanged** [comment]
Ok, there is some severe problem with auth-lock... Trying to find out what's wrong

**Comment by nchanged** [comment]
```
vendor = fuse.bundle("vendor").target("browser").instructions("~index.jsx");
    app = fuse.bundle("app").target("browser").instructions("!>[index.jsx]");
```

This one fixes one problem, but then there is another

```
var Auth0Lock = function (_Core) {

  _inherits(Auth0Lock, _Core);

  function Auth0Lock(clientID, domain, options) {
    _classCallCheck(this, Auth0Lock);

    var _this = _possibleConstructorReturn(this, _Core.call(this, clientID, domain, options, _classic2.default));

    injectStyles();
    return _this;
  }

  return Auth0Lock;
}(_core2.default);
```
`_core2.default` is never a function. It's a function. It's bundled correctly, but i am afraid there is a bug in the library

**Comment by nchanged** [comment]
Please check this issue. I can't seem fix it, cuz it's not really fixable. FuseBox bundles it correctly with `target("browser")`. 
https://github.com/styled-components/styled-components/issues/271

And it's not resolved. You could try shimming it maybe?

**Comment by ixjakub** [comment]
Wow, I had the same issue with superagent and fuse-box. Adding `.target('browser')` helped. Thank you!

```js
    vendor = fuse.bundle("vendor").target("browser").instructions("~ index.jsx")
    app = fuse.bundle("app").target("browser").instructions("> [index.jsx]")
```

BTW Should it be added to both vendor and app?

**Comment by nchanged** [comment]
@ixjakub with the latest beta you can set it in the parent config
```
target : "browser"
```

**Comment by nchanged** [comment]
![screenshot 2017-06-20 21 06 00](https://user-images.githubusercontent.com/1629088/27351200-cda832f8-55fc-11e7-9109-42d7b0e3b141.png)

@ixjakub I hope this will be helpful 👍

**Comment by ixjakub** [comment]
Cool :)

**Comment by rosensama** [comment]
@nchanged thanks.  I'll test the target('browser') bits over the next few days.  I've reported a defect to Auth0, but we'll see where that goes.

**Comment by nchanged** [comment]
@rosensama that's cool, we will keep it open for now. I tested it thoroughly, and it really seems like fusebox has nothing to do with the build.

**Comment by rosensama** [comment]
@nchanged sorry for the delay.   Looks good to me.

**Comment by devmondo** [comment]
Will close this for now as it seems to be  resolved, but let us know otherwise :)
