### ISSUE TITLE
Quantum - bakeApiIntoBundle broken by uglification

### ISSUE THREAD

**Issue by UncleDave** [fuse-box/fuse-box#625]
When bakeApiIntoBundle is set the Quantum bundle writer will attach the fuse-box api to the front of the given file and then append a newline, if uglify is enabled this newline will get removed.

`targetBundle.generatedCode = new Buffer(this.core.api.render() + "\n" + targetBundle.generatedCode);`

This produces (after uglification):

`!function(){ *api bundle* }()(function(n){ *our bundle* })($fsx)`

When trying to run this the browser will error:

`Uncaught TypeError: (intermediate value)(...) is not a function`

I'm assuming it reads the above code as: api bundle gets called, then its result gets called with the next bundle, which gets called with $fsx - this seems wrong to me.

**Comment by nchanged** [comment]
@UncleDave I think you need to update `fuse-box` 
It has been fixed `2.2.0-beta.13`

**Comment by UncleDave** [comment]
Oh cool I've just been sitting on 2.1.0

**Comment by nchanged** [comment]
@UncleDave check betas from time to time. there is a major update [coming](https://github.com/fuse-box/fuse-box-examples/blob/2.2.0/examples/code-splitting/src/index.ts#L4)

**Comment by UncleDave** [comment]
That is a juicy one.
