### ISSUE TITLE
2.2.0 beta - Object.values usage

### ISSUE THREAD

**Issue by UncleDave** [fuse-box/fuse-box#626]
2.2.0 introduces usage of Object.values, the earliest version of Node that implements this (without using the --harmony flag) is 7.0.0, whereas package.json still refers to 6.9.5 being the minimum required node version.

http://node.green/#ES2017-features-Object-static-methods-Object-values

**Comment by nchanged** [comment]
Hm, which module is using it?

**Comment by nchanged** [comment]
oh right, @aretecode could you remove it from there?

**Comment by nchanged** [comment]
Fixed in `fuse-box@2.2.0-beta.14`

**Comment by aretecode** [comment]
https://github.com/fuse-box/lego-api/pull/4
