### ISSUE TITLE
typescript / react

### ISSUE THREAD

**Issue by dragosbulugean** [fuse-box/fuse-box#63]
Hey guys! How should I configure fusebox so it can compile a typescript / react project? 
Right now I get a buncha runtime errors in my browser with:
```
export const fuseBox = fsbx.FuseBox.init({
  homeDir: 'web',
  outFile: 'web/dist/app.js',
  plugins: [
    [
      fsbx.SassPlugin({ outputStyle: 'compressed' }),
      fsbx.CSSPlugin({ write: true })
    ],
    fsbx.TypeScriptHelpers,
    fsbx.JSONPlugin(),
    fsbx.HTMLPlugin({ useDefault: false }),
  ]
})
````
with tsconfig.json
```
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "jsx": "react",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "strictNullChecks": true
  }
}
```

Maybe you can point me to an example?

**Comment by Shepless** [comment]
What are your errors? Also the `TypeScriptHelpers()` plugin hasn't been called (might not fix your issue). See docs [here](http://fuse-box.org/#typescript-helpers)

**Comment by dragosbulugean** [comment]
Yes, still not working after calling TypeScriptHelpers().
```
var ExecutionEnvironment = require('fbjs/lib/ExecutionEnvironment');
```
This line from React makes ExecutionEnvironment undefined, and then this line throws:

```
var canUseCompositionEvent = ExecutionEnvironment.canUseDOM && 'CompositionEvent' in window;
```

**Comment by nchanged** [comment]
You can try this example
https://github.com/fuse-box/react-example
