### ISSUE TITLE
Babel failed to generate code when not all files are parsed by Babel.

### ISSUE THREAD

**Issue by bigdrum** [fuse-box/fuse-box#633]
I think commit https://github.com/fuse-box/fuse-box/commit/66642d44c425e69ac0ff55fc58fd9b91dcf7ce00#diff-14c35f8fffcbcbe444c9fba46923e108L240 introduced a bug by setting the babel code generator for the context.

However, not all files are parsed by Babel when the BabelPlugin is set to limit2project. So we could end of to have some files have ast from Acorn, some from Babel. The custom code generator should really be specified on a per file basis rather than setting on the context.

**Comment by nchanged** [comment]
@bigdrum 
Hi.
* I think you don't need Babel for node_modules anymore with `2.2.0-beta.16`
* It has been fixed. At least with a try catch, but we will have a better solution.

Please try the latest version and remove Babel for node_modules

**Comment by bigdrum** [comment]
Thanks, it works for me now.
