### ISSUE TITLE
Sparky task running twice

### ISSUE THREAD

**Issue by leon-andria** [fuse-box/fuse-box#639]
I'm running on fuse-box version 2.1.0.
And I found out that the issue is coming from the following code:
```
return this.start(name).then(() => this.execute(this.tasks.get(name).fn()));
```
So, looking into the master, I found out that https://github.com/fuse-box/fuse-box/blob/master/src/sparky/Sparky.ts#L85, this looks like fixed.

So my question is that why this is not fixed on version 2.1.0 that should be a stable version ?

It should be great to have a patch on version 2.1.0

**Comment by nchanged** [comment]
It's fixed in the latest 2.2 beta

**Comment by leon-andria** [comment]
I'm not running on 2.2.beta.
Why we don't have a patch versioning ? You can't force to move to a beta, we are running on a stable version.

**Comment by nchanged** [comment]
@leon-andria it's too late already, 2.2 is getting to be stable =) and the release is today/tomorrow
