### ISSUE TITLE
FuseBox css module isn't bundled with vendor

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#640]
`fuse-box-css` module isn't bundled

**Comment by BetsuNo** [comment]
May be this example is related?
[https://github.com/BetsuNo/fuse-box-css-electron-issue](https://github.com/BetsuNo/fuse-box-css-electron-issue)

**Comment by skellock** [comment]
I had this issue as well.  `+fuse-box-css` will [make it work](https://github.com/skellock/electron-starter/blob/master/fuse.js#L44) but this got me too.

I mean, I’m totally fine putting it there, just didn’t expect to.

**Comment by Shepless** [comment]
@nchanged is this still something that needs to be addressed?
