### ISSUE TITLE
Export types for bundles etc.

### ISSUE THREAD

**Issue by mattoni** [fuse-box/fuse-box#646]
I have a fairly complex fuse.ts file I run with ts-node. One of the biggest issues is that I need to keep a "global" reference to the Fusebox.init(opts) call. 

```
interface BuildVars {
    fuse?: FuseBox;
    port?: number;
    clientBundle?: Bundle;
    build?: string;
}
```

In order to keep my typings I have to pull them out from deeeeeeeeeeeep within the mysterious fuse typings folder: 

```
import { Bundle } from "fuse-box/dist/typings/core/Bundle";
import { BundleProducer } from "fuse-box/dist/typings/core/BundleProducer";
import { FuseBoxOptions } from "fuse-box/dist/typings/core/FuseBox";
```

is there a way to make these more accessible so that I can keep my types in order?
:)

**Comment by nchanged** [comment]
better? ;-)
