### ISSUE TITLE
Fluent syntax for arithmetic 

### ISSUE THREAD

**Issue by NN---** [fuse-box/fuse-box#647]
Is it planned to have fluent syntax instead of arithmetic?
http://fuse-box.org/page/bundle#arithmetic-symbols

For instance instead of ">index.js" write .output("index.js")
Or "-remove.js" write .ignore("remove.js")

And so on

**Comment by nchanged** [comment]
@NN--- not a priority ATM. We had some implementation by @aretecode 
I think you can even use it.
https://github.com/fuse-box/fuse-box/blob/master/src/arithmetic/Fluent.ts#L124

**Comment by NN---** [comment]
IMO fluent is much nicer than arithmetic language.
It is also more maintainable and doesn't require writing any parsers.

**Comment by aretecode** [comment]
@NN--- I agree, I have a plan for doing this sometime with the rest of the functionality, the fluent arithmetic should still work yup. Been working on this for the ultimate in fluent https://github.com/fluents/chain-able
