### ISSUE TITLE
In memory build

### ISSUE THREAD

**Issue by calebboyd** [fuse-box/fuse-box#648]
With webpack you can set the `outputFileSystem`, which allows you to capture the output in an in-memory filesystem (and also prevent writing to the actual fs).

Is there a way to prevent fuse-box from writing the output and just retrieve the bundle result?

**Comment by nchanged** [comment]
Hi!

We will expose the functionality, it is possible, just need a switch

**Comment by calebboyd** [comment]
This would be very helpful. Thanks!

**Comment by JamesMGreene** [comment]
@nchanged: Any idea on an ETA? Thanks!

**Comment by nchanged** [comment]
@JamesMGreene next week!

**Comment by nchanged** [comment]
http://fuse-box.org/page/configuration#writebundles
`fuse-box@2.2.1-beta.10`
