### ISSUE TITLE
SCSS/CSS Source Maps

### ISSUE THREAD

**Issue by eCustic** [fuse-box/fuse-box#649]
I can't seem to get the source maps for my SCSS or CSS files to work. 

First of all if I use SassPlugin at all I get source maps for my CSS regardless of whether or not I have `sourceMaps: true` or `sourceMaps: false`. However the `sourceMappingURL` doesn't match the generated `.map` file.

In my project I have the following structure: 
```
+ dist
+ src
    main.ts
  + styles
    - main.scss
    - _colors.scss
```
`main.ts` only has the line `import './styles/main.scss';`.
`_colors.scss` defines three colors `$red`, `$green`, `$blue`.
`main.scss` imports `_colors.scss` and declares three classes `.red`, ``.green`, `.blue` each of which set color to their respective variables.

My `fuse.js` looks like this:

```
const { FuseBox, SassPlugin, CSSPlugin } = require('fuse-box');
const fuse = FuseBox.init({
  homeDir: 'src',
  sourceMaps: false,
  output: 'dist/$name.js',
  plugins: [
    [
      SassPlugin(),
      CSSPlugin({ 
        outFile: function() { return 'dist/app.css' },
        inject: false
      })
    ]
  ]
});

fuse.bundle('app')
    .instructions('> main.ts');

fuse.run();
```

The result I get is an `app.js` in `dist` with no source map, and an `app.css` and `app.css.map`. The CSS is correct but at the end of the file this is what is says: `/*# sourceMappingURL=main.scss.map */`.

If I turn on `sourceMaps: true`, I get an additional `app.js.map` but my CSS source map stays the same.

Clearly I'm doing something wrong, can anyone help?

**Comment by nchanged** [comment]
Hi!
It's hard to tell, could u provide a sample repo?

**Comment by eCustic** [comment]
Yup, here you go: [https://github.com/eCustic/fusebox-sass-example](https://github.com/eCustic/fusebox-sass-example).

**Comment by nchanged** [comment]
@eCustic you are modifying a file name without fuse knowing about it.
Please use the configuration below.
```js
 CSSPlugin({ 
        outFile: file =>`dist/${file}`,
        inject: false
      })
```

**Comment by eCustic** [comment]
@nchanged But now it saves it as `dist/main.scss` instead of `dist/main.css`. The contents of the file are the same (compiled SCSS) but it has the wrong extension.

**Comment by nchanged** [comment]
Ok, that's a bug. I will take a look at it, thanks!

**Comment by eCustic** [comment]
@nchanged Ok, cool. I don't know if it is related, but adding `PostCSSPlugin()` after `SassPlugin()`, with or without any PostCSS plugins, causes the `sourceMappingUrl` line to be stripped from the generated CSS file. Just thought I'd mention that as well, since I'm planning to use both Sass and PostCSS.

**Comment by nchanged** [comment]
@eCustic source maps are so tedious...Please, check the fix in `fuse-box@2.2.1-beta.2`
Regarding the POSTCss after Sass yes, it kills the sourceMaps completely, as it regenerates them from scratch.

**Comment by nchanged** [comment]
Please re-open if you see that the issue persists. Closing it now

**Comment by rs3d** [comment]
@eCustic I've get it working with this config
```
 .plugin([
            SassPlugin({
              outputStyle: 'compressed',
              omitSourceMapUrl: RELEASE,
              sourceMap: `${platform.id}.${module}.css.map`,
              outFile: '', // needs to be empty if map is in the same folder as created css file
            }),
            CSSPlugin({
              inject: false,            
              outFile: file => path.join(distPath, `${platform.id}.${module}.css`)
            }),
          ])
```

**Comment by davidDuymelinck** [comment]
`SassPlugin({ sourceMap: false })`does the trick. So it looks like the SassPlugin ignores the Sourcemaps setting from the init.
