### ISSUE TITLE
Fusebox with BabelPlugin emits different result from others

### ISSUE THREAD

**Issue by johnwook** [fuse-box/fuse-box#652]
Hi. First of all, thanks for writing great things! I love the speed and easy configuration of fusebox :)
When I tried to apply fuse-box with my on-going project, I found some issue. It looks like BabelPlugin doesn't work what it'd expected.

### Issues

- When I put typescript files to FuseBox with BabelPlugin enabled, it doesn't emit the results expected.

### Original code

```js
import React from "react";
import ReactDOM from "react-dom";

const App = () => <div>Hi, there</div>;

ReactDOM.render(<App />, document.getElementById("root"));
```

1. withBabelWithFuseBox
```js
...
"use strict";

var _react = require("react");

var _react2 = _interopRequireDefault(_react);

var _reactDom = require("react-dom");

var _reactDom2 = _interopRequireDefault(_reactDom);
...
```

2. tsWithBabelWithFuseBox
```js
...
"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var react_1 = require("react");
var react_dom_1 = require("react-dom");
var App = function App() {
  return react_1.default.createElement("div", null, "Hi, there");
};
react_dom_1.default.render(react_1.default.createElement(App, null), document.getElementById("root"));
...
```

3. tsWithBabelWithWebpack
```js
...
"use strict";


var _react = __webpack_require__(82);

var _react2 = _interopRequireDefault(_react);

var _reactDom = __webpack_require__(98);

var _reactDom2 = _interopRequireDefault(_reactDom);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var App = function App() {
  return _react2.default.createElement("div", null, "Hi, there");
};
_reactDom2.default.render(_react2.default.createElement(App, null), document.getElementById("root"));
...
```

ts with FuseBox dosen' emit `_interopRequiredDefault` applied code.

to make it clear, I wrote some code [here](https://github.com/johnwook/fusebox-typescript-babel-test). You can find `tsconfig.json` or version of dependencies out there. Am I missing something? :(

Thanks, in advance!

**Comment by nchanged** [comment]
@johnwook hi! You don't need Babel at all, FuseBox transpiles required modules automatically

**Comment by johnwook** [comment]
@nchanged Yes you're right! it's true that given code does not need babel at all. I just want to use TS with ES6 import syntax with with this plugin [babel-plugin-transform-es2015-modules-commonjs](https://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/). Anyway it looks like TS with Babel does not parse code correctly as we can see from the above code :(

**Comment by devmondo** [comment]
@johnwook  it is babel issue and not Fuse, Typescript don't do default imports.

this will explain it well for you
https://github.com/Microsoft/TypeScript/issues/5565#issuecomment-155216760

**Comment by xdave** [comment]
http://2ality.com/2017/01/babel-esm-spec-mode.html

**Comment by johnwook** [comment]
@devmondo @xdave thank you for responding!

@devmondo Ok it might be an issue of babel. But as I told above, webpack with [ts-loader, babel-loader] compiles them correctly. If it's a problem of typescript, then webpack have to get the same issue, but it doesn't look like. Or if it's a problem of babel, again then webpack have to get the same issue... That's why I posted this issue to FuseBox. I'll investigate more. Please let me know if you find something :)

@xdave Should I try "spec" mode?  I can't find relevant issue from the artitle :(

**Comment by johnwook** [comment]
@nchanged Um.. If I transpile `Original Code` without Babel, fusebox output
```
var react_1 = require("react");
var react_dom_1 = require("react-dom");
var App = function App() {
  return react_1.default.createElement("div", null, "Hi, there");
};
```
something like this, which is not working becaus React and ReactDom does not export deafult

**Comment by devmondo** [comment]
@johnwook  u can use aliases for this?

**Comment by nchanged** [comment]
No, aliases have nothing to do with `exportsInterop`

This should be solved by typescript, but the only solution now is 
```
import * as react from "react"
```

**Comment by nchanged** [comment]
There is, however, a simple trick we can apply. Polyfill all used libraries with"default"

**Comment by xdave** [comment]
I would prefer if you didn't do that.  I would rather everyone converge on the spec.

**Comment by nchanged** [comment]
@xdave it adds so much trash to the source code, I dislike that

**Comment by johnwook** [comment]
Import syntax is done by [ES2015 modules to CommonJS transform
](https://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/) which is a part of [es2015 preset](https://babeljs.io/docs/plugins/preset-es2015/). So basically you don't have to make change of import( default) syntax.

What make me wonder is why babel plugin above is not applied to typescript file transpiled wit fusebox..

[**Here is source code**](https://github.com/johnwook/fusebox-typescript-babel-test)

**Comment by johnwook** [comment]
may be related to this ..? https://github.com/fuse-box/fuse-box/issues/377
I found this from [change log](https://github.com/fuse-box/fuse-box/blob/master/docs/changelog.md) but couldn't find related commits

**Comment by xdave** [comment]
@johnwook When babel introduced ES2015 Modules => CommonJS, the spec wasn't completed.  However, everyone was using it.  The spec came along and stipulated that you cannot request a default import (ie. `import Foo from 'x'`) from a module that doesn't have one.  Instead, you must `import * as Foo from 'x'`.

Typescript changed their compiler to follow the spec and ended up breaking everyone's code a long time ago.  Babel caught up later and introduced options to force your code to conform to the spec.  You have to use these babel config options:
```json
{
    "presets": [
        ["es2015", { "modules": false }]
    ],
    "plugins": [
        ["transform-es2015-modules-commonjs", {
            "noInterop": true,
            "strict": true
        }]
    ]
}
```

Here's the difference.
## Without those babel options:
### Input:
```js
import React from 'react';

const e = React.createElement('div', null, 'foo');
```
### Output:
```js
'use strict';

var _react = require('react');

var _react2 = _interopRequireDefault(_react);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var e = _react2.default.createElement('div', null, 'foo');
```

## With those strict options:
### Output:
```js
'use strict';

var _react = require('react');

var e = _react.default.createElement('div', null, 'foo');
```
This will throw an error.
The reason is because the `react` CommonJS module does not export a name `default`.  You must use `import * as React from 'react'`:
### Proper input:
```js
import * as React from 'react';

const e = React.createElement('div', null, 'foo');

```
### Proper output:
```js
'use strict';

var _react = require('react');

var e = _react.createElement('div', null, 'foo');
```
Which is what typescript does.

**Comment by johnwook** [comment]
Thank you for your kind explanation, @xdave !
In that case, I agree on following spec. Everyone should follow the spec always there are someone because of legacy.. :(
I'll change my input code as spec suggests :)

This issue can be closed now, I think. Thank you guys all!
