### ISSUE TITLE
Linked packages are not bundled

### ISSUE THREAD

**Issue by screendriver** [fuse-box/fuse-box#653]
I believe I found a bug in `fuse-box`. When you link local packages the build runs fine as expected but at runtime I get the error message `Package not found`. With other bundlers like webpack the issue does not happen.

Because the explanation of the project structure is a little bit complicated, I created a [test repo](https://github.com/screendriver/fuse-box-link-local) where you can easily reproduce the issue. Just run `yarn install && yarn run build` and start a http-server in the `dist` directory.

**Comment by nchanged** [comment]
Hi @screendriver ` "name": "@my-app/source"` it's not supported unfortunately ATM

**Comment by screendriver** [comment]
Oh, damn 😞 My whole project is structured like this because it makes the import statements more elegant and I could publish one of them separately as independent package if I want to.

Are there any plans to support linked packages? For projects that are using [lerna](https://github.com/lerna/lerna) or something (like Babel, React and so on) this is unfortunately a show stopper 😕

**Comment by screendriver** [comment]
By the way: is this a constrain because of scoped packages (`@foo/bar`) or because of linked packages in generell?

**Comment by nchanged** [comment]
No, FuseBox creates a virtual structure. It's like running on server. But you can fix it easily with aliases
http://fuse-box.org/page/configuration#alias
```
alias : { "@my-app" : "~/" }
```

**Comment by screendriver** [comment]
Unfortunately this doesn't work. Here is my new `fuse.js`:

```js
const { FuseBox, WebIndexPlugin } = require('fuse-box');

const fuse = FuseBox.init({
  homeDir: 'src',
  output: 'dist/$name.js',
  plugins: [WebIndexPlugin()],
  alias: {
    '@my-app/components': '~/components/',
  },
});

fuse.bundle('app').instructions(`>index.ts`);

fuse.run();
```

I still get `Package not found @my-app/components`

**Comment by screendriver** [comment]
Nevermind. I got it working. I don't know why, but now it works! 🎉 💃 

Thank you 👍
