### ISSUE TITLE
SourceMaps are not working

### ISSUE THREAD

**Issue by screendriver** [fuse-box/fuse-box#654]
In my project I don't get SourceMaps to work. I created a [Gist](https://gist.github.com/screendriver/4eaf651bad4472b85e9bbec7de74a780) with my `fuse.js` configuration. The only thing that I can see in my Chrome DevTools Sources Tab is "top => localhost:4444 => packages => default" but nothing more.

Am I missing something in my configuration?

**Comment by nchanged** [comment]
Have you cleared the cache?

**Comment by screendriver** [comment]
Oh, my bad. That did it. Thank you 👍 Usually I don't forget to delete the cache if something strange happen 😁
