### ISSUE TITLE
Missing 'open' option in development server

### ISSUE THREAD

**Issue by screendriver** [fuse-box/fuse-box#656]
It would be great if the dev server could open my browser automatically when I add a property called `open` to `ServerOptions`. For example:

```js
fuse.dev({ open: true }); // opens my browser
```

**Comment by nchanged** [comment]
http://fuse-box.org/page/development#opening-in-browser
`fuse-box@2.2.1-beta.11`

**Comment by screendriver** [comment]
Wohoo thank you! 👍 🎉
