### ISSUE TITLE
2.2.0 breaks report terminal colors in solarized

### ISSUE THREAD

**Issue by tyrsius** [fuse-box/fuse-box#661]
In 2.1.0 this is the report on solarized dark
![image](https://user-images.githubusercontent.com/1187432/28132642-493e833a-66f2-11e7-874f-290619a9f15b.png)

Here it is in 2.2.0
![image](https://user-images.githubusercontent.com/1187432/28132664-547f7e66-66f2-11e7-9fde-a54251e6677d.png)

Notice how the files under dynamo have been blended into the background color. This issue has [come up before](https://github.com/fuse-box/fuse-box/issues/173)

**Comment by nchanged** [comment]
Thanks, milestoned
