### ISSUE TITLE
bundleing svg separely

### ISSUE THREAD

**Issue by bellomimarc** [fuse-box/fuse-box#670]
Hi, 
i develop a react web site with a lot of svg and i'm trying to split App bundle in two module.

Is it possible? 
If yes, a sample related with https://github.com/fuse-box/react-example.git it will be good enough.

Thants a lot,
Marcello

**Comment by nchanged** [comment]
hi!
This will help you http://fuse-box.org/page/bundle#arithmetic-instructions

**Comment by bellomimarc** [comment]
Thanks for replay.
This is what i do:
`app = fuse
        .bundle("app")
        .split('*.svg', 'svg > [index.jsx]')
        .instructions("> [index.jsx]")`
and i use WebIndexPlugin.
The bundle is correctly split in two blocks now!

I have only one problem, WebIndexPlugin does not add the bundle to index.js.
It seems that fuse not register the splitted bundle. Where can i fix that?

Thanks and sorry for my poor english

**Comment by nchanged** [comment]
@bellomimarc it will not add it, naturally code splitting is for lazy loading. 
So you can use `import()` to lazy load. But if you want to include it, you can do it manually too.

Feel free to re-open the issue, if you feel like you have any problems with it.
