### ISSUE TITLE
Allowing fuse-box-css module on Server

### ISSUE THREAD

**Issue by leon-andria** [fuse-box/fuse-box#674]
For SSR, it should be good to have fuse-box-css module available rather than having error message that this module is not available.

**Comment by nchanged** [comment]
https://github.com/fuse-box/fuse-box/blob/master/modules/fuse-box-css/index.js#L18
this module is "working" on server. It's not reporting errors

**Comment by devmondo** [comment]
it is important to mention that this module needs to be added to the arithmetic instructions on the server bundle to remove the error above.

**Comment by JohnLouderback** [comment]
@devmondo  How does one do that?

**Comment by devmondo** [comment]
@JohnLouderback for example `fuse.bundle("app").instructions("> index.ts + fuse-box-css")`
