### ISSUE TITLE
CSSResourcePlugin adds extra ) to url block

### ISSUE THREAD

**Issue by Martaver** [fuse-box/fuse-box#675]
I am having the weirdest fuse-box issue...

I have a project using CSSResourcePlugin like so in my stack:

```
[
      SassPlugin({
        importer: true
       }),
      CSSModules(),
      CSSResourcePlugin({
        dist: `../${BUILD_PATH}/assets`,
        resolve: (f) => `/assets/${f}`
      }),
      CSSPlugin(),
      PostCSSPlugin(),
    ],
```

I have a `scss` file referenced in a component... a class in it links to an asset which is in the same folder (an SVG):

```
background-image: url("./logo.svg"); 
```

The asset gets picked up by `CSSResourcePlugin` and moved to the `.../assets` correctly.

Even the path to the asset gets updated correctly, except for one tiny little thing:

```
background-image: url(/assets/_1615307439.svg));
```

Yep, it keeps generating an extra `)` for me at the end of the url block. Which causes it to fail.

I'm using Windows 10, TS 2.3.3, Fusebox 2.2.0... I've nuked the entire repository, cleaned yarn and rebuilt everything from scratch. Still no worky.

Meanwhile, my colleague on a Mac - for him it works fine.

This WAS working about 6 weeks ago...

I'm happy to investigate, but right now I have NO idea where to turn. Any ideas?

**Comment by nchanged** [comment]
@Martaver weird indeed. Could you help testing this regexp on your machine
https://github.com/fuse-box/fuse-box/blob/master/src/lib/postcss/PostCSSResourcePlugin.ts#L24

I guess it is matched incorrectly, on windows....

**Comment by devmondo** [comment]
is it related to this recent update?
https://github.com/fuse-box/fuse-box/commit/e9a52ac6e14f332b93b52b69191a2e566afb3574#diff-d69e0e70ed916a16bc089c2c95fb81c8R24

**Comment by nchanged** [comment]
Bug confirmed, will be fixed tomorrow

**Comment by nchanged** [comment]
Actually, `2.2.1-beta.14` this version has it fixed. I just verified.

**Comment by nchanged** [comment]
@devmondo my commit actually fixed it. It has been verified and 100% working with the new version. Closing it for now

**Comment by Martaver** [comment]
Did the trick!

Thanks... is there an easier way to keep up to date with the dev builds for
fuse-box?

I remember there was fuse-box:3333 when version 2 was being built. Where
can I go to find the latest pre-release builds listed?

**Comment by nchanged** [comment]
Oh, it's currently in the draft, but i am thinking about having a page, with the recent changes

**Comment by Martaver** [comment]
It would be handy, at least somewhere to look up the latest pre-build version number.

**Comment by nchanged** [comment]
@Martaver I will arrange that on the main fuse-box.org page along with the changes in the pipeline

**Comment by Martaver** [comment]
Great news, thanks mate!

I really love how fuse-box is coming along. R.I.P. Webpack!
