### ISSUE TITLE
Can't import preact/devtools

### ISSUE THREAD

**Issue by screendriver** [fuse-box/fuse-box#676]
I tried to import the [preact developer-tools](https://github.com/developit/preact#developer-tools) but unfortunately I get following error at runtime:

```
http://localhost:4444/preact/devtools 404 (Not Found)
preact/devtools not found on request
```

I can create a sample project if you want but it's really simple: just try to do `import 'preact/devtools';`. If you import it without devtools `import 'preact';` everything works.

**Comment by devmondo** [comment]
if you are using typescript with fuse, does it work if u do it like this `import 'preact/devtools.js'`

**Comment by screendriver** [comment]
Sorry, my fault. I deleted the fuse-box cache, did a completely reinstall of my node_modules and now it's working 🙄
