### ISSUE TITLE
Bundling *.ts and *.tsx in tests

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#681]
Dears, this is just a question. Is it possible to bundle both ts and tsx in tests?
Following does not work:

```js
testFuse
    .bundle('app')
    .test('[**/**.test.{ts,tsx}]')
```

**Comment by nchanged** [comment]
@tomitrescak i don't think so. YOu can bundle sure, but the tests need to have `.test.ts` at the end

**Comment by tomitrescak** [comment]
@nchanged .. not true .. I had ALL my test as *.tsx till now and no issues, but when I started to work on server tests I needed to bundle also *.ts and I do not know how to do it.

**Comment by nchanged** [comment]
`.test('[**/**.test.{ts,tsx}]')` seems legit...

**Comment by tomitrescak** [comment]
@nchanged it finds 0 tests that way :/

**Comment by Shepless** [comment]
@tomitrescak any joy with this? I'm doing a bit of house keeping on older issues but don't want to close if this is still an issue for you?

**Comment by tomitrescak** [comment]
Hmm, never figured this out actually, but I seem not to need it anymore ;)
