### ISSUE TITLE
Quantum: wrong documentation

### ISSUE THREAD

**Issue by screendriver** [fuse-box/fuse-box#683]
If you look at [the docs](http://fuse-box.org/page/quantum#installation) about Quantum it says:

```
UglifyJs is enabled by default
```

But in reality I see in my console output while bundling:

```sh
  → Stats
      warnings: 1,
      apiStyle: 'Optimised numbers (Best performance)'
      target: 'browser'
      uglify: false
      removeExportsInterop: true
      removeUseStrict: true
      replaceProcessEnv: true
      ensureES5: true
      treeshake: false 
```

I have to enable it manually: `QuantumPlugin({ uglify: true })`

Furthermore the build does not work when I have `UglifyJSPlugin` enabled:

```js
FuseBox.init({
  ...
  plugins: [
    isProduction && QuantumPlugin({ uglify: true }),
    isProduction && UglifyJSPlugin()
  ]
  ...
})
```

If I remove `isProduction && UglifyJSPlugin()` it works.

**Comment by nchanged** [comment]
Oh yeah, thanks i will correct that

**Comment by screendriver** [comment]
I updated my post (I pressed submit accidentally before I was finished with my text)
