### ISSUE TITLE
Bundle includes non production code

### ISSUE THREAD

**Issue by screendriver** [fuse-box/fuse-box#684]
For example:

```js
if (process.env.NODE_ENV === 'production') {
  start();
} else {
  import('preact/devtools')
    .then(() => import('./hmr'))
    .then(({ setStatefulModules }) => setStatefulModules('hmr'))
    .then(start);
}
```

If I build my project and set `NODE_ENV` to `production` with the builtin `EnvPlugin` then the production bundle still contains `preact/devtools` and my `hmr.ts` file. Furthermore I get the following warning:

```sh
Warnings:
Your quantum bundle might not work
  - Computed statement warning in default/hmr.js
```

**Comment by nchanged** [comment]
@screendriver you should use `require` statement in this case. imports are for lazy loading

**Comment by screendriver** [comment]
I know but does that matter? `require` is not ES compliant and there are some situations where I want to load it lazy on purpose.

Shouldn't it detect that the `else` block is useless because the code is not reachable when `production` was set? 🤔

**Comment by nchanged** [comment]
Yes it detects it. You don't need to set NodeEnv plugin at all, Quantum sets NODE_ENV automatically. Enable tree-shaking you will have it removed.

**Comment by screendriver** [comment]
I tried it with `treeShake: true`. It gets removed from the resulting bundle. Cool 👍 
But the warning at the end of build and the info that the file `hmr.ts` gets included still remains in my console output 😉

**Comment by nchanged** [comment]
```
 warnings : false
```
👍 

It happens because hmr part is in the bundle and gets processed anyway. 

Quantum should unwrap your if statement and leave just

```js
start()
```

**Comment by screendriver** [comment]
Ok, cool. Thank you 👍
