### ISSUE TITLE
"__fsbx_css" not defined

### ISSUE THREAD

**Issue by jvanharn** [fuse-box/fuse-box#685]
First of all, I love fuse-box, it has slashed my compile time from 20mins (with SystemJS+jspm+gulp) to just under 5s. However when I use a specific angular2 package (angular2-select) that dynamically imports stylesheets, I get into trouble.

It keeps giving me an error `Uncaught ReferenceError: __fsbx_css is not defined`, and I have traced it back to a piece of code in my bundle that exactly resembles this code:
- https://github.com/fuse-box/fuse-box/blob/b60d13d6b664253f73276f251ac39bdf42e6f996/modules/fuse-box-css/index.js
(The above code is at the time of writing in *master*, but I added the hash to keep it working afterwards)

What seems to happen is that the **__fsbx_css** function is not defined in any of my bundles, but is instead assigned to the **module.exports** variable. Which means it wont be able to call it using the other alias. In the following file it does seemingly add the alias (which appears to be an typescript source file), however I cannot find this or a compiled variant of it in my bundles:
- https://github.com/fuse-box/fuse-box/blob/93b5daca3fb1f91989983cf088b546a6f3672083/src/modules/fsbx-default-css-plugin/index.ts

After making sure that the __fsbx_css version reaches the correct function, it works (e.g. it is a problem with the above mentioned third-party package) but I still think it should be addressed.

Can anybody either tell me what I am doing wrong, fix, or help me fix the problem?

**Comment by nchanged** [comment]
Hi @jvanharn 

Thanks ;-)

Yes, that function is a legacy, which hasn't been removed (it's a bug) on async call trigger. If you are encountering this issue that means that you are dynamically requiring a CSS file that is not in the bundle. Please double check that. Regardless of your issue, it will be handled accordingly in the next beta

**Comment by nchanged** [comment]
Please, test `fuse-box@2.2.2-beta.2`

**Comment by jvanharn** [comment]
Thank you! I will test this tonight (in about 3 hours).

**Comment by nchanged** [comment]
Great!
