### ISSUE TITLE
SassPlugin import doesn't import

### ISSUE THREAD

**Issue by sjahan** [fuse-box/fuse-box#686]
Hi, 

First, thank you for that great project :D

I have a problem with the SassPlugin and the import feature of Sass: 

In my final css bundle, I get: 
`@import url(/...my project path.../node_modules/normalize.css/normalize.css);`
The path is ok, but the content of the file is not included :(

I use this configuration: 
```
const fuse = FuseBox.init({
    'homeDir': 'src',
    'output': '$name',
    'sourceMaps': !prod,
    'plugins': [
        [
            /\.s?css$/,
            SassPlugin({
                'importer': true,
                'outputStyle': 'compressed',
                'sourceMap': `.${module}.css.map`
            }),
            CSSPlugin({
                'group': 'app.css',
                'outFile': './app.css'
            })
        ],
        BabelPlugin({
            'config': {
                'sourceMaps': !prod,
                'presets': [ 'es2015' ],
                'plugins': [ 'transform-react-jsx' ]
            }
        }),
        WebIndexPlugin({
            'path': '.',
            'template': 'src/index.html'
        }),
        prod && QuantumPlugin({
            'removeExportsInterop': false,
            'uglify': true
        })
    ]
});
```

And i imported the file like that: 
`@import "~normalize.css/normalize.css";`

Is that normal?

PS: i've updated my fuse-box right now so i'm working with the last version.

**Comment by nchanged** [comment]
@sjahan Are you sure that
`node_modules/normalize.css/normalize.css` exists? 
And i don't think you can import a css file like that
Shouldn't it be:

```
@import "~normalize.css/_normalize.css";
```

These are Sass basics

**Comment by sjahan** [comment]
Thank you for your fast answer! 

The file exists, but this line is the result of my SassPlugin/CSSPlugin chain.
I think i got confused by the SassPlugin documentation that mentions :
`@import '~bootstrap/dist/bootstrap.css';` 
Plus, IntelliJ autocompleted the path for me, and I worked nightly/early on it so I trusted it...

I'm currently commuting, but as soon as I get a laptop, I'll test and give you some updates, thank you for your help!

**Comment by sjahan** [comment]
Thank you for your fast answer! 

The file exists, but this line is the result of my SassPlugin/CSSPlugin chain. My import is:
`@import "~normalize.css/normalize.css";`
I think i got confused by the SassPlugin documentation that mentions :
`@import '~bootstrap/dist/bootstrap.css';` 
Plus, IntelliJ autocompleted the path for me, and I worked nightly/early on it so I trusted it...

I'm currently commuting, but as soon as I get a laptop, I'll test and give you some updates, thank you for your help!

**Comment by nchanged** [comment]
yeah, no worries, it's to to Sass to resolve it, cuz the paths are correct

**Comment by sjahan** [comment]
Actually, I was just too tired! 
Using `@import "~normalize.css/normalize";` instead of `@import "~normalize.css/normalize.css";` did the trick! 

Thank you for your help! Finally, no problem at all with fusebox, thanks again for that wonder :)

**Comment by nchanged** [comment]
@sjahan you are more than welcome!
