### ISSUE TITLE
Acorn error

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#691]
Dears, after new update couple things are happening:

1. I am receiving following acorn error that did not appear previously:

```ts
Acorn error: Unexpected token (102:10)
File: /Users/tomi/Github/packages/webpack2-typescript-2/src/client/modules/organisations/stores/organisation_store.ts

100          });
101      },
102      async delete() { // highligted line
103          const { Utils, state } = context;
104          if (await Utils.Ui.confirmDialogAsync()) {
105              return context.Db.mutate({
106                  context,
```

Second, the CSS Resource Plugin causes generation of incorrect bundle. The input parameter to the bundle is FuseBox and it says, `FuseBox not defined`. Removing CSS Resource Plugin causes the bundle to run again.

**Comment by tomitrescak** [comment]
The version of FuseBox that I had previously was 2.0.2 and last that seems to work is 2.1.0. 2.2.0 throws this error. I am pretty sure this is a valid syntax:

```
const a = {
  async delete() { 
          const { Utils, state } = context;
          if (await Utils.Ui.confirmDialogAsync()) {
          }
  }
```

**Comment by tomitrescak** [comment]
Looks like you need to use plugin to support this: https://www.npmjs.com/package/acorn-es7-plugin

**Comment by nchanged** [comment]
@tomitrescak there is what we are using: 
https://github.com/fuse-box/fuse-box/blob/master/src/analysis/FileAnalysis.ts#L11-L12

Is it some different plugin?

**Comment by tomitrescak** [comment]
Yes it is, your plugin supports only "decorators".

**Comment by nchanged** [comment]
`fuse-box@2.2.2-beta.6` i am afraid it has become slower... or it just seems so, please test

**Comment by tomitrescak** [comment]
Hello, I could not notice any difference with speed ... only ... smoooooooth build ;)
