### ISSUE TITLE
Global context of FuseBox object

### ISSUE THREAD

**Issue by whitecolor** [fuse-box/fuse-box#693]
For the purpose of composability, ability to build reusable components with fusebox, it is needed to remove FuseBox object from global window context and made it available via module import.

The case is when one wants to use a component build with fusebox of one version of an application that uses another version of Fusebox.

**Comment by nchanged** [comment]
Not gonna happen. You need a shared object in order to share bundle scopes

**Comment by whitecolor** [comment]
> You need a shared object

Just think about it. It potentially limits fuse-box, I think probably no need to abuse real global context.

**Comment by nchanged** [comment]
It doesn't limit -no way. and there is abuse either. This is how JavaScript works. No shared object no code splitting, no vendors no - nothing. I am sorry, but there is nothing to discuss even. These are fundamentals

**Comment by whitecolor** [comment]
Yes you probably need some shared object, but I'm saying about a possible conflict, that is definitely possible to resolve. For example use unique name of shared object.

**Comment by whitecolor** [comment]
If say I want to use two applications built with different versions of FuseBox, will it work without problems?

**Comment by nchanged** [comment]
FuseBox front end API didn't have any breaking changes since the initial release last year.

**Comment by whitecolor** [comment]
I mean won't those two different components have conflicts in some other way (than just API methods)?

**Comment by nchanged** [comment]
Nope
