### ISSUE TITLE
ionicons - CSSResourcePlugin doesn't generate any resource

### ISSUE THREAD

**Issue by jezikk** [fuse-box/fuse-box#694]
CSSResourcePlugin doesn't generate any resources for ionicons package. The resource folder is created, but it's empty. Ionicons package is installed using npm and it is imported using SASS.

The following errors are displayed in the browser console:
`GET http://localhost:3000/assets/css/assets/resources/_320671712.gif 404 (Not Found)`
`GET http://localhost:3000/assets/css/assets/resources/618794844.woff `
`GET http://localhost:3000/assets/css/assets/resources/1405431714.ttf `

fuse.js:
```
const fuse = FuseBox.init({
    homeDir: 'src/',
    output: 'static/$name.js',
    target: 'browser',
    plugins: [
        [
            SassPlugin({ importer: true }),
            CSSResourcePlugin({
                dist: 'static/assets/resources',
                resolve: f => `assets/resources/${f}`
            }),
            CSSPlugin({
                group: 'bundle.css',
                outFile: `static/assets/css/bundle.css`
            })
        ]
    ],
    shim: {
        jquery: {
            source: 'node_modules/jquery/dist/jquery.js',
            exports: '$'
        },
        tether: {
            source: 'node_modules/tether/dist/js/tether.js',
            exports: 'Tether'
        }
    }
});

fuse.dev({ httpServer: true, hmr: true, port: 3000 });

fuse.bundle('assets/js/bundle').instructions('>index.ts').watch().hmr();

fuse.run();
```

The whole project is available here:
[https://github.com/jezikk/fuse-box-test](url)

**Comment by nchanged** [comment]
@jezikk that happens because your http server is not serving it. Or serving but not correctly. Make sure your express server has `static` exposed. (I see it's not)

**Comment by nchanged** [comment]
Oh i see, sorry

**Comment by nchanged** [comment]
@jezikk i checked it recently, it happens because it's not possible to resolve files. for example Sass refers to a file which is not there. In this case i would recommend pointing to a dist, instead of sass

**Comment by nchanged** [comment]
Closing it for now due to inactivity, reopen elsewise

**Comment by naoric** [comment]
@nchanged Resources are there, with `materialize-css` for example, the paths are correct.
Maybe something happens to the paths after sass is being transformed to css files? Changing to `materialize-css/dist/css/materialize.min.css` doesn't solve the issue.

**Comment by nchanged** [comment]
@naoric if you require css directly, you should remove SassPlugin, or create a separate chain for `*.css`

**Comment by naoric** [comment]
@nchanged works like a charm! thank you

**Comment by jezikk** [comment]
@nchanged  Ok, the following settings desn't work
```
fuse = FuseBox.init({
        homeDir: './',
        output: 'dist/$name.js',
        sourceMaps: true,
        plugins: [
            [
                SassPlugin({ outputStyle: 'compressed', importer: true }),
                CSSResourcePlugin({
                    dist: "dist/resources",
                    resolve: (f) => `resources/${f}`
                }),
                CSSPlugin({
                    group: 'app.css',
                    outFile: `dist/app.css`,
                    inject: false
                })
            ]
        ],
        shim: {
            jquery: {
                source: 'node_modules/jquery/dist/jquery.js',
                exports: '$'
            },
            popper: {
                source: 'node_modules/popper/dist/index.js',
                exports: 'Popper'
            }
        }
    });

    fuse.dev({ root: './', httpServer: true, port: 3000 });

    app = fuse.bundle('app')
        .watch()
        .hmr()
        .instructions('> js/index.ts')
```
This error is shown:
```
GET http://localhost:3000/dist/resources/_216027356.woff2 
GET http://localhost:3000/dist/resources/_6968626.woff 
```

**Comment by nchanged** [comment]
You resolve.option is incorrect. /resources probably? Idk depends on your http server config

**Comment by jezikk** [comment]
The problem is that the resource files are not generated - `dist/resources` folder is empty. I fixed my resolve.option path.

**Comment by nchanged** [comment]
That means that the paths in that sass file are incorrect. I would recommend using the dist file where the resources will be in place
