### ISSUE TITLE
bundle.css is bundled again

### ISSUE THREAD

**Issue by jezikk** [fuse-box/fuse-box#695]
I have the following fuse.js settings:
```
const fuse = FuseBox.init({
    homeDir: 'src/',
    output: 'static/$name.js',
    target: 'browser',
    plugins: [
        [
            SassPlugin({ importer: true }),
            CSSResourcePlugin({
                dist: 'static/assets/resources',
                resolve: f => `assets/resources/${f}`
            }),
            CSSPlugin({
                group: 'bundle.css',
                outFile: `static/assets/css/bundle.css`
            })
        ]
    ],
    shim: {
        jquery: {
            source: 'node_modules/jquery/dist/jquery.js',
            exports: '$'
        },
        tether: {
            source: 'node_modules/tether/dist/js/tether.js',
            exports: 'Tether'
        }
    }
});

fuse.dev({ httpServer: true, hmr: true, port: 3000 });
fuse.bundle('assets/js/bundle').instructions('>index.ts').watch().hmr();
fuse.run();
```

- All scss and ts files are in `src` folder
- All bundles (bundle.css and bundle.js) are generated to `static` folder

bundle.css file is bundled to a new bundle as you can see in the following log:
```
--------------------------
Bundle "assets/js/bundle"

    index.js
    ts/sliders.js
    app.scss
    bundle.css
└──  (4 files,  1.7 kB) default
└── jquery 203 Bytes (1 files)
└── tether 208 Bytes (1 files)
└── fusebox-hot-reload@0.0.0 1.8 kB (0 files)
└── fusebox-websocket@0.0.0 2.9 kB (0 files)
└── events@0.0.0 9.8 kB (0 files)
└── bootstrap@4.0.0-alpha.6 97.6 kB (0 files)
└── slick-carousel@1.6.0 82.5 kB (0 files)
└── fuse-box-css@0.0.1 1.5 kB (0 files)
size: 198.2 kB in 9s 110ms

---------------------------------------------------
Development server running http://localhost:3000
---------------------------------------------------

22:36:00: HMR is enabled
```

This show an error in browser:
![errors](https://user-images.githubusercontent.com/7671531/28756918-91f1b004-7578-11e7-810a-fc0bada2a1f0.png)

The whole project is available here:
[https://github.com/jezikk/fuse-box-test](url)

**Comment by nchanged** [comment]
@jezikk it's not resolved correctly
http://fuse-box.org/plugins/css-plugin#inject

**Comment by jezikk** [comment]
@nchanged  I'm so sorry, but I still don't understand where is the problem. I use this settings from docs:
```
CSSPlugin({
        group: "app.css",
        outFile: `${tmp}/app.css`
    })
```
So I assume that all scss > css files will be bundled into app.css and then this file can be statically linked in index.html.

**Comment by nchanged** [comment]
@jezikk they aren't linked. Unless you link it manually. The script is being appended to the HEAD, therefore we need to know how resolve it. Use `inject` tag

**Comment by jezikk** [comment]
@nchanged that is correct, I link this bundle manually in my index.html as follows:
```
<link rel="stylesheet" href="assets/css/bundle.css">
```

This is my file structure:
```
src/
static/
-- assets/
         -- css/
               -- bundle.css
         -- js/
               -- bundle.js
-- index.html
```

and my server is running in the `static` folder. So I don't know where is the problem, because all bundles are placed in the `assets` folder. I would expect this kind of error `bundle.js:19073 GET http://localhost:3000/assets/css/bundle.css ` and not this one `bundle.js:19073 GET http://localhost:3000/bundle.css `. I think that problem is somewhere in the `bundle.js`.

**Comment by nchanged** [comment]
Did you set inject : false in this case?

**Comment by jezikk** [comment]
Yes, it solved this problem. Thank you!
