### ISSUE TITLE
code-splitting is not working

### ISSUE THREAD

**Issue by misantronic** [fuse-box/fuse-box#696]
Please see https://github.com/fuse-box/fuse-box-examples/issues/4

**Comment by nchanged** [comment]
What do you mean doesn't work?
Have you tried `node fuse dist`?

**Comment by nchanged** [comment]
It's working. Run node fuse dist. I will update the documentation. Physical code splitting doesn't work in Vanilla API. that's for development

**Comment by nchanged** [comment]
![screenshot 2017-07-30 23 57 24](https://user-images.githubusercontent.com/1629088/28757417-e911b23a-7582-11e7-853f-18dc4ccb6319.png)

**Comment by misantronic** [comment]
Thanks a lot for clearing that up. I wasn't aware of this.

**Comment by dgreif** [comment]
@nchanged I'm not sure what changed in the last 4 days, but it looks like the example is indeed broken.  Running with or without `dist`, both fail in different ways.  It looks like it's trying to do physical code splitting without `dist`, which does not match up with the docs.  I'm trying to use code splitting in my own project and running into similar issues.  Any input?  Thanks in advance!

**Comment by nchanged** [comment]
care to elaborate how do they fail?

**Comment by nchanged** [comment]
Upgraded to the latest beta. No issues.
Make sure you have that one on: https://github.com/fuse-box/fuse-box-examples/blob/master/examples/react-code-splitting/fuse.js#L14

And try that example it works without problems

**Comment by dgreif** [comment]
Sorry for the lack of details earlier, I was in a hurry and wanted to get it on your radar asap.  I can confirm that setting `experimentalFeatures: true` got it working with `2.2.1`.
