### ISSUE TITLE
Angular AOT and alternate typescript compilers

### ISSUE THREAD

**Issue by calebboyd** [fuse-box/fuse-box#699]
Please correct me if I missed it, but is there a mechanism to use an alternate typescript compiler? 

Such as byots or angular's ngc? Right now it seems like the default `typescript` compiler is hardcoded.

Wondering if it would make sense to put it in a plugin. But would need a way to disclude it if you wanted to provide your own...

**Comment by devmondo** [comment]
@calebboyd  Fuse uses TS by default, but nothing prevents you from creating a plugin to plug in your favorite compiler, the same we did for babel, and even coffeescript.

**Comment by calebboyd** [comment]
As far as I can tell I cannot prevent fusebox from trying to transpile typescript. (and do it myself instead). For example, if I want to use the AOT angular compiler.

If I try to make a `.ts` plugin and use a different one I inevitably end up with:

```
{ Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at File.handleTypescript (/my/project/node_modules/fuse-box/dist/commonjs/core/File.js:283:20)
```

**Comment by calebboyd** [comment]
If i'm reading it right I can apply a plugin to a typescript file, but only if the typescript file is already cached??
https://github.com/fuse-box/fuse-box/blob/master/src/core/File.ts#L466

I could also use `onTypescriptTransform` but that still does double work if I wanted to transpile it myself.

**Comment by nchanged** [comment]
@calebboyd yes we could have an option that would override and give a full control. But there are places where typescript is mandatory as, for example, it transpiles node_modules if es6 is detected

**Comment by calebboyd** [comment]
https://gitter.im/fusebox-bundler/Lobby?at=5981e55b4bcd78af56098b63
```
@calebboyd 09:44
Why would node modules be es6?
to support treeshaking? -- if so what will typescript do anyway if its configured to output es2015 modules

@nchanged 09:45
that’s for node_modules
if there is an es6 module ts will transpiled it
@troynt feel free to improve the plugin, but don’t make breaking changes please https://github.com/fuse-box/fuse-box/blob/master/src/plugins/WebIndexPlugin.ts

@nchanged 09:46
to support running on fusebox -)

@calebboyd 09:48
I'm not following... Why would someone publish an unconsumable module on npm

@nchanged 09:48
angular

calebboyd @calebboyd 09:50
Angular is published as umd, Are you saying fusebox will consume the es2015 entrypoint?

@nchanged 09:51
well you don’t know the whole story
well fuse can consume anything
some users import es6 code from node_module
http://fuse-box.org/page/configuration#usejsnext

@devmondo 09:59
we dont control what libraries put, but for a long time, we have solved edge cases u would never ever think of, those edge cases are the result of people smoking and drinking and then creating libraries with all sort of imagination formats, structure that comes to their mind while drunk  that is why fuse can eat whatever u feed it, it was and still not a trivial task to manage internally, yet u get the awesome beauty 

@calebboyd 10:04
Okay, so you're accommodating the rollup "standard". You mentioned angular but it doesnt use either of those (it uses pkg.es2015). Which seems to be the same thing, but isn't picked up by fusebox
```

**Comment by calebboyd** [comment]
Thanks for the clarification. Is there a different codepath that handles the jsnext/es6 module transpilation? (other than File#consume?)

**Comment by patrickmichalina** [comment]
@calebboyd are you working on integrating the AOT compiler into a plugin? I have an open ticket in my starter repo for this issue I haven't had time to investigate much yet.

https://github.com/patrickmichalina/fusebox-angular-universal-starter/issues/44

**Comment by calebboyd** [comment]
@patrickmichalina yeah @dgreif and I will be looking into adding this. Right now its not too easy to use alternate typescript compilers. So I have to find a way around that first...

**Comment by calebboyd** [comment]
So, Exploring this a bit more now that 5 is out with a better compiler. -- It looks like to perform AOT using `ngc` you have to use a program. Which is problematic because fusebox makes use of transpileModule exclusively.

Any ideas on how to support that are most welcome

**Comment by sod** [comment]
This is how a poor mans integration could look like: https://github.com/sod/fuse-angular5

`fuse.js`
```javascript
const ngc = require('@angular/compiler-cli/src/main');
const {FuseBox} = require('fuse-box');

ngc.main(['--watch']);

const fuse = FuseBox.init({
    sourceMaps: true,
    homeDir : "dist/out-tsc/src",
    output : "src/dist/$name.js"
});

fuse.dev({
    root: 'src',
    open: true,
});

fuse.bundle("bundle/main")
    .instructions(`> main.aot.js`)
    .watch("dist/out-tsc/**");

fuse.run();
```

Just runs `ngc` in a separate process and fuse-box only touches the files that `ngc` emits.

**Comment by patrickmichalina** [comment]
Got this working with lazy loading! https://github.com/patrickmichalina/fusing-angular

If anyone needs it :)

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
