### ISSUE TITLE
Debugging in react

### ISSUE THREAD

**Issue by matt-erhart** [fuse-box/fuse-box#700]
In chrome with react, the source maps and error messages do not line up my original code: there are added underscores and the line numbers are different. React dev tools doesn't recognize the app. Is there an example known to have an ideal react typescript dev experience in chrome?

**Comment by nchanged** [comment]
hi @matt-erhart what do you mean added underscores?

**Comment by matt-erhart** [comment]
It's just the transpiled js. With webpack the tsx files show up in chrome.

**Comment by devmondo** [comment]
we need repo to reproduce it

**Comment by matt-erhart** [comment]
https://github.com/matt-erhart/fuseboxin

I left the error in this repo.

**Comment by nchanged** [comment]
<img width="1435" alt="screenshot 2017-08-02 22 21 48" src="https://user-images.githubusercontent.com/1629088/28893247-04c1dd84-77d1-11e7-9f13-4441f4548350.png">
Got no problems [here](https://github.com/fuse-box/fuse-box-examples/tree/master/examples/react-code-splitting) please check it out

**Comment by matt-erhart** [comment]
Yes, thanks. Updates so fast. Which option enables ts rather than js in chrome? Also, btw, this is an awesome project, but I think you need to have even better docs/more tutorials/more examples to take on webpack. Some videos on, e.g. egghead.io, would make a big difference too.

**Comment by matt-erhart** [comment]
One more thing: when I set production = true on the react code split example, it seems to finish  but I have to ctr-c to get the terminal back.

**Comment by matt-erhart** [comment]
I had to set  sourceMaps: true to get what's in your image.

**Comment by nchanged** [comment]
yes, if you want to have source maps you need to enable Source Maps, that goes without saying

**Comment by matt-erhart** [comment]
Careful man, I want you to be successful so we can put an end to js setup hell, so I'd recommend never saying 'that goes without saying'. I know you're becoming an uber expert in setup/build, but it's by far the most frustrating and arbitrary process in web development today. For example, I thought sourceMaps would be the default because why would someone want to develop on super fast dev server without sourceMaps? Anyhoo, when I have some time I might chip away at the docs, though I'm a bit less motivated now...

**Comment by nchanged** [comment]
I agree with you, that's why FuseBox exists in the first place, I didn't mean to lower your moviation. Feel free to help out with the docs, it's quite diffucult to write them pretty much alone :) Stay fused

**Comment by serkon** [comment]
I add breakpoint my endpoint.ts file at 72 but, chrome debug tool stop line 52.

Also, i add console.log to line 72 for access to point with click from console screen, but output tells me line number is 52 so when click this source it redirects me to line 52. 

I tried a lot of things but cannot resolve.  Even, I disable sourceCode and when look line number the console output, it refer to still line 52 :)

I need for all kinds of suggestions it will help. Thank you

**Comment by nchanged** [comment]
@serkon if you want to your sourcemaps to work remove `Ng2TemplatePlugin` plugin. The issue https://github.com/alex-klock/ng2-fused/issues/11 is not resolved yet.

**Comment by serkon** [comment]
Thanks for hint but i have to use it, i will wait for solution. I migrate current project to fuse and want to make minimum change.

**Comment by nchanged** [comment]
Sure, but then it's not fusebox' issue.

**Comment by serkon** [comment]
Hi again @nchanged ,
I replace all decorators to require method in "*.components.ts"  and Ng2TemplatePlugin removed from fuse.js but still getting same error. Please could you test console output for Async request success response.

**Comment by nchanged** [comment]
that has been raised already and solved, clear the cache.

**Comment by serkon** [comment]
Hi again @nchanged if we talk about .fuse and dist folder remove, i have already do dis. Is There another options which i don't know?

**Comment by nchanged** [comment]
`.fusebox` yeah, it should be all good

**Comment by serkon** [comment]
I have already did it but same problem is continue. Nothing changed.

**Comment by nchanged** [comment]
Ok, can you reproduce it with the latest release?

**Comment by serkon** [comment]
All day i have create the project from beginning. All dependencies updated with ncu -a, and used minimum configuration. The issue still continue. sadness

**Comment by nchanged** [comment]
Please check this repository https://github.com/fuse-box/angular2-example there shouldn't be any sourcemap related issues

**Comment by serkon** [comment]
I think, if *.component.ts file has an any comment inside sourcemap is refere wrong path. When I remove comments inside *.component.ts i guess referencing correct path.

**Comment by serkon** [comment]
I resolve, remove `alias` from fuse.js and add `tsconfig.json` below
```javascript
"baseUrl": ".",
"paths": {
      "~/*": ["src/*"]
 }
```
than works fine also webstorm:
`import {EndpointService} from '~/shared/services/endpoint/endpoint.service';`

next step i will try with Ng2TemplatePlugin. Maybe it work fine too.

**Comment by serkon** [comment]
Yes, Ng2TemplatePlugin also work with correct sourceMap output!

![screen shot 2017-11-01 at 03 35 46](https://user-images.githubusercontent.com/71252/32255001-6f237908-bead-11e7-88e8-84944916cd6b.png)

**Comment by serkon** [comment]
Hi, i move my angular version to latest version that is v5.0.1. And, i have updated node_modules folder with npm install. After that, sourceMap has show one more line wrong position from correct position. When moves again to node_modules folder to old version (v4.4.5) then has been showing correct position again.

**Comment by nchanged** [comment]
So you are saying that angular version affects sourcemaps?

**Comment by serkon** [comment]
At the beginning i think cause. But This is not angular 5.0.1 version issue sorry for wrong info. I manually update just angular packages everythings goes fine.  I think I get this error while upgrade the some other packages. I am trying to find what happening and which one. I will share if i catch.

**Comment by serkon** [comment]
I think, i catched the error. It's comes from "fuse-box" version. When i use "fuse-box": "^2.5.0-beta.1" sourceMaps moves 1 line below. If i return to "fuse-box": "^2.3.3" version everythings goes fine again.

**Comment by nchanged** [comment]
How about 2.4.0 ?

**Comment by nchanged** [comment]
Can u reproduce it in a repository ?

**Comment by serkon** [comment]
I will try and update this comment

**Comment by francescoporcudev** [comment]
> hi @matt-erhart what do you mean added underscores?

Hi, is  there the possibility to debug node_modules folders after fusebox debug build???

**Comment by francescoporcudev** [comment]
HI @nchanged 
I need to debug node_modules folders in vendors bundle builded with fusebox.
Is there any way to do that?
