### ISSUE TITLE
changing a tsx file resets react's this.state with hmr

### ISSUE THREAD

**Issue by matt-erhart** [fuse-box/fuse-box#707]
Is react state known to be maintained when hmr is enabled? I get reset to default state on each edit.

**Comment by nchanged** [comment]
You would need to store it someplace else.
Read up [here](http://fuse-box.org/page/development#custom-hmr)

**Comment by matt-erhart** [comment]
Just so I understand, HMR only maintains static files and doesn't retain the state of any variables in those files? People who want that still need to use something like: https://github.com/gaearon/react-hot-loader?

**Comment by nchanged** [comment]
Fuse HMR replaces a module at runtime and then retriggers an entry point. Moreover it's 5 lines of code which I sent above, u can easlity replace them with your own logic and store the state in a local variable, for example, it's very flexible
