### ISSUE TITLE
SassPlugin (with CSSModules...?) updates all SCSS files when only one was changed.

### ISSUE THREAD

**Issue by Martaver** [fuse-box/fuse-box#710]
I noticed this early on, that all my SCSS files were being pushed to client on every HMR update, even though I only changed one. I didn't think of it much because it's super fast, but now I'm starting to get quite a few and it's slowing down.

Another issue with it is that I have application lifecycle events bound to my components, and the components are reconstructed on *each* SCSS file's update. With my 20+ SCSS files, this means all my application events are re-initialized 20+ times every time I make an SCSS change. God help me if I have side-effects attached to them.

To reproduce the problem, I forked and modified the react-code-splitting demo in the fusebox-examples repository: https://github.com/Martaver/fuse-box-examples/tree/master/examples/react-code-splitting

Repro instructions:

1. fork link above and fire up the react-code-splitting
1. `node fuse` to start
1. Edit HomeComponent.scss or ContactComponent.scss
1. Observe in browser's console that HMR updates both SCSS files each change.
1. Observe also the console.log showing that AppComponent.tsx gets reconstructed on each update.

Expected behavior:
Only the changed SCSS file is updated. AppComponent is only reconstructed once. (If it all...?)

**Comment by nchanged** [comment]
`use-box@2.2.2-beta.8`
