### ISSUE TITLE
Error bundling engine.io-client (part of socket.io)

### ISSUE THREAD

**Issue by xaviergonz** [fuse-box/fuse-box#711]
engine.io-client includes a piece of code like this one
where xmlhttprequest-ssl is a package.json (installed) dependency

```js polling.js
var hasXHR2 = (function () {
  var XMLHttpRequest = require('xmlhttprequest-ssl');
  var xhr = new XMLHttpRequest({ xdomain: false });
  return null != xhr.responseType;
})();
```

it generates the following code when using fusebox with target('browser'):
```js
var hasXHR2 = function () {
    var XMLHttpRequest = require('./lib/xmlhttprequest.js');
    var xhr = new XMLHttpRequest({ xdomain: false });
    return null != xhr.responseType;
}();
```
before bundling / with browserify bundling XMLHttpRequest  is not undefined, however when bundling 
 with fusebox XMLHttpRequest becomes undefined and there's a HTTP try to GET http://localhost:63342/foobar/dist/resources/lib/xmlhttprequest.js 404 (Not Found)

Why is it working with browserify but not with fusebox?

**Comment by nchanged** [comment]
thanks for submitting the issue @xaviergonz 
Could you provide a github repository? It will help me to quickly identify the issue without spending time on setting up the project, thanks

**Comment by xaviergonz** [comment]
https://github.com/xaviergonz/fuse-box-bug

npm run build, then open the index.html file inside dist

note that I just noticed it only happens when target is set to "browser", if it is not set it seems to work correctly (but then npm uuid package gets broken)

**Comment by nchanged** [comment]
I found it.
https://github.com/socketio/engine.io-client/blob/master/package.json#L72

```
"xmlhttprequest-ssl": "./lib/xmlhttprequest.js"
```

That simply won't work, because of its being requested from `lib/transports`
Not our fault. It's a lack of standards, everyone is using these things how they like.
A solution is to use aliases in FuseBox.

```
alias : {
  	"./lib/xmlhttprequest.js" : "~/lib/xmlhttprequest.js"
  },
```
It is working, i tested the solution above myself.

**Comment by xaviergonz** [comment]
are you sure there isn't an standard for this? according to https://github.com/defunctzombie/package-browser-field-spec/blob/master/README.md - 

All paths for browser fields are relative to the package.json file location (and usually project root as a result).

**Comment by nchanged** [comment]
That's a valid point, I will see it fixed, thanks

**Comment by xaviergonz** [comment]
@nchanged this is once more broken with 2.2.3 (it is not broken with 2.2.2), apparently it is not picking up the browser section of engine-io

**Comment by xaviergonz** [comment]
I think this commit is at fault: https://github.com/fuse-box/fuse-box/commit/c364e53ce12532da4fc750e63e2b03539da5518f

**Comment by nchanged** [comment]
I will check it and add tests

**Comment by nchanged** [comment]
Will create another issue

**Comment by nchanged** [comment]
#776
