### ISSUE TITLE
Quantum pooches with bad third party javascript libraries

### ISSUE THREAD

**Issue by Martaver** [fuse-box/fuse-box#712]
As per conversation with @nchanged here (scroll down a bit): https://gitter.im/fusebox-bundler/Lobby/archives/2017/07/25

Certain JS libraries, e.g. react-router, with their imports declared in 'naughty' syntax cause Quantum to die a horrible, horrible death.

Hints from @nchanged about the issue:

> oh var i = 'function' == 'function' && require;
> http://fuse-box.org/page/configuration#usejsnext

Repo with error reproduced: https://github.com/Martaver/fuse-box-examples/tree/master/examples/react-code-splitting

Steps to reproduce:
1. Clone repro repo and run it with `node fuse` (QuantumPlugin is enabled by default)
1. Open localhost:4444 - Observe error in debugger trying to load the page.

Error is:
```
vendor.js:15160 Uncaught ReferenceError: require is not defined
    at e (http://localhost:4444/static/vendor.js:15160:45)
    at http://localhost:4444/static/vendor.js:15164:6
    at i (http://localhost:4444/static/vendor.js:15122:26)
    at $fsx.f.(anonymous function) (http://localhost:4444/static/vendor.js:15138:2)
    at Object.$fsx.r (http://localhost:4444/static/api.js:73:9)
    at $fsx.f.(anonymous function) (eval at <anonymous> (http://localhost:4444/static/api.js:44:33), <anonymous>:19:37)
    at Object.$fsx.r (http://localhost:4444/static/api.js:73:9)
    at http://localhost:4444/static/api.js:45:39
    at XMLHttpRequest.request.onreadystatechange (http://localhost:4444/static/api.js:16:17)
```

Offending line in source is:
```
var i = 'function' == 'function' && require;
```

**Comment by nchanged** [comment]
@Martaver it's quite difficult with this webpack build, 
`useJsNext` fixes it, but it breaks something else in your case?! Could you point out what exactly does it break?

**Comment by nchanged** [comment]
Oh now I see, react router module relies on a non-standard es6

**Comment by nchanged** [comment]
Ok, there is a solution, not the prettiest but what can one do if people don't follow standards.
```
fuse.register("typescript-collections", {
    main: "dist/lib/index.js",
    homeDir: "node_modules/typescript-collections",
    instructions: " "
})
```

`instructions` is required, therefore it's an empty string with one symbol, don't mind that it will be fixed.

It will work without useJsNext and keep that stupid Router intact

**Comment by Martaver** [comment]
Hi mate, your solution works, but can you give us some background on what 'register' is doing, and why it works?

**Comment by nchanged** [comment]
By default, that library points to `umd.js` which is `package.json` `main` property. And it is bundled with `webpack`
 Toggling `useJsNext` reads other properties like `js:next` and `module` which in our case is pointing to 
`dist/lib/index.js` (es6 module) It works just fine but doesn't really work with react-router heresy source code.  `Register` overrides a package. You can set a different entry point, as well as include some files which were not mentioned in require statements (like bundle HTML files and such)

**Comment by Martaver** [comment]
I see... so really, is the problem that react-router is too behind the times, or that typescript-collections is too ahead of the times... :-/

**Comment by Martaver** [comment]
Or both...

Either way, thanks mate, appreciate it!

**Comment by Janaka-Steph** [comment]
I have the same issue with reactstrap-tether - https://www.npmjs.com/package/reactstrap-tether.
I fixed it by doing this hack in fuse config:
```
 alias: {
      "reactstrap-tether": ''
    }
```
I still get a `does not provide a module` error but the app is not blocked and everything is working.
