### ISSUE TITLE
"dist/.js.js" has failed to resolve in module x

### ISSUE THREAD

**Issue by Janaka-Steph** [fuse-box/fuse-box#715]
Hello,

I use fuse-box: "^2.2.2-beta.9"

In the package.json of Reactstrap lib we have `"main": "dist/reactstrap.cjs.js"`.
It resolves to `→ WARNING Statement "dist/.js.js" has failed to resolve in module "reactstrap"`
I tried also `"main": "dist/reactstrap.es.js"` and same result
Note that `"main": "dist/reactstrap.min.js"` resolves properly

**Comment by nchanged** [comment]
which library exactly?

**Comment by Janaka-Steph** [comment]
https://github.com/reactstrap/reactstrap/blob/master/package.json

**Comment by nchanged** [comment]
What's the use case? Could you provide a sample repository or an entry point (a file)?

**Comment by Janaka-Steph** [comment]
I don't understand, I posted reactstrap repo just above.

**Comment by nchanged** [comment]
And? What are u importing? I don't have time for reproducing the error

**Comment by Janaka-Steph** [comment]
To reproduce you just need to add Reactstrap as a node modules in your fusebox project.
`npm init`
`npm i reactstrap fusebox`
`node fuse`

That's it

**Comment by nchanged** [comment]
Right, how are you importing It, I need to know the exact steps what you
aren't doing there and how

**Comment by nchanged** [comment]
Can't reproduce. Just added it, it works without problems
add target : "browser" to your fusebox config
