### ISSUE TITLE
Registering and Displaying Errors

### ISSUE THREAD

**Issue by dgreif** [fuse-box/fuse-box#717]
In a general dev cycle, you are likely to run into errors from one or more fuse plugins.  Whether it be a scss compilation error, TypeScript type error, or any other place where a developer can make a mistake.  The general strategy right now seems to be to log these errors directly to the console. Take SassPlugin for example:
https://github.com/fuse-box/fuse-box/blob/ea625759a6e7069197e75417f96677def335f1af/src/plugins/stylesheet/SassPlugin.ts#L103

I would like to propose an internal mechanism for plugins to register errors with fuse-box.  The errors could then be reported in the following places:

* In the fuse-box output at the *end* of the output for a bundle, rather than at the top before the file list
* In the result object that you get after bundling.  This could be used in CI if your production bundle has some errors in it.
* In the console of the browser if using HMR (would be really useful if you don't often look at the fuse-box output in your terminal)
* As some sort of overlay in the DOM (Nice to have in case you don't have terminal or browser console open)

Finally, it would be really nice if code outside of fuse-box could register errors as well.  Namely, if I could hook up [fuse-box-typechecker](https://github.com/fuse-box/fuse-box-typechecker) and have it automagically report type errors in my browser, that would be *amazing*.

**Comment by nchanged** [comment]
Thanks, @dgreif that would be great to have.
There is already an attempt like this:

https://github.com/fuse-box/fuse-box/blob/ea625759a6e7069197e75417f96677def335f1af/src/core/BundleProducer.ts#L69-L78

But there are a lot of places where it's just `console.log`. I absolutely agree with you, having a class where all the errors will be dumped is just great.

The best for such things is in BundleProducer 
https://github.com/fuse-box/fuse-box/blob/ea625759a6e7069197e75417f96677def335f1af/src/core/BundleProducer.ts

Everything and everyone can access this object during the bundle time.

We could start sending errors from plugins at first, do you think @dgreif you could start implementing it?

**Comment by dgreif** [comment]
@nchanged I'll start looking into it.  Thanks for being open to the idea!

**Comment by dgreif** [comment]
See https://github.com/fuse-box/fuse-box/pull/718 for the first step.

**Comment by nchanged** [comment]
@dgreif awesome!!
https://github.com/fuse-box/fuse-box/tree/error-logging

**Comment by nchanged** [comment]
@dgreif are you going to continue improving it?

**Comment by dgreif** [comment]
@nchanged sorry for the delay. I'll have another PR early next week adding styles and minimizing in the browser.

**Comment by nchanged** [comment]
Let's close this one now

**Comment by 0xorial** [comment]
I am using TypeScript because I want compiler to find certain errors that I make as early as possible. Why would this not be enabled by default somehow? And what do I need to do to get those?
