### ISSUE TITLE
select2 npm package is not loaded

### ISSUE THREAD

**Issue by devmondo** [fuse-box/fuse-box#72]
no matter what kind of import syntax we use, it just cant be loaded
only way it worked is through this

`import * as select2 from  'https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.full.min.js';`

but this wont work

`import * as select2 from 'select2/dist/js/select2.full.js';`

**Comment by nchanged** [comment]
`$` is available after that!

**Comment by nchanged** [comment]
We should create a different issue, how to automatically shim jquery
