### ISSUE TITLE
Can't import typescript files from package

### ISSUE THREAD

**Issue by sod** [fuse-box/fuse-box#722]
Given this monorepo filestructure:

```log
app/
    fuse.js
    node_modules/
        lib_a/ => symlinked <../../lib_a/>
    src/
        index.ts

lib_a/
    src/
        foo.ts
```

`index.ts` can't do:
```typescript
import {foo} from `lib_a/src/foo`
```

fuse-box actually puts it into the bundle and via debugger it was available via `require('lib_a/src/foo.ts')`, but the runtime does `require('lib_a/src/foo')` (without .ts extension) that fails.

Demo Repo https://github.com/sod/fusebox-typescript-monorepo

**Comment by nchanged** [comment]
you shouldn't explicitly set extensions when requiring a typescript file.  If you are referring to a node_module all your files need to be already transpiled.  You could try [that](http://fuse-box.org/page/configuration#custom-modules-folder) for example, but again, everything external should be transpiled (if it's ts) or you can use javascript, and fusebox will transpile it once es2015++ is detected.

**Comment by sod** [comment]
> you shouldn't explicitly set extensions when requiring a typescript file. 

i never did and also didn't in the example :)

> If you are referring to a node_module all your files need to be already transpiled.

Actually fuse-box already transpiles it (as seen in the example), just the runtime can't find it.

**Comment by sod** [comment]
Followup:

Was interested if fuse-box now handles the usecase. Tested `3.0.0-next.14` and it indeed works. Don't know what commit fixed it, but thanks for that :)

**Comment by nchanged** [comment]
@sod https://github.com/fuse-box/fuse-box/commit/91b3a287c5fd4a761d36af16982a392abfaf2a99
You now publish typescript packages to npm

The full doc isn't really yet, but there you go https://github.com/fuse-box/fuse-box/blob/doc-ver-3/docs/publishing.md
