### ISSUE TITLE
Quantum breaks ace editor

### ISSUE THREAD

**Issue by dgreif** [fuse-box/fuse-box#728]
Ace editor has the following code:

https://github.com/thlorenz/brace/blob/a417c2ed414528bd754f131d04a8aaaf66315891/index.js#L49-L50

Quantum replace `typeof module` (as it is supposed to [per the docs](http://fuse-box.org/page/quantum#configuration)).  However, this is a weird case where they actually have a local variable called `module` and it's expected to be of type `string`, not `object`.  I'm not very familiar with the AST library you are using, but I'm wondering if we could verify that it's a reference to the global `module`, and skip any local variables.

**Comment by nchanged** [comment]
That's odd, cuz last week I integrated that module successfully into React

```
import AceEditor from 'react-ace';
import 'brace/mode/css';
import 'brace/theme/xcode';


<AceEditor
                    mode="css"
                    theme="xcode"
                    value={this.state.form && this.state.form.body}
                    onChange={(value) => this.handleChange("body", value)}
                    width="100%"
                    height="600px"
                    name="UNIQUE_ID_OF_DIV"
                    editorProps={{ $blockScrolling: true, }}
                />
```

**Comment by nchanged** [comment]
@dgreif regardless, I have introduced a new option

https://github.com/fuse-box/fuse-box/blob/4e519489694f00a8b25d0aab838267d480ca6ea3/src/quantum/plugin/modifications/TypeOfModifications.ts#L6-L17

**Comment by dgreif** [comment]
@nchanged Thanks for the fix.   I still think it would be worth-while to look for local vs global variables, but this will get us by for now.

Regarding your import into react, were you using Quantum in that build?

**Comment by nchanged** [comment]
Actually no, I was just developing an app from scratch and didn't try quantum

**Comment by dgreif** [comment]
Gotcha.  Yeah, it works just fine without Quantum.  The `typeof module` replacements are the only thing that it breaks.

**Comment by nchanged** [comment]
but generally, it's quite a bad practice having it in the code ;-) that's why I am cleaning up the production code quite aggressively

**Comment by dgreif** [comment]
Yeah, it makes sense.  Just a rare case here where we need to check a little more info on the AST before removing it.  In general Quatum seems to do a really great job tho.  Tree shaking worked perfectly in our project.  Nice work @nchanged!

**Comment by dgreif** [comment]
Do you plan to do the extra step and check if `module` is a local variable, or do you only plan to have the option to turn the replacement off completely?  Feel free to close this issue if the option is all you want to do.

**Comment by nchanged** [comment]
thanks @dgreif 
Of course, I have total control over the code, I don't think it will require much time for me, I've become the AST ninja during the Quantum development hah ;-)

**Comment by calebboyd** [comment]
@nchanged Will this land in a beta in the next 6 hours? If not Do you have any documentation on how you produce a production build? (eg. consumable fuse-box npm package)

**Comment by nchanged** [comment]
@calebboyd 
```
function hello(module){
 if (typeof module === "string) {
   console.log(";-(")
 }
}
hello("123123")
```
It might happen today, can't promise anything

**Comment by nchanged** [comment]
@dgreif @calebboyd 
Ok, here is what I did.

https://github.com/fuse-box/fuse-box/blob/e31372d8b908c13cfaefd36a29d9cbaceb1f1179/src/quantum/core/FileAbstraction.ts#L487-L511

This bit ^ check for the local scope, for example `var module = {}` or `function(module)`

and this one
https://github.com/fuse-box/fuse-box/blob/e31372d8b908c13cfaefd36a29d9cbaceb1f1179/src/quantum/plugin/modifications/TypeOfModifications.ts#L11-L33

takes it into consideration.

Also, I covered it nicely with tests

https://github.com/fuse-box/fuse-box/blob/e31372d8b908c13cfaefd36a29d9cbaceb1f1179/src/quantum/tests/TypeOfReplacement.test.ts#L63-L84

It will work in 99.9999 of cases, but that 0.001 chance will not break anything, nothing will be replaced within one file is all. For example

```
if ( typeof module === "obect) {}

var hello = function(module){
  if ( typeof module === "string") {
 }
}
```

The code above will stay untouched, which is fine, but if you think about it ^, it's quite a heresy (my favourite word now), so we can consider this issue to be fixed. Feel free to improve the analysis, it's very simple now and.. well it delivers.

`fuse-box@2.2.2-beta.14`

**Comment by dgreif** [comment]
@nchanged looks like it's working great.  Thanks for getting the new beta out so quick!
