### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by graforlock** [fuse-box/fuse-box#729]
Fuse-box sometimes is unable to import a certain module, both using an out-of-the-box compiler and with `BabelPlugin()` throwing `Uncaught TypeError: Super expression must either be null or a function, not undefined`.  
I have created a repository with a fully reproducible example:

https://github.com/graforlock/super-expression-issue

The above works fine with both `webpack` and `browserify`, importing their module correctly. If that is the case for `auth0-lock`, it would possibly not work with some of the others libraries that follow the same exports practice as well.

**Comment by nchanged** [comment]
`target : "browser"` ?

**Comment by nchanged** [comment]
Problem identified, fuse resolves `core/index.js` instead of `core.js`, will be fixed soon

**Comment by nchanged** [comment]
Please test `fuse-box@2.2.2-beta.16`

**Comment by graforlock** [comment]
thanks, it now works using `require('auth0-lock').default;`
