### ISSUE TITLE
CSS Import mapping for HMR (help needed, discussion, contributing)

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#730]
Hey guys, 
The current situation with CSS (with any processor) is that HMR is not triggered when an imported file is changed. We didn't have this issue till the recent change, a valid fix where the CSSPlugin checks for the changed file. (Before that, FuseBox re-bundled all CSS)

Then the issue #723 made me think of a better way of handling it.

Why creating a hack like in Webpack, IF WE CAN DO BETTER
```
var postcssImport = require('postcss-import');
    ...
    postcss: function(webpack) {
        return [
            postcssImport({ addDependencyTo: webpack }), // Must be first item in list
            precss,
            autoprefixer
        ];
    },
```

All preprocessors use the same syntax for importing external CSS files

```
@import "file"
```

If we had a library that is agnostic to any preprocessor and to extend CSSPlugin, we could automatically extract the dependencies using a simple RegEXP. Moreover, to make it easier for the library, we could trace the chain, and tell which preprocessor is used, and match `scss` instead of, say, `less`.  Anyway like I said, I should be agnostic in the first place.

It would look like:

```
extractDeps(file).then(deps => {
  /// maybe not the best word
  context.addWatcherDependendent(file, deps)
  // deps : ["a.css", "b.css"]
})
```

What do you think? Maybe somebody has a super fast library to do that?

**Comment by nchanged** [comment]
Implemented in `fuse-box@2.2.3-beta.1` for SassPlugin and PostCSS
http://fuse-box.org/plugins/postcss-plugin#paths-for-hmr

**Comment by graforlock** [comment]
So, how does this work for SassPlugin? My current setup is:

```javascript
const fuse = FuseBox.init({
    homeDir: '',
    output: 'public/javascripts/$name.js',
    plugins: [
        [ 
            SassPlugin(), 
            PostCSSPlugin(plugins),
            CSSPlugin({ 
                outFile: file => `./public/${file}`, 
                inject: production ? false : (file) => `/${file}`
            })
        ],
        EnvPlugin({ NODE_ENV: production ? 'production' : 'development' }),
        BabelPlugin(),
        production && UglifyJSPlugin()
    ]
});
```

Like as in PostCSS 

```javascript
            SassPlugin({
                paths : [ path.resolve(__dirname, 'stylesheets/base' )]
            })
```

Is that the desired solution?

**Comment by nchanged** [comment]
@graforlock basically with Sass it's just Sass options
```
SassPlugin({
                includePaths : [ path.resolve(__dirname, 'stylesheets/base' )]
})
```
Which is understood by Sass, and at the same time by fusecss resolver.

**Comment by graforlock** [comment]
Just now trying to apply that in `fuse-box@2.2.3-beta.1`, with globs such as:

```javascript
    fuse.bundle('bundle')
        .target('browser')
        .watch(`(common/**.js|stylesheets/**.scss)`)
        .hmr()
        .instructions(`> [client/bundle.js]`);
```

And although it does recompile on refresh and `stylesheets/styles.css` modifying the `@import "base/base";` has no effect on picking up hmr. Is glob not correct?

**Comment by nchanged** [comment]
Update to the latest beta.7 and u need to import that file in your js module

**Comment by graforlock** [comment]
as in :
```
require('../stylesheets/base/_base.scss);
require('../stylesheets/styles.scss');
```
is that what you mean?

**Comment by nchanged** [comment]
Yes, or
`import "../stylesheets/base/_base.scss")`

**Comment by graforlock** [comment]
Is there supposed to be a major difference? I believe behaviour still the same as in `beta.1`.  2.2.2 rebuilds on page refresh so its okay for me as temporary (better than not doing so, as in `beta` - as it seems). Of course, I always clear the `.fusebox` cache.

**Comment by nchanged** [comment]
@graforlock if your problem persists, please create a repository where I can reproduce the issue. Closing this one for now

**Comment by graforlock** [comment]
Here is the repository:

https://github.com/graforlock/sass-compile-reproduce

I have identified the problem. 

In `index.js` :

```
require('./lib/_base.scss');
require('./styles/base/_base.scss');
require('./styles/styles.scss');
```

If `./lib/_base.scss` contains a variable declaration that `./styles/base/_base.scss` uses , it doesn't hot replace the styles  - i presume due to an error `node-sass` is unable to link the proper variables.

**Comment by nchanged** [comment]
@graforlock well of course, these are 3 separate node-sass instances. You need to use internal `@import` syntax.
