### ISSUE TITLE
how to remove api code in dist file,How to configure?

### ISSUE THREAD

**Issue by abnerCrack** [fuse-box/fuse-box#735]
in bundle.js, i get some code (Quantum API file )  like this, how can i remove it
    Because I have a lot of independent components I don't want to each component has the code.
    and also need   Removes Object.defineProperty(exports, '__esModule', { value: true }); or 
    exports.__esModule = true from the bundle

    // code warper
    (function($fsx){
     })($fsx);

    //api file
    (function() {
         if (window.$fsx) {
            return;
        };
        var $fsx = window.$fsx = {}
        $fsx.f = {}
        // cached modules
        $fsx.m = {};
        $fsx.r = function(id) {
            var cached = $fsx.m[id];
            // resolve if in cache
             if (cached) {
                 return cached.m.exports;
            }
             var file = $fsx.f[id];
             if (!file)
                return;
             cached = $fsx.m[id] = {};
            cached.exports = {};
            cached.m = { exports: cached.exports };
            file(cached.m, cached.exports);
             return cached.m.exports;
        };
    })();

**Comment by nchanged** [comment]
@abnerCrack you probably have `bakeApiIntoBundle` enabled, just get rid of it

And read up here http://fuse-box.org/page/configuration#global-variables

**Comment by abnerCrack** [comment]
@nchanged  i mean 。
>source
![image](https://user-images.githubusercontent.com/8336662/29404350-62b7d72e-8300-11e7-8c9d-a4a1dfd1351c.png)
>result
![image](https://user-images.githubusercontent.com/8336662/29404320-531fc862-8300-11e7-98cd-6b73ec760ca1.png)

**Comment by nchanged** [comment]
Yeah and? i don't see any problems here

**Comment by nchanged** [comment]
And updates?
