### ISSUE TITLE
FuseBox.remove does not work

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#736]
Hi, I am trying to remove a module from FuseBox cache and reload it (I mocked it).
Yet when I call FuseBox.remove it is not found in the cache.
I debugged it and the reason is simple:

FoseBox.remove resoles path to my module as: 

`components/schedule_admin_view/index.jsx` -> REALLY WEIRD?

While in cache this module exists as

`client/module/schedule/components/schedule_admin_view.jsx`;

So even this code will not work:

```
FuseBox.import('../components/schedule_admin_view');
FuseBox.remove('../components/schedule_admin_view'); // does not exist in cache
```

**Comment by nchanged** [comment]
@tomitrescak you gotta use FuseBox.dynamic and FuseBox.flush((f) => f)

**Comment by tomitrescak** [comment]
I just used Flush and it did the trick;) thanks!
