### ISSUE TITLE
No output when using Quantum as a bundle plugin

### ISSUE THREAD

**Issue by eddow** [fuse-box/fuse-box#737]
https://github.com/eddow/eddow-bug-expo/tree/bpq

When Quantum is not specified at `FuseBox.init` but rather in a bundle `fuse.bundle("myBundle").plugin(...)`, no output file is produced (in the `dist` folder) without warning nor error.

Note: If one bundle is using Quantum and a second one is made after even without Quantum, the second one has no output neither.

**Comment by nchanged** [comment]
Quantum should be initialized in the primary config (`FuseBox.init`) that's the only place, and it works across the instance and applied to all bundles

**Comment by slezica** [comment]
I'm having the same problem. My `QuantumPlugin()` **is defined** in the `init()` configuration.

```
{ homeDir: 'src',
  output: 'dist/assets/js/$name.js',
  tsConfig: 'tsconfig.json',
  plugins: [ QuantumPluginClass { ... } ] }
```

The same configuration without the `QuantumPlugin` works perfectly.

**Comment by nchanged** [comment]
@slezica you should inject QuantumPlugin instead.

**Comment by slezica** [comment]
Not sure what you mean. What I posted earlier was the live configuration object, printed with `console.log()`. I updated my previous comment to hold the config as written in code.

**Comment by nchanged** [comment]
@slezica I am not sure what the problem is. Do you think you can reproduce it in a repository?
