### ISSUE TITLE
How to import BundleSource class?

### ISSUE THREAD

**Issue by patrickmichalina** [fuse-box/fuse-box#738]
Can you expose more of the Classes/Interfaces?

Writing a local plugin and using 

```js
import { BundleSource } from "fuse-box/src/BundleSource";
```

throws 
```js
SyntaxError: Unexpected token import
```

**Comment by nchanged** [comment]
You are importing a raw ts file to JavaScript ...

**Comment by Shepless** [comment]
I think it is safe to close this, we have type definitions if people want to develop plugins using TypeScript.
