### ISSUE TITLE
QuantumPlugin stringifies (deep) objects in EnvPlugin

### ISSUE THREAD

**Issue by miickel** [fuse-box/fuse-box#739]
When using the QuantumPlugin after the EnvPlugin, it appears to stringify deeply nested object properties. Eg.

```javascript
const env = {
    NODE_ENV,
    config: {
        key: 'value',
        anotherKey: false,
    }
}

// ...
  plugins: [
    EnvPlugin(env),
    isProduction && QuantumPlugin(),
  ]
// ...
```

Result when `isProduction === false`:

```javascript
console.log(process.env.NODE_ENV) // 'development'
console.log(process.env.config) // { key: 'value', anotherKey: false }
```

Result when `isProduction === true`:

```javascript
console.log(process.env.NODE_ENV) // 'development'
console.log(process.env.config) // [object Object]
```

Bug or Feature?

Thanks for making my builds stupid fast, btw! 😄

**Comment by nchanged** [comment]
Np :) that's a bug Quantum replaces the values at build time, and we don't support replacing objects just yet

**Comment by miickel** [comment]
Ah ok, makes sense. I'll avoid objects for now then. Feel free to close this issue if you don't need it for reference. 👍

**Comment by nchanged** [comment]
@miickel i will keep it open and see it fixed in the next release ;-) it's not a big issue

**Comment by nchanged** [comment]
@miickel hey, I have finally investigated the issue.
```
process.env.FOOOOO = { foo: 1 }
console.log(typeof process.env.FOOOOO, process.env.FOOOOO)
```
Turns out, whatever you assign to process.env is becoming a string. And it's understandable, as these variables are agnostic to the environment, meaning that they are being read from the user's PATH.

I can't really fix it.
