### ISSUE TITLE
VueJS and TypeScript extends

### ISSUE THREAD

**Issue by thechrisde** [fuse-box/fuse-box#742]
Hello,

I'm currently trying to get fuse-box with VueJS to work. Unfortunately I'm not able to.
Every time I try it with the same structure as it was working with WebPack I get JavaScript errors in the Browser at the end,

The error I get is:
```
Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at __extends (app.js:39)
    at app.js:55
    at Number.<anonymous> (app.js:67)
    at $import (app.js:20731)
    at locals.require (app.js:20717)
    at Number.<anonymous> (app.js:10)
    at $import (app.js:20731)
    at Function.FuseBox.import (app.js:20745)
    at $isBrowser (app.js:20442)
```

Here are my files:

Fuse.js (here I tried everything I could find to get it working, so there might be a lot of unnecessary code)
```
const { FuseBox, EnvPlugin, VuePlugin, HTMLPlugin, CSSPlugin, WebIndexPlugin, BabelPlugin, Sparky, JSONPlugin, CSSResourcePlugin, TypeScriptHelpers } = require("fuse-box");

const production = false;
const fuse = FuseBox.init({
    homeDir: "./src",
    output: "dist/$name.js",
    hash: production,
    cache: !production,
    plugins: [
        TypeScriptHelpers(),
        JSONPlugin(),
        VuePlugin(),
        BabelPlugin(),
        [/node_modules.*\.js$/,
            BabelPlugin()
        ],
        [
            CSSPlugin({ group: "app.css", outFile: "./dist/app.css" })
        ],
        [
            /node_modules.*\.css$/,
            CSSResourcePlugin({ inline: true }),
            CSSPlugin()
        ],
        [            
            CSSResourcePlugin(),
            CSSPlugin({ group: "app.css", outFile: "./dist/app.css" })
        ],
        HTMLPlugin({ useDefault: false }),
        WebIndexPlugin({ template: "./src/index.html" })
    ],
    log: true,
    debug: true
    //sourceMaps: true
});

fuse.dev();

fuse.bundle("app.js")
    .instructions("> main.ts")
    .watch();

fuse.run();

Sparky.task("default", () => {
    return Sparky.watch("./assets", { base: "./src" })
        .dest("./dist");
}
);
```

main.ts
```
import * as Vue from 'vue/dist/vue.common.js'
import * as VueRouter from 'vue-router';

import HomeComponent from './components/home/home';

// register the plugin
Vue.use(VueRouter);

let router = new VueRouter({
    routes: [
        { path: '/', component: HomeComponent }
    ]
});

new Vue({
    el: '#app-main',
    router: router,
    components:
    {
        'home': HomeComponent
    },
    render: h => h(HomeComponent)
});
```

home.ts
```
import Vue from 'vue';
import Component from 'vue-class-component';
import * as Template from "./home.html";

@Component({
    template: Template
})
export default class HomeComponent extends Vue {
    msg: string = 'Testing';
}
```

home.html
```
<div class="row">
    <div class="content col-md-4">
        <h1><strong>Thank you for using <span class="text-primary">\{{msg}}</span></strong></h1>       
    </div>
</div>
```

package.json
```
{
  "name": "VueJSFuseBoxTest",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "start": "node ./fuse.js"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-plugin-transform-react-jsx": "^6.24.1",
    "babel-preset-es2015": "^6.24.1",
    "fuse-box": "^2.0.0",
    "typescript": "^2.5.1"
  },
  "dependencies": {
    "@types/node": "^8.0.24",
    "bootstrap": "^3.3.7",
    "bulma": "^0.4.1",
    "datatables.net": "^1.10.15",
    "datatables.net-autofill": "^2.2.0",
    "datatables.net-autofill-bs": "^2.0.0",
    "datatables.net-bs": "^1.10.15",
    "datatables.net-buttons": "^1.4.0",
    "datatables.net-buttons-bs": "^1.4.0",
    "eonasdan-bootstrap-datetimepicker": "^4.17.47",
    "jquery": "^3.2.1",
    "vue": "^2.4.2",
    "vue-class-component": "~5.0.0",
    "vue-property-decorator": "~4.0.0",
    "vue-router": "^2.7.0",
    "vue-template-compiler": "~2.3.2",
    "vue-template-es2015-compiler": "~1.5.2"
  }
}
```

Thank you for your help

**Comment by nchanged** [comment]
hi @thechrisde 
To begin with, it won't work the same as in webpack, as the official plugin is made just for WebPack and it's huge. But thankfully, our community members work actively to make it better and as close to as possible to the original plugin. The author Evan isn't helping us, althogh he is aware that FuseBox is 1000x faster than Webpack

Let's poke @eddow who is actively improving Vue experience with FuseBox, he might help.

**Comment by eddow** [comment]
Sure,
So, the Vue implementation in fuse-box is mainly about [single-file-components](https://vuejs.org/v2/guide/single-file-components.html). Here, you are using Vue and fuse-box "separately" - fuse-box for example doesn't know that `template: Template" means that "./home.html" has to be compiled. (in fuse-box, vue templates are transformed into constructive JS code server-side)

I think the best for you is to begin with a single-file-component and then try to extend as you can : VuePlugin is widely unfinished and under development, even though quite usable.

**Comment by thechrisde** [comment]
Thank you for the answers.

The other option is to use it as it is shown here (https://github.com/fuse-box/fuse-box-vue-seed/tree/master/src/components/none-single-file) I think?

So that there is no extend. It seems to me that the extend is causing the problem. Not the Template or something else. But I could be wrong.

**Comment by eddow** [comment]
Oops, you are right, I missed that part of the vue-seed and, indeed, never used it.
The problem I think is that something is undefined while it should be null or an object. This can come from so many things it is hard to say - I would say, try to debug in your generated code to find out what is undefined, and after find out how come it is undefined.

It is a bit of a dirty work as you dive into generated code and fuse-box source but, if you find a bug in fuse-box code, it helps fuse-box and if you find a problem in your code, you find an answer :)

**Comment by nchanged** [comment]
@thechrisde if your question is answered, can we close the issue?

**Comment by eddow** [comment]
imho - he got as much answers as he could possibly have - this doesn't mean his troubles are over though

**Comment by nchanged** [comment]
Well if there are any troubles, please create a separate issue, Closing this one for now
