### ISSUE TITLE
Compatibility issue with babel-runtime generators

### ISSUE THREAD

**Issue by geowarin** [fuse-box/fuse-box#748]
Hello,

I'm trying to use a module compiled with babel, which uses generators, from a typescript project.

When trying to import the module, I can see this error in my console:

```
Uncaught TypeError: Cannot read property 'mark' of undefined
    at vendor.js:22936
    at Number.<anonymous> (vendor.js:23007)
    at c (vendor.js:30809)
    at w.require (vendor.js:30809)
    at Number.<anonymous> (vendor.js:22676)
    at c (vendor.js:30809)
    at w.require (vendor.js:30809)
    at Number.<anonymous> (vendor.js:22210)
    at c (vendor.js:30809)
    at w.require (vendor.js:30809)
```

Looking at the code:

![screen shot 2017-08-22 at 14 35 32](https://user-images.githubusercontent.com/1045636/29565709-4e726a9a-8747-11e7-91ba-4f8712c12722.png)

The original code is the following:

```js
import _regeneratorRuntime from 'babel-runtime/regenerator';

var map = function () {
  var _ref = _asyncToGenerator(_regeneratorRuntime.mark(function _callee2(frames) {
    var _this = this;

     ...
```

So I can see that fusebox adds a `.default` after the `_regeneratorRuntime`.

Is it expected behavior and is there a workaround for this ?
Thanks!

Repro [here](https://github.com/geowarin/overlayz)

**Comment by geowarin** [comment]
![screen shot 2017-08-22 at 14 42 15](https://user-images.githubusercontent.com/1045636/29565895-217adc7e-8748-11e7-96a1-a690ec97d995.png)

**Comment by nchanged** [comment]
There is nothing wrong with it, it's being transpiled by typescript according to the specs. This library doesn't conform to js standards and uses `default` `( import a from "b" )` where module doesn't export a `default` module

**Comment by nchanged** [comment]
There is a solution, you should you use that perverted babel plugin to transform this package. 
```
["node_modules/heresy/**", BabelPlugin()]
```

**Comment by geowarin** [comment]
Thank you for your quick response!

Sorry but I might have not understood the solution.
 [I tried it](https://github.com/geowarin/overlayz/commit/b79b2479a645ad9549afd15c7660a540cd5d17c3) without success...

**Comment by nchanged** [comment]
I commented;-)

**Comment by geowarin** [comment]
I tired:

```patch
--- fuse.ts	(revision 4812c7e0fb9bd10e5d9ed38af7cc881d524ee763)
+++ fuse.ts	(revision )
@@ -8,13 +8,14 @@
     SVGPlugin(),
     CSSPlugin(),
     WebIndexPlugin({template: './src/index.html'}),
-    ["node_modules/react-error-overlay/**", BabelPlugin({
+    [/react-error-overlay.*\.js/, BabelPlugin({
       config: {
         sourceMaps: true,
         presets: ["react-app"]
       },
     })] as Plugin
-  ]
+  ],
+  debug: true
 });
 
 fuse.dev();
```

And I can see the debug output:

```
16:05:46: BabelPluginClass : Captured lib/index.js
16:05:46: BabelPlugin : 
        Configuration: {"sourceMaps":true,"presets":["react-app"]}
16:05:47: BabelPluginClass : Captured lib/overlay.js
16:05:47: BabelPluginClass : Captured lib/effects/unhandledError.js
...
```

Which indicates that the plugins picks up the files... But still the same error ! 😕

**Comment by nchanged** [comment]
Are you sure that this plugin adds requireExportsInterop?

**Comment by geowarin** [comment]
Ah ok I finally understood what you were getting at.
Unfortunately, the lib I'm trying to use does not provide original (unbabeled) source code so I'm not sure this approach will work.

**Comment by nchanged** [comment]
Then it's your who does something wrong :)

Import * as blabla from

**Comment by nchanged** [comment]
@geowarin I believe `2.2.3-beta.10` solves everything.
```
useJsNext: ["react", "react-dom"],
polyfillNonStandardDefaultUsage : true,
```

^^ Add conflicting libraries to `useJsNext` i tested it myself, works like a charm.

**Comment by geowarin** [comment]
Awesome!
I made it work: [diff](https://github.com/geowarin/overlayz/compare/workaround).

```ts
let fuse = new FuseBox({
  useJsNext: ["babel-runtime"],
  polyfillNonStandardDefaultUsage : true,
});
```

Thank you for taking the time to understand and provide an elegant way of dealing with this issue :heart: .
