### ISSUE TITLE
Code splitting and mutliple bundles HMR

### ISSUE THREAD

**Issue by graforlock** [fuse-box/fuse-box#753]
With the example bundling flow of:

```javascript
fuse.bundle('vendor')
       .target('browser')
       .instructions(`~ client/*.js`);

fuse.dev({
        port: 5000,
        httpServer: false
    });

fuse.bundle('bundle-a')
        .target('browser')
        .watch()
        .hmr()
        .instructions(`> [client/bundle-a.js]`);

fuse.bundle('bundle-b')
        .target('browser')
        .watch()
        .hmr()
        .instructions(`> [client/bundle-b.js]`);
```

Only the first (`bundle-a`) is being watched and replaced, the latter one is neglected, and effectively, only one api reloader is available at the  given time. Are there any plans to support multiple bundle sockets, or maybe there is a way to still facilitate hmr in this setup (that part seems to be missing in docs) ?

**Comment by nchanged** [comment]
@graforlock you can use multiple fuse instances, there you can use as many sockets as you wish

**Comment by graforlock** [comment]
That indeed works, although it might've been a bit more DRY this way. 

The documentation needs some more examples, just figured. I may be able to help with forking the PR for it.
