### ISSUE TITLE
Bundle analyzer?

### ISSUE THREAD

**Issue by screendriver** [fuse-box/fuse-box#755]
Just a question: are there any plans to add a functionality to analyse the bundle and it's size to see which bundle dependencies are bigger than others? For example something like [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer)?

**Comment by nchanged** [comment]
Well of course, but it's not a priority. We have plenty of other pressing issues to resolve ;-)
If you want I can help you implement it.

**Comment by screendriver** [comment]
> Well of course, but it's not a priority. We have plenty of other pressing issues to resolve ;-)

Sure 👍 I only wanted to know if you were totally against it or if this could be added at some point in the future.

Can this be done as a plugin for fuse-box or can this only resist in the core of it? Unfortunately I don't know how `webpack-bundle-analyzer` is working internally. I only know that it is analysing the generated source maps and prints everything out with D3 or so.

**Comment by nchanged** [comment]
Yes, it can be done in a plugin, and of course should be done after it has been Quantumized
`onProducerEnd(){}`

https://github.com/fuse-box/fuse-box/blob/aa732ca3583206838676f5b52c3a90f3bb9af215/src/quantum/plugin/QuantumCore.ts#L35-L58

This Class knows every single detail about packages and files, and it's super easy to extract this information. You can get sizes, dependency tree, e.t.c

**Comment by screendriver** [comment]
Ok. I will play around with it. Thank you.

**Comment by nchanged** [comment]
I think i can be a part of Quantum. Like an option `stats : true`

**Comment by screendriver** [comment]
That would be the best solution IMHO 😉

**Comment by jtmthf** [comment]
@screendriver You actually don't need the bundle analyzer tool to be integrated into your build tool. Per [this tweet](https://twitter.com/dan_abramov/status/898182013945094145) from Dan Abramov `webpack-bundle-analyzer` is somewhat inaccurate and you're better off using a tool that performs analysis off your source-maps.

- [`source-map-explorer`](https://github.com/danvk/source-map-explorer) Doesn't have the same visual appeal, but has a reputation for being accurate.
- [`bundle-buddy`](https://github.com/samccone/bundle-buddy) Is mored geared towards eliminating code duplication across split points, but also works under the same principle.

Both of these tools currently work with Fuse-Box, but one of these tools could even be integrated into a plugin to be even easier to use.

**Comment by RPDeshaies** [comment]
Any status on this ?

**Comment by nchanged** [comment]
No status, nobody is working on it, unfortunately

**Comment by vegarringdal** [comment]
@nchanged any news on this ?
Nice to think about it while making v4 so its easier to add

**Comment by nchanged** [comment]
I will be adding an API for that in v4, but I need some help building the actual analyzer

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
