### ISSUE TITLE
className not set with CSSModules

### ISSUE THREAD

**Issue by Cyberlane** [fuse-box/fuse-box#758]
Currently all my CSSModules className attributes are not being set on the HTML elements, however the classes are being injected into the head. I get no errors in the console nor terminal, and spent a couple hours trying to find answers online first, but came up empty.

The fusebox config I am running is as follows:

```js
let isProduction = false;

const fuse = FuseBox.init({
  homeDir: 'src',
  output: 'dist/$name.js',
  hash: isProduction,
  sourceMaps: !isProduction,
  plugins: [
    BabelPlugin(),
    [
      SassPlugin(),
      CSSModules(),
      CSSPlugin(),
    ],
    WebIndexPlugin({
      template: 'public/index.html',
    }),
    isProduction && QuantumPlugin({
      treeshake: true,
      removeExportsInterop: false,
      uglify: true,
    }),
  ],
});

if (!isProduction) {
  fuse.dev({
    open: true,
    port: 8080,
  });
}

fuse
  .bundle('app')
  .instructions('> index.js')
  .watch()
  .hmr();

fuse.run();
```

my npm packages are

```json
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-plugin-transform-react-jsx": "^6.24.1",
    "babel-preset-latest": "^6.24.1",
    "fuse-box": "^2.2.2",
    "node-sass": "^4.5.3",
    "postcss-modules": "^0.8.0",
    "uglify-js": "^3.0.28"
  },
  "dependencies": {
    "react": "^15.6.1",
    "react-dom": "^15.6.1"
  }
```

That jsx module not adding the className:
```jsx
import React, { Component } from 'react';
import styles from './App.scss';

class App extends Component {
  render() {
    return (<div className={styles.red}>colored words</div>);
  }
}

export default App;
```

Am I perhaps missing something obvious, or have I stumbled across a bug?

**Comment by nchanged** [comment]
And your jsx please

**Comment by Cyberlane** [comment]
I've updated my original question with the JSX in question. Please note that this works perfectly fine in my WebPack configuration - I was simply comparing WebPack against FuseBox.

**Comment by nchanged** [comment]
Unfortunately, I wasn't able to reproduce it. Here is my sass file
```css
.hello {
    color: red;
}
```

The import (i am using typescript)
```ts
import styles from "./modules.scss";
console.log(styles);
```

The output;
```
{ "hello" : "_hello_foqbe_1" }
```

And the whole config:

```
const { FuseBox, WebIndexPlugin, SassPlugin, CSSModules, CSSPlugin } = require("fuse-box");
const fuse = FuseBox.init({
    homeDir: "src",
    output: "dist/$name.js",
    plugins: [
        WebIndexPlugin({
            template: "src/index.html",
        }), [
            SassPlugin(),
            CSSModules(),
            CSSPlugin(),

        ],
    ]
});

fuse.dev();
fuse.bundle("app").hmr().watch()
    .instructions(`>index.ts`);


fuse.run()
```

Try clearing the cache, if it doesn't help, I would appreciate if you create a repository where I can see the issue.
Cheers

**Comment by Cyberlane** [comment]
You can find the code here:

https://github.com/Cyberlane/fuse-box-test

**Comment by nchanged** [comment]
@Cyberlane you babel transpiler does it wrong

```
import styles from './App.scss';
console.log(styles);
```
means `default` that's a standard which is broken by one of the babel plugins. Which means that styles should be assigned to `default`.

Please upgrade to a more appropriate babel plugin, or at least the one that conforms to es6 standards. Alternatively, you can use 

```
CSSModules({
  useDefault: false,
})
```

And continue using your implementation, but I would recommend align with the es6 spec.
![screenshot 2017-08-30 09 28 22](https://user-images.githubusercontent.com/1629088/29860312-035197d2-8d66-11e7-90fc-5be89353139b.png)

**Comment by Cyberlane** [comment]
@nchanged thanks for pointing out the issue, however I am going to have to throw this back at you.

Please update your own example repo, as my babel plugin was a copy from your example found here:
https://github.com/fuse-box/react-example

**Comment by nchanged** [comment]
Fair enough @Cyberlane 
This commit https://github.com/fuse-box/fuse-box/commit/3b793ca2e9fc118a7fb315db37d1ec6dfe7666e4 should "hack" it in `fuse-box@2.2.3-beta.14`

I personally dislike babel, too many inconsistencies
