### ISSUE TITLE
SassPlugin & RawPlugin both caching

### ISSUE THREAD

**Issue by dgreif** [fuse-box/fuse-box#760]
This configuration:
```js
[
  '*.scss',
  SassPlugin(),
  RawPlugin()
]
```
doesn't work because both the `SassPlugin` and `RawPlugin` support caching.  `SassPlugin` sets the cache and `RawPlugin` reads the sass output without doing it's normal work.  Need to find a way for multiple plugins in a row to support caching.

in `2.2.3-beta.12`

**Comment by nchanged** [comment]
Please check `fuse-box@2.2.3-beta.13`
