### ISSUE TITLE
A change of SASS dependencies doesn't trigger re-render on Windows

### ISSUE THREAD

**Issue by rs3d** [fuse-box/fuse-box#763]
(Probably only an issue on windows)

**Reproduce issue:**
1. `index.ts` imports `index.scss`
2. `index.scss` imports `nested.scss`
3. change `nested.scss` in _watch mode_ 
4. Result: `index.css` is not rebuilding. It gets only updated if i change `index.scss` afterwards.

**Examples:**
1. I've tried now https://github.com/fuse-box/fuse-box-examples/tree/master/examples/responsive_hmr_sass 
When i change `foo.scss` changes are directly visible. When I change `shared.scss` nothing happens until i change `foo.scss` again.
2. I extended my example with nested scss files: https://github.com/rs3d/fuse-box-examples/tree/master/examples/hmr-hosted-css-files/src
It seems like it's conntected to the folder structure somehow. If I move `\hmr-hosted-css-files\src\styles\_imported.scss` and `\hmr-hosted-css-files\src\styles\_variables.scss` one level up it seems to work...
3. I've updated @graforlock's repo with the current version: https://github.com/rs3d/sass-compile-reproduce

See also here: https://github.com/fuse-box/fuse-box/issues/757

**Comment by nchanged** [comment]
Could you guys debug this piece for me on windows?
https://github.com/fuse-box/fuse-box/blob/a88a2eb7109847cf8e1b41bad6e3b65fb428aa54/src/plugins/stylesheet/CSSplugin.ts#L134-L137

I am interested in  `lastFile` `file.info.fuseBoxPath`

If the bug is not there, then there is this function

https://github.com/fuse-box/fuse-box/blob/a88a2eb7109847cf8e1b41bad6e3b65fb428aa54/src/core/File.ts#L436-L461

Which is related to the functionality, it's probably best to debug filename there.

Thanks

**Comment by rs3d** [comment]
Hi @nchanged 

I've tested this repo and added console logs to the corresponding fuse box js files (don't know how the easiest/best way to debug this in the ts src files): https://github.com/rs3d/fuse-box-examples/tree/master/examples/hmr-hosted-css-files

1. Changing `index.scss`
![image](https://user-images.githubusercontent.com/1399149/29960807-78278236-8efd-11e7-8900-4c8fdaf3542c.png)
2. Changing `_variables.scss` (no bundle update)
![image](https://user-images.githubusercontent.com/1399149/29960875-ae273124-8efd-11e7-9d12-6a5aa0f49fd4.png)
3. Changing `_imported.scss`(no bundle update)
![image](https://user-images.githubusercontent.com/1399149/29960924-e596f46e-8efd-11e7-838d-e1c00db065d8.png)

So `emitRequired` is never set `true` with this if clause in step 2 and 3:
![image](https://user-images.githubusercontent.com/1399149/29961308-8286c460-8eff-11e7-919b-6cb15b9ed8a3.png)

**Comment by rs3d** [comment]
debugging `fileDependsOnLastChangedCSS`
![image](https://user-images.githubusercontent.com/1399149/29962896-1f6ca704-8f05-11e7-9080-07dcd41c8c72.png) and https://github.com/fuse-box/fuse-box/blob/a88a2eb7109847cf8e1b41bad6e3b65fb428aa54/src/plugins/stylesheet/SassPlugin.ts#L93

1. Changing `index.scss` 
![image](https://user-images.githubusercontent.com/1399149/29963567-a1a9be12-8f07-11e7-984e-8b7f3706ef19.png)
2. Changing `_variables.scss` 
![image](https://user-images.githubusercontent.com/1399149/29963602-be208530-8f07-11e7-97ad-28216964d783.png)
3. Changing `_imported.scss`
![image](https://user-images.githubusercontent.com/1399149/29963772-4ea5121a-8f08-11e7-97ce-6236ca2da3d1.png)

**Comment by nchanged** [comment]
Let's try replacing in File.ts
```
const absPath = ensureFuseBoxPath(collection[this.info.absPath][i]);
                if (absPath.indexOf(bundle.lastChangedFile) > -1) {
                    this.context.log.echoInfo(`CSS Dependency: ${bundle.lastChangedFile} depends on ${this.info.fuseBoxPath}`)
                    HMR_FILE_REQUIRED.push(this.info.fuseBoxPath);
                    this.context.setItem("HMR_FILE_REQUIRED", HMR_FILE_REQUIRED);
                    return true;
                }
```

**Comment by rs3d** [comment]
Kudos, it's working with your patch!

**Comment by nchanged** [comment]
`fuse-box@2.2.3-beta.19` let's close this one. Just confirm that it works in this beta

**Comment by rs3d** [comment]
Confirmed!

**Comment by guillaume86** [comment]
Is it possible the LESS plugin has the same issue? After updating from 2.1.0-beta.2 to 2.2.2 (and setting `target: browser` to fix an unrelated issue), I lost the live CSS reloading when changing nested .less files.

I tried the fuse-box@2.2.3-beta.19 and it didn't fix the issue, I'm also on windows.

**Comment by nchanged** [comment]
@guillaume86 oh yeah, LESS is not there, Please submit an issue
