### ISSUE TITLE
Add support for PostCSSPlugin configuration

### ISSUE THREAD

**Issue by rs3d** [fuse-box/fuse-box#765]
Currently there is no way to disable **SourceMaps** entirely via FuseBox config or per bundle when the **PostCSSPlugin** gets applied. 

It would be nice to have an option parameter for the PostCSSPlugin (https://github.com/fuse-box/fuse-box/blob/master/src/plugins/stylesheet/PostCSSPlugin.ts#L80) to make adjustments how sourcemaps are handled. (Options: https://github.com/postcss/postcss/blob/master/docs/source-maps.md Default: `inline`)

**Suggestion:**
```
bundle.PostCSSPlugin({
              plugins: [plugin1, plugin2, plugin3],
              map: { inline: false }
            })
```

**Comment by nchanged** [comment]
Please verify in `fuse-box@2.2.3-beta.20`

**Comment by rs3d** [comment]
Looks good, thank you!
