### ISSUE TITLE
arbitrary variables in WebIndexPlugin

### ISSUE THREAD

**Issue by FredericHeem** [fuse-box/fuse-box#769]
Would it be possible to inject any kind of variable with `WebIndexPlugin`?

**Comment by nchanged** [comment]
Yes, we can enable that.

**Comment by pyros2097** [comment]
This should be possible with the new templateString attribute in WebIndexPlugin. You just need to use es6 string templates and inject you variables into it.

**Comment by Shepless** [comment]
Closing as we now have this feature. Please re-open if it is not working for you @FredericHeem
