### ISSUE TITLE
inline styles need to be loaded before js files

### ISSUE THREAD

**Issue by devmondo** [fuse-box/fuse-box#77]
i dont know if it is there or not but the below  does not work, what i mean is that styles are loaded but only after `app` import is executed.

```
import './styles/main.scss';
import  './app';
```

**Comment by nchanged** [comment]
They are loaded in order, JavaScript appends them to the head, I am afraid nothing can be done there

**Comment by devmondo** [comment]
ok  i will try to change my strategy and see
