### ISSUE TITLE
code split with dependencies

### ISSUE THREAD

**Issue by FredericHeem** [fuse-box/fuse-box#771]
This is a follow up from PR https://github.com/fuse-box/fuse-box-examples/pull/9

When code imported with `import` contains third party dependencies, fuse doesn't include these external dependencies.

Steps to reproduce the problem:

```
git clone https://github.com/FredericHeem/starhackit.git
cd starhackit/client
git checkout fusebox
npm i
node fuse
```

Click on the menu and select `THEME`

`localhost/:1 Uncaught (in promise) Package not found react-color`

Click on `DB SCHEMA`

`lodash/map not found on request`

Click on `ADMIN`

`Package not found reactabular-table`

This is a blocker that prevents me from getting rid of webpack.
I beg your support on this specific issue.

**Comment by nchanged** [comment]
Ok, and what if that package belongs to multiple split bundles?

**Comment by FredericHeem** [comment]
It is a very valid point, code splitting is far from being a trivial feature.
For simplicity, let's copy the package to the bundles who require it if not already included in the vendor.
Alternatively, if it's a package used by multiples bundles, let's manually add it to the vendor.

**Comment by nchanged** [comment]
Indeed, and a tricky way to detect if a package was not added manually, automatically. I spent weeks trying to figure it out. Needs investigation.

**Comment by nchanged** [comment]
@FredericHeem that's coming very very soon. Stay tuned, you will be able to play with it already tomorrow.
