### ISSUE TITLE
Timeout for test-runner

### ISSUE THREAD

**Issue by dakom** [fuse-box/fuse-box#772]
Originally from https://github.com/fuse-box/fuse-test-runner/issues/12

( @nchanged  asked me to put a reminder here )

**Comment by nchanged** [comment]
so odd, the deployed version doesn't contain this if condition ...

**Comment by dakom** [comment]
hehe ;)

**Comment by nchanged** [comment]
`fuse-test-runner@1.0.14`

Alternatively, you can set `timeout` property
```
export class TimeoutTest {
    timeout: 30000;

    'Timer test'(done) {
        console.log(`---- TIMEOUT VALUE FROM TEST: ${process.env.FUSE_TEST_TIMEOUT}`);

        const amount = 500;
        const target = 10000;
        let total = 0;
        const interval = setInterval(() => {
            should(true).equal(true);

            total += amount;

            if (total === target) {
                clearInterval(interval);
                done();
            }

            console.log(`Current total: ${total}`);
        }, amount);
    }
}

```

**Comment by dakom** [comment]
Nope, still failing: https://github.com/dakom/temp-fuse-test/blob/timer-test/src/tests/TestInit.test.ts

**Comment by dakom** [comment]
okay semi-resolved... upgrading to `fuse-test-runner@1.0.14` fixes it for the ENV variable, but setting the timeout property in the class does not work.

I'd still consider this broken since different tests may want to set different timeout variables, shouldn't be constant from environment

**Comment by nchanged** [comment]
@dakom how are you setting it?

**Comment by dakom** [comment]
```
export class TesterInit {
    timeout: 30000;
    
    'Timer test'(done) { ... }
}
```

**Comment by dakom** [comment]
That doesn't work. Setting the FUSE_TEST_TIMEOUT env variable does, but then that can't be nicely adjusted per-test

**Comment by dakom** [comment]
here I made it easier for you to see, on the `timer-test` branch at https://github.com/dakom/temp-fuse-test/tree/timer-test

`npm run test` fails and `npm run test:env` passes. 

In other words the environment variable works but the timeout property does not

**Comment by nchanged** [comment]
Set a property, not typing
```
timeout = 30000;
```
