### ISSUE TITLE
Is it possible to dynamically load ad-hoc modules on demand not known during build time

### ISSUE THREAD

**Issue by maximusk** [fuse-box/fuse-box#774]
In our application we use Webpack for the build. However, since our application is a platform we need to load 3rd party plugins packaged as ESM/CommonJS modules during runtime. The important constraint is that we don't know which plugins we will need to load. Webpack can only dynamically load modules it knows about during build time so we also need to use SystemJS:

```
fetch('plugins-list').then((list)=>{
   list.forEach((p)=>{
      SystemJs.import(p.path).then()
   }
}
```

FuseBox is described as a bundler/module loader that combines the power of webpack, JSPM and SystemJS. So I thought maybe it can also load ad-hoc modules dynamically that are not known during build time which will replace two module loaders (Webpack and SystemJS) in our project with one FuseBox.

Any comments are highly appreciated!

**Comment by nchanged** [comment]
Hi @maximusk you can use `FuseBox.import` or just `require` to load modules that are not in the bundle.

Also, you can use `import("./module.js")` it's all [here](http://fuse-box.org/page/dynamic-import)

You can also use [wildcard imports](http://fuse-box.org/page/loader-api#wildcard-import) if you wish.

**Comment by maximusk** [comment]
@nchanged , thanks for the prompt reply. I've tried to use `import()` and it works fine with dependencies resolved during build time. However, the following setup fails:

// src/list.txt
`./src/a.js`

// bundled module
var myRequest = new Request('src/list.txt');
```
fetch(myRequest).then((response)=>{
  response.text().then((name)=>{
    console.log(name); // logs `/src/a.js`
    import(name).then((m) => {
      console.log(m); // logs `undefined`
    });
  });
});
```

**Comment by nchanged** [comment]
@maximusk there is something off with your config
I have just added a similar example:

https://github.com/fuse-box/fuse-box-examples/tree/master/examples/dynamic_import_js

**Comment by maximusk** [comment]
@nchanged , thanks, but your example uses import path that can be resolved during build time. As I said, I tried that and it works fine. When it doesn't work is when it's not possible to resolve module path at the build time:

```
fetch(myRequest).then((response)=>{
  response.text().then((name)=>{
    import(name).then((m) => {   <----- we don't know here what `name` will be during build
```

**Comment by nchanged** [comment]
No, there is not `target.js` during the build time. You can check the `src/` folder. 
Dist folder contains `target.js` (which is simply copied there for the testing purposes)

**Comment by maximusk** [comment]
@nchanged , but you specify the name here:

``import("./target.js")`

when building, correct? I don't know the name in advance

**Comment by nchanged** [comment]
```
const a = "./target.js"
import(a)
```
the same result

**Comment by maximusk** [comment]
@nchanged , thanks a lot for you help. I figured it out. I didn't include

`experimentalFeatures: true,`

into the configuration.

**Comment by nchanged** [comment]
@maximusk yep, also this one:
https://angular.patrickmichalina.com/
@patrickmichalina knows so much about fuse + ng2, you can have a chat with him.
There were plans on making `angular-fuse-cli`

**Comment by maximusk** [comment]
@nchanged , great, thanks. Also if I was willing to start contributing, where would I begin? Some docs describing internal architecture would be very beneficial.

**Comment by nchanged** [comment]
@maximusk not at the moment. Hopefully, this week I write some guide.

**Comment by maximusk** [comment]
@nchanged , okay, thanks, if there's anything let me know please

**Comment by maximkott** [comment]
@nchanged Is this still possible? The doc links seem to be broken
