### ISSUE TITLE
Using `./` as homeDir results in unresolvable npm package

### ISSUE THREAD

**Issue by rs3d** [fuse-box/fuse-box#775]
When I use `import * as isNumber from "is-number";` from `node_modules` with `FuseBox.init({homeDir: './'})` the resulting bundle contains:
```
FuseBox.pkg("is-number@2.1.0", {"kind-of":"3.2.2"}, function(___scope___){
```
which results in an error: `events@0.0.0:308 Uncaught Package not found is-number`

Switching to `homeDir: './app'` is working correctly and results in:
```FuseBox.pkg("is-number", {}, function(___scope___){```

**Comment by nchanged** [comment]
@rs3d this has been fixed with the latest beta, and a stable version will be released this week
