### ISSUE TITLE
Browser field doesn't respect direct node_module references

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#776]
Subj:
Example: https://github.com/socketio/engine.io-client/blob/master/package.json#L72

#770
#711

**Comment by nchanged** [comment]
@xaviergonz

https://github.com/fuse-box/fuse-box/releases/tag/v2.2.31

**Comment by xaviergonz** [comment]
@nchanged thanks! working once more

**Comment by nchanged** [comment]
Shouldn't get broken anymore :) it's covered :)
