### ISSUE TITLE
CSSModules issues

### ISSUE THREAD

**Issue by Fjandin** [fuse-box/fuse-box#777]
I have played around with the react-example and CSSModules and found some issues

I have added this alias.
```
alias: {
    styles: '~/styles',
    images: '~/images'
},
```
However, it seems alias is not working when in a css file for exampe:
```
@value blu from 'styles/colors.css';
```

Another thing is that when running in dev mode and i make any change it will result in 
```
SyntaxError: Unexpected token o in JSON at position 1
    at Object.parse (native)
```
Seems it adds css to the main js file?
![image](https://user-images.githubusercontent.com/167869/30039397-6e5d9198-91d0-11e7-820a-9d1c12a88b6a.png)
This only happens when `sourceMaps: true`

This is my playground project.
https://github.com/Fjandin/react-example

PS! I'm very new to fuse-box so might be because i'm doing something wrong. If that's the case... sorry :P

**Comment by nchanged** [comment]
Hi :)
You almost got it right, CssModules needs to come after PostCss plugin

**Comment by Fjandin** [comment]
HI

I tried movin `CssModules` after `PostCss`, but I still am having the same issues. Both with the alias not working and sourcemaps corrupting the main js file.

**Comment by nchanged** [comment]
@Fjandin aliases are related only to javascript code, it has nothing to do with CSS.
You need to utilize some PostCSS modules that handles the replacement.
We have it in Sass, for example, http://fuse-box.org/plugins/sass-plugin#macros but that's because Sass supports it out of the box

**Comment by Fjandin** [comment]
ah ok. Fair enough 👍 

But about the other issue... any idea what could cause this?

This is the output i get from fusebox:

https://gist.github.com/Fjandin/9ba060988b5a21a22f99b5fd5b08fab3

basically as soon as i change any file i get a `SyntaxError: Unexpected token o in JSON at position 1` error.

**Comment by nchanged** [comment]
Well, it's kind of because your PostCSS spits and error that breaks fusebox, that shouldn't happen in fact, and will be fixed soon.

**Comment by cmizzi** [comment]
Error is only thrown if `sourceMaps: true` because `JSON.parse({})` is called. The bug seems to be provided by the `CSSPlugin` that handles `souceMaps: {}` in the file configuration

**Comment by Fjandin** [comment]
It's weird that i can't find anything on this. Am i the only one using css modules together with postcss? :P + wants sourcemaps

**Comment by cmizzi** [comment]
This configuration works : 

```js
const {FuseBox, PostCSSPlugin, CSSPlugin} = require('fuse-box')
const fuse      = FuseBox.init({
	homeDir    : 'sources',
	output     : 'built/$name.js',
	log        : true,
	sourceMaps : true,
	plugins    : [
		[
			'style/**.css', 

			PostCSSPlugin([require('autoprefixer')(), require('precss')()], {
				sourceMaps: true,
			}),
			CSSPlugin({ group: 'app.css', inject: (file) => `built/${file}`, outFile: 'built/app.css' })
		],

		CSSPlugin({ group: 'vendor.css', inject: true }),
	],
	useTypescriptCompiler : true
})

fuse.dev({ root: './', port: 8081, devServer: false })
fuse.bundle('vendor').instructions('~ index.ts').watch().hmr()
fuse.bundle('app').instructions('!> [index.ts]').watch().hmr()

fuse.run()
```

```bash
fusebox master ✗ 51e87b9 ✖ △ ➜ tree sources
sources
├── index.ts
└── style
    └── app.css

fusebox master ✗ 51e87b9 ✖ △ ➜ cat sources/index.ts 
import './style/app.css'

fusebox master ✗ 51e87b9 ✖ △ ➜ cat sources/style/app.css 
body {
	background: black;
}
```
I don't know why but it's very redundant to repeat the `outDir` configuration into the `CSSPlugin:outFile` and `CssPlugin:inject` object members in order to make `HRM` working...
