### ISSUE TITLE
TS/SassPlugin and SCSS imports have different paths in SourceMaps file

### ISSUE THREAD

**Issue by rs3d** [fuse-box/fuse-box#778]
### Steps to reproduce:

1. in `app/index.ts` => `import('index.scss');`
2. in `app/index.scss` => `@import 'sub';`
3. use following setup: 

```
const {
  FuseBox,
  SassPlugin,
  CSSPlugin,
} = require('fuse-box');

const path = require('path');

const basePath = 'app';
const distPath = 'dist';

const fuse = FuseBox.init({
  homeDir: basePath,
  output: `${distPath}/$name.js`,
  tsConfig: 'tsconfig.json',
  log: true,
  debug: true,
  cache: false,
  sourceMaps: {
    inline: false,
    sourceRoot: `/${basePath}`
  }
});

fuse.bundle(basePath)
  .plugin([
    SassPlugin({
      sourceMap: true,
      outputStyle: 'compressed'
    }),
    CSSPlugin({
      inject: file => `/${file}`,
      outFile: file => `${distPath}/${file}`
    })
  ])
  .target('browser')
  .instructions(`> index.ts`);

fuse.run();
```
### Demo:
https://github.com/rs3d/fuse-box-sass-issue

### Results in `dist/index.scss.map`
```
{"version":3,"file":"index.scss","sources":["/app/index.scss","/app/app/_sub.scss"],"names":[],"mappings":"ACAA,AAAA,IAAI,AAAC,CACD,UAAU,CAAE,GAAG,CAClB,ADAD,AAAA,IAAI,AAAC,CACD,KAAK,CAAE,IAAI,CACd"}
```
==> wrong path here `/app/app/_sub.scss`

**Comment by rs3d** [comment]
Forgot to mention that i used FuseBox with this PR https://github.com/fuse-box/fuse-box/pull/773/files
Without this change `_sub.scss` is not included as source.

**Comment by zigmo** [comment]
@rs3d - if you move `_sub` one level down e.g. `styles/_sub.scss` helps right? This is what I was thinking of as I created the PR. I tried to avoid any breaking changes of this [line](https://github.com/fuse-box/fuse-box/blob/813bc793c7d9de764a5f9aac64889233426f2c0a/src/core/File.ts#L594)  - ofc I don't know if its a breaking change.

I think the best way to tackle this is to change the node-sass options [here](https://github.com/fuse-box/fuse-box/blob/813bc793c7d9de764a5f9aac64889233426f2c0a/src/plugins/stylesheet/SassPlugin.ts#L61) and add `file` property to something like this

```ts
const options = Object.assign({
    data: file.contents,
    sourceMap: true,
    file: file.info.absDir+"/"+file.info.fuseBoxPath,
    outFile: file.info.fuseBoxPath,
    sourceMapContents: true
}, this.options);
```
this will also remove `stdin` from the sources and provide the correct path. `file.info.absDir` also helps to have the right path hierarchy (with subforlder e.g. /src/index.scss or /app/index.scss). Currently you get somethink like `index.scss` (with this.info.fuseBoxPath) for the root file but `src/sub.scss` for all related. So its not following the same schema or I'm wrong?

and change it [here](https://github.com/fuse-box/fuse-box/blob/813bc793c7d9de764a5f9aac64889233426f2c0a/src/core/File.ts#L592) to:

```ts
jsonSourceMaps.sources = jsonSourceMaps.sources.map((source : string) => {
    return this.context.sourceMapsRoot + "/" + source;
});
```

And for `sourceRoute:''`` this [line](https://github.com/fuse-box/fuse-box/blob/813bc793c7d9de764a5f9aac64889233426f2c0a/src/core/WorkflowContext.ts#L330) need to be adjust to:

```ts
if (params.sourceRoot || params.sourceRoot === '') { }
```
so the result for the repo with  `sourceRoot :''` would be:

```
{"version":3,"file":"index.scss","sources":["/app/index.scss","/app/_sub.scss"],"names":[],"mappings":"ACAA,AAAA,IAAI,CAAC;EACD,UAAU,EAAE,GAAG;CAClB;;ADAD,AAAA,IAAI,CAAC;EACD,KAAK,EAAE,IAAI;CACd"}
```

and with not providing sourceRoot (be default its ./src:

```
{"version":3,"file":"index.scss","sources":["/src/app/index.scss","/src/app/_sub.scss"],"names":[],"mappings":"ACAA,AAAA,IAAI,CAAC;EACD,UAAU,EAAE,GAAG;CAClB;;ADAD,AAAA,IAAI,CAAC;EACD,KAAK,EAAE,IAAI;CACd"}
```

I can craft a small PR if its ok to solve it this way. @rs3d @nchanged What do you think?

**Comment by nchanged** [comment]
@zigmo sounds good to me ;-) thanks for you help!

**Comment by zigmo** [comment]
@nchanged sure? I think e.g. examples will not work anymore by default, because `/src` will be added by default but sourceMaps now respect the hierachy. So I have to set ``sourceRoot:''` to make it work by default. Don't you think that a lot of people have their source in `/src` and this worked before out of the box and now this will be `/src/src/....` - or I'm wrong?

**Comment by nchanged** [comment]
@zigmo I haven't gotten into it yet.  I think we can default it to `sourceRoot:''`

**Comment by zigmo** [comment]
@nchanged I'm just concern about the side effect on [this line](https://github.com/fuse-box/fuse-box/blob/813bc793c7d9de764a5f9aac64889233426f2c0a/src/core/File.ts#L566) for typescript

with respecting of `sourceRoot:''`:

```
{"version":3,"sources":["/index.ts","packages/fuse-box-css@0.0.1"],"names":[],"mappings":";;;;;;AAAA,wBAAsB;
```

and keep it like it is:

```
{"version":3,"sources":["/src/index.ts","packages/fuse-box-css@0.0.1"],"names":[],"mappings":"
```
but my homeDir is `/app`

with `sourceRoot :'/app'`:

```
{"version":3,"sources":["/app/index.ts","packages/fuse-box-css@0.0.1"],"names":[],"mappings":";;;;;;AAA
```

but than sass sourceMaps are broken because its already repects the hierachy:

````
{"version":3,"file":"index.scss","sources":["/app/app/index.scss","/app/app/_sub.scss"],"names":[],"mappings":"ACAA,AAAA,
````

and now I'm thinking that this should be related to my homeDir, too... mhhh

**Comment by nchanged** [comment]
that should be related to your `homeDir`, In fact, if you have an idea how to remove node_modules sourcemaps - even better, they are there cuz of some nasty bug.  They should be there only when requested

**Comment by rs3d** [comment]
Well i see it as a bugfix/clean up if we set `sourceRoot:''` as default.
If this breaks some sourceMaps in dev environments it's not that breaking change while bundling is still working and people have to update fuse-box to experience this.

Proper sourceMaps with nested scss sources is outweighing this minor change imo.

@zigmo Your change is working for me, ty!

**Comment by nchanged** [comment]
`fuse-box@2.3.1-test.1` please test ;-)

**Comment by rs3d** [comment]
For the log :) `fuse-box@2.3.1-test.1` is solving my issue!
