### ISSUE TITLE
LESSPlugin lost live reloading of @imported files in 2.2.2

### ISSUE THREAD

**Issue by guillaume86** [fuse-box/fuse-box#780]
As discussed in this similar issue: https://github.com/fuse-box/fuse-box/issues/763#issuecomment-326933765

After updating from 2.1.0-beta.2 to 2.2.2 (and setting target: browser to fix an unrelated issue), I lost the live CSS reloading when changing nested .less files.

I tried the fuse-box@2.2.3-beta.19 and it didn't fix the issue, I'm on windows but it seems unrelated (the LESS plugin do not send back the dependencies like the SASS one).

**Comment by nchanged** [comment]
Some super nice update here: fuse-box@2.2.4-beta.1
You will get error reports in the browser, please test

**Comment by guillaume86** [comment]
Hi thanks for looking into it. Here's what I did and the results:

- install fuse-box@2.2.4-beta.1
- clear fusebox cache
- start my usual dev/watch task
- my app is loading fine
- changing something in a @imported .less file
- node/fusebox process output this error (nothing in browser)

```
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at File.generateCorrectSourceMap (C:\Data\Projects\Hrweb-git-tfs\HrWeb.WebClient\node_modules\fuse-box\dist\commonjs\core\File.js:381:39)
    at CSSPluginClass.transform (C:\Data\Projects\Hrweb-git-tfs\HrWeb.WebClient\node_modules\fuse-box\dist\commonjs\plugins\stylesheet\CSSplugin.js:129:35)
    at tasks.push (C:\Data\Projects\Hrweb-git-tfs\HrWeb.WebClient\node_modules\fuse-box\dist\commonjs\core\File.js:126:63)
    at context.queue.realm_utils_1.each.promise (C:\Data\Projects\Hrweb-git-tfs\HrWeb.WebClient\node_modules\fuse-box\dist\commonjs\core\File.js:137:76)
    at iterate (C:\Data\Projects\Hrweb-git-tfs\HrWeb.WebClient\node_modules\realm-utils\dist\commonjs\each.js:79:34)
    at iterate (C:\Data\Projects\Hrweb-git-tfs\HrWeb.WebClient\node_modules\realm-utils\dist\commonjs\each.js:87:25)
    at C:\Data\Projects\Hrweb-git-tfs\HrWeb.WebClient\node_modules\realm-utils\dist\commonjs\each.js:92:16
    at Promise (<anonymous>)
    at Object.exports.Each [as each] (C:\Data\Projects\Hrweb-git-tfs\HrWeb.WebClient\node_modules\realm-utils\dist\commonjs\each.js:9:12)
```

I have to clear the cache to be able to start my app again (fusebox has the same error on first build if I don't). I can debug if you need some values to help.

**Comment by nchanged** [comment]
@guillaume86 can you reproduce your case in a repository? I am sure we will get it all fixed

**Comment by guillaume86** [comment]
Here's the minimal case I think:
https://github.com/guillaume86/fusebox-issue-780

If you uncomment the sourceMaps option in the gulpfile the error also comes up.

**Comment by nchanged** [comment]
@guillaume86 discovered a bug there... that wasn't just related to less
`fuse-box@2.2.4-beta.3` tested your repo, all working just fine 👍

**Comment by guillaume86** [comment]
@nchanged great thanks for the fix

**Comment by guillaume86** [comment]
The live reloading is working fine now, but setting sourceMaps: true still triggers the same error, not really important for me but that's probably also worth a look.

**Comment by nchanged** [comment]
Oh man, forgot about that one, I will check

**Comment by sandyplace** [comment]
I am now getting this error after upgrading to 2.3.2

**Comment by nchanged** [comment]
this repo still works? https://github.com/guillaume86/fusebox-issue-780
i mean i can reproduce the issue there?

**Comment by sandyplace** [comment]
Sorry, I haven't checked out the version in the link yet. I just noticed after I upgraded from 2.2.31 -> 2.3.2 that when I build clean (after removing my .fusebox folder) that everything builds successfully. If I make a change to a source file or try rebuilding again it throws the exact same exception and stack trace that was described in this issue.

**Comment by sandyplace** [comment]
I checked out the example project and it seems to work fine. I will see if I can reproduce it.
