### ISSUE TITLE
Auto-reloading without HMR

### ISSUE THREAD

**Issue by dakom** [fuse-box/fuse-box#781]
HMR is great but isn't always the right tool for the job.

It would be helpful to have an option under `dev` for auto-reload based on watched files, which rebuilds/reloads rather than replacing in-memory.

**Comment by devmondo** [comment]
@dakom 
would something like this #806 help you?

**Comment by dakom** [comment]
Probably - though I'd rather not introduce another tool. One of the main benefits of Fuse-Box imho is that everything is under one roof. One of the main problems I had with webpack was when introducing other tools that are supposed to be compatible but aren't. I get browserSync is kindof a different beast, but still... a "reload when changed" property to the dev server would be better I think.

Either way, thanks for the heads up!

**Comment by nchanged** [comment]
@dakom 
sorry it took so long http://fuse-box.org/page/development#auto-reload-page

`fuse-box@2.3.1-beta.10`

**Comment by iLLucionist** [comment]
The option "auto-reload-page" has been removed from documentation?

Following the link http://fuse-box.org/page/development#auto-reload-page does not show anything??

**Comment by nchanged** [comment]
@iLLucionist I believe that was an accident, it belongs here: https://fuse-box.org/page/development-server. IT should be just `reload : true`

**Comment by iLLucionist** [comment]
@nchanged Thanks for the info, really helpful. Is there any work on implementing some sort of auto reloading on when non-bundled files change? Would be great to have something like "StaticPlugin" or something:

```
plugins [

(...)

["src/**html",
    StaticPlugin({
        reload_on_file_change: true
    })
],

(...)

],
```

**Comment by nchanged** [comment]
@iLLucionist that's a great idea. Do you think you can submit a PR?
