### ISSUE TITLE
[Discussion] Self Host?

### ISSUE THREAD

**Issue by calebboyd** [fuse-box/fuse-box#783]
It would be pretty awesome if fuse-box could be self hosted.
And by that I mean be able to bundle/build the fuse-box project.

Thoughts?

**Comment by nchanged** [comment]
It's actually possible, and already happening when you run `node test`
But why would one want to have it?

**Comment by calebboyd** [comment]
If a project uses fuse-box as a dependency, being able to bundle that project

eg. [nexe](https://github.com/nexe/nexe)

**Comment by calebboyd** [comment]
But as you can probably guess I'm running into a problem with Config.

Would accept a PR that moved `Config` to the FuseBox instance level and shared it using the 
WorkflowContext?

**Comment by nchanged** [comment]
@calebboyd there are millions of references to the context, across the code.... You can try of course, but push to a different branch
