### ISSUE TITLE
How to use fuse-box through command line

### ISSUE THREAD

**Issue by maximusk** [fuse-box/fuse-box#784]
As I understand to run fuse-box I need to create and execute JS file:

```
const {FuseBox} = require("fuse-box");
...
fuse.run();
```

Is it possible to run it as a command line tool passing the configuration options:

`$ fusebox --homeDir="src" --output="dist/$name.js"`

FuseBox npm installation doesn't seem to be adding an executable into `node_modules/.bin`.

**Comment by nchanged** [comment]
We don't have CLI and this moment

**Comment by maximusk** [comment]
Thanks, are there plans to have one? I'm willing to contribute

**Comment by nchanged** [comment]
@maximusk I don't think it's necessary as it doesn't bring much value, no plans on it yet

**Comment by maximusk** [comment]
@nchanged , okay, thanks, is there anything "easy" to help with?

**Comment by nchanged** [comment]
@maximusk plenty of things ;-)
for example this issue https://github.com/fuse-box/fuse-box/issues/781
