### ISSUE TITLE
Acorn "script" vs "module" -- allow configuration?

### ISSUE THREAD

**Issue by calebboyd** [fuse-box/fuse-box#785]
I'm wondering if i missed it somewhere. -- Allow bundling of non-strict code.

Any way to pass a different configuration to acorn?

**Comment by nchanged** [comment]
@calebboyd I don't think you can.... Do you think it's possible to switch acorn to a non-strict mode and solve these 2 issues? We would put it there by default, it makes sense

**Comment by calebboyd** [comment]
Ahh yes, it probably does. Most of the module transpilers will include the strict directive anyway.
