### ISSUE TITLE
PostCSSPlugin problems

### ISSUE THREAD

**Issue by ben33** [fuse-box/fuse-box#788]
In the PostCSSPlugin,
we pass processors and options.
In the documentation, the options.plugins "seems" to replace processors instead of it should work like options if we refer to the postCSS JS api...

**PostCSSPlugin.ts**
```
return postcss(this.processors)
            .process(file.contents, postCSSPlugins)
            .then(result => {
                file.contents = result.css;

                if (file.context.useCache) {
                    file.analysis.dependencies = cssDependencies;
                    file.context.cache.writeStaticCache(file, generateSourceMaps && file.sourceMap, "postcss");
                    file.analysis.dependencies = [];
                }
                return result.css;
            });
```
**postCSS api**
```
postcss([processors])
            .process(css, {options})
```

Furthemore,
we can't pass options to postcss...

PS : To make it works for me and only me, I replaced **postCSSPlugins** by **this.options**
Maybe I'm the only one to use postcss ^^

**Comment by nchanged** [comment]
Valid points. Do you think you can suggest a PR?

**Comment by ben33** [comment]
I can and I will suggest a PR. I'll do it this weekend. Thx for the answer

**Comment by ben33** [comment]
Re,

Can you create a branch for the problem then I will push my fix ?
Or where do I push ?
Or how do you want to process ?

Thx

**Comment by nchanged** [comment]
You can submit to master, I can review and test in manually

**Comment by ben33** [comment]
It seems that I can't push at work... I'll take my computer this evening and I'll push tonight.
Sorry for the delay.
