### ISSUE TITLE
Code that package referenced is not transpiled...?

### ISSUE THREAD

**Issue by Martaver** [fuse-box/fuse-box#790]
I might be doing something stupid, here... but I wonder if I've found a problem with fuse-box?

I have a project that references `ghostjs`, which is written using es7 `async` operations. I'm using fuse-box version 2.2.3, and running the output on node 6.x, so targeting es2015.

I reference ghostjs, try to open a page, and the generates JS fails:
```
CDP(async (client) => {
                  ^
SyntaxError: Unexpected token (
```

Somehow, there are async/awaits finding their way into the generated JS.

If I did a bit deeper into the generated JS, the `ghostjs` package actually seems to be transpiled, because all of the .js files in the root of its `/src` folder, have had their async/awaits replaced by their corresponding constructs (such as __awaiter etc). 

But for some reason, the code referenced in its `/src/chrome` folder doesn't get transpiled. It's included in the output JS, but it still has its classes and async/awaits. 

I'm not sure what the difference is. It's the `ghost.js` file that references the `/chrome` folder with the following line:
```
var ChromeGhostDriver = require('./chrome/')
```

As I understand it, if the TS compiler can transpile the other files fine, it should also work for the files in `/src/chrome`.

Is this a bug, or am I just being retarded?

**Comment by Martaver** [comment]
I have a sample repo here:

https://github.com/Martaver/alfred

Clone and run `yarn fuse`, then `node bin/main.js`.

**Comment by nchanged** [comment]
@Martaver that's right, isn't transpiled, simply because  FuseBox thinks it's all good there. At it is in fact, it just cares about `exports` cooked. 
So as a solution, a good compromise I'd say, I added this line: 
https://github.com/fuse-box/fuse-box/commit/5049fc790421cca6d6199feafe5af89072f91094#diff-46932920d0bc7fb5940a60d3a3fe2e22R30


`fuse-box@2.3.1-beta.5`

**Comment by calebboyd** [comment]
Hmm -- What about when you're targeting an environment that `async await` works in? eg. current node, edge, chrome, etc.

The library the OP is using suggests to their users - to use babel... Wouldn't `BabelPlugin({ limit2project: false})` solve this?

**Comment by nchanged** [comment]
@calebboyd we try to avoid Babel ;-) ts does it's pretty nicely

**Comment by calebboyd** [comment]
Thats not really my point -- if you're targeting node 8 this change will transpile your code to a lesser language version

**Comment by nchanged** [comment]
if you target server, you don't usually bundle dependencies (and the problem is in the deps). And regarding the code base you have  tsconfig

**Comment by calebboyd** [comment]
Still not my point... I'll open a separate issue...

**Comment by Martaver** [comment]
@calebboyd I actually tried the BabelPlugin, and it seemed to skip the reference too. Not sure why, I was probably just using it incorrectly.

But I much rather prefer dropping Babel entirely, if TS compiler can take care of it.

@nchanged I think that's a good compromise. Probably worth trying to detect and categorize all compatible language features. It would be nice to not have to muck around with all this.

Thanks for the fast turnaround!

**Comment by Martaver** [comment]
And it seems to work fine!

On to the next round of errors...

**Comment by nchanged** [comment]
@Martaver `fuse-box@2.3.1-beta.6`
You would need to set [language level](http://fuse-box.org/page/configuration#language-level)

thanks to @calebboyd we now have a proper [solution](https://github.com/fuse-box/fuse-box/pull/793) to the problem

**Comment by Martaver** [comment]
Hey that's great news!

The proactivity of fuse-box astounds me, honestly!

**Comment by Martaver** [comment]
I would make a big hype out of this feature, this is fantastic.
