### ISSUE TITLE
JS projects broken

### ISSUE THREAD

**Issue by calebboyd** [fuse-box/fuse-box#791]
In the latest fuse-box@2.3.1-beta.5

This change https://github.com/fuse-box/fuse-box/commit/5049fc790421cca6d6199feafe5af89072f91094#diff-46932920d0bc7fb5940a60d3a3fe2e22R30

causes the simplest vanilla JavaScript bundle to fail

index.js
```javascript
async function main () {
    await new Promise(resolve => setTimeout(() => resolve(42), 2000))
}
console.log('started')
main().then(x => console.log('finished'))
```

fuse.js
```javascript
const { FuseBox } = require('fuse-box')

const fuse = FuseBox.init({
    homeDir: './',
    cache: false,
    output: '$name.js',
})
fuse.bundle('main')
    .instructions('index.js')

fuse.run()
```
Steps:
- Run `node fuse.js`
  - `Error: Cannot find module 'typescript'`
- Install typescript (first weird thing, because i'm writing a simple plain JS project)
- Run `node fuse.js`
  - Bundle is 55 lines of ES5...(my plain js was transpiled by typescript ¯\_(ツ)_/¯?)

The current version works as expected and gives the 5 non-down-converted lines of JS I'd expect.

Node 8 goes to LTS in 20 days and has `async await` out of the box. 

FuseBox does the same sort of thing for import/export (es6 modules) This is probably the only appropriate language feature to make that assumption for. However -- fusebox still converts that code over-aggressively. If its goal is to handle the module-feature it should set typescript to the highest target possible and keep commonjs as the module format. Typescript is setup to transpile modules separate from language features (and the "automagic" feature of fusebox should be too)

This type of change isn't scalable as people are always going to publish some Stage 3 javascript feature to npm. Its the package authors responsibility to either specify the correct node/environment version or provide compatible builds -- also to a version they specify.

**Comment by nchanged** [comment]
Well it's been working like this for quite a while, except now it transpiles the code if there is `async` in it. I am not sure what would be the best solution. Behind the flag?

**Comment by calebboyd** [comment]
Right, FuseBox has transpiled 🐛*  on import/export detection for a while. 
This is fine, because the module language construct does not make sense in a bundle. 

What is not okay - is doing this arbitrarily for other language features that have nothing to do with bundling. All the JS fusebox projects that relied on those language features will break due to this change (some of mine included), or at the very least have all their code transpiled (making it needlessly slower, too).


🐛*  - The language level should probably be set to "ESNext" so that it has the smallest effect on other language features in the module file. Or, at least configurable. TypeScript config is already setup to handle the module feature differently as well.

ghostjs is just a poorly published package. All the files use different module styles import/require and they expect it to be run with their CLI (babel/register) or mocha compilers.

**Comment by calebboyd** [comment]
If the language level flag is added, TypeScript should probably be at least a Peer Dependency.. You think?

**Comment by nchanged** [comment]
Ok, lemme clarify something.
The only thing I did is I added an extra condition to toggle es6 transpile of typescript. So that fix shouldn't have broken anything, as any `export` or `import` triggered that scenario for like 4 months already. 
I don't have a good solution to that except for tweaking this bit

https://github.com/fuse-box/fuse-box/blob/9d0ddd9509973e8bcb61a866efae816ae804b993/src/analysis/plugins/ImportDeclaration.ts#L60-L67

You see, we need to transpile it, as many modules like you mentioned are poorly packaged. I am not sure if we can tell typescript not to transpile some of the features. I think it's either all or nothing, es6 or es5.

**Comment by calebboyd** [comment]
Hah, I think we're going back and forth -- I understand its been that way:
>Right, FuseBox has transpiled 🐛* on import/export detection for a while.
And I think that it is good
>because the module language construct does not make sense in a bundle.

But doing that transpilation (the change that was made) with other features is bad, because someone could want to use them. In the environment they're targeting (browser/server/electron)
So it breaks anyone who wasn't relying on typescript in their project/dev pipeline.

To only transpile to commonjs and keep the highest supported language features in typescript. You just need to do

```
     compilerOptions: { 
         module: "commonjs", 
         target: "ESNext" 
     }, 
 };
```

**Comment by nchanged** [comment]
@calebboyd use the latest 3.0 it's fixed and polished
https://github.com/fuse-box/fuse-box/blob/doc-ver-3/docs/useful.md#understanding-targets-and-script-levels

**Comment by hinell** [comment]
Getting the same error here.
```
fuse-box@2.5.0-beta.1
node --version => v9.2.0
```

After installation of the ``typescript`` I found node_modules folder empty of the `fuse-box` folder. 
Only after reinstalling it again I got it working correctly.

## Steps to reproduce 
```
mkdir fresh-new-folder
npm i -S fuse-box
```
### command
Then using default `fuse.js` provided by the [getting started](http://fuse-box.org/page/getting-started )
just run
`node fuse.js`

```typescript
// src/index.ts
console.log('Hello FuseBox')
```

**Comment by nchanged** [comment]
Well you need typescript of course… I don’t see any issues here, fuse doesn’t come with preinstalled to

**Comment by hinell** [comment]
@nchanged Yep, it is okay with typescript peer but what about removal of the `fuse-box` from the `node_modules` when it was installed before but deleted after typescript installation?

**Comment by guillaume86** [comment]
@hinell do you use yarn? I think I have a similar issue.

**Comment by nchanged** [comment]
I think it's time to close this issue. I hope everything is resolved. We are on fuse 3 now. ;-) Docs are very clear about TypeScript
