### ISSUE TITLE
Typescript 2.3+ custom transformers

### ISSUE THREAD

**Issue by yihongang** [fuse-box/fuse-box#792]
Any plans to support them?

https://github.com/Microsoft/TypeScript/pull/13940

e.g., https://github.com/TypeStrong/ts-loader/pull/535

**Comment by nchanged** [comment]
at the plugin level? or what do you mean?

**Comment by yihongang** [comment]
I was under the impression that custom transformers are run in the typescript transpile step and since fuse-box does that step, there can be a config to specify them?

**Comment by nchanged** [comment]
I supposed so!
Just need to figure out which one

**Comment by yihongang** [comment]
I finally had some time to look at this.

Something like https://github.com/yihongang/fuse-box/commit/812eaa87197c41003094c789ff659795508333d5 seems to work. Is that acceptable?

**Comment by nchanged** [comment]
COuld you point out how to use it?

**Comment by yihongang** [comment]
something like this

```
const { FuseBox } = require('./dist/commonjs');
const ts = require('typescript');

// useless transformer
const shouty = (context) => (node) => {
  return ts.visitEachChild(node, visitor, context);

  function visitor(node) {
    switch (node.kind) {
      case ts.SyntaxKind.StringLiteral:
        const text = node.getText();
        return ts.createLiteral(text.toUpperCase());
    }
    return ts.visitEachChild(node, visitor, context);
  }
};


const fuse = FuseBox.init({
    homeDir: "test_src",
    output: "dist/$name.js",
    cache: false,
    transformers: {
        before: [shouty]
    }
});
fuse.bundle("app")
    .instructions(`>index.ts`);

fuse.run();
```

**Comment by nchanged** [comment]
Awesome! Once you have some example that does something, could you PR, and update docs/configuration.md with that example too?

It is very useful, in fact, I need it too! 

Thanks

**Comment by deamme** [comment]
@yihongang How far are you? This feature could be awesome so the [typescript transformer](https://github.com/deamme/ts-transform-inferno) for [Inferno](https://github.com/infernojs/inferno) can be used.

**Comment by deamme** [comment]
Bumping this because I'm THAT excited!
