### ISSUE TITLE
CSS as an entry?

### ISSUE THREAD

**Issue by knpwrs** [fuse-box/fuse-box#794]
I use CSS-in-JS but I still like using the `sanitize.css` and `lato-font` packages. In webpack I was able to use those packages as entries so I didn't have to explicitly import them:

```js
entry: [
  'style-loader!css-loader!sanitize.css/sanitize.css',
  'style-loader!css-loader!lato-font/css/lato-font.css',
  'main.js',
]
```

Does FuseBox have anything like this? I've tried playing around with extra `+` and `>` but haven't gotten anywhere:

```js
//...
fuse.bundle('client')
   .instructions('> index.tsx + sanitize.css/sanitize.css + lato-font/css/lato-font.css')
//...
```

**Comment by nchanged** [comment]
I don't get what's the problem, can you just import it in the code?
```js
import "sanitize.css/sanitize.css"
```
With CSSPlugin in place?

**Comment by knpwrs** [comment]
That works, but adding CSS as an entry has several advantages:

1. The code more readily runs in Node with no need for a build step. This is important for testing frameworks such as Ava which do not (currently) support builds outside of Babel. Other solutions include using a Babel plugin to remove non-js imports (either with `babel-node` or ava) or overriding `require.extensions`.
1. My code does not explicitly depend on `sanitize.css` or `lato-font`. The semantics of importing css files make more sense for modularized CSS (e.g., components).
1. Some people (not me) are _really_ uncomfortable importing CSS files leading to situations where they [combine Gulp, WebPack, and BrowserSync](https://css-tricks.com/combine-webpack-gulp-4/) (yikes). Having explicit support for static assets as entry points alleviates this in my mind. You can see me in the comments section pointing out as much (unfortunately the thread is now closed and I cannot respond the to replies).

It's just a pattern I'm surprised isn't supported. When I started using this pattern in Webpack it was an intuitive step to move an imported module to be a bundle entry. Nobody even needed to tell me it was a thing that could be done, I did it and it worked. It seems like the Architecture in Fuse-Box is fundamentally different to the point of not supporting this pattern? At least explicitly anyway.

What about making a `web.ts` file or similar which imports the modules? That handles the first two points and maybe a little of the third. In my _specific_ case you could make an argument that `index.tsx` could be that file, especially for the first point, but I've used this pattern across a wide variety of projects depending on the required semantics and technologies. If CSS entry points were an explicitly documented feature then that could also alleviate the third point where some people feel the need to combine multiple build tools.

**Comment by nchanged** [comment]
Don't understand what's the problem. Think FuseBox, not Webpack.
1) Read up on CSSPlugin, you can pipe out css files to the filesystem without bundling them
2) You can make web.ts and import required files there, that's right

**Comment by knpwrs** [comment]
It's just semantics, not a "problem." I would make the case, however, that the way WebPack works here is more intuitive -- everything is a module and any module can be an entry point. Is there any reason why Fusebox _shouldn't_ work that way? It seems arbitrary to me to make a distinction between modules which can be imported and modules which can be entry points.

**Comment by knpwrs** [comment]
As for outputting to the filesystem, that's not what I'm trying to accomplish. This is just a semantic thing.

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
