### ISSUE TITLE
Requiring relative paths with package.json#main entries

### ISSUE THREAD

**Issue by calebboyd** [fuse-box/fuse-box#795]
PathMaster#testFolder does not take into account a package.json being in the folder

https://github.com/fuse-box/fuse-box/blob/8134ac6d151daf98d409f09389562dc49ecc7e44/src/core/PathMaster.ts#L227-L248

It should probably perform a proper `require.resolve` resolution here. 

Do you have that utility extracted anywhere?

**Comment by nchanged** [comment]
Yeah, that's a known bug, nope it's not there, I hope it won't affect the performance much

**Comment by calebboyd** [comment]
I'd think something like `tryReadPkgMain(dir) : string | false` could perform pretty fast

**Comment by nchanged** [comment]
It's actually here

https://github.com/fuse-box/fuse-box/blob/8134ac6d151daf98d409f09389562dc49ecc7e44/src/core/PathMaster.ts#L287-L301

**Comment by calebboyd** [comment]
Here is the broken case:

```
|____folder 
| |____module.js //require('..')
|____library.js
|____package.json //main: './library.js'
```

**Comment by nchanged** [comment]
It works only with explicit package require, like `module/hello/world`

**Comment by calebboyd** [comment]
Right, I modified testFolder, to resolve the correct entry file -- but failed

**Comment by calebboyd** [comment]
@devmondo Why the enhancement label? this is most certainly a bug

**Comment by calebboyd** [comment]
Can you explain what `resolved` and `alias` are supposed to be?

**Comment by calebboyd** [comment]
I made a gist that mostly demonstrates some not so fun issues...
https://gist.github.com/calebboyd/48d62efd1f36d137a9e0492837d81b18

**Comment by nchanged** [comment]
@calebboyd alias is being replaced at runtime

**Comment by nchanged** [comment]
@calebboyd check out this one, please
https://github.com/fuse-box/fuse-box/commit/cb5dfbd4670344b839fc81b9e2b7f969a6f45d85

I think removing `if explicit` fixes it, so it's checking it every time. Please verify, if it fixes the case, let's update the loader with that corner case you've found.

**Comment by calebboyd** [comment]
Hey that looks good. I've updated my PR.
I also added a check so it doesn't resolve aliases to `'...js' or `../.js` `../../.js` etc..

**Comment by nchanged** [comment]
Ok, let's see what's happening here `fuse-box@2.3.1-beta.7`
Let's test intensively

**Comment by calebboyd** [comment]
Will do. Trying on large project rn

**Comment by nchanged** [comment]
Check Quantum too, i am afraid it might be broken

**Comment by calebboyd** [comment]
Looks like it is broken -- but its only as broken as much as it was before
