### ISSUE TITLE
cacheFolder is invalid in Windows 10

### ISSUE THREAD

**Issue by carloslfu** [fuse-box/fuse-box#800]
Running a simple bundle fails in Windows 10 because cacheFolder contains an invalid character `.fusebox\cache\https:\registry.npmjs.org\fuse-box`.

This is the error:
`\.fusebox\cache\https:\registry.npmjs.org\fuse-box\-\fuse-box-2.2.31.tgz\F6gbH-vendo
r\permanent contains invalid WIN32 path character`

**Comment by nchanged** [comment]
Oh.. that was supposed to be a version right?
