### ISSUE TITLE
Quantum, css and fuse-box-css

### ISSUE THREAD

**Issue by eddow** [fuse-box/fuse-box#801]
### Situation: trying to compile a module to publish on npm/bower/yarn/...

When making a commonjs module in order to publish it, two things happen after quantum compilation.
- the package `fuse-box-css` is not published if not explicitely mentionned in the sources. It is not a bug so-to-speak but demand the user to get quite curious about how fuse-box is built to discover this detail (that I still miss some times even after spending time deeply in fuse-box)

Explicit mention :
```js
fuse.bundle("my-library")
	.instructions('> [index.ts] +fuse-box-css');
```
- The CSS references are not transformed.

They are not transformed in two ways again :
- the CSS file is not bundled and it remains an external reference (with a `require` and a path instead of quantum' file number - with the correct path though)
- to `require` a CSS file directly is perhaps a `fuse-box`-specific feature. I might be wrong, but if I am not; if for instance other bundlers cannot handle that, it could be neat for fuse-box to invoke `fuse-box-css` on it instead of simply requireing it.

**Comment by nchanged** [comment]
You isolate deps, of course it's not bundled.
Yes, `fuse-box-css` handles CSS files at rintime, that's right.
Can you make an example repo please?

**Comment by eddow** [comment]
https://github.com/eddow/vue-golden-layout

**Comment by nchanged** [comment]
Right, I would like to have something simpler with steps to reproduce as I don't really get what's the problem l

**Comment by eddow** [comment]
So, the repo I gave here is an example of library I try to bundle with fuse.
Note, that library is client-side but I already have "universal"-side libraries ( [exemple](https://github.com/eddow/ts-json-schema-decorator) ) that mean to run client-side and server side.

A patient user reported a bug, as the bundled module raise errors when it is used (in this case, bundled with webpack - but it would be the same if used by node or bundled with another bundler)
The user is so patient, he provided a [repository of a sandbox that uses the library](https://github.com/soyvv/vue4vgl-test)

I finally succeeded to publish on npm a vrsion of my library for this webpack-repo to work but I had to edit manually the bundled library to remove this code line :
```js
        global.require = require;
```
To be correct, I removed this whole code that keeps unused values (a commonjs module does not really need to know whether it is running client or server-side) - the value `isBrowser` is indeed not used further :
```js
    var isBrowser = typeof window !== "undefined";
    if (!isBrowser) {
        global.require = require;
    }
```

This code is dangerous as, what ever imports that library - should it be node.js or webpack - they **provide** `global.require`; no commonjs module has the idea to override node' `require` global - but this is what is happening here.

For the pragmatical exemple, there are the 2 repositories provided here ( [library](https://github.com/eddow/vue-golden-layout) and [client](https://github.com/soyvv/vue4vgl-test) )

When the library is bundled, it contains the `global.require` modification, if the client import it "as is", it raises errors.

Note: I published a version of the library manually edited on npm, so, if just `npm install`-ed, it works without problem

Note: I provide here the repositories as requested, but I still think that understanding a library shouldn't fuss with `global.require` is the easy way in understandment. Just try to imagine if a user try to bundle with fuse a module that changes `global.require` without consideration of `fuse-box`

**Comment by nchanged** [comment]
So your suggestion wouldn be to remove global require?

**Comment by eddow** [comment]
Definitely - to remove the setting of `global.require`; along with the concern of client/server-side (`isBrowser`)

Note, we can do it in a dedicated bundling mode; I thought at first to make it in `universal` mode but we decided afterward to create an `npm` mode. I still think that `npm` is a poor name as it fits for npm/bower/yarn/yalc/etc. - I would definitely call it something more like `commonjs` as it is a format intended to be used and managed.

Also, this question will quickly arise : what is the difference between `commonjs` and `universal` mode ? I let these questions to you, I don't want to interfere with some of your users that might use `universal` already

But yes, definitely, I would love to use fuse-box to bundle a commonjs library and the interference with `global.require` is the nail pointing out of the chair.

**Comment by nchanged** [comment]
What a drama ;-)

I can't remove it completely as it will be a breaking change for many many users, 
But there you go 
https://github.com/fuse-box/fuse-
box/commit/2b189b4c7fb7f7ca6eb8f7c6793bda766c577633

`fuse-box@2.3.1-beta.9`

**Comment by nchanged** [comment]
Closing it for now, re-open elsewise

**Comment by eddow** [comment]
what break? We created the npm build - it was not even used - we can create another one - I suggested the name "commonjs" it breaks nothing
"elsewise"

**Comment by nchanged** [comment]
@eddow you can use the option `globalRequire : false` in Quantum that won't bundle that part of the code you are complaing about. That's what the commit is about
