### ISSUE TITLE
HMR not using alias

### ISSUE THREAD

**Issue by DaveO-Home** [fuse-box/fuse-box#803]
Using config below, error - Uncaught Package not found "app"
changing require("app")  ==> require("./js/app");  the module is found.

alias: {
        	"app": "~/js/app"
        }
        
        var test = fuse.bundle("test")
            .target("browser")
            .instructions(` > index.js
            + **/*.{js,html,css,json}
        `);
        
       test.hmr().watch();

**Comment by devmondo** [comment]
I think u might have got it wrong, `aliases`  are key/value based.
so with 
```
alias: {
"app": "~/js/app"
}
```
you are asking fuse to whenever someone does `import * as something from"app"`, to internally require `~/js/app` and not vice versa.

**Comment by nchanged** [comment]
I wasn't able to reproduce the issue
![screenshot 2017-09-17 18 19 39](https://user-images.githubusercontent.com/1629088/30522714-d3bd10aa-9bd4-11e7-87f0-e28861ccf0b3.png)

HMR picked up the changes without problems. Please provide a repository

**Comment by DaveO-Home** [comment]
My fuse.js is up one level and my index.js is under src.

**Comment by nchanged** [comment]
Doesn't matter as long as your don't go outside the homeDir, it works

**Comment by DaveO-Home** [comment]
Wouldn't mind seeing what's is fuse.js

**Comment by DaveO-Home** [comment]
And my fuse.js is outside of homeDir.  Could be the problem??

**Comment by DaveO-Home** [comment]
My File hierarchy follows the getting-started doc.

**Comment by nchanged** [comment]
That's good, it should be outside homeDIr.

**Comment by DaveO-Home** [comment]
Is js your homeDir?

**Comment by nchanged** [comment]
no `src`

**Comment by DaveO-Home** [comment]
Humor me just once - add the CSSPlugin() plugin to your config, nothing else and see what happens.

**Comment by nchanged** [comment]
Yep, works without problems.

**Comment by DaveO-Home** [comment]
Here's what I had to do:
1. Added my css to the test html page;
<link rel="stylesheet" type="text/css" href='css/site.css'>
        <link rel="stylesheet" type="text/css" href='../node_modules/bootstrap/dist/css/bootstrap.min.css'>
        <link rel="stylesheet" type="text/css" href="../node_modules/tablesorter/dist/css/theme.blue.min.css">
        <link rel="stylesheet" type="text/css" href="../node_modules/tablesorter/dist/css/jquery.tablesorter.pager.min.css">
2. removed CSSPlugin() and aliases
3. copied one non-standard library to my js dir - node_modules/tablesorter/dist/js/extras/jquery.tablesorter.pager.min.js (no need to do this when alias works).
4.  changed require imports to relative directories.
Works with this config....  and font-awesome works without changes.

**Comment by nchanged** [comment]
It's easier if you create a repo with your problem
And HMR doesn't work on external files.

**Comment by DaveO-Home** [comment]
Follow up on using HMR with  bootstrap & tablesorter 

1.	Not using aliases
2.  CSS - Using CSSPlugin  - config and code 
	
	CSSPlugin({
                group: 'bundle.css',
                outFile: `${src}/bundle.css`
            }),


/*
  Group and bundle css into ${src}/bundle.css - allows HMR to locate css
 */
if (1 == 2) {  //hack to eliminate 404's
    require("\~/../node_modules/bootstrap/dist/css/bootstrap.min.css");
    require("\~/../node_modules/tablesorter/dist/css/theme.blue.min.css");
    require("\~/../node_modules/tablesorter/dist/css/jquery.tablesorter.pager.min.css");
    require("\~/../node_modules/tablesorter/dist/js/extras/jquery.tablesorter.pager.min.js");
}

require('~/css/site.css');
require("font-awesome/css/font-awesome.css");

3. The tablesorter pager library(a jquery plugin) - used CopyPlugin - 

	CopyPlugin({ files: ["node_modules/tablesorter/dist/js/extras/jquery.tablesorter.pager.min.js"], dest : "static", useDefault : false })

	require("../dist_test/static/d5b4a6d8-jquery.tablesorter.pager.min.js");

	Need to code above import to have fuse inject the correct link into the html.

Whew! 

From https://medium.com/fusebox/fusebox-2-0-the-beast-reborn-e4ec0443b782

Would like to get this working...

But with FuseBox HMR, we won’t make you refresh the browser, we will automagically reload only the files that changed, and all of your changes will immediately appear on your page!

**Comment by nchanged** [comment]
@DaveO-Home 
why don't you do:
```js
import "bootstrap/dist/css/bootstrap.min.css"
```

Then use [shims](http://fuse-box.org/page/configuration#shimming) for jquery and tablesorter

**Comment by devmondo** [comment]
@DaveO-Home the syntax provided by @nchanged above works perfectly, we use it.

**Comment by DaveO-Home** [comment]
@devmondo - you are absolutely correct and I am using the jquery shim and the bootstrap import works just fine.  However the tablesorter css does not load using the same syntax.  Also, I'm thinking the aliases don't work because in my config I declare them in src's parent directory.  I'm trying to use the same config for both dev and prod.  Aliases work in prod, so I do something like this require('bootcss'), therefore I put the boostrap for HMR in the bundle with tablesorter css.  Yes it may be much cleaner not to use alias with bootstrap.  My file hierarchy is complaint to [this](http://fuse-box.org/page/getting-started#your-first-bundle).  Also, I tried a shim for the tablesorter pager plugin without success.

**Comment by DaveO-Home** [comment]
guys, I did finally get the css to load with @nchanged suggested syntax, don't know why it didn't work previously?? So if I can only get the jquery plugin to work, it's coded like !function(e){ code..}(jquery);
Tried this in shim:
        tablesorter: {source: "node_modules/tablesorter/dist/js/jquery.tablesorter.combined.js", exports: "tablesorter"},
        tablepager: {source: "node_modules/tablesorter/dist/js/extras/jquery.tablesorter.pager.min.js"}

**Comment by nchanged** [comment]
I don't this a jquery shim exports anything. I think it's set globally to `$` variable, that's how plugins in jquery work

**Comment by DaveO-Home** [comment]
I checked that out by coding the plugin first in the shim.  It gave me "jQuery" not defined.  Moved it after jquery and it didn't complain.

**Comment by nchanged** [comment]
that's how it should be after Jquery. Then you can just use it.. $.tablesorter or whatever

**Comment by DaveO-Home** [comment]
My problem is not with tablesorter that works just fine, it's the pager jquery plugin that's giving me the headache.  If I do my hack and load via html it plugs into jquery.  The shim doesn't plug it in, I get
$(...).tablesorter(...).tablesorterPager is not a function

**Comment by DaveO-Home** [comment]
Well, it turns out that the issue is index.js vs index.ts - index.js works when started up, but once a change is made to code the hmr does to re-process the aliases etc.  Changing to index.ts everything works, bug or feature?

**Comment by nchanged** [comment]
Can u share your config?

**Comment by DaveO-Home** [comment]
const {FuseBox, QuantumPlugin, WebIndexPlugin, CSSPlugin, CSSResourcePlugin, HTMLPlugin, JSONPlugin, UglifyJSPlugin, HMRPlugin, CopyPlugin, EnvPlugin} = require("fuse-box");
	const  {BlockStripPlugin} = require("./appl/js/plugin/BlockStrip");
	const aliases = {
	    "apptest": "./karma/apptest.js",
	    "routertest": "./routertest.js",
	    "toolstest": "./toolstest.js",
	    "domtest": "./domtest.js",
	    "app": "~/js/app",
	    "router": "~/js/router",
	    "pager": "tablesorter/dist/js/extras/jquery.tablesorter.pager.min.js",
	    "default": "~/js/utils/default",
	    "setup": "~/js/utils/setup",
	    "helpers": "~/js/utils/helpers",
	    "config": "~/js/config"
	};
	let value = !process.env.NODE_ENV? EnvPlugin({NODE_ENV: 'development', USE_KARMA: 'false'}) : null;
	let isProduction = process.env.NODE_ENV === 'production';
	let distDir = isProduction ? "dist_prod" : "dist_test";
	let isKarma = process.env.USE_KARMA === "true";
	let useQuantum = true;
	let resources = (f) => (isProduction && isKarma ? `/base/dist_prod/resources/${f}` : isProduction ? `dist_prod/resources/${f}` : `../dist_test/resources/${f}`);
	var src = 'appl';

	const fuse = FuseBox.init({
	    experimentalFeatures: false,
	    plugins: [
		isProduction && WebIndexPlugin({
		    template: "appl/testapp.html",
		    target: "testapp.html",
		}),
		isProduction && useQuantum && QuantumPlugin({
		    //bakeApiIntoBundle: 'acceptance',
		    api: (core) => {
		        core.solveComputed("moment/moment.js");
		    },
		    //uglify: !isKarma,
		    manifest: false
		}),
		["node_modules/font-awesome/**.css",
		    CSSResourcePlugin({
		        dist: distDir + "/resources",
		        resolve: resources
		    }), CSSPlugin()],
		CSSPlugin(),
		HTMLPlugin(),
		JSONPlugin(),
		isProduction && !isKarma && BlockStripPlugin({
		    options: {
		        start: 'develblock:start',
		        end: 'develblock:end'
		    }}),
		isProduction && !isKarma && UglifyJSPlugin({
		    compress: true,
		    mangle: true,
		})
	    ],
	    homeDir: src,
	    output: distDir + "/$name.js",
	    log: true,
	    debug: true,
	    cache: !isProduction,
	    hash: false,
	    sourceMaps: isProduction && !isKarma,
	    alias: aliases,
	    allowJs: true,
	    shim: {
		jquery: {
		    source: "node_modules/jquery/dist/jquery.js",
		    exports: "$",
		}
	    }
	});

	if (!isProduction) {

    fuse.dev({
        root: './',
        port: 3080,
        open: false,
    });

    var vendor = fuse.bundle("vendor")
            .target("browser")
            .instructions(`~ index.ts`);

    var acceptance = fuse.bundle("acceptance")
            .target("browser")
            .instructions(`> [index.ts]`)
            .hmr({reload : true})
            .watch();

	} else {

    fuse.bundle('vendor')
            .target('browser')
            .sourceMaps(true)
            .instructions(`~ index.ts`);

    fuse.bundle('acceptance')
            .target('browser')
            .sourceMaps(false)
            .instructions(`!> [index.ts]) // + ./appl/**/*.{js,html,css,json}`)
            .alias(aliases);
	}

	fuse.run(); //{chokidar : {ignored: /((^|[\/\\])\..|node_modules)/} });
	
and my index.ts and index.js - using  .js alias fails on reload, note; isKarma is false, isProduction is false
	
	
	/* develblock:start */
	if(!window.__karma__) {
	    require ("./js/hmr");
	}
	/* develblock:end */

	window.Popper = require("popper.js");

	var App = require("app"),
		Router = require("router"),
		Default = require("default"),
		Setup = require("setup"),
		Helpers = require("helpers"),
		Config = require("config");
	require("pager");

	App.init(Default);

	var Route = Router.init();

	Setup.init();

	/* develblock:start */
	//Code between the ..start and ..end tags will be removed by the BlockStrip plugin during the production build.
	//testit is true if running under Karma - see testapp_dev.html
	if (typeof testit !== "undefined" && testit) {
	    
	    var apptest = require("./karma/apptest").apptest;

    //Run acceptance tests.
    apptest(Route, Helpers, App);
    jasmine.DEFAULT_TIMEOUT_INTERVAL = 10000;
    setTimeout(function () {
        __karma__.start();  //<===== Very Important - executed here!! -- Fusebox needs a delay.
    }, 500);

	}
	/* develblock:end */

**Comment by nchanged** [comment]
Have you seen that http://fuse-box.org/page/configuration#usetypescriptcompiler ?

You should use it, if you bundle .js instead of .ts

**Comment by devmondo** [comment]
@DaveO-Home also make sure you dont have the same file name as `ts` and `js` as typescript will get confused

**Comment by nchanged** [comment]
@DaveO-Home any updated?

**Comment by DaveO-Home** [comment]
No real updates - I went with development index.ts to use HMR and index.js in production to strip development code(I couldn't get typescript to not strip comments, even with my own tsconf file).
Using usetypescriptcompiler seems to be overkill(but it does fix the hmr problem), Renaming index.js to index.ts is simpler since typescript accepts javascript.
