### ISSUE TITLE
If I just got an error and make a change, I have to manually refresh browser.

### ISSUE THREAD

**Issue by matt-erhart** [fuse-box/fuse-box#806]
Maybe I could plug browsersync into fusebox until it's fixed? I deal with a lot of errors, so I'd rather have a simple refresh from error->maybe error is fixed than to have insta-load only for working code.

**Comment by devmondo** [comment]
yes u can plug browser-sync, something like the below ( minus browser-sync config)

```
fuse.bundle("app")
    .instructions(`>app.tsx`)
    .completed(()=>{
browserSync.reload();
});
```

**Comment by matt-erhart** [comment]
Cool, thanks!

**Comment by devmondo** [comment]
@matt-erhart great 👍 

will close this for now.

**Comment by nchanged** [comment]
Proper implemenation:
http://fuse-box.org/page/development#auto-reload-page

fuse-box@2.3.1-beta.10
