### ISSUE TITLE
Cannot use yarn with flat dependency structure

### ISSUE THREAD

**Issue by chimon2000** [fuse-box/fuse-box#807]
**Description of Problem**
When attempting to use yarn with `"flat":true` set in the package.json, attempting to build after adding resolutions results in build errors.

In a couple of cases, regardless of the dependency I choose I still get errors building the project.  I believe this is because some of FuseBox's dependencies use different versions of the same modules.

**Comment by nchanged** [comment]
Interesting, can you reproduce the issue in a repository?

**Comment by Shepless** [comment]
@chimon2000 is this still an issue for you?
