### ISSUE TITLE
Get shared code between bundles into another bundle

### ISSUE THREAD

**Issue by whitecolor** [fuse-box/fuse-box#808]
I have `main.js` module that dynamicly imports  A and B 
```js
import('./A' )
import('./B')
```
and both `A` and `B` import `C` (statically) 

The question: how to have bundles: main, A, B, C, where C is shared code between A and B?

Such config seem to work:
```js
const bundle = fuse.bundle('main')
  .split('A**', 'A > A.js')
  .split('B**', 'B > B.js')
  .split('C**', 'C > C.js')
  .instructions(`> [main.js] + [A.js] + [B.js] + [C.js]`)
```
But it is quite verbose and too explicit. Is it possible to config automatically have shared code between `A` and `B` into separate bundle without involving `C` in config?

**Comment by nchanged** [comment]
How about dynamic imports? I don't think that code splitting is the best solution here.

**Comment by whitecolor** [comment]
What dynamic import? A and B are imported dynamically in main bundle, and they share some code (statically imported), I would like this code be in the separate bundle. And it should be loaded with either A or B at the moment when A or B bundle is requested.

**Comment by nchanged** [comment]
Well right, you config works? If it does, then we don't have any else, if you want magic, you can create your own helper that does it less verbose.

**Comment by whitecolor** [comment]
Well this config works but it is just simpliest sample. `C` is actually not one module but some commonly shared set of modules. For example webpack has `CommonsChunksPlugin` to accomplish alike tasks, but it is not very smart, works only with very explicit configs (though it works). 

For example in stealjs this task is solved in a quite right way, it automatically finds shared code of all bundles and places it into separate additional bundles automatically. I thought such optimization algorithms should be embedded in advanced bundlers by default, but it seems that it is not the case.

**Comment by nchanged** [comment]
We can cook such functionality, let's create specs for that

**Comment by chickendinosaur** [comment]
This is definitely needed to avoid redundant source code in child chunks.

**Comment by nchanged** [comment]
It's already implemented long time ago
