### ISSUE TITLE
Warning about broswer field in modules when taregting server

### ISSUE THREAD

**Issue by mika-fischer** [fuse-box/fuse-box#810]
I get lots of the following warnings when bundling a nodejs app and I don't know how to silence them:
```WARNING Library "mongoose" contains "browser" field. Set .target("browser") to avoid problems with your browser build!```

**Comment by nchanged** [comment]
`{warnings : false}` ?

**Comment by mika-fischer** [comment]
Fair enough, but why is it warning in the first place if I already specify `.target('server')`? And won't I disable other potentially very useful warnings with `{warnings: false}`?

**Comment by nchanged** [comment]
@mika-fischer you are right! we need to disable those for server builds
