### ISSUE TITLE
Quantum shim moment.js in vendor bundle

### ISSUE THREAD

**Issue by jcmoore0** [fuse-box/fuse-box#811]
I am unable to shim moment.js in the quantum vendor bundle.
The shim works well when not using quantum.
When using quantum, the source js is not included.
I would appreciate any guidance.
Best regards,
John

fuse.bundle('vendor')
        .shim({
                jszip: {
                    source: "node_modules/jszip/dist/jszip.js",
                    exports: "jszip"
                },
                moment: {
                    source: "node_modules/moment/moment.js",
                    exports: "moment"
                }
            })
        .instructions(' ~ main.ts ');

// moment/index.js
$fsx.f[1] = function(module,exports){
module.exports = moment;
}

**Comment by nchanged** [comment]
Hi John!
That might be a bug, in the meantime try setting it to the global config, it should work (I think)

**Comment by nchanged** [comment]
I wasn't able to reproduce the issue. 
But i think i know what's the problem
```
const { FuseBox, QuantumPlugin, WebIndexPlugin, HTMLPlugin, UglifyJSPlugin, CopyPlugin } = require("fuse-box");
const isProduction = true;
const fuse = FuseBox.init({
    homeDir: "src",
    output: "dist/$name.js",
    shim : {
        foo : {exports : "window.foo", source : "./foo.js"}
    },
    plugins: [
        WebIndexPlugin(),
        isProduction && QuantumPlugin({
            target: "browser",
            treeshake: true,
        })
    ]
});

fuse.dev();
fuse.bundle("app")
    .instructions(`>index.ts`);

fuse.run();
```

Quantum creates `shims.js` file. So if you used WebIndexPlugin you wouldn't have had this problem.
