### ISSUE TITLE
Option to customize the file name in CSSResourcePlugin

### ISSUE THREAD

**Issue by ypconstante** [fuse-box/fuse-box#812]
The CSSResourcePlugin currently doesn't have option for the user to customize the name of the generated file.  In my current webpack, i use the format `{libraryname}--{originalfilename}--{hash}.{ext}`. it would be interesting to receive the complete path of the file, to allow this kind of customization, but just receiving the file name  in the function would be enough to help organize the resources folder.

**Comment by nchanged** [comment]
FuseBox is smart with that, it uses easy hashes for development, and full hashes for production. I think it can be customised
