### ISSUE TITLE
Resolve Sass urls based on original file

### ISSUE THREAD

**Issue by ypconstante** [fuse-box/fuse-box#815]
Webpack has the [resolve-url-loader](https://github.com/bholloway/resolve-url-loader) to make the Sass urls resolve from the original file instead of resolving from the file that imported the original file. 
The Sass Plugin currently has macros, that can be helpful to deal with this problem, but it's a FuseBox only solution, and doesn't work with the autocomplete from IDEs.

**Comment by nchanged** [comment]
@ypconstante you can add additions paths to make it work without the `importer`

**Comment by nchanged** [comment]
I am not sure we can help with your IDE.  Use [this](http://fuse-box.org/plugins/sass-plugin#macros) option
