### ISSUE TITLE
parent node_modules not picked up by the bundle

### ISSUE THREAD

**Issue by xaviergonz** [fuse-box/fuse-box#817]
Basically I'm trying to use the new yarn workspaces feature (https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/) that will basically move all "shared" node_modules across many sub-packages to the parent node_modules, but fusebox seems to be ignoring the parent node_modules folder if something cannot be found in the "sub-package" node_modules folder.

Is there a way to tell fusebox to actually look into two node_modules folders? (the one at home plus the one one directory above home)?

**Comment by xaviergonz** [comment]
just to clarify, my current project structure is

/
--/package1/ 
--/package2/ with fuse.js
--/package3/ 

yarn workspaces will create on the root a node_modules with stuff that is shared across package1, 2 and 3

/
--/node_modules/
--/package1/
----/node_modules/
--/package2/ with fuse.js
----/node_modules/
--/package3/
----/node_modules/

when running fusebox inside package2/ it picks up package2/node_modules/ correctly, but it ignores /node_modules/

**Comment by nchanged** [comment]
we have [that](http://fuse-box.org/page/configuration#custom-modules-folder) but it works only with 1 custom folder, we could technically extend it to support multple

**Comment by xaviergonz** [comment]
that'd be awesome!
