### ISSUE TITLE
EnvPlugin not injecting NODE_ENV when using modulesFolder: './node_modules'

### ISSUE THREAD

**Issue by xaviergonz** [fuse-box/fuse-box#818]
Basically when using modulesFolder (even if it is './node_modules', which in theory should do nothing) the EnvPlugin does not inject ```fb.EnvPlugin({ NODE_ENV: "development" }),``` (process.env exists, but it is an empty object)

removing modulesFolder makes it work again

**Comment by nchanged** [comment]
make sure EnvPlugin it inject in the vendor and comes first

**Comment by nchanged** [comment]
@xaviergonz I wasn't able to reproduce the issue. Could you reproduce it in a repository?

**Comment by xaviergonz** [comment]
Closing the ticket since I was unable to reproduce it making a minimal example
