### ISSUE TITLE
Babel's config in VuePlugin

### ISSUE THREAD

**Issue by s4kr4** [fuse-box/fuse-box#821]
Hello,

In the `VuePlugin`, we can specify the transpiler by defining the `lang` attribute.
And if we select `babel`, it seems that we can set babel's config like this.

```javascript
VuePlugin({
  babel: {
    config: {
      "presets": [
        ["env", {
          "targets": {
            "browsers": [
              "last 2 versions",
            ],
          },
        }],
      ],
    },
  },
}),
```

But in this case, `babel` loses default config(`babel-plugin-transform-es2015-modules-commonjs`).
Is this behavior to be expected?
I think that specified settings should be merged with default settings.

Thanks.

**Comment by devmondo** [comment]
@s4kr4  we are working with Mr. @Shepless on making the vue plugin perfect, hang in there, it will be out soon :)

**Comment by nchanged** [comment]
Yeah there will be a fully fledged support for Vue in 2.3.1 it’s coming in 1 week

**Comment by s4kr4** [comment]
Sounds good!

**Comment by TombolaShepless** [comment]
@s4kr4 hey there - I really want a fully functional one too for my own work too. Im working on the plugin now and it is almost done but I am working on it in the evenings in personal time so please bear with me 👍

**Comment by TombolaShepless** [comment]
Update for you @s4kr4 Functionality is developed - its not perfect but it is a lot more feature complete now. I need to write the documentation and will have a PR up tomorrow evening for @nchanged and @devmondo to review.

**Comment by Shepless** [comment]
@s4kr4 can you verify that this issue is now resolved?

**Comment by s4kr4** [comment]
@Shepless It's nice idea that using BabelPlugin instead of the VuePlugin's inner process. This resolved my this issue related to Babel's config.
This issue will close, but now I have another issue on VueComponentPlugin.
I'll make new issue about that.

Thanks.

**Comment by Shepless** [comment]
@s4kr4 good news. Can't see your new issue? Did you manage to resolve?

**Comment by s4kr4** [comment]
@Shepless Sorry for late, I made #835 .
