### ISSUE TITLE
Resolve path

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#824]
Guys, is there any functionality that would give me a current module path, such as commonJs’s require.resolve?

**Comment by tomitrescak** [comment]
Got it.

__filename
__dirname

standard node.js ;)

**Comment by calebboyd** [comment]
Implementing:
`require.cache`
`require.extensions`
`require.resolve` 

would be helpful though...

**Comment by JamesMGreene** [comment]
:+1: to @calebboyd's comment. The omission of `require.resolve` was an immediate issue for me when trying to bundle our production app.
