### ISSUE TITLE
source map file name was wrong when bundle name with dot

### ISSUE THREAD

**Issue by zeniroy** [fuse-box/fuse-box#825]
``` javascript
const fuse = FuseBox.init({
...
output: "build/$name",
sourceMaps: true,
...
});

fuse.bundle('index.js')
```

output file is "index.js" but source map file name is "index.js.js.map".

How can i fix it?

**Comment by nchanged** [comment]
@zeniroy 
`output: "build/$name.js",`

`fuse.bundle('index')`

**Comment by zeniroy** [comment]
I want use filename with some dots.(ex. some.file.name.with.dot.min.js ) I found that when i use bundle name with dot, extension in output option is ignored. so i cannot use like this

'''javascript
output: 'build/$name.js'
'''

**Comment by nchanged** [comment]
@zeniroy that's right, js is added automatically, and `min` considered to be extension.

**Comment by nchanged** [comment]
@zeniroy `fuse-box@2.3.1-beta.16`

**Comment by zeniroy** [comment]
ok, i works. thanx!
