### ISSUE TITLE
A failed task should exit with a non-zero exit code

### ISSUE THREAD

**Issue by chelmertz** [fuse-box/fuse-box#828]
I'm a bit new to fuse and I got stuck on making a task fail with a non-zero exit code.

Both of these tasks fail with an exit code of 0:

```js
Sparky.task('fail', () => {
  return 1;
});
```

```js
Sparky.task('exception', () => {
  throw new Error("Fail, please");
});
```

Do I have to surround all of the contents in a `Sparky.task()` in a try-catch and `call process.exit(1)` manually?

Fuse is only a part of our build process (JS for the front-end, something else for the backend) so it's very important that I can trust that "an exit code of 0 == a successful build", which I cannot right now 

I'm running the task with the regular npm fuse fail command and the Fuse version I tried is 2.2.31

**Comment by nchanged** [comment]
@chelmertz I've just checked it.
Exit code 0 - success
Exit code 1 - error

```
Sparky.task('default', () => {
    throw new Error("Fail, please");
  });
```

Are you doing something wrong?

**Comment by chelmertz** [comment]
I will get back to you with something reproducible.

Den 27 sep. 2017 21:16 skrev "nchanged" <notifications@github.com>:

**Comment by nchanged** [comment]
AS it was verified and returning corresponding codes, I am closing this for now. Feel free to re-open once reproduced.

**Comment by danielbodart** [comment]
Hi there, I'm having the same problem but all of my tasks are async:

task('compile', async () => {
    return await tsc('.', {}); // Not sure if I need the return here or not
});

If the file fails to compile it still carries on, am I missing something?

**Comment by nchanged** [comment]
It might be it, yes. need to check the implementation. I am in vacation atm, feel free to make a PR :)

**Comment by nchanged** [comment]
@danielbodart please try `fuse-box@3.7.0-next.12`
