### ISSUE TITLE
Fails to install in some environments

### ISSUE THREAD

**Issue by calebboyd** [fuse-box/fuse-box#831]
Running into an error where some environments might not have the `node` executable.
Eg. apt installs node to `nodejs`

Fusebox fails to install in these environments because `opencollective postinstall` executes a script with the `node` executable

**Comment by nchanged** [comment]
I guess we need to remove it, nobody donates anyway 😢

**Comment by calebboyd** [comment]
😧 😭  
I was able to get around it with a temporary session long symlink / path hack. Just thought I'd let you know.

**Comment by devmondo** [comment]
:(
