### ISSUE TITLE
VueComponentPlugin's bundle process often doesn't work properly with BabelPlugin

### ISSUE THREAD

**Issue by s4kr4** [fuse-box/fuse-box#835]
Hello,

I tried using VueComponentPlugin with BabelPlugin, but it doesn't work properly.

Reproduce

1. Clone [this repogitory](https://github.com/s4kr4/fuse-box-vue-sample).
2. Install npm modules.
3. `yarn start` or `npm start`
4. Hit `Ctrl + C` to stop watching.
5. Restart `yarn start` or `npm start`.

The first process includes `index.js`, `App.vue` and `Test.vue`, but the second process includes only `index.js`.

![fusebox-bug](https://user-images.githubusercontent.com/7105797/31056306-8ff48be6-a70a-11e7-914c-e07a647d1141.gif)

Is the setting file([fuse.js](https://github.com/s4kr4/fuse-box-vue-sample/blob/master/fuse.js)) wrong?

Thanks.

**Comment by nchanged** [comment]
Can you try removing Babel and use [useTypescriptCompiler](http://fuse-
box.org/page/configuration#usetypescriptcompiler) option instead?
@Shepless I think we should somehow make it by default ... it's a very powerful option and it's suitable for so many cases.

**Comment by Shepless** [comment]
@nchanged it is typescript by default. I'm out at the moment but will take a look later

**Comment by nchanged** [comment]
@s4kr4  yep, remove Babel and use this config ;-)
```
const fuse = FuseBox.init({
  homeDir: './src',
  output: 'dist/$name.js',
  useTypescriptCompiler : true,
  plugins: [
    VueComponentPlugin({}),
    WebIndexPlugin({
      template: './src/index.html'
    }),
  ],
});
```

**Comment by s4kr4** [comment]
@nchanged 
Thank you for your advice.
I took your advice ([this commit](https://github.com/s4kr4/fuse-box-vue-sample/commit/456731000dc742487d616e011207493e95ac836c)).
It came to include `index.js` and `App.vue`, but exclude `Test.vue` constantly.

**Comment by TombolaShepless** [comment]
@s4kr4 This is not an issue with FuseBox - it is how Typescript works. If you `import Foo from './foo'`; but never actually use that import it will not be transpiled - have a try with tsc directly in your console on a couple of files. More info can be found [here](https://github.com/Microsoft/TypeScript/issues/9191). If you update you're `App.vue` to:

```html
<script lang="js">
import Test from './Test.vue';

export default {
  name: 'app',
  components: {
    Test
  }
}
</script>
```

In addition you have another issue:

```js
new Vue({
  el: '#root',
  render: h => h(App)
})
```

^^^^^ In index.html you have no div with `id="root"`, it is a class. If you fix these 2 issues then it works absolutely fine.

@nchanged can be closed as its not a FuseBox issue

**Comment by s4kr4** [comment]
It was my mistake. Sorry :(
