### ISSUE TITLE
[Question] FuseBox and ASP.NET Core with HMR support

### ISSUE THREAD

**Issue by HamedFathi** [fuse-box/fuse-box#845]
How to use FuseBox and ASP.NET Core with **HMR support**?

Can anyone guide me or share a sample?

**Comment by nchanged** [comment]
@HamedFathi hi!
isn't it .Dot and not javascript? ;-)

**Comment by devmondo** [comment]
@HamedFathi what u r missing? 
are you doing SPA or standard site with .NET? 
mostly you will not have to do anything .NET specific, just make sure to proxy fuse devserver to your .NET  
 http://fuse-box.org/page/development#proxy.
the rest is purely fuse :) let us know if u need more info.

**Comment by HamedFathi** [comment]
@nchanged @devmondo 

Hi!, I want to use FuseBox with Aurelia and ASP.NET Core as **SPA** project but in Webpack we have [JavaScriptServices](https://github.com/aspnet/JavaScriptServices) for [HMR](http://angularfirst.com/asp-net-core-javascript-services-with-webpack-hmr/) integration.

```
// Startup.cs

// ...
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
// ...
if (env.IsDevelopment())
{
  app.UseDeveloperExceptionPage();
  app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions {
    HotModuleReplacement = true
  });
}

app.UseDefaultFiles();

// ...
}
```

so My question is Do we have something similar to Webpack and JavaScriptServices for activating HMR on ASP.NET Core?

of course, I did not test fusebox proxy **yet**.

**Comment by nchanged** [comment]
there is no need in that ^ You can just say
```
fuse.dev({httpServer : false})
```

That's it. HMR will be working with your IIS http server

**Comment by HamedFathi** [comment]
@nchanged 

Thanks, 

ASP.NET Core works on any web servers, not just IIS.
eg : [Kestrel ](https://docs.microsoft.com/en-us/aspnet/core/publishing/linuxproduction?tabs=aspnetcore2x) or [Nginx](https://docs.microsoft.com/en-us/aspnet/core/publishing/linuxproduction?tabs=aspnetcore2x)

Does it work for any web server ? or a tip for IIS?

**Comment by nchanged** [comment]
any server @HamedFathi

**Comment by devmondo** [comment]
@HamedFathi fuse dont care about whatever server technology you use :)  just enable HMR and proxy your server endpoint and boom !

**Comment by HamedFathi** [comment]
I opened [new issue](https://github.com/fuse-box/fuse-box/issues/853) so I close this one
