### ISSUE TITLE
Babel transform class properties, what's wrong?

### ISSUE THREAD

**Issue by direct-fuel-injection** [fuse-box/fuse-box#85]
Hello. Gulp task code:
```
gulp.task('build', ['clean', 'prepare'], function () {
    var fuse = new fusebox.FuseBox({
        homeDir: buildDir,
        cache: true,
        outFile: path.join(buildDir, 'bundle.js'),
        plugins: [
            fusebox.CSSPlugin(),
            fusebox.BabelPlugin({
                test: /\.jsx?$/,
                config: {
                    presets: ["es2015", "stage-0", "react"],
                    plugins: [["transform-react-jsx"]]
                }
            })
        ]
    });

    return fuse.bundle('>index.js');
});
```

Error:
```
 [12:13:28] Starting 'build'...
SyntaxError: unknown: Unexpected token (13:10)
  11 | 
  12 | class App extends Component {
> 13 |     state = {
     |           ^
  14 |         isLoading: true
  15 |     }
  16 |     shouldComponentUpdate (nextProps, nextState) {
    at Parser.pp$5.raise (/home/dfi/Projects/ReduxAppBoiler/node_modules/babel-core/node_modules/babylon/lib/index.js:4246:13)
    at Parser.pp.unexpected (/home/dfi/Projects/ReduxAppBoiler/node_modules/babel-core/node_modules/babylon/lib/index.js:1627:8)
    at Parser.pp$1.parseClassProperty (/home/dfi/Projects/ReduxAppBoiler/node_modules/babel-core/node_modules/babylon/lib/index.js:2419:50)
    at Parser.pp$1.parseClassBody (/home/dfi/Projects/ReduxAppBoiler/node_modules/babel-core/node_modules/babylon/lib/index.js:2330:34)
    at Parser.pp$1.parseClass (/home/dfi/Projects/ReduxAppBoiler/node_modules/babel-core/node_modules/babylon/lib/index.js:2270:8)
    at Parser.pp$1.parseStatement (/home/dfi/Projects/ReduxAppBoiler/node_modules/babel-core/node_modules/babylon/lib/index.js:1711:19)
    at Parser.pp$1.parseBlockBody (/home/dfi/Projects/ReduxAppBoiler/node_modules/babel-core/node_modules/babylon/lib/index.js:2133:21)
    at Parser.pp$1.parseTopLevel (/home/dfi/Projects/ReduxAppBoiler/node_modules/babel-core/node_modules/babylon/lib/index.js:1645:8)
    at Parser.parse (/home/dfi/Projects/ReduxAppBoiler/node_modules/babel-core/node_modules/babylon/lib/index.js:1537:17)
    at parse$1 (/home/dfi/Projects/ReduxAppBoiler/node_modules/babel-core/node_modules/babylon/lib/index.js:6466:37)
[12:13:28] Finished 'build' after 256 ms

```

**Comment by devmondo** [comment]
@direct-fuel-injection 
are you sure you included all required babel plugins?

**Comment by direct-fuel-injection** [comment]
```
npm list | grep babel-preset
├─┬ babel-preset-es2015@6.18.0
├── babel-preset-latest@6.16.0 extraneous
├─┬ babel-preset-react@6.16.0
├─┬ babel-preset-stage-0@6.16.0
│ └─┬ babel-preset-stage-1@6.16.0
│   └─┬ babel-preset-stage-2@6.18.0
│     └─┬ babel-preset-stage-3@6.17.0

```

**Comment by devmondo** [comment]
@direct-fuel-injection 
i may be wrong but shouldn't  
```
state = {
     |           ^
  14 |         isLoading: true
  15 |     }
```
be
```
state:{} //notice the double colon 
```

**Comment by nchanged** [comment]
That issue is coming from babel, no fusebox trace back is here

**Comment by devmondo** [comment]
@nchanged he has syntax error above as i mentioned

**Comment by direct-fuel-injection** [comment]
@devmondo webpack + babel works with that code fine.

**Comment by nchanged** [comment]
But if you get a babel error that means that fuse has nothing to do with it

**Comment by direct-fuel-injection** [comment]
@nchanged looks like babel-preset-stage-0 not included.

**Comment by direct-fuel-injection** [comment]
@devmondo [babeljs.io/repl](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-0&code=class%20App%20extends%20Component%20%7B%0A%20%20%20%20state%20%3D%20%7B%0A%20%20%20%20%20%20%20%20isLoading%3A%20true%0A%20%20%20%20%7D%0A%20%20%20%20loadImage%20%3D%20(url%2C%20callback)%20%3D%3E%20%7B%7D%0A%20%20%20%20render()%20%7B%7D%0A%7D%0A) transformed code.

**Comment by direct-fuel-injection** [comment]
state = {} added this line to react-example demo code, samer error.

**Comment by devmondo** [comment]
@nchanged do we use `acorn` when we use `babel` plugin ?

**Comment by devmondo** [comment]
@direct-fuel-injection do you have repo so we can reproduce this ?

**Comment by nchanged** [comment]
@devmondo no it skips it ...

**Comment by devmondo** [comment]
@nchanged then most probably it is not fuse! as fuse dont modify the source code.

any ways if @direct-fuel-injection  provide repo  we will see if we can reproduce it.

**Comment by nchanged** [comment]
@direct-fuel-injection config is fed to babel-core as is. Make sure you have it all installed (plugins, presets). And yes, if nothing helps we are ready to help as soon as you give us some sample code.

**Comment by direct-fuel-injection** [comment]
@nchanged, @devmondo [forked react-example](https://github.com/direct-fuel-injection/react-example).

**Comment by devmondo** [comment]
@direct-fuel-injection , after lots of testing, i found the problem.

you did not install `babel-preset-stage-0`, install it and just add it to `babel` preset `   presets: ["latest","stage-0"]` and everything works fine.

**Comment by direct-fuel-injection** [comment]
@devmondo I've found that `sourceMaps: false` gives `Acorn error: Unexpected token (5:10)`.
Can you checkout latest commits in [react-example](https://github.com/direct-fuel-injection/react-example)?

**Comment by devmondo** [comment]
@direct-fuel-injection  i just tested it and it runs fine without error, again try to delete fuse cache folder and node_modules folder and start from scratch and let us know.

**Comment by direct-fuel-injection** [comment]
@devmondo after cache cleared same error.

**Comment by devmondo** [comment]
@nchanged do you have any idea about why this would cause sourcemaps errors with @direct-fuel-injection ?

on my machine, i tested with source maps, and everything looks fine and i get no errors.

@direct-fuel-injection, if you get the same error even after installing babel preset and removing cache, then there is something really odd!!! i attached screen shot to show you it is working
![image](https://cloud.githubusercontent.com/assets/1266367/21998568/12ef99be-dc4f-11e6-9664-bc6be88a7ab7.png)

**Comment by direct-fuel-injection** [comment]
@devmondo turn off sourcemaps

**Comment by nchanged** [comment]
#180

**Comment by 8-uh** [comment]
Experiencing this on v1.3.115

`.babelrc`
```language-json
{
  "sourceMaps": true,
  "presets": [
    "latest",
    "stage-0"
  ],
  "plugins": [
    "transform-class-properties",
    "transform-react-jsx"
  ]
}
```

offending js
```
export default class Editor extends Component {
  let codeblock = null
  let codewrap = null

  componentDidMount() {
    this.editor = new Misbehave(codeblock)
  }
  render() {
    <pre refs={() => {codewrap = pre}}>
      <code
        className="language-javascript"
        contenteditable="true"
        autocorrect="off"
        autocapitalize="off"
        spellcheck="false"
        ref={() => {codeblock = code}}></code>
    </pre>
  }
}
```

**Comment by 8-uh** [comment]
And.... please disregard... had the wrong syntax for class properties.

mea culpa

**Comment by nchanged** [comment]
Have u tried nuking? (Cache)
