### ISSUE TITLE
polyfillNonStandardDefaultUsage not working with axios

### ISSUE THREAD

**Issue by linde12** [fuse-box/fuse-box#850]
I encountered a problem with the 'polyfillNonStandardDefaultUsage` option when i used a library called `axios`

Steps to reproduce:
1. Clone fuse-box/react-example
2. Add `polyfillNonStandardDefaultUsage: true,` to fuse.js
3. Run `npm install axios`
4. Add the following code to index.jsx `import axios from 'axios'; axios({method: 'get', url: '/bla/bla'});`
5. Observe the stacktrace:

```
Uncaught RangeError: Maximum call stack size exceeded
    at assignValue (vendor.js:21577)
    at forEach (vendor.js:21552)
    at merge (vendor.js:21586)
    at assignValue (vendor.js:21579)
    at forEach (vendor.js:21552)
    at merge (vendor.js:21586)
    at assignValue (vendor.js:21579)
    at forEach (vendor.js:21552)
    at merge (vendor.js:21586)
    at assignValue (vendor.js:21579)
```

**Comment by nchanged** [comment]
Isn't it coming from the `axios` library and not from fusebox?

**Comment by linde12** [comment]
I'm not entierly sure why, but i know it works without the polyfill. I am trying to debug it but not getting far as i'm not familiar with fusebox internals (yet :-))

**Comment by nchanged** [comment]
I will check it later on, no problem. For now, you can follow the standards  as axios doesn't export `default`

`import * as axios from 'axios'

**Comment by linde12** [comment]
Alright, thank you!

**Comment by nchanged** [comment]
@linde12 `fuse-box@2.3.4-beta.1`

**Comment by linde12** [comment]
Glad to see i was looking at the right file at least.

I'm getting an error using the `react-example` (+ polyfillNonStandard) app with the following code in index.jsx (and 2.3.4-beta.1). I can also change the imports to `import React from 'react'` and that yíelds the same effect.

```
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import './index.css';


import axios from 'axios'
axios({method: 'get', url: '/bla/bla'})


ReactDOM.render(
  <div>hello</div>, document.getElementById('root'));
```

It seems to work if i remove react & react-dom and just use axios(even though i get another error sometimes because, just because i'm not calling ReactDOM.render ? :confused: )

The error i'm getting is this:
```
index.tsx:11 Uncaught TypeError: Cannot define property default, object is not extensible
    at Function.defineProperty (<anonymous>)
    at module.exports (index.tsx:11)
    at Number.<anonymous> (vendor.js:1880)
    at c (vendor.js:22752)
    at w.require (vendor.js:22752)
    at vendor.js:77
    at Number.<anonymous> (vendor.js:1755)
    at c (vendor.js:22752)
    at w.require (vendor.js:22752)
    at Number.<anonymous> (vendor.js:24)
```

Do we have to create a new object to put the properties on? Do you have a clue of what's going on? I still don't know how to get source maps for vendor.js so i can't provide much more information than that.

**Comment by nchanged** [comment]
oh, that's because of that  line
```
if (process.env.NODE_ENV !== 'production') {
  Object.freeze(emptyObject);
}
```

**Comment by nchanged** [comment]
this should fix it `fuse-box@2.3.4-beta.2` but in the long run we probably need to patch require statements instead

**Comment by linde12** [comment]
LGTM, except now there are console.log's popping up for every module. I'm not sure if this is related to this change though.

I will try to get a proxy server running (redirect my API calls to my RPI) and see if my app works. I'll report back!

**Comment by nchanged** [comment]
Sorry man, my bad `fuse-box@2.3.4-beta.3`

**Comment by linde12** [comment]
No problem, i'm thankful for your time.

I set up the proxy (super easy btw, i was able to paste my solution from webpack) and everything seems to work just fine. Thanks a lot!
