### ISSUE TITLE
[VueComponentPlugin] Uncaught package not found vue-hot-reload-api

### ISSUE THREAD

**Issue by cmizzi** [fuse-box/fuse-box#852]
I've got an error while using the `VueComponentPlugin`. I installed all dependencies, cleaned up `node_modules`, `.fusebox` but the package is still not found.

```json
{
  "name": "fusebox",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "lodash": "^4.17.4",
    "typescript": "^2.5.3"
  },
  "devDependencies": {
    "autoprefix": "^1.0.1",
    "autoprefixer": "^7.1.4",
    "fuse-box": "^2.3.2",
    "postcss": "^6.0.13",
    "postcss-selector-parser": "^2.2.3",
    "precss": "^2.0.0",
    "vue": "^2.4.4",
    "vue-hot-reload-api": "^2.1.1",
    "vue-template-compiler": "^2.4.4",
    "vue-template-es2015-compiler": "^1.5.3"
  }
}
```

```js
const {FuseBox, PostCSSPlugin, CSSPlugin, VueComponentPlugin} = require('fuse-box')
const fuse      = FuseBox.init({
	homeDir    : 'sources',
	output     : 'built/$name.js',
	log        : true,
	sourceMaps : false,
	plugins    : [
		VueComponentPlugin(),
		CSSPlugin(),

		[
			'style/**.css', 

			PostCSSPlugin(require('autoprefixer')(), require('precss')()),
			CSSPlugin()
		]
	],
	useTypescriptCompiler : true
})

fuse.dev({ root: './', port: 8081, devServer: false })
fuse.bundle('vendor').instructions('~ index.ts').watch().hmr()
fuse.bundle('app').instructions('!> [index.ts]').watch().hmr()
```

**Comment by TombolaShepless** [comment]
@cmizzi thanks for bringing the issue to our attention. I'm not able to look at this until tomorrow unfortunately but I will try to get to the cause of your issue and get back to you ASAP.

**Comment by Shepless** [comment]
@cmizzi I have tried for a while now but I cannot reproduce this issue - please can you provide a demo repo (or the actual repo if possible) showing the issue? Thanks.

**Comment by cmizzi** [comment]
This is the public repository : https://github.com/cmizzi/fusebox-vuecomponentplugin

```bash
fusebox master 51e87b9 ➜ yarn
fusebox master 51e87b9 ➜ node ./fuse.js
```

```bash
fusebox master 51e87b9 ➜ node -v
v7.0.0
```

**Comment by Shepless** [comment]
@cmizzi PR is up - it will resolve the issue you raised. Thanks for bringing it to our attention. On a side note, you're repo has a small issue when importing `Vue`. You either need to use:

```js
import * as Vue from 'vue';
```

or in your FuseBox config, use the [polyfillNonStandardDefaultUsage](http://fuse-box.org/page/configuration#polyfillnonstandarddefaultusage) option:

```js
polyfillNonStandardDefaultUsage: true
// or just for vue
polyfillNonStandardDefaultUsage: ['vue']
```

**Comment by cmizzi** [comment]
Great, thank you for your replies. It works now.
