### ISSUE TITLE
Integration with ASP.NET Core and Aurelia

### ISSUE THREAD

**Issue by HamedFathi** [fuse-box/fuse-box#853]
One of the classic sample project with Aurelia and ASP.NET Core and Webpack comes from here

[Microsoft.AspNetCore.SpaTemplates](https://www.nuget.org/packages/Microsoft.AspNetCore.SpaTemplates/)

You should install it with this command
`dotnet new --install Microsoft.AspNetCore.SpaTemplates::*`

and use it with this command `dotnet new aurelia`

this sample works with `webpack` perfectly but I uploaded it on my github and wrote `fuse.js` for that.

[Aurelia-ASP.NETCore-WebPack](https://github.com/HamedFathi/Aurelia-ASP.NETCore-WebPack)

I borrowed the most settings from the awesome project [aurelia-skeleton-fusebox](https://github.com/arabsight/aurelia-skeleton-fusebox/blob/master/fuse.js)

but I have some problems that you can see in below picture, can anyone help me for replacing webpack in this project and fix the problems?

![untitled](https://user-images.githubusercontent.com/8418700/31287089-0245e206-aacd-11e7-9576-451ae8eaa74d.png)

when I use `webpack` commands it produced files like below

![1](https://user-images.githubusercontent.com/8418700/31287222-6ac143e8-aacd-11e7-9f89-f98b434bc65f.png)

another problem is `dotnet run` command and integration with FuseBox. when we run `dotnet run` the project run on `localhost:5000` but I have problem on it. 

```
const {
    Sparky,
    FuseBox,
    EnvPlugin,
    RawPlugin,
    HTMLPlugin,
    JSONPlugin,
    UglifyJSPlugin,
    WebIndexPlugin
} = require('fuse-box');

let production = process.env.NODE_ENV === 'production';

let vendorModules = [
    'aurelia-loader-fusebox',
    'aurelia-bootstrapper',
    'aurelia-framework',
    'aurelia-event-aggregator',
    'aurelia-fetch-client',
    'aurelia-history-browser',
    'aurelia-logging-console',
    'aurelia-pal-browser',
    'aurelia-polyfills',
    'aurelia-route-recognizer',
    'aurelia-router',
    'aurelia-templating-binding',
    'aurelia-templating-resources',
    'aurelia-templating-router',
    'bootstrap',
    'jquery',
    'aurelia-animator-css',
    'whatwg-fetch',
    'bluebird'
];

Sparky.task('clean', () => Sparky.src('dist/*').clean('dist'));

Sparky.task('build', () => {
    const fuse = FuseBox.init({
        homeDir: 'ClientApp',
        output: 'wwwroot/dist/$name.js',
        debug: !production,
        log: !production,
        hash: production,
        cache: !production,
        target: 'browser',
        plugins: [
            EnvPlugin({ NODE_ENV: production ? 'production' : 'development' }),
            RawPlugin(['.css']),
            HTMLPlugin({ useDefault: true }),
            JSONPlugin(),
            production && UglifyJSPlugin()
        ]
    });

    const vendor = fuse.bundle('vendor')
        .shim({
            jquery: {
                source: "node_modules/jquery/dist/jquery.js",
                exports: "$"
            }
        })
        .instructions(`${vendorModules.join(' + ')}`);

    const app = fuse.bundle('app')
        .instructions(`!> boot.ts + [**/*.{js,html,css}]`);

    if (!production) {
        app.watch().hmr().sourceMaps(true);
    }

    if (!production) {
        fuse.dev({
            root: 'wwwroot/dist',
            port: 5000,
            hmr: true,
            httpServer: false
        });
    }
    return fuse.run();
});

Sparky.task('copy', () => {});

Sparky.task('default', ['clean', 'copy', 'build'], () => { });
```

**Comment by devmondo** [comment]
@HamedFathi you are using your app at port 5000 which is the fuse dev server port, but in your config, you disabled that using `httpServer:false` so fuse has no way to resolve those files. 
you either enable fuse httpServer ( which i think you don't want because you are already using asp.net server) or use the proxy option to rewrite those paths to your asp.net server

**Comment by HamedFathi** [comment]
@devmondo Is it possible for you to change my fuse.js to correct one? I don't know how to fix it.

**Comment by Shepless** [comment]
@HamedFathi Its in the documentation [here](http://fuse-box.org/page/development#proxy). Please  have a read and try implementing.
