### ISSUE TITLE
suggestion: vue ts example with single file component

### ISSUE THREAD

**Issue by Jack85** [fuse-box/fuse-box#856]
Would be nice to have vue single file component project, with typescript, less, sass, vue-class-component example provided.

**Comment by Shepless** [comment]
Hi @Jack85 everything you mentioned there (apart from vue-class-component) is in the [vue-seed](https://github.com/fuse-box/fuse-box-vue-seed). It would be a great help if you can create a PR to add in the vue-class-component side of things.

**Comment by Jack85** [comment]
Unfortunately not quite, you are using babel there (not like <script lang="ts"), even I tried that config, I put typescripthelpers there I couldnt make it work. - got error with missing tslib, tried tweak it no success.
So I dont like generalization when different configuration has different behavior very often thats why I would ask ts only example.

**Comment by Shepless** [comment]
@Jack85 we are using typescript compiler not babel.

**Comment by Jack85** [comment]
In that seed, not seem to be used typescript for component. 
my typical construct in ts would be `export default class extends Vue`
Export default doesnt compile in ts as far as I know. You entry is js file not ts file like in my case and so on...

**Comment by Shepless** [comment]
I do not wish to come across as rude - that isn't my intention. However, have you read the fuse config file? Or the documentation? 

If you set use typescript compiler and allowjs, Fuse box will use typescript. The only way for babel to be used is to explicitly setup the BabelPlugin (which isn't there in the seed). 

Typescript is a super set of JavaScript, which means any valid JS is also valid TS. Creating a class or exporting default is not a typescript construct - they are both standard ES2015. 

The reason we don't use Babel is because Typescript can do it and with much less hassle. I have to drive to work now but will be online later. Please read the docs and the fuse config in the seed - if it still doesn't seem clear then let me know.

**Comment by Jack85** [comment]
To be formal, You can see typical ts constructs here: 
https://vuejs.org/v2/guide/typescript.html
Everytime with component options or vue-class-component
Constructs you are using is typical babel setup example.  I checked the config and docs says it detects ts automatically, and yes it compiles but it doesnt get me there - error `Uncaught Package not found tslib`
Tested wit your tsconfig, mine ts config working with webpack fine, with fuse I get tslib error and lots of warnings.. like -- comment.js" has failed to resolve in module "default"
My fuse config looks like:
```
const {
    FuseBox,
    VueComponentPlugin,
    QuantumPlugin,
    HTMLPlugin,
    LESSPlugin,
    SassPlugin,
    CSSPlugin,
    CSSResourcePlugin,
    WebIndexPlugin,
    Sparky,
    BabelPlugin,   
    TypeScriptHelpers,
    JSONPlugin 
   
} = require("fuse-box");

let fuse;
let isProduction = false;

Sparky.task("set-prod", () => {
    isProduction = true;
});
Sparky.task("clean", () => Sparky.src("./dist").clean("dist/"));
Sparky.task("watch-assets", () => Sparky.watch("./assets", { base: "./src" }).dest("./dist"));
Sparky.task("copy-assets", () => Sparky.src("./assets", { base: "./src" }).dest("./dist"));

Sparky.task("config", () => {
    fuse = FuseBox.init({
        homeDir: "./src", //Statement "components/admin/editpost.js" has failed to resolve in module "default"
        output: "dist/$name.js",
        //hash: isProduction,
        sourceMaps: !isProduction,
        useTypescriptCompiler: true,
        polyfillNonStandardDefaultUsage: true,
        target: "browser",
        plugins: [
            VueComponentPlugin({
                style: [
                    LESSPlugin({
                       // paths: [path.resolve(__dirname, 'node_modules')]
                    }),
                   // TypeScriptHelpers(),
                    CSSResourcePlugin(),
                    CSSPlugin({
                        group: 'components.css',
                        inject: 'components.css'
                    })
                ]
            }),
            TypeScriptHelpers(),
            CSSPlugin(),
            WebIndexPlugin({
                template: "./index.html"
            }),
            isProduction && QuantumPlugin({
                bakeApiIntoBundle: "vendor",
                uglify: true,
                treeshake: true
            }),
        ],
        shim: {
            jquery: {
                source: "node_modules/jquery/dist/jquery.min.js",
                exports: "$"
            }
        }
    });

    if(!isProduction){
        fuse.dev({
            open: true,
            port: 8080
        });
    }
    
    const vendor = fuse.bundle("vendor")
        .instructions("~ app.ts");

    const app = fuse.bundle("app")
        .instructions("> [app.ts]");

    if(!isProduction){
        app.watch().hmr();
    }
})

Sparky.task("default", ["clean", "watch-assets", "config"], () => {
    return fuse.run();
});

Sparky.task("dist", [ "clean", "copy-assets", "set-prod", "config"], () => {
    return fuse.run();
});
```
mine tsconfig
```
{
  "compilerOptions": {
    "module": "es2015",
    "target": "es5",  
    "allowSyntheticDefaultImports": true, "moduleResolution": "node", 
    "sourceMap": true, "experimentalDecorators": true, "lib": [
      "dom",
      "es5","es6", "esnext",
      "es2015.promise", "es2015.iterable","dom.iterable","es2015"
    ]
   , "noImplicitAny": false
  },
  "exclude": [ "node_modules"  ]
}
```

**Comment by TombolaShepless** [comment]
@Jack85 Thanks for getting back to me. I'll pull down the vue seed repo and have a play around -
 will keep you posted 👍

**Comment by Jack85** [comment]
Thats why I think It would be wise to have separate just TS only example to play with, too see it working and putting more libraries there see if its still working. 
Otherwise If not reproducible, i could put small project here to test afterwards.

**Comment by TombolaShepless** [comment]
@Jack85 Update for you bud - I have taken a look and there are two separate issues I can see:

1) When using TS the `TypeScriptHelper` plugin is not being used when really it should (incase you use decorators etc.)
2) When explicitly using `lang="ts"` and `useTypescriptCompiler: true` Fuse will tell you it cannot find a valid plugin to process the file

I'm at work now and have to leave this until this evening but will hopefully have a PR up soon.

**Comment by Jack85** [comment]
Yes, decorators highly recommended Im, using av-ts, vue-class-coponent, vue-property-decorator.. 
Would be cool to see that with fuse.

**Comment by Shepless** [comment]
@Jack85 PR #861 is up to fix point 2) above. Looking into point 1) now.

**Comment by Jack85** [comment]
Im in process of creating simple complex project if you want to test.. ?

**Comment by Shepless** [comment]
Sure - you got a link? I have a fix for point 2) but it needs reviewing as I think I might be doing some "no-nos". I have also updated the `vue-seed` locally to test out the changes and it works fine with  `vue-class-component` now.

When the fix is merged I'll also push the update version of the seed up. I know it isn't exactly what you wanted in terms of a fully fledged "here is how you write Vue in typescript" but I'd rather show that we can support as many different variations of Vue usages as possible. If you want to create you're own, more opinionated fusebox-vue-seed then that would be awesome and we can link to it from the website. What do you think?

**Comment by Jack85** [comment]
Ok, I ll prepare it tomorow.. and let you know. 
My target is simple -  it compiles smooth with webpack, it should compile smooth with fuse WITHOUT changing code inside components in order to compile with fuse.. (jquery $ import is typical example) Only thing changing should be ts and fuse config. 
I tend to use several libraries with decorators.. more is better to test i think.  I used to experiment with ts libraries and babel in one project. 

If I get it working sample at some stage then I can think of making seed. There are not many high quality examples covering this out there.
I ll simplify and give you some link.

**Comment by Shepless** [comment]
Excellent - thats great news!

**Comment by Jack85** [comment]
Here you go https://github.com/Jack85/vue-ts-ex
small app, would be cool to see also how fuse uses url or file-loaders, if you can make it work.

**Comment by Jack85** [comment]
updated example to use latest webpack, problem moved loadin woff..

**Comment by TombolaShepless** [comment]
@Jack85 sorry bud - I have been away for the weekend and not able to access a computer (and now Im at work) I will take a look tonight at what you have there.

**Comment by Shepless** [comment]
@Jack85 update - PR #870 is now up for review, it will play nice with `vue-class-component`.

**Comment by Jack85** [comment]
Thanks, when there ll be sample or version to test?

**Comment by nchanged** [comment]
@Jack85 use the latest beta

**Comment by Jack85** [comment]
what would be also interesting to see in your examples, what i dint put in my example yet, async components and file spliting features recently introduced..

**Comment by TombolaShepless** [comment]
@Jack85 did this solve your issues (in terms of being able to use tools like `vue-component-class`)?

**Comment by Jack85** [comment]
not there yet, but as soon I ll come there I ll let you know.

**Comment by Jack85** [comment]
using 2.3.4-beta.11
Test app appears and seems to work, complexer gets rendered without javascript injected, showing empty page

```
<div id="app"></div>
--
  | <!-- <script  type="text/javascript" src="/vendor.js"></script>
  | <script  type="text/javascript" src="/app.js"></script> -->
  | </body>
```


styles not loaded with less plugin when importing like so 

```
<style lang="less" >
 
  @import url("./../node_modules/bootstrap/dist/css/bootstrap.min.css");
```
importing woff font in ts
`import './../node_modules/markdown-it-editor/lib/css/iconfont.b300b13.woff'`
getting warning 
```
\node_modules\markdown-it-editor\lib\css\iconfont.b300b13.woff.ts" cannot be
bundled because it's out of your project directory (homeDir)

```
```
 WARNING Statement ../node_modules/markdown-it-editor/lib/css/iconfont.b300b13.woff.js" has f
ailed to resolve in module "default"
```

**Comment by TombolaShepless** [comment]
@Jack85 Is this in the repo you linked to before?

**Comment by Jack85** [comment]
repo I linked js seems to work, but you ll find styles problem I mentioned there.. bigger one im investigating, but its hard when fuse doesnt write log why it rendered commented?

**Comment by Jack85** [comment]
sorry comment was my fault in inx.html. Js part seems to work, styles seems to be completely broken.

**Comment by nchanged** [comment]
@Jack85 
```
 @import url("./../node_modules/bootstrap/dist/css/bootstrap.min.css");
```
is invalid, you can't access node_modules like that in FuseBox.

Use instead ->

```
@import url("bootstrap/dist/css/bootstrap.min.css");
```

**Comment by Jack85** [comment]
sorry even if i put like you suggest - not loaded. 
I believe relative references should be handled
http://lesscss.org/features/#import-directives-feature

**Comment by nchanged** [comment]
Oh sorry that less, then you need to add paths parameter to the resolver (check less options)

**Comment by Jack85** [comment]
official example:
@import "foo.css";  // statement left in place, as-is  
Not working
another official example 
@import (css) "foo.less";
Not working

 @import (css) "./../node_modules/bootstrap/dist/css/bootstrap.min.css";
this guys works

should I teach you LESS or you guys ll be so kind and implement it hassle free?

**Comment by nchanged** [comment]
@Jack85 are you sure you are using the latest beta?

**Comment by Jack85** [comment]
2.3.4-beta.11

**Comment by Shepless** [comment]
@Jack85 It appear you aren't using LESS imports correctly (at least from my understanding). If you are importing CSS inside a LESS then it is left as-is, from the docs:

> @import "foo.css";  // statement left in place, as-is

Since it is left in place, that means the LESS compiler does not change the source code. Therefore this ends up as is a standard CSS import for a file that does not exist (since you are not copying the css files into your output directory when bundled). So as far as I can see you have two options:

1) Copy the CSS files you want into your output directory (with full path, e.g. `output/node_modules/bootstrap/dist/css/bootstrap.min.css`, or;
2) Use the correct LESS syntax to import CSS and have the LESS compiler compile it: `@import (less) "node_modules/bootstrap/dist/css/bootstrap.min.css";`

Its not FuseBoxes duty to handle LESS or SCSS imports - that is the job of LESS and SCSS. I have pulled your repo and made the `@import (less)` change and it works with no issues. Let me know if you have anymore problems.

**Comment by Jack85** [comment]
If I use webpack less loader it works..  
But doc says its left as is.. you might be right. Its kind of weird to mark css file to process as `(less)`
I would expect alteast `(css) `to do it, but they mark it also like left as is.

**Comment by Shepless** [comment]
@Jack85 Webpack (IMO) is overstepping its duties in this instance - LESS and SCSS have their own import features that work perfectly fine and so shouldn't really be managed by a bundler. Other peoples opinions differ on that subject, but ours is the opposite to Webpacks.

In regards to the CSS file not being LESS compatible that is not possible (as LESS is an extension of the CSS language) so it will be safe to import CSS as LESS for sure.

I guess it depends on how you intend to use those node_modules styles. I noticed in your repo that the `<style>` block is not set to be scoped (i.e. they will be applied globally) to any markup that uses it. If that is your goal then you could import the styles at your app entry point and handle them with the `CSSPlugin`. For example:

```js
// app.ts
import 'bootstrap/dist/css/bootstrap.min.css';

// fuse.js
plugins: [
   CSSPlugin({
      group: 'app.css'
   })
]
```

In this case you wouldn't need to import them in your `app.vue` component at all.

**Comment by Jack85** [comment]
In this case itend to have global styles in app, other onw could be scoped. 
I think in this case it should be part of vendor css.. 
And woff import?

**Comment by Shepless** [comment]
Sorry @Jack85 I missed that part - I updated my previous comment 😄

**Comment by TombolaShepless** [comment]
@Jack85 is it ok to close this issue now? I feel we have fixed the original issue with TypeScript?

**Comment by Jack85** [comment]
I think so, thanks guys.
