### ISSUE TITLE
Fusebox doesn't work since node 6.4.0 ~ 7.4.0

### ISSUE THREAD

**Issue by unlight** [fuse-box/fuse-box#86]
I got working on node v6.3.1, when I switching to 6.4.0+
Bundle result is `app.js` size 5.1k (empty)

**Comment by devmondo** [comment]
@unlight did you try to delete fuse cache folder ?
also could you post your config ?

**Comment by unlight** [comment]
>  did you try to delete fuse cache folder ?

Yes. I've tried.

> also could you post your config ?

Config starts here:
https://github.com/unlight/angular2-blank-project/blob/fuse-box/gulpfile.js#L17
Repo:
https://github.com/unlight/angular2-blank-project/tree/fuse-box

**Comment by devmondo** [comment]
if you enable log option, do you get any meaningful error messages ?

**Comment by unlight** [comment]
https://github.com/fuse-box/angular2-example - same issue

**Comment by unlight** [comment]
With log enabled:
```
[16:05:56] Starting 'build'...
└── default (0 files,  53 Bytes)

    --------------
    Size: 53 Bytes
    Time: 658ms
    --------------
```

**Comment by nchanged** [comment]
All tests work with the latest node 6

**Comment by nchanged** [comment]
I mean on Travis :) I will check it later

**Comment by devmondo** [comment]
are we sure it is not gulp issue ?
if you use builtint watch of fuse like this ` fuseBox().bundle(">main.ts",true)` does it work ?

**Comment by unlight** [comment]
I'm going to close this. Looks like some kind environment issue, because at my home machine with node 7.4.0 everything is works fine.
