### ISSUE TITLE
[Feature] CLI parsing

### ISSUE THREAD

**Issue by freehuntx** [fuse-box/fuse-box#866]
First of all, i really like fusebox :D 
I missed an way for proper options parsing.
Therefore i wrote an module called "fuse-box-cli" (https://github.com/freehuntx/fuse-box-cli)

Are you interested in adding an feature like this to fusebox?
(Show help, List tasks, list options, access options)

**Comment by devmondo** [comment]
@freehuntx great work man, could you please change the intro in the repo
`Fusebox is a nice piece of software, i really like it! But sadly there is no easy way for providing options.
For this reason i created this module.`

the `But sadly there is no easy way for providing options.` will confuse people and think that fuse has no options what so ever :)

**Comment by freehuntx** [comment]
Ok, sorry ^^

**Comment by nchanged** [comment]
Awesome @freehuntx do you feel like making a PR? I like the functionality

**Comment by freehuntx** [comment]
Im glad there is interest for it!
I will do that in near future :)

**Comment by freehuntx** [comment]
Feature is added with this commit: https://github.com/fuse-box/fuse-box/commit/fcd30fb39b9f4c31c1fca7cfade17f020e072794
#Closed
