### ISSUE TITLE
Workers without Quantum

### ISSUE THREAD

**Issue by dakom** [fuse-box/fuse-box#869]
As it is right now, workers require quantum, and quantum does not support source maps. So it is _really_ hard to debug workers in the current fuse-box.

As an alternative to issue #868 - a fix could be to allow Workers without Quantum.

For the particular use-case of debugging workers, there's no specific preference which of the above is fixed first, though I'd say it's relatively high priority to fix one of them since as it is right now, there is no way to debug workers at all.

**Comment by nchanged** [comment]
`2.3.4-beta.10` supports Workers with VanillaAPI (sourcemaps and all in place), give it a spin https://github.com/fuse-box/fuse-box-examples/tree/master/examples/webworker

**Comment by dakom** [comment]
woohoo! will try it out tomorrow!!

**Comment by nchanged** [comment]
@dakom no worries, maybe you could report some of the issues with WebWorker and `global`
