### ISSUE TITLE
Enable loading remote files on the server

### ISSUE THREAD

**Issue by leon-andria** [fuse-box/fuse-box#871]
Below is the line that silently resolve nothing on the server:
https://github.com/fuse-box/fuse-box/blob/master/modules/fuse-box-responsive-api/index.js#L116.

I locally tested the below code by adding it to https://github.com/fuse-box/fuse-box/blob/master/modules/fuse-box-responsive-api/index.js#L116.
```javascript
/* @if server */                
        return new Promise(function(resolve, reject) {        
            var http = require("http");
            var uri = require("url");        
            const srvUrl = uri.parse(url);        
            http.get({
                protocol: srvUrl.protocol,
                hostname: srvUrl.hostname,
                port: srvUrl.port,
                path: srvUrl.path
            }, function(resp){
                resp.on('data', function(chunk){                
                    resolve(evaluateModule(url, chunk.toString(), "javascript"));
                });
            }).on("error", function(e){            
                reject(e.message);
            });
        });               
        /* @end */
```
In addition, we need to modify the line below https://github.com/fuse-box/fuse-box/blob/master/modules/fuse-box-responsive-api/index.js#L272 with:

```javascript
/* @if server */
                    var t = loadRemoteScript(id, isCSS);                    
                    return resolve(t);
                    /* @end */

                    /* @if browser */
                    return loadRemoteScript(id, isCSS);
                    /* @end */
```

And I was able to successfully load the remote file.

However, I was not able to implement the auto-detection the file type. As you see above on the evaluate function, the 3rd parameter is hard-coded to javascript.
Now we know how to fix it, could you please implement the correct solution as I could not move any further.

My biggest problem now is that my project is on hold because it has an isomorphic code that should work on the server and the client. And the problem above is blocking me.

Please fix this as it will block any projects that use isomorphic code. (And can't wait any more :-))

Thank you

**Comment by nchanged** [comment]
And what if it's `https`?

**Comment by nchanged** [comment]
I think we should use this lib instead https://github.com/request/request

**Comment by leon-andria** [comment]
```
protocol: srvUrl.protocol,
```
This is enough and avoid any extra deps. Request is so huge. Http is built-in on nodejs

**Comment by nchanged** [comment]
why did you close this one?
