### ISSUE TITLE
Browser error from a 3rd-party module after updating fuse-box version

### ISSUE THREAD

**Issue by kristerkari** [fuse-box/fuse-box#872]
**console error since version:** v2.2.31+
**no error for version:** v2.2.2

When updating from fuse-box *v2.2.2* to *v2.3.3*, I get this error printed to the browser console: `./lib/locales does not provide a module`. This error is not printed if I use version *v2.2.2*. 

I searched for the code in my project and the error comes from both `inlt-relativeformat` and `intl-messageformat` modules. I'm using `react-intl` package in my project which depends on the other intl packages.

`intl-messageformat/index.js`:

```js
/* jshint node:true */

'use strict';

var IntlMessageFormat = require('./lib/main')['default'];

// Add all locale data to `IntlMessageFormat`. This module will be ignored when
// bundling for the browser with Browserify/Webpack.
require('./lib/locales');

// Re-export `IntlMessageFormat` as the CommonJS default exports with all the
// locale data registered, and with English set as the default locale. Define
// the `default` prop for use with other compiled ES6 Modules.
exports = module.exports = IntlMessageFormat;
exports['default'] = exports;
```

As you can see, that code is supposed to be removed by browserify/webpack, but does not get removed by fuse-box.

I tested older fuse-box versions, and it seems that the error has been printed since `v2.2.31`. 

@nchanged

**Comment by nchanged** [comment]
so what is it you don't like? the error?

**Comment by kristerkari** [comment]
Yeah, I don't like errors in my production bundle :) But the real question is that can I get fuse-box to work the same way as webpack where that `require` would get ignored when bundling?

**Comment by kristerkari** [comment]
and to clarify: I'm using fuse-box to create a bundle for the browser.

**Comment by kristerkari** [comment]
Another thing that would be good to know is that why did the error appear when I updated fuse-box version? Was it there before but just not printed to console? 

When I look at the bundle using fuse-box v2.2.2, I see that at least the `require` is inside vendor.js:
```
require('./lib/locales');
```

**Comment by nchanged** [comment]
There was a request to log all unresolved modules, and yes fusebox still ignores it, don’t worry

**Comment by kristerkari** [comment]
@nchanged good to know, is there a way to get rid of the `console.error` that it causes?

**Comment by nchanged** [comment]
@kristerkari warnings: false

**Comment by kristerkari** [comment]
hmm... that does not work, the error still gets printed

**Comment by kristerkari** [comment]
@nchanged I just had a look at the code where the error gets printed. It's in the loader api, so `warnings: false` does not affect it:
https://github.com/fuse-box/fuse-box/blob/master/modules/fuse-box-loader-api/fusebox.js#L185-L187

Would there be an easy way to add support for silencing that console.error? I'd need update to a newer version of fuse-box, but this issue is currently blocking me from doing it.

**Comment by nchanged** [comment]
Ah, now I get it, it's at runtime. I will look into it but please, be patient.

**Comment by kristerkari** [comment]
thanks! I can also help if needed, but I'm not familiar enough with the code to figure out by myself.

**Comment by nchanged** [comment]
Btw, that's a development API.
Oh yeah, I don't think we need to modify anything.... Are you familiar with Quantum? It has a micro API, and no logging is there. Production ready. Give it a try

**Comment by kristerkari** [comment]
Oh that's for development only? 

I tried Quantum, but unfortunately I could not get it to work in our project. I tried different combinations of quantum options but nothing worked. 

I guess that there is something somewhere inside the project that is not compatible with Quantum.

**Comment by nchanged** [comment]
@kristerkari no only, of course you use it. Quantum just make super small and runtime optimised

**Comment by nchanged** [comment]
@kristerkari anything is compatible with Quantum except for Aurelia ;-) join gitter we will help you set it up

**Comment by nchanged** [comment]
I will close it for now, feel free to re-open
