### ISSUE TITLE
cannot parse tsconfig.json generated by tsc --init

### ISSUE THREAD

**Issue by kasugaiasuka** [fuse-box/fuse-box#873]
tsc --init generates tsconfig.json, but this is not plain JSON (containing some comments)
and causes syntax error until the comments is removed from tsconfig.

I think this is correct, but not typescript-friendly.

```bash
$ tsc --init
message TS6071: Sucessfuly created a tsconfig.json file.
$ node fuse.js (<- Ctrl+C & Ctrl+V from "Getting started")
--- FuseBox 2.3.3 ---
→Typescript config:  /tsconfig.json
SyntaxError: /home/foo/temp/tsconfig.json: Unexpected token / in JSON at position 29
    at JSON.parse (<anonymous>)
    at ...
```

edited: typo

**Comment by nchanged** [comment]
Thanks, that's a known issue

**Comment by kswope** [comment]
> FuseBox loves typescript, and does not require any additional configuration.

**Comment by cjdell** [comment]
@kasugaiasuka My PR might fix your issue. https://github.com/fuse-box/fuse-box/pull/1129
