### ISSUE TITLE
import() with code splitting

### ISSUE THREAD

**Issue by leon-andria** [fuse-box/fuse-box#875]
config:
```javascript
.split("routes/about/**", "about > routes/about/AboutComponent.ts")
```
code:
```javascript
const aboutModule = await import("./routes/about/AboutComponent");
```
This code works perfectly until that we start to use Quantum with target as "server:
config:
```javascript
.splitConfig({ browser: "../thisisbrowser/", server: "../",  dest: "bundles/" })   
```
code:
```
plugins: [
            HTMLPlugin({default: true}),
            WebIndexPlugin(),
            isProduction && QuantumPlugin({
                uglify: false,
                bakeApiIntoBundle: "server/server",
                target: "server"
            }),
        ]
```

With Quantum, the code below doesn't work anymore:
```javascript
const aboutModule = await import("./routes/about/AboutComponent");
```
The only code valid is using "about" specified in the split.

So what is the "Best Practices", the key "about" or the "path" ? As we should not adapt our code regarding if we go to production or not.

Also, nothing is mentioned int he doc that splitconfig is linked to Quantum.

**Comment by nchanged** [comment]
https://github.com/fuse-box/fuse-box-examples/tree/master/examples/code-splitting
Works perfectly on server, you have an error somewhere. See the example above

**Comment by leon-andria** [comment]
I see the error, the path in the import should not be to fuse "homeDir".
You agree with me that splitConfig is strongly mapped with Quantum ? And this need to be specify in the Doc!
