### ISSUE TITLE
Bad sourcemaps with angular+electron

### ISSUE THREAD

**Issue by tao-cumplido** [fuse-box/fuse-box#877]
Hi,

I switched from webpack to fuse-box and everything works fine except for the sourcemaps.
I combined the angular and electron seeds available for this and I didn't encounter this issue in either of them, so maybe it's also something with my configuration.

I have a boilerplate repository for this:
https://github.com/tao-cumplido/electron-angular-boilerplate

The actual problem I am having is that in the renderer the console.log from app.component.ts is marked as line 3 even though it actually is line 10.

If you spot any problem with my fuse.js please let me know. :)

**Comment by Shepless** [comment]
@tao-cumplido thanks for raising the issue. Sourcemaps are a tricky beast! I've taken a quick look at your fuse.js file and nothing looks wrong to me. We will look into it and get back to you.

**Comment by nchanged** [comment]
@tao-cumplido hi!
I think I know what's causing it
This plugin https://github.com/tao-cumplido/electron-angular-boilerplate/blob/master/fuse.js#L53

It re-renders the code without fixing the sourcemaps, could you try removing it? That's a 3rd party library, I really like it, it's very well coded, but ...

**Comment by tao-cumplido** [comment]
@nchanged 
right, I kinda forgot about the plugin, it seems indeed to be the culprit.
I removed it and changed `templateUrl` and `styleUrls` to `template` and `styles` with require statements instead and the sourcemaps work fine. :)
I will go this way for now and raise the issue on ng2-fused.
Thanks for the help.
