### ISSUE TITLE
Code split first parameter matching

### ISSUE THREAD

**Issue by leon-andria** [fuse-box/fuse-box#880]
To make a full match with filename (server/products.ts), this doesnt work, we need to put products.js
The doc said that it matches files from the source where you have *.ts files.
Either it's a bug or the doc needs to be updated.

**Comment by nchanged** [comment]
You can't require with `ts` extension, that's how typescript works man, fusebox has nothing to do with it!

**Comment by leon-andria** [comment]
As far as i see here, http://fuse-box.org/page/code-splitting#first-argument-path-matching, the break down logic shows clearly that we compare with .ts file. Do i misunderstand it?
Trust me that everyone dont think to put a js file from his source file.

**Comment by nchanged** [comment]
It has to be explicit
it's all working

https://github.com/fuse-box/fuse-box-examples/blob/c46115ccb94719c117ef8d425eac7e7571549b0a/examples/code-splitting/fuse.js#L25-L28

**Comment by leon-andria** [comment]
I know this work but this is not my use. I dont have a folder about nor home.
I want to split my home.ts, products.ts, about.ts.
So, these files are under server folder and i want to do code splitting.
To do so,
.split("×××", ...)
What you specify on xxx to get home.js, products.js, ...?
I'm curious to see your answer based on the link i share above.

**Comment by nchanged** [comment]
Because it's an entry point!

**Comment by leon-andria** [comment]
You are not answering my question, what should be the value on xxx?
Tell me that an entry point doesnt help me to understand nor only me but everyone who will read the documentation. And, on the doc, there is nothing about entry point about the first parameter meaning.

**Comment by nchanged** [comment]
![screenshot 2017-10-18 22 16 40](https://user-images.githubusercontent.com/1629088/31740582-1504dba2-b452-11e7-8c3a-d268f1edebc4.png)

**Comment by leon-andria** [comment]
This is not right that you close this issue without giving the right support and answer. You are not even trying to understand the use-case that I'm pointing out:
```js
.split("server/products.ts", "products > server/products.ts")
```
I want to have a "Full matching" filename and the code above doesn't work. After debugging, I notice that the right code should be follow:
```js
.split("server/products.js", "products > server/products.ts")
```
You can ignore my issue but the documentation is WRONG and I'm confident to say that. People are not using ** and you cannot force everyone to create a sub-folder.

**Comment by nchanged** [comment]
Then you should explain better, I don't understand you!

**Comment by leon-andria** [comment]
Pay attention on the comment on this commit yesterday: https://github.com/fuse-box/fuse-box/commit/c67cffe0555e3e1e2f064aef98303e8d14f90c42

> The issue was being caused by a mismatch of the fuseBoxPath stored in cache and the lastChangedFile
when using typescript as the .ts extension gets normalised to .js

I'm pretty sure this is related to my highlight above with the first parameter of the split method, it requires a "dot js" extension rather than a "dot ts" extension to match the splitting rule.

**Comment by nchanged** [comment]
I might have just understood the issue, I will check if it’s being filtered through ensure public extension function

**Comment by leon-andria** [comment]
If my input can help, for me, we need to update the documentation, and i can do that. For me, this is not a BUG, it's a normal behavior. The truth is on the code and the starting point for this is PackageAbstraction.ts where FileAbstraction is created based on the filename. And the filename is already with ".js" extension because it's already transpiled by Typescript. That's being said, the filename here is used to match the code split rule.

If you agree, i do a PR on the documentation.
