### ISSUE TITLE
Allow WebIndexPlugin to take template data also

### ISSUE THREAD

**Issue by pyros2097** [fuse-box/fuse-box#885]
I reckon most of my projects to use the same index.html code. So would it be possible to provide the template inline instead of passing a file path to it. Will make it easier related to configuration since now I can also use string templates to inject keys for production and also this will remove the need for a single index.html file in my folder structure. Just an idea.
```html
<!DOCTYPE html>
<html>

<head>
  <title></title>
</head>

<style>
  body {
    margin: 0;
    padding: 0;
    font-family: sans-serif;
  }
</style>

<body>
  <div id="root"></div>
  $bundles
</body>

</html>
```

**Comment by nchanged** [comment]
thanks @Shepless for implementing it so quick! You rock 🔥
