### ISSUE TITLE
Quantum and negative comparisons

### ISSUE THREAD

**Issue by eddow** [fuse-box/fuse-box#888]
As written in the documentation, 
```js
if ( process.env.NODE_ENV === "production" ){
    console.log("production")
} else {
    console.log("development")
}
```
will be "quantumed" into 
```js
console.log("production")
```

When using quantum along with `VueComponentPlugin`, [this code](https://github.com/fuse-box/fuse-box/blob/2792c1dacfc9719ba9bd0420ba1cb1512955db70/src/plugins/vue/VuePlugin.ts#L259) will come to be processed by quantum :
```js
        if (process.env.NODE_ENV !== "production") {
          var api = require('vue-hot-reload-api');

          process.env.vueHMR = process.env.vueHMR || {};

          if (!process.env.vueHMR['${scopeId}']) {
            process.env.vueHMR['${scopeId}'] = true;
            api.createRecord('${scopeId}', module.exports.default);
          }
        }
```
The whole `if` block is supposed to be eliminated (as `process.env.NODE_ENV` **is** `"production"`) but it stays and produce quite a problematic code :
```js
var api = require('vue-hot-reload-api');
undefined = undefined || {};
if (!undefined['null']) {
    undefined['null'] = true;
    api.createRecord('null', module.exports.default);
}
```

Note: The hack consisting in using `replaceProcessEnv: false` doesn't have any effect

**Comment by nchanged** [comment]
Oh that’s a bug, thank you! We will take a look

**Comment by Shepless** [comment]
@nchanged just to confirm - this is not an issue with `VueComponentPlugin`?

**Comment by nchanged** [comment]
@Shepless as an immediate solution you could change the block
```
if ( process.env.NODE_ENV === "production" ){
```

And i will take a look a bit later

**Comment by Shepless** [comment]
@nchanged rather than inverting the check (as it would make the logic a bit weird). Would `Quantum` work with:

```js
if (process.env.NODE_ENV === 'development') {}
```

**Comment by nchanged** [comment]
@Shepless yeah it should

**Comment by nchanged** [comment]
@eddow can you reproduce it please? 
https://github.com/fuse-box/fuse-box-vue-seed <-- all works here.
Besides, 
https://github.com/fuse-box/fuse-box/blob/8aa91f80d25d27011613ad75c184ac45add1d9f1/src/quantum/tests/ProcessEnvDeadCode.test.ts#L6-L31

**Comment by Shepless** [comment]
@eddow are you still facing this issue?

**Comment by eddow** [comment]
Hi, sorry, I am a bit unavailable nowadays, I will come back to you as these topics are starred but I cannot promise when.

**Comment by Shepless** [comment]
Closing for now. Feel free to reopen if you still think this is an issue.
