### ISSUE TITLE
Quantum and `FuseBox.global` (`__fsbx_decorate` is not defined)

### ISSUE THREAD

**Issue by eddow** [fuse-box/fuse-box#889]
Fuse-box will use globals like `__fsbx_decorate` that it will define like this:
```js
FuseBox.global("__fsbx_decorate", function(localArguments) {...
```

When the module is processed by quantum, these declarations are eliminated (I suppose because the variable name, like `__fsbx_decorate` is given as a string so it is considered as data, not a variable name?)

Finally, the module processed by quantum will therefore raise a `ReferenceError: __fsbx_decorate is not defined` exception.

Note: In my case, this happens when compiling an `"npm"` module, the bug will happen in the project using the quantum-ed module.

Note: the quantum options are: 
```
			{
				bakeApiIntoBundle : 'myModule',
				containedAPI : true,
				globalRequire: false,
				target: 'npm'
			}
```

**Comment by nchanged** [comment]
It’s deprecated, please use tslib.

**Comment by eddow** [comment]
Well, I added ts-lib in my sources (with `.instructions('... +ts-lib')`) but it seems this is not enough, this is still in the code :
```js
var __decorate = __fsbx_decorate(arguments);
```
and `__fsbx_decorate` is still not defined.

Should I use another option to force the use of ts-lib instead of `__fsbx_` functions?

**Comment by nchanged** [comment]
Remove that plugin install tslib modify your ts config (please google tslib)

**Comment by Shepless** [comment]
@eddow You need to update (or add) your `tsconfig.json` to include the following:

```json
{
    "compilerOptions": {
        "importHelpers": true
    }
}
```

With that you should not need `.instructions('... +ts-lib')` (also remember to remove `TypeScriptHelpers` plugin from your config.

**Comment by eddow** [comment]
Ah ok - found it, it was the plugin `TypeScriptHelper` that I had to remove - everything in order now - thx!
