### ISSUE TITLE
Flash of unstyled content

### ISSUE THREAD

**Issue by phamtm** [fuse-box/fuse-box#891]
First of all thank you for making this great tool. The compilation speed `fuse-box` is near instant for me. 

I notice that during my web application starts there's a visible flash of un-styled content, which I assume is the result of loading CSS dynamically hence JavaScripts can be executed before CSS is parsed.
Is this an intentional trade off? And are there any option to opt out of dynamic CSS loading. Thank you very much!

**Comment by nchanged** [comment]
@phamtm thanks for the kind words!
It's a normal practice for development, if you want your CSS loaded along with everything else, you need to use `outFile` option with `inject:false` and `group` of course, if you have multiple files. Then include the generated files in the HEAD.

More here:
http://fuse-box.org/plugins/css-plugin

**Comment by phamtm** [comment]
@nchanged Thank you, it works well for me.
