### ISSUE TITLE
Running sparky task on watch

### ISSUE THREAD

**Issue by amygdaloideum** [fuse-box/fuse-box#894]
Is it possible to run a sparky task from a watch?

For example, I have a task that generates a $templateCache for angular that I want to run every time a `'src/**/*.view.html'` file changes.

I'm imagining something along the lines of:
```js
Sparky.watch("src/**/*.view.html").task('templates');
```

Or is there another way to achieve the same behavior?

**Comment by devmondo** [comment]
@amygdaloideum  you can use fuse file api to achieve any custom code you want.
http://fuse-box.org/page/sparky#file-api

**Comment by CzBuCHi** [comment]
@devmondo I know, that this is necromancy but your answer is not technically aswer to OPs question ....

Lets say, i have this code in `fuse.ts` (called via `ts-node`, but that not important):
```ts
import { Sparky } from "fuse-box";

Sparky.task("default", () => {
  Sparky.watch(pattern).file(pattern, () => {
    // how to call "otherTask" task from here?
  });
});

Sparky.task("otherTask", () => {
   ...
});
```

currently only way i can think of is to move all code from "otherTask" into function and call that from both places, but i would prefer simply call "otherTask" directly ...

**Comment by devmondo** [comment]
@CzBuCHi you exactly did what i tried to suggest, sparky has `exec` api method, see below your example where i added that, hope it helps :)

```js
import { Sparky } from "fuse-box";
import {exec} from "fuse-box/sparky";

Sparky.task("default", () => {
  Sparky.watch(pattern).file(pattern, () => {
    // how to call "otherTask" task from here?
    exec("otherTask")
  });
});

Sparky.task("otherTask", () => {
   ...
});
```
