### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by fknop** [fuse-box/fuse-box#90]
I just had an issue:

![image](https://cloud.githubusercontent.com/assets/6775689/21957723/b12999ee-da9d-11e6-88ea-5f8e8ed50d00.png)

After reading the error, it looked like an issue with the cache so I deleted the .fusebox folder and it worked fine.

**Comment by nchanged** [comment]
Thanks, i will look into that

**Comment by nchanged** [comment]
supposedly fixed in `1.3.52`
