### ISSUE TITLE
HRM doesn't work with preact

### ISSUE THREAD

**Issue by pedronauck** [fuse-box/fuse-box#901]
I don't know why and I try a lot of ways to make a hrm workaround, but every time that hrm reload the preact render a new instance at the dom. I think that is a huge issue, because it was a big ascension now and was a pretty good idea use it with fuse-box.

Any some ideas how to fix that? He're a example:
https://github.com/xyyjk/fusebox-preact-example

maybe @developit can be help us here 🙏

**Comment by nchanged** [comment]
@pedronauck HMR in FuseBox is pretty simple, once a module is updated it triggers an entry point. For example, it works perfectly with react, cuz react is smart enough to destroy the existing element (or re-init) I guess preact should work the same way.

**Comment by pedronauck** [comment]
Of course @nchanged, I tried to do the same with Inferno and React and both working perfectly with hrm, unfortunelly preact didn't so smart than that 😢

**Comment by Shepless** [comment]
@pedronauck can you provide a link to a repo please so we can take a look into it?

**Comment by pedronauck** [comment]
Of course @Shepless https://github.com/pedronauck/fusebox-preact-example

**Comment by nchanged** [comment]
@pedronauck based on the referenced issue can we close this one now?

**Comment by pedronauck** [comment]
Yeah, I think it's a preact render's bug not fuse-box... thanks @nchanged

**Comment by nchanged** [comment]
@pedronauck no problem, closing this for now
