### ISSUE TITLE
Error loading lib via worker

### ISSUE THREAD

**Issue by dakom** [fuse-box/fuse-box#903]
When both the lib and worker and parent app are all built via fuse-box I get an error

Lib config is like:

```
QuantumPlugin({
    removeUseStrict: false,
    globalRequire: false,
    containedAPI: true,
    bakeApiIntoBundle: bundleName,
    treeshake: true,
    uglify: true,
    target: "npm"
})

package: packageName;
globals: { packageName: globalsName };

target: "browser",
useTypescriptCompiler : true
```

Worker config is like:

```
QuantumPlugin({
  removeUseStrict: false
  containedAPI: true,
  bakeApiIntoBundle: workerName,
  uglify: true,
  treeshake: true,
  target: "server"
})
target: "browser"
```

Although they're constantly changing so these can't be relied upon for testing, there are live projects that exhibit this [here](https://github.com/dakom/frpong) (app+worker) and [here](https://github.com/dakom/fl-matrix) (lib)

**Comment by nchanged** [comment]
@dakom so how can I reproduce the issue? do you have something simple?

**Comment by dakom** [comment]
My mistake - it was a bug on my side and I misread the error, sorry!
