### ISSUE TITLE
fuse-heresy-default not working properly with HMR

### ISSUE THREAD

**Issue by freehuntx** [fuse-box/fuse-box#906]
If i use polyfillNonStandardDefaultUsage, and have HMR active, first everything works.
But if i then add a new import and the file gets reloaded by HMR, the polyfill is not applying for this import.

Do i make something wrong or is this a bug?
My config is:

```
{
  homeDir: 'src',
  output: '.dist/$name.js',
  cache: !options.prod,
  sourceMaps: !options.prod,
  polyfillNonStandardDefaultUsage: true,
  plugins: [
    [
      CSSResourcePlugin({ inline: true }),
      CSSPlugin()
    ],
    WebIndexPlugin({
      title: 'Nice electron app',
      path: '.',
      template: 'src/app/index.html'
    }),
    options.prod && UglifyESPlugin()
  ]
}
```

**Comment by nchanged** [comment]
From documentation:

> This functionality will not work in your project (people should stop relying on it, it's limited by design), but it's targeted to dependencies where useJsNext is interconnected.

Please, consider conforming to javascript standards. 

As for the issue, I will take a look

**Comment by freehuntx** [comment]
I somehow like the comfort of this polyfill :/
```
import React, { Component } from 'react'
```
simply looks better than
```
import * as React from 'react'
import { Component } from 'react'
```

**Comment by nchanged** [comment]
how about
```
import * as React from 'react'

export HelloComponent extends React.Component {
}

```

**Comment by freehuntx** [comment]
Could do this as an workaround :/

**Comment by freehuntx** [comment]
I'll look today into it and give you feedback.

**Comment by nchanged** [comment]
@freehuntx please upgrade to the latest beta and toggle 
https://fuse-box.org/page/configuration#allowsyntheticdefaultimports
`polyfillNonStandardDefaultUsage` has been depreacted

**Comment by freehuntx** [comment]
Its working now.
