### ISSUE TITLE
React import LESSPlugin

### ISSUE THREAD

**Issue by Gouigouix** [fuse-box/fuse-box#911]
hello,

I use LESSPlugin into a project and the build working well
It's a React project with some tsx components
I testing to import "style.less" into each components, but only the first is display into <head> !

You can test with this example : `https://github.com/orchestra-ts/fuse-box-examples/tree/master/examples/react-typescript-less`

Thank you

**Comment by nchanged** [comment]
Hi
https://github.com/orchestra-ts/fuse-box-examples/blob/7c0432c6727b0e2385d539a377aab78e8c11877f/examples/react-typescript-less/src/components/footer/index.tsx#L3

That is incorrect^^
Should be 
```
import "./styles.less"
```

Same here (and everywhere else) https://github.com/orchestra-ts/fuse-box-examples/blob/master/examples/react-typescript-less/src/components/layout/index.tsx#L6

**Comment by Gouigouix** [comment]
Oh my god,

I was really tired! After 5 days of vacation and fixes everything works ...
Are you interested in a pull-request example (corrected)?

Thank you.

**Comment by nchanged** [comment]
@Gouigouix absolutely!

**Comment by Gouigouix** [comment]
@nchanged The pull request is: https://github.com/fuse-box/fuse-box-examples/pull/17

Thx

**Comment by nchanged** [comment]
Thanks!
