### ISSUE TITLE
Quantum tree shaking variables that are being used

### ISSUE THREAD

**Issue by mattoni** [fuse-box/fuse-box#912]
I have a separate UI package I maintain which i import and use in my main project. A couple variables are being tree-shook that I'm using and it's breaking my builds.

In my UI package I have the following:
```
export const zIndexLayers = {
    bottom: 0,
    middle: 1,
    top: 2,
    max: 3,
};

export const BorderColor = {
    AccentWhite: rgb(250, 250, 252),
};
```

which are then grouped together in the root index file and re-exported like so:

```
import * as Theme from "./theme";
export { Theme, Utils, DataTables, StatefulForms, Forms, Text ...};
```

In my main app, I'm using the BorderColor/zIndexLayers in a split bundle:
```
import {
    Theme,
} from "@cycleplatform/cycle-ui";

const Styles = {
    subpanel: style({
        backgroundColor: `${Theme.BrandColor.AccentWhite}`,
        border: `1px solid ${Theme.BorderColor.AccentWhite}`,
        textAlign: "center",
    }),
};

later on...

...
<PanelBody className={Styles.subpanel}>
...
```

When running a quantum build, I find the following:

```
 → tree shaking: Remove FontWeight from @cycleplatform/cycle-ui/dist/font.js
  → tree shaking: Remove ColorHelper from @cycleplatform/cycle-ui/dist/theme.js
  → tree shaking: Remove Transparency from @cycleplatform/cycle-ui/dist/theme.js
  → tree shaking: Remove BorderColor from @cycleplatform/cycle-ui/dist/theme.js
  → tree shaking: Remove zIndexLayers from @cycleplatform/cycle-ui/dist/theme.js
```

and running the build fails because it can't find that function.

Most of these things are in use, so I'm not sure why they would be removed. This is a critical issue in me getting a production build out so hopefully we can figure this out quickly.

edit: I'm on v2.4.0

**Comment by nchanged** [comment]
![screenshot 2017-11-14 16 49 04](https://user-images.githubusercontent.com/1629088/32789305-c7642c12-c95b-11e7-9393-09e1c28297db.png)

I cannot reproduce the issue


src/index.ts
```
import * as data from "./utils";
data.a()
```

`src/utils/index.ts`
```
export { a } from "./a"
export { b } from "./b"
```
