### ISSUE TITLE
change order tryTypescriptPlugins with replaceDynamicImports

### ISSUE THREAD

**Issue by zeniroy** [fuse-box/fuse-box#913]
I'm using split and dynamic import feature in production and not in development because i want to use hmr feature in development mode.

And to do so, i have to replace some code for import modules, before replacing dynamic import. Now I'm using "onTypescriptTransform" feature for replacing code, So some order problem on File.ts,

```typescript
private handleTypescript() {
        ...
        this.replaceDynamicImports(); 
        this.tryTypescriptPlugins();
        ...
}
```

So, i think it's better that there is replaceDynamicImports step after tryTypescriptPlugins step.
How about that?

**Comment by nchanged** [comment]
@zeniroy don't really get 
> I'm using split and dynamic import feature in production and not in development because i want to use hmr feature in development mode.

Imports and the actual splitting happens only in production, in development your bundle is not split and totally working with HMR. Try that one:

https://github.com/fuse-box/fuse-box-examples/tree/master/examples/react-code-splitting

**Comment by zeniroy** [comment]
Oh, you are right. That's awesome!
