### ISSUE TITLE
throwContainedAPIError when using split 

### ISSUE THREAD

**Issue by zeniroy** [fuse-box/fuse-box#914]
I'm using Code splitting for building some kind of browser library.
And i want to use containedAPI for avoiding collision $fsx in another project.

But throwContainedAPIError is occurred when using containedAPI. That error has message like "Make sure code splitting is not in use".

So, I commented throwContainedAPIError part, but it works perfectly.
I'm not sure that it works in multiple bundle(not split bundle) case, But in my case(only use split bundle) it was ok.

So, how do you think about accepting split bundle with containedAPI?

**Comment by nchanged** [comment]
@zeniroy it can't work with containedAPI, simply because there is no way to share bundle information (bacause it's contained and there is no access to window)

**Comment by nchanged** [comment]
However we could technically create a random variable in window ...

**Comment by zeniroy** [comment]
Split bundle and Dynamic import doesn't need global variable. As far as i know, $fsx.l() has internal ajax request, so dosen't need global variable to import dynamically.

By the way, i think global random variable is also good. I want to choose this option if Using containedAPI with split bundle is not possible. Can you add option for it?

**Comment by zeniroy** [comment]
In my case, the filename which will be dynamically loaded are in "bMapping" variable in main bundle file. If filename will be "83jkk3h33-about.js", bMapping can be modified for it. Am i wrong?

**Comment by nchanged** [comment]
that's right, but then when you load a bundle, we need to store virtual file structure somewhere, need to check how we can implement it. I am not saying it's impossible, just tricky a little bit

**Comment by zeniroy** [comment]
Ok, i got it. So do you have a plan to implement containedAPI with split bundle? Or let user to use global random variable bundling?

**Comment by nchanged** [comment]
we can think about it, it's possible, but it maybe behind a different flag, because in this case it will be no longer be isolated.

**Comment by zeniroy** [comment]
Ok, good. I really need that!

**Comment by nchanged** [comment]
https://github.com/fuse-box/fuse-box/issues/947
