### ISSUE TITLE
When setting custom dev port, the websocket connection fails

### ISSUE THREAD

**Issue by jsamr** [fuse-box/fuse-box#915]
Currently, you have to explicitly set `socketURI` to the right port if you change `port` setting when invoking `fuse.dev`.  [Minimal working example](https://github.com/sveinburne/fuse-box-socketuri-bug)

### Working example (default): 

`port = 4444`

### Working example (custom):

`port = 8880`
`socketURI = 'ws://localhost:8880'`

<details>
<summary>configuration with explicit <code>socketURI</code></summary>
<p>

``` javascript
const { FuseBox, WebIndexPlugin } = require("fuse-box");

const port = 8888
const socketURI = `ws://localhost:${port}`

const fuse = FuseBox.init({
    homeDir: "src",
    output: "dist/$name.js",
    plugins: [
      WebIndexPlugin({
          path: '.'
      })
    ]
});

fuse.bundle("app")
    .instructions(`>index.ts`)
    .watch()
    .hmr({ socketURI });

fuse.dev({
    root: "dist",
    port
})

fuse.run();

```

</p>
</details>

### Failing example (custom):

`port = 8880`

<details>
<summary>configuration with non-explicit <code>socketURI</code></summary>
<p>

``` javascript
const { FuseBox, WebIndexPlugin } = require("fuse-box");

const port = 8888

const fuse = FuseBox.init({
    homeDir: "src",
    output: "dist/$name.js",
    plugins: [
      WebIndexPlugin({
          path: '.'
      })
    ]
});

fuse.bundle("app")
    .instructions(`>index.ts`)
    .watch()
    .hmr();

fuse.dev({
    root: "dist",
    port
})

fuse.run();

```

</p>
</details>

### Comments

In the latest example, the client will try to connect to default socketURI, `ws://localhost:4444` resulting in repeated failed requests.

**Comment by nchanged** [comment]
YOu need to change .hmr(port) too

**Comment by patrickmichalina** [comment]
This doesn't appear to work even when setting via .hmr config

**Comment by nchanged** [comment]
@sveinburne can you paste your fuse.js config please?

**Comment by sveinburne** [comment]
@nchanged Here is a [minimal working example](https://github.com/sveinburne/fuse-box-socketuri-bug).

<details>
<summary>Working configuration (explicit <code>socketURI</code>)</summary>
<p>

``` javascript
const { FuseBox, WebIndexPlugin } = require("fuse-box");

const port = 8888
const socketURI = `ws://localhost:${port}`

const fuse = FuseBox.init({
    homeDir: "src",
    output: "dist/$name.js",
    plugins: [
      WebIndexPlugin({
          path: '.'
      })
    ]
});

fuse.bundle("app")
    .instructions(`>index.ts`)
    .watch()
    .hmr({ socketURI });

fuse.dev({
    root: "dist",
    port
})

fuse.run();

```

</p>
</details>

<details>
<summary>Failing configuration (non-explicit <code>socketURI</code>)</summary>
<p>

``` javascript
const { FuseBox, WebIndexPlugin } = require("fuse-box");

const port = 8888

const fuse = FuseBox.init({
    homeDir: "src",
    output: "dist/$name.js",
    plugins: [
      WebIndexPlugin({
          path: '.'
      })
    ]
});

fuse.bundle("app")
    .instructions(`>index.ts`)
    .watch()
    .hmr();

fuse.dev({
    root: "dist",
    port
})

fuse.run();

```

</p>
</details>

**Comment by nchanged** [comment]
@sveinburne 
That does work for me
```
fuse.bundle("app")
    .instructions(`>index.ts`)
    .watch()
    .hmr({socketURI : `http://localhost:${port}` });
```

**Comment by sveinburne** [comment]
@nchanged precisely, my all post is about `socketURI` should be inferred from `port` instead of set explicitly 🙂

**Comment by nchanged** [comment]
Would you mind taking a look and making a PR? ;-)

**Comment by sveinburne** [comment]
@nchanged OK I'll look at it this week

**Comment by nchanged** [comment]
Closing this for now, feel free to re-open when you have time

**Comment by CapOM** [comment]
This still does not work, please re-open, thx!

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
