### ISSUE TITLE
es6 module in node_modules not transpiled

### ISSUE THREAD

**Issue by guillaume86** [fuse-box/fuse-box#916]
I have a dependency of a dependency (`only-react-css-property-operations` which is required by `react-dom-animated`) which use the `const` es6 feature and it is not getting transpiled to es5 `var` when using the browser target (I also tried browser@es5).

I managed to force the transpilation by using a plugin to set `file.es6module = true` on the appropriate file.

From what I gathered from the source code, only files using es6 imports/exports are currently transpiled:
https://github.com/fuse-box/fuse-box/blob/master/src/analysis/plugins/ImportDeclaration.ts#L28-L46

Edit: to clarify, the module is using es6 syntax features (const), but not the es6 module (import/export) syntax.

**Comment by nchanged** [comment]
@guillaume86 if you are familiar with AST you could try adding const let and other conditions here
https://github.com/fuse-box/fuse-box/blob/master/src/analysis/plugins/LanguageLevel.ts#L4

That's a very simple fix, i don't remember exactly the node name, but it looks something llke this:
```
if( node.kind === "const"){
     file.setLanguageLevel(ScriptTarget.ES2016)
}
```

Do you think you can make a PR?

**Comment by guillaume86** [comment]
Ok I'm going to give it a shot.

**Comment by Shepless** [comment]
@guillaume86 @nchanged can this be closed now the PR has been merged?

**Comment by guillaume86** [comment]
Yes it's solved.

Le dim. 5 nov. 2017 17:31, Chris Shepherd <notifications@github.com> a
écrit :
