### ISSUE TITLE
CSSPlugin ignoring outFile and inject options with SassPlugin

### ISSUE THREAD

**Issue by cryptoquick** [fuse-box/fuse-box#918]
Hi! Great project. However, I have yet to see it successfully produce a css file.

Our configuration is here, please take a look:

https://github.com/influxdata/chronograf/blob/typescript/ui/fuse.js

It's kind of unclean because I've been experimenting with different options, trying to get it to work, to no avail.

Thanks in advance for your help.

**Comment by nchanged** [comment]
HI, I see the problem right away, u need to chain it, use an array [sass, css] I am not at home atm, read up on docs and let us know if they are unclear

**Comment by cryptoquick** [comment]
Thanks for the quick response. I'll give that a try!

**Comment by cryptoquick** [comment]
That worked alright. It took me a bit of work to figure out what's supposed to go into plugin chaining vs init config.

If there's anything else we're doing wrong, or we could do better in our fuse script, please let us know! And also, thanks for the quick response!
