### ISSUE TITLE
No sourceMaps for /src 

### ISSUE THREAD

**Issue by apostololeg** [fuse-box/fuse-box#919]
version `2.4.0` and `2.5.0-beta.1`
reproduce repo https://github.com/apostololeg/fuse-box-vue-sourcemaps

![](http://i.imgur.com/8KkBylr.gif)
`dist/build.map.js`:
```json
{
  "version": 3,
  "sources": [
    "packages/default",
    "packages/fusebox-hot-reload@0.0.0",
    "packages/fuse-heresy-default@0.0.0",
    "packages/fusebox-websocket@0.0.0",
    "packages/events@0.0.0",
    "packages/vue@2.5.3",
    "packages/process@0.0.0",
    "packages/fuse-box-css@0.0.1",
    "packages/vue-hot-reload-api@2.2.0"
  ],
  "names": [],
  "mappings": ";AAAA;AACA;AACA;AACA;AACA;AACA;...",
  "file": ""
}
```
Am I wrong or there is bug in plugin ?

**Comment by Shepless** [comment]
@apostololeg Thanks for raising. I have pulled your repo down and I have updated your `.babelrc` file to include `sourceMaps: true` and that correctly generates source maps:

```js
{
    "sourceMaps": true,
    "presets": [
        ["es2015"],
        ["env", { "modules": false }]
    ],
    "plugins": [
        "syntax-dynamic-import",
        "transform-vue-jsx",
        "transform-decorators-legacy",
        "transform-object-rest-spread"
    ]
}
```

The `BabelPlugin` use the `babelrc` file and ignores options passed in directly. I will put up a PR in a moment to resolve this but i the meantime the above will resolve your issue.

**Comment by Shepless** [comment]
@apostololeg PR is up #920

**Comment by apostololeg** [comment]
oh, dat nice! Thanks, Chris 👍

**Comment by Shepless** [comment]
PR is merged. Going to close this now.
