### ISSUE TITLE
Dev server issues

### ISSUE THREAD

**Issue by unlight** [fuse-box/fuse-box#92]
#### 1. Expose server instance
This need need graceful shutdown and to subscribe on events like `close`, etc.
```
gulp.task('server:dev', (done) => {
    const server = fuseBox.devServer('>main.ts');
    server.on('close', () => done);
});
```
#### 2. Allow to add middlewares
The most used middlewares for dev server are: 
1. Proxy
2. connect-history-api-fallback (Angular2)

**Comment by unlight** [comment]
3. Provide Api (server) for explicitly call client's refresh (hot and full)

**Comment by nchanged** [comment]
In `1.3.72`
```
const devServer = fuseBox.devServer(">index.ts", {
    port: 8083,
    root : false // if you want to serve "/" by yourself
});
devServer.httpServer.app.use(/* your middleware */)
```

API thingy has been moved to a different issue
