### ISSUE TITLE
Reload the page after custom Sparky.watch

### ISSUE THREAD

**Issue by mkhennoussi** [fuse-box/fuse-box#921]
Hi everyone,

Thanks for this great tool !

Auto-reloading is working great with files in the homeDir folder. But what if I want to watch files not in the homeDir folder and then reload the page ? Is it possible to manually reload the page with the devserver ?

Something like : 
``` 
Sparky.task('watch:site', () => {
  return Sparky.watch('**/*.*', {
    base: './site'
  }).file("*.*", file => {
   // reload the page manually with the devserver
  })
})
```

**Comment by nchanged** [comment]
Hi I think we had a similar feature request somewhere, well keep that in mind for v3

**Comment by ZeroPie** [comment]
+1

**Comment by nchanged** [comment]
```
You can send events from your `fuse.js` to the application by calling:

```
// for the whole page reload
fuse.sendPageReload()

// for the HMR event
fuse.sendPageHMR();
```

**Comment by ZeroPie** [comment]
Still not working.. or at least i could not figure out how.. put it inside the Sparky Task.. no reload after html change. 
Could you post an example?

**Comment by ZeroPie** [comment]
Can you post an example? I did not get it to work.

**Comment by nchanged** [comment]
that was the example. You must upgrade to the latest `next` version. You should have `hmr()` enabled too
