### ISSUE TITLE
Avoid watch triggering initially

### ISSUE THREAD

**Issue by amygdaloideum** [fuse-box/fuse-box#922]
I have the following script to trigger the generation of a template cache:

```javascript
Sparky.task('watch:views', () => {
  return Sparky
    .watch('**/*.view.html', { base: './src' })
    .file("*.*", file => {
      Sparky.start("templates");
    });
})
```
Which works, but when I start my dev-server it triggers the watch on every view file i have in my repository, recreating the cache over a dozen times. Is there anyway to avoid the watch to trigger initially (on files that havent event changed)?

**Comment by nchanged** [comment]
@amygdaloideum you can use just JavaScript ;-) 
```
if(!initial) { }
initial = false
```

**Comment by amygdaloideum** [comment]
```javascript
let initial = true;

Sparky.task('watch:views', () => {
  return Sparky
    .watch('**/*.view.html', { base: './src' })
    .file("*.*", file => {
      !initial && Sparky.start("templates");
      initial = false;
    });
})
```

Is this what you mean? If I write is like this It only skips the first file, and I still have to wait 10+ seconds while it triggers on all the other files. Is there a way to know when all the initial files have triggered? I guess I could use a timeout but that makes me feel kind of dirty.

**Comment by nchanged** [comment]
@amygdaloideum do you feel like making a PR? We could use some help!

**Comment by amygdaloideum** [comment]
@nchanged I might! I will look into it after work! :)

**Comment by nchanged** [comment]
Feel free to re-open it, closing it for now
