### ISSUE TITLE
FuseBoxOptions.package is not typed properly

### ISSUE THREAD

**Issue by RPDeshaies** [fuse-box/fuse-box#923]
The property `package` inside the interface `FuseboxOptions` has the `any` type.

```
export interface FuseBoxOptions {
    homeDir?: string;
    modulesFolder?: string;
    tsConfig?: string;
    package?: any;
    cache?: boolean;
    ...
```

It makes it very difficult to understand since the only place where it seems to be used is here : 

https://github.com/fuse-box/fuse-box-npm-package-seed

**Comment by RPDeshaies** [comment]
Even the doc is not clear, sometime it uses a property called `main` and sometime it uses `entry`

![image](https://user-images.githubusercontent.com/6224111/32457337-c8984f84-c2f6-11e7-9f90-4c868bd60da0.png)

**Comment by nchanged** [comment]
@RPDeshaies do you think you can submit a PR? We can use some help

**Comment by RPDeshaies** [comment]
Sure. I just need to know what are the properties :)

**Comment by RPDeshaies** [comment]
@nchanged also the documentation is not very clear on how to handle the generation of npm packages properly without including dependencies in them

https://github.com/fuse-box/fuse-box-npm-package-seed/issues/3
