### ISSUE TITLE
Line numbers are off with workers

### ISSUE THREAD

**Issue by dakom** [fuse-box/fuse-box#924]
Some sample screenshots below from just `console.log` in a worker:

The console.log() happens at line 57 in the worker, but it's reported as line 48 in Chrome dev tools

sourceMaps === true in the producer config.

![screen shot 2017-11-07 at 13 06 11](https://user-images.githubusercontent.com/6406986/32491390-34c59ebe-c3bf-11e7-8432-1800e9372149.png)
![screen shot 2017-11-07 at 13 24 59](https://user-images.githubusercontent.com/6406986/32491391-34ebbd24-c3bf-11e7-8c4d-cc7f9be25dd5.png)

**Comment by nchanged** [comment]
is it still not working with 3.0?

**Comment by dakom** [comment]
oh, sorry man - I had to move away from FuseBox for now... not setup to test this atm. Looking forward to coming back in the future though!

**Comment by nchanged** [comment]
Moved to another bundler?

**Comment by dakom** [comment]
ya - back to webpack/rollup for now :\

**Comment by nchanged** [comment]
What the reason can I ask you?

**Comment by dakom** [comment]
FuseBox is great! I can't remember now... but I'm sure whatever it was is/will be worked out as it matures.

I think it might have been some hiccups when targeting both a library and an app from FuseBox, and needing source maps through the process, but I'm not sure exactly :\

No doubt I'll switch back at some point :)

**Comment by nchanged** [comment]
Right ) ok yeah sourcemaps for production )
