### ISSUE TITLE
Quantum file mapping

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#927]
* Make an ability to generate the entire file free map in Quantum. 
* Make it possible to use imports using dynamic variables
e.g
```
const req = (path) =>require(path)
req("./something")
```

**Comment by arabsight** [comment]
any progress on this...

**Comment by nchanged** [comment]
No progress yet

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
