### ISSUE TITLE
Import issues

### ISSUE THREAD

**Issue by unlight** [fuse-box/fuse-box#93]
Real Angular code:
```
const routes: Routes = [
    {
        path: 'about', loadChildren: () => {
            return new Promise((resolve, reject) => {
                FuseBox.import('./about.module.js', ({FuseBox}) => {
                    const { AboutModule } = FuseBox.import('./about.module');
                    resolve(AboutModule);
                });
            });
        }
    },
];
```
Build script:
```
fuseBox.bundle('[about.module.ts]')
```
#### 1. FuseBox API is included
How to get rid of it?

#### 2. FuseBox.import() do not emit error
`$async` function where `XMLHttpRequest` is used, `xmlhttp.onerror` is not used when some error happens (for example 404)

**Comment by nchanged** [comment]
1) FuseBox API is included
Remove imports of FuseBox API, it's global.
just use 
`declare const FuseBox : any`
We will fix typings later

2) FuseBox.import() yes that's an issue. Will check it

**Comment by nchanged** [comment]
UPD:
```
FuseBox.import('./about.module.js',(data) => {
})
```
Returns `module.exports` of that FILE, not the fusebox API

**Comment by nchanged** [comment]
`1.3.70` return undefined if a request returns anything else than 200

**Comment by unlight** [comment]
I did not get about issue 1, will it be fixed later? And when `declare const FuseBox : any` will added to contents?
```
FuseBox.import('./about.module.js',(data) => {
})
```
`data` is fusebox, not a `module.exports`
Contents of `about.module.js` http://pastebin.com/fju2KVwM (it fusebox) why it should be `module.exports`
I did not specified any options to exclude fb api.

Config is same as for main (except entry point).
main: `[>main.ts]`
about.module: `[about.module.ts]`

**Comment by nchanged** [comment]
@unlight you don't import FuseBox at any time in your code. I will make a check in AST later to avoid that.

```
FuseBox.import('./about.module.js',(data) => {
})
```

If `about.module.js` is found then you will get whatever that module exports (regular practice).
Based on what you pasted, your code does not have any entry point. First thing off - you should rebundle your `about.module.js` with an entry point.

Cheers
