### ISSUE TITLE
Code Splitting

### ISSUE THREAD

**Issue by leon-andria** [fuse-box/fuse-box#933]
There is a repo here: https://github.com/leon-andria/fuse-zxcvbn
How to make "zxcvbn" module into the bundle "pwd" rather than to the master bundle ?
Making code splitting becomes useless if it goes always to the master bundle.

**Comment by mattoni** [comment]
this is the issue i was having @nchanged, where it renamed it ~lib/main.js

**Comment by nchanged** [comment]
Fixed in 3.0 beta
