### ISSUE TITLE
using import()

### ISSUE THREAD

**Issue by leon-andria** [fuse-box/fuse-box#934]
It seems that the following code 
```
await import("zxcvbn")
```
is transformed to 
```
await import("~/lib/main.js")
```
This is a kind of issue that @mattoni had mentioned last time.
So after a debug, I figure out that "zxcvbn" is a npm module and fuse automatically replace it to the main entry point in the package.json of this module.
For me this is a side effect because the Fuse API Loader is not able to map "~/lib/main.js" when using code splitting.
Either fuse should throw an exception or warning to say that import("xxx") doesn't support with npm module.
If it should be supported, this is a BUG then.

**Comment by leon-andria** [comment]
I forget to mention that if you do a Code-Spitting with bundle name like a npm module, you are dead.

**Comment by nchanged** [comment]
@leon-andria I guess it should have been transformed into `import("zxcvbn/lib/main.js")`
But it won't work I guess, and imports are for dynamic loading, It should automatically split with the new code splitting in 3.0

**Comment by leon-andria** [comment]
Thanks @nchanged 
It's also related to https://github.com/fuse-box/fuse-box/issues/933
We should really tackle this in the 3.0 with a clear path how to make it. Today, the way how the code splitting is executed is so closed in term of implementation and combining with Quantum becomes like we need to be smart and blocking for contribution.
Either you listen my advice or not, trust me, you have to review all of this implementation because it's a nightmare. Full proof of that is that how much time people are blocked or confused with Code-Splitting and Quantum ?
For me, the 3.0 would be a nice catchup to review fusebox API with more transparency, so people can contribute with less technical debts to start with.

**Comment by nchanged** [comment]
@leon-andria I am with the community on this one, you will be able to try out the new smart code splitting soon enough (with `3.0`)
We start with full automation first and then go for customisation.

**Comment by nchanged** [comment]
https://github.com/fuse-box/fuse-box/blob/55bc66b3f756dfe87fc839610fe100e7d4489993/src/tests/dynamic_imports_test/ImportAutoSplitModules.test.ts#L33-L51
