### ISSUE TITLE
Build Quantum multi modules

### ISSUE THREAD

**Issue by Gouigouix** [fuse-box/fuse-box#935]
Hello,

I have test many configurations for isolate multi modules loaded into the same page, without good result! For simplify my current project, I create a simple exemple. 

**You can see it here :** 
https://github.com/orchestra-ts/fuse-box-examples/tree/master/examples/quantum_multi_bundles

Thx for you help.

**Comment by nchanged** [comment]
How about

```
 globals: { default: "myModuleA" },


QuantumPlugin({
      target: "browser",
      uglify: false,
      ensureES5: true,
      bakeApiIntoBundle: "myModuleA",
      containedApi: true
    })
```
You should set `containedApi` true

**Comment by Gouigouix** [comment]
@nchanged @devmondo 

I tested with `FuseBox 3.0.0-next.36` but I have the same problem.
You thinking resolve this issue into FB3 ?

Thank you.

**Comment by nchanged** [comment]
@Gouigouix there is no issue with FuseBox, 99% you configured it wrong ;-)

**Comment by nchanged** [comment]
https://github.com/orchestra-ts/fuse-box-examples/blob/f5b56e55706819c6c036e625d8a97e4738fe17e0/examples/quantum_multi_bundles/fuse_bundleA.js#L11-L15
there is you problem.  You package doesn't match with globals configuration. Make it the same, or simply remove `package ` property it should work

**Comment by Gouigouix** [comment]
@nchanged 

Hello and happy new year 2018...
I fixed an error in the configuration and update to FuseBox v3 ;)
If you want I create a PR for my exemple https://github.com/orchestra-ts/fuse-box-examples/tree/master/examples/quantum_multi_bundles

Very good job for v3 @ all team.
Thank you
