### ISSUE TITLE
hmr() with { reload: true } doesn't reload the page when using JavaScript target

### ISSUE THREAD

**Issue by mrkstwrt** [fuse-box/fuse-box#936]
The following simple config will reload the page when a file is updated:

```javascript
const fuse = FuseBox.init({
  homeDir: 'src',
  output: 'dist/$name.js'
});

fuse.dev({ open: true });

fuse.bundle('app')
  .instructions('> scripts/index.ts')
  .watch()
  .hmr({ reload: true });

fuse.run();
```

However changing the 9th line to (as well as having an `index.js` target):

```javascript
.instructions('> scripts/index.js')
```

Doesn't work as expected, is this by design? This seems to affect the latest beta and 2.4.0

**Comment by nchanged** [comment]
How about adding useTypescriptCompiler option?

**Comment by mrkstwrt** [comment]
Ah yes, that fixed it. Is this feature specific to the Typescript compiler?

**Comment by nchanged** [comment]
well, the problem is that there are no plugins to handles HMR. Usually, either typescript or babel does it. But in this case, there are no plugins at all. (useTypescriptCompiler flag - enables typescript)

**Comment by mrkstwrt** [comment]
I see, that makes sense. Thanks for the speedy reply.
