### ISSUE TITLE
Introducing ts:main in package.json - Ability to publish typescript sources to npm

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#938]
# Available in fuse-box@3.0.0-next.14
Introduce an ability to publish typescript sources to npm. 
Should work in cases:
```
{
 "ts:main" : "src/index.ts"
}
```
As well as

```
{
 "main" : "src/index.ts"
}
```

On top of that,  dynamic `import()` inside these packages should work too.
For example, e if you have a library `hello-world` that lazy loads a package called `foo`, FuseBox should be able to extract that package respecting your `output` config

**Comment by nchanged** [comment]
Typescript package: https://github.com/fuse-box/fuse-ts-raw-package

Usage example: https://github.com/fuse-box/fuse-box-3-preview/blob/master/use-typescript-package/src/index.ts

**Comment by vegarringdal** [comment]
@nchanged very cool
Do the tsconfig need to be same folder as main ?
I kinda like to have that on root of the module package

**Comment by nchanged** [comment]
@vegarringdal you don't need tsconfig.json there, that's the whole point, your local config will deal with it (targets e.t.c)

**Comment by vegarringdal** [comment]
whats added with latest release 3.0.0-next.12 ?
I was able to use a npm module with 3.0.0-next.11 just fine.

**Comment by nchanged** [comment]
You can check the commits after that =) @vegarringdal
