### ISSUE TITLE
Unable to copy assets from `node_modules` to `dist` folder (CSSResourcePlugin?)

### ISSUE THREAD

**Issue by Devgaze** [fuse-box/fuse-box#944]
Hi,

as suggested by @nchanged , I followed [this example](https://github.com/fuse-box/shimming-and-css-example/blob/master/fuse.js), but was unable to get FontAwesome fonts into my `dist` folder using `CSSResourcePlugin`.

I have created this repo [https://github.com/Devgaze/fusebox-example](https://github.com/Devgaze/fusebox-example) which demo the issue.

Thanks for the help!
Alen

**Comment by nchanged** [comment]
Ok, here is a problem.
When you reference an external file within a sass file FuseBox is unable to resolve resources. Simply because it's all inlined.

Here is the config 
```
const fuse = FuseBox.init({
    homeDir: 'src',
    output: 'dist/$name.js',
    cache: false,
    plugins: [
        [ 
          SassPlugin({ importer: true}), 
          CSSResourcePlugin({
             dist: "dist/resources",
             resolve: (f) => `/resources/${f}`
          }), 
          CSSPlugin()
        ],

        [ 
         "*.css",
          CSSResourcePlugin({
             dist: "dist/resources",
             resolve: (f) => `/resources/${f}`
          }), 
          CSSPlugin()
        ],
        WebIndexPlugin({title: 'Welcome to FuseBox', template: 'src/index.html'})
    ]
});
```

`index.ts`

```
import 'font-awesome/css/font-awesome.css'
import './style.scss';
```


So the trick is to load font-awesome via typescript.
