### ISSUE TITLE
BundleProducer overrides NODE_ENV to production

### ISSUE THREAD

**Issue by bigdrum** [fuse-box/fuse-box#950]
This commit seems to force NODE_ENV to production, even if the quantum mode is not used:

https://github.com/fuse-box/fuse-box/commit/e0442c83488a571f0f630c60ed3e5fe8e8076c41

Is this intentional or a bug? We have a build script that will create multiple project which calls Fusebox.init multiple times. It is very surprising that such call changes the environment variable.

**Comment by nchanged** [comment]
@bigdrum that's only for Quantum, it's not affecting development.

**Comment by bigdrum** [comment]
If I'm tracing the logic correctly the `Fusebox.init` calls `new BundlerProducer` in all situation. And BundleProducer has the following statement:

```
public userEnvVariables: any = Object.assign(process.env, { NODE_ENV: "production" });
```
Which will mutate `process.env` as well. Isn't that the case? Let me know if you want an actual test to reproduce this.
