### ISSUE TITLE
allow module aliasing

### ISSUE THREAD

**Issue by pillowsoft** [fuse-box/fuse-box#96]
In Webpack I can have module aliases, like:

`alias: {
      'react-native': 'react-native-web'
}
`

to route all require/import of 'react-native' to 'react-native-web'.  Is there any way to do this in fuse-box?

**Comment by nchanged** [comment]
You can use [shimming](http://fuse-box.org/#shimming) which will work nicely for that case
```
shim : {
   "react-native-web" : { exports : "require('react-native')"}
}
```
You can reference any object `window.ReactNative`, and require function is at your convenience

**Comment by pillowsoft** [comment]
That works!  Thanks!
