### ISSUE TITLE
HMR fails to do anything

### ISSUE THREAD

**Issue by are1000** [fuse-box/fuse-box#960]
Hi! I have created a basic project that uses fuse-box. Bundle gets correctly built, but HMR does absolutely nothing. I think I have followed the docs, but I might missed something, so any help would be appriciated.

### `fuse.js`
```js
const { FuseBox } = require('fuse-box')

const fuse = FuseBox.init({
  homeDir: 'src',
  output: 'public/build/$name.js',
  log: true,
  debug: true
})

fuse.dev({
  root: 'public'
})

fuse.bundle('app').watch('src/**').hmr({ reload: true }).instructions('> index.js')

fuse.run()
```
### `src/index.js`
```js
document.write('Hello there.')
document.write('foo bar baz') // added after starting the web server
```

### Network tab <small>after saving the file few times</small>

![](https://i.imgur.com/8grceRa.png)

There are no errors in the console.
```
Connecting to fusebox HMR at ws://localhost:4444
Connected
```

### Project structure
![](https://i.imgur.com/RUTwhe3.png)

(Removing `.fusebox` and `node_modules`, reinstalling and restarting doesn't solve the issue)

**Comment by are1000** [comment]
I just found #936 but it touches only on `.hmr({ reload: true })`. Without it still nothing changes.

**Comment by nchanged** [comment]
@are1000 
`.watch('src/**')`

Should be just `watch()` 

Besides, you don't have any transpilers enabled. 
add [useTypescriptCompiler](http://fuse-box.org/page/configuration#usetypescriptcompiler) That will setup the basics

**Comment by are1000** [comment]
I did that and it works :tada:, but why is transpiler required? Also, there is nothing in the HMR docs that say it is required, maybe thats where my confusion comes from?

**Comment by nchanged** [comment]
@are1000 we will update the docs, of course.
You would need a typescript compiler to control script target, for example. Because FuseBox will use it anyway, to match the level, read up on [here](https://github.com/fuse-box/fuse-box/blob/doc-ver-3/docs/useful.md#understanding-targets-and-script-levels)

TypeScript and Babel both have their own logic on triggering the HMR
