### ISSUE TITLE
Glob not working as expected

### ISSUE THREAD

**Issue by Devgaze** [fuse-box/fuse-box#963]
Following regex does not work as expected
```
Sparky.task('fa-woff', () => Sparky.src('node_modules/font-awesome/**/*.(woff|woff2)').dest('dist/fonts/$name'));
```
but when you split it in two, it works fine
```
Sparky.task('fa-woff', () => Sparky.src('node_modules/font-awesome/**/*.woff').dest('dist/fonts/$name'));
Sparky.task('fa-woff2', () => Sparky.src('node_modules/font-awesome/**/*.woff2').dest('dist/fonts/$name'));
```

**Comment by nchanged** [comment]
@Devgaze I think we've figured it out. You should add `exec()` for every procedure you define

**Comment by Devgaze** [comment]
I thought this was just a workaround!?

The thing is [documentation](http://fuse-box.org/page/sparky#source) says we can use glob patterns with `Sparky.src` (as shown in the docs)
```
Sparky.src("src/**/*.(jpg|png|gif))")
```
Unless I'm missing something here, it seems to me described behaviour looks like a bug. 

Am I wrong here?

**Comment by devmondo** [comment]
@Devgaze your syntax should work i have similar one and it works
`Sparky.watch(["./src/client/**/*.+(html|css)", "./src/shared/**/*.+(html|css)"])`

I see you have extra parenthesis after `gif`!

**Comment by Devgaze** [comment]
@devmondo actually double parenthesis is a typo from FuseBox website, my code snippet is described in the opening comment. Try this line in any of your projects

```
Sparky.task('fa-woff', () => Sparky.src('node_modules/font-awesome/**/*.(woff|woff2)').dest('dist/fonts/$name'));

```

**Comment by Devgaze** [comment]
@devmondo you are genius - look at that `+` sign in your example 😎

**Comment by Devgaze** [comment]
feel free to close this one

**Comment by devmondo** [comment]
@Devgaze  hahahah glad it worked ;)
