### ISSUE TITLE
LessPlugin + PostCSSPlugin breaks HMR

### ISSUE THREAD

**Issue by ccapndave** [fuse-box/fuse-box#965]
I have a less entry file called `app.less` that imports other less files:

```less
@import "components/login.less";
```

If I have the following plugin chain:

```ts
[
  LESSPlugin(),
  CSSPlugin()
]
```

then HMR works fine.  If, however, I add in PostCSS:

```ts
[
  LESSPlugin(),
  PostCSSPlugin(),
  CSSPlugin()
]
```

then HMR doesn't work anymore (notice this happens when not using any actual PostCSS plugins).  I've had a look at #723 and set the path to my stylesheets (although they are all relative to the entry CSS), but that didn't seem to help either.

```ts
[
  LESSPlugin(),
  PostCSSPlugin({ paths : [ path.resolve(__dirname, "app/style" )] }),
  CSSPlugin()
]
```

Note that the behaviour is that when I update `login.less`, Fusebox console displays:

```
  → CSS Dependency: style/components/login.less depends on style/app.less
10:12:06: Source changed for style/app.less
```

and then the browser displays:

```
update "style/app.less"
```

and the page flashes briefly, but the actual change isn't applied.  If I remove the `PostCSSPlugin` from the chain again exactly the same thing happens, but this time the change is applied.

**Comment by nchanged** [comment]
@ccapndave can you reproduce the issue in a repository?

**Comment by ccapndave** [comment]
https://github.com/ccapndave/fuse-box-965

If you comment and uncomment the line at https://github.com/ccapndave/fuse-box-965/blob/master/fuse.ts#L10 you can see the issue happening and not happening.
