### ISSUE TITLE
ReplacePlugin is too naive

### ISSUE THREAD

**Issue by dzek69** [fuse-box/fuse-box#967]
The implementation of ReplacePlugin is very simple and has few lines only, it's just taking the keys from provided object and replacing that in the code directly, without analyzing the context.

I see three different cases when it's going to make a trouble:

1) We want to replace `$version` with `1.0.1`. We have an app that renders HTML on server and wants to expose that to client, so the code contains:
```javascript
res.send(head + "<script>window.$version = '" + $version + "';</script> + footer);
```
The whole thing now becomes:
```javascript
res.send(head + "<script>window."1.0.1" = '" + "1.0.1" + "';</script> + footer);
```
2) We want to replace `process.env.NODE_ENV` variable in such code:
```javascript
send("this line is soo long i'm gonna split it randomly, because I like and I can, and NODE ENV is " + process.env.
    NODE_ENV + " k thx bye");
```

3) We have `NODE` (path to node binary) and `NODE_ENV`  environment variables. We wan't to replace them both in this code:
```javascript
send(NODE)
send(NODE_ENV)
```
but `Object.keys` returned `NODE` before `NODE_ENV`, so the result becomes:
```javascript
send("/usr/bin/node");
send("/usr/bin/node"_ENV);
```

1) Will crash
2) Will not replace (and we may miss that - it may be even important security issue)
3) Will crash

I don't know how webpack behaves before someone ask. I just noticed issue number 3, so I examined ReplacePlugin code.

3 is easy to fix (reverse alphabetical ordering before applying)
2 and 1 will require a parser, not a regexp

Some information is needed - do we need to fix these ? How? Or maybe just a note in docs is acceptable solution?

**Comment by nchanged** [comment]
@dzek69 use `process.env.version`
Read up [here](http://fuse-box.org/page/quantum#dead-code-elimination), don't use ReplacePlugin
