### ISSUE TITLE
Escaped newlines are being added as Unescaped newlines

### ISSUE THREAD

**Issue by cryptoquick** [fuse-box/fuse-box#968]
Escaped newlines `\n` are being added as unescaped newlines throughout the resulting bundle.

The project is open source and can be found here:

https://github.com/arcjet/arcjet

Fusebox config is in:

https://github.com/arcjet/arcjet/blob/master/src/build.ts

You can test it by installing with `yarn`, then `yarn build`, then `yarn test-bin`.

**Comment by nchanged** [comment]
@cryptoquick Hi
I can't check it right now, but I did check your config
1) Get rid of TypescriptHelpers (it's removed from 3.0 in favour of tslib
3) install the latest 3.0 beta (it will automatically create tsconfig with the required configuration

**Comment by cryptoquick** [comment]
Thanks for the quick response. I will do what you recommended. I actually found the issue, it's related to my shell script I run on build, not the actual build tool itself. Removing this code makes it work:
`echo \"#!/usr/bin/env node\n$(cat bin/arcjet.js)\" > bin/arcjet.js`
Unfortunately, the shebang has to be added manually. Will look into solutions.
