### ISSUE TITLE
Allow to able to specify custom package name with dynamic module

### ISSUE THREAD

**Issue by leon-andria** [fuse-box/fuse-box#97]
https://github.com/fuse-box/fuse-box/blob/master/src-frontend/FuseBox.ts#L463

By default, it's always default, it should be good that we can specify our custom package name.
I would see this in the third parameter with deffault value as 'default' :-)

**Comment by nchanged** [comment]
Dynamic modules work only for the "default" package. And changing a [package name](http://fuse-box.org/#package-name) should work in case you are planning to publish your bundle.

**Comment by leon-andria** [comment]
Maybe, i didn't explain very well my request.
Your answer is write but it's not what i intend to do.
Let's take the following scenario:
1. I publish a documentation website
2. my documentation website allows End-Users interactive "Coding"
3. to make my sampling working, i will probably package my bundle with 'default" (it makes sense right ?)
4. but this become dangerous if i allow my End-Users to write code that might override my own stuff by using dynamic module
5. when he register his code with dynamic module, i want to specify another package name like 'interactive' rather than 'default'
6. package name here is like a namespace to isolate your code versus external dynamic module interactive

**Comment by nchanged** [comment]
I see the point, My suggestion would be:

`FuseBox.dynamic("test/foo.js", "console.log(1)")` registers in "default"

`FuseBox.dynamic("interactive", "test/foo.js", "console.log(1)") ` registers in "interactive"

**Comment by leon-andria** [comment]
Yes, to keep Api compatibility, as i said in my first post, put it in the third parameter.

Tks this will be awesome... sorry its already :-)

**Comment by nchanged** [comment]
Oh man, sorry forgot to comment, I did it pretty much [right away](https://github.com/fuse-box/fuse-box/blob/master/test/dynamic_modules.js#L129) =)

**Comment by leon-andria** [comment]
Thanks for this but you didnt listen what i said.
If you put the package name at the first parameter, you are doing a breaking change in the Api because people already use it and me too.
If we dont know what has been changed in the change logs, believe me people will complain.
This kind of details, we are taking of because we can lose hour to find out why it doesnt work with a new update of fuse. And may lose trust...

**Comment by nchanged** [comment]
What's wrong with you man?
You think I would break the API?
It won't break anything.  [here](https://github.com/fuse-box/fuse-box/blob/master/test/dynamic_modules.js#L116) and [here](https://github.com/fuse-box/fuse-box/blob/master/test/dynamic_modules.js#L116)

**Comment by leon-andria** [comment]
There is nothing wrong. I just warm you that in term api design its weird.
You make familiar with 2 params and if it's 3 params the first param it means another thing.
Believe me this we dont lesrn api like this. Tomorrow there is anothet param, you are going to check if there is 2 params?
This logic become yours but thing for people who contribute, they will not have the full picture.
Now up to you to take my advise :-)

**Comment by nchanged** [comment]
there can't be more than 3 params. And in fact, 3 params are not documented yet, and not breaking anything.
[here](https://github.com/fuse-box/fuse-box/blob/master/src-frontend/FuseBox.ts#L462)

**Comment by nchanged** [comment]
For example in `mongodb` it's quite a regular practice. But I agree partialy, i can introduce an additional method later or.

**Comment by leon-andria** [comment]
I wont be fast to say that, you never know....

**Comment by nchanged** [comment]
Ok, then can u wait, I could come with an alternative solution with props

**Comment by leon-andria** [comment]
Designing api is not easy but what is really important is to think about the primary goal.
Here we want to import code and package is like optional because we yse default in case.
But the main question is that protected your default package is more important in term of isolation or not. What i want to say is that your design is drived but some requirements.
Now, think now you want to introduce these requirements:
1. Allow to import multiple codes rather than calling multiple times import ( accepting an Array?)
2. Based on req. 1, i want to lock this package for security reason, no one can add code in this package ... security security....
3. Package should be locked from his owner or design choice...

You see, there are plenty of things... we need to embrace our imagination :-)

**Comment by devmondo** [comment]
that is why i favor arguments destructure over this style as no matter how many params you add in future it wont break the api.

**Comment by nchanged** [comment]
JavaScript can be broken regardless of your lock, cuz it's just a JavaScript variable. Nothing bad happens unless your server has a breach, so keep that in mind. Browser are pretty secure.

**Comment by devmondo** [comment]
@leon-andria 
can you explain what do you mean by security ?

**Comment by leon-andria** [comment]
Imagine that you distribute a package bundled with fuse and it has licensing model.
I know where is the module located, and i use import. This means that i hacked someone package. This means security issues from fuse. We should prevent to this when we build api.
Locking a package to be modify on runtime is needed.....

**Comment by nchanged** [comment]
@leon-andria i can open my online bank, find a method that renders the amount of my money and add 5 zeros there. It does not mean that I hacked it. I can do everything from developer's console. There is no security issues with Fuse, nor with JavasScript.

>>Locking a package to be modify on runtime is needed.....

That means I just hacked google, and made it draw dicks =)

**Comment by leon-andria** [comment]
I think you just forget what you own tool aims to: bundling. This means that i can distribute packages that enterprises can use this package as a library. I'm building a software and i want to protect a little bit my IP. A developper import my lib and just behind he does a dynamic import to ovewrite some module of my lib. Maybe you dont care but as an enterprise i care.
Think it like this, with fuse you make a bundle and trust me, you can make it like a voodoo for substitution like stub or mocking features.
Remember, power means responsibilities...

**Comment by nchanged** [comment]
Ok in `1.3.77` in has been changed:

```
FuseBox.dynamic("hello/world.js", "module.exports = {hello : 'world'}", {pkg : 'foo'})
```
