### ISSUE TITLE
~/component-indexof.js not found on request (ANTD)

### ISSUE THREAD

**Issue by illumen** [fuse-box/fuse-box#971]
Hi!

I'm getting an error when I try to use [antd 3.0.0](https://github.com/ant-design/ant-design/) with fuse-box. It seems like "component-classes" (component-indexof.js) is the culprit but I can't seem to figure out why...

It's a dependency of "rc-select" and gets required like this:
```javascript
FuseBox.pkg("component-classes", {}, function(___scope___){
___scope___.file("index.js", function(exports, require, module, __filename, __dirname){

try {
    var index = require('~/component-indexof.js');
} catch (err) {
    var index = require('component-indexof');
}
```

While bundling I get the following error:

>  → WARNING Statement "component-indexof.js" has failed to resolve in module "component-classes"
>  → WARNING The contents of C:\Development\sse\flow\node_modules\antd\package.json weren't loaded. Missing a plugin?

and my fuse config is:
```javascript
const {
  FuseBox,
  EnvPlugin,
  SVGPlugin,
  CSSPlugin,
  BabelPlugin,
  QuantumPlugin,
  WebIndexPlugin,
  Sparky
} = require("fuse-box");

let fuse, app, vendor, isProduction;

Sparky.task("config", () => {
  fuse = new FuseBox({
    homeDir: "src/app",
    sourceMaps: !isProduction,
    hash: isProduction,
    target: "browser",
    output: "dist/$name.js",
    useTypescriptCompiler: true,
    experimentalFeatures: true,
    useJsNext: ["antd"],
    polyfillNonStandardDefaultUsage: true,
    plugins: [
      EnvPlugin({ NODE_ENV: isProduction ? "production" : "development" }),
      SVGPlugin(),
      CSSPlugin(),
      WebIndexPlugin({
        template: "src/app/index.html"
      })
      /*isProduction &&
        QuantumPlugin({
          target: "browser",
          treeshake: true,
          uglify: false
        })*/
    ]
  });
  // vendor
  vendor = fuse.bundle("vendor").instructions("~ index.tsx");

  // bundle app
  app = fuse.bundle("app").instructions("> [index.tsx]");
});

Sparky.task("default", ["clean", "config"], () => {
  fuse.dev();
  // add dev instructions
  app.watch().hmr();
  return fuse.run();
});

Sparky.task("clean", () => Sparky.src("dist/").clean("dist/"));
Sparky.task("prod-env", ["clean"], () => {
  isProduction = true;
});
Sparky.task("dist", ["prod-env", "config"], () => {
  // fuse.dev();
  return fuse.run();
});
```

Thanks for any help.

**Comment by nchanged** [comment]
@illumen 
1) `component-indexof` is not bundled for some reason. 
2) `~/component-indexof.js` Points to the root of the project
3) You need to add `JSONPlugin`

**Comment by cpunion** [comment]
Same here.

If I remove following lines of `component-classes/package.json`, it works fine. (https://github.com/component/classes/blob/master/package.json#L15-L17)

```json
  "browser": {
    "indexof": "component-indexof"
  }
```

@nchanged Is that wrong? I guess it means pointing to `component-indexof` package.

**Comment by nchanged** [comment]
Yes that’s an override

**Comment by fraherm** [comment]
I ran into the same issue. Is there a good way to override the browser field for `component-classes`?

**Comment by nchanged** [comment]
yeah, the problem is it doesn't throw an exception. What you can do it set an alias that would point it to a correct package.

**Comment by fraherm** [comment]
Sorry, but I think I do not completely grasp the issue. I tried to set an alias for fuse-box which still resulted in the same issue. As far as I understand, `component-index` should be loaded whenever `indexof` is required.

```
alias: {
    'indexof': '~/node_modules/component-indexof/index',
  }
```
Can you tell me why it isn't working?

**Comment by nchanged** [comment]
Should be like this:
```
alias: {
    'indexof': 'component-indexof/index',
  }
```

**Comment by fraherm** [comment]
Sorry for bugging you with my problem. Now I do not receive the warning for the build process anymore but I still get it in the browser.
```
~/component-indexof.js not found on request
```
Do you maybe know why?

**Comment by nchanged** [comment]
that's probably because it's in `try catch` statement, maybe `npm install component-indexof` will help?

**Comment by fraherm** [comment]
`npm install component-indexof` didn't help either. At least `component-indexof` is used in only two components. 😄 
With tree shaking I don't have any problems because I don't need those two components.

**Comment by nchanged** [comment]
So it sorts out by itself in the production build? I am uncertain about throwing an expection for now...

**Comment by xaviergonz** [comment]
I had that with rc-slider and fixed this with something like this
```
    alias: {
      '~/component-indexof.js': 'component-indexof' // just to avoid some stupid issue with rc-slider
    }
```

**Comment by fraherm** [comment]
@xaviergonz That fixed it for me too. 👍 Thanks for posting your solution.
I think this issue can also be closed now.

**Comment by nchanged** [comment]
Awesome!

**Comment by Relaxe111** [comment]
I have same import issue but with component-classes i get: 
![image](https://user-images.githubusercontent.com/40892030/81263266-a8f21c00-903f-11ea-8ee0-fc9d9ed0ee33.png)
I've tryed to add:
alias:{
     'classes':'component-classes/index'
}
and get:
![image](https://user-images.githubusercontent.com/40892030/81263518-1605b180-9040-11ea-9d65-3750da27f4a6.png)
on last suggested solution i get same error as initially.

**Comment by Relaxe111** [comment]
I found out that component-classes tryinig to import index of or classes-index.of 
![image](https://user-images.githubusercontent.com/40892030/81264793-56662f00-9042-11ea-8fe8-bbe3dc7e959a.png)
