### ISSUE TITLE
Question: How to auto-reload browser on html change?

### ISSUE THREAD

**Issue by KatSick** [fuse-box/fuse-box#977]
My fuse.js config

```js
const { FuseBox, WebIndexPlugin, SassPlugin, CSSPlugin } = require('fuse-box');
const fuse = FuseBox.init({
  homeDir: 'src',
  output: 'dist/$name.js',
  plugins: [WebIndexPlugin({ template: 'src/index.html' }), [SassPlugin(), CSSPlugin()]]
});

fuse.dev();
fuse
  .bundle('app')
  .hmr({ reload: true })
  .watch('**/*')
  .instructions(`>index.ts`);

fuse.run();
```

My project structure is

```
- fuse.js
-- index.html
-- index.ts 
```

I changing HTML file, but browser does not reloaded

**Comment by devmondo** [comment]
because your html page is not part of the bundle, ( i think we should add this option to webindex plugin to watch the template if it changes)

you could work around this now by doing this

```js

const { FuseBox, WebIndexPlugin, SassPlugin, CSSPlugin } = require('fuse-box');
const fuse = FuseBox.init({
  homeDir: 'src',
  output: 'dist/$name.js',
  plugins: [WebIndexPlugin({ template: 'src/index.html' }), [SassPlugin(), CSSPlugin()]]
});

fuse.dev();
const clientBundle = fuse
  .bundle('app')
  .hmr({ reload: true })
  .watch('**/*')
  .instructions(`>index.ts`);

Sparky.task("watch:html", () => {
    //  return Promise.resolve()
    return Sparky.watch([`./index.html`])
           .completed(() => {
            clientBundle.exec();
        });
});

Sparky.task("default", [`&watch:html`], () => {
    fuse.run();
});

```

notice that we run `clientBundle.exec();` when sparky task detects change.

hope this helps :)

**Comment by KatSick** [comment]
@devmondo 

Unfortunately this does not work :(

<img width="1016" alt="screen shot 2017-12-07 at 16 05 38" src="https://user-images.githubusercontent.com/13982649/33719158-8837de52-db68-11e7-8257-793a6bf62799.png">

**Comment by KatSick** [comment]
All up and running, but browser does not reloaded after index.html changes

**Comment by devmondo** [comment]
@KatSick could you change the globbing to 
```js
Sparky.watch([`./client/**/*.html`])
```
it works perfectly on my side

**Comment by ZeroPie** [comment]
Can confirm this issue. Workaround does not work on my side either.

**Comment by nchanged** [comment]
I will take a look

**Comment by ZeroPie** [comment]
Anything new? :D

**Comment by nchanged** [comment]
You can send  a special event to trigger full HMR or a page reload
fuse.sendPageReload if I am not mistaken

**Comment by nchanged** [comment]
Can be done using this option 
https://fuse-box.org/page/development-server#send-events

**Comment by ZeroPie** [comment]
can someone please paste a running example: 
fuse.sendPageHMR(); is not a function
fuse.sendPageReload(); is not a function

**Comment by nchanged** [comment]
@ZeroPie https://github.com/fuse-box/fuse-box-examples/tree/master/examples/manual-page-reload

**Comment by laekem34** [comment]
Hello Katsik,

I tried this and it worked for me
in fuse.js

add a property 'fuse' to the object:
```
context({
  isProduction: false,
  fuse: null,     <-- here
  getConfig() {
    return FuseBox.init({
      homeDir : "./src",
   // etc
```
then add this task: 
`task("watch:index", (context) => watch(['src/**.*']).file("*.html", () => context.fuse.sendPageReload()))`

then in your default task assign fuse configuration to fuse property and start the watch task:
```
task("default", ["clean", "copyStatic"], async (context) => {
  const fuse = context.getConfig();
  context.fuse = fuse

  fuse.dev({open: true});
  context.createAppBundle(fuse);

  exec("watch:index")
  await fuse.run();  
});
```

Is it working for you ?
