### ISSUE TITLE
Fusebox 3.0 and sourcemaps

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box#978]
Hi

Been using FB 3 beta a few weeks now, love it
But sourcemaps is sometimes out of sync
@nchanged You said it was prb alias doing it on gitter, could be something else too. if I see it in projects not using alias I will update post

![image](https://user-images.githubusercontent.com/2901416/33736941-d1c712d2-db94-11e7-836e-a06f9f320df6.png)

![image](https://user-images.githubusercontent.com/2901416/33736962-e151bd74-db94-11e7-8acd-694e60eda13d.png)

**Comment by nchanged** [comment]
Can u confirm that the file contains aliases

**Comment by vegarringdal** [comment]
Its importing from alias module on the to, 
Decorators and interface is the alias module
this you wanted

**Comment by nchanged** [comment]
@vegarringdal @matthiasak @mattoni `fuse-box@3.0.0-next.34` Please verify the fix ;-)

**Comment by vegarringdal** [comment]
@nchanged 

Looking very good on my last issue
Thank you :-)
Ill report back on this if I run into new issues

![image](https://user-images.githubusercontent.com/2901416/33854489-30623bc0-dec2-11e7-9a0c-bdb7b7dbb200.png)

**Comment by matthiasak** [comment]
Looking strong, here!

**Comment by nchanged** [comment]
I will close this one now ;-) Happy to hear it works ;-)

**Comment by vegarringdal** [comment]
@nchanged Thanks again, keep up the good work :-)
