### ISSUE TITLE
CSSResourcePlugin not working with border-image declaration

### ISSUE THREAD

**Issue by wrench7** [fuse-box/fuse-box#980]
I'm specifying a a `border-image` with a url and it's not getting picked up by the CSSResourcePlugin.

Adding `declaration.prop.indexOf("border-image") > -1` to the following line of code would fix this issue.

https://github.com/fuse-box/fuse-box/blob/4761af96cd8405f413af5b518c722b89546c537b/src/lib/postcss/PostCSSResourcePlugin.ts#L23

**Comment by nchanged** [comment]
@wrench7 I would appreciate if you submitted a PR, please.
