### ISSUE TITLE
TypeError: require(...) is not a function . . .

### ISSUE THREAD

**Issue by challenger532** [fuse-box/fuse-box#986]
I'm getting this error:

`path/to/projct/react/react-skeleton/build/ssr/development/bundle.js:7624     require("./streams")(iconv);                         ^ TypeError: require(...) is not a function . . .
`
babel plugin configuration:
```
let  babelPresetEnv = [
  'env',
  {
    targets: {
      browsers
    },
  }
]

_.BabelPlugin({
  config: {
    sourceMaps: true,
    presets: ['react', 'stage-0', babelPresetEnv],
    plugins: [
      'babel-plugin-transform-decorators-legacy',
      'babel-plugin-transform-class-properties',
      'babel-plugin-transform-object-rest-spread',
      'babel-plugin-transform-es2015-spread',
      'babel-plugin-transform-object-assign'
    ].map(require.resolve)
  }
})
```

**Comment by nchanged** [comment]
@challenger532 have you considered using http://fuse-box.org/page/configuration#usetypescriptcompiler  instead of babel?

That means that `./streams` returns nothing.  Could be for multiple reasons. Babel + webpack specific? Try using typescript compiler instead of Babel,

**Comment by challenger532** [comment]
@nchanged I just did, it worked building the script, thanks for the ` typescript compiler ` it's great... but I still have the same error...

**Comment by challenger532** [comment]
I downgraded express to the version: `"express": "4.15.4",` this fixed it!
