### ISSUE TITLE
Problems using Node APIs in Electron renderer

### ISSUE THREAD

**Issue by jollytoad** [fuse-box/fuse-box#989]
I'm attempting to use fuse-box (2.5.0-beta.1) to bundle the renderer side of my Electron app, which makes use of the native Node modules available in the environment, ie, path, fs, etc.

Even after setting `target: 'electron'` these modules are empty.

I've read through a lots of issues here on this matter, eg. `serverBundle` option - which appears to have been removed now, and looked through the codebase, the way that these modules check `FuseBox.isServer`, and that `FuseBox.isServer = !isBrowser`

It seems to be that the most obvious fix for this is to have both FuseBox.isBrowser & FuseBox.isServer set to true for the 'electron' target. Unless isServer has some deeper meaning that i've not discovered yet.

If you agree with this course of action i'd be happy to experiment, test, and submit a PR - or any other suggestions?

**Comment by nchanged** [comment]
hi @jollytoad 
Thanks for submitting ;-). Let's determine first the cause of the issue. Maybe you could create a repository which reproduces the bug? and we could move forward after that.

And please, use the latest `fuse-box@next`

**Comment by jollytoad** [comment]
Hmm, seemed to be a configuration issue, coming from an ejected 'create-react-app', after stripping out old configs and restarting with something more like the fuse-box-electron-seed project i'm having more luck.

**Comment by nchanged** [comment]
@jollytoad there still an issue with server polyfill, this will be fixed soon enough ;-)
