### ISSUE TITLE
ScriptTarget ESx/ESyyyy aliases are wrong

### ISSUE THREAD

**Issue by jollytoad** [fuse-box/fuse-box#990]
The aliases from ES(edition) to ES(year) are mismatched

Should be:
ES6 = ES2015  (ie. 6th editor is ES2015)
ES7 = ES2016
ES8 = ES2017

This enum is wrong:

```
export enum ScriptTarget {
    ES5 = 1,
    ES2015 = 2,
    ES2016 = 3,
    ES6 = 3,
    ES2017 = 4,
    ES7 = 4,
    ESNext = 5
}
```

should be:

```
export enum ScriptTarget {
    ES5 = 1,
    ES2015 = 2,
    ES6 = 2,
    ES2016 = 3,
    ES7 = 3,
    ES2017 = 4,
    ES8 = 4,
    ESNext = 5
}
```

**Comment by jollytoad** [comment]
Probably best to not have ES8 (and discourage use of ES6/7 in favour of year)

https://www.typescriptlang.org/docs/handbook/compiler-options.html lists...

ES5 
ES6 
ES2015 
ES7 
ES2016 
ES2017 
ESNext

**Comment by nchanged** [comment]
Good catch! @jollytoad could you submit a PR? (you can include es8) And the docs too, I would appreciate it greatly.
Thanks
