### ISSUE TITLE
Decorators not handled

### ISSUE THREAD

**Issue by Cyberlane** [fuse-box/fuse-box#991]
Sample project can be found here: https://github.com/Cyberlane/fusebox-test

It currently fails on both Linux and Mac, with the following error:

![image](https://user-images.githubusercontent.com/1614416/34303411-70358952-e735-11e7-8f58-506af8afddec.png)

**Comment by nchanged** [comment]
@Cyberlane 
You can't use `modulesFolder` pointed to `src`. It's not webpack, use aliases instead. And fix you target, it's not server, it's browser.

```
const {
  FuseBox,
  SassPlugin,
  CSSModules,
  CSSPlugin,
  WebIndexPlugin,
} = require('fuse-box');

const fuse = FuseBox.init({
  target: 'browser@es5',
  homeDir: 'src',
  output: 'dist/$name.js',
  alias : {
    "decorators" : "~/decorators"
  },
  useTypescriptCompiler : true,
  plugins: [
    WebIndexPlugin({ template: 'public/index.html' }),
    [SassPlugin(), CSSModules(), CSSPlugin()],
  ],
});

fuse.dev();
fuse.bundle('app')
  .hmr()
  .watch()
  .instructions('>index.js');

fuse.run();
```
