### ISSUE TITLE
Calling sparky.watch with a parent base directory

### ISSUE THREAD

**Issue by RobbertWolfs** [fuse-box/fuse-box#995]
Is it possible to call `sparky.watch` (to copy my assets) with a parent base directory?

```
Sparky.task("watch-assets", () => Sparky.watch("./assets/*.png", { base: '../src/' }).dest('../dist'));
```

If I put my `fuse.js` file in the root and use it like the example on the site, it works..
But  when I try to put my `fuse.js` file in a subdirectory and then change my base path (see example above).. but then it won't copy my assets 👎 

Any suggestions?

**Comment by nchanged** [comment]
@RobbertWolfs i guess `"./assets/*.png"` is still pointing to your sub folder, ignore `base`. I think you have found a bug ;-)

**Comment by RobbertWolfs** [comment]
Hmm oke.. 

If I have time tonight I will see if I can find the bug

**Comment by RobbertWolfs** [comment]
@nchanged PR is created 👍 
All tests have passed

**Comment by RobbertWolfs** [comment]
There wasn't a test for the watch base property I think?
