### ISSUE TITLE
CSSModules generates different hash when creating two bundles at once

### ISSUE THREAD

**Issue by dzek69** [fuse-box/fuse-box#997]
This is a summary of what I've reported on gitter.

Comparing to 2.5.0 beta.1 current version (3.0.0 beta.44) Fusebox now forces `generateScopedName` option being passed to `postcss-modules` by doing this:
```javascript
generateScopedName: this.scopedName ? this.scopedName : '_[local]___[hash:base64:5]'
```

And there are two issues with that:
1) I may actually want to leave it undefined, so `postcss-modules` will keep its default behavior

2) when `generateScopedName` is a string and uses `hash` - the hash will be calculated different if two bundle are created in the same process

Why?
`postcss-modules` are using `generic-names` to generate the hash and uses `filename` for that.

But files seems to be passed to `postcss` as content strings not filenames:
```javascript
return postcss([
    require('postcss-modules')({ /* options */ })
]).process(file.contents, {})
    .then(result => {
        file.contents = result.css;
        return resolve();
    });
```
This causes filenames inside `generic-names` to be visible as: `<input css 1>` `<input css 2>` ... `<input css 13>` and so on.

So when I'm making first bundle - my file will get `<input css 1>` as a base for hash generating, but when second bundle is made - it will pass the same css contents again and will result with `<input css 14>` as filename.

So the hashes will be different.

**Comment by nchanged** [comment]
@dzek69 could you suggest a fix?

**Comment by henrinormak** [comment]
@nchanged what if the postcss usage in CSSModules plugin would feed in the file path as the from option?

```
return postcss([
    require('postcss-modules')({ from: file.absPath })
]).process(file.contents, {})...
```

In my local test, this seems to produce stable hashes for same files/classes.

**Comment by nchanged** [comment]
We can try that! Can you open a PR?
