### ISSUE TITLE
TypeScriptHelpers is not a function

### ISSUE THREAD

**Issue by osdevisnot** [fuse-box/fuse-box#998]
On the travis build and locally, I am getting strange error which seems to be related to fuse-box:

![image](https://user-images.githubusercontent.com/802242/34466347-9142cab6-eef5-11e7-8127-f0dbda6ae2d5.png)

Here is a repro repository -- https://github.com/osdevisnot/hyperapp-fusebox

Any pointers on what can fix this?

**Comment by Shepless** [comment]
I believe Typescript helpers have been deprecated now.

**Comment by devmondo** [comment]
as @Shepless mentioned, it is deprecated now, the official recommended approach is to use tslib.

you can get full info here https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html

scroll to Support for external helpers library (tslib).

let us know otherwise.
